### ISSUE TITLE
Дублікація відповідей в замоника у тендері, після переходу тендера зі статусу "Період уточнень" у статус "Учікування пропозицій".

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#100]
Дублікація відтворюється тільки в тендері замовника, у тендері учасників - дублікації немає.

![doublication_questions](https://cloud.githubusercontent.com/assets/10761162/6190897/f9f877ee-b3ad-11e4-9fcf-601440f1dc82.png)

**Comment by S-Shevchenko** [comment]
Спасибо,есть такая задача в работе.

**Comment by S-Shevchenko** [comment]
не воспроизводиться.

**Comment by lerich** [comment]
Закриваю.
