### ISSUE TITLE
E-Auction: Неможливо видалити прикріплений файл під час подачі пропозиції.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1001]
**Лінк:** http://e-auction.pro/#/

**Передумови:** 
o Ліквідатор створив аукціон, 
o Учасник зареєстрував пропозицію на суму ХХ, додав Документ1, Документ2. 
o Модератор акцептував пропозицію учасника 

**Кроки:** (Виконуються учасником)
1. Відкрити сторінку Аукціону
2. Спробувати видалити прикріплений до пропозиції Документ1.

**Фактично:** На місце Документу1 можна завантажити якийсь інший документ, проте повністю видалити його не можна: відсутній функціонал видалення (х). 

**Очікувано:** Наявність функціоналу видалення документів (х).

**Comment by oleksandrakulenko** [comment]
Це коректна поведінка, прохання закрити баг

"У випадку помилкового завантаженого документу користувач може змінити цей документ" - в сценаріях ручних тестів це відображено

"У випадку зміни документу, стара версія на сайтах майданчиків відображається перекресленою"

https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#
