### ISSUE TITLE
UACE: Чекбокс "Запам'ятати мене" при авторизації не змінює налаштування cookie

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1002]
**Кроки відтворення:**
1. Зайти на сайт http://test-eauction.uace.com.ua/
2. Ввести імейл, пароль
3. Обрати чекбокс "Запам'ятати мене"
4. Натиснути кнопку "Вход"
5. Перевірити налаштування cookie

**Очікуваний результат:**
Cookie має мати значення у полі "Expires / Max-Age" у майбутньому, не на сесію. 

**Актуальний результат:**
Cookie виставляється тільки на сесію без огляду на чекбокс "Запам'ятати мене"

**Comment by oleg4646** [comment]
Там iнший принцип роботи.  Розробник сам визначае як органiзовувати процес.
