### ISSUE TITLE
Zakupki: Після заміни документа, старий документ не відображається перекресленим.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1004]
**Лінк:** http://devsale.zakupki.com.ua
**Передумови:** Є створений аукціон.
**Кроки:**
1. Залогінитись , як організатор (логін: likvidator1@example.com).
2. Перейти до редагування аукціону.
3. Завантажити нові документи.

**Очікувано:** У випадку заміни документу стара версія відображається перекресленою.
**Фактично:** Стара версія не перекреслена.

**Comment by dexvsmax** [comment]
у нас не передбачений функціонал “зміни документу”. документі можна лише додавати після публікації. а на стадії черновика документ повныстю замінюється. (бо це черновик). В ручних тестах не знайшов, що обов'язково треба перекреслювати "стару" версію. Якщо це обов'язковий функіонал, то зробимо.

**Comment by dexvsmax** [comment]
Реалізовано.
<img width="1648" alt="2017-01-12 15 30 49" src="https://cloud.githubusercontent.com/assets/16776302/21891640/578b771c-d8dc-11e6-97bd-f54557f7ca07.png">

**Comment by SoftserveQC1** [comment]
Не має можливості видаляти документ. Перевірено на http://devsale.zakupki.com.ua
На майданчику є можливість вокумент видалити документ на стадії чернетки
