### ISSUE TITLE
Privat: Ліквідатор не може зберегти аукціон в чернетку

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1007]
Privat: Ліквідатор не може зберегти аукціон в чернетку

1. Зайти як ліквідатор на майданчик
2. Натиснути кнопку "Створити лот"
3. Зберегти аукціон як чернетку без публікації в ЦБД

Очікуваний результат:
Користувач має можливість створення чернеток на порталі без публікації в ЦБД

Отриманий результат:
Користувач не може створити чернетку на порталі без публікації в ЦБД

**Comment by kurbpa** [comment]
Исправлено на  sell.pb.ua

**Comment by SoftserveQC1** [comment]
Аукціон зберігається, але в разі переходу до іншого вікна знайти аукціон неможливо

**Comment by SoftserveQC1** [comment]
система збереження чернеток реалізована. дефект зачинено
