### ISSUE TITLE
Privat: Власник лоту не має можливісті редагувати лот

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1008]
Privat: Власник лоту не має можливісті редагувати лот

1. Зайти на портал як ліквідатор
2. Знайти раніше створений аукціон на порталі як очікує заявки
3. Відредагувати аукціон згідно функціонали (можливість додавання нових документів)

Очікуваний результат:
Власник аукціону має можливість редагування власного аукціону (додавати документи)

Отриманий результат:
Користувач не може редагувати створений аукціон

**Comment by kurbpa** [comment]
Исправлено на  sell.pb.ua

**Comment by SoftserveQC1** [comment]
перевірено та зачинено
