### ISSUE TITLE
Privat: Користувач не може додати до свого профілю "Додати документ з фінансовою ліцензією"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1009]
Privat: Користувач не може додати до свого профілю "Додати документ з фінансовою ліцензією"

1. Зайти на портал
2. Перейти до закладки "Мій кабінет" >> "Профіль"
3. Натичнути кнопку "Додати документ з фінансовою ліцензією"

Очікуваний результат:
Користувач може додати і зберегти документ з фінансовою ліцензією

Отриманий результат:
Користувач не може додати фінансову ліцензію до свого профілю

**Comment by kurbpa** [comment]
Исправлено на sell.pb.ua

**Comment by SoftserveQC1** [comment]
перевірено та зачинено
