### ISSUE TITLE
Запитання можна задавати, після того, як переіод запитань завершився

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#101]
1. Залогуватися замовником.
2. Зайти в кабінет, нажати кнопку "Створити тендер".
3. В полі "Дата закінчення прийому запитань:" вказати певний час.
4. В полі початку "Період прийому заявок:" вказати час на 10 хв пізніше від часу закінчення прийому запитань:"
5. В полі закінчення "Період прийому заявок:" вказати час на 30 хв пізніше від часу початку "Період прийому заявок:"
6. Заповнити всі обов'язкові поля і нажати кнопку: "Створити тендер".
7. Зайти в систему як учасник (чи замовник), і дочекатися часу закінчення прийому запитань.
8. Вибрати створений тендер (статус "Період уточнень") і нажати кнопку "Задати запитання"

Очікуваний результат: учасник чи замовник не повинні мати можливості задавати запитання після закінчення "Дати закінчення прийому запитань".

Дійсний результат: учасник чи замовник мають можливость задавати запитання після закінчення "Дати закінчення прийому запитань".

![time_questions](https://cloud.githubusercontent.com/assets/10761162/6209145/06d718fc-b5cb-11e4-932b-3320cd2d0c0b.png)

**Comment by S-Shevchenko** [comment]
@myroslav Вопросы мы можем подавать только в статусе "Період уточнень". Если еще какие правила подачи вопросов через  ЦБД? Спасибо.
