### ISSUE TITLE
E-auction: посилання на аукціон непомітне

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1013]
майданчик: http://e-auction.pro/#/
користувач: memberpz_test
передумова: аукціон з посиланням на його проведення

Сценарій:
1. Авторизуватись на майданчику
2. Відкрити аукціон з передумови

Фактично: Посилання на аукціон важко знайти, бо воно має такий самий стиль, як і назви розділів
Очікувано: Посилання на аукціон легко знайти, бо воно виділяється на фоні всіх даних
![image](https://cloud.githubusercontent.com/assets/13050207/21522039/b8d29ec0-cd0a-11e6-9cd4-fb1ccae2d1a9.png)

**Comment by SergeDmitriev** [comment]
У нас на продуктивной системе в тендерах пользователи так ДВА ГОДА работают, при этом никаких замечаний у них не возникают

**Comment by SoftserveQC1** [comment]
зачинено
