### ISSUE TITLE
UACE: При спробі опублікувати аукціон у якому заповнено лише одне з полів: дата або номер рішення ФГВФО з'являється повідомлення з ерором

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1016]
http://test-eauction.uace.com.ua/buyer/

**Середа:**
- Mac OS El Capitan; Mozilla 50.0.1
- Mac OS El Capitan; Chrome 55.0.2883.95 (64-bit)
- Mac OS El Capitan; Safari 10.0.1 (11602.2.14.0.7)
- Windows 7; IE 11 11.0.9600.16428 (за допомогою Parallels Desktop)
- Windows 10; Edge 20.10240.171146.0 (за допомогою Parallels Desktop)

**Опис:** При спробі опублікувати аукціон у якому заповнені всі обов'язкові поля та вказані лише дата або лише номер рішення ФГВФО (не обидва поля одночасно) з'являється повідомлення із ерором який містить фрагмент коду

**Передумова:**
- Увійти на майданчик під логіном buyer@ustudio.com.ua
- Перейти до розділу "Мої ацкціони"
- Натиснути кнопку "Створити аукціон"
- Проскролити вниз сторінки та натиснути "Зберегти та перейти до публікації", щоб усі обов'язкові поля були виділені червоним кольором

**Відтворення:**
1) Заповнити усі обов'язкові поля валідними даними
2) Заповнити поле "Номер рішення виконавчої дирекції ФГВФО про затвердження умов продажу" (наприклад 123)
3) Поле "Дата рішення виконавчої дирекції ФГВФО про затвердження умов продажу" лишити пустим
4) Проскролити вниз сторінки та натиснути "Зберегти та перейти до публікації"

**Очікуваний результат:** Поле "Дата рішення виконавчої дирекції ФГВФО про затвердження умов продажу" виділено червоним, під ним повідомлення "Вкажіть дату рішення", публікація не відбувається

**Фактичний результат:** Відображається повідомлення про помилку із фрагментами коду

![default](https://cloud.githubusercontent.com/assets/13050207/21638358/b3890cd8-d273-11e6-8ad8-2addf7adb0b5.png)

**Comment by oleg4646** [comment]
Поправил.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
