### ISSUE TITLE
"Internal Server Error" при створенні тендера

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#102]
![error](https://cloud.githubusercontent.com/assets/10761162/6210004/dfc1254c-b5d3-11e4-8be7-e77969de2fe4.png)

**Comment by lerich** [comment]
пожалуйста сообщите uri
У нас сейчас продакшин на e-tender.biz, www.e-tender.biz и на e-tender.biz:99

**Comment by yuliyaSoftserve** [comment]
http://e-tender.biz:99/

**Comment by S-Shevchenko** [comment]
Не воспроизводиться.

**Comment by lerich** [comment]
Закриваю.
