### ISSUE TITLE
birga-ukraine.com.ua: Інформаційне повідомлення про отримання ролі Ліквідатора містить граматичні помилки

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1023]
**Опис:** Користувач отримує повідомлення після успішного виконання заявки для отримання ролі Ліквідатора з граматичними помилками 

**Передумови:** Зареєстрований користувач подав заявку на отримання ролі – Ліквідатора

**Кроки:** (Виконуються учасником)
1. Залогінитись як користувач
2. Зайти в меню "Кабінет" > "Профіль"
3. Натиснути на клавішу в нижньому лівому кутку – Подати заявку

**Фактично:** На пошту користувача надходить повідомлення про успішне надання доступу в ролі Ліквідатора з наступним змістом:
## Вітамємо. Ви надано доступ ліквідатора до с-ми ubiz

**Очікувано:** На пошту користувача надходить повідомлення про успішне надання доступу:
## Вітаємо. Вам надано доступ Ліквідатора до системи ubiz.
![2017-01-13_1317](https://cloud.githubusercontent.com/assets/20213167/21932826/333ce736-d9ab-11e6-9e54-acd04211371c.png)

**Comment by w-be** [comment]
І не Ubiz, а Товарна біржа «Перша універсальна біржа «Україна».

**Comment by SoftserveQC1** [comment]
Також відтворюється при створенні ліквідатора на http://test.torgi.vidol.com.ua
![image](https://cloud.githubusercontent.com/assets/13050207/21982835/e86bcec2-dbf6-11e6-8d16-ad868d7ec87a.png)

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SergeAntonets** [comment]
Поправлено.
