### ISSUE TITLE
birga-ukraine.com.ua: Не робоча клавіша – "Уповноважена особа". Вхід в режимі Юридичної особи

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1024]
**Опис:** не працює кнопка "Уповноважена особа" для переходу на відповідну сторінку

**Передумови:** Зареєстрований користувач ролі – Юридична особа

**Кроки:** (Виконуються учасником)
1. Залогінитись як Юридична особа
2. Зайти в меню "Кабінет" > "Профіль"
3. З вкадки "Інформація про юридичну особу" або "Банківські реквізити" натиснути на кнопку "Уповноважена особа"

**Фактично:** При наведенні на кнопку "Уповноважена особа" курсор змінюється на "Hand" але після кліку користувач залишається  в тому самому меню і завантаження сторінки "Уповноважена особа" не відбувається 

**Очікувано:** Після натискання кнопки "Уповноважена особа" відкривається вкладка з даними Уповноваженої особи
![2017-01-13_14411](https://cloud.githubusercontent.com/assets/20213167/21933043/5515de84-d9ac-11e6-8220-101cb3a1e321.png)

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SergeAntonets** [comment]
По табам переходить можно только через кнопку "Далі". При заполнение других форм, где форма разбита по табам, как правило, валидация происходит в каждом табе и перейти на следующий таб нельзя, если форма не валидна в конкретном табе. Здесь тот же подход, но здесь данные на валидность в табах не проверяются.
