### ISSUE TITLE
birga-ukraine.com.ua: Не робоча клавіша – "Уповноважена особа". Вхід в режимі Ліквідатора

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1025]
**Опис:** Користувач не може застосувати кнопку - "Уповноважена особа" для переходу на відповідну сторінку

**Передумови:** Зареєстрований та апрувнутий користувач ролі - Ліквідатор

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Ліквідатор
2.	Зайти в меню "Кабінет" > "Профіль"
3.	З вкадки "Інформація про юридичну особу" або "Банківські реквізити" натиснути на кнопку "Уповноважена особа"

**Фактично:** При наведенні на кнопку "Уповноважена особа" курсор змінюється на "Hand" але після кліку користувач залишається  в тому самому меню і завантаження сторінки "Уповноважена особа" не відбувається 

**Очікувано:** Після натискання кнопки "Уповноважена особа" відкривається вкладка з даними Уповноваженої особи

![2017-01-13_14411](https://cloud.githubusercontent.com/assets/20213167/21933121/bb89286a-d9ac-11e6-908c-6ae2969d2318.png)

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SergeAntonets** [comment]
По табам переходить можно только через кнопку "Далі". При заполнение других форм, где форма разбита по табам, как правило, валидация происходит в каждом табе и перейти на следующий таб нельзя, если форма не валидна в конкретном табе. Здесь тот же подход, но здесь данные на валидность в табах не проверяются.
