### ISSUE TITLE
E-commodity: Користувачу виводиться Json після публікації.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1027]
**Лінк:** https://zakupki.e-commodity.fbp.com.ua
**Кроки:**
1. Увійти в ролі ліквідатора. (omelen@softserveinc.com)
2. Створити новий аукціон або використати чернетку та опублікувати його.
3. Натиснути на лінк "Публікацію завершено"

**Фактично:** Користувачу виводиться Json.
**Відео:**  https://www.screencast.com/t/707o3bLk7e

**Примітка:**  Актуально для будь-яких публікацій, наприклад для скасування аукціону або помилки.

![2017-01-11_1508](https://cloud.githubusercontent.com/assets/13050207/21934507/4cafd21c-d9b2-11e6-8873-8b6ff6c02147.png)

![2017-01-11_1301](https://cloud.githubusercontent.com/assets/13050207/21934513/54a110a8-d9b2-11e6-8715-b89d77028742.png)

**Comment by SDiesel** [comment]
2: Користувачу виводиться Json
Примітка: Актуально для будь-яких публікацій, наприклад для скасування аукціону або помилки

Це додаткова інформація для розробників, у разі якщо у замовника виникли помилки.
відображається та приховується якщо клікнуті на лінк "Публікацію завершено"

Технічним завданням начебто не заборонено.
Якщо це критично - то також уже виправлено.

**Comment by SDiesel** [comment]
3:
Ви додали Документ x_dgfPublicAssetCertificate посилання,
де вказали url:
	https://zakupki.e-commodity.fbp.com.u
Наша процедура валідації вважає його коректним,
ЦБД визнала некоректним.
Використаємо більш жорстку процедуру валідації URL
та сьогодні після завершення тестування опублікуємо.

**Comment by SDiesel** [comment]
Валідацію URL виправили та опублікували
