### ISSUE TITLE
E-commodity: Зміна назви поля "адреса місцезнаходження майна \активу" після публікації.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1028]
**Лінк:** https://zakupki.e-commodity.fbp.com.ua
**Кроки:**
1. Увійти в ролі ліквідатора. (omelen@softserveinc.com)
2. Перейти до створення аукціону та додати лоти.
3. Перейти до додання адреси .
4. Заповнити всі поля та опублікувати аукціон.

**Очікувано:** Назва поля "Адреса місцезнаходження майна або Адреса місцезнаходження активу (в залежності від обраної процедури)" 
**Фактично:** Під час створення аукціону назва поля відображається правильно, але після публікації поле називається "Адреса".

![2017-01-13_1102adress](https://cloud.githubusercontent.com/assets/13050207/21934798/822615ae-d9b3-11e6-8e4b-bbd5b11e7e86.png)

![2017-01-13_1544 1](https://cloud.githubusercontent.com/assets/13050207/21934804/886d49fa-d9b3-11e6-9dfb-6c6f800d6e51.png)

**Comment by VadymShevchenko** [comment]
Виправлено
