### ISSUE TITLE
birga-ukraine.com.ua: Помилка 403 при спробі завантажити Рішення дирекції ФГВ. Роль - Ліквідатор.

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1029]
**Опис:** користувач отримує помилку 403 при спробі завантажити Рішення дирекції ФГВ.

**Кроки:** (Виконуються учасником)
1. Залогінитись як Ліквідатор
2. Зайти в меню "Особистий кабінет" > "Офіс замовника" > "Договори" > "ID договора" **200335**> "Завантажити"

**Фактично:** помилка 403, відсутня можливість завантажити Рішення дирекції ФГВ

**Очікувано:** користувач має можливість завантажувати Рішення дирекції ФГВ

![2017-01-16_11222](https://cloud.githubusercontent.com/assets/20213167/21977784/625772ac-dbe0-11e6-857a-c0ebdc836acd.png)

![2017-01-14_2109](https://cloud.githubusercontent.com/assets/20213167/21977790/6b2ae7c4-dbe0-11e6-8c86-f0b71e5e5bf1.png)

![2017-01-14_2109_001](https://cloud.githubusercontent.com/assets/20213167/21977796/6f82c97c-dbe0-11e6-9df5-4087e06c2aa9.png)

**Comment by SergeAntonets** [comment]
Поправлено.

**Comment by MMarkiyan** [comment]
Дефект відтворюється в Google chrome 55.0.2883.87 m (64-bit):
https://www.screencast.com/users/Mark_lviv/folders/torgi.birga.ukraine/media/de0b1b59-f4c1-4d87-a1ab-e87969483d1f

Також є користувачі в яких відтворити дефект не вдається(Firefox 50.1.0):
https://www.screencast.com/t/eI3iRi00KS

**Comment by SergeAntonets** [comment]
Дело в том, что  у Вас не подгрузился файл в момент подачи заявки на доступ ликвидатора. Это было поправлено. Вам нужно удалить файл и прикрепить новый. Я Вам верну редактирование заявки на доступ

**Comment by SoftserveQC1** [comment]
Проверено на площадке:
http://test.torgi.birga-ukraine.com.ua/
