### ISSUE TITLE
У "Кабінеті" -> "Профіль" ->"Реєстраційні дані" з'явилася нова кнопка "Відправити на модерацію", що саме має відбуватися, коли користувач нажме цю кнопку?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#103]
![send_moderation](https://cloud.githubusercontent.com/assets/10761162/6210229/3dbb358c-b5d6-11e4-91a7-3914b4828529.png)

**Comment by S-Shevchenko** [comment]
У нас появилась новая роль(оператор) специально для апрува пользователей.
Нажимая на кнопку мы отправляем на апрув оператору.

Для тестирования заходите на  сайт
http://services.e-tender.biz:99/#/
Оператор: 
Логин: оoperator1
Пароль: 123qwe

**Comment by lerich** [comment]
Закриваю.
