### ISSUE TITLE
birga-ukraine.com.ua: не підписаний стан фільтра, сторінка "Заявки на проведення торгів"

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1030]
Не підписаний статус фільтра, сторінка "Заявки на проведення торгів"
**Опис:** відкривши сторінку "Заявки на проведення торгів" фільтри дропбоксів присутні по замовчуванню без вибору активного фільтра. Цей стан фільтра варто підписати як – "Не обрано"
**Кроки:** (Виконуються учасником)
1. Залогінитись як користувач Ліквідатор
2. Зайти в меню "Особистий кабінет" > "Офіс замовника" > "Заявки на проведення торгів"
**Фактично:**  відображається контент без застосованих фільтрів
**Очікувано:** відображається контент без застосованих фільтрів

![2017-01-14_21322](https://cloud.githubusercontent.com/assets/20213167/21979623/6c95b7ee-dbe8-11e6-9536-043a99f5ac03.png)

**Comment by SergeAntonets** [comment]
Учтем на будущее. Спасибо.

**Comment by SoftserveQC1** [comment]
Дефект виправлено, у випадаючому списку назви полів відображаються, під час сортування обрані поля не відображаються пустими https://www.screencast.com/t/pW6YsTOGdNOn
