### ISSUE TITLE
birga-ukraine.com.ua: не коректна номерація заявок

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1031]
**Опис:** Заявки номеруються починаючи з №3.
**Кроки:** (Виконуються учасником)
1.	Залогінитись як користувач Ліквідатор
2.	Зайти в меню "Особистий кабінет" > "Офіс замовника" > "Заявки на проведення торгів"
3.	Додати нову заявку
**Фактично:** Створюється єдина заявка під №3. Всі наступні номеруються коректно.
**Очікувано:** Створені заявки номеруються починаючи від 1-ці.

![2017-01-15_2157](https://cloud.githubusercontent.com/assets/20213167/21979964/dbe88ecc-dbe9-11e6-9728-7132e73af79b.jpg)

**Comment by SergeAntonets** [comment]
Таблица едина для всех пользователей, которые имеют доступ к созданию заявок. Поэтому ид заявки не идет по порядку для конкретного пользователя.  Здесь по порядку потому, что в данный момент только Вы создавали заявки на сайте)
