### ISSUE TITLE
torgi.vidol: Помилки в перекладі імейла про публікацію лота

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1032]
**Опис:** Помилки в перекладі на українську мову листа про публікацю Лота.

**Кроки:**
1. Залогінитись як ліквідатор
2. Вибрати: Особистий кабінет>Офіс замовника>Заявки на проведення торгів> Додати лот
3. Заповнити відповідні поля і зберегти лот.
4. На сторінці 'Заявки на проведення торгів' вибрати Дія>Виконати публікацію

**Фактичний результат:** отримано імейл:"Лот опублыковано в ЦБД. Номер оголошеної процедури UA-EA-2017-01-16-000202-1"

![image](https://cloud.githubusercontent.com/assets/13050207/21983961/608b239e-dbfc-11e6-9b4d-1fb017285ee8.png)

**Очікуваний результат:** "Лот опубліковано в ЦБД. Номер оголошеної процедури UA-EA-2017-01-16-000202-1"

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SergeAntonets** [comment]
Поправлено.
