### ISSUE TITLE
birga-ukraine.com.ua: повідомлення про зміну пароля написане від ubiz.ua

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1033]
**Опис:** Користувач отримує повідомлення про успішну зміну пароля від ubiz.ua. Повідомлення містять граматичні помилки.

**Передумови:** користувач змінює пароль для свого акаунту

**Кроки:** (Виконуються учасником)
1. Зайти на сайт - http://test.torgi.birga-ukraine.com.ua
2. "Авторизація" > "Забули пароль"
3. Запит на відновлення паролю
4. Відкриваємо лист з посиланням для зміни паролю
5. Вказати новий пароль 

**Фактично:** Лист  з посиланням для зміни паролю надходить від імені стороннього сервісу - ubiz.ua. Слова з граматичними помилками відмічені на скріншотах.

**Очікувано:** Лист  з посиланням для зміни паролю надходить від імені Товарна біржа «Перша універсальна біржа «Україна»

![new2](https://cloud.githubusercontent.com/assets/20213167/21984299/f6162660-dbfd-11e6-8d4b-f8db454baf8d.png)

![new](https://cloud.githubusercontent.com/assets/20213167/21984228/a45f15ac-dbfd-11e6-919f-7647ee0c24eb.png)

**Comment by SoftserveQC1** [comment]
відтворюється для http://test.torgi.vidol.com.ua

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SergeAntonets** [comment]
Поправлено.
