### ISSUE TITLE
torgi.vidol: Початкова вартість лоту/крок аукціону/гарантійний внесок та кількість активів можуть містити від'ємні значення

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1034]
**Опис:** Користувач може добавити від'ємні значення в поля Початкова вартість, Крок аукціону і Гарантійний внесок та кількість активів

**Кроки:**

1. Залогінитись як ліквідатор
2. Вибрати: Особистий кабінет>Офіс замовника>Заявки на проведення торгів> Додати лот
3. Заповнити відповідні поля Початкова вартість, Крок аукціону і Гарантійний внесок та кількість активів від'ємними значеннями
4. Заповнити решту полів і зберегти лот

**Фактичний результат:** Лот може бути збережений з від'ємними значеннями в полях Початкова вартість, Крок аукціону, Гарантійний внесок та к-сть активів
![image](https://cloud.githubusercontent.com/assets/13050207/21986972/49cfbddc-dc0a-11e6-8e0d-7c014c30c934.png)

**Очікуваний результат** поля Початкова вартість, Крок аукціону і Гарантійний внесок та к-сть активів не повинні містити від'ємні значення.

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua , але опублікувати аукціон не вийде - повідомлення "Помилка даних"

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SergeAntonets** [comment]
Поправлено.
