### ISSUE TITLE
birga-ukraine.com.ua: не витримується крок ставок аукціону

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1035]
Не витримується крок ставок аукціону
**Опис:** 
**Кроки:** (Виконуються учасником)
1.	Залогінитись як користувач
2.	Вибрати буть який аукціон
3.	Зробити ставку
4.	Зробити нову ставку що не відповідає крокові

**Фактично:** ставка не відповідає крокові. Допускається ставка починаючи від+1 грн до вартості лоту
**Очікувано:** користувачі роблять ставки відповідно до заданого кроку Ліквідатора.

![2017-01-16_1639](https://cloud.githubusercontent.com/assets/20213167/21987667/209971ee-dc0d-11e6-8501-973129686be8.png)

![2017-01-16_1641](https://cloud.githubusercontent.com/assets/20213167/21987681/2b04d9b6-dc0d-11e6-9f1a-8dae1955cd6d.png)

![2017-01-16_1649](https://cloud.githubusercontent.com/assets/20213167/21987699/3931067c-dc0d-11e6-8125-cf84a5e6e760.png)

**Comment by SoftserveQC1** [comment]
Відтворюється на http://test.torgi.vidol.com.ua/

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua
Крок аукціону також не витримується під час етапу "Аукціон"
![2](https://cloud.githubusercontent.com/assets/13050207/22103124/99e06062-de42-11e6-9913-0b4727c6792f.png)
![default](https://cloud.githubusercontent.com/assets/13050207/22103130/a14f9c3c-de42-11e6-8a8e-b09bb41330cc.png)

**Comment by SoftserveQC1** [comment]
відтворюється на uutb http://test.tp.uutb.com.ua

**Comment by SergeAntonets** [comment]
Все, что происходит во время ставок касается модуля аукциона.

**Comment by w-be** [comment]
Крок ставки відраховується від попередньої ставки того самого учасника. В наданому прикладі мінімальний крок 1000 грн; фактичний крок 1000 грн 50 к.

**Comment by SergeAntonets** [comment]
так значит сам модуль аукциона разрешает такое делать. Разве нет?
