### ISSUE TITLE
torgi.vidol: Опції Файл і Видалити повинні бути розміщені поруч із кожним завантаженим файлом

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1036]
**Опис:** На сторінці 'Прикріпити документи' Опція 'Видалити' розміщена не біля файлу з назвою. Користувачу незрозуміло який із завантажених файл можна видалити, а який ні.

**Кроки:**

1.  Залогінитись як Ліквідатор
2.  Вибрати: Особистий кабінет>Офіс замовника>Заявки на проведення торгів> Переглянути список лотів
2.  Вибрати існуючий неопублікований лот (або створити новий)
3.  Вибрати Дія>Прикріпити документ
4.  Прикріпити документи і зберегти зміни

**Фактичний результат:** Опція 'Видалити' розміщена біля лінки 'Файл' (яка не містить назви файлу). Користувач не бачить який саме файл видалити.
![image](https://cloud.githubusercontent.com/assets/13050207/21988898/8605e4c8-dc11-11e6-9a09-1c38c7dcc12a.png)

**Очікуваний результат:** Користувач повинен бачити який саме файл він планує видалити

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SergeAntonets** [comment]
Сделано.
