### ISSUE TITLE
torgi.vidol: імейл про скасування аукціону містить неправильну лінку

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1037]
**Опис:** Користувач отримує імейл про скасування аукціону, який містить лінку яка відноситься до іншого уже існуючого аукціону (який має такий самий номер лоту).

**Кроки:** 
1. Залогінитись як Ліквідатор
2. Вибрати: Особистий кабінет>Офіс замовника>Заявки на проведення торгів>Дія> Переглянути список лотів
3. Вибрати існуючий неопублікований лот (або створити новий)
4. Вибрати Дія>Виконати публікацію
5. Після публікації лоту, вибрати Дія>Скасувати аукціон

**Фактичний результат:** в імейлі про скасування лоту відображається некоректна лінка
![image](https://cloud.githubusercontent.com/assets/13050207/21990783/c13385bc-dc18-11e6-8f9d-bb12f444eb17.png)

**Очікуваний результат:** в імейлі про скасування лоту повинна відображатись лінка, яка веде на відповідний скасований аукціон.

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SergeAntonets** [comment]
Поправлено.
