### ISSUE TITLE
torgi.vidol: помилки в попапі який повідомляє користувача про успішну реєстрацію

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1038]
**Опис:** Виявлені помилки в попапі, що інформує користувача про завершення реєстрації.

**Кроки:**
1. Вибрати 'Реєстрація' (фізична або юридична особа)
2. Заповнити відповідні поля та натиснути кнопку 'Зареєструватись'

**Фактичний результат:** появляється попап-вікно із текстом: "Вітаємо, Ви успішно зареєструвалися на порталі TEST! Для авторизації, на Вашу електронну пошту напралено повідомлення. Перегляньте його та перейдіть за посиланням! Дякуємо за користування нашим сервісом! "

![image](https://cloud.githubusercontent.com/assets/13050207/22014669/730f4828-dca7-11e6-9c6e-617f29895eb5.png)

**Очікуваний результат:** Вітаємо, Ви успішно зареєструвалися на порталі TEST! Для авторизації на Вашу електронну пошту відправлено повідомлення. Перегляньте його та перейдіть за посиланням. Дякуємо за користування нашим сервісом.

**Comment by SergeAntonets** [comment]
Поправлено.
