### ISSUE TITLE
torgi.vidol: помилки в попапі який повідомляє користувача про підтвердження імейлу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1039]
**Опис:** Виявлені помилки в попапі, який інформує користувача про те що імейл був підтверджений.

 **Кроки:**
1. Вибрати 'Реєстрація' (фізична або юридична особа)
2. Заповнити відповідні поля та натиснути кнопку 'Зареєструватись'
3.  Відкрити імейл про підтвердження реєстрації і перейти за вказаним в ньому посиланням.

**Фактичний результат:** з'являється попап-вікно із текстом: "Вітаємо. Ви підтвердили ваш Email. Від тепер Ви має можливість користуватися сервісом TEST!"
![image](https://cloud.githubusercontent.com/assets/13050207/22015280/0b90ef64-dcaa-11e6-83dd-8e35d515eadd.png)

**Очікуваний результат:** "Вітаємо. Ви підтвердили ваш Email. Відтепер Ви маєте можливість користуватися сервісом TEST."

**Comment by SergeAntonets** [comment]
Поправлено.
