### ISSUE TITLE
На сторінці "Авторизації" зник чек-бокс "Запам'ятати мене"

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#104]
![remember_me](https://cloud.githubusercontent.com/assets/10761162/6212309/57a33ede-b5ec-11e4-9713-e5d6c87ff2de.png)

**Comment by S-Shevchenko** [comment]
Задача внесена в ближайший билд.

**Comment by S-Shevchenko** [comment]
Убрали данный функционал.
