### ISSUE TITLE
torgi.vidol: "Порядок ознайомлення з активом у кімнаті даних"/"Порядок ознайомлення з майном" відображаються як посилання

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1040]
**Опис:** На вкладці "Опис майна", "Порядок ознайомлення з активом у кімнаті даних"/"Порядок ознайомлення з майном" відображаються як лінки. Опис доданий під час створення(редагування) лоту відображається під лінкою

**Кроки:**
1. Залогінитись як Ліквідатор
2. Вибрати: Особистий кабінет>Офіс замовника>Заявки на проведення торгів> Переглянути список лотів> Дія> Додати лот
3. Заповнити відповідні обов'язкові поля
4. Опублікувати лот
5. Вибрати Дія> Переглянути

**Фактичний результат:** "Порядок ознайомлення з активом у кімнаті даних"/"Порядок ознайомлення з майном" є посиланнями. Доданий опис міститься під лінкою.
![image](https://cloud.githubusercontent.com/assets/13050207/22021128/33a16622-dcc4-11e6-9c84-38355c19915e.png)

**Очікуваний результат:** "Порядок ознайомлення з активом у кімнаті даних"/"Порядок ознайомлення з майном"повинні бути текстовими полями. Доданий опис повинен відображатись поряд з назвами "Порядок ознайомлення з активом у кімнаті даних" чи "Порядок ознайомлення з майном"

**Comment by SoftserveQC1** [comment]
відтворюється на uutb http://test.tp.uutb.com.ua

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SergeAntonets** [comment]
Поправлено.
