### ISSUE TITLE
torgi.vidol: Розмір гарантійного внеску може бути будь-яким значенням до 500 000 грн включно

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1041]
**Опис:** Розмір гарантійного внеску може бути більше або менше 5%  від Початкової ціни реалізації Лоту, але завжди менше 500 000 грн.

**Кроки:**
1.  Залогінитись як Ліквідатор
2. Вибрати: Особистий кабінет>Офіс замовника>Заявки на проведення торгів> Переглянути список лотів> Дія> Додати лот
3. Заповнити відповідні обов'язкові поля
4. Вказати значення більше 500 000 грн в полі Розмір гарантійного внеску

**Фактичний результат:** Користувач отримує повідомлення" Величина гарантійного внеску повинна бути меншою за 500 000". Величина гарантійного внеску може бути значенням <= 500 000 грн. і більшим за значення Розмір гарантійного внеску.
![image](https://cloud.githubusercontent.com/assets/13050207/22022279/f8c89fa6-dcc9-11e6-88a5-aa84839360ac.png)

**Очікуваний результат:** Розмір гарантійного внеску повинен складати 5% від Початкової ціни реалізації Лоту.

**Comment by MMarkiyan** [comment]
відтворюється для torgi.birga-ukraine.com.ua

![2017-01-18_0757](https://cloud.githubusercontent.com/assets/20213167/22052658/219c947a-dd54-11e6-9709-ecdb5a277e40.png)

**Comment by SergeAntonets** [comment]
Идут правки в связи новой инфой.

**Comment by w-be** [comment]
Дане обмеження зняте, ще до нового року.

**Comment by SergeAntonets** [comment]
Поправлено!
