### ISSUE TITLE
birga-ukraine.com.ua: не коректно працює кнопка "Дія" в розділі "Контракти"

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1042]
**Опис:** натиснувши на кнопку Дія, зявляється дропдаун з відсутніми опціями

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Ліквідатор
2.	Особистий кабінет > Офіс замовника > Контракти
3.	Клікнути на клавішу "Дія"

**Фактично:** клавіша "Дія" виконана у вигляді дропбокса, але для вибору доступне тільки пусте поле 
**Очікувано:** натиснувши на клавішу "Дія" надається можливість застосувати запропоновані дії з дропбокса

![2017-01-17_2137](https://cloud.githubusercontent.com/assets/20213167/22052796/21607f5c-dd55-11e6-8507-ad6261c80c05.png)

**Comment by SoftserveQC1** [comment]
відтворюється на https://torgi.vidol.com.ua/

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SoftserveQC1** [comment]
відтворюється на http://test.tp.uutb.com.ua

**Comment by SergeAntonets** [comment]
Внесена правка

![image](https://cloud.githubusercontent.com/assets/7313452/22375837/5ae164b0-e4b4-11e6-922d-a38a523e18c5.png)

**Comment by SoftserveQC1** [comment]
Исправлено на:
vidol - http://test.torgi.vidol.com.ua
cuex - http://testing.torgy.com.ua
torgibirgaua - http://test.torgi.birga-ukraine.com.ua
![15cb4cdfa2](https://cloud.githubusercontent.com/assets/13050207/23793926/5078017a-0596-11e7-8c95-13b46aac6cb2.jpg)
