### ISSUE TITLE
birga-ukraine.com.ua: не працюючі навігаційні кнопки в процедурі додавання лоту

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1043]
**Опис:** Користувач має можливість пересуватись в розділі оформлення лоту з допомогою меню навігаційних кнопок "Опис майна", "Параметри", "Активи аукціону" та "Назад" "Далі". Кнопки з навігаційного меню не відповідають на клік.

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Ліквідатор
2.	Особистий кабінет > Офіс замовника > Контракти
3.	Клікнути на кнопки "Опис майна", "Параметри", "Активи аукціону"
4.	Дизайн навігаційного меню має дефект. Розмір кнопок менший за розмір переходу між ними

**Фактично:**  кнопки не реагують на клік
**Очікувано:** після кліку на кнопку, користувач переміщується у відповідний розділ оформлення Лоту

![2017-01-18_0756](https://cloud.githubusercontent.com/assets/20213167/22052880/f88127e8-dd55-11e6-8fc9-b08383fd4dab.png)

**Comment by SergeAntonets** [comment]
По табам переходить можно только в порядке заполнения форм. Для того, чтобы перейти на другую вкладку  - таб должен пройти валидацию через последовательное нажатие кнопок "Далі" и т.д.
