### ISSUE TITLE
birga-ukraine.com.ua: після зміни масштабування сторінки перекривається текстове поле з Ціновою пропозицією

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1044]
**Опис:** при зміні масштабування вікна деформується дизайн сторінки та стає недоступне поле для Цінової пропозиції

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Користувач
2.	Подати заявку на участь в аукціоні
3.	Зменшити масштаб сторінки

**Фактично:** відсутня можливість заповнити заявку на лот у вікні зменшеного масштабу
**Очікувано:** заявку на лот можна подати не залежно від розміру вікна

![2017-01-17_2102](https://cloud.githubusercontent.com/assets/20213167/22054360/daf8b224-dd5d-11e6-832d-e1ffbf353e26.png)

![2017-01-17_2103](https://cloud.githubusercontent.com/assets/20213167/22054361/dc2a3622-dd5d-11e6-85b9-1389924f10ee.png)

**Comment by SergeAntonets** [comment]
Поправлено.

**Comment by MMarkiyan** [comment]
Виправлено
