### ISSUE TITLE
birga-ukraine.com.ua: після зміни масштабування сторінки деформується дизайн, розділ Профіль

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1046]
**Опис:** при зміні масштабування вікна деформується дизайн сторінки

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Користувач
2.	Особистий кабінет – Налаштування - Профіль
3.	Зменшити масштаб сторінки

**Фактично:** Вертикальне меню з лівої сторони вікна переходить в праву сторону
**Очікувано:** Сторінка зберігає пропорції при масштабуванні

![2017-01-12_2024](https://cloud.githubusercontent.com/assets/20213167/22055315/4478d058-dd63-11e6-8f29-fa2c1af85151.png)

![2017-01-13_1054](https://cloud.githubusercontent.com/assets/20213167/22055269/fef1b64e-dd62-11e6-9792-ee7fbca2023d.png)

![2017-01-12_2023](https://cloud.githubusercontent.com/assets/20213167/22055308/3ac08d80-dd63-11e6-82ab-f29052cfed7f.png)

**Comment by SergeAntonets** [comment]
Поправлено.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
перевірено:
IE 11.0.96.00.17843
Chrome 56.0.2924.87 (64-bit)
Mozilla 52.0 (64-bit)
