### ISSUE TITLE
Ueex: На формі створення лоту поле “контактна особа” не обов’язкове

### ISSUE THREAD

**Issue by georgedp** [openprocurement/frontend#1047]
_Ueex: На формі створення лоту поле “контактна особа” не обов’язкове_

**Фактично:** 
Для збереження лоту у чернетці не обов'язково заповнювати поле “контактна особа”

**Очикувано:** 
Для збереження лоту у чернетці обов'язково заповнювати поле “контактна особа”

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by georgedp** [comment]
відтворюється на https://sale-tbe.com.ua/test/
