### ISSUE TITLE
Ueex: На формі регістрації користувача відсутня валідація полів

### ISSUE THREAD

**Issue by georgedp** [openprocurement/frontend#1048]
_Ueex: На формі регістрації користувача відсутня коректна валідація полів_

**Фактично:** 
Всі поля валідуються на основі розмірів полів у ЦБД

**Очикувано:** 
Поля валідуються з вимогами і типом даних які вводяться.
```
(Наприклад: 
р/с - 14 цифер і не може міститі літери
ЄДРПОН - 8 разрядів, не більше і не містить спец символів
МФО - 6 разрядів
ІНН - 12 разрядів, містить лише цифри
і т.д. по кожному полю)
```

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SoftserveQC1** [comment]
відтворюється на http://test.torgi.vidol.com.ua

**Comment by MMarkiyan** [comment]
відтворюється на http://sale.nkc.biz.ua

**Comment by georgedp** [comment]
відтворюється на https://sale-tbe.com.ua/test/

**Comment by alex85vol** [comment]
відтворюється на https://ti.tbkmfb.com.ua/test

**Comment by SoftserveQC1** [comment]
на майданчика клонах Ubiz "Ограничение снято для иностранных клиентов, покупателей"

**Comment by v-lego** [comment]
Встановлено перевірку полів для полів: ЄДРПОУ, Індекс, Рахунок, МФО, ІПН, Серія та № паспорту

**Comment by georgedp** [comment]
Ueex: та Katerynoslav: - провалідовані
Дифект **виправленно** на майданчиках sale.ueex.com.ua/test, sale-tbe.com.ua/test/

Поребує валідаціі для інших майданчиків
v:nkcentr
v:tbkmfb
v:torgibirgaukraine
v:vidol

**Comment by SoftserveQC1** [comment]
v:torgibirgaukraine
Відсутня валідація полів: Рахунок, ІПН, Серія та № паспорту
https://www.screencast.com/t/9TABucKlby9

**Comment by SergeAntonets** [comment]
Данные валидируются на этапе подачи заявки на участие

**Comment by SoftserveQC1** [comment]
Перевірено на http://test.torgi.vidol.com.ua
