### ISSUE TITLE
Ueex: На формі регістрації користувача сповіщення не відповідають вимогам полів

### ISSUE THREAD

**Issue by georgedp** [openprocurement/frontend#1049]
_Ueex: На формі регістрації користувача сповіщення не відповідають вимогам полів_

**Фактично:** 
Сповіщення про незаповнення або не коректне заповнення полів містять застереження на основі розмірів полів у ЦБД

**Очикувано:** 
Сповіщення про незаповнення або не коректне заповнення полів містять застереження на основі вимог і типів даних які вводяться.
```
(Наприклад: 
р/с - 14 цифер і не може міститі літери
ЄДРПОН - 8 разрядів, не більше і не містить спец символів
МФО - 6 разрядів
ІНН - 12 разрядів, містить лише цифри
і т.д. по кожному полю)
```

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by georgedp** [comment]
відтворюється на https://sale-tbe.com.ua/test/

**Comment by SoftserveQC1** [comment]
на майданчика клонах Ubiz "Ограничение снято для иностранных клиентов, покупателей"

**Comment by v-lego** [comment]
Застереження до полів  ЄДРПОУ, Індекс, Рахунок, МФО, ІПН, Серія та № паспорту містять повідомлення згідно формату даних

**Comment by georgedp** [comment]
Ueex: та Katerynoslav: - провалідовані
Дифект **виправленно** на майданчиках sale.ueex.com.ua/test, sale-tbe.com.ua/test/

Поребує валідаціі для інших майданчиків
v:nkcentr
v:torgibirgaukraine

**Comment by SoftserveQC1** [comment]
v:torgibirgaukraine
Відсутня валідація полів: Рахунок, ІПН, Серія та № паспорту.
Повідомлень про невірно введені дані немає
https://www.screencast.com/t/9TABucKlby9

**Comment by SergeAntonets** [comment]
валидация данных на уровне профиля не происходит. Только на момент подачи заявки на участие

**Comment by SoftserveQC1** [comment]
Перевірено на http://test.torgi.vidol.com.ua
