### ISSUE TITLE
Тестове середовище для майданчика e-tender.biz

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#105]
це потрібно для тестування негативних сценаріїв

**Comment by myroslav** [comment]
п.Юлі потрібне середовище, яке працює з sandbox-ом, щоб не "псувати" картинку в тестових аукціонах на production.

**Comment by lerich** [comment]
ок, завтра сделаем

**Comment by S-Shevchenko** [comment]
@yuliyaSoftserve @myroslav 
Юля, Створив тестове середовище:
http://services.e-tender.biz:99/#/
Модерує оператор:

Логін: operator1
Пароль: 123qwe

Пошта оператора: operator1testetender@i.ua
Пароль: 1111!@#

**Comment by yuliyaSoftserve** [comment]
Скажіть будь-ласка url та сама що і на майданчик?

**Comment by lerich** [comment]
http://services.e-tender.biz:99/
Обратите внимание в начале "services". Это разные машины

**Comment by lerich** [comment]
на продакшин e-tender.biz (или www.e-tender.biz или e-tender.biz:99) без слова services
