### ISSUE TITLE
birga-ukraine.com.ua: користувачу надходять повідомлення що до активності в аукціоні від ubiz.ua

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1050]
**Опис:** Користувач отримує  всі сервісні повідомлення від ubiz.ua

**Наступні повідомлення:** (Виконуються учасником)
1. Повідомлення про Перемогу в торгах по лоту
2. Повідомлення про Посилання на участь в аукціоні
3. Повідомлення про Пропозиція по лоту
4. Повідомлення про Допуск до участі в аукціоні
5. Повідомлення про Заяву на участь в торгах

**Фактично:** Повідомлення надходять від стороннього сервісу - ubiz.ua.

**Очікувано:** Сревісні повідомлення надходять від імені Товарна біржа «Перша універсальна біржа «Україна»

![2017-01-17_1600](https://cloud.githubusercontent.com/assets/20213167/22055476/04f293e6-dd64-11e6-881c-f32effbad088.png)

**Comment by SoftserveQC1** [comment]
відтворюється на http://test.torgi.vidol.com.ua

**Comment by SoftserveQC1** [comment]
відтворюється на uutb http://test.tp.uutb.com.ua

**Comment by SergeAntonets** [comment]
Изменены smtp сервера:
test.birga-ukraine.com.ua
test.torgi.vidol.com.ua
Ожидается:
test.tp.uutb.com.ua
test.market.comminnex.com
test.torgi.status-expert.com.ua

**Comment by SergeAntonets** [comment]
Поправлено
