### ISSUE TITLE
Ueex: На формі створення лоту відсутня коректна валідація полів

### ISSUE THREAD

**Issue by georgedp** [openprocurement/frontend#1051]
_Ueex: На формі створення лоту відсутня валідація полів_

**Фактично:** 
Всі поля валідуються на основі розмірів полів у ЦБД

**Очикувано:** 
Поля валідуються з вимогами і типом даних які вводяться.
```
(Наприклад: 
час, назви населенних пунктів, номер ФГВФО, почтовий індекс, контактна особа)
```

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by georgedp** [comment]
відтворюється на https://sale-tbe.com.ua/test/

**Comment by v-lego** [comment]
Встановлено перевірку полів час, номер ФГВФО, контактна особа. Поле почтовий індекс перевірка формату за наявності значення

**Comment by georgedp** [comment]
Ueex: та Katerynoslav: - провалідовані
При першому тестуванні цей дифект стосувася группи полів "контактна особа", "замовник", полів лотів.

На цей цас дифект **виправленно** на майданчиках sale.ueex.com.ua/test, sale-tbe.com.ua/test/

Группи полів "контактна особа", "замовник" заповнюються автоматично з даних користувача;
Поля лотів валідуються і нотіфікуються згідно вимогам полів

Поребує валідаціі для інших майданчиків
v:nkcentr

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
