### ISSUE TITLE
Ueex: На формі створення лоту сповіщення не відповідають вимогам полів

### ISSUE THREAD

**Issue by georgedp** [openprocurement/frontend#1052]
_Ueex: На формі створення лоту сповіщення не відповідають вимогам полів_

**Фактично:** 
Сповіщення про незаповнення або не коректне заповнення полів містять застереження на основі розмірів полів у ЦБД

**Очикувано:** 
Сповіщення про незаповнення або не коректне заповнення полів містять застереження на основі вимог і типів даних які вводяться.
```
(Наприклад: 
час, назви населенних пунктів, номер ФГВФО, почтовий індекс, контактна особа)
```

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by georgedp** [comment]
відтворюється на https://sale-tbe.com.ua/test/

**Comment by v-lego** [comment]
Внесено зміни
Застереження до полів час, Індекс (за наявності значення) містять повідомлення згідно формату даних

**Comment by georgedp** [comment]
Ueex: та Katerynoslav: - провалідовані
При першому тестуванні цей дифект стосувася группи полів "контактна особа", "замовник", полів лотів.

На цей цас дифект **виправленно** на майданчиках sale.ueex.com.ua/test, sale-tbe.com.ua/test/:
Группи полів "контактна особа", "замовник" заповнюються автоматично з даних користувача;
Поля лотів валідуються і нотіфікуються згідно вимогам полів

**Comment by georgedp** [comment]
поребує валідаціі для інших майданчиків
v:nkcentr

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
