### ISSUE TITLE
Ueex: У листах сповіщення відсутні зображення інколи “не гарні” полсилання

### ISSUE THREAD

**Issue by georgedp** [openprocurement/frontend#1053]
_Ueex: У листах сповіщення відсутні зображення інколи “не гарні” полсилання_

**Фактично:** 
![error-2017-01-17_13-50-16](https://cloud.githubusercontent.com/assets/24564984/22055719/33dc9aca-dd65-11e6-9294-5324e293a075.jpg)
У листах сповіщення відсутні зображення
Деякі посілання мають вигляд html коду

**Очикувано:** 
Листи сповіщення містять усі прікріпленні зображення
Усі посілання мають однаковий вигляд

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by georgedp** [comment]
відтворюється на https://sale-tbe.com.ua/test/

**Comment by alex85vol** [comment]
відтворюється на https://ti.tbkmfb.com.ua/
