### ISSUE TITLE
UUTB: Відсутня валідація поля ЄДРПОУ

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1054]
**Лінк:** http://test.tp.uutb.com.ua
**Кроки:**
1. Перейти до реєстрації юридичної особи. 

**Очікувано:** максимальна кількість знаків в полі ЄДРПОУ 8.
**Фактично:** можна ввести більше знаків, а також текст, наприклад тест123"№;

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SergeAntonets** [comment]
Ограничение снято для иностранных клиентов, покупателей
