### ISSUE TITLE
UUTB: Відсутня валідація поля ІПН 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1055]
**Лінк:** http://test.tp.uutb.com.ua
**Кроки:**
1. Перейти до реєстрації фізичної особи.

**Очікувано:** кількість знаків в полі ІПН 10.
**Фактично:** є можливість ввести текст та спецсимволи, та зберегти менше ніж з 10 символами.

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SergeAntonets** [comment]
Ограничение снято для иностранных клиентов, покупателей
