### ISSUE TITLE
UUTB: Некорректна назва поля "Період аукціону"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1056]
**Лінк**: http://test.tp.uutb.com.ua
**Кроки:**
1.  Створити аукціон і опублікувати його.

**Очікувано:** Поле називається "Дата проведення аукціону"
**Фактично:** Під час створення поле називається "Дата проведення аукціону" , після публікації "Період аукціону"

![2017-01-17_1615](https://cloud.githubusercontent.com/assets/13050207/22056741/387cdfcc-dd6a-11e6-9f4f-0c391a3580ec.png)

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SoftserveQC1** [comment]
відтворюється на http://test.torgi.vidol.com.ua

**Comment by SoftserveQC1** [comment]
https://github.com/openprocurement/frontend/issues/1023

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SergeAntonets** [comment]
Поправлено.
