### ISSUE TITLE
UUTB: Некоректна реалізація видалення документів.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1057]
**Лінк:** http://test.tp.uutb.com.ua
**Кроки:**
1. Увійти як ліквідатор (omelen@softserveinc.com)
2. Створити аукціон (опублікувати той котрий ще не був опублікований)
3. Прикріпити документи та зберегти

**Очікувано:** Кнопка "Видалити" розміщена біля документу, користувачу зрозуміло який саме файл він видаляє.
**Фактично:** Кнопка "Видалити" розміщена біля лінки "Файл" 

![2017-01-18_1051](https://cloud.githubusercontent.com/assets/13050207/22057182/4277684c-dd6c-11e6-9703-0eede1f86878.png)

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SergeAntonets** [comment]
Переделано.
