### ISSUE TITLE
torgi.vidol:  користувач може зберегти лот не заповнюючи поля "Рішення виконавчої дирекції ФГВФО про затвердження умов продажу №" та "Від"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1058]
**Опис:** Користувач має змогу зберегти лот не заповнюючи поля "Рішення виконавчої дирекції ФГВФО про затвердження умов продажу №" та "Від". Проте не може опублікувати лот, через помилку в даних.

**Кроки:**

1. Залогінитись як Ліквідатор
2. Вибрати: Особистий кабінет>Офіс замовника>Заявки на проведення торгів> Переглянути список лотів> Дія> Додати лот
3. Заповнити відповідні обов'язкові поля; Поля "Рішення виконавчої дирекції ФГВФО про затвердження умов продажу №" та "Від" залишити пустими
4. Зберегти та опублікувати лот

**Фактичний результат:** Користувач отримую повідомлення "Помилка в даних" при спробі опублікувати лот, в якого поля Рішення виконавчої дирекції ФГВФО про затвердження умов продажу №" та "Від" є незаповненими

![image](https://cloud.githubusercontent.com/assets/13050207/22057760/c61e7ba2-dd6e-11e6-98f7-a3f98951d6e8.png)

**Фактичний результат:** Поля Рішення виконавчої дирекції ФГВФО про затвердження умов продажу № та Від повинні бути обов'язковими для заповнення.

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SergeAntonets** [comment]
Поправлено.
