### ISSUE TITLE
torgi.vidol: Ліквідатор може  приймати участь у торгах і задавати запитання самому собі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1059]
**Опис:** Ліквідатор який створив лот може приймати участь в аукціоні і задавати сам собі запитання.

**Кроки:**
1. Залогінитись як Ліквідатор
2. Вибрати: Особистий кабінет>Офіс замовника>Заявки на проведення торгів> Переглянути список лотів> Дія> Додати лот>Зберегти >Дія > Опублікувати аукціон
3. Вибрати Дія>Переглянути аукціон

**Фактичний результат:** Ліквідатор має можливість приймати участь у створеному ним аукціоні і задавати запитання самому собі.
![image](https://cloud.githubusercontent.com/assets/13050207/22060912/6eefa0b0-dd7b-11e6-9978-870ace661f50.png)

**Очікуваний результат:** Ліквідатор не повинен мати можливості брати участь у аукціоні і задавати собі запитання.

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SoftserveQC1** [comment]
відтворюється на uutb  http://test.tp.uutb.com.ua

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SergeAntonets** [comment]
Убрали такую возможность.
