### ISSUE TITLE
Не має можливості створити тендер - відсутня кнопка "Створити тендер" для нового користувача

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#106]
![no_button](https://cloud.githubusercontent.com/assets/10761162/6229764/b63a5064-b6c2-11e4-8fc6-b86250f2e4ca.png)

Раніше вже був заведений такий дефект
https://github.com/openprocurement/frontend/issues/67

**Comment by S-Shevchenko** [comment]
Цей користувач пройшов модерацію оператора?

**Comment by yuliyaSoftserve** [comment]
Ні, не пройшов

**Comment by S-Shevchenko** [comment]
Скорее всего данный пользователь не прошел модерацию оператора и не может создавать тендер. 
Окружение для тестирования:
http://services.e-tender.biz:99/#/

**Comment by OksanaPakholok** [comment]
Було створено нового користувача, як юридична особа, з відзначеним чебоксом "Державний замовник". Користувач подав заявку на модерацію, натиснувши кнопку "Відправити на модерацію". Зайшовши під логіном operator1 заявка була підтвержена.

Результат: користувач-замовник немає можливості створювати тендер.

![no_possibility_create_tender](https://cloud.githubusercontent.com/assets/11062040/6269940/34a27f1a-b85f-11e4-915e-5e2c22002e8d.png)

**Comment by S-Shevchenko** [comment]
Выложил актуальную версию. проверь пожалуйста...

**Comment by OksanaPakholok** [comment]
Так, зараз вже є можливість у замовника створювати тендери, причому і до модерації і після

![newtender](https://cloud.githubusercontent.com/assets/11062040/6270591/a21b5450-b863-11e4-82e2-9dd731ecf74b.png)

**Comment by S-Shevchenko** [comment]
В ближайшем билде закроем данную возможность, юзер может
создавать тендер в тестовый режиме, только тогда, когда пройдет первичную модерацию.

**Comment by lerich** [comment]
Закриваю.
