### ISSUE TITLE
torgi.vidol: Нема можливості ввести текст-опис причини скасування аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1060]
**Опис:** Нема можливості вводити текст-опис причини скасування аукціону

**Кроки:**
1. Залогінитись як Ліквідатор
2. Вибрати: Особистий кабінет>Офіс замовника>Заявки на проведення торгів> Переглянути список лотів> Дія> Додати лот
3. Заповнити обов'язкові поля відповідними значеннями та опублікувати аукціон
4. Після публікації вибрати Дія>Скасувати аукціон

**Фактичний результат:** Користувач немає змоги вводити текст-опис причини скасування аукціону
![image](https://cloud.githubusercontent.com/assets/13050207/22061392/6aad3510-dd7d-11e6-82f4-a9f3845de420.png)

**Очікуваний результат:** Користувач повинен мати можливість вводити екст-опис причини скасування аукціону

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by SoftserveQC1** [comment]
відтворюється на uutb  http://test.tp.uutb.com.ua

**Comment by SergeAntonets** [comment]
![image](https://cloud.githubusercontent.com/assets/7313452/22133106/06769fc8-dec7-11e6-927d-650d93890de7.png)

**Comment by SoftserveQC1** [comment]
Під час обговорення було вирішено, що два варіанти реалізації підходять: наявність поля для введення причини або дропдауна.
