### ISSUE TITLE
torgi.vidol: Переможець аукціону непроінформований про те що протокол необхідно підписати на протязі 3-х діб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1061]
**Опис:** Переможець аукціону непроінформований про те що повинен підписати протокол на протязі 3 діб.

**Кроки:**
1. Як ліквідатор створити та провести аукціон
2.  Добавити учасників до аукціону

**Фактичний результат:** В повідомленні про "Перемогу в торгах по лоту", переможець не отримує інформацію про те що треба підписати аукціон на протязі 3х діб.
![image](https://cloud.githubusercontent.com/assets/13050207/22063986/2ff4cc32-dd8a-11e6-84c1-1cffdbc4d753.png)

![image](https://cloud.githubusercontent.com/assets/13050207/22065200/d090766e-dd8f-11e6-92f2-87ceace948c0.png)

**Очікуваний результат:** Учасник повинен отримати повідомлення про необхідність підписати Протокол на протязі трьох діб. 
**Примітка:** Повідомлення не повинно містити помилок у словах.

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SoftserveQC1** [comment]
відтворюється на uutb http://test.tp.uutb.com.ua

**Comment by SergeAntonets** [comment]
Поправлено.
