### ISSUE TITLE
torgi.vidol: Імейл про підтвердження участі в електронних торгах містить помилки та не має посилання на "правила проведення електронних торгів"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1062]
**Опис:** Користувач отримує повідомлення електронною поштою про підтвердження участі в в електронних торгах з помилками.

**Кроки:** 
1. Як учасник, подати заявку на участь в торгах
2. Переглянути отриманий імейл-підтвердження

**Фактичний результат:** Імейл про підтвердження участі в електронних торгах містить помилки та немає лінки на "правила проведення електронних торгів".
![image](https://cloud.githubusercontent.com/assets/13050207/22069304/9f2e7b6e-dda0-11e6-8557-9d59ac09e09c.png)

**Очікуваний результат:** Імейл не повинен містити помилок, посилання на "правила проведення електронних торгів" повинно бути додане.

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SoftserveQC1** [comment]
відтворюється на uutb http://test.tp.uutb.com.ua посилання відсутнє

**Comment by SergeAntonets** [comment]
Поправлено.
