### ISSUE TITLE
nkcentr: користувач не може здійснити повний цикл роботи з документами.

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1063]
**Опис:** під час реєстрації присутні опції "Додати документ" та "Оновити". 
Видалити документи учасник не може.

**Передумови:** Зареєстрований та підтверджений користувач ролі - Ліквідатор

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Ліквідатор
2.	"Профіль" > "Учасник"
3.	Розділ "Документи учасника" > "Додати документ" > "Обрати файл" > "Завантажити"
4.	Після "Завантажити" вікно завантаження документації залишається відкритим разом з вже завантаженим файлом.
5.	Присутні лише дві опції – "Додати документ" та "Оновити"

**Фактично:**  користувачу доступні дії з доданими документами: "Додати документ" та "Оновити"

**Очікувано:** користувач здійснює повний цикл роботи з Доданими документами:
Додати документ, оновити, видалити, відкрити.

![2017-01-18_1409](https://cloud.githubusercontent.com/assets/20213167/22069808/64519542-dda2-11e6-9494-cec091a99c1f.png)

**Comment by w-be** [comment]
Дублікат 1064 та 1065.
