### ISSUE TITLE
nkcentr: користувач не може здійснити повний цикл роботи з документами. Опція "Оновити" додає документ замість заміни існуючого.

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1064]
**Опис:** в розділі "Документи учасника" не коректно працює опція "Оновити". Замість заміни існуючого документу додається новий.

**Передумови:** Зареєстрований та підтверджений користувач ролі - Ліквідатор

**Кроки:** (Виконуються учасником)
Залогінитись як Ліквідатор
1. "Профіль" > "Учасник"
2. Розділ "Документи учасника" > завантажити/обрати вже завантажений файл > "Оновити"
3. Додається новий файл, хоча мав замінити існуючий. 

**Фактично:** користувач не може застоувати опцію "Оновити" документ. 

**Очікувано:** користувач успішно замінює існуючий докумнет новою версією з допомогою опції "Оновити".

![2017-01-18_1710](https://cloud.githubusercontent.com/assets/20213167/22070270/10a0fc92-dda4-11e6-9a0b-f1acec0ffd36.png)

**Comment by MMarkiyan** [comment]
відтворюється - https://sale.bestbid.com.ua

**Comment by v-lego** [comment]
Внесено зміни:
Так як  це локальне сховище - попередній документ видаляється, а новий додається до списку.

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
