### ISSUE TITLE
nkcentr: користувач не може здійснити повний цикл роботи з документами. Перегляд документа - Server Error

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1065]
**Опис:** під час перегляду документу в розділі "Додати документ" виникає помилка -  Server Error

**Передумови:** Зареєстрований та підтверджений користувач ролі - Ліквідатор

**Кроки:** (Виконуються учасником)
1. Залогінитись як Ліквідатор
2. "Профіль" > "Учасник"
3. Розділ "Документи учасника" > обрати документ для перегляду

**Фактично:**  під час перегляду документу в розділі "Додати документ" виникає помилка -  Server Error

**Очікувано:** користувач має можливість переглянути завантажені документи

![2017-01-18_1351](https://cloud.githubusercontent.com/assets/20213167/22070363/64067434-dda4-11e6-9055-fde82c649f2b.png)

**Comment by v-lego** [comment]
Внесено зміни до отримання документу з локального сховища
