### ISSUE TITLE
torgi.vidol: помилка при завантаженні документів в Internet Explorer

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1066]
**Опис:** Користувач отримує помилку "Недопустимий тип файла" при спробі завантажити файл через Internet Explorer.

**Кроки:**
1. Залогінитись як Ліквідатор через Internet Explorer.
2. Вибрати існуючий лот (або створити новий)
3. Вибрати Дія>Прикріпити документи

**Фактичний результат:** користувач отримує помилку "Недопустимий тип файла", проте файл завантажений успішно і може бути збережений.
![image](https://cloud.githubusercontent.com/assets/13050207/22101542/951fa890-de3c-11e6-96de-295de8b2b222.png)

**Очікуваний результат:** користувач повинен мати змогу успішно завантажити документи відповідного формату, помилки не повинні виникати.

**Comment by SoftserveQC1** [comment]
Дефект відтворюється у cuex http://testing.torgy.com.ua

**Comment by MMarkiyan** [comment]
відтворюється на http://test.torgi.birga-ukraine.com.ua/

**Comment by SoftserveQC1** [comment]
відтворюється на uutb http://test.tp.uutb.com.ua

**Comment by SergeAntonets** [comment]
Под вопросом

**Comment by SergeAntonets** [comment]
Поправлено.
