### ISSUE TITLE
cuex: Неможливо скасувати не підтвержену адмінами пропозицію до аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1068]
http://testing.torgy.com.ua/person/default/cancelbid/?id=55&token=a8bacf197f5e63cef6913994f0a5e008&time=1484831930

**Опис:** При спробі скасувати ще не підтвержену адмінами пропозицію до аукціону користувачеві відкривається пуста сторінка та скасування пропозиції не відбувається

**Передумова:**
- Залогінитись як покупець usser1@mfsa.ru
- Обрати будь-який аукціон (майно банків)

**Відтворення:**
1) Натиснути кнопку "Стати учасником" у тілі аукціона
2) Заповнити всі необхідні поля та натиснути "Подати заявку" у вкладці "Додатки"
3) Натиснути на кнопку "Скасувати пропозицію" (дивись додаток)
![default](https://cloud.githubusercontent.com/assets/13050207/22107640/ace04b04-de57-11e6-8cd8-19792e8ebf91.png)

**Очікуваний результат:** Пропозиція користувача скасовується
**Фактичний результат:** Пропозиція користувача не скасовується, користувачеві відкривається пуста сторінка
![2](https://cloud.githubusercontent.com/assets/13050207/22107645/b40638ee-de57-11e6-9cbf-025684b62a08.png)

**Comment by SergeAntonets** [comment]
Поправлено.
