### ISSUE TITLE
Редагування чекбоксу не зберігаються за першим разом

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#107]
1. При заповненні профілю користувача, в полі "Фізична/юридична особа:" обрати "Юридична особа"
2. Заповнити всі поля, і встановити чекмарк в "Державний замовник" чекбоксі.
3. Нажати кнопку "Зберегти зміни"
4. В "Реєстраційних даних" нажати кнопку "Редагувати профіль"
5. Чекмарк в "Державний замовник" чекбоксі - не встановлений, встановити знову чекмарк "Державний замовник"
6. Нажати кнопку "Зберегти зміни"
7.  В "Реєстраційних даних" нажати кнопку "Редагувати профіль"
8. На цей раз чекмарк в чекбоксі "Державний замовник"  вже встановлений.

Щоб забрати чекмарк з "Державний замовник" чекбоксу, профіль також треба зберігати двічі.

![double_check](https://cloud.githubusercontent.com/assets/10761162/6230456/9fbecbe8-b6c8-11e4-829a-1d3ca9ccb951.png)

**Comment by S-Shevchenko** [comment]
Спасибо, взяли в работу.

**Comment by S-Shevchenko** [comment]
Не воспроизводиться.

**Comment by lerich** [comment]
Закриваю
