### ISSUE TITLE
eauction.brizol: Розмір мінімального кроку аукціону може бути менше 1% та більше від суми початкової ціни продажу лота

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1070]
**Опис:**Користувач може задати Розмір мінімального кроку аукціону < 1% та > 100% від суми початкової ціни продажу лота.

**Кроки:** 

1. Залогінитись як ліквідатор
2. Вибрати 'Мої аукціони'>'Створити аукціон'
3. Введіть відповідні значення та заповніть: Початкова ціна лоту=100000, Розмір мінімального кроку аукціону = 996
4. Натисніть 'Зберегти до чернетки'
5. Виберіть 'Редагувати оголошення'
6. Введіть Початкова ціна лоту=100000, Розмір мінімального кроку аукціону = 100002
7. Натисніть 'Зберегти до чернетки'

**Фактичний результат:** Розмір мінімального кроку аукціону може бути < 1%  та більше від суми початкової ціни продажу лота.

![image](https://cloud.githubusercontent.com/assets/13050207/22112941/6cb54942-de6d-11e6-82b2-a6fbc4078ec9.png)

![image](https://cloud.githubusercontent.com/assets/13050207/22112987/8b334a9a-de6d-11e6-8eef-b3c46d5863e2.png)

**Очікуваний результат:** Розмір мінімального кроку аукціону повинен бути більше >1 % та не може бути більше від початкової ціни продажу лоту.

**Comment by OSerhii** [comment]
Ми дозволяємо користувачу зберігати до чернетки не валідовану інформацію, на то вона і чернетка. Якщо ви спробуєте потім створити аукціон з такими даними, то отримаєте повідомлення про помилку.

**Comment by OSerhii** [comment]
Тобто це не дефект, прошу закрити. Дякую!

**Comment by SoftserveQC1** [comment]
Дефект відтворюється при публікації аукціону, додаю скрін 
http://prnt.sc/dz7zdh
![image](https://cloud.githubusercontent.com/assets/13050207/22203490/08ebe45a-e176-11e6-923f-f0610fb90cec.png)

**Comment by OSerhii** [comment]
так, це відтворюється, дякую! 
Але це вже інший дефект))
Вже пофікшено, прошу перевірити і закрити issue)

**Comment by SoftserveQC1** [comment]
Дефект виправлений та може бути закритий.
