### ISSUE TITLE
TBTELETORG: Після підписання договору, договору та період не з"являються у формі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1072]
Адреса майданчика http://test.etc-torgi.com/
Передумови:
1. Аукціон завершено.
2. Переможця кваліфіковано.
3. Всі не обхідні документи завантажено з боку переможця та організатора.

Кроки для відтворення

1. Під правами організатора акціону увійти в платформу майданчика.
2. Вибрати завершений аукціон.
3. Вибрати підписати договір.
4. Заповнити небохідні поля та завантажити необхіжні документи.
5.Натиснути зберегти
Очікуваний результат: В формі в розділі договори з"являється інформація продоговір. Поля номер договору та період заповнені
Актуальний результат: В формі в розділі договори з"являється інформація продоговір. Поля номер договору та період  не 
![signing_contract](https://cloud.githubusercontent.com/assets/13050207/22116120/267289da-de78-11e6-80a0-aa4c41af914b.jpg)
заповнені

**Comment by greeschenko** [comment]
Вітаю цей момент виправлено

**Comment by SoftserveQC1** [comment]
Пофіксано, можна закривати.
