### ISSUE TITLE
nkcentr: Під час формування лоту доступні для вибору інші види валюти які не допускаються до використання в аукціоні, що вводить користувача в оману та приводить до появи оголошення про помилку.

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1073]
**Опис:** під час формування заявки лоту доступні для вибору EUR, GBP, RUB, USD. При спробі збереження заявки з іншими валютами окрім UAH зявляється помилка англійською.

**Передумови:** Зареєстрований та підтверджений користувач ролі - Ліквідатор

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Ліквідатор
2.	Аукціони > Новий аукціон > Оголошення аукціону з продажу: > Валюта

**Фактично:** доступні для користувача опції використання яких призводить до помилки.

**Очікувано:** користувач вибирає доступні опції для успішного формування заявки.

![123](https://cloud.githubusercontent.com/assets/20213167/22139434/9486610a-deee-11e6-9cd2-3d9746374aaf.jpg)

![default](https://cloud.githubusercontent.com/assets/20213167/22139469/d67b1362-deee-11e6-86c9-f3ecfd834c11.jpg)

**Comment by MMarkiyan** [comment]
відтворюється - https://sale.bestbid.com.ua

**Comment by v-lego** [comment]
Вибір валют прибрано

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
