### ISSUE TITLE
nkcentr: Відсутня валідація обов’язкових полів: Номер лоту в ФГВ та Загальна назва аукціону

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1074]
**Опис:** під час збереження заявки лоту не перевіряються обов’язкові поля:
- Номер лоту в ФГВ
- Загальна назва аукціону

**Передумови:** Зареєстрований та підтверджений користувач ролі - Ліквідатор

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Ліквідатор
2.	Аукціони > Новий аукціон > Оголошення аукціону з продажу:

**Фактично:** обовязкові для заповнення поля можуть бути пропущені користувачем. Валідація відбувається лише з Початкова ціна реалізації лоту.

**Очікувано:** всі обовязкові для заповнення поля перевіряються перед збереженням

![2017-01-19_1450](https://cloud.githubusercontent.com/assets/20213167/22139504/107a49ca-deef-11e6-809a-8456c71c2bbf.png)

**Comment by v-lego** [comment]
Змінено порядок перевірки відповідно до відображення полів на формі
всі поля, позначених зірочкою, мають перевірку обов'язкового заповнення

**Comment by SoftserveQC1** [comment]
Дефект виправлено відповідно до змін відкрито новий дефект #1286
