### ISSUE TITLE
nkcentr: Некоректна робота дропбоксу – Лоти виставляються

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1075]
**Опис:** Дроб бокс "Лоти виставляються" по замовчуванню вибирає значення "1" хоча присутнє перше значення - "Не відомо"

**Передумови:** Зареєстрований та підтверджений користувач ролі - Ліквідатор

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Ліквідатор
2.	Аукціони > Новий аукціон > Оголошення аукціону з продажу:

**Фактично:** форма самостійно виконує дію вибору замість користувача

**Очікувано:** користувач самостійно обирає котрий раз виставляється лот на аукціон

![2017-01-19_2113](https://cloud.githubusercontent.com/assets/20213167/22139560/75f1cb0c-deef-11e6-8f29-f3b0700e07cf.png)

![default](https://cloud.githubusercontent.com/assets/20213167/22139561/79bad65c-deef-11e6-9fd6-5a4d1a23ce9b.jpg)

**Comment by georgedp** [comment]
Заведеденный тикет не является дефектом и не противоречит требованиям.

Выдержка из чек листа:
Лот виставляється на торги: (1, 2, 3, 4, Не відомо) 

Требования:
Поле для нумерації спроб продажу активу/майна
Неймінг: Лоти виставляються
Поле: tenderAttempts
Опис: Селект від 1 до 4 + варіант “Не відомо”. Якщо точно не знаємо , обираємо “Не відомо” при заведенні. В такому випадку в `tenderAttempts` нічого не пишемо (attention, ЦБД приймає варіанти тільки від 1 до 4!), в description додаємо інформацію “Торги проводяться повторно”
	Варіанти на виводі:
`tenderAttempts` == 1 - Лот виставляється вперше
`tenderAttempts` == от 2 до 4 - Лот виставляється повторно
`tenderAttempts` == невідомо - блок “Лот виставляється на торги” відсутній, інформація виводиться в блоці Загальна інформація про торги (поле description)

**Comment by MMarkiyan** [comment]
відтворюється - https://sale.bestbid.com.ua

**Comment by w-be** [comment]
Так це не баг. Це побажання, по зручності.

**Comment by v-lego** [comment]
Встановлено первинне значення елементу "виберіть значення"

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
