### ISSUE TITLE
nkcentr: Розділ реєстрації учасника - після застосування "Оновлення" документів,  застаріла версія залишається без позначки що вона не актуальна

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1077]
**Опис:** після оновлення весії документу в розділі "Додати документ" застаріла версія залишається без позначки що вона не актуальна

**Передумови:** Зареєстрований та підтверджений користувач

**Кроки:** (Виконуються учасником)
1. Залогінитись
2. Профіль > Учасник
3. Розділ Документи учасника > Оновити документ

**Фактично:** під час оновлення версії документу відбувається нове завантаження. Застарілий документ не має жодних позначок

**Очікувано:** після оновлення документу попередня версія отримує позначку як не актуальна та додається новий документ

![2017-01-20_1227](https://cloud.githubusercontent.com/assets/20213167/22146005/f364a49e-df0b-11e6-8cd1-ad1e3bbebc45.png)

**Comment by MMarkiyan** [comment]
відтворюється - https://sale.bestbid.com.ua

**Comment by v-lego** [comment]
Внесено зміни:
попередній документ видаляється, новий додається до списку

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
