### ISSUE TITLE
nkcentr: Налаштування лоту - після застосування "Оновлення" документів, застаріла версія залишається без поміток

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1078]
**Опис:** під час оновлення документу в розділі "Додати документ"

**Передумови:** Зареєстрований та підтверджений користувач

**Кроки:** (Виконуються учасником)
1.	Залогінитись як Ліквідатор
2.	Створити лот
3.	Відкрити лот > Документи аукціону – Додати документ

**Фактично:** під час оновлення версії документу відбувається нове завантаження. Застарілий документ не має жодних позначок

**Очікувано:** після оновлення документу попередня версія отримує позначку як не актуальна та додається новий документ

![2017-01-20_1432](https://cloud.githubusercontent.com/assets/20213167/22149605/566d58b8-df1d-11e6-9eec-c18fed2e97df.png)

**Comment by SoftserveQC1** [comment]
Дефект відтворюється на agrex  https://etp.agrex.gov.ua/test/

**Comment by MMarkiyan** [comment]
Відтворюється для https://sale.bestbid.com.ua

**Comment by v-lego** [comment]
Відновлено функціональність:
Попередні версії відображуюються перекресленими

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
