### ISSUE TITLE
nkcentr: Розділ оформлення лоту - з допомогою опції  "Додати документ", можливо виконувати записи без публікації матеріалів(документи та ін.)

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1079]
**Опис:** в розділі оформлення лоту - "Додати документ", можливо виконувати записи без публікації матеріалів(документи та ін.)

**Передумови:** Зареєстрований та підтверджений користувач

**Кроки:** (Виконуються учасником)
1. Залогінитись як Ліквідатор
2. Створити лот
3. Відкрити лот > Документи аукціону – Додати документ
4. Кнопка - Завантажити

**Фактично:** відбувається виконання запису без прикріплених матеріалів

**Очікувано:** запис виконується з необхідним додатком

![2017-01-20_1431](https://cloud.githubusercontent.com/assets/20213167/22149717/104385d2-df1e-11e6-86ff-d62c9169df05.png)

![2017-01-20_1431_001](https://cloud.githubusercontent.com/assets/20213167/22149718/1043c54c-df1e-11e6-8954-16ae7747a52d.png)

**Comment by MMarkiyan** [comment]
відтворюється - https://sale.bestbid.com.ua

**Comment by SoftserveQC1** [comment]
Дефект відтворюється на agrex https://etp.agrex.gov.ua/test/

**Comment by v-lego** [comment]
Встановлено відображення типу документу одразу при публікації

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
рекомендовано локалізувати ерор-повідомлення українською
![1](https://cloud.githubusercontent.com/assets/13050207/25802682/0e7bc100-33fc-11e7-8e6a-cbb978e88575.png)
