### ISSUE TITLE
Форма звітування про проблему

### ISSUE THREAD

**Issue by myroslav** [openprocurement/frontend#108]
Офіційна форма http://ppr.org.ua/povidomlennya-pro-problemu/ поламана. Варто відновити її роботу.

**Comment by myroslav** [comment]
@SergeyShevchenko1 підписуйтеся на нотифікації, щоб знати коли проблему буде усунуто

**Comment by S-Shevchenko** [comment]
@myroslav Підписаний.

**Comment by myroslav** [comment]
Згідно з листом від Андрія, проблема усунута. Відповідальні від майданчиків отримали URL з таблицею, де реєструватимуться звіти про помилку в електронній пошті в листі з заголовком "Re: Е-Тендер".
