### ISSUE TITLE
eauction.brizol: Користувач може відправити пусте запитання (Internet Explorer)

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1080]
**Опис:** Користувач може відіслати пусте запитання залогінившись в Internet Explorer

**Кроки:**

1. Залогінитись як Учасник в ІЕ
2. Вибрати Запитання>Відповіді
3. Не вводити нічого та натиснути кнопку 'Подати Запитання'

**Фактичний результат:** користувач отримує повідомлення: "Питання успiшно вiдправлено"
![image](https://cloud.githubusercontent.com/assets/13050207/22150295/ec584452-df20-11e6-8d9e-e702a3b5ff77.png)

**Очікуваний результат:** Користувач не повинен мати змоги відправляти пусті запитання.

**Comment by OSerhii** [comment]
Вияснили, дефект відтворюється для ІЕ 7. Ця версія ІЕ не підтримується майданчиком.
Прошу закрити issue, дякую!
