### ISSUE TITLE
nkcentr: Відсутнє інформування користувача під час його сесії про нові/непрочитані повідомлення

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1081]
**Опис:** Користувач не проінформований про нові та непрочитані повідомлення. За вимогами: Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до Лоту

**Передумови:** Зареєстрований та підтверджений користувач

**Кроки:** (Виконуються учасником)
1. Виконати вхід
2. Профіль > Повідомлення
3. Знаходяться не прочитані повідомлення.

**Фактично:** відсутнє інформування користувача про нове або не прочитане повідомлення

**Очікувано:**  Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до Лоту

**Comment by SoftserveQC1** [comment]
Дефект відтворюється на agrex https://etp.agrex.gov.ua/test/

**Comment by v-lego** [comment]
Встановлено 
Одразу при завантаженні сторінки і потім кожну хвилину виконується запит на непрочитані повідомлення, За наявності повідомлень віодбражується блокуюче вікно з повідомленнями.

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
