### ISSUE TITLE
nkcentr: Прочитані та не прочитані повідомлення мають однаковий вигляд

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1082]
**Опис:** Прочитані та не прочитані повідомлення мають однаковий вигляд, що може ввести кінцевого користувача в оману і він може пропустити важливу інформацію про перебіг аукціону. Не помітивши різницю між вже прочитаними та ще не прочитаними повідомленнями.

**Передумови:** Зареєстрований та підтверджений користувач

**Кроки:** (Виконуються учасником)
1.	Виконати вхід
2.	Профіль > Повідомлення

**Фактично:** у вхідних повідомленнях немає змоги відрізнити прочитані та не прочитані повідомлення

**Очікувано:** Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до Лоту

![2017-01-20_1529](https://cloud.githubusercontent.com/assets/20213167/22151125/5b68e0fa-df25-11e6-9246-d3eb4344a2d1.png)

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by v-lego** [comment]
Встановлено для прочитаних повідомлень сірий фон

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
