### ISSUE TITLE
Privat: файл договору не відображається після завантаження

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1084]
Майданчик: https://sell.pb.ua
користувач: +380102030405
Передумова: аукціон з визначеним переможцем

Сценарій: 
1. Авторизуватись
2. Відкрити аукціон з передумови
3. Долучити та завантажити договір

Очікувано: договір відображається
Фактично: договір не відображається
![image](https://cloud.githubusercontent.com/assets/13050207/22152291/c607331c-df2a-11e6-8e06-d3e71e6a72a4.png)

**Comment by pbil** [comment]
виправлено

**Comment by SoftserveQC1** [comment]
договір завантажується і відображається. дефект виправлено.
