### ISSUE TITLE
eauction.brizol:  Ліквідатор не отримує сповіщення про отримання запитання до лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1085]
**Опис:**  Ліквідатор не отримує повідомлення про запитання до Лоту в особистому кабінеті

**Кроки:**
1. Залогінитись як Учасник
2. Вибрати Запитання>Відповіді 
3. Задати запитання до лоту
4. Залогінитись як Ліквідатор

**Фактичний результат:** Ліквідатор не отримує повідомлення про отримане запитання до лоту в особистому кабінеті. 

**Очікуваний результат:** Ліквідатор повинен отримати повідомлення про запитання до Лоту в особистому кабінеті при наступному вході в нього.

**Comment by OSerhii** [comment]
Це не зовсім вірно. Уже неодноразово оговорювали реалізацію цього механізму на наших майданчиках. Повідомлення з'являється у кабінеті Ліквідатора примусово модальним вікном раз у сутки при першій авторизації і буде виводитися при кожній авторизації, доки користувач не перейде на сторінку і відповість на запитання, або аукціон перейде у статус завершений, відмінений чи скасований та відпрацює скрипт по крону, який запускається раз у сутки о 2.00.

**Comment by OSerhii** [comment]
Прошу закрити issue, дякую!

**Comment by OSerhii** [comment]
Пофіксили, перевірте будь ласка)
