### ISSUE TITLE
nkcentr: вживається визначечення - Тендер при проведенні Аукціон, Розділ подати пропозицію

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1086]
**Опис:**  помилка в повідомленнях, інформація про участь/зміни/ тендера

**Передумови:** Зареєстрований та підтверджений користувач

**Кроки:** (Виконуються учасником)
1.	Виконати вхід, роль Учасника аукціону
2.	Аукціони > обрати потрібний аукціон > Пропозиція
3.	У верхньому лівому кутку вказано Тердер та Номер

**Фактично:** не коректне інформування учасника аукціону про його участь в тендері 

**Очікувано:** в розділі Подати пропозицію вказана інформація про аукціон та його номер

![2017-01-23_0807](https://cloud.githubusercontent.com/assets/20213167/22197821/5ce9e472-e15c-11e6-93c1-2b57f397b7ea.png)

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by v-lego** [comment]
Замінено на вживання слова "аукціон"

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
![2](https://cloud.githubusercontent.com/assets/13050207/25802769/7c4e68b8-33fc-11e7-9728-2b6c226ec7cf.png)
