### ISSUE TITLE
nkcentr: вживається визначечення - Тендер при проведенні Аукціон, інформаційні повідомлення на email

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1087]
**Опис:** помилка в повідомленнях, інформація про участь/зміни/ тендера

**Передумови:** Зареєстрований та підтверджений користувач

**Кроки:** (Виконуються учасником)
1. Зайти у вхідні повідомлення email
2. Відкрити повідомлення від nkc.biz.ua

**Фактично:** не коректне інформування учасника аукціону про його участь в тендері 

**Очікувано:** учасник аукціону отримує повідомлення про участь в аукціоні

![2017-01-23_0826](https://cloud.githubusercontent.com/assets/20213167/22197968/0b41dcfa-e15d-11e6-9043-c03e89b0f5cf.png)

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua, в нагадуваннях з 00:00 ночі

**Comment by v-lego** [comment]
Замінено на вживання слова "аукціон"

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
