### ISSUE TITLE
nkcentr: Переможець аукціону не має змоги перейти до аукціону з допомогою посилання  в листі

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1088]
**Опис:** після визнання учасника торгів Переможцем аукціону, надходять повідомлення про його статус(Переможець аукціону) за адресою email та у розділ повідомлень майданчика.
Лінк на аукціон з email повідомлення направляє на не існуючу сторінку

**Передумови:** Зареєстрований та підтверджений користувач
Кроки: (Виконуються учасником)
1.	Зайти у вхідні повідомлення email
2.	Відкрити повідомлення про визнання учасника переможцем аукціону від nkc.biz.ua

**Фактично:** не працюючий лінк на аукціон

**Очікувано:** переможець аукціону сповіщений про перемогу та переходить на аукціон за допомогою посилання у повідомленні

![2017-01-23_1124](https://cloud.githubusercontent.com/assets/20213167/22198607/eb649172-e15f-11e6-97ae-4c4bf8b1abbc.png)

![2017-01-23_1125](https://cloud.githubusercontent.com/assets/20213167/22198610/ef2752ea-e15f-11e6-937f-dc4244f17e6b.png)

**Comment by v-lego** [comment]
Посилання йде не сторінку тендера. На самій сторінці є посилання на модуль аукціону.
Вимоги наявності посилання на саме проведення аукціону до повідомлення Про визнання переможцем немає. Посилання на модуль аукціону присутнє тільки у повідомленні після завершення періоду прийому пропозицій.
Відтворити ламане посилання не змогли. Можливо, воно ламається конкретним поштовим клієнтом.
