### ISSUE TITLE
nkcentr: Кваліфікація Переможця аукціону, присутність неточностей сценарію

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1089]
**Опис:** Користувач майданчику заходить до аукціону щоб пройти Кваліфікацію і бачить відсутність опцій для кваліфікації
Продовжити кваліфікацію може в розділі Пропозиція 

**Передумови:** Зареєстрований та підтверджений користувач

**Кроки:** (Виконуються учасником)
1.	Виконати вхід, роль Учасника аукціону
2.	Аукціони > обрати потрібний аукціон

**Фактично:** Шлях для здійснення Кваліфікації не очевидний користувачу. Сама Кваліфікація має вигляд не доступної, а щоб завершити процедуру потрібно застосовувати опцію - Пропозиція яка використовувалась для подачі першої ставки по лоту.

**Очікувано:** Переможець аукціону проходить чітку та зрозумілу процедуру кваліфікації 

Розділ Кваліфікація у вікні аукціону
![2017-01-23_0918](https://cloud.githubusercontent.com/assets/20213167/22200275/1ab90c08-e167-11e6-8c66-92d67c68e2c2.png)

Доступна Кваліфікація у розділі Пропозиція
![default](https://cloud.githubusercontent.com/assets/20213167/22200308/3d365c68-e167-11e6-9dda-c16264faa5a6.jpg)

Вигляд кваліфікації
![2017-01-23_0925](https://cloud.githubusercontent.com/assets/20213167/22200354/730caa7c-e167-11e6-9f20-863e55f6394b.png)

**Comment by v-lego** [comment]
Внесено зміни
У розділі кваліфікації для Переможця відображується повідомлення з посиланням на протокол Порталу (продуктового) та рекомендацією дій.

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
