### ISSUE TITLE
Після реєстрації нового користувача, система не направляє повідомлення для подальшої активації, на адресу електронної пошти користувача.

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#109]
Було здійснене очікування на повідомлення для подальшої активації протягом більше 20 хвилин.

![no_acknowledge](https://cloud.githubusercontent.com/assets/10761162/6245085/59bd7c66-b763-11e4-9dce-396c0d986e1a.png)

**Comment by S-Shevchenko** [comment]
Письмо пришло?

**Comment by yuliyaSoftserve** [comment]
Зараз, повідомлення для подальшої активації на скриньку користувача вже приходить, але
користувач не може зайти в систему під своїм логіном.

![unsuccessful_registration](https://cloud.githubusercontent.com/assets/10761162/6248731/3b47eae6-b78b-11e4-83b8-acc22b476c21.png)

**Comment by S-Shevchenko** [comment]
Ваш запит не був активований....Ви можете надалі проводити тестування на сайті http://services.e-tender.biz:99/#/

**Comment by OksanaPakholok** [comment]
Ця проблема перевірена і вже вирішена. Не репродюситься. ЇЇ можна закривати

**Comment by lerich** [comment]
Закриваю.
