### ISSUE TITLE
Centrex: UI помилки в системі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1092]
**Лінк:** http://eauction.centrex.com.ua
**Браузер**  Firefox 50.1.0

1. Видно тільки частину кнопки "Створити аукціон" 

![default](https://cloud.githubusercontent.com/assets/13050207/22240891/b074f464-e225-11e6-8510-3278eb139fae.png)

2. Кнопка для закриття вікна питання зміщена.

![events2](https://cloud.githubusercontent.com/assets/13050207/22240982/1528ab58-e226-11e6-868f-44c4fa5ca3cb.png)

3.  На всіх сторінках відображається пустий елемент

![error4](https://cloud.githubusercontent.com/assets/13050207/22240997/2a2706b2-e226-11e6-8acb-7b76f78fbf02.png)

**Comment by SoftserveQC1** [comment]
Дефект відтворюється на aukzionua http://torgi.aukzion.com.ua

**Comment by PaulBoroday** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено на aukzionua http://torgi.aukzion.com.ua
