### ISSUE TITLE
aukzionua: При спробі опублікувати аукціон у якому не заповнені дата та номер рішення ФГВФО відображається сторінка з ерором

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1093]
http://torgi.aukzion.com.ua/buyer/tender/create

**Опис:** При спробі опублікувати аукціон у якому заповнені всі обов'язкові поля та не вказані дата та номер рішення ФГВФО з'являється повідомлення із ерором який містить фрагмент коду

**Передумова:**

- Увійти на майданчик під логіном checkdto@gmail.com
- Перейти до розділу "Мої ацкціони"
- Натиснути кнопку "Створити аукціон"
- Проскролити вниз сторінки та натиснути "Зберегти та перейти до публікації", щоб усі обов'язкові поля були виділені червоним кольором

**Відтворення:**

1) Заповнити усі обов'язкові поля валідними даними
2) Залишити пустими поля "Рішення виконавчої дирекції ФГВФО про затвердження умов продажу" "від" та "№"
3) Проскролити вниз сторінки та натиснути "Зберегти та перейти до публікації"

**Очікуваний результат:** Поля "Рішення виконавчої дирекції ФГВФО про затвердження умов продажу" виділені червоним, біля них повідомлення "Необхідно заповнити "Дата рішення виконавчої дирекції ФГВФО про затвердження умов продажу" та "Необхідно заповнити "№ рішення"", публікація не відбувається

**Фактичний результат:** Відображається повідомлення про помилку із фрагментами коду
![default](https://cloud.githubusercontent.com/assets/13050207/22241168/f75b9fc6-e226-11e6-81db-0500e8c6d9d7.png)

**Comment by PaulBoroday** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
