### ISSUE TITLE
Centrex: граматичні помилки в системі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1094]
**Лінк:** http://eauction.centrex.com.ua
**Кроки:**
1. Відкрити сторінку реєстрації. 

![error1](https://cloud.githubusercontent.com/assets/13050207/22242347/a52c0984-e22b-11e6-8be7-a602f3d24a84.png)

![error2](https://cloud.githubusercontent.com/assets/13050207/22242351/aba5be5e-e22b-11e6-886e-f8b2bb146852.png)

2. Увійти в систему та натиснути на випадаючий список "Мої фінанси"

![error3](https://cloud.githubusercontent.com/assets/13050207/22242375/c9287462-e22b-11e6-8bb3-e970532f47ea.png)

3. Слово 'Events' не перекладено

![events](https://cloud.githubusercontent.com/assets/13050207/22242388/d577e392-e22b-11e6-9543-691a3cd9eb27.png)

**Comment by SoftserveQC1** [comment]
Дефект відтворюється на aukzionua http://torgi.aukzion.com.ua

**Comment by PaulBoroday** [comment]
Виправили

**Comment by SoftserveQC1** [comment]
Дефекти №1 та №2 відтворюються на aukzionua http://torgi.aukzion.com.ua

**Comment by SoftserveQC1** [comment]
пункт №1 досі відтворюється на Centrex

**Comment by OSerhii** [comment]
Виправлено.
