### ISSUE TITLE
aukzionua: Поля "Рішення виконавчої дирекції ФГВФО" не відображаються як обов'язкові

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1095]
http://torgi.aukzion.com.ua/buyer/tender/create

**Опис:** Дата та номер Рішення виконавчої дирекції ФГВФО про затвердження умов продажу не виділяються як обов'язкові

**Передумова:**

- Увійти на майданчик під логіном checkdto@gmail.com

**Відтворення:**

1) Перейти до розділу "Мої ацкціони"
2) Натиснути кнопку "Створити аукціон"
3) Проскролити вниз сторінки та натиснути "Зберегти та перейти до публікації", щоб усі обов'язкові поля були виділені червоним кольором

**Очікуваний результат:** Поля "Рішення виконавчої дирекції ФГВФО про затвердження умов продажу" виділені червоним, біля них повідомлення "Необхідно заповнити "Дата рішення виконавчої дирекції ФГВФО про затвердження умов продажу" та "Необхідно заповнити "№ рішення""

**Фактичний результат:** Поля "Рішення виконавчої дирекції ФГВФО про затвердження умов продажу" не виділені як обов'язкові
![default](https://cloud.githubusercontent.com/assets/13050207/22243830/ab9272d0-e231-11e6-89ab-bcc3597c8262.png)

**Comment by SoftserveQC1** [comment]
відтворюється на https://eauction.brizol.net

**Comment by SoftserveQC1** [comment]
відтворюється на Centrex  http://eauction.centrex.com.ua

**Comment by OSerhii** [comment]
Пофіксили)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
