### ISSUE TITLE
nkcentr: ліквідатор має можливість відмінити аукціон без завантаження обов'язкових документів про скасування торгів

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1096]
**Опис:** аукціон може бути скасований без документів про скасування торгів

**Передумови:** Зареєстрований та підтверджений користувач ролі Ліквідатор

**Кроки:** (Виконуються учасником)
1. Виконати вхід, роль Ліквідатор
2. Аукціони > обрати діючий аукціон > Скасувати
3. Відміна > Скасувати запит

**Фактично:** ліквідатор має можливість відмінити аукціон без завантаження обов'язкового документа про скасування

**Очікувано:** ліквідатор скасовує аукціон заповнивши всі обовязкові поля та прикріпляє документи що засвідчують причину скасування

![2017-01-24_1226](https://cloud.githubusercontent.com/assets/20213167/22244608/e686f6ce-e234-11e6-98fe-bdd945ff48f2.png)

![2017-01-24_1228](https://cloud.githubusercontent.com/assets/20213167/22244612/ea1e2bcc-e234-11e6-9f71-1d0be29b01f5.png)

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by v-lego** [comment]
Встановлено заборону активації рішення без документів

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
![0](https://cloud.githubusercontent.com/assets/13050207/25803028/c353e50c-33fd-11e7-95e2-e3b96d1c56c6.png)
![1](https://cloud.githubusercontent.com/assets/13050207/25803027/c353ef3e-33fd-11e7-8d11-9f9a26bd02e0.png)
