### ISSUE TITLE
aukzionua: Ліквідатор має можливість відмінити аукціон без завантаження обов'язкових документів про скасування торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1097]
http://torgi.aukzion.com.ua/buyer/tender/cancel/

**Опис:** Ліквідатор має можливість відмінити аукціон без завантаження обов'язкових документів про скасування торгів

**Передумова:**
- Увійти на майданчик під логіном checkdto@gmail.com
- Перейти до розділу "Мої ацкціони"
- Натиснути кнопку "Створити аукціон"
- Заповнити усі обов'язкові поля валідними даними
- Проскролити вниз сторінки та натиснути "Зберегти та перейти до публікації"

**Відтворення:**
1) У правому меню "Очікування пропозицій" натиснути кнопку "Скасувати аукціон/лот"
2) У меню скасування обрати об'єкт та причину
3) Натиснути кнопку "Скасувати"

**Очікуваний результат:** Скасування не відбудеться, бо не завантажені обов'язкові документи про скасування торгів, про що з'являється відповідне повідомлення для користувача

**Фактичний результат:** Скасування успішно відбувається
![skas1](https://cloud.githubusercontent.com/assets/13050207/22247044/75d1cba0-e240-11e6-8bc5-ba89310fa00b.png)
![skas2](https://cloud.githubusercontent.com/assets/13050207/22247045/75eb6fce-e240-11e6-8eb1-40e84d0ba5ea.png)

**Comment by OSerhii** [comment]
Пофіксили)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
