### ISSUE TITLE
aukzionua: Невірні назви статусів для скасованих аукціонів, аукціонів що не відбулися та успішно завершених

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1098]
http://torgi.aukzion.com.ua/buyer/tenders/index

**Опис:** Скасовані аукціони (cancelled) відображаються зі статусом "Відмінена" замість "Торги відмінено", аукціони, що не відбулися (unsuccessful) відображаються як "Торги відмінено" замість "Торги не відбулися", а успішно пройдені (complete) відображаються як "Завершена" замість "Продаж завершений"
Рекомендовано змінити неймінг також внести аналогогічні зміни назв у сортуванні (додаток2)

**Відтворення:**
1) Увійти на майданчик під логіном checkdto@gmail.com
2) Перейти до розділу "Мої аукціони" та переглянути неймінг статусів аукціонів

**Очікуваний результат:** 
- Статус cancelled - Торги відмінено
- Статус unsuccessful - Торги не відбулися
- Статус complete - Продаж завершений

**Фактичний результат:**
- Статус cancelled - Відмінена
- Статус unsuccessful - Торги відмінено
- Статус complete - Завершена
![1](https://cloud.githubusercontent.com/assets/13050207/22247752/0c2f0ef2-e244-11e6-80a6-a60cdcf298d2.png)

![2](https://cloud.githubusercontent.com/assets/13050207/22247757/1279f858-e244-11e6-853b-055bb9b19126.png)

**Comment by PaulBoroday** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
