### ISSUE TITLE
nkcentr: відсутній період уточнень по лоту в описі аукціону

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1099]
**Опис:** в умовах аукціону відсутня інформація про період уточнень

**Кроки:** (Виконуються учасником)

1. Виконати вхід використовуючи будь яку роль
2. Аукціони > обрати діючий аукціон
3. Пунк опису Період уточнень з ____ до____

**Фактично:** відсутній період уточнень по лоту в описі аукціону

**Очікувано:** користувач майданчика має можливість ознайомлюватись з доступною інформацією проведення та умов участі аукціону 

![2017-01-24_1510](https://cloud.githubusercontent.com/assets/20213167/22248690/86f4bd7c-e248-11e6-9e52-9d69298331cc.png)

**Comment by oleksandrakulenko** [comment]
Майданчику потрібно видалити блок "Період уточнень", так як ці дати відсутні у Прозоро.Продажах

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua
