### ISSUE TITLE
"Internal Server Error" при підписанні контракту

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#110]
1. Зайти замовником у свій тендер, який має статус "Пропозиції розглянуто"
2. Натиснути кнопку "Контракт" у нижній частині вікна.
3. В полі "Опис" додати опис.
4. Натиснути кнопку "Додати документ" і добавити його.
5. Натиснути кнопку "Підписати"

![sign_contract](https://cloud.githubusercontent.com/assets/11062040/6252182/22ee2eae-b7a1-11e4-8608-353142de003c.png)

**Comment by S-Shevchenko** [comment]
Спасибо, знаем... разбираемся.

**Comment by S-Shevchenko** [comment]
Не воспроизводиться.
