### ISSUE TITLE
nkcentr: помилка в описі аукціону(використання терміну - тендер)

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1100]
**Опис:** міститься помилка в описі аукціону

**Передумови:** Зареєстрований та підтверджений користувач ролі Ліквідатор

**Кроки:** (Виконуються учасником)
1. Виконати вхід, роль Ліквідатор
2. Аукціони > Новий аукціон
3. Оголошення аукціону з продажу: майна банків
4. Вид забезпечення тендерних пропозиції

**Фактично:** міститься помилка в описі - Вид забезпечення тендерних пропозиції.
Неохідно замінити на Вид забезпечення участі в аукціоні

**Очікувано:** в описі аукціону міститься інформація про умови участі

![2](https://cloud.githubusercontent.com/assets/20213167/22249307/1cb4e506-e24b-11e6-8c45-688b88af218c.jpg)

**Comment by MMarkiyan** [comment]
відтворюється - https://sale.bestbid.com.ua

**Comment by v-lego** [comment]
Замінено на вживання слова "аукціон"

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
