### ISSUE TITLE
nkcentr: уніфікація термінів (Електронна гарантія - Гарантійний внесок)

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1101]
**Опис:** на майданчику використовуються різні терміни з однаковим сенсом що може заплутати кінцевого користувача

**Передумови:** Зареєстрований та підтверджений користувач 

**Кроки:** (Виконуються учасником)
1. Виконати вхід, роль Ліквідатор
2. Аукціони > Новий аукціон
3. Оголошення аукціону з продажу: майна банків
4. Вид забезпечення тендерних пропозиції:
•	Електронна гарантія
•	Відсутнє

**Фактично:** на майданчику міститься два терміни які необхідно уніфікувати.
При оформленні - Електронна гарантія, під час початкової ставки - Гарантійний внесок

**Очікувано:** користувач обирає вид забезпечення аукціону з варіантів:
•	Гарантійний внесок
•	Відсутнє

![default](https://cloud.githubusercontent.com/assets/20213167/22248978/c22574bc-e249-11e6-9fc4-6a5547b32630.jpg)

![2017-01-23_0853](https://cloud.githubusercontent.com/assets/20213167/22248987/ccf9926a-e249-11e6-8217-65ab78d55f59.png)

**Comment by MMarkiyan** [comment]
відтворюється - https://sale.bestbid.com.ua

**Comment by v-lego** [comment]
Внесено зміни: використовується термін "Гарантійне забезпечення"

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
![2](https://cloud.githubusercontent.com/assets/13050207/25803081/f3893452-33fd-11e7-8b3e-75282d7c90f8.png)
