### ISSUE TITLE
nkcentr: немає нагадування про запитання/пропозицію без відповіді(згідно вимог сценарію ручного тестування електронних майданчиків, пункт №12)

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1102]
**Опис:** відсутнє нагадування про запитання/пропозиції без відповіді на майданчику

**Передумови:** Зареєстровані та підтверджені користувачі, ролі Ліквідатора та Клієнт майданчика

**Кроки:** (Виконуються учасником)
1. Виконати вхід, роль Ліквідатора
2. Розпочати аукціон
3. Задати питання по аукціону з акаунта Клієнта
4. Ліквідатор, впродовж доби, не отримує нагадування від майданчика про запитання.
5. Нагадування надходить лише піля 00:00 на email.

**Фактично:** Ліквідатор отримує нагадування лише на електронку і тільки після 00:00. Якщо Ліквідатор проводить аукціон з 9-18, впродовж цього часу отримує запитання і не відповідає на нього, тоді існує висока ймовірність що клієнт не буде робити ставок на лот який не супроводжується належним чином 

**Очікувано:** про всі запитання/пропозиції Ліквідатор негайно інформується. Постійно отримує нагадування які не можливо проігнорувати.(Наприклад блокується вікно майданчика, поки Ліквідатор не прочитає повідомлення)

**Comment by v-lego** [comment]
Повідомлення про нове запитання передаються одразу і на сторінку повідомлень і на пошту 
на сторінці повідомлень 
![default](https://cloud.githubusercontent.com/assets/24773833/22271970/2313d7f4-e2a0-11e6-82d6-99909cd7af81.png)
в в описі ручних тестів чітко вказано "Отримати повідомлення про запитання до Лоту в особистому кабінеті Організатора при наступному вході в нього."
Все інше, на розгляд кожного майданчика окремо
Також нагадування на питання без відповіді надаються КОЖНОГО дня. Коли - не вказано.
В нашій реалізації спрацьовують задачі обробки дня о 00:00

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by v-lego** [comment]
Додали нагадування ще і  до повідомлень на майданчику (на електронну пошту повідомлення надходили)

**Comment by MMarkiyan** [comment]
Виправлено

![2017-01-30_1249](https://cloud.githubusercontent.com/assets/20213167/22420338/b16d1e4a-e6ea-11e6-9e77-9ed7ba12fb60.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
