### ISSUE TITLE
bestbid: ЗАБЛОКАНИЙ, відсутня можливість завершити реєстрацію

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1103]
**Опис:** користувач не має змоги завершити реєстрацію. Після команди Зберегти та Підтвердити відсутня очікувана поведінка. Сторінка не оновлюється, зміни відсутні.

**Кроки:** (Виконуються учасником)
1. Залогінитись
2. Розділ - Учасник
3. Заповнити всі обовязкові поля
4. Обрати опцію - Зберегти
5. Обрати опцію - Підтвердити

**Фактично:** користувач не може завершити реєстрацію, що в свою чергу блокує роботу з аукціонами

**Очікувано:** користувач успішно проходить процедуру реєстрації, всі обовязкові поля заповнено, інформація збережена, про реєстрацію повідомлено в розділі Повідомленн та на email.

Профіль учасника заповнено
![2017-01-24_2249](https://cloud.githubusercontent.com/assets/20213167/22266540/10056f40-e289-11e6-87c4-6aba994a653e.png)

натискання кнопки - Зберегти
![default](https://cloud.githubusercontent.com/assets/20213167/22266550/192513d2-e289-11e6-9cfb-2a3e4b356d7b.jpg)

натискання кнопки - Підтвердити
![2](https://cloud.githubusercontent.com/assets/20213167/22266551/1938925e-e289-11e6-882e-d80a2d84e676.jpg)

Повторне відкриття Учасника
![2017-01-24_2253](https://cloud.githubusercontent.com/assets/20213167/22266561/1f7ef36a-e289-11e6-94da-5f349f4def52.png)

**Comment by v-lego** [comment]
Зміни внесено

**Comment by MMarkiyan** [comment]
Виправлено
