### ISSUE TITLE
aukzionua: Ліквідатор має можливість завершити аукціон без завантаження скан-копії договору

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1104]
http://torgi.aukzion.com.ua/tender/protokol/

**Опис:** Ліквідатор має можливість завершити аукціон без завантаження скан-копії договору після успішного проходження аукціону та визначення переможця

**Передумова:**
- Увійти на майданчик під логіном checkdto@gmail.com
- Перейти до розділу "Мої ацкціони"
- Натиснути кнопку "Створити аукціон"
- Заповнити усі обов'язкові поля валідними даними
- Проскролити вниз сторінки та натиснути "Зберегти та перейти до публікації"
- Увійти на майданчик під логіном checkdto1@gmail.com
- Зробити ставку на раніше створений аукціон
- Увійти на майданчик під логіном checkdto2@gmail.com
- Зробити ставку на раніше створений аукціон
- Увійти на майданчик під логіном checkdto@gmail.com
- Дочекатись визначення переможця торгів

**Відтворення:**
1) У правому меню "Очікування пропозицій" натиснути кнопку "Таблиця кваліфікації"
2) Підтвердити переможця торгів (прикріплення протоколу торгів)
3) Підтвердити оплату переможцем (кнопка "визнати переможцем")
4) Заповнити дату та номер договору але не завантажувати скан-копії договора
5) Натиснути кнопку "Завершити"

**Очікуваний результат:** Завершення продажу не відбудеться, бо не завантажена скан-копія підписаного договору, про що з'являється відповідне повідомлення для користувача

**Фактичний результат:** Продаж успішно завершено без завантаження скан-копії договору
![default](https://cloud.githubusercontent.com/assets/13050207/22284767/5efc2c3e-e2f1-11e6-88c1-22e495120c7e.png)

**Comment by OSerhii** [comment]
Пофіксили, перевірте будь ласка)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
