### ISSUE TITLE
Centrex: UI проблеми при додаванні і відображенні контракта.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1105]
**Лінк:** http://eauction.centrex.com.ua

**Кроки:**
1. Увійти в ролі ліквідатора.
2. Провести аукціон і перейти до кваліфікації учасника.
3. Перейти до завантаження контракту.

**Фактично:** Кнопку "Додати документ" видно тільки частково.

![button](https://cloud.githubusercontent.com/assets/13050207/22285079/d5e813e8-e2f2-11e6-8e10-f34f1706c01b.png)
 
**Кроки:**
1. Увійти в ролі ліквідатора.
2. Провести аукціон та завантажити контракт.
3. Увійти в ролі учасника , перейти на сторінку аукціону та натиснути кнопку "Контракт"

**Фактично:** Учаснику відображаються два пустих поля , у ліквідатора під час заповнення контракту вони відсутні. 

![_](https://cloud.githubusercontent.com/assets/13050207/22285229/6bfa6804-e2f3-11e6-8875-d6efbd403cdb.png)

**Очікувано:** Учаснику повинні відображатись ті самі поля , як і ліквідатору.

![2](https://cloud.githubusercontent.com/assets/13050207/22285566/d80ac182-e2f4-11e6-8b57-0f4c269be439.png)

**Comment by SoftserveQC1** [comment]
Дефект відтворюється на aukzionua http://torgi.aukzion.com.ua

**Comment by SoftserveQC1** [comment]
Відтворюється на https://eauction.brizol.net

**Comment by OSerhii** [comment]
Виправили.
