### ISSUE TITLE
govfound: Невірні назви статусів аукціонів і валідацій у листах

### ISSUE THREAD

**Issue by georgedp** [openprocurement/frontend#1106]
Опис: Невірні назви статусів аукціонів і валідацій у листах

http://www.gov.auction
Відтворення:

- Створити лот
- Виставити на торги
- Задати питання
- Відменити торги
(один з кейсів)

**Очікуваний результат:**

- Статус cancelled - Торги відмінено
- Статус unsuccessful - Торги не відбулися
- Статус complete - Продаж завершений

**Фактичний результат:**

- Статус cancelled - Відмінена
- Статус unsuccessful - Торги відмінено
- Статус complete - Завершена

**Comment by OSerhii** [comment]
Вчора цей дефект був пофікшений на всіх проектах. Не підкажете як ви це відтворили сьогодні?

**Comment by OSerhii** [comment]
Прошу закрити дефект

**Comment by oleg4646** [comment]
надайте будь ласка скрiн листа

**Comment by OSerhii** [comment]
Виправлено

**Comment by georgedp** [comment]
Дефект виправленний
