### ISSUE TITLE
aukzionua: Реалізувати функціональність отримання покупцем посилання на модуль аукціону електронною поштою та у кабінеті Учасника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1108]
http://torgi.aukzion.com.ua/

**Опис:** Необхідно реалізувати функціональність отримання покупцем посилання на модуль аукціону електронною поштою та у кабінеті Учасника після завершення періоду прийому пропозицій.
На даному етапі посилання на модуль аукціону можна знайти лише у тілі створеного аукціону продажу.

**Очікуваний результат:** Після завершення періоду прийому пропозицій отримати посилання на модуль аукціону електронною поштою та у кабінеті Учасника.

**Comment by SoftserveQC1** [comment]
Також необхідно реалізувати для https://eauction.brizol.net

**Comment by SoftserveQC1** [comment]
також для Centrex http://eauction.centrex.com.ua

**Comment by OSerhii** [comment]
Пофіксили, для перевірки необхідно буде попередньо домовитися щоби ми дьорнули крон після того як стане доступним посилання на аукціон.
