### ISSUE TITLE
aukzionua: Реалізувати функціональність яка дозволяє покупцеві змінювати розмір ставки по аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1109]
http://torgi.aukzion.com.ua/

**Опис:** Необхідно  додати можливість покупцеві змінювати пропозицію до аукціону (не менше ніж початкова ціна продажу)
На даному етапі Учасник може лише відмінити пропозицію, а потім внести нову пропозицію з наступною валідацією ії адмінами, таким чином якщо Учасник вирішив змінити пропозицію перед завершенням періоду пропозицій його нова пропозиція може не встигнути валідуватися.

**Очікуваний результат:** Внести зміни можна лише до завершення кінцевого строку подання пропозицій, Учасник в особистому кабінеті отримує повідомлення про прийняття пропозиції Майданчиком та початку валідації Учасника та/або перевірку гарантійного внеску/банківської гарантії

**Comment by SoftserveQC1** [comment]
також актуально для Centrex http://eauction.centrex.com.ua

**Comment by SoftserveQC1** [comment]
Актуально для https://eauction.brizol.net

**Comment by OSerhii** [comment]
Виправлено.
