### ISSUE TITLE
"Помилка при експортуванні до ЦБД" при збереженні змін у контракті

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#111]
1. Зайти замовником у свій тендер, який має статус "Пропозиції розглянуто"
2. Натиснути кнопку "Контракт" у нижній частині вікна.
3. В полі "Опис" додати опис.
4. Натиснути кнопку "Додати документ" і добавити його.
5. Натиснути кнопку "Зберегти зміни"

![save_contract](https://cloud.githubusercontent.com/assets/11062040/6252134/c22a1650-b7a0-11e4-80d3-4c299c1ef62b.png)

**Comment by lerich** [comment]
не воспроизводиться

**Comment by lerich** [comment]
Закриваю
