### ISSUE TITLE
nkcentr: відсутнє повідомлення для Ліквідатора про валідацію 

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1113]
**Опис:** відсутні повідомлення для Ліквідатора про валідацію у вхідних повідомленнях майданчика та email

**Передумови:** Ліквідатор створив та опублікував аукціон в ЦБД

**Кроки:** (Виконуються учасником)
1. Виконати вхід, роль Ліквідатора
2. Опублікувати аукціон
3. Перевірити вхідні повідомлення на майданчику та email про публікацію аукціону в ЦБД

**Фактично:** відсутні повідомлення на майданчику та email про публікацію аукціону в ЦБД

**Очікувано:** після публікації аукціону в ЦБД надходять повідомлення на email та майданчик

**Comment by MMarkiyan** [comment]
Відтворюється на https://sale.nkc.biz.ua

**Comment by v-lego** [comment]
Встановленно надходження повідомлення при публікації

**Comment by SoftserveQC1** [comment]
Дефект виправлено v:nkcentr https://sale.nkc.biz.ua/test/
