### ISSUE TITLE
nkcentr: не коректне інформування про неуспішну валідацію

### ISSUE THREAD

**Issue by MMarkiyan** [openprocurement/frontend#1114]
**Опис:** під час публікації аукціону з не коректними даними відбувається інформування користувача 

**Передумови:** Зареєстрований та підтверджений користувач

Кроки: (Виконуються учасником)
1. Виконати вхід
2. Аукціони > Новий аукціон

**Фактично:** зявляється повідомлення англійською про неуспішну валідацію аукціону

**Очікувано:** під час не успішної валідації зявляється повідомлення з чітким змістом для кінцевого користувача щоб відкоригувати налаштування та завершити публікацію ЦБД.
При цьому кінцевий користувач може не володіти Англійськю мовою, тому повідомлення має відображатись мовою локалізації майданчика.

![2017-01-19_1313](https://cloud.githubusercontent.com/assets/20213167/22322947/fe1af1a4-e3a7-11e6-933f-90ab39a82bcc.png)

![2017-01-19_1313_001](https://cloud.githubusercontent.com/assets/20213167/22322945/fe0bef92-e3a7-11e6-8c46-0feaedb7e51c.png)

![2017-01-19_1306](https://cloud.githubusercontent.com/assets/20213167/22322946/fe1844d6-e3a7-11e6-9398-33898b6c7d07.png)

**Comment by v-lego** [comment]
Валідація полів виконується з застосуванням змісту українською мовою,
Повідомленя Англійською мовою надходять від ЦБД,
По мірі виявлення чіткого неприйняття ЦБД, такі повідомлення оформлюються українською мовою.

**Comment by v-lego** [comment]
Внесено зміни до повідомлення про період
![default](https://cloud.githubusercontent.com/assets/24773833/26091948/f2f5e66a-3a16-11e7-9513-f91df5481735.png)
стосовно інших повідомлень від ЦБД англійською мовою додали пропозицію
"(У випадку повторення, зверніться до майданчику)"

**Comment by SoftserveQC1** [comment]
Дефект виправлено
