### ISSUE TITLE
У статусах Тендера, де є розділ "Заявки" - файли не завантажуються

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#112]
У статусах Тендера: Пропозиції розглянуто, Очікування пропозицій (в учасника який подав пропозицію, у тендері), Кваліфікація переможця (в учасника), Відмінена закупівля (на деяких етапах), Завершена закупівля, у розділі "Заявки" (під зеленою лінією), файли не завантажуються у Firefox та InternetExplorer бравзерах. (В Chrome бравзері - файли завантажуються).
Це відтворюється і втестовому середовищі, і на продакшині.

![open_docs](https://cloud.githubusercontent.com/assets/11062040/6264442/b7d57dde-b82c-11e4-8e0c-ba511646bc0b.png)

**Comment by OksanaPakholok** [comment]
На даному етапі, уся вище подана інформація залишається актуальною, але зявляється повідомлення "Internal Server Error"

![server_error](https://cloud.githubusercontent.com/assets/11062040/6272262/1a066526-b86f-11e4-8fe9-cba643dd7361.png)

**Comment by lerich** [comment]
@OksanaPakholok  Будь-ласка, перевірте, чи актуальна проблема?

**Comment by OksanaPakholok** [comment]
Зараз файли не відкриваються тільки у Firefox та IE бравзерах

![ff_ie_greenline](https://cloud.githubusercontent.com/assets/11062040/6580975/9f98c5fc-c75c-11e4-8994-36f4c267c837.png)

@lerich
