### ISSUE TITLE
TBKMFB: Розмір мінімального кроку аукціону може бути меншим 5% від суми аукціону

### ISSUE THREAD

**Issue by alex85vol** [openprocurement/frontend#1121]
Адреса майданчика: https://ti.tbkmfb.com.ua/
Кроки відтворення:

1.Залогуватися на майданчику як ліквідатор
2.Перейти до створення аукціону
3.Внести розмір кроку аукціону меншим 5% від суми
4. Заповнити всі необхідні поля та зберегти.

Очікуваний результат:
Форма не збережена,  мінімальний крок має бути більшим 5% від суми аукціону https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit

Отриманий результат:
Форма збережена з мінімальним кроком аукціону меншим 5% від вартості аукціону

**Comment by w-be** [comment]
Додай будь-ласка посилання на вимоги.
