### ISSUE TITLE
Utsb: ліквідатор може створити аукціон у валюті відмінній від гривні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1126]
Utsb: ліквідатор може створити аукціон у валюті відмінній від гривні

Кроки відтворення:
1. Залогінитися на майданчику як ліквідатор
2. Перейти до створення аукціону
3. При створення аукціону вказати валюту не гривню
![image](https://cloud.githubusercontent.com/assets/13050207/22370858/55e06f78-e49c-11e6-94a6-bb0b1619e108.png)

Очікваний результат:
Аукціони можуть оголошуватися лише у гривні

Отриманий результат:
Ліквідатор може створити аукціон не тільки у гривні

**Comment by v-lego** [comment]
Можливість вибору валют прибрано
