### ISSUE TITLE
agrex: Невірний неймінг та валідація поля Розмір гарантійного внеску

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1129]
https://etp.agrex.gov.ua/test/

**Відтворення:**
1) Увійти на майданчик під логіном chekount@gmail.com
2) Перейти до розділу "Аукціони"
3) Натиснути кнопку "Створити аукціон"
4) Оглянути сторінку аукціону
5) Заповнити всі поля валідними даними (зокрема початкова ціна 100, розмір забезпечення 4)

**Очікуваний рузультат:** Присутнє поле "Розмір гарантійного внеску" з можливістю його установити у розмірі від 0 до розміру початкової вартості продажу

**Фактичний результат:** Присутній дропбокс "Вид забезпечення участі в аукціоні" та поле "Розмір забезпечення тендерної пропозиції" із валідацією від 5 до 100% від розміру початкової вартості продажу
![fild](https://cloud.githubusercontent.com/assets/13050207/22372607/52a5030a-e4a6-11e6-94d7-e7baf634655c.png)

**Comment by w-be** [comment]
Розмір гарантійного внеску може бути від 5% відсотків включно.

**Comment by AlexGr7** [comment]
![default](https://cloud.githubusercontent.com/assets/28492320/26404847/fb625dca-409b-11e7-8cd3-2893e1096e94.png)
змінено занесення розміру гарантійного внеску: прийнятні межі від 5% до 100%
