### ISSUE TITLE
Чи однакові версії тестового середовища і продакшину?

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#113]
Вчора на тестовому середовищі були помічені наступні речі:
1. Після створення тендера, і подачі пропозицій, після переходу тендера в статус "Період аукціону", час проведення аукціону було встановлено того ж дня, через 15 хв (Хоча насправді, час проведення аукціону - повинен бути встановлений на наступний день після 11 год)

![auction_time](https://cloud.githubusercontent.com/assets/11062040/6264748/525a88ac-b82f-11e4-98a5-c71f842d9399.png)
1. На майданчику тендер залишився в статусі "Очікування пропозицій" після часу прийому заявок

![waiting_proposal](https://cloud.githubusercontent.com/assets/11062040/6264806/e56308ea-b82f-11e4-8535-24d6104c2be5.png)

**Comment by S-Shevchenko** [comment]
@OksanaPakholok  Версии одинаковые,  только на тестовом окружении стоит быстрый режим -аукцион начинается через 15 мин (для ускоренного тестирования)

**Comment by OksanaPakholok** [comment]
Дякую

**Comment by lerich** [comment]
Закриваю.
