### ISSUE TITLE
Utsb: Після закінчення торгів учаник отримує повідомлення про те, що він став переможцем після підписання договору

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1130]
Utsb: Після закінчення торгів учаник отримує повідомлення про те, що він став переможцем після підписання договору

1. Провести торги з декількома учасниками (мінімум два)
2. Дочекатися їх завершення
3. Залогуватися на майданчику та в пошті учасником який зробив найвищу ставку
4. Очікувати повідомлення про перемогу

Отриманий результат:
Учасник з найвищою ставкою після закінчення аукціону не отримає повідомлення проперемогу

Очікуваний резльтат:
Після закінчення торгів учасник з найвищою ставкою отримує повідомлення проперемогу

**Comment by SoftserveQC1** [comment]
Дефект відтворюється на agrex https://etp.agrex.gov.ua/test/

**Comment by v-lego** [comment]
Внесено зміни
Повідомлення формується одразу при отриманні змін від ЦБД по записах кваліфікації

**Comment by SoftserveQC1** [comment]
**utsb: - пофіксано**

**Comment by SoftserveQC1** [comment]
agrex - не відтворюється
