### ISSUE TITLE
Utsb: Після закінчення торгів учаник з другою по величені ставки отримує повідомлення про те, що він зайняв друге місце лише після підписання договору

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1131]
Utsb: Після закінчення торгів учаник з другою по величені ставки отримує повідомлення про те, що він зайняв друге місце лише після підписання договору

1. Провести торги з декількома учасниками (мінімум два)
2. Дочекатися їх завершення
3. Залогуватися на майданчику та в пошті учасником який зробив другу ставку по величині
4. Очікувати повідомлення про зайняття другого місця

Отриманий результат:
Учасник з другою ставкою після закінчення аукціону не отримає повідомлення про зайняття другого місця

Очікуваний резльтат:
Після закінчення торгів учасник з другою по величені ставкою отримує повідомлення зайняття другої позиції

**Comment by w-be** [comment]
2 по величині ставка, ще не до кінця реалізована.

**Comment by v-lego** [comment]
Отримані повідомлення можна БУЛО переглянути на сторінці повідомлень кабінету та на пошті
