### ISSUE TITLE
Vidrodzhennia: Відсутній дропдаун з причинами скасування аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1134]
**Опис:** Корисувач не має змоги вибрати причину скасування аукціону з дропдауну. Дропдаун відсутній.

**Майданчик:** https://e.tbv.com.ua/

**Кроки:**
1. Залогінитись як Ліквідатор
2. Створити та опублікувати аукціон
3. Скасувати аукціон

**Фактично:** Відсутній дропдаун з причинами скасування аукціону
![image](https://cloud.githubusercontent.com/assets/13050207/22373687/9d6da234-e4ab-11e6-8130-0e89b1253ae9.png)

**Очікувано:** Можливі причини скасування аукціону задаються майданчиком (drop down):
   - Згідно рішення виконавчої дирекції Фонду гарантування вкладів фізичних осіб
   - Порушення порядку публікації оголошення

**Comment by v-lego** [comment]
Встановлено випадаючий список
![default](https://cloud.githubusercontent.com/assets/24773833/26444675/fe78242c-4145-11e7-99ea-79586ef3071e.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
