### ISSUE TITLE
Vidrodzhennia: Невірна назва кнопки “Скасування аукціону”

### ISSUE THREAD

**Issue by georgedp** [openprocurement/frontend#1137]
**Опис:** Невірна назва кнопки “Скасування аукціону”

**Майданчик:** https://e.tbv.com.ua/

**Фактично:** кнопка назівається "Відмінити"

**Очікувано:** кнопка називається “Скасування аукціону”
![2017-01-27_13-24-36](https://cloud.githubusercontent.com/assets/24564984/22374507/1bfeced6-e4af-11e6-9b42-6e5179c95d27.jpg)

**Comment by v-lego** [comment]
Кнопку переіменовано
![default](https://cloud.githubusercontent.com/assets/24773833/26437722/6e748316-4127-11e7-80f8-bd2c4475c37e.png)
Кнопка веде до окремої сторінки з можливістю завантаження документів та реєстрації причини
окремий список причин відмови не регламентований
![default](https://cloud.githubusercontent.com/assets/24773833/26437778/c90b2686-4127-11e7-957c-f417caefb61a.png)

**Comment by v-lego** [comment]
встановлено випадаючий список 
![default](https://cloud.githubusercontent.com/assets/24773833/26444719/2414410c-4146-11e7-9faa-ff265593fc75.png)

**Comment by SoftserveQC1** [comment]
Дефект випралено
