### ISSUE TITLE
Уточніть будь-ласка, на якому скріні оператор може відхиляти, приймати заявки на реєстрацію?

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#114]
![operator](https://cloud.githubusercontent.com/assets/11062040/6264999/c5c70cf0-b831-11e4-9236-78407ee9403a.png)

**Comment by S-Shevchenko** [comment]
@OksanaPakholok 
Очень просто, нужно зайти под оператором и прописать в адресной строке:
http://services.e-tender.biz:99/#/profiles
![image](https://cloud.githubusercontent.com/assets/10655287/6265191/091a1cde-b834-11e4-91df-173fb5205119.png)

**Comment by S-Shevchenko** [comment]
@OksanaPakholok 
![image](https://cloud.githubusercontent.com/assets/10655287/6265202/1fd985fe-b834-11e4-9672-31e36f92cc02.png)

**Comment by OksanaPakholok** [comment]
Дякую

**Comment by lerich** [comment]
закрываю
