### ISSUE TITLE
agrex: Ліквідатор має можливість завершити аукціон без завантаження скан-копії договору

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1141]
https://etp.agrex.gov.ua/test/

**Відтворення:**

1) Увійти на майданчик під логіном chekount@gmail.com (ліквідатор)
2) Перейти до розділу "Аукціони"
3) Натиснути кнопку "Створити аукціон"
4) Додати хочаб один актив та заповнити всі поля вілідними даними
5) Зберегти та опублікувати аукціон
6) Зробити ставки користувачами checkount@gmail.com та checkount1@gmail.com
7) Дочекатися закінчення аукціону
8) Зайти ліквідатором chekount@gmail.com до аукціону
9) Кваліфікувати переможця
10) Заповнити дату та номер договору але не завантажувати скан-копії договора
11) Завершити аукціон

**Очікуваний результат:** Завершення продажу не відбудеться, бо не завантажена скан-копія підписаного договору, про що з'являється відповідне повідомлення для користувача
**Фактичний результат:** Продаж успішно завершено без завантаження скан-копії договору

**Comment by AlexGr7** [comment]
Змінено перевірку на наявність файлів саме на типу contractSigned
