### ISSUE TITLE
agrex: Поля з адресою активу не відображаються при перегляді створеного аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1144]
https://etp.agrex.gov.ua/test/

**Відтворення:**

1) Увійти на майданчик під логіном chekount@gmail.com
2) Перейти до розділу "Аукціони"
3) Натиснути кнопку "Створити аукціон"
4) Додати хочаб один актив та заповнити всі поля валідними даними
5) Зберегти та опублікувати аукціон
6) Оглянути сторінку аукціону після публікації

**Очікуваний рузультат:** Усі заповнені раніше дані відображаються для користувача

**Фактичний результат:** Дані з адресою активу не відображаються
![default](https://cloud.githubusercontent.com/assets/13050207/22382988/9f89ce1a-e4d0-11e6-90ed-45a546ef22f5.png)

**Comment by v-lego** [comment]
Інформація deliveryAddress передається при публікації.
Але від ЦБД повертається повідомлення вже без такого блоку.
Можливо прибрати цей блок?

**Comment by v-lego** [comment]
Внесено зміни у збереження полів
![default](https://cloud.githubusercontent.com/assets/24773833/26455959/5f1440da-4174-11e7-91f2-69904811900e.png)
