### ISSUE TITLE
Polonex: Неоднакові формати дати для полів "Дата проведення аукціону" та "Дата рішення ФГВФО"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1148]
Передумови:
Організатор: логін: testadmin@test.t
адреси майданчиків: http://test.polonex.in.ua/,  http://test.etc-torgi.com, http://test.e-trading.kiev.ua

1.Залогуватися як Організатор
2. Створити Аукціон
Фактичний результат: неоднакові формати дати для полів: "Дата проведення аукціону" та "Дата рішення ФГВФОЄ" . Наприклад: 2017-02-08 та 2017-2-08
Див. скріншот
![data](https://cloud.githubusercontent.com/assets/13050207/22503424/5a9175f8-e87a-11e6-9aa6-5f14225ce098.png)

**Comment by greeschenko** [comment]
баг виправили, перевірте будьласка

**Comment by SoftserveQC1** [comment]
Перевірено на http://test.polonex.in.ua/, http://test.etc-torgi.com, http://test.e-trading.kiev.ua
