### ISSUE TITLE
При створенні тендера дублікація одиниць виміру при повторному виборі

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#115]
![doublication_measurements_unit](https://cloud.githubusercontent.com/assets/11062040/6267445/b3f5af3e-b84c-11e4-8ea3-80dc9636b305.png)

**Comment by OksanaPakholok** [comment]
Проблема глибше досліджена у https://github.com/openprocurement/frontend/issues/117

**Comment by S-Shevchenko** [comment]
Спасибо, знаем,  в работе.

**Comment by S-Shevchenko** [comment]
Закрываем. Основная задача :
https://github.com/openprocurement/frontend/issues/117

**Comment by lerich** [comment]
Закриваю.
