### ISSUE TITLE
birga-ukraine.com.ua: Покупці бачать не опубліковані Ліквідатором аукціони у загальному списку лотів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1152]
http://test.torgi.birga-ukraine.com.ua/category/?prozorro=1

**Опис:**  Покупці бачать не опубліковані Ліквідатором аукціони у загальному списку лотів, при спробі переглянути не опублікований лот Учасникові відображається помилка 403

**Кроки:**
1) Залогінитись як Ліквідатор
2) Створити заявку на проведення торгів.
Особистий кабінет > 2 >  Заявки на проведення торгів >  (якщо відкритих немає) Додати нову заявку >  Створити заявку
3) Створити лот.
Особстий кабінет >  Офіс замовника >  Заявки на проведення торгів >  Додати лот (натиснути “ + “ або дія “додати лот” ), але **НЕ Публікувати** лот
4) Залогінитись як Учасник
5) Перейти до списку аукціонів (головне меню "ProZorro.Продажі")

**Очікуваний результат:** Не опубліковані аукціони/лоти не відображаються для учасників

**Фактичний результат:** Учасник бачить лот створений Ліквідатором у статусі "Не опубліковано", при спробі його переглянути відображає помилку 403

![default](https://cloud.githubusercontent.com/assets/13050207/23452270/5f9de4ac-fe6c-11e6-9564-1cb2c3b52623.png)

**Comment by SergeAntonets** [comment]
Исправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
