### ISSUE TITLE
birga-ukraine.com.ua: Аукціон набуває статус "Пропозиції розглянуто" і не переходить у статус "Не відбувся" після 11 діб очікування договору

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1153]
http://test.torgi.birga-ukraine.com.ua/

**Опис:** Після підтвердження оплати Ліквідатором аукціон переходить у статус "Пропозиції розглянуто" і залишається у цьому статусі навіть після закінчення періоду Підписання/активація контракту (11 діб з моменту переходу учасника в етап Awarding). 
Хоча у [ТЗ](https://docs.google.com/document/d/1_aqt5Wl4X7x87VpuWpbRBmqOihYjYJzVH8huuxsnH4w/edit#) Awarding 2.1 стр3 п7 сказано "У випадку відсутності договору від Ліквідатора в системі після 11-го дня, ЕТС автоматично дискваліфікує Кандидата", а цього не відбувається

**Передумова:**
- Залогінитись як Ліквідатор chekount@gmail.com
- Створити заявку на проведення торгів (таймінг 144).
Особистий кабінет > 2 > Заявки на проведення торгів > (якщо відкритих немає) Додати нову заявку > Створити заявку
- Створити лот.
Особстий кабінет > Офіс замовника > Заявки на проведення торгів > Додати лот (натиснути “ + “ або дія “додати лот” ) та опублікувати його
- Залогінитись Учасником1 checkount@gmail.com та зробити ставку по створеному раніше лоту(стартова ціна + мін крок)
-  Залогінитись Учасником2 checkount1@gmail.com та зробити ставку по створеному раніше лоту(стартова ціна + мін крок)
- Дочекатися переходу аукціону у стадію кваліфікації переможця

**Кроки:**
1) Ліквідатор завантажує протокол для Учасника1 протягом 1-3 доби Awarding Учасника1 (Особистий кабінет->Офіс замовника->Кваліфікація)
2) Ліквідатор підтверджує оплату Учасником1 протягом 1-11 доби Awarding Учасника1 (Особистий кабінет->Офіс замовника->Кваліфікація)
3) Учасник2 відмовляється від участі, забирає свій внесок (Особистий кабінет->Купую->Кнопка "Забрати внесок")
4) Ліквідатор не завантажує договір з Учасником1 протягом 1-11 доби Awarding Учасника1

**Очікуваний результат:** Торги переходять у статус "Не відбулися", Учасник1 отримує листа про дискваліфікацію на пошту та/чи у Особистому кабінеті

**Фактичний результат:** Аукціон переходить у статус "Пропозиції розглянуто" і залишається у ньому навіть після закінчення строку Awarding Учасника1 (після 11ої доби)
Приклад: http://test.torgi.birga-ukraine.com.ua/lot/30288-keys-7/
http://test.torgi.birga-ukraine.com.ua/lot/30503-keys-8-popytka-2/
![7-8](https://cloud.githubusercontent.com/assets/13050207/23453678/f62c2280-fe71-11e6-8386-93d5646c18e2.png)

**Comment by SoftserveQC1** [comment]
Результат отриманий від ЦБД
https://lb.api-sandbox.ea.openprocurement.org/api/2.4/auctions/ca946a08d25140a49585a612270f690a
скрин1
![pasted image at 2017_03_01 10_27 am](https://cloud.githubusercontent.com/assets/13050207/23453741/2a7d016c-fe72-11e6-933a-3046793adc4e.png)
скрин2
![pasted image at 2017_03_01 10_28 am](https://cloud.githubusercontent.com/assets/13050207/23453748/2f6bb394-fe72-11e6-83ae-83091a06dd2f.png)

**Comment by SoftserveQC1** [comment]
Відповідь від ЦБД
https://lb.api-sandbox.ea.openprocurement.org/api/2.4/auctions/d0ce38f937f8414187281c9a419fb3da
скрин1
![pasted image at 2017_03_01 11_40 am](https://cloud.githubusercontent.com/assets/13050207/23454124/e7aa129c-fe73-11e6-88b5-86bc0017fba7.png)
скрин2
![pasted image at 2017_03_01 11_40 am 1](https://cloud.githubusercontent.com/assets/13050207/23454172/204a5f6c-fe74-11e6-9f0f-9f56823c87df.png)

**Comment by w-be** [comment]
Те саме на tbelectrotorg.

**Comment by SergAntonec** [comment]
Accelerator:144

**Comment by SergeAntonets** [comment]
Сменил акселератор на 360 и провел торги по вышеуказанному сценарию. Все отработало
 http://test.torgi.birga-ukraine.com.ua/lot/30854-accelerator-360/

**Comment by SoftserveQC1** [comment]
Провів аукціони за сценаріями кейсу 35 детального звіту (акселератор 360), дефект відтворився
http://test.torgi.birga-ukraine.com.ua/lot/31268-360-8/
http://test.torgi.birga-ukraine.com.ua/lot/31267-360-7/

**Comment by SoftserveQC1** [comment]
Дефект виправлено
http://test.torgi.birga-ukraine.com.ua/lot/33106-keys-7-aftefiks-1/
http://test.torgi.birga-ukraine.com.ua/lot/33107-keys-7-aftefiks-2/
http://test.torgi.birga-ukraine.com.ua/lot/33549-protokol-dogovor/
