### ISSUE TITLE
Невірний статус торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1154]
майданчик: http://test.etc-torgi.com/
користувач: testadmin@test.t
передумова: аукціон, що очікує підписання договору
посилання на аукціон: http://test.etc-torgi.com/prozorrosale/auctions/901

Сценарій:
1. Очікувати 11 днів
2. Авторизуватись на майданчику
3. Відкрити аукціон з передумови

Фактично: статус аукціону - Пропозиції розглянуто
![image](https://cloud.githubusercontent.com/assets/13050207/23469802/5b6e80e4-fead-11e6-9576-68bc82bc3c6c.png)

Очікувано: статус аукціону - Торги відмінено

**Comment by greeschenko** [comment]
вітаю вкажіть будьласка номер лоту

**Comment by greeschenko** [comment]
1. ми декілька разів змінювали значення параметру прискорення тому невідомо скільки необхідно чекати до того як система нарахує 11днів
2. аукціон синхронізовано з цбд https://lb.api-sandbox.ea.openprocurement.org/api/2.4/auctions/61253ceb7ade4d53861bcc2632e58ae6?opt_pretty=1
і має такий самий стутус в цбд тому нам не зрозуміло в чому саме помилка нашої системи

**Comment by SoftserveQC1** [comment]
дефект перевірено та зачинено
