### ISSUE TITLE
test.torgi.vidol.com.ua: Покупці бачать не опубліковані Ліквідатором аукціони у загальному списку лотів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1155]
http://test.torgi.vidol.com.ua/category/?prozorro=1

**Опис:** Покупці бачать не опубліковані Ліквідатором аукціони у загальному списку лотів, при спробі переглянути не опублікований лот Учасникові відображається помилка 403

**Кроки:**

1. Залогінитись як Ліквідатор
2. Створити заявку на проведення торгів.
Особистий кабінет > 2 > Заявки на проведення торгів > (якщо відкритих немає) Додати нову заявку > Створити заявку
3. Створити лот.
Особстий кабінет > Офіс замовника > Заявки на проведення торгів > Додати лот (натиснути “ + “ або дія “додати лот” ), але НЕ Публікувати лот
4. Залогінитись як Учасник
5. Перейти до списку аукціонів (головне меню "ProZorro.Продажі")

**Очікуваний результат:** Не опубліковані аукціони/лоти не відображаються для учасників

**Фактичний результат:** Учасник бачить лот створений Ліквідатором у статусі "Не опубліковано", при спробі його переглянути відображає помилку 403

![fb67f56be7](https://cloud.githubusercontent.com/assets/13050207/23471739/02c9b142-feb3-11e6-88b8-195845ce3b4b.jpg)

**Comment by SergeAntonets** [comment]
Исправлено
