### ISSUE TITLE
KIF: Аукціон набуває статус "Оплачено, очікується підписання договору" і не переходить у статус "Не відбувся" після 11 діб очікування договору

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1157]
https://sale.kif.in.ua/test/

**Опис:** Після підтвердження оплати Ліквідатором аукціон переходить у статус "Оплачено, очікується підписання договору" і залишається у цьому статусі навіть після закінчення періоду Підписання/активація контракту (11 діб з моменту переходу учасника в етап Awarding).
Хоча у [ТЗ](https://docs.google.com/document/d/1_aqt5Wl4X7x87VpuWpbRBmqOihYjYJzVH8huuxsnH4w/edit#) Awarding 2.1 стр3 п7 сказано "У випадку відсутності договору від Ліквідатора в системі після 11-го дня, ЕТС автоматично дискваліфікує Кандидата", а цього не відбувається

**Передумова:**

- Залогінитись як Ліквідатор owner1uub@gmail.com
- Створити аукціон ("Виконання з прискоренням" - 144).
Головна сторінка -> Створити аукціон (або Особистий кабінет->Аукціони->Новий аукціон) та опублікувати його
- Залогінитись Учасником1 customer1uub@gmail.com та зробити ставку по створеному раніше лоту(стартова ціна + мін крок)
- Залогінитись Учасником2 customer2uub@gmail.com та зробити ставку по створеному раніше лоту(стартова ціна + мін крок)
- Дочекатися переходу аукціону у стадію кваліфікації переможця

**Кроки:**

1) Ліквідатор завантажує протокол для Учасника1 протягом 1-3 доби Awarding Учасника1 (Аукціон->Додати документ (протокол торгів)->Підтвердити протокол)
2) Ліквідатор підтверджує оплату Учасником1 протягом 1-11 доби Awarding Учасника1 (Аукціон->Підтвердити оплату учасником)
3) Учасник2 відмовляється від участі, забирає свій внесок (Аукціон->"Відмінити")
4) Ліквідатор не завантажує договір з Учасником1 протягом 1-11 доби Awarding Учасника1

**Очікуваний результат:** Торги переходять у статус "Не відбулися", Учасник1 отримує листа про дискваліфікацію на пошту та/чи у Особистому кабінеті

**Фактичний результат:** Аукціон переходить у статус "Оплачено, очікується підписання договору" і залишається у ньому навіть після закінчення строку Awarding Учасника1 (після 11ої доби)
Приклади: https://sale.kif.in.ua/test/auction/UA-EA-2017-03-01-030303-3/
https://sale.kif.in.ua/test/auction/UA-EA-2017-03-01-030346-3/

![8](https://cloud.githubusercontent.com/assets/13050207/23517859/49fb2c22-ff7a-11e6-8a59-c2db95591a6d.png)

![8-2](https://cloud.githubusercontent.com/assets/13050207/23517875/5161d312-ff7a-11e6-950e-5f02980e9cbc.png)

**Comment by v-lego** [comment]
все таки вопрос
это должна делать площадка или ЦБД?
мы не против этой реализации на площадке, только получится это единственная временная метка, которая отслеживается площадкой

**Comment by SoftserveQC1** [comment]
Було проведено тесты з прискоренням 360:
Case №1 (Уч1-Д, Уч2-Ч)
Л. завантажує протокол для Уч1 протягом до 3 діб ->
Л. підтвержує для Уч1. оплату протягом 11 діб ->
Л. дискваліфікує Уч1. без завантаження договору ->
Л. завантажує протокол для Уч2 протягом до 3 діб ->
Л. підтвержує для Уч2. оплату протягом 11 діб ->
Л. не завантажує договір з Уч2. протягом 11 діб

https://sale.kif.in.ua/test/auction/UA-EA-2017-03-02-004258-2/ - статус "Оплачено, очікується підписання договору"
https://sale.kif.in.ua/test/auction/UA-EA-2017-03-02-000076-1/ - статус "Не відбувся"

Case №2 (Уч1-Ч, Уч2-В)
Л. завантажує протокол для Уч1 протягом до 3 діб ->
Л. підтвержує для Уч1. оплату протягом 11 діб ->
Уч2. відмовляється, заберає свій внесок ->
Л. не завантажує договір з Уч1. протягом 11 діб

https://sale.kif.in.ua/test/auction/UA-EA-2017-03-02-001285-2/ - статус "Оплачено, очікується підписання договору"

**Comment by SoftserveQC1** [comment]
Дефект виправлено
https://sale.kif.in.ua/test/auction/UA-EA-2017-03-09-000084-1/
https://sale.kif.in.ua/test/auction/UA-EA-2017-03-09-000080-1/
https://sale.kif.in.ua/test/auction/UA-EA-2017-03-09-000081-1/
