### ISSUE TITLE
Public-bid: Відсутня кнопка "Кандидат кваліфікований"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1158]
Відтворення:
1. Залогуватися ліквідатором
2. Провести торги до стадії кваліфікації переможця
3. На сторінці, де завантажуєм договір звернути увагу на відсутнь кнопки "Кандидат кваліфікований"

Фактично: кнопка "Кандидат кваліфікований" відсутня

Очікувано: кнопка "Кандидат кваліфікований" присутня зверху

**Comment by w-be** [comment]
Потрібно додати знімок екрану, адресу веб сторінки та логін користувача (без пароля).

**Comment by alexmirn** [comment]
fixed

**Comment by Valdisk92** [comment]
Більше такої кнопки не має, з'явився статус "Очікується оплата", так само називається кнопка, яка переводить авард в цей статус. А коли авард в цьому статусі, буде кнопка "Визнати переможцем", яка переводить авард в статус active.
Чи потрібно кнопку, яка переводить авард в статус active назвати "Кандидат кваліфікований"?
