### ISSUE TITLE
Public-bid: Відсутня можливість забрати гарантій внесок для участника торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1159]
Відтворення: 
1. Залогуватись як участник
2. Взяти участь у торгах і зайняти там друге місце
3. Під час кваліфікації переможця забрати свій гарантій внесок, недочекавшись остаточного визначення переможця

Фактично: відсутня опція "забрати гарантійний внесок"

Очікувано: Наявність опції "забрати гарантіний внесок"

**Comment by SoftserveQC1** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/13050207/23606639/4bc9c994-026a-11e7-80b4-407cc135c8fc.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/13050207/23606638/4bc8ed30-026a-11e7-8219-ae6425bded5c.png)

**Comment by Valdisk92** [comment]
Fixed

**Comment by KaterynaMatvieieva** [comment]
Опція "Забрати гарантійний внесок" реалізована кнопкою "Відмінити участь
![mozilla firefox 2017-03-10 10 17 49](https://cloud.githubusercontent.com/assets/24721040/23789581/1dfed0fa-0584-11e7-9717-8c5a25b8a0f3.png)
"
