### ISSUE TITLE
"Internal Server Error" на валідацію полів "Повний доступний бюджет закупівлі" та "Мінімальний крок аукціону"

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#116]
1. При створенні тендера в поля "Повний доступний бюджет закупівлі" та "Мінімальний крок аукціону" ввести значення для прикладу 05
2. Заповнити решту полів валідними даними.
3. Натиснути кнопку "Створити тендер"

![bad_validation](https://cloud.githubusercontent.com/assets/11062040/6267771/ade7780e-b84f-11e4-9c17-dd5372152058.png)

**Comment by S-Shevchenko** [comment]
Спасибо, взяли в работу

**Comment by S-Shevchenko** [comment]
Не воспроизводиться
