### ISSUE TITLE
test.torgi.vidol.com.ua: Відсутність ідентифікатора лоту в темі повідомлення що надходить в особистий кабінет та до електронної поштової скриньки 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1160]
http://test.torgi.vidol.com.ua/message/default/list/?token=cc1481821c5e40b9795d72cf1e798716&time=1488562149

**Опис:** Повідомлення, що учасники отримують в особистий кабінет та на пошту не мають ідентифікатора лоту, що унеможливлює пошук повідомлень без перегляду тіла повідомлення, тобто повідомлення які стосуються різних лотів можуть мати однакову тему. 

![ea9d4932fb](https://cloud.githubusercontent.com/assets/13050207/23579258/3de90e94-00f2-11e7-9d5b-e834c27fea36.jpg)

Користувач також бачить у повідомленні незрозуміле унікальне ID:

![73a40e291a](https://cloud.githubusercontent.com/assets/13050207/23579308/3a70ecf4-00f3-11e7-8c28-d6de7e7585de.jpg)

Також при отримання відповідних листів на електронну пошту, вони сортуються по темі і таким чином утворюють нелогічні блоки повідомлень що мають однакову тему але відносяться до різних лотів (стандартні налаштування поштової скриньки gmail). 

![4030e3b9c1](https://cloud.githubusercontent.com/assets/13050207/23579272/9fa415a2-00f2-11e7-82fa-12951af0f4d7.jpg)

![6c477d46fb](https://cloud.githubusercontent.com/assets/13050207/23579296/ff362cd0-00f2-11e7-878e-8df590d09ae0.jpg)

**Кроки:**

1. Залогінитись як Учасник 
2. Подати заявки на участь в декількох акціонах
3. Прийняти участь в аукціонах 
4. Перейти в Особистий кабінет 
5. Переглянути повідомлення в Особистому кабінеті 
6. Залогінитись до відповідної поштової скриньки
7. Переглянути повідомлення в ел. поштовій скринці 

**Очікуваний результат:** 
1. В темі повідомдень присутній UA-ID що дозволяє користувачеві бачити до якого саме лоту відноситься конкретне повідомлення та шукати інформацію
Наприклад:
[UA-EA-2017-03-03-004245-1] Дискваліфікація в електронних торгах
[UA-EA-2017-03-03-001091-1] Допуск до участі в аукціоні
...
2. В темі повідомдень відсутній внутрішній ID ([58b99c7353120], [58b9892c41441] і т.п.)
3. Повідомлення не утворюють блоки за темою у поштовій скринці

**Фактичний результат:**
1. Відсутній ідентифікатор лоту в темі повідомлення що надходить в особистий кабінет та до електронної поштової скриньки 
2. Наявність у темі повідомлення незрозумілого унікального ID
3. Групування листів за однаковими темами у поштовій скринці

**Comment by SergeAntonets** [comment]
![image](https://cloud.githubusercontent.com/assets/7313452/23607681/898f57ea-026e-11e7-9994-ffea6a3f5e4e.png)
слева ид лота  в нашей с-ме, справа название лота

**Comment by SoftserveQC1** [comment]
Да, там есть название лота, но оно в теле сообщения а не в его теме. Таким образом стандартный почтовик (в данном случае использовалась почта gmail) группирует сообщения согласно теме. И если тема одинаковая вместе группируются сообщения которые касаются разных лотов, а значит вместе сгруппированы быть не должны. 
![4030e3b9c1](https://cloud.githubusercontent.com/assets/13050207/23615738/170555ae-0290-11e7-9b31-27b9b1f1b6f1.jpg)
Как видите несколько сообщений с одинаковой темой но по разным лотам оказываются в одной группе и отслеживать их неудобно

**Comment by SergeAntonets** [comment]
Правки внесены

**Comment by SoftserveQC1** [comment]
Сообщения маркируются UA-ID:

![2031ec44d2](https://cloud.githubusercontent.com/assets/13050207/23660403/fe897632-0351-11e7-9a39-11c9a95cd451.jpg)
