### ISSUE TITLE
test.torgi.vidol.com.ua: Неповна локалізація майданчика

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1161]
http://test.torgi.vidol.com.ua

**Опис:** Неповна локалізція майданчика
При оформленні заявки на участь в аукціоні користувач бачить нелокалізовані поля:
![1c3c3113cf](https://cloud.githubusercontent.com/assets/13050207/23579500/678aabe0-00f7-11e7-8cea-0eb510d64279.jpg)

**Кроки:**

1. Залогінитись як Учасник 
2. Обрати лот
3. Подати заявки на участь в аукціоні (кнопка "Стати учасником")
4. Перейти на вкладинку Додатки

**Очікуваний результат:** 
1. Усі лейбли та кнопки українською (або відповідно до обраної мови, якщо присутня дана можливість) 

**Фактичний результат:**
1. Частина написів англійською

**Comment by SergeAntonets** [comment]
У вас английский установлен в языковых настройках браузера.

**Comment by SoftserveQC1** [comment]
Перевірено при відповідних налаштуваннях браузера.
