### ISSUE TITLE
test.torgi.vidol.com.ua: Користувачі не отримують повідомлення з кінцевими результатами аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1162]
майданчик: http://test.torgi.vidol.com.ua/
користувач: ayefym@softserveinc.com
посилання на аукціон: http://test.torgi.vidol.com.ua/lot/32147-test-kredit-na-um1/

**Опис:**  Користувачі не отримують жодного повідомлення по досягненню аукціоном завершального статусу (Не відбувся, Неуспішний, Переможець)

**Кроки:**
1. Залогінитись як Ліквідатор
2. Створити заявку на проведення торгів.
3. Створити лот.
4. Опубліковати лот
5. Залогінитись як Учасник 1
6. Перейти до списку аукціонів 
7. Знайти відповідний лот (опублікований у п.4)
8. Подати заявку на участь в акціоні
9. Залогінитись як Учасник 2
10. Перейти до списку аукціонів 
11. Знайти відповідний лот (опублікований у п.4)
12. Подати заявку на участь в акціоні
13. Дочекатися проведення аукціону та переходу на єтип кваліфкації
14. Залогінитись як Ліквідатор
15. Провести Кваліфікацію переможця
16. Підписати та опублікувати договір з переможцем
17. Залогінитись як Учасник 1(Переможець, 1-ше місце в аукціоні)
18. Перевірити повідомлення стосовно даного лоту в Особисному кабінеті
19. Залогінитись як Учасник 2(2-ге місце в аукціоні)
20. Перевірити повідомлення стосовно даного лоту в Особисному кабінеті

**Очікуваний результат:** 
1. Учасники отримали повідомлення що аукціон завершено та він набув відповідного статтусу

**Фактичний результат:**
1. Учасники не отримали повідомлення що аукціон завершено та він набув відповідного статтусу

Приклад останього повідомлення, що отримав Переможець:
![29409c9bfc](https://cloud.githubusercontent.com/assets/13050207/23579657/217f0b70-00fa-11e7-8c2a-8ee8a48fe9d2.jpg)

Приклад останього повідомлення, що отримав Учасник що посів друге місце:
![db94af6a2d](https://cloud.githubusercontent.com/assets/13050207/23579676/a7a86890-00fa-11e7-8a1f-2847fb6577d7.jpg)

**Comment by SergeAntonets** [comment]
Добавлено

**Comment by SoftserveQC1** [comment]
Якщо аукціон успішний та статус лоту перейшов у "Завершений" учасники отримують наступне повідомлення: 
![01d2886795](https://cloud.githubusercontent.com/assets/13050207/23664488/674e7b98-035e-11e7-9670-d905b4fb1131.jpg)

Якщо аукціон набуває статусу "Не відбувся" через дискваліфікацію Учасника чи вичерпаний термін подання/підтвердження відповідних документів Учасник що був дискваліфікований бачить наступне повідомлення останнім по цьому лоту:
![e7fc4e4315](https://cloud.githubusercontent.com/assets/13050207/23665097/2ef2ba8c-0360-11e7-96e3-99101d11c91f.jpg)
