### ISSUE TITLE
PROM: При спробі дискваліфікувати Учасника на етапі active аукціон "зависає" у статусі "Підписання договору"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1164]
https://my.zakupki.dz-test.net/cabinet/purchases/state_auction/list?mode=created_by_my_merchant

**Опис:** При спробі дискваліфікувати Учасника на етапі active аукціон "зависає" у статусі "Підписання договору" хоча Учаснику приходить на пошту повідомлення про дискваліфікацію, а Ліквідатору приходить на пошту лист "Ошибка отправки данных на ЦБД"

**Передумова:**

- Залогінитись як Ліквідатор chekount@gmail.com
- Створити заявку на проведення торгів (таймінг майданчика 192 (1 день=7,5 хвилин))(Аукціони -> кнопка "Новий аукціон")
- Заповнити поля аукціону валідним даними та опублікувати його
- Залогінитись Учасником1 checkount@gmail.com та зробити ставку по створеному раніше лоту(стартова ціна + мін крок)
- Залогінитись Учасником2 checkount1@gmail.com та зробити ставку по створеному раніше лоту(стартова ціна + мін крок)
- Дочекатися переходу аукціону у стадію кваліфікації переможця

**Кроки:**

1) Ліквідатор завантажує протокол для Учасника1 протягом 1-3 доби Awarding Учасника1 (Аукціон->кнопка "Загрузить протокол")
2) Ліквідатор підтверджує оплату Учасником1 протягом 1-11 доби Awarding Учасника1 (Аукціон->кнопка "Підтвердити оплату")
3) Ліквідатор дискваліфікує Учасника1
(Аукціон->кнопка "Відхилити"->прикріпляє документ дискваліфікації і підтверджує)

**Очікуваний результат:** 
- Учасника1 дискваліфіковано
- Учасник1 отримує листа про дискваліфікацію на пошту та/чи у Особистому кабінеті
- Кваліфікація переходить до Учасника2 (pending.verification Учасника2)

**Фактичний результат:** 
- Аукціон "зависає" у статусі "Підписання договору", кваліфікація Учасника2 не розпочинається
![5 1-2](https://cloud.githubusercontent.com/assets/13050207/23610954/8138464c-027d-11e7-95a3-ac77b9285960.png)
![5 1-2-2](https://cloud.githubusercontent.com/assets/13050207/23610958/88c2a1aa-027d-11e7-8e7c-ecd40b91459f.png)

- Учасник1 отримує листа про дискваліфікацію
![5 1-3](https://cloud.githubusercontent.com/assets/13050207/23610977/9d300b3c-027d-11e7-8f0b-1f26a7ac8765.png)

-  Ліквідатору приходить на пошту лист "Ошибка отправки данных на ЦБД"
![5](https://cloud.githubusercontent.com/assets/13050207/23611020/d1b1c166-027d-11e7-8327-fff312c19a30.png)

**Comment by SoftserveQC1** [comment]
Аналогічний кейс із дискваліфікацією Учасника1 був успішно пройдений на наступних аукціонах інших майданчиків (у випадках 1-3 "зависання" відбулося вже після закінчення строку Awarding Учасника2 про що були заведені відповідні дефекти #1153 #1157):
1) http://test.torgi.birga-ukraine.com.ua/lot/31267-360-7/
2) http://test.torgi.birga-ukraine.com.ua/lot/30288-keys-7/
3) https://sale.kif.in.ua/test/auction/UA-EA-2017-03-02-004258-2/
4) https://sale.kif.in.ua/test/auction/UA-EA-2017-03-02-000076-1/

**Comment by znakharenko** [comment]
`Name: data. 0: Can't add document in current (active.awarded) auction status`
Известная проблема на стороне ЦБД, мы уберём возможность грузить файл в данном статусе, хотя это конечно очень странное решение 👎

**Comment by znakharenko** [comment]
Можете проверять

**Comment by SoftserveQC1** [comment]
Дефект виправлено
Файл мождиво завантажити лише до active.awarded(загрузка протокола), після цього можливість завантажити файл при дискваліфікації Учасника відсутня, але з'являється повідомлення, що Учасника буде дискваліфіковано та відмінити дію у подальшому неможливо
https://my.zakupki.dz-test.net/cabinet/purchases/state_auction/view/500280
https://my.zakupki.dz-test.net/cabinet/purchases/state_auction/view/500215
