### ISSUE TITLE
Public-Bid: Після натискання кнопки "Зберегти оцінку" появляється повідомлення про помилку запису до ЦБД

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1165]
Відтворення:
1. Залогуватись як ліквідатор
2. провести торги до стадії кваліфікації з 2 участниками
3. Після дискваліфікації участника та/або кваліфікації переможця нажати кнопку "Зберегти оцінку"

Фактично: повідомлення про помилку "Помилка запису до ЦБД"

Очікувано: оцінка збереглась згідно дискваліфікації участника та/або кваліфікації переможця
![case 33](https://cloud.githubusercontent.com/assets/13050207/23650851/3babc112-032c-11e7-9134-546a483c0eaf.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/13050207/23650857/3f2ff7c2-032c-11e7-9a42-1c80f6e0ad23.png)

**Comment by KaterynaMatvieieva** [comment]
Зазначена помилка з'являється при повторному проведенні кваліфікації/дискваліфікації (натисненні відповідних кнопок) без наявності відповіді від ЦБД. Після натискання кнопки "Зберегти оцінку" необхідно дочекатись відповіді від ЦБД (декілька хвилин) і оновити сторінку, після чого з'явиться кнопка "Визначити переможцем" або кандидата буде дискваліфіковано.
