### ISSUE TITLE
Public-Bid: Після дискваліфікації першого участника і завантаження протоколу другим участником кнопка "оцінити" не завжди появляється для другого участника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1167]
Відтворення:
1. Залогінитись як ліквідатор 
2. Провести торги з двома участинками
3. Дискваліфікувати першого участника
4. Завантажити протокол в якості другого участника
5. Як ліквідатор перейти на сторінку 'результати аукціону' -> 'участники аукціону'

Фактично: відсутня кнопка "оцінити" для другого участника після завантеження ним протоколу

Очікувано: наявність кнопки
![screenshot_2](https://cloud.githubusercontent.com/assets/13050207/23652465/bc092034-0331-11e7-9ed5-57202e4a0623.png)
 "оцінити" для другого участника після завантеження ним протоколу

**Comment by Valdisk92** [comment]
Зробили близько 5 аукціонів і в жодному разі баг не був виявлений. Кнопка оцінити завжди з'являлась. Можливо потрібно зачекати на синхронізацію з ЦБД, до 5 хвилин.

**Comment by KaterynaMatvieieva** [comment]
![google chrome 2017-03-10 08 56 43](https://cloud.githubusercontent.com/assets/24721040/23789800/0c23535a-0585-11e7-9c68-58222c1d32a4.png)
