### ISSUE TITLE
Public-Bid: Під час аукціону після закінчення етапу ставок залогінених користувачів (ліквідатор та два участниками) вилогінює з порталу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1168]
Відтворення
1. Залогінитись як ліквідатор в одному браузері(наприклад chrome), паралельно залогінитись як 2 участника в двох інших браузерах(firefox- участник №1, IE - участник №2)
2. Провести торги з 2 участниками до закінчення ставок
3. Коли закінчились торги повернутись на портал, і спробувати зайти в особистий кабінет
4. Звернути увагу що система вилогінює користувача

Фактично: користувач (участник чи/і ліквідатор) вилогований із системи, перебуває на порталі як анонімус

Очікувано: користувач далі залогінений і перебуває на порталі НЕ як анонімус

**Comment by PetrovAndrii** [comment]
Можете, буль ласка, описати більш детально цей момент, а то не зовсім зрозуміло.
При можливості додайте скріншот.

**Comment by KaterynaMatvieieva** [comment]
Збільшено тривалість сесії залогіненого користувача
