### ISSUE TITLE
Vidol: Доцільність використання "Вітаємо" на початку повідомлення

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1169]
майданчик: http://test.torgi.vidol.com.ua/
користувач: a.kim80008@gmail.com
посилання на аукціон: http://test.torgi.vidol.com.ua/lot/33735-test-knizhkova-shafa-kam-yan/
передумова: провести аукціон та буди дискваліфікованим

**Опис:**
Учасник бачить привітання "Вітаємо" на початку кожного повідомлення, навіть якщо воно стосується дискваліфікації чи публікації договору з іншим учасником. 
Приклад повідомлення:

![7b8d7c8e2a](https://cloud.githubusercontent.com/assets/13050207/23665626/ac9b593e-0361-11e7-84a6-1aa8f92b53a6.jpg)

**Comment by SergeAntonets** [comment]
окей, почистим

**Comment by SoftserveQC1** [comment]
Перевірено на http://test.torgi.vidol.com.ua
