### ISSUE TITLE
Public-Bid: Під час завантаження протоколу участником вибиває помилку 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1170]
Відтворення:
1. Провести торги з двома участниками
2. Після етапу торгів, завантажити протокол як участник той що виграв

Очікувано: протокол завантажився і нотифікація про успішне збереження

Фактично: помилка "Не вдалося зареєструвати пропозицію у ЦБД, спробуйте будь ласка пізніше"

![default](https://cloud.githubusercontent.com/assets/13050207/23750352/283105ca-04d5-11e7-9d9f-30ac3ab71e13.png)

**Comment by KaterynaMatvieieva** [comment]
Відповідь аналогічна на помилку #1165, намагалися повторити дію без наявності відповіді від ЦБД.
