### ISSUE TITLE
Public-Bid: Помилка запису до ЦБД після завантаження протоколу нажавши кнопку "зберегти"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1171]
Відтворення:
1. Провести торги з двома участниками
2. Як ліквідатор завантажити протокол для участника який переміг 
3. Нажати кнопку "зберегти"

Очікувано: нотифікація про збереженя після натискання кнопки "зберегти"

Фактично: помилка запису до ЦБД, після натискання кнопки "зберегти"

![default](https://cloud.githubusercontent.com/assets/13050207/23750614/754a6918-04d6-11e7-8905-6adef87b8165.png)

**Comment by KaterynaMatvieieva** [comment]
Відповідь аналогічна на помилку #1165, намагалися повторити дію без наявності відповіді від ЦБД.
