### ISSUE TITLE
Public-Bid: Поява неактуальних полів для заповнення під час завантаження договору, після дискваліфікації участника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1172]
Відтворення:
1. Провести торги з двома участниками
2. Як ліквідатор спробувати дискваліфікувати участника (1 і 2)
3. Перезавантажити сторінку, звернути увагу на появу неактуальних і неактивних полів

Очікувано: відсутні неактуальні поля

Фактично:  Поява неактуальних полів, які не реагують на мишку.

![default](https://cloud.githubusercontent.com/assets/13050207/23750932/d33ca2c4-04d7-11e7-8955-dc41d3a15d70.png)

**Comment by Valdisk92** [comment]
Fixed

**Comment by KaterynaMatvieieva** [comment]
Помилку виправлено
