### ISSUE TITLE
Public-Bid: Статус "In reducing" в повідомленні Учаникам акціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1178]
майданчик: https://217.76.194.185:56005/
користувач: anny.efimenko@gmail.com
посилання на аукціон: https://217.76.194.185:56005/purchase_card?year=2017&id=c6151138-c553-4dd3-8049-2dcf65ce0a25
передумова: Аукціон завершений, з Учасником 1 підписано договір.

**Опис:**
Не зрозумілий статус "In reducing" в повідомленні Учаникам акціону що надходить на пошту та в особистий кабінет:
![9f0d774bcb](https://cloud.githubusercontent.com/assets/13050207/23849715/43960f46-07e5-11e7-89a2-7fefff4211b9.jpg)

**Очікуваний результат:**
Відповідно до логіки нотифікації на данному майданчику (повідомляється про зміну статусу у форматі  Попередній статус - Актуальний статус) має бути статус "На аукціоні"

**Фактичний результат:**
Попередній статус: "In reducing" в повідомленні Учаникам акціону

**Comment by KaterynaMatvieieva** [comment]
Помилку виправлено

**Comment by SoftserveQC1** [comment]
Коректні статуси у повідомленнях: 

![9e97d42187](https://cloud.githubusercontent.com/assets/13050207/23860111/a2c77d96-080e-11e7-8252-224a9bb73e7e.jpg)
