### ISSUE TITLE
Скажіть будь-ласка чому на тестовому середовищі, майданчик в Internet Explorer бравзері відрізняється по тенднрах від майданчиків в Chrome та Firefox бравзерах?

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#118]
![chrome_firefox](https://cloud.githubusercontent.com/assets/11062040/6286316/f59ddd18-b90e-11e4-852d-7aaf6e97060e.png)
![explorerfirefox](https://cloud.githubusercontent.com/assets/11062040/6286324/0c349bd4-b90f-11e4-9076-42b0d890b3d0.png)

**Comment by S-Shevchenko** [comment]
@OksanaPakholok Пожалуйста проверьте, воспроизводиться задача?

**Comment by OksanaPakholok** [comment]
На тестовому середовищі http://services.e-tender.biz:100/#/
дані на майданчиках у Firefox, Chrome, IE та Opera бравзерах відображаються однаково.
Можна закривати

**Comment by S-Shevchenko** [comment]
Спасибо, закрываем.
