### ISSUE TITLE
Учасники не отримують сповіщення на e-mail та особистий кабінет про діскваліфікацію

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1182]
Проблема наявна для наступних кейсів:
1. Уч1. та Л. не завантажують протокол протягом 3 діб->
   Уч2. дискваліфікований ліквідатором

Результат - Уч1 та Уч2 не отримують сповіщення на e-mail та особистий кабінет про діскваліфікацію

2. Л. завантажує протокол для Уч1 протягом до 3 діб -> 
Л. підтвержує для Уч1. оплату протягом 11 діб -> 
Л. дискваліфікує Уч1. без завантаження договору -> 
Л. завантажує протокол для Уч2 протягом до 3 діб ->  
Л. підтвержує для Уч2. оплату протягом 11 діб ->  
Л. не завантажує договір з Уч2. протягом 11 діб 

Результат - Уч2 не отримає сповіщення на e-mail та особистий кабінет про діскваліфікацію

3. Л. завантажує протокол для Уч1 протягом до 3 діб -> 
Л. підтвержує для Уч1. оплату протягом 11 діб -> 
Уч2. відмовляється, заберає свій внесок -> 
Л. не завантажує договір з Уч1. протягом 11 діб

Результат - Уч1 не отримає сповіщення на e-mail та особистий кабінет про діскваліфікацію

**Comment by SlaOne** [comment]
и на кого заведен баг? укажите лейбл.

**Comment by OlegNekovalev** [comment]
Пофиксили нотификацию.
Учасники отримують сповіщення на e-mail та особистий кабінет про дискваліфікацію

**Comment by SoftserveQC1** [comment]
Дефект було зафіксано і перевірено
