### ISSUE TITLE
Prom: Участник зареєстрований як ФОП не може подати заявку на аукціон

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1184]
Відтворення:
1. Зареєструвати участника як ФОП 
2. Подати цим участником заявку на попередньо створений аукціон
3. Звернкти увагу на відсутність такої можливості для ФОП

Очікувано: ФОП має можливість подати заявку на аукціон

Фактично: Повідомлення про неможливість
![2](https://cloud.githubusercontent.com/assets/13050207/24099420/d7d5c024-0d77-11e7-9089-314bbb2bcb83.png)
 подати заявку будучи ФОП

**Comment by Rzaporozhets** [comment]
Нужно было в профиле поставить чекбокс "Хочу покупать финансовые активы". Добавили в профиль и сохранили их.
