### ISSUE TITLE
Prom: незрозуміла інформація для користувача у повідомленні після реєстрації

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1185]
Відтворення:
1. Створити нового юзера як участника
2. заповнити всі поля та надіслати дані
3. звернути увагу на повідомлення

Очікувано: відсутність незрозумілої користувачу інформації

Фактично: наявна незрозуміла інформація (стрічки з коду)

![3](https://cloud.githubusercontent.com/assets/13050207/24100045/f9df7bf8-0d7a-11e7-9a9f-3ada9169932c.png)

**Comment by znakharenko** [comment]
Осечка в переводе, поправим

**Comment by SoftserveQC1** [comment]
Багу виправлено та перевірено.
