### ISSUE TITLE
Prom: Статус успішного аукціону відображенно у неправильному роді

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1186]
Передумови: юзер використовує **російську мову** 

Відтворення:
1. Провести успішні торги з двома участниками, де перемагає 1-ий участник
2. Звернути увагу на назву стаутуса завершених торгів російською мовою

Очікувано: надпис "Завершен", та "Обьявлен"

Фактично: надпис "Завершена", та "Обьявлена"

![4](https://cloud.githubusercontent.com/assets/13050207/24107631/efc8d59c-0d93-11e7-8906-45b26336ba11.png)

"

**Comment by Rzaporozhets** [comment]
Если счтитать что это Процедура (она), тогда статус правильный.

**Comment by SoftserveQC1** [comment]
В нас на табі пише "Аукцион", яким чином юзер догадається що це "Процедура", судячи по тому що пише на формі, мова йде не про "Процедуру", а про "Аукцион" 
Процедура - поняття дуже обширне, і стосується швидше розробників, а ніж користувачів які беруть участь у аукціоні

**Comment by znakharenko** [comment]
Поправим, крайне минорный ишью.
