### ISSUE TITLE
Prom: Участникам аукціону та замовнику не приходить лист на пошту про завершення успішних торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1187]
У разі питань нотифікації на пошту, звязатись з Oleksandr Akulenko

Відтворення:
1. Провести успішні торги з двома участниками, де 1-ий участник стає переможцем
2. Зайти на пошту замовника та участників 

Очікувано: наявність листа про успішне завершення торгів 

Фактично: відсутність листа про успішне завершення торгів

![5](https://cloud.githubusercontent.com/assets/13050207/24105603/12fb9622-0d8e-11e7-802d-facdfa27e644.png)
![5](https://cloud.githubusercontent.com/assets/13050207/24105604/13003a7e-0d8e-11e7-95ef-52c341e2127b.png)

**Comment by znakharenko** [comment]
До завершения первых торгов сделаем :)

**Comment by znakharenko** [comment]
Можно проверять
