### ISSUE TITLE
Prom: Замовник немає змоги змінити дані про аукціон, які він вже заповнив

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1188]
Відтворення:
1. Залогінитись як замовник
2. Створити нові торги, оголосити їх
3. Спробувати редагувати торги

Очікувано: користувач може змінити дані про торги, які він уже вводив

Фактично: поля, які користувач вже заповнював є неактивними

![6](https://cloud.githubusercontent.com/assets/13050207/24106487/a9fe5f58-0d90-11e7-84a3-f3d662289543.png)
![6](https://cloud.githubusercontent.com/assets/13050207/24106488/aa1363e4-0d90-11e7-91e5-f5df89392e81.png)

**Comment by Rzaporozhets** [comment]
Это было изначально задумано и такая реализация на всех площадках.

**Comment by SoftserveQC1** [comment]
Не баг
