### ISSUE TITLE
Чи повинна кнопка "Очистити" на майданчику, в розширеному фільтрі очищати поле "Пошук за номером тендера"?

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#119]
![clearbutton](https://cloud.githubusercontent.com/assets/11062040/6286864/d348d0aa-b914-11e4-8edf-b145f2e44229.png)

**Comment by S-Shevchenko** [comment]
Нет.

**Comment by OksanaPakholok** [comment]
Дякую за відповідь. Відповідь аплікації - очікувана.
