### ISSUE TITLE
Prom: Можливо встановити мінімальний крок аукціону нижче 1% при створенні та редагуванні аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1190]
https://zakupki.dz-test.net/

**Опис:** Можливо встановити мінімальний крок аукціону менше 1% від вартості лоту при **створенні аукціону та при його редагуванні**, хоча згідно [вимог](https://docs.google.com/document/d/14Yav0iwWOHd-6NeZ_P4fHlNT8e22Hlo24RVz6rSed4M/edit) мінімальний крок має складати від 1% до 100% від вартості лоту включно

**Відтворення:**
1. Залогінитись як Замовник prom-organizator@yopmail.com
2. Створити нові торги (Аукціони->Новий аукціон)
3. Заповнити всі поля валідними значеннями окрім мінімального кроку
4. Внести значеннями мінімального кроку менше 1% від початкової вартості
5. Опублікувати аукціон (кнопка Оголосити аукціон)

**Очікуваний результат:** система видасть повідомлення про помилку, що мінімальний крок повинен бути не менше 1% від початкової вартості згідно с.9 [ТЗ](https://docs.google.com/document/d/14Yav0iwWOHd-6NeZ_P4fHlNT8e22Hlo24RVz6rSed4M/edit) (мінімальний крок має складати від 1% до 100% від вартості лоту)

**Фактичний результат:** створено аукціон із значенням мінімального кроку менше 1% від вартості лоту включно

![1](https://user-images.githubusercontent.com/13050207/27855018-8cdc71b4-6171-11e7-9664-2fbbb5f8e99a.png)
![2](https://user-images.githubusercontent.com/13050207/27855017-8cdc71f0-6171-11e7-85f1-ec06d4b81e1d.png)

**Comment by znakharenko** [comment]
Можно получить ссылку на требования, в которых это указанно?

**Comment by SoftserveQC1** [comment]
https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.qpazhmpkb3j 
На 6 ст.

**Comment by znakharenko** [comment]
Спасибо, а можно цитату, а то не могу найти.
"Мінімальний крок аукціиону (за замовчуванням - 1% від ціни продажу)" - явно не то

**Comment by SoftserveQC1** [comment]
Це і є то, мінімальний крок аукціону - це то, що повинно бути мінімум 1%

**Comment by znakharenko** [comment]
Причину переоткрытия укажите пожалуйста, а то мы так и не пришли к пониманию.

**Comment by SoftserveQC1** [comment]
помилкове закриття, не було інформації про те що баг вже пофіксаний, відповідно ще не відбулася перевірка

**Comment by SoftserveQC1** [comment]
Дефект перевідкрито, досі відтворюється як при створенні так і при редагуванні аукціону

**Comment by SoftserveQC1** [comment]
Згідно нових змін у регламенті не є багом, головне що є можливість встановити мінімальний крок у розмірі 1%, розмір кроку на відповідальності замовника

**Comment by SoftserveQC1** [comment]
Дефект первірено. Ні при створенні, ні при редагуванні аукціону не можливо встановити мінімальний крок аукціону нижче 1%.
