### ISSUE TITLE
Smart: Відсутній тип документу "Кваліфікаційні вимоги замовника" при оголошенні продажу активів 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1193]
майданчик: http://test.smarttender.biz
користувач: PPR_TEST_FGI

*Опис:* Коли Замовник додає документи при оголошенні продажу активів, відсутній тип документу "Кваліфікаційні вимоги замовника"  

*Кроки:*
1. Залогінитись на майданчик як Замовник 
2. Перейти на "Аукціони ФДМ на продаж(тестові)"
3. Додати аукціон
4. На формі оголошення продажу активів  перейти на вкладку "Завантаження документаціі"
5. Додати документ
6. Обрати тип доданого документу

*Очікуваний результат:*
Замовник має можливість додати документ типу "Кваліфікаційні вимоги замовника"

*Фактичний результат:*
Тип "Кваліфікаційні вимоги замовника" відсутній у переліку доступних до додавання.

![1](https://cloud.githubusercontent.com/assets/13050207/24151626/f76af71c-0e51-11e7-8ff5-9bc58bfc9b8b.png)

**Comment by f3man** [comment]
Питання вирішено

**Comment by SoftserveQC1** [comment]
Перевірено. Замовник має можливість додати документ типу "Кваліфікаційні вимоги замовника"
![54ff11ed87](https://cloud.githubusercontent.com/assets/13050207/24201823/de097320-0f19-11e7-9b21-68180add452e.jpg)
