### ISSUE TITLE
DTO: При створенні аукціону замість единого типу оголошення "Майно Замовника" можна обрати один з чотирьох видів аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1195]
http://www.dz3.byustudio.in.ua/

**Опис:** Створюючи аукціон Замовник може вибрати тип оголошення із чотирьох видів (два з яких "майно банків" та "права та вимоги"), хоча має бути лише один тип оголошення аукціону - "Майно Замовника".

**Відтворення:**
1) Залогінитись як Замовник checkdto@gmail.com
2) Натиснути кнопку "Створити аукціон"
3) У формі створення аукціону натиснути на дропбокс "Тип оголошення"

**Очікуваний результат:** У дропбоксі є лише один тип оголошення аукціону - "Майно Замовника"

**Фактичний результат:** Створюючи аукціон Замовник може вибрати тип оголошення із чотирьох видів (два з яких "майно банків" та "права та вимоги"), типу "Майно Замовника" - немає
![default](https://cloud.githubusercontent.com/assets/13050207/24152430/4514f7a4-0e54-11e7-9dc7-ca6e02b989ac.png)

**Comment by PaulBoroday** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
