### ISSUE TITLE
DTO: При реєстрації користувача замість типу Замовник фігурує термін Банк

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1196]
http://www.dz3.byustudio.in.ua/

**Відтворення:** 
1) Перейти на майданчик
2) Натиснути кнопку "Реєстрація"
3) Оглянути перелік "Тип Реєстрації"

**Очікуваний результат:** Можливо обрати тип учасника - Замовник

**Фактичний результат:** Замість типу учасника "Замовник" присутній тип учасника - "Банк"
![default](https://cloud.githubusercontent.com/assets/13050207/24152780/4c23079c-0e55-11e7-8d87-dc3ae7a73b7f.png)

**Comment by PaulBoroday** [comment]
Готово

**Comment by SoftserveQC1** [comment]
Дефект виправлено
