### ISSUE TITLE
Smart: Невірна інформація про тип процедури та Замовника в описі аукціону 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1198]
майданчик: http://test.smarttender.biz
користувач: PPR_TEST_FGI
посилання на аукціон: http://test.smarttender.biz/government/details/748682 
передумова: мати опублікований аукціон 

**Опис:** Відображення інформації про тип процедури та Замовника в описі аукціону не відповідає прийнітій у вимогах термінології

**Кроки:**

1. Залогінитись на майданчик
2. Переглянути інформацію про відповідний лот

**Очікуваний результат:**
На сторінці аукціону користувач бачить наступне: 
    **Тип процедури:**
    ProZorro.Продажі (Майно) 
   
**Фактичний результат:**
На сторінці аукціону користувач бачить наступне: 
    **Тип процедури:**
    Майно банку
   
![b378bbe568 1](https://cloud.githubusercontent.com/assets/13050207/24157208/6d36f0cc-0e61-11e7-877e-8d365cb90938.jpg)

**Comment by SoftserveQC1** [comment]
При створенні процедури на майданчмку вказується тип "Продаж майна"
![0c89639cfe](https://cloud.githubusercontent.com/assets/13050207/24157864/4b56cfde-0e63-11e7-8ad2-e8ca1a861253.jpg)

**Comment by f3man** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Інформація уточнена Проектним відділом:
"Тип процедури варто використовувати назву ProZorro.Продажі (Майно)"

**Comment by f3man** [comment]
@SoftserveQC1 Актуалізовано

**Comment by SoftserveQC1** [comment]
На сторінці аукціону користувач бачить наступне:
Тип процедури:
ProZorro.Продажі (Майно)
![4baa6d9c28](https://cloud.githubusercontent.com/assets/13050207/24198104/0c6c4420-0f0d-11e7-83b5-bb2a5fdc1f01.jpg)
