### ISSUE TITLE
Smart: Невірне посилання на регламент в описі аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1199]
майданчик: http://test.smarttender.biz
користувач: PPR_TEST_FGI
посилання на аукціон: http://test.smarttender.biz/government/details/748682
передумова: мати опублікований аукціон

**Опис:** Невірне посилання на регламент. При процедурі опублікованій у ЦБД-2 має бути відповідне посилання на регламент. 

**Кроки:**

1. Залогінитись на майданчик
2. Переглянути інформацію про відповідний лот
3. Перейти за посиланням на регламент

**Очікуваний результат:**
При процедурі опублікованій у ЦБД-2 має бути відповідне посилання на регламент роботи електронної торгової системи щодо проведення публічних торгів (аукціонів) з продажу майна(активів) (Регламент ЕТС) 

**Фактичний результат:**
Посилання на регламент ProZorro.Продажі
(активний лінк - https://drive.google.com/file/d/0B7KIe21cMRzrbm9oZ3dsS0RsVG8/view)

![2d4b02483f](https://cloud.githubusercontent.com/assets/13050207/24158519/3a0aecea-0e65-11e7-9103-693f8703a39e.jpg)

**Comment by SoftserveQC1** [comment]
Станом на 23.03.2017 остаточно затверджений регламент по проекту ProZorro.Продажі (Майно) відсутній, тому помилка потребує перегляду після вступу відповідного оновленого документу в силу, та поширення актуальної лінки між зацікавленими сторонами.

**Comment by f3man** [comment]
полагоджено

**Comment by SoftserveQC1** [comment]
Перевірено. Посилання працює. 
Веде до наступного документу(актуальне станом на 28.03.2017): https://drive.google.com/file/d/1iQ4lTWf3XLeNQZXZMj2fKqh6ADs9bHhqKCIB-HmdfyE/view
