### ISSUE TITLE
Bugs Prom.Ua

### ISSUE THREAD

**Issue by dmarghania** [openprocurement/frontend#12]
1 – Numbers and Symbols

![image](https://cloud.githubusercontent.com/assets/10658369/5862093/674190f6-a288-11e4-998c-2d8a906ebdbc.png)

2 – Error opening announced tender 
![image](https://cloud.githubusercontent.com/assets/10658369/5862108/80257128-a288-11e4-90d0-583eb5700daa.png)

![image](https://cloud.githubusercontent.com/assets/10658369/5862128/9b9c8dec-a288-11e4-87c5-f7ec2773e059.png)

3 – Тендер не должен объявляться без прикрепления документа, без указания даты поставки. Все поля должны быть обязательными.
4. Размер одного файла ограничен 1 МБ. Это явно мало. У нас в Грузии 8МБ. Я думаю должно быть минимум 10МВ.
5.Не видно даты объявления тендера и так же не видно даты изменения статуса (Отменен не видно когда).
6.Каждое изменение статуса кроме статуса “тендер не состоялся” должен требовать прикрепления документа (протокол заседания тендерной комиссии) и без этого не должен меняться. 
7.Фактически можно сказать, что фильтров поиска нет кроме 2 критерии; как минимум должен быть поиск по заказчику, по регионам, по времени, по сумме, по поставщику в тех  тендерах где закончился аукцион и есть минимум один поставщик.

**Comment by myroslav** [comment]
@dmarghania: разработчики будут очень признательны, если в будущем каждая ошибка будет отдельным issue. Так можна будет по одной закрывать, и каждой назначить отдельный приоритет.

**Comment by darchik** [comment]
1. дело в том что мы выгружаем все единицы измерений, которые были переданы на ЦБД вместе с тендером. Их каждая площадка обзывает как хочет. Здесь больше просьба для всех площадок - нормально переименовывать.

**Comment by darchik** [comment]
1. уже этой ошибки нет, временная ошибка была
2. это к ЦБД. Эти поля в ЦБД необязательны и на этом все настаивали. Я согласен что дата поставки может быть необязательна, но файл - обязателен.
3. размер файла ограничен ЦБД. Мирослав обещал увеличить лимит.
4. Такой лог мы не ведем пока...
5. Все статусы автоматические, кроме перехода с квалификации на подписание договора / тендер не состоялся. Только на этом этапе загружаются документы. Это логика ЦБД.
6. поиск будем улучшать конечно же.
