### ISSUE TITLE
DTO: При створенні лоту перелік доступних до завантаження документів не повний

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1201]
http://www.dz3.byustudio.in.ua/

**Опис:** Створюючи аукціон Замовник не має можливості додати документи категорії "Кваліфікаційні вимоги замовника", "Типовий договір" та "Інші документи", натомість у переліку доступних до завантаження документів є зайві "Паспорт торгів", "Публічний паспорт активу", "Договір NDA" та посилання на Публічний паспорт активу.

**Відтворення:**
1) Залогінитись як Замовник checkdto@gmail.com
2) Натиснути кнопку "Створити аукціон"
3) Натиснути на поле "Документація до лоту"
4) Натиснути на поле "Додати файл документації"
5) Додати файл (наприклад .png не більше 1мб)
6) Натиснути на дропбпокс "Тип документа"

**Очікуваний результат:** Замовник має можливість додати документи категорії **_"Кваліфікаційні вимоги замовника", "Типовий договір" та "Інші документи"_** згідно [вимогам](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.beiwod5g2jrq) стр.6 п.1 Створення Лоту - дії користувача

**Фактичний результат:** Замовник не може додати документи категорії **_"Кваліфікаційні вимоги замовника", "Типовий договір" та "Інші документи"_**, бо вони відсутні. Натомість присутні зайві до завантаження категорії документів "Паспорт торгів", "Публічний паспорт активу", "Договір NDA" та посилання на Публічний паспорт активу.
![default](https://cloud.githubusercontent.com/assets/13050207/24189129/8033622e-0eec-11e7-8239-5ba3108db4a1.png)
![default](https://cloud.githubusercontent.com/assets/13050207/24189130/803b6d20-0eec-11e7-86e9-b0b499160687.png)

**Comment by OSerhii** [comment]
Проектний офіс вирішив залишити це саме у такому стані.
