### ISSUE TITLE
Prom: Різні абзаци повідомлень при нотифікації дій, які зробив користувач

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1202]
Відтворення:
1. Оголосити торги
2. В якості 1 (або 2-го) участника подати пропозицію та одразу підписатись на аукціон
3. Звернути увагу на абзаци повідомлень при появі нотифікації зверху на формі

Очікувано: повідомлення відображаються в одному форматному стилі

Фактично: різна абзацна відстань у різних нотифікацій

![9](https://cloud.githubusercontent.com/assets/13050207/24193273/6bb11946-0efa-11e7-92fb-f2cc473702f6.png)

**Comment by znakharenko** [comment]
Поправим позже, приоритетность минимальна

**Comment by SoftserveQC1** [comment]
Дефект виправлено та перевірено.
