### ISSUE TITLE
Smart: Не працює кнопка "Додати" на табі "Завантаження документації" при додаванні оголошення з продажу активів 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1203]
майданчик: http://test.smarttender.biz
користувач: PPR_TEST_FGI

**Опис:** При додаванні оголошення з продажу активів  відсутня можливість прикріпити документ через те що не працює кнопка "Додати" на табі "Завантаження документації"

**Кроки:**

1. Залогінитись на майданчик як замовник.
2. Додати оголошення з продажу активів.
3. У формі для створеня оголошення перейти на табу "Завантаження документації".
4. Спробувати додати документ за допомогою кнопки "Додати".

**Очікуваний результат:**
1. Кнопка "Додати" працює. 
2. Документи до оголошення успішно додані.

**Фактичний результат:**
1. Кнопка "Додати" не працює. 
2. Відсутня можливість додати документи до оголошення.

![a88a86dfcd](https://cloud.githubusercontent.com/assets/13050207/24196244/b66c9c34-0f05-11e7-9fe6-0c809a80c684.jpg)

**Comment by f3man** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Перевірено.
Документи успішно додані.
