### ISSUE TITLE
Smart: Причини при спробі скасувати аукціон не відповідають вимогам.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1204]
майданчик: http://test.smarttender.biz
користувач: PPR_TEST_FGI
посилання на аукціон: http://test.smarttender.biz/government/details/749496
передумова: мати опублікований аукціон

**Опис:** Якщо Замовник хоче скасувати проведення вже оголошеного аукціону, він має вказати причину. Перелік причин не відповідає зазначеним у вимогах. 

**Кроки:**

1. Залогінитись на майданчик як замовник.
2. Обрати оголошену процедуру на стадії "Прийом пропозицій"
3. Натиснути "Отмена аукциона"
4. У формі Скасування аукціону обрати причину скасування.

**Очікуваний результат:**
Можливі причини скасування аукціону (drop down):
   - Згідно рішення виконавчої дирекції Замовника
   - Порушення порядку публікації оголошення 

**Фактичний результат:**
Причини скасування (drop down):
   - Згідно рішення виконавчої дирекції ФГВФО
   - Порушення порядку публікації оголошення 

![bc239538c5](https://cloud.githubusercontent.com/assets/13050207/24197426/3555d2fa-0f0a-11e7-8886-e50916e00fc9.jpg)

**Comment by f3man** [comment]
Питання вирішено

**Comment by SoftserveQC1** [comment]
Перевірено. 
Можливі причини скасування аукціону (drop down):
Згідно рішення виконавчої дирекції Замовника
Порушення порядку публікації оголошення

![72d2e65aa2](https://cloud.githubusercontent.com/assets/13050207/24241868/eb45be04-0fbe-11e7-971f-b38c806a5c30.jpg)
