### ISSUE TITLE
Smart: Неповна локалізація майданчика

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1205]
майданчик: http://test.smarttender.biz
користувач: PPR_TEST_FGI
передумова: мати опублікований аукціон на стадії "Прийом пропозицій"		

**Опис:** В кабінеті Замовника неповна локалізація 

**Кроки:**
1. Залогінитись на майданчик як замовник.
2. Перейти на "Аукціони ФДМ на продаж(тестові)"
3. Обрати опублікований аукціон
4. Перевірити доступні кнопки

**Очікуваний результат:**
1. Наявність кнопки "Скасування аукціону"
2. Відсутність кнопки "Отмена Тендера" для Замовника що працює в кабінеті для "Аукціони ФДМ на продаж(тестові)"

**Фактичний результат:**
1. Наявність кнопки "Отмена аукціону"
2. Наявність кнопки "Отмена Тендера"
![e7c84ba803](https://cloud.githubusercontent.com/assets/13050207/24200975/6751dc92-0f17-11e7-9f19-c5d768b482c3.jpg)

**Comment by SoftserveQC1** [comment]
Також відсутня локалізація у відображенні стадій аукціону:
![d805424f67](https://cloud.githubusercontent.com/assets/13050207/24201211/0be1dbe0-0f18-11e7-9b8f-716a7a60fdf4.jpg)

**Comment by SoftserveQC1** [comment]
Також відсутня локалізація у відображенні валюти та в повідомленні що користувач отрумує при внесенні змін до аукціону:
![b236e55659](https://cloud.githubusercontent.com/assets/13050207/24204192/6a20623c-0f20-11e7-8ff3-9dca8e98fb5e.jpg)

**Comment by f3man** [comment]
Полагоджено

**Comment by SoftserveQC1** [comment]
Форма додавання оголошення:
![a6f9273599](https://cloud.githubusercontent.com/assets/13050207/24240832/a1173d92-0fbb-11e7-982c-cde68a505971.jpg)


Вкладинка "Тестові аукціони на продаж"
![0b68636d7a](https://cloud.githubusercontent.com/assets/13050207/24240996/0f341660-0fbc-11e7-9d97-edc28c607ac1.jpg)

![73ca151085](https://cloud.githubusercontent.com/assets/13050207/24241127/7f74fda4-0fbc-11e7-9363-a551036a9c0e.jpg)

**Comment by f3man** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Перевірено.
