### ISSUE TITLE
Smart: Розкривається інформація про автора запитання/вимоги 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1207]
майданчик: http://test.smarttender.biz
користувач: PPR_TEST_FGI
передумова: мати опублікований аукціон на стадії "Прием предложений"

**Опис:** При отриманні повідомлення про запитання Замовником розкривається інформація про автора запитання/вимоги  

**Кроки:**
1. Залогінитись на майданчик як Учасник
2. Знайти опублікований Замовником аукціон 
3. Задати питання по аукціону
4. Залогінитись на майданчик як Замовник.
5. Перейти на "Аукціони ФДМ на продаж(тестові)"
6. Переглянути повідомлення

**Очікуваний результат:**
Інформація про автора запитання/вимоги не розкривається

**Фактичний результат:**
 Замовникові розкривається інформація про автора запитання/вимоги:

![a721f51c46](https://cloud.githubusercontent.com/assets/13050207/24208829/5282f51a-0f2d-11e7-8d84-e8933f2fe572.jpg)

![8c1226b16d](https://cloud.githubusercontent.com/assets/13050207/24209073/e97ea59a-0f2d-11e7-965a-a60acc407e92.jpg)

**Comment by f3man** [comment]
питання вирішено

**Comment by SoftserveQC1** [comment]
Перевірено.
Інформація про автора запитання/вимоги не розкривається
![7f7a660874](https://cloud.githubusercontent.com/assets/13050207/24241740/89078a10-0fbe-11e7-9609-66463620424a.jpg)
