### ISSUE TITLE
Smart: Не працюють посилання на аукціони з кабінету Замовника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1208]
майданчик: http://test.smarttender.biz
користувач: PPR_TEST_FGI
передумова: мати опубліковані аукціони

**Опис:** Замовник не може переглянути веб-сторінку аукціону за посиланням зі стовбчику "Номер тендера в ЦБД"

**Кроки:**

1. Залогінитись на майданчик як Замовник.
2. Переглянути веб-сторінку аукціону за посиланням зі стовбчику "Номер тендера в ЦБД"
![918090e119](https://cloud.githubusercontent.com/assets/13050207/24211673/76d72bcc-0f35-11e7-8475-63450ebfe373.jpg)

**Очікуваний результат:**
Лінка веде на веб-сторінку відповідного аукціону 

**Фактичний результат:**
Кочистувач переходить на сторінку з повідомленям "Тендер не знайдено"
![01b8679d7b](https://cloud.githubusercontent.com/assets/13050207/24211714/98310ec8-0f35-11e7-84a2-c892adbdf74c.jpg)

**Comment by f3man** [comment]
Наскільки я знаю, тестові процедури не публікуються на офіційному порталі.
А якщо треба перейти до сторінки на самому майданчику, необхідно клікати по внутрішньому номеру аукціону

**Comment by SoftserveQC1** [comment]
Баг закритий, тому що зі слів розробників майданчика є два джерела даних про оголошений аукціон:
"є централізований портал ProZorro, а є майданчик, Замовники та Учасники торгів дивляться в два джерела даних(на сторінці аукціону ви можете клікнути по номеру *UA-PS...*  і буде такий саме результат)
сама ідея відображення двох лінків, що ведуть до порталу та до майданчика, була реалізована з потреб Замовників."
