### ISSUE TITLE
Smart: Учасник не отримує повідомлення про зміну статусу його заявки чи статусу торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1209]
майданчик: http://test.smarttender.biz
користувач: testtest3@softserveinc.com
передумова: мати опублікований аукціон на стадії  "Прийом пропозицій"			

**Опис:** Після подання пропозиції Учасник в особистому кабінеті не отримує повідомлення про прийняття пропозиції Майданчиком та перевірку гарантійного внеску/Замовниківської гарантії/інших документів

**Кроки:**
1. Залогінитись на майданчик як Учасник.
2. Знайти опублікований аукціон
3. Подати пропозицію
4. Виконати публікацію
5. Перейти в Особистий кабінет
6. Відкрити Повідомлення > Мої повідомлення

**Очікуваний результат:**
1. Учасник в особистому кабінеті отримує повідомлення про прийняття пропозиції Майданчиком та перевірку гарантійного внеску/Замовниківської гарантії/інших документів

**Фактичний результат:**
1. Учасник в особистому кабінеті не отримує жодного повідомлення про прийняття пропозиції Майданчиком та перевірку гарантійного внеску/Замовниківської гарантії/інших документів

**Comment by SoftserveQC1** [comment]
Учасник також не отримує повідомлення про успішну валідацію.

**Очікуваний результат:**
1. Отримати повідомлення в особистому кабінеті Учасника при наступному вході в нього. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до аукціону. 
2. Отримати повідомлення електронною поштою. 
В повідомленні повідомляється про публікацію в ЦБД пропозиції, дату і час публікації, дату і час початку аукціону і посилання на аукціон в режимі учасника

**Comment by SoftserveQC1** [comment]
Учасник отримує миттєве повідомлення про те що пропозицію подано відразу після нитискання "Надіслати пропозицію"
![b8398dfbb5](https://cloud.githubusercontent.com/assets/13050207/24247082/e02a2f28-0fd2-11e7-8ec8-b19a70ae39c1.jpg)

![236d41ca46](https://cloud.githubusercontent.com/assets/13050207/24247135/213f73a6-0fd3-11e7-8afe-1a4952b534e5.jpg)

**Comment by SoftserveQC1** [comment]
Участик не отримує повідомлення про скасування  аукціону по якому він задав запитання.

**Очікуваний результат:**
1. Отримати повідомлення про скасування Організатором Аукціону в особистому кабінеті при наступному вході в нього.
2. Отримати повідомлення про скасування Організатором Аукціону  електронною поштою

**Comment by SoftserveQC1** [comment]
Учасник, що посів друге місце, не отримує повідомлення про зайняття ним другого місця в аукціоні:

**Очікуваний результат:**

1. Отримати повідомлення про зайняття Учасником другого місця в аукціоні при наступному вході в кабінет і про можливість не забирати гарантійний внесок на протязі 11 робочих днів під час яких Переможець аукціону може бути дискваліфікований. В інтерфейсі повідомлення є кнопка “Забираю гарантійний внесок зараз”, при натисканні на неї в ЦБД передається інформація про те, що другий кандидат відсутній. 
2. Отримати повідомлення про зайняття Учасником другого місця в аукціоні  електронною поштою і про можливість не забирати гарантійний внесок на протязі 11 робочих днів під час яких Переможець аукціону може бути дискваліфікований. В інтерфейсі повідомлення є кнопка “Забираю гарантійний внесок зараз”. При натисканні кнопки “Забираю гарантійний внесок зараз” в ЦБД передається інформація про те, що другий кандидат відсутній.

**Comment by f3man** [comment]
Скасування аукціону по якому він задав питання - **виконано**
Пропозиція подана по ~тендеру~ аукціону -  **виконано**
Повідомлення до особистого кабінету після подачі пропозиції - **виконано**
Повідомлення про успішну валідацію- **виконано** (акцептування заявки та доступ до подачі пропозиції то воно і є, з лінком до аукціону де буде відкрита кнопка "Подати пропозицію")

**Comment by SoftserveQC1** [comment]
Наступна проблема відтворюється:
Участик не отримує повідомлення про скасування аукціону по якому він задав запитання.

**Кроки:**

1. Залогінитись на майданчик як Учасник.
2. Знайти опублікований аукціон
3. Задати питання по аукціону
4. Залогінитись на майданчик як Замовник
5. Скасувати аукціон (з п.2)
6. Залогінитись на майданчик як Учасник.
7. Відкрити Повідомлення > Мої повідомлення

**Очікуваний результат:**
Отримати повідомлення про скасування Організатором Аукціону в особистому кабінеті при наступному вході в нього.
Отримати повідомлення про скасування Організатором Аукціону електронною поштою

**Comment by SoftserveQC1** [comment]
**Участик не отримує повідомлення про неуспішну валідацію**

**Кроки:**

1. Залогінитись на майданчик як Учасник.
2. Знайти опублікований аукціон
3. Подати заявку на участь в аукціоні
4. Відхилити заявку з боку майданчика
5. Залогінитись на майданчик як Учасник.
6. Відкрити Повідомлення > Мої повідомлення

**Очікуваний результат:**
1. Отримати повідомлення в особистому кабінеті Учасника при наступному вході в нього. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до аукціону. 
2. Отримати повідомлення електронною поштою. 
3. В повідомленні повідомляється про неуспішне проходження валідації (з вказанням причини) або відсутність гарантійного внеску / банківської гаранії та лінк на пропозицію для внесення змін

Фактичний результат:
1. Учасник не отримує повідомлення про неуспішну валідацію
2. Учасник не отримує інформації чому його заявка була відхилена
3. Учасник бачить що заявка відхилена лише на сторінці аукціону: 
![86f07bc7cc](https://cloud.githubusercontent.com/assets/13050207/24301280/e38ad83a-10b7-11e7-9cc0-7707957d98b2.jpg)

**Comment by SoftserveQC1** [comment]
>>> Повідомлення до особистого кабінету після подачі пропозиції - виконано
Повідомлення про успішну валідацію- виконано (акцептування заявки та доступ до подачі пропозиції то воно і є, з лінком до аукціону де буде відкрита кнопка "Подати пропозицію")

Перевірено, учасник отримує наступне повідомлення: 
![5948fb01e6 1](https://cloud.githubusercontent.com/assets/13050207/24347315/958fd330-12e0-11e7-8496-9327bfc78c41.jpg)

**Comment by f3man** [comment]
Усе виправлено

**Comment by SoftserveQC1** [comment]
Перевірено. Повідомлення надходять учасникам.
