### ISSUE TITLE
DTO: Відсутні повідомлення про визнання Учасника Кандидатом наступним за переможцем

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1210]
http://www.dz3.byustudio.in.ua/

**Передумова:**
- Залогінитись як Замовник checkdto@gmail.com
- Натиснути кнопку "Створити аукціон"
- Заповнити усі поля валідними даними та опублікувати аукціон
- Залогінитись як Учасник checkdto1@gmail.com
- Зробити ставку та підтвердити ії у Адміна
- Внести гарантійний внесок (відповідна кнопка у тілі аікціону)
- Залогінитись як Учасник checkdto2@gmail.com
- Зробити ставку та підтвердити ії у Адміна
- Внести гарантійний внесок (відповідна кнопка у тілі аікціону)
- Дочекатися завершення аукціону, початку кваліфікації

**Відтворення:**
1. Залогуйтесь в систему під учасником, який зайняв 2-ге місце в аукціоні
2. Перевірити "повідомлення" у особистому кабінеті
3. Перевірити пошту на наявність листа

**Очікуваний результат:**
Отримати повідомлення про зайняття Учасником другого місця в аукціоні на пошту та/або при наступному вході в кабінет і про можливість не забирати гарантійний внесок на протязі 11 робочих днів під час яких Переможець аукціону може бути дискваліфікований. В інтерфейсі повідомлення є кнопка “Забираю гарантійний внесок зараз”, при натисканні на неї в ЦБД передається інформація про те, що другий кандидат відсутній([Тестові сценарії](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.1fap1z6or798) рівень 2 (Учасник), кейс 10).

**Фактичний результат:**
Учаснику, який зайняв 2-ге місце в аукціоні не приходить повідомлення про це ні  по електронній пошті, ні в Особистому кабінеті.

**Comment by w-be** [comment]
Не баг. В даній ітерації не вимагається корекна робота функціоналу avarding 2.0.

**Comment by w-be** [comment]
Згідно https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#, ст 16, пункт 10 це баг.

**Comment by SoftserveQC1** [comment]
Повідомлення учаснику, який зайняв друге місце в аукціоні, приходять.
