### ISSUE TITLE
Smart: Повідомлення містять термін "тендер" та неочевидні посилання

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1211]
майданчик: http://test.smarttender.biz
користувач: testtest3@softserveinc.com
передумова: мати опублікований аукціон на стадії  "Прийом пропозицій"			

**Опис:** Після подання пропозиції Учасник в особистому кабінеті отримує повідомлення з нагадування про аукціон. В даному повідомленні присутнії термін "тендер" та неочевидне посилання. 

**Кроки:**
1. Залогінитись на майданчик як Учасник.
2. Знайти опублікований аукціон
3. Подати пропозицію
4. Виконати публікацію
5. Дочекатись отримання повідомлення з нагадуванням про аукціон
6. Перейти в Особистий кабінет
7. Відкрити Повідомлення > Мої повідомлення
8. Відкрити повідомлення з темою "Продаж майна. Нагадування про аукціон по тендеру №***"

**Очікуваний результат:**
1. Термін "тендер" не використовується для проекту ProZorro.Продажі (Майно) 
2. Посилання на аукціон віглядає як лінк

**Фактичний результат:**
1. Багаторазове використання терміну "тендер" 
2. Посилання на аукціон неочевидне

![f8a9715124](https://cloud.githubusercontent.com/assets/13050207/24248385/d74ae21c-0fd7-11e7-894f-53fd4609090e.jpg)

**Comment by SoftserveQC1** [comment]
Аналогічні проблеми в повідомленні "Ваша пропозиція зараз на розгляді..."

![d2ee9059db](https://cloud.githubusercontent.com/assets/13050207/24249048/77c3aaa6-0fda-11e7-8dbd-fe6b50deac9b.jpg)

**Comment by f3man** [comment]
Ваша пропозиція зараз на розгляді - **виконано**

**Comment by SoftserveQC1** [comment]
Аналогічні проблеми в повідомленні "Зміна статусу Вашої пропозиції "
![dcf60941f6](https://cloud.githubusercontent.com/assets/13050207/24295308/cc514826-10a2-11e7-8e0a-07f509fd2b02.jpg)

**Comment by SoftserveQC1** [comment]
![aa10c35780](https://cloud.githubusercontent.com/assets/13050207/24350267/4417aa50-12ea-11e7-9753-7bcabd2cb077.jpg)

**Comment by f3man** [comment]
усе виправлено

**Comment by SoftserveQC1** [comment]
Перевірено.
