### ISSUE TITLE
Smart: Зміст повідомлення про визнання Учасника переможцем в аукціоні не відповідає вимогам

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1212]
майданчик: http://test.smarttender.biz
користувач: testtest3@softserveinc.com
передумова: прийняти участь в аукціоні та бути визнаним переможцем 			

**Опис:** Зміст повідомлення про визнання Учасника переможцем в аукціоні не відповідає вимогам.

**Кроки:**
1. Залогінитись на майданчик як Учасник.
2. Перейти в Особистий кабінет
3. Відкрити Повідомлення > Мої повідомлення
4. Відкрити повідомлення з темою "Ваша пропозиція зараз на розгляді..."

**Очікуваний результат:**
1. Учасник в особистому кабінеті отримує повідомлення **про визнання Учасника переможцем і необхідність підписати Протокол на протязі трьох діб.**
2. Учасник електронною поштою отримує повідомлення **про визнання Учасника переможцем і необхідність підписати Протокол на протязі трьох діб.** 

**Фактичний результат:**
1. Неочевидним є той факт що учасника визнано переможцем
2. Відсутня інформація про необхідність підписати Протокол на протязі трьох діб

![d4127cee4b](https://cloud.githubusercontent.com/assets/13050207/24250190/abfb49ba-0fde-11e7-8a18-e27e73af0ddc.jpg)

**Comment by w-be** [comment]
Не баг. Протягом 3-х діб - не актуальна вимога дя цієї ітерації. Інформування, що ваша пропозиція на розгляді, означає що ви перейшли до кваліфікації. Цього достатьньо.

**Comment by f3man** [comment]
у будь якому випадку, полагоджено

**Comment by w-be** [comment]
Розібрали питання з Олександром Акуленко: таки баг, повідомлення має бути саме таким як в очікуваному результаті.

**Comment by SoftserveQC1** [comment]
Перевірено.
Учасник отримує наступне повідомлення: 
![5948fb01e6](https://cloud.githubusercontent.com/assets/13050207/24301974/aae8eaa6-10b9-11e7-99b2-8c3cf958d65e.jpg)
