### ISSUE TITLE
Smart: Не працює посилання на регламент торгів при оформленні Учасником заявки на участь в аукціоні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1215]
майданчик: http://test.smarttender.biz
користувач: testtest3@softserveinc.com
передумова: мати посилання на аукціон
аукціон: http://test.smarttender.biz/government/details/753541 

**Опис:** Коли учасник подає заявку на участь в торгах він має заповнити форму та відмітити "Я погоджуюсь з регламентом проведення торгів" у відповідному чекбоксі. Посилання на регламент не працює.

**Кроки:**
1. Залогінитись на майданчик як Учасник.
2. Перейти на веб-сторінку аукціону за відповідним посиланням
3. Нитиснути кнопку "Взяти участь"
4. Перейти за лінкою "регламентом проведення торгів" (чекбокс "Я погоджуюсь з регламентом проведення торгів")

![1efa9d4a51](https://cloud.githubusercontent.com/assets/13050207/24400343/b63525ee-13b8-11e7-9137-df892a03daa2.jpg)

**Очікуваний результат:**
1. Учасник переходить за лінкою до регламенту торгів

**Фактичний результат:**
1. Перехід за лінкою призводить до помилки:
![8ff83b0114](https://cloud.githubusercontent.com/assets/13050207/24400396/f5b1f418-13b8-11e7-9618-27f69431fb18.jpg)

Станом на 23.03.2017 остаточно затверджений регламент по проекту ProZorro.Продажі (Майно) відсутній, тому помилка потребує перегляду після вступу відповідного оновленого документу в силу, та поширення актуальної лінки між зацікавленими сторонами.

**Comment by f3man** [comment]
полагоджено

**Comment by SoftserveQC1** [comment]
Перевірено. Посилання працює. 
Веде до наступного документу(актуальне станом на 28.03.2017): https://drive.google.com/file/d/1iQ4lTWf3XLeNQZXZMj2fKqh6ADs9bHhqKCIB-HmdfyE/view
