### ISSUE TITLE
OpenTender: При реєстрації користувача замість типу Замовник фігурує термін Банк

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1216]
http://test-eauction.open-tender.com.ua/register

**Відтворення:** 
1) Перейти на майданчик
2) Натиснути кнопку голоного меню "Зареєструватись"
3) Натиснути на дропбокс "Реєстрація як"

**Очікуваний результат:** У дропбоксі можливо обрати тип учасника - "Замовник"

**Фактичний результат:** Замість типу учасника "Замовник" присутній тип учасника - "Банк/Ліквідатор"
![default](https://cloud.githubusercontent.com/assets/13050207/24450633/421b1de0-1484-11e7-9eed-fc3fa703ed38.png)

**Comment by IllyaPetrusenko** [comment]
Сделано. Теперь есть выпадайка с выбором "Інше", которая регистрирует человека как заказчика

**Comment by SoftserveQC1** [comment]
При реєстрації не фігурує "Замовник", користувачеві незрозуміло як зареєструватись "Замовником" неймінг полів не відповідає [ручним сценаріям](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#), можливо краще змінити неймінг боксу "Реєстрація як" з "Банк/Ліквідатор" на "Банк/Ліквідатор/Замовник", а у випадайці змінити "Інше" на "Замовник"

**Comment by SoftserveQC1** [comment]
Дефект виправлено
