### ISSUE TITLE
Govfound: Під час підтвердження фінансової авторизації вибиває помилку після натискання кнопки "Детальніше"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1218]
Відтворення:
1. Зареєструвати участника як юридичну особу
2. Підтвердити на пошті
3. На порталі нажати кнопку "детальніше"

Очікувано: відображається необхідна інформація

Фактично: помилка "Not Found 404"

![2](https://cloud.githubusercontent.com/assets/13050207/24452634/d0b29ecc-148c-11e7-9592-6a69557331ca.png)

**Comment by oleg4646** [comment]
Добавили страничку. http://prntscr.com/eqd3fu
