### ISSUE TITLE
Govfound: Відсутня можливість завантажувати документи при реєстрації 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1219]
Відтворення:
1. Нажати кнопку зареєструватись
2. Переглянути форму реєстрації

Очікувано: наявність опції завантажити документи

Фактично: відсутня опція завантажити документи

![3](https://cloud.githubusercontent.com/assets/13050207/24453218/a7908740-148f-11e7-974d-b286d55acb95.png)
![3](https://cloud.githubusercontent.com/assets/13050207/24453220/a7945bc2-148f-11e7-8af0-e4b60bf56252.png)
![3](https://cloud.githubusercontent.com/assets/13050207/24453219/a791d078-148f-11e7-9fd9-ea6147176b89.png)

**Comment by OSerhii** [comment]
Реалізовуватися не буде, оскільки не надано сховища для збереження цих документів. Прошу закрити дефект.

**Comment by SoftserveQC1** [comment]
Дефект виправлено http://eauction.byustudio.in.ua/
#886
