### ISSUE TITLE
При створенні тендера, у словниках, чи очікувана поведінка не відображення усіх значень, при частково введеному коді класифікатора?

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#122]
При введенні у поле "Оберіть класифікатор" - текстового значення - відображаються значення  які співпадають на початку, всередині та кінці;
при введенні - числового значення - відображаються значення, які співпадають лише на початку.

![filter_search](https://cloud.githubusercontent.com/assets/11062040/6326736/7dfc40b4-bb5d-11e4-8a31-4227c3f4bdfa.png)

**Comment by lerich** [comment]
Да, так закладывалось в систему. Поиск производится по алгоритму, что код начинается с этой цифры
