### ISSUE TITLE
Govfound: Після натискання кнопок "Вийти"->"Увійти" юзер не вводить креди знову, а залоговується як попередньо-залогований юзер

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1221]
Відтворення: 
1. Залогінитись на портал
2. Нажати кнопку "Вийти"
3. Нажати кнопку "Увійти"

Очікувано: вибиває форму для входу

Фактично: Юзер залогіненився на портал як попередньо-залогований юзер

![4](https://cloud.githubusercontent.com/assets/13050207/24453986/a1e7c1ac-1492-11e7-827f-d0cde70dda60.png)
![4](https://cloud.githubusercontent.com/assets/13050207/24453984/a1e4198a-1492-11e7-9821-fb328ac9f6a2.png)
![4](https://cloud.githubusercontent.com/assets/13050207/24453985/a1e6da58-1492-11e7-97b3-ec3c776c62e7.png)

**Comment by IllyaPetrusenko** [comment]
fixed . Закройте , пожалуйста дефект.
