### ISSUE TITLE
Smart: Некоректне відображення посилання в повідомленні у випадку коли користувач використовує "Приватний доступ" браузера. 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1222]
майданчик: http://test.smarttender.biz
користувач: testtest3@softserveinc.com
передумова: мати в особистому кабінеті повідомлення типу "Заявка на участь в аукціоні"
аукціон: http://test.smarttender.biz/government/details/754255

**Опис:** Коли учасник використовує "Приватний доступ" в браузері, він бачить некоректне відображення посилання в повідомленнях типу "Заявка на участь в аукціоні"

**Кроки:**
1. Відкрити вікно "Приватного доступу" в браузері
2. Залогінитись на майданчик як Учасник 
3. Перейти Особистий кабінет
4. Перейти в Повідомлення > Мої повідомлення
5. Обрати розділ "Допуск до участі в аукціонах ФГВ/ФДМ"
6. Відкрити повідомлення типу "Заявка на участь в аукціоні"

**Очікуваний результат:**
1. Учасник бачить посилання у вагляді картинки

![f6109f98cd](https://cloud.githubusercontent.com/assets/13050207/24454539/e6a9d63e-1494-11e7-88c2-0a1c220dc371.jpg)

**Фактичний результат:**
1. Учасник бачить посилання у вагляді напису "Image"

![1](https://cloud.githubusercontent.com/assets/13050207/24454445/8d8e442c-1494-11e7-9b46-514fd80417c0.jpg)

**Comment by f3man** [comment]
виправлено

**Comment by SoftserveQC1** [comment]
Відтворюється в Mozilla Firefox

**Comment by SoftserveQC1** [comment]
Перевірено
