### ISSUE TITLE
Govfound: Відсутня можливість створити аукціон з тих які вже були оголошені

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1224]
Повинна бути присутня опція творення нового аукціону на основі того який вже був оголошений

Відтворення:
1. Залогінитись як замовник 
2. Зайти у чернетки
3. Зайти на останній аукціон

Очікувано: присутня опція створення нового аукціону на основі відваданого

Фактично: відсутня опція створення нового аукціону на основі відваданого

**Comment by oleg4646** [comment]
Надо зайти на аукцион, который надо скопировать. Нажать кнопку "Копировать" http://prntscr.com/eqa61t

**Comment by SoftserveQC1** [comment]
Я його то можу скопіювати, а оголосити з тими самими даними -НІ, він то скопійований, а далі я зним нічого зробити не можу, 
Повинна бути опція у чернетці, яка дозволяє оголосити на основі пепереднього незалежно від фінального статусу, або ж при оголошенні нових - опція оголосити з чернеток, при натисканні на яку, ми обираємо аукціон з тих які вже пройшли
Ця опція існує для того, щоб не вписувати ті самі дані ще раз

**Comment by OSerhii** [comment]
Колеги, не розумію з чим у вас виникла проблема... На даний момент все реалізовано коректно. Користувач може перейти на сторінку відображення свого аукціону => на цій сторінці зробити копію => тут же перейти на сторінку редагування аукціону, де внести необхідні зміни (як мінімум дати) і опублікувати.  

Якщо я правильно вас зрозумів, ви хочете щоби була можливість опублікувати абсолютну копію без жодної зміни. Наведіть будь ласка хоч один юз кейс, коли може бути потрібно створювати абсолютні клони аукціонів.

**Comment by SoftserveQC1** [comment]
На даному майданчику ця опція по іншому реалізована, закриваю
