### ISSUE TITLE
Smart: Помилка при спробі перегляду/завантаження документів по аукціону неавторизованим користувачем

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1225]
майданчик: http://test.smarttender.biz
передумова: мати посилання на аукціон
аукціон: http://test.smarttender.biz/government/details/754154

**Опис:** Неавторизований користувач не може переглянути/завантажити документи по аукціону. Він бачить помилку при спробі зробити одну з вказаних дій

**Кроки:**
1. Зайти на майданчик (не авторизовуватись)
2. Перейти на веб-сторінку аукціону за відповідним посиланням
3. Відкрити документи аукціону:

![9d4b4024bc](https://cloud.githubusercontent.com/assets/13050207/24457226/4203c07c-149e-11e7-9250-72e54212a756.jpg)

4. Спробувати завантажити документи
5. Спробувати відкрити документи

![2](https://cloud.githubusercontent.com/assets/13050207/24457293/6e835d92-149e-11e7-8ef4-7185464a5fed.jpg)

**Очікуваний результат:**
1. Неавторизований користувач може переглянути документи по аукціону
2. Неавторизований користувач може завантажити документи по аукціону

**Фактичний результат:**
1. Неавторизований користувач не може переглянути документи по аукціону
2. Неавторизований користувач не може завантажити документи по аукціону
3. Користувач бачить наступну помилку:
![c78e7154a6](https://cloud.githubusercontent.com/assets/13050207/24457613/7462dba6-149f-11e7-939c-5e434190832a.jpg)

**Comment by f3man** [comment]
прийнято, досліджуємо 
по завершенню відпишемось

**Comment by f3man** [comment]
питання вирішено
