### ISSUE TITLE
Smart: Не працюють посилання на аукціони з кабінету Замовника (за № аукціону)

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1226]
майданчик: http://test.smarttender.biz
користувач: PPR_TEST_FGI
передумова: мати опубліковані аукціони

**Опис:** Замовник не може переглянути веб-сторінку аукціону за посиланням зі стовбчику "№ аукціону"

**Кроки:**

1. Залогінитись на майданчик як Замовник.
2. Переглянути веб-сторінку аукціону за посиланням зі стовбчику "№ аукціону"
![088014a9bb](https://cloud.githubusercontent.com/assets/13050207/24458006/67ee73d4-14a0-11e7-9d63-1886ffb3a2a2.jpg)

**Очікуваний результат:**
1. Посилання веде на веб-сторінку відповідного аукціону 

**Фактичний результат:**
1. Користувач бачить наступну помилку:
![bccd0d6b11](https://cloud.githubusercontent.com/assets/13050207/24457949/47372a50-14a0-11e7-8654-0462049583b7.jpg)

**Comment by f3man** [comment]
прийнято, досліджуємо 
по завершенню відпишемось

**Comment by f3man** [comment]
питання вирішено
