### ISSUE TITLE
Govfound: Лишня опція для вибору типу аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1228]
Відтворення:
1. Як замовник натиснути кнопку свторити аукціон 
2. Натиснути на випадаючий список "Оголошення аукціону з продажу"

Очікувано: присутні лише дві опції "права та вимоги" та "майно замовника"

Фактично: присутня лишня незрозуміла опція 

![9](https://cloud.githubusercontent.com/assets/13050207/24495991/adbb6972-153f-11e7-8267-ae18969e25d2.png)

**Comment by oleg4646** [comment]
Это не лишняя опция. Это процедура для ЦБД2. Переименовали её в  Оголошення аукціону з продажу "Майна замовника"

**Comment by SoftserveQC1** [comment]
Цитую:
Можливість заводити лоти в ЦБД-1 (Майно і кредити банків, база Фонду гарантування) має бути виключно у ролі - Ліквідатор (Банк). Відповідно, якщо у них зареєстрований Замовник, який не є ліквідатором, в нього не має бути можливості завести лоти не в своїй базі. Це критично. Якщо в базу Фонду гарантування потраплять "чужі" лоти, будуть проблеми

**Comment by IllyaPetrusenko** [comment]
FIXED. Теперь при регистрации есть возможность выбрать НЕ банк. Для этого выбираем "Банк\Ликвидатор" и после чего появляется выпадайка с типом "Банк" и "другое" . Теперь чужие лоты не попадут в базу ЦБД-1

**Comment by IllyaPetrusenko** [comment]
Закройте дефект, пожалуйста
