### ISSUE TITLE
Govfound: Опція "Майно замовника" має назву "Майно банків"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1229]
Відтворення:
1. Як замовник натиснути кнопку свторити аукціон
2. Натиснути на випадаючий список "Оголошення аукціону з продажу"

Очікувано: Присутня опція, яка стосується майна має назву "Майно замовника"

Фактично: Присутня опція, яка стосується майна має назву "Майно банків"

![10](https://cloud.githubusercontent.com/assets/13050207/24496144/1a3d95ca-1540-11e7-802d-8d67053025e0.png)

**Comment by oleg4646** [comment]
Это не касается функционала.

**Comment by SoftserveQC1** [comment]
Це не актуальна назва, вона стосується іншого проекту, є вимога вживати коректну назву для Prozzoro .Sale 2.0 і це НЕ "банк", а "ЗАМОВНИК", тому аргумент "це не стосується функціонала" - не є аргументом розглядати це як не баг, це важлива вимога мати актуальну назву
https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#

**Comment by oleg4646** [comment]
Первые 2 пункта смотрят в ЦБД №1 и реализуют соответственно процедуры dgfOtherAssets и dgfFinancialAssets
Третий пункт "Майно замовника" смотрит в ЦБД №2 и реализует процедуру dgfOtherAssets

**Comment by OSerhii** [comment]
Пофіксили, прошу закрити дефект.

**Comment by SoftserveQC1** [comment]
які з цих опцій заносить дані в ЦБД 2?

**Comment by IllyaPetrusenko** [comment]
Третий пункт "Майно замовника" смотрит в ЦБД №2 и реализует процедуру dgfOtherAssets

**Comment by SoftserveQC1** [comment]
Цитую:
Можливість заводити лоти в ЦБД-1 (Майно і кредити банків, база Фонду гарантування) має бути виключно у ролі - Ліквідатор (Банк). Відповідно, якщо у них зареєстрований Замовник, який не є ліквідатором, в нього не має бути можливості завести лоти не в своїй базі. Це критично. Якщо в базу Фонду гарантування потраплять "чужі" лоти, будуть проблеми

**Comment by IllyaPetrusenko** [comment]
исправлено по задаче №1228. Закройте дефект.
