### ISSUE TITLE
OpenTender: Переможець аукціону не має можливості прикріпити Протокол торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1232]
http://test-eauction.open-tender.com.ua/seller/tender/award/153

**Опис:** Переможець аукціону не має можливості прикріпити Протокол торгів, ані в тілі аукціону, ані в розділі аукціону "Таблиця кваліфікаціЇ"

**Передумова:**
- Залогінитись як Замовник chekount@gmail.com
- Натиснути кнопку "Створити аукціон"
- Заповнити усі поля валідними даними та опублікувати аукціон
- Залогінитись як Учасник checkdto1@gmail.com
- Зробити ставку та підтвердити ії у Адміна
- Внести гарантійний внесок (відповідна кнопка у тілі аікціону)
- Залогінитись як Учасник checkdto2@gmail.com
- Зробити ставку та підтвердити ії у Адміна
- Внести гарантійний внесок (відповідна кнопка у тілі аікціону)
- Повторити кроки ще для двох учасників
- Дочекатися завершення аукціону, початку кваліфікації

**Відтворення:**
1) Залогінитись як Переможець
2) Перейти до аукціону 
3) У правому сайдбарі натиснути "Таблиця кваліфікаціЇ"
4) Переглянути сторінку кваліфікації

**Очікуваний рузультат:** У розділі лоту Кваліфікація з'являється кнопка "Завантажити протокол" та кнопка "Підтвердити протокол", після завантаження протоколу та натискання кнопки "Підтвердити" протокол відправляється до ЦБД

**Фактичний результат:** Відсутня можливість додати "протокол торгів" переможцем
![default](https://cloud.githubusercontent.com/assets/13050207/24545657/a7d37686-1610-11e7-84d3-097cb006e7a2.png)

**Comment by IllyaPetrusenko** [comment]
fixed. Закройте дефект, пожалуйста.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
