### ISSUE TITLE
Govfound: Некоректно проставленні назви при реєстреції замовника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1234]
Відтворення: 
1. Нажати на кнопку "Зареєструватись"
2. Глянути на спадний список "**Реєстрацiя як**" 

Очікувано: замість слова "Банк" присутнє слово "Замовник", опція вибору виглядає як "Замовник/Ліквідатор"

Фактично: Банк/Ліквідатор - стосується однієї сторони, точніше Ліквідатор є уповноваженою особою від банку 

![14 -](https://cloud.githubusercontent.com/assets/13050207/24546880/e42b0d88-1615-11e7-84f7-e8bdfc6666c8.png)

**Comment by IllyaPetrusenko** [comment]
Готово. Прошу закрыть дефект
