### ISSUE TITLE
Govfound: Опція "Інше" повинна бути замінена на "Замовник" при вибору реєстрації типу  

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1235]
Відтворення:

1. Нажати на кнопку "Зареєструватись"
2. Глянути на спадний список "тип"

Очікувано: замість слова "інше" присутнє слово "Замовник"

Фактично: присутня опція "інше", яка не дає достовірної інформації користувачу

![14 -](https://cloud.githubusercontent.com/assets/13050207/24546982/61bf1564-1616-11e7-96c6-03b1bd99f72a.png)

**Comment by IllyaPetrusenko** [comment]
Fixed
