### ISSUE TITLE
OpenTender: У листі Переможцю аукціону відсутня інформація про необхідніть прикріпити Протокол торгів протягом 3х діб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1237]
http://test-eauction.open-tender.com.ua

**Опис:** У листі Переможцю відсутня інформація про необхідніть прикріпити Протокол торгів протягом 3х діб та у тексті та заголовку листа відсутня інформація про те що учасник є переможцем, факт перемоги не є очевидним

**Передумова:**
- Залогінитись як Замовник chekount@gmail.com
- Натиснути кнопку "Створити аукціон"
- Заповнити усі поля валідними даними та опублікувати аукціон
- Залогінитись як Учасник checkdto1@gmail.com
- Зробити ставку та підтвердити ії у Адміна
- Внести гарантійний внесок (відповідна кнопка у тілі аікціону)
- Залогінитись як Учасник checkdto2@gmail.com
- Зробити ставку та підтвердити ії у Адміна
- Внести гарантійний внесок (відповідна кнопка у тілі аікціону)
- Дочекатися завершення аукціону, початку кваліфікації

**Відтворення:**
1) Залогінитись як Переможець
2) Перевірити Особистий кабінет "Повідомлення" 
3) Перевірити на пошті лист "Зміна статусу кваліфікації за аукціоном......"

**Очікуваний результат:**
Згідно [ручних тестів](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#) Рівень - Учасник, кейс 9 
1. Учасник в особистому кабінеті отримує повідомлення **про визнання Учасника переможцем і необхідність підписати Протокол на протязі трьох діб.**
2. Учасник електронною поштою отримує повідомлення **про визнання Учасника переможцем і необхідність підписати Протокол на протязі трьох діб.** 

**Фактичний результат:**
1. Неочевидним є той факт що учасника визнано переможцем
2. Відсутня інформація про необхідність підписати "Протокол торгів" протягом трьох діб
![win](https://cloud.githubusercontent.com/assets/13050207/24606343/711ef702-1875-11e7-85f8-fd9ebaeb2674.png)

**Comment by IllyaPetrusenko** [comment]
fixed. Закройте дефект, пожалуйста

**Comment by SoftserveQC1** [comment]
Все ще відтворюється UA-PS-2017-04-10-000006
![win](https://cloud.githubusercontent.com/assets/13050207/24902622/675a7a86-1eb3-11e7-8d40-4fae3c4b8f82.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено http://eauction.byustudio.in.ua/
![default](https://user-images.githubusercontent.com/13050207/27687195-89bb05f0-5cde-11e7-899a-bb948012c941.png)
