### ISSUE TITLE
Govfound: Відсутній пробіл між словами на сторінці аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1238]
Відсутній пробіл між словами на сторінці аукціону, в останній фразі (знизу) 

Відтворення:
1. Оголосити торги 
2. В якості участника подати заявку, та дочекатись періоду аукціону
3. Звернути увагу на останню фразу

Очікувано: всі слова розділені пробілом

Фактично: між словом "аукціон" та назвою аукціону відсутній пробіл

![15](https://cloud.githubusercontent.com/assets/13050207/24608164/125481ac-187e-11e7-9164-2b61fc5da97a.png)

**Comment by OSerhii** [comment]
Виправлено, прошу закрити дефект.
