### ISSUE TITLE
При переході тендера зі статусу "Період уточнень" у статус "Очікування пропозицій", відповіді на питання в учасників - зникають

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#124]
Зображення нище показує тентери учасника та замовника на стадії "Період уточнень"

![tender_waiting](https://cloud.githubusercontent.com/assets/11062040/6333129/480c88c0-bb93-11e4-9028-6ac4f77b394a.png)

Нище показано тентери учасника та замовника у статусі "Очікування пропозицій"

![tender_checkin](https://cloud.githubusercontent.com/assets/11062040/6333133/4faf9d38-bb93-11e4-829e-675bdb4dc239.png)

Актуально для Сhrome, Firefox, IE та Opera бравзерів.

**Comment by S-Shevchenko** [comment]
Спасибо. Изменения выйдут в  ближайшем билде.

**Comment by OksanaPakholok** [comment]
03/12/2015, http://services.e-tender.biz:100/#/ Перевірено. Не репродюситься.
