### ISSUE TITLE
Замовник не отримує нагадування про запитання/вимоги без відповіді

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1241]
Валідно у випадку ненадання протягом 24 годин Замовником відповіді на запитання до Лоту.
Про цей дефект було проінформовано контактну особу майданчика (illia_petrusenko) - і була отримана відповідь, що на даний момент даний функціонал не є реалізованим.

**Comment by IllyaPetrusenko** [comment]
Готово. Прошу закрыть дефект
