### ISSUE TITLE
OpenTender: Неймінг полів при створенні/перегляді аукціону не відповідає новим вимогам

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1244]
http://test-eauction.open-tender.com.ua/buyer/tender/create

**Опис:** Неймінг полів лишився такий самий як на Prozorro.Sale
- Загальний опис аукціону --> Загальний опис **процедури**
- Номер лоту за ФГВ--> **Номер лоту в Замовника**
- Рішення виконавчої дирекції ФГВФО....--> **Поля для рішення замовника**
- Стислий опис активу та забезпечення--> **Стислий опис активу**

**Відтворення:**
1) Залогінитись як Замовник checkdto@gmail.com
2) Натиснути кнопку "Створити аукціон"
3) Переглянути перелічені в описі поля

**Очікуваний результат:** Неймінг полів відповідає [вимогам](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.ph8fpaozr3jk)

**Фактичний результат:** Неймінг полів не відповідає [вимогам](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.ph8fpaozr3jk) стр.6 п.1 Створення Лоту - дії користувача
![1](https://cloud.githubusercontent.com/assets/13050207/24696973/1f9ae4ba-19f4-11e7-9cad-2e82251ee5bc.png)
![2](https://cloud.githubusercontent.com/assets/13050207/24696975/1fb480a0-19f4-11e7-9f15-34310b2eeb4c.png)

**Comment by IllyaPetrusenko** [comment]
Готово. Прошу закрыть дефект

**Comment by SoftserveQC1** [comment]
Дефект виправлено для полів при створенні ауцкіону
![1](https://cloud.githubusercontent.com/assets/13050207/24855153/5f93203e-1de9-11e7-9272-4962c8b1eb52.png)
![2](https://cloud.githubusercontent.com/assets/13050207/24855154/5f93aec8-1de9-11e7-8403-9e6ce36ee8d2.png)

**Comment by SoftserveQC1** [comment]
При перегляді створеного аукціону/чернетки з продажу майна Замовника досі відтворюється
приклад UA-PS-2017-04-10-000006 http://test-eauction.open-tender.com.ua/buyer/tender/view/949
![1](https://cloud.githubusercontent.com/assets/13050207/24855825/69995402-1deb-11e7-9fd1-e9d97a13c241.png)
![2](https://cloud.githubusercontent.com/assets/13050207/24855824/699843d2-1deb-11e7-8b1e-756758b2841e.png)

**Comment by IllyaPetrusenko** [comment]
Исправлено. Прошу закрыть дефект.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
