### ISSUE TITLE
OpenTender: При створенні лоту перелік доступних до завантаження документів не повний

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1245]
http://test-eauction.open-tender.com.ua/buyer/tender/create

**Опис:** Створюючи аукціон Замовник не має можливості додати документи категорії "Кваліфікаційні вимоги замовника", "Типовий договір" та "Інші документи", натомість у переліку доступних до завантаження документів є зайві "Паспорт торгів", "Публічний паспорт активу", "Договір NDA" та посилання на Публічний паспорт активу.

**Відтворення:**
1) Залогінитись як Замовник checkdto@gmail.com
2) Натиснути кнопку "Створити аукціон"
3) Натиснути на поле "Документація до лоту"
4) Натиснути на поле "Додати файл документації"
5) Додати файл (наприклад .png не більше 1мб)
6) Натиснути на дропбпокс "Тип документа"

**Очікуваний результат:** Замовник має можливість додати документи категорії **_"Кваліфікаційні вимоги замовника", "Типовий договір" та "Інші документи"_** згідно [вимогам](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.beiwod5g2jrq) стр.6 п.1 Створення Лоту - дії користувача

**Фактичний результат:** Замовник не може додати документи категорії **_"Кваліфікаційні вимоги замовника", "Типовий договір" та "Інші документи"_**, бо вони відсутні. Натомість присутні зайві до завантаження категорії документів "Паспорт торгів", "Публічний паспорт активу", "Договір NDA" та посилання на Публічний паспорт активу.
![1](https://cloud.githubusercontent.com/assets/13050207/24697253/217273f6-19f5-11e7-83aa-8bbe2a501039.png)
![2](https://cloud.githubusercontent.com/assets/13050207/24697252/21721b7c-19f5-11e7-833c-5d5ec04befeb.png)

**Comment by IllyaPetrusenko** [comment]
Готово. Прошу закрыть дефект

**Comment by SoftserveQC1** [comment]
Документи категорії "Кваліфікаційні вимоги замовника" та "Типовий договір" додано
**все ще відсутні категорія "Інші документи"**
все ще присутні зайві документи "Паспорт торгів", "Публічний паспорт активу", "Договір NDA" та посилання на Публічний паспорт активу також з'явився документ "Пояснення до запитань учасників"
![default](https://cloud.githubusercontent.com/assets/13050207/24854959/c7fe8ace-1de8-11e7-8b02-54343959d463.png)

**Comment by SoftserveQC1** [comment]
Згідно з новими роз'ясненнями у обов'язковий перелік документів входять
- Завантаження ілюстрації лоту аукціону
- Кваліфікаційні вимоги замовника (може бути набір документів) 
- Завантаження Презентації
- Типовий договір.

Усі інші докумети на відповідальності майданчика, тому дефект закрито
