### ISSUE TITLE
25h8auction: Дублювання повідомлення про відсутність прав доступу для створення аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1246]
Відтворення:
1. Зареєструвати юзера
2. Підтвердити реєстарція
3. На порталі нажаті кнопку "Створити аукціон"

Очікувано: Відсутнє дублювання інформації

Фактично: Присутнє дублювання інформації

![default](https://cloud.githubusercontent.com/assets/13050207/24753752/371e16aa-1adc-11e7-8700-9f040f8e62fb.png)

**Comment by OSerhii** [comment]
Виправлено, прошу закрити дефект.
