### ISSUE TITLE
25h8auction: Відсутня кнопка "Подати пропозицію" для участника, щоб взяти участь у аукціоні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1247]
Відтворення:
1. Оголосити торги _як замовник_
2. В _якості участника_ перейти на сторінку торгів та спробувати подати цінову пропозицію (щоб взяти участь у торгах)

Очікувано: для участника є кнопка(функція) яка дозволяє йому подати свою цінову пропозицію, та взяти участь у торгах

Фактично: функція подачі цінової пропозиції відсутня, участник не може взяти участь у аукціоні

![3](https://cloud.githubusercontent.com/assets/13050207/24757330/913d898a-1ae7-11e7-80c1-874754a20d12.png)
![3](https://cloud.githubusercontent.com/assets/13050207/24792066/319582aa-1b85-11e7-8403-22a4cd8e707f.png)

**Comment by IllyaPetrusenko** [comment]
Не воспроизводится. Прошу закрыть дефект
