### ISSUE TITLE
E-auction: При реєстрації замість типу учасника Замовник є тип учасника Ліквідатор

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1249]
http://uatasset.e-auction.ua

**Передумова:**
- Перейти на майданчик
- У головному меню натиснути реєстрація
- Заповнити поля форми реєстрація валідними даними та відправити заявку
- Звернутися до адміна за валідацію користувача

**Відтворення:**
1) Після вілідації залогінитися користувачем
2) У Кабінеті перейти у розділ "Дані організації"
3) Натиснути на дропбокс "Фізична/юридична особа"

**Очікуваний результат:** Користувач може вибрати тип Учасника з:
- **Замовник**
- Юридична особа
- Фінансова компанія
- ФОП
- Фізична особа

**Фактичний результат:** Замість типу Учасника "Замовник" присутній тип "Ліквідатор"
![default](https://cloud.githubusercontent.com/assets/13050207/24792874/7451b516-1b88-11e7-8a32-4e6049e6f0c9.png)

**Comment by OlegNekovalev** [comment]
Исправили
![screenshot_9](https://cloud.githubusercontent.com/assets/23699721/24914811/08fa6408-1ede-11e7-9742-562ad0e42ddc.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
