### ISSUE TITLE
E-auction: Спроба завантажити документи у Особистому кабінеті, до аукціону Замовником, до ставки Учасником призводить до помилки

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1250]
http://uatasset.e-auction.ua

**Опис:** При спробі завантажити докумети 
- Користувачами у особистому кабінеті до профілю
- Замовником до аукціону/чернетки
- Учасниками до своєї ставки по акціону

З'являється нотифікація про еррор, документи не додаються

**Передумова:**
- Залогінитися як Замовник (derZamovnik)
- Створити аукціон (Кабінет->Мої торги->Створит оголошення з продажу активу)
- Заповнити всі поля валідними даними та опублікувати

**Відтвореня:**
1) Зайти користувачем у Кабінет->Дані організації
2) Клікнути на чекбокс "Я хочу довантажити документи....."
3) Натиснути кнопку "Завантажити" та обрати файл (.png < 1мб)

або
1) Перейти до раніше створеного аукціону
2) У тілі аукціону натисиснути кнопку "Browse..." розділу Документи торгів та обрати файл

або
1) Залогінитися як Учасник (derYurik)
2) Перейти до аукціону на стадіїї "Очікування пропозицій"
3) Зробити ставку не менше початкової вартості та натиснути "Реєстрація пропозиції"
4) Натисиснути кнопку "Browse..." під ставкою та обрати файл

**Очікуваний результат:** Документи успішно завантажуються

**Фактичний результат:**  Документи не завантажуються, з'являється нотифікація з ерором
![1](https://cloud.githubusercontent.com/assets/13050207/24793928/7dc6ddde-1b8c-11e7-8676-6d6aa834fed3.png)
![2](https://cloud.githubusercontent.com/assets/13050207/24793927/7dc1a666-1b8c-11e7-9112-96bffa07f79f.png)

**Comment by SoftserveQC1** [comment]
Дефект майже виправлено, можна прибрати статус "Критичний"
лишився кейс:
1) Учасник робить ставку до аукціону
2) Потім натискає кнопку "Choose file" під ставкою та обрає файл (тип документу у дропбоксі не обираємо)

**Очікувано:** Файл завантажується як дефолтни1 тип документу, або не завантажується і з'являється попап із повідомленням "Оберіть тип документу"

**Фактично:** Файл не завантажується, з'являється незрозумілий попап із помилкою
![default](https://cloud.githubusercontent.com/assets/13050207/24906736/a8e23ec2-1ec1-11e7-8755-2343923a2bb7.png)

**Comment by w-be** [comment]
Критичну частину виправили.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![1250](https://cloud.githubusercontent.com/assets/13050207/25123291/9727d2b8-2430-11e7-9cbb-224df4c39d6f.png)
