### ISSUE TITLE
E-auction: При створенні лоту перелік доступних до завантаження документів не повний

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1254]
http://uatasset.e-auction.ua

**Опис:** Створюючи аукціон Замовник не має можливості додати документи категорії "Кваліфікаційні вимоги замовника" та "Типовий договір", натомість у переліку доступних до завантаження документів є зайві "Паспорт торгів", "Публічний паспорт активу", "Критерії оцінки", "Пояснення до запитань заданих учасниками" та "Інформація про учасників".

**Відтворення:**
1) Залогінитись як Замовник (derZamovnik)
2) Створити аукціон (Кабінет->Мої торги->Створит оголошення з продажу активу->Майно...)
3) Заповнити всі поля валідними даними
4) Опублікувати аукціон
5) У тілі аукціону натисиснути дропбокс "Оберіть тип для завантажуємого документа"

**Очікуваний результат:** Замовник має можливість додати документи категорії **_"Кваліфікаційні вимоги замовника", "Типовий договір" та "Інші документи"_** згідно [вимогам](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.beiwod5g2jrq) стр.6 п.1 Створення Лоту - дії користувача

**Фактичний результат:** Замовник не може додати документи категорії **_"Кваліфікаційні вимоги замовника" та "Типовий договір", бо вони відсутні. Натомість присутні зайві до завантаження категорії документів "Паспорт торгів", "Публічний паспорт активу", "Критерії оцінки", "Пояснення до запитань заданих учасниками" та "Інформація про учасників".
![default](https://cloud.githubusercontent.com/assets/13050207/24796243/e3664b18-1b94-11e7-8774-c82725249c19.png)

**Comment by OlegNekovalev** [comment]
Исправили
"Натомість присутні зайві до завантаження категорії документів "Паспорт торгів", "Публічний паспорт активу", "Критерії оцінки", "Пояснення до запитань заданих учасниками" та "Інформація про учасників". - це не зайві
![screenshot_12](https://cloud.githubusercontent.com/assets/23699721/24954791/7b5ed85c-1f89-11e7-80e0-0dc81e203f9b.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
