### ISSUE TITLE
E-auction: Неймінг полів при створенні/перегляді аукціону не відповідає новим вимогам

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1255]
http://uatasset.e-auction.ua

**Опис:** Неймінг полів не відповідає вимогам ручних тестів:
- Загальний опис процедури --> **Загальна назва процедури**
- Загальний опис аукціону --> **Загальний опис процедури** (description)
- Номер лоту в ФГВ--> **Номер лоту в Замовника**
- Номер рішення в ФГВ--> **Номер рішення в Замовника**
- Дата прийняття рішення в ФГВ--> **Дата прийняття рішення в Замовника**
- Код відповідного класифікатору лоту: CPV--> Код відповідного класифікатору лоту: **CAV**

**Відтворення:**
1) Залогінитись як Замовник (derZamovnik)
2) Створити аукціон (Кабінет->Мої торги->Створит оголошення з продажу активу->Майно...)
3) Оглянути назви полів аукціону
4) Заповнити всі поля валідними даними та опублікувати аукціон
5) Переглянути аукціон після публікації

**Очікуваний результат:** Неймінг полів відповідає [вимогам](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.ph8fpaozr3jk)

**Фактичний результат:** Неймінг полів не відповідає [вимогам](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.ph8fpaozr3jk) стр.6 п.1 Створення Лоту - дії користувача
1) Назва має бути "Оголошення аукціону з продажу"
![default](https://cloud.githubusercontent.com/assets/13050207/24796742/efe827b0-1b96-11e7-87cc-29fbf489b5c4.png)
2) Поля ФГВ у тілі лоту при створенні
![1](https://cloud.githubusercontent.com/assets/13050207/24796744/f004eaa8-1b96-11e7-87e8-8a97fee68c6c.png)
3) Поле про рішення ФГВФО при перегляді створеного лоту
![2](https://cloud.githubusercontent.com/assets/13050207/24796743/f002da1a-1b96-11e7-904d-bede8ef55caf.png)

**Comment by OlegNekovalev** [comment]
Исправили
![screenshot_10](https://cloud.githubusercontent.com/assets/23699721/24946224/e74aee8a-1f6a-11e7-82c2-076500410f9e.png)
![screenshot_11](https://cloud.githubusercontent.com/assets/23699721/24946226/e865f13e-1f6a-11e7-9dc6-f29fd58f412b.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
