### ISSUE TITLE
25h8auction: При виборі контактної особи під час створення нового лоту не підтягується інформація про неї у поля

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1258]
Відтворення:
1. Стоворити новий лот
2. Заповнити всі поля
3. При виборі контактної особи, звернути увагу на те що поля, які містять інформацію про неї не заповнюються

![7](https://cloud.githubusercontent.com/assets/13050207/24799030/d0d4253a-1ba1-11e7-945e-dffa953ead81.png)

**Comment by IllyaPetrusenko** [comment]
Залилась новая версия. Необходимо нажать Ctrl+ F5
