### ISSUE TITLE
25h8auction: Після натискання кнопки "Зберегти та перейти до публікації" вибиває помилку, якщо вибрати поточну дату

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1259]
**Важливо: баг відтворються якшо вибрати поточну(сьогоднішню) дату**

Відтворення:
1. Створити новий аукціон або перейти до чернеток
2. Заповнити всі поля
3. Нажати кнопку "Зберегти та перейти до публікації"

Очікувано: нотицікація про оголошення, яке відбудеться протягом певного часу

Фактично: помилка

![8](https://cloud.githubusercontent.com/assets/13050207/24801476/0b3059dc-1bad-11e7-92db-9217dfb5f756.png)

**Comment by IllyaPetrusenko** [comment]
fixed. Прошу закрыть багу

**Comment by IllyaPetrusenko** [comment]
Выполнено.
