### ISSUE TITLE
При створенні тендера, при внесенні в поле "Кількість" 10 значного числа, на подальших скрінах, кількість відображується нулем

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#126]
![10_digits](https://cloud.githubusercontent.com/assets/11062040/6350759/600ecd78-bc3f-11e4-9aa6-5879788bf5c1.png)

Питання актуальне у Chrome, Firefox, IE та Opera бравзерах

**Comment by S-Shevchenko** [comment]
Исправлено. Можно закрывать.
