### ISSUE TITLE
Govfound: Зайва опція в спадному списку "Оголошення аукціону з продажу" на сторінці з торгами

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1260]
Відтворення:
1. Зайти на сторінку списку торгів
2. Нажати на спадний список "Оголошення аукціону з продажу" 

Фактично: присутня лишня опція

Очікувано: відсутні лишні опції незрозумілі для користувача

![17](https://cloud.githubusercontent.com/assets/13050207/24855379/24193f7e-1dea-11e7-85c1-72d1a51f4e05.png)

**Comment by IllyaPetrusenko** [comment]
Готово. Закройте дефект.
