### ISSUE TITLE
25h8auction: Не видно ссилку "перебіг аукціону", поки користувач не наведе на неї курсор

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1261]
Відтворення:
1. Оголосити торги з двома участниками
2. Дочекатись підтвердження пропозицій, та появи ссилок в низу сторінки

Фактично: не видно ссилки для переходу в етап аукіону

Очікувано: ссилка для переходу на етап аукціону є видима завжди

![9](https://cloud.githubusercontent.com/assets/13050207/24863040/ecd345b4-1e07-11e7-82fa-fee44970dfd7.png)
![9](https://cloud.githubusercontent.com/assets/13050207/24863039/ecd2ea06-1e07-11e7-99ec-8ee1f217483d.png)

**Comment by IllyaPetrusenko** [comment]
fixed. Прошу закрыть дефект.
