### ISSUE TITLE
25h8auction: Невідповідність даних про користувача полям в яких вони відображаються

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1262]
В прикладі на скріншоті, "львів" варто перенести в поле "Місто" добавивши кому після назви області

Відтворення:
1. Провести успішні торги з двома участниками
2. Зайти на пошту участників та глянути повідомлення про завершеення етапу аукціону

Фактично: деякі поля не відповідають своїм потенційним значенням

Очікувано: назва міста відображається в полі місто

![11](https://cloud.githubusercontent.com/assets/13050207/24866401/aa93fe4a-1e12-11e7-8866-e44acb299ec0.png)

**Comment by OSerhii** [comment]
Виправлено, прошу закрити дефект.

**Comment by SoftserveQC1** [comment]
Бага не актуальна, у зв'язку зі змінами в авардінгу та відповідно змінами повідомлень.
Коментар від illia_petrusenko
