### ISSUE TITLE
25h8auction: Різні розміри і положення кнопок створюють незрозумілий інтерфейс під час етапу кваліфікації

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1263]
Відтворення:
1. провести успішні торги з двома участниками
2. звернути увагу на інтерфейс сторінки під час етапу кваліфікації

Фактично: кнопки розкидані і мають різні розміри (вводить користувача в запутаність)

Очікувано: кнопки одного розміру, та вирявняні відносно одна одної або інших елементів та впорядковано розміщені (щоб користувач візуально легко сприймав можливі подальші опції)

![15](https://cloud.githubusercontent.com/assets/13050207/24907065/383efec4-1ec3-11e7-8b1e-553e78666526.png)

**Comment by OSerhii** [comment]
Виправлено, прошу закрити дефект.

**Comment by SoftserveQC1** [comment]
![image](https://user-images.githubusercontent.com/13050207/35265838-fd8119b8-0029-11e8-8956-17556009f05a.png)
Кнопки змінені та вирівняні.
