### ISSUE TITLE
25h8auction: У повідомленні яке приходить до поточного переможця після ставок відсутня інформація про те що потрібно завантажити протокол протягом трьох діб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1264]
Відтворення:
1. Провести успішні торги з двома участниками
2. дочекатись етапу коли потрібно завантажити протокол
3. НЕ ЗАВАНТАЖУВАТИ протокол для 1-го участника
4. дискваліфікувати 1-го участника
5. НЕ ЗАВАНТАЖУВАТИ протокол для 2-го участника
6 перевірити пошту участників

Фактично: В листі яке прийшло участникам немає інформації про те що їм необхідно завантажити протокол протягом 3 діб

Очікувано: В листі яке прийшло участникам є інформації про те що їм необхідно завантажити протокол протягом 3 діб

![17 3](https://cloud.githubusercontent.com/assets/13050207/24911833/fd6ca28a-1ed4-11e7-8870-f8d8854f2f63.png)
![17 3](https://cloud.githubusercontent.com/assets/13050207/24911834/fd6cd2fa-1ed4-11e7-951c-45f63a814cf3.png)

**Comment by IllyaPetrusenko** [comment]
Fixed.
