### ISSUE TITLE
25h8auction: В повідомлені яке приходить 2-му участнику немає інформації про те що він може не забирати свій гарантіний внесок протягом 11-15 діб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1265]
Відтворення:
1. Провести успішні торги з двома участниками
2. Відкрити повідомлення яке приходить 2-ому участнику після зайняття ним 2-го місця

Фактично: відсутня інформація про те що він може не забирати свій гарантіний внесок протягом 11-15 діб

Очікувано: є інформація про те що він може не забирати свій гарантіний внесок протягом 11-15 діб

![16 11-15](https://cloud.githubusercontent.com/assets/13050207/24911953/591f4060-1ed5-11e7-91bc-5b1d6fd8fdff.png)

**Comment by IllyaPetrusenko** [comment]
Fixed
