### ISSUE TITLE
25h8auction: Відсутня кнопка, яка дозволяє забрати 2-му участнику свій гарантійний внесок після проведення ставок 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1266]
Відтворення:
1. Провести успішні торги з двома участниками
2. Участником який зайняв 2-ге місце перейти на сторінку кваліфікації переможців

Очікувано: присутня кнопка, яка дозволяє забрати свій гарантійний внесок

Фактично: відсутня кнопка, яка дозволяє забрати свій гарантійний внесок

![13](https://cloud.githubusercontent.com/assets/13050207/24912131/ea6092b8-1ed5-11e7-9acb-e995709e1658.png)

**Comment by IllyaPetrusenko** [comment]
Fixed.
