### ISSUE TITLE
UEEX: невирівняні елементи на сторінці торгів після етапу завантаження протоколу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1268]
Відтворення:
1. Провести успішний аукціон з двома участниками
2. Під час завантаження договору, завантажити ще кілька документів, різних опцій

Очікувано: елементи впорядковано розміщенні та вирівняні одне відносно одного

Фактично: елементи зміщені, незрозуміло яка інформація куди відноситься

![1](https://cloud.githubusercontent.com/assets/13050207/24959642/f9de60aa-1f9b-11e7-8708-c1b561964238.png)

**Comment by v-lego** [comment]
Провели перерозміщення
![default](https://user-images.githubusercontent.com/24773833/33995950-3b1fd4fa-e0e8-11e7-93ad-d8d042bdbb71.png)

**Comment by SoftserveQC1** [comment]
![image 6](https://user-images.githubusercontent.com/13050207/36736117-6b7b2266-1be0-11e8-919f-e4aa3a28d63f.png)
Пофікшено
