### ISSUE TITLE
E-auction: У тілі аукціону та у повідомленнях для Учасника який зайняв друге місце вказується, що можна не забирати гарантійний внесок протягом 15 діб замість 11-ти

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1270]
http://uatasset.e-auction.ua/

**Опис:**При перегляді сторінки аукціону та у повідомленнях на пошту та у особистому кабінеті для Учасника який зайняв друге місце вказується, що можна не забирати гарантійний внесок протягом 15 діб замість [регламентованих](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.1fap1z6or798) 11-ти

**Відтворення:**
1) Залогінитись Замовником (derZamovnik)
2) Створити та опублікувати аукціон майно Замовника
3) Зробити ставки трьома учасниками (derYurik, derFin, derFiz)
4) Провалідувати ставки адміном
5) Дочекатися початку кваліфікації
6) Перевірити пошту та "повідомлення" у особистому кабінеті Учасником який зайняв друге місце
7) Переглянути сторінку аукціону у розділі "Пропозиції"

**Очікуваний результат:** При пергляді у аукціоні своєї ставки до аукціону та у повідомленнях учаснику, що зайняв друге місце вказується, що можна не забирати гарантійний внесок протягом 11 діб

**Фактичний результат:** При пергляді у аукціоні своєї ставки до аукціону та у повідомленнях учаснику, що зайняв друге місце вказується, що можна не забирати гарантійний внесок протягом 15 діб.
![15](https://cloud.githubusercontent.com/assets/13050207/25006417/77d059e0-2065-11e7-91bc-807339c8aab6.png)
![2](https://cloud.githubusercontent.com/assets/13050207/25006422/7ba231c4-2065-11e7-87a4-8e1aa5b0c061.png)
![2 2](https://cloud.githubusercontent.com/assets/13050207/25006423/7bbee01c-2065-11e7-8dd4-38b51c3f09b2.png)

**Comment by SoftserveQC1** [comment]
Виправлено повідомлення у листі, повідомлення у тілі аукціону все ще відтворюється
![2](https://cloud.githubusercontent.com/assets/13050207/25334543/a182a190-28f7-11e7-9f75-7af5d65001bb.png)

**Comment by OlegNekovalev** [comment]
Исправили
![default](https://cloud.githubusercontent.com/assets/23699721/25336183/08ed6548-28ff-11e7-9776-3bd75755ac58.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
