### ISSUE TITLE
E-auction: При розміщенні ставки відсутня функціональність згоди із умовами Замовника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1272]
http://uatasset.e-auction.ua/

**Опис:** При розміщенні Учасником ставки по аукціону відсутня функціональність "Підтвердити згоду з умовами Замовника\З умовами Аукціону (оферта, чекбокс, будь-які інші варіанти)" яка має бути згідно [ручним тестам](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.b29moe9uvka). Дана функціональність важлива бо у кожного замовника мажуть бути свої вимоги. Основний сценарій такий: Учасник заходить на сторінку аукціону -- > на сторінці є документ з вимогами Замовника --> Учасник ознайомлюється з ним --> Якщо згоден - клікає чекбокс та робить ставку

**Відтворення:**
1) Залогінитись Учасником (derFiz)
2) Перейти до розділу головного меню "Торги"
3) Обрати аукціон типу "майно Замовника" у статусі "Очікування пропозицій"
4) У тілі аукціону проскролити до розділу "Пропозиції"

**Очікуваний результат:** Перед тим як зробити ставку Учасник має підтвердити згоду з умовами Замовника\З умовами Аукціону (оферта, чекбокс, будь-які інші варіанти)

**Фактичний результат:**  При розміщенні Учасником ставки по аукціону відсутня функціональність "Підтвердити згоду з умовами Замовника\З умовами Аукціону (оферта, чекбокс, будь-які інші варіанти)" яка має бути згідно [ручним тестам](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.b29moe9uvka)
![bid](https://cloud.githubusercontent.com/assets/13050207/25043232/069a0d58-2127-11e7-9f9e-f9c89d22e2a1.png)

**Comment by OlegNekovalev** [comment]
Исправили
![default](https://cloud.githubusercontent.com/assets/23699721/25277805/d42cf24a-26a8-11e7-891b-796f610abdae.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![default](https://cloud.githubusercontent.com/assets/13050207/25326200/d486db08-28d7-11e7-868e-b296abe70de7.png)
