### ISSUE TITLE
utsb: При оголошенні з чернеток при виборі поточної дати аукціон неможливо оголосити

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1274]
Можна оголосити лише вибравши завтрашню дату, при оголошенні сьогоднішньої дати з пізнишим часом - помилка

Відтворення:
1. Створити аукціон
2. Зберегти його та скопіювати
3. Зайти на скопійований аукціон та спробувати його оголосити вибравши сьогоднішню дату з пізнішим часом

Очікувано: аукціон успішно оголошений

Фактично: помилка оголошення повязана з датою

![2](https://cloud.githubusercontent.com/assets/13050207/25481308/3d79f1f2-2b55-11e7-9d80-0f61e38fa153.png)
![2](https://cloud.githubusercontent.com/assets/13050207/25481307/3d77a2bc-2b55-11e7-8b3c-5299b4cc2668.png)

**Comment by v-lego** [comment]
При створенні чернетки на пісочниці слід обов'язково вказувати мітку "Використання з прискоренням".
Інакше чернетка буде створена зі стандартними правилами щодо періодів.
![default](https://cloud.githubusercontent.com/assets/24773833/25515807/9a4e7b38-2bef-11e7-9fe9-933e484825da.png)
