### ISSUE TITLE
utsb: При свторенні лоту відсутня можливість завантаження документів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1275]
Відтворення:
1 оголосити новий аукціон
2 переглянути форму

Очікувано: присутня можливість завантажувати документи при створенні лоту

Фактично: можливість завантажувати документи присутня лише при редагуванні лоту

![3](https://cloud.githubusercontent.com/assets/13050207/25481378/91c487ae-2b55-11e7-9299-9bb8c60fd510.png)
![3](https://cloud.githubusercontent.com/assets/13050207/25481379/91c6d554-2b55-11e7-8d4d-b4f2cbdbcb3b.png)
![3](https://cloud.githubusercontent.com/assets/13050207/25481377/91c407e8-2b55-11e7-9fef-2b589f598f61.png)

**Comment by v-lego** [comment]
Документи можна додавати після збереження чернетки і отримання хоча б ідентифікатору чернетки.
Про це йде у повідомленні
![default](https://cloud.githubusercontent.com/assets/24773833/25515922/18d86eb4-2bf0-11e7-9dc6-ba6a70a9ad72.png)
