### ISSUE TITLE
utsb: Неможливо поповнити рахунок

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1277]
Відтворення:
1 Спробувати поповнити собі рахунок у особистому кабінеті

![5](https://cloud.githubusercontent.com/assets/13050207/25481921/1841beb2-2b58-11e7-9da6-2fdf1ff011a6.png)

**Comment by v-lego** [comment]
Можливість створення рахунку зі сторінки перегляду розрахунків прибрано.
Рахунок можна створити тільки з прив'язкою до конкретної пропозиції на сторінці пропозиції.
![default](https://cloud.githubusercontent.com/assets/24773833/25516062/f18a1258-2bf0-11e7-8cdd-54869220aad6.png)
