### ISSUE TITLE
utsb: При відміні лоту но сторінці списку лотів відображається неактуальна інформація

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1278]
Відтворення:
1 Оголосити торги
2 відмінити торги
3 повернутися до списку торгів та знайти відмінений

![6](https://cloud.githubusercontent.com/assets/13050207/25482870/3a89d992-2b5c-11e7-8c34-8de2a2516be1.png)

**Comment by v-lego** [comment]
Внесено зміни у відображення списку.
![default](https://cloud.githubusercontent.com/assets/24773833/25516396/18e28bc6-2bf3-11e7-92ce-c9d3189a3a9e.png)
