### ISSUE TITLE
utsb: Торги не переводяться на етап кваліфікації після проведення ставок

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1279]
Відтворення:
1 Провести торги 
2 Закінчивши етап аукціону, перейти на сторінку торгів

Очікувано: торги переходять в етап кваліфікації

Фактично: торги лишаються на етапі аукціону

![7](https://cloud.githubusercontent.com/assets/13050207/25486841/1058ff22-2b6b-11e7-8da0-5024e1632d57.png)
![7](https://cloud.githubusercontent.com/assets/13050207/25486839/104653f4-2b6b-11e7-90e5-b24e064815ff.png)
![7](https://cloud.githubusercontent.com/assets/13050207/25486840/1047d6b6-2b6b-11e7-8ac2-a25b7779ff8f.png)

**Comment by v-lego** [comment]
Просимо повторити тест
