### ISSUE TITLE
utsb: Не вирівняні елементи на сторінці під час і після етапу кваліфікації

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1280]
Інформація розкидана і не вирівняна що створює труднощі при читанні для користувача

Відтворення:
1 Провести успішні торги з 2-ома участниками, завантажити всі необхідні документи
2 переглянути сторінку аукціону після завершення всіх активностей

![8](https://cloud.githubusercontent.com/assets/13050207/25526600/f4f3e4d8-2c1c-11e7-95e6-4144db948d38.png)

**Comment by v-lego** [comment]
провели вирівнювання елементів
![default](https://cloud.githubusercontent.com/assets/24773833/25792826/b36134c8-33d1-11e7-8366-8da9d85482f4.png)
