### ISSUE TITLE
utsb: Неможливо замінити "договір" або додати інший тип документів нажавши кнопку "оновити" на етапі кваліфікації

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1281]
Завантажити кілька різних документів за допомогою кнопки "оновити" та "додати документ". Більшість спроб завантажити документи відображають невідповідну інформацію

Відтворення: 
1 Провести успішні торги 
2 Після завантаження договору нажати кнопку "оновити"
3 завантажити ще один документ під іншим типом

![10](https://cloud.githubusercontent.com/assets/13050207/25528490/c99531c0-2c26-11e7-8582-4c51e02ae7bb.png)
![10](https://cloud.githubusercontent.com/assets/13050207/25528489/c9923fd8-2c26-11e7-84e3-b282e51de49a.png)

**Comment by v-lego** [comment]
за отриманою консультацією: змінювати тип неможливо
можливість зміну типу прибрали.
