### ISSUE TITLE
utsb: Кнопка "зберегти договір" видає помилку

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1282]
Відтворення:
1 Провести успішні торги 
2 Після завантаження договору натиснути кнопку "зберегти договір"

![9 -](https://cloud.githubusercontent.com/assets/13050207/25528712/c63f3722-2c27-11e7-84c6-84db0d5309c2.png)

**Comment by v-lego** [comment]
внесли зміни шодо обробки пустого повідомлення від ЦБД при передачі повідомлення без зміни даних
