### ISSUE TITLE
utsb: Ліквідатор повинен сам вводити номер договору

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1283]
Відтворення
1 Провести успішні торги
2 Завантажити договір
3 Звернути увагу на поле "номер договору"

Очікувано: ліквідатор власноруч вводить номер підписаного договору

Фактично: номер договору визначається автоматично

![11](https://cloud.githubusercontent.com/assets/13050207/25529096/50a24764-2c29-11e7-8434-cb343e18ce03.png)

**Comment by v-lego** [comment]
встановлено можливість введення і відображення власного номера 
![default](https://cloud.githubusercontent.com/assets/24773833/25792908/247ac5ac-33d2-11e7-92a4-5de36083f0d1.png)
