### ISSUE TITLE
nkcentr: Поле "телефон" не є обов'язковим при реєстрації та у особистому кабінеті

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1284]
https://sale.nkc.biz.ua/test/

**Відтворення:**
1) Увійти на майданчик
2) Натиснути кнопку "Зареєструватися"
3) Заповнити поля усі обов'язкові поля та чекбокси крім поля "телефон"
4) Проскролити вниз та натиснути кнопку "Зареєструватися"
5) Перейти до Профілю->Користувач

**Очікуваний результат:** Поле "Телефон" є обов'язковими при реєстрації згідно [Ручних тестів](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#)

**Фактичний результат:** Поле Телефон не є обов'яковими
![1](https://cloud.githubusercontent.com/assets/13050207/25531862/d00828a2-2c33-11e7-97ca-bafbbe45aa44.png)
![2](https://cloud.githubusercontent.com/assets/13050207/25531861/d0019604-2c33-11e7-9235-ddc6add8d9ee.png)

**Comment by v-lego** [comment]
встановлено обов'язковість полів

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![1](https://cloud.githubusercontent.com/assets/13050207/25796532/7d2f4a46-33e2-11e7-906a-509fd269619b.png)
![2](https://cloud.githubusercontent.com/assets/13050207/25796531/7d282662-33e2-11e7-85be-e22bc68a38c7.png)
