### ISSUE TITLE
nkcentr: Список доступних до завантаження Ліквідатором документів має зайві

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1285]
https://sale.nkc.biz.ua/test/

**Відтворення:**
1) Увійти на майданчик під логіном nkc-likvidator@yopmail.com
2) Перейти до розділу "Аукціони"
3) Натиснути кнопку "Новий аукціон" 
4) Обрати тип "майна банків", проскролити вниз та натиснути "Додати актив" 
5) Заповнити поля валідними даними та зберегти аукціон
6) Проскролити вниз та натиснути "Додати документ"
7) У вікні "Завантажте документ", яке з'явилось, кликнути на випадаючий список "Тип документу"
8) Переглянути список можливих документів для завантаження

**Очікуваний результат:** перелік доступних до завантаження документів має відповідати затвердженним у [Ручних тестах](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.beiwod5g2jrq)

**Фактичний результат:** " можливо завантажити документи яких не має бути:
- Критерії оцінки
- Пояснення до питань заданих учасниками
- інформація про учасників
- Юридична інформація майданчиків (при додаванні відсутня можливість оновити або видалити!)
- Віртуальна кімната для роботи з конфіденційними даними
- Дві презентації
![default](https://cloud.githubusercontent.com/assets/13050207/25524583/ce17afc4-2c13-11e7-8ab5-9331fe3286eb.png)

**Comment by v-lego** [comment]
Прибрали лишні, 
але переіменували "Пояснення до питань заданих учасниками" в "Погодження змін до опису лоту" - він зараз використовується для опису лотів
![default](https://cloud.githubusercontent.com/assets/24773833/25796710/4d0f120a-33e3-11e7-9715-84d6c73d8fad.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
