### ISSUE TITLE
nkcentr: Поля Рішення дирекції ФГВФО не відмічаються червоним кольором при спробі опублікувати аукціон не заповнивши їх

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1286]
https://sale.nkc.biz.ua/test/

**Опис:** Поля Рішення дирекції ФГВФО не відмічаються червоним кольором при спробі опублікувати аукціон не заповнивши їх, а текст повідомлення "Помилка: This field is required." не вносить ясності яке саме поле необхідно заповнити

**Відтворення:**
1) Увійти на майданчик під логіном nkc-likvidator@yopmail.com
2) Перейти до розділу "Аукціони"
3) Натиснути кнопку "Новий аукціон" 
4) Обрати тип "майна банків" 
5) Заповнити поля валідними даними (лишити пустими поля Рішення дирекції ФГВФО)
6) Зберегти аукціон
7) Опублікувати аукціон

**Очікуваний результат:** Поля Рішення дирекції ФГВФО помічені червоним кольором

**Фактичний результат:** Поля Рішення дирекції ФГВФО не помічені червоним кольором, а текст еррор-повідомлення "Помилка: This field is required." не каже яке саме поле необхідно заповнити
![1](https://cloud.githubusercontent.com/assets/13050207/25532342/c31a5f82-2c35-11e7-99b5-2728e93265f9.png)
![2](https://cloud.githubusercontent.com/assets/13050207/25532343/c31c5aa8-2c35-11e7-9d61-d0b3ba1f2f96.png)

**Comment by v-lego** [comment]
внесли до перевірки обов'язкових полів

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![0](https://cloud.githubusercontent.com/assets/13050207/25799579/2b6f89da-33ee-11e7-9203-fb42d4afdac6.png)
![1](https://cloud.githubusercontent.com/assets/13050207/25799580/2b73bd98-33ee-11e7-83d5-30e4acd1710b.png)
