### ISSUE TITLE
nkcentr: Невірні назви полів при створенні/перегляді аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1287]
https://sale.nkc.biz.ua/test/

**Опис:** 
Початкова ціна реалізації Лоту - має бути "Початкова ціна продажу Лоту"
Розмір гарантійного забезпечення пропозиції - має бути "Розмір гарантійного внеску"

**Відтворення:**
1) Увійти на майданчик під логіном nkc-likvidator@yopmail.com
2) Перейти до розділу "Аукціони"
3) Натиснути кнопку "Новий аукціон" 
4) Передивитися назви полів при створенні аукціону
5) Обрати довільний опублікований аукціон та перглянути назви полів

**Очікуваний результат:** Неймінг полів відповідає [Ручним тестам](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.ph8fpaozr3jk)

**Фактичний результат:** Назва полів "Початкова ціна реалізації Лоту" - має бути "Початкова ціна продажу Лоту", а "Розмір гарантійного забезпечення пропозиції" - має бути "Розмір гарантійного внеску" згідно [Ручним тестам](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.ph8fpaozr3jk) рівень 1 (Організатор)
![default](https://cloud.githubusercontent.com/assets/13050207/25533192/7c43f6e2-2c38-11e7-8342-55efc659b30b.png)
![2](https://cloud.githubusercontent.com/assets/13050207/25533300/e38df3de-2c38-11e7-85f7-d81f174a4cd8.png)

**Comment by v-lego** [comment]
внесено зміни
![default](https://cloud.githubusercontent.com/assets/24773833/25793899/387dfc5e-33d7-11e7-92a5-2557c156df2d.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
