### ISSUE TITLE
nkcentr: Після опублікування при заміні документу "Порядок ознайомлення з майном" текст документу відображається який був до зміни 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1288]
https://sale.nkc.biz.ua/test/

**Опис:** Після опублікування при заміні документу "Порядок ознайомлення з майном" текст документу відображається який був до зміни, також **при пергляді документ відображається як посилання яке веде до неіснуючої сторінки** https://sale.nkc.biz.ua/test/undefined

**Відтворення:**
1) Увійти на майданчик під логіном nkc-likvidator@yopmail.com
2) Перейти до розділу "Аукціони"
3) Натиснути кнопку "Новий аукціон" 
4) Обрати тип "майна банків"
5) Заповнити поля валідними даними зберегти та опублікувати аукціон
6) Додати документ "Порядок ознайомлення з майном"
7) Зберегти та опублікувати аукціон
8) Оновити в аукціоні документ "Порядок ознайомлення з майном" замінивши текст
9) Перезавантажити сторінку аукціону

**Очікуваний результат:** "старий" документ перекреслено, а "новий" відображається з оновленим змістом

**Фактичний результат:** замість оновленого тексту "порядку ознайомлення з майном" відображується той що був до зміни (UA-EA-2017-04-28-000016-2)
![default](https://cloud.githubusercontent.com/assets/13050207/25533683/161e8498-2c3a-11e7-86ff-c62a2ca5f0c7.png)

**Comment by v-lego** [comment]
отримано консультацію, що це значення поки змінювати не можна.
Тому:
- можливість оновлення цього типу документації прибрано
- виведено застереження (можливо потрібно більш контрастно), що значення у подальшому не можна буде змінити
![default](https://cloud.githubusercontent.com/assets/24773833/25794017/d0bb4738-33d7-11e7-93d1-e2af40a496df.png)

**Comment by SoftserveQC1** [comment]
Після додавання документу "Порядок ознайомлення з майном" текст вказаний у ньому дудблюється після інших прикріплених документів
прошу прибрати лейб importent
![default](https://cloud.githubusercontent.com/assets/13050207/25799747/ef8dd772-33ee-11e7-8c4f-d93aef1f34c0.png)

**Comment by v-lego** [comment]
Внесено зміни до завантаження документації 
![default](https://cloud.githubusercontent.com/assets/24773833/25989402/a48bff6a-3704-11e7-9cb0-560e4b37b774.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
