### ISSUE TITLE
nkcentr: Відсутнє повідомлення про визнання Учасника переможцем і необхідність підписати Протокол на протязі трьох діб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1289]
https://sale.nkc.biz.ua/test/auction/UA-EA-2017-04-28-000030-2/

**Опис:** Переможцю не приходять повідомлення про визнання його переможцем і необхідність підписати Протокол на протязі трьох діб. Дане повідомлення не приходить ні на пошту ні до особистого кабінету

**Передумова:**
- Увійти на майданчик під логіном nkcentr-likvidator@yopmail.com
- Перейти до розділу "Аукціони"
- Натиснути кнопку "Новий аукціон" 
- Обрати тип "майна банків"
- Заповнити поля валідними даними зберегти та опублікувати аукціон
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-yurosoba@yopmail.com
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-fizosoba@yopmail.com
- Дочекатися початку кваліфікації

**Відтворення:**
1) Увійти на майданчик переможцем
2) Перевірити повідомлення у кабінеті (Профіль-Повідомлення)
3) Перевірити пошту переможця

**Очікуваний результат:** Отримати повідомлення про визнання Учасника переможцем і необхідність підписати Протокол на протязі трьох діб електронною поштою та особистому кабінеті

**Фактичний результат:** Повідомлення переможцю про перемогу відсутні
UA-EA-2017-04-28-000027-2
UA-EA-2017-04-28-000030-2
UA-EA-2017-04-28-000017-2

**Comment by v-lego** [comment]
Внесено зміни
Повідомлення формується

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![default](https://cloud.githubusercontent.com/assets/13050207/25902766/2aab5568-35a3-11e7-8e71-40e791f37aaf.png)
