### ISSUE TITLE
nkcentr: Відсутні повідомлення переможцю про автоматичну дискваліфікацію і Ліквідатору та Учаснику2 про перехід кваліфікації до нього

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1290]
https://sale.nkc.biz.ua/test/

**Опис:** Після автоматичної дискваліфікації Переможця через відсутніть протоколу/договору у встановлені строки не надходять повідомлення про дискваліфікацію Переможця (на пошту та у кабінеті Переможцю) та про початок кваліфікації Учасника2 і необхідність прикріпити протокол торгів протягом 3я діб (Учаснику2 та Ліквідатору)

**Передумова:**
- Увійти на майданчик під логіном nkcentr-likvidator@yopmail.com
- Перейти до розділу "Аукціони"
- Натиснути кнопку "Новий аукціон" 
- Обрати тип "майна банків"
- Заповнити поля валідними даними зберегти та опублікувати аукціон
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-yurosoba@yopmail.com
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-fizosoba@yopmail.com
- Дочекатися початку кваліфікації
- Не прикріпляти Протокол торгів Ліквідатором протягом 3х діб(дискваліфікація Переможця)

**Відтворення:**
1) Увійти на майданчик переможцем
2) Перевірити повідомлення у кабінеті (Профіль-Повідомлення)
3) Перевірити пошту
4) Увійти на майданчик Учасником, що зайняв друге місце
5) Перевірити повідомлення у кабінеті (Профіль-Повідомлення)
6) Перевірити пошту

**Очікуваний результат:** 
1) Переможця автоматично дискваліфіковано, про що він отримує відповдне повідомлення на пошту та у особистому кабінеті
2) Кваліфікація переходить до наступного учасника, Учасник, що зайняв друге місце та Ліквідатор отримують листа про початок кваліфікації для Учасника, що зайняв друге місце

**Фактичний результат:** 
1) Переможець **НЕ отримує** повідомлення про дискваліфікацію на пошту та у особистому кабінеті
2) Учасник, що зайняв друге місце та Ліквідатор  **НЕ отримують** листа про початок кваліфікації для Учасника, що зайняв друге місце

**Comment by v-lego** [comment]
Внесено зміни
Ліквідатор і Учасник1 отримує повідомлення про зміну стану дискваліфікованої пропозиції
Ліквідатор і Учасник2 отримує повідомлення про початок кваліфікації №2

**Comment by SoftserveQC1** [comment]
Дефект виправлено
