### ISSUE TITLE
nkcentr: У повідомленнях для Учасника який зайняв друге місце вказується, що можна не забирати гарантійний внесок протягом 15 діб замість 11-ти

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1291]
https://sale.nkc.biz.ua/test/

**Опис:**У повідомленнях на пошту та у особистому кабінеті для Учасника який зайняв друге місце вказується, що можна не забирати гарантійний внесок протягом 15 діб замість [регламентованих](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.1fap1z6or798) 11-ти

**Передумова:**
- Увійти на майданчик під логіном nkcentr-likvidator@yopmail.com
- Перейти до розділу "Аукціони"
- Натиснути кнопку "Новий аукціон" 
- Обрати тип "майна банків"
- Заповнити поля валідними даними зберегти та опублікувати аукціон
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-yurosoba@yopmail.com
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-fizosoba@yopmail.com
- Дочекатися початку кваліфікації

**Відтворення:**
1) Увійти на майданчик Учасником, що зайняв друге місце
2) Перевірити повідомлення у кабінеті (Профіль-Повідомлення)
3) Перевірити пошту

**Очікуваний результат:**У повідомленнях учаснику, що зайняв друге місце вказується, що можна не забирати гарантійний внесок протягом 11 діб

**Фактичний результат:** У повідомленнях учаснику, що зайняв друге місце вказується, що можна не забирати гарантійний внесок протягом 15 діб
![1](https://cloud.githubusercontent.com/assets/13050207/25809064/9e129ef2-3414-11e7-930a-679cb26d9a22.png)
![2](https://cloud.githubusercontent.com/assets/13050207/25809062/9dd9e65c-3414-11e7-9b69-d066da6091ed.png)

**Comment by v-lego** [comment]
Внесено зміни до шаблону повідомлень

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![11](https://cloud.githubusercontent.com/assets/13050207/25902654/d93ff0b2-35a2-11e7-85aa-c6c67d9ddfc9.png)
![111](https://cloud.githubusercontent.com/assets/13050207/25902655/d977c0f0-35a2-11e7-9ddd-b988117c36c8.png)
