### ISSUE TITLE
nkcentr: Учасник не отримує повідомлення про дискваліфікацію

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1293]
https://sale.nkc.biz.ua/test/

**Опис:** Учасник не отримує повідомлення про дискваліфікацію у разі відсутності доданого Протоколу/Договору у строк 3/11 діб відповідно. Повідомлення про дискваліфікацію Ліквідатором також надходять не завжди

**Передумова:**
- Увійти на майданчик під логіном nkcentr-likvidator@yopmail.com
- Перейти до розділу "Аукціони"
- Натиснути кнопку "Новий аукціон" 
- Обрати тип "майна банків"
- Заповнити поля валідними даними зберегти та опублікувати аукціон
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-yurosoba@yopmail.com
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-fizosoba@yopmail.com
- Дочекатися початку кваліфікації

**Відтворення:**
1) Не прикріпляти Ліквідатором Протокол торгів протягом 3х діб
2) Після автоматичної дискваліфікації переможця перевірити його пошту та повідомлення в особистому кабінеті
3) Прикріпіи Ліквідатором Протокол торгів для наступного учасника
4) Не прикріпляти договір протягом 11діб
5) Після автоматичної дискваліфікації учасника перевірити його пошту та повідомлення в особистому кабінеті

**Очікуваний результат:** Після автоматичної дискваліфікації учасник отримує відповідне повідомлення на пошту та у особистому кабінеті

**Фактичний результат:** Після автоматичної дискваліфікації учасник не отримує повідомлення на пошту та у особистому кабінеті

**Comment by v-lego** [comment]
Повідомлення надходять при отриманні оновлень від ЦБД
Оновлення надходять з затримкою (очікувано до 5 хвилин)

**Comment by SoftserveQC1** [comment]
https://sale.nkc.biz.ua/test/auction/UA-EA-2017-05-10-000020-2/
Повідомлення про дискваліфікацію прийшло лише першому учаснику, другий кандидат не отримав аналогічного листа
![default](https://cloud.githubusercontent.com/assets/13050207/25903075/17776292-35a4-11e7-9254-1050261ae029.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
також надходять повідомлення про завершення торгів
