### ISSUE TITLE
nkcentr: Ліквідатор може дискваліфікувати учасника не прикріпляючи документ із поясненням рішення

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1295]
https://sale.nkc.biz.ua/test/

**Опис:**Ліквідатор може дискваліфікувати учасника не прикріпляючи документ із поясненнями рішення, для дискваліфікації достатньо лише заповнити поле зі змістом рішення. У [вимогах](http://dgf.api-docs.openprocurement.org/uk/latest/tutorial.html#disqualification-of-a-candidate) чітко сказано "У випадку ручної дискваліфікації, організатор **повинен** завантажити файл з поясненням причини дискваліфікації кандидата"

**Передумова:**
- Увійти на майданчик під логіном nkcentr-likvidator@yopmail.com
- Перейти до розділу "Аукціони"
- Натиснути кнопку "Новий аукціон" 
- Обрати тип "майна банків"
- Заповнити поля валідними даними зберегти та опублікувати аукціон
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-yurosoba@yopmail.com
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-fizosoba@yopmail.com
- Дочекатися початку кваліфікації

**Відтворення:**
1) Увійти Ліквідатором
2) Перейти до аукціону у розділ "Кваліфікація"
3) Заповнити поле "Зміст рішення" для Переможця
4) Натиснути кнопку "Кандидат дискваліфікований"

**Очікуваний результат:** Дискваліфікація не відбувається, Ліквідатор отримує повідомлення про необхідність додати файл з поясненням причини дискваліфікації кандидата

**Фактичний результат:** Учасника дискваліфіковано без додавання файлу з поясненням причини дискваліфікації кандидата

**Comment by v-lego** [comment]
Внесено перевірку на кількість документів при дискваліфікації

**Comment by SoftserveQC1** [comment]
Дефект виправлено
