### ISSUE TITLE
nkcentr: Відсутні повідомлення Ліквідатору та учаснику, що зайняв друге місце про початок кваліфікації для нього пісяля дискваліфікації переможця

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1296]
https://sale.nkc.biz.ua/test/

**Опис:** Ліквідатор та Учасник наступний за переможцем(Уч2) не отримують повідомлення про початок авордінгу для Уч2 після дискваліфікації Переможця

**Передумова:**
- Увійти на майданчик під логіном nkcentr-likvidator@yopmail.com
- Перейти до розділу "Аукціони"
- Натиснути кнопку "Новий аукціон" 
- Обрати тип "майна банків"
- Заповнити поля валідними даними зберегти та опублікувати аукціон
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-yurosoba@yopmail.com
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-fizosoba@yopmail.com
- Дочекатися початку кваліфікації

**Відтворення:**
1) Увійти Ліквідатором
2) Перейти до аукціону у розділ "Кваліфікація"
3) Заповнити поле "Зміст рішення" для Переможця
4) Додати документ з описом рішення
5) Натиснути кнопку "Кандидат дискваліфікований"

**Очікуваний результат:** Уч2 та Ліквідатор отримують повідомлення на пошту та у особистому кабінеті про початок кваліфікації Уч2 та дискваліфікації Переможця

**Фактичний результат:** Уч2 та Ліквідатор не отримують повідомлення про початок кваліфікації/авордінгу Уч2

**Comment by v-lego** [comment]
Учасник 2 одразу (при потраплянні змін  до майданчику) отримує повідомлення, про визнання переможцем
![default](https://cloud.githubusercontent.com/assets/24773833/25895304/fb7cadb6-3587-11e7-9b1b-3053f0f662a7.png)
чи потрібно надавати повідомлення Ліквідатору? Не знаходжу за ручними тестами
https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.xzzfi7nsffou

**Comment by SoftserveQC1** [comment]
Учасник2 отримав повідомлення, бажано додати повідомлення Ліквідатору, бо він може пропустити кваліфікацію Учасника2
Прошу прибрати лейб "important"

**Comment by v-lego** [comment]
Внесено зміни
Ліквідатор отримує повідомлення про зміни кваліфікації (ручні/автоматичні)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
