### ISSUE TITLE
utsb: При дискваліфікація першого учатника після завантаження протоколу не вимагається завантаження документів та вказання причини з боку ліквідатора

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1297]
Відтворення:
1 провести торги до етапу кваліфікації
2 завантажити протокол для переможця
3 дискваліфікувати переможця

Очікувано: необхідно завантажити документ та вказати причину дискваліфікації

Фактично: кандидат дискваліфікується лише нажаттям кнопки "дискваліфікувати"

![12](https://cloud.githubusercontent.com/assets/13050207/25894426/6a57fb36-3584-11e7-86df-3530c16aff30.png)

**Comment by v-lego** [comment]
Внесено перевірку кількості документів при дискваліфікації

**Comment by SoftserveQC1** [comment]
**АКТУАЛЬНО**
Внесена перевірка мабуть перевіряє "протокол", а конкретно причину дискваліфікацї та документ дискваліфікації від ліквідатора не вимагає

**Comment by v-lego** [comment]
внесено перевірку на подання протоколу 
![default](https://cloud.githubusercontent.com/assets/24773833/25993213/f7a90172-3711-11e7-894e-fe81a71e27ab.png)
внесено перевірку на документ відмови
![default](https://cloud.githubusercontent.com/assets/24773833/25993337/51eb4f1e-3712-11e7-98e5-7f2ec2d2a695.png)
Перевірка на заповнення поля зміст присутня
![default](https://cloud.githubusercontent.com/assets/24773833/25993458/b45d721c-3712-11e7-9edd-2fffc647ca52.png)

**Comment by SoftserveQC1** [comment]
Вибиває помилку 
![16](https://cloud.githubusercontent.com/assets/13050207/25997815/9fdc6294-3726-11e7-8870-01487a4ed179.png)

**Comment by v-lego** [comment]
Це повідомлення від ЦБД про неможливість прийняти документ у цьому стані
Прибрано можливість дискваліфікувати Учасника після отримання оплати
залишено тільки "Відміна"
Прибрано можливість додавання документів у стані "Виграно"

**Comment by SoftserveQC1** [comment]
Кнопка "відмінити" не працює

**Comment by v-lego** [comment]
змінили стан передачі для кнопки "Відмінити"

**Comment by SoftserveQC1** [comment]
![16](https://cloud.githubusercontent.com/assets/13050207/26002300/e5870748-3737-11e7-8937-6ae0417ea3bd.png)

**Comment by v-lego** [comment]
Для даного типу контейнера встановили за відсутності типу
![default](https://cloud.githubusercontent.com/assets/24773833/26003473/707c0bac-373b-11e7-830d-82bab07d5ebc.png)

**Comment by SoftserveQC1** [comment]
![16](https://cloud.githubusercontent.com/assets/13050207/26053867/37ba4880-3973-11e7-8915-a8f1a62328db.png)

**Comment by v-lego** [comment]
Внесли оновлення.
Просимио перевірити дискваліфікацію

**Comment by SoftserveQC1** [comment]
![16](https://cloud.githubusercontent.com/assets/13050207/26054530/96e3fb10-3975-11e7-9320-ca6de40d018c.png)

**Comment by v-lego** [comment]
Просимо продовжити
