### ISSUE TITLE
utsb: Перший участник не дискваліфіковується автоматично після не завантажування ним пртокол протягом 3-о діб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1298]
Відтворення:
1 Провести торги до етапу кваліфікації
2 не завантажувати протокол для переможця

Очікувано: кандидат автоматично дискваліфіковується після 3-ох діб очікування

Фактично: кандидат не дискваліфіковуєтсья після 3-ох діб очікування

![13 3 -](https://cloud.githubusercontent.com/assets/13050207/25894565/f67c7182-3584-11e7-9822-57e28e0aa321.png)

**Comment by v-lego** [comment]
ЦБД може відпрацьовувати зміни до 5 хвилин
в даному випадку ми отримали оновлення тільки о 13:22:53.820
