### ISSUE TITLE
nkcentr: Поле дата підписання договору не є обов'язковим полем для заповнення

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1299]
https://sale.nkc.biz.ua/test/

**Опис:** Згідно [Ручних тестів](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.i1yp8prqs2f8) завершуючи аукціон Ліквідатор обовязково повинен вказати номер договору, дату підписання та прикріпити підписаний договір, але поле "дата підписання" не є обов'язковим. Втім вразі його незаповнення можливо успішно завершити аукціон бо датою підписання договору буде відображена дата обробки у ЦБД

**Передумова:**
- Увійти на майданчик під логіном nkcentr-likvidator@yopmail.com
- Перейти до розділу "Аукціони"
- Натиснути кнопку "Новий аукціон" 
- Обрати тип "майна банків"
- Заповнити поля валідними даними зберегти та опублікувати аукціон
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-yurosoba@yopmail.com
- Залогінитись та зробити ставку(початкова вартість+мин крок) nkcentr-fizosoba@yopmail.com

**Відтворення:**
1) Увійти на майданчик під логіном nkc-likvidator@yopmail.com
2) Перейти до аукціону
3) Прикріпити та підтвердити Протокол торгів
4) Підтвердити оплату
5) Додати документ договору
6) Вказати номер договору
7) Не заповнювати дату підписання та опублікувати договір

**Очікуваний результат:** Публікація договору не відбувається, Ліквідатор отримує еррор-повідомленя про необхідність ввести дату договору (обов'язкове поле)

**Фактичний результат:** Договір публікуєтья та аукціон успішно завершено. При перегляді аукціону відображено дату публікації

**Comment by v-lego** [comment]
Зняли обов'язковість полів Дати підписання та Номеру

**Comment by v-lego** [comment]
Поновили повну обо`вязковість полів Дати підписання та Номеру

**Comment by SoftserveQC1** [comment]
Дефект виправлено
