### ISSUE TITLE
ЭЛЕГ - не открылись торги, пришедшие с ПРОМ

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#13]
![image](https://cloud.githubusercontent.com/assets/9398532/5872032/03cdcb36-a2ef-11e4-9f1a-2ec26bc74e39.png)

**Comment by S-Shevchenko** [comment]
Исправили
Причина ошибки: не открывались торги, из-за того что не был заполнен профиль. Пользователь вошел в систему и перешел на просмотр деталей тендера
