### ISSUE TITLE
Новостворений тендер потрапляє на майданчик, із статусом "Немає даних" і залишається в цьому стані вже більше 3 годин

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#130]
Протестовано в Chrome, Firefox, IE та Opera.

![nodata](https://cloud.githubusercontent.com/assets/11062040/6389544/79a05e40-bdad-11e4-8703-bfa4631d0bea.png)

**Comment by S-Shevchenko** [comment]
Спасибо. Были остановлены  сервисы на 99 машине и тендер повис. Можно закрывать.
Тесовое окружение перенесено на http://services.e-tender.biz:100/#/.

**Comment by lerich** [comment]
Закриваю.
