### ISSUE TITLE
utsb: Участникам та ліквідатору не приходить повідомлення на пошту про успішне завершення торгів 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1300]
Відтворення:
1 провести успішні торги
2 перевірити пошту участників та ліквідатора

Очікувано: Участники отримують листа на пошту про успішне завершення торгів

Фактично: листи на пошту не приходять ні участникам ні ліквідатору

**Comment by v-lego** [comment]
Внесено повідомлення про термінальні стани Лоту для Ліквідатора, Учасників та Авторам запитань
