### ISSUE TITLE
utsb: Після завантаження протоколу для 1-го участника, 2-ий участник немає змоги відмовитись від участі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1301]
**Обрати "права та вимоги"**

Відтворення:
1 провести торги
2 завантажити протокол для 1-го участника
3 в якості 2-го участника спробувати відмовитись від участі

Очікувано: 2-ий участник має можливість відмовитись від участі після завантаження протоколу для 1-го участника

Фактично: 2-го участника дискваліфіковано

![14 2](https://cloud.githubusercontent.com/assets/13050207/25896624/a6c8b570-358d-11e7-97ea-af94e33ae1aa.png)

**Comment by v-lego** [comment]
Нажаль такий стан оримали з ЦБД одразу після аукціону 
Скоріш за все, зза того що пропозиція була по ції виставлення 20000
Тому пропозиція була одразу дискваліфікаована

status:	unsuccessful
complaintPeriod{2}
suppliers[1]
bid_id:	74238a0e678b4d59b34469aeb875a86a
value{3}
currency	:	UAH
amount	:	20000
valueAddedTaxIncluded	:		true
date	:	2017-05-10T14:18:39.691676+03:00
id	:	316b10035f494a8d9afb17c05fc3127c
