### ISSUE TITLE
utsb: Нагадування про запитання регулярно приходить ліквідатору після відміни аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1302]
Відтворення:
1. Запустити торги
2 в якості участника задати запитання
3 не відповідати на запитання
4 відмінити торги
5 почекати кілька днів, перевіряючи пошту

очікувано:  нагадування не будуть приходити коли вони вже не актуальні

фактично: отримання неактуальних нагадувань 

![15](https://cloud.githubusercontent.com/assets/13050207/25940193/f6ed43e4-363d-11e7-8099-5775a3eefba4.png)
![15](https://cloud.githubusercontent.com/assets/13050207/25940194/f6f0717c-363d-11e7-9299-c565e6027510.png)

**Comment by v-lego** [comment]
- внесно зміни до дій по термінальному стану 
- проведено погашення питань активних питань
будь-ласка, перевірте у завтрашньому нагадуванні
