### ISSUE TITLE
epsilon: Відсутня функціональність завантажувати користувачами документи до профілю при реєстрації та у особистому кабінеті

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1303]
https://tbepsilon.com/register

**Опис:** На майданчику користувач не має можливості завантажувати документи під час реєстрації чи в особистому кабінеті, наприклад:
- Можливість завантажувати скановану копію рішення дирекції ФГВ щодо призначення
- Можливість завантаження фінансової ліцензії 
- Можливість завантаження інших документів

**Відтворення:**
1) Перейти на майданчик
2) Натиснути кнопку "Зареєструватись"
3) Переглянути можливість завантажувати докумети
4) Залогінитись користувачем epsilon-likvidator@yopmail.com
5) Перейти до розділу головного меню "Моя компанія" --> "Інформація про компанію"
6) Натиснути кнопку "Редагувати компанію" і переглянути можливість завантажувати докумети

**Очікуваний результат:** При реєстрації або/та у особистому кабінеті існує можливість Користувачу додавати необхідні підтверджуючі документи згідно до [Ручних тестів](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.eye0w8ma7zvx) розділу "Тестові сценарії, реєстрація користувачів" п.1-6

**Фактичний результат:** Можливості додати документ на етапі реєстрації немає, а для Замовника є обов'язковим додання необхідних підтверджуючих документів

**Comment by IllyaPetrusenko** [comment]
Fixed. Прошу закрыть дефект.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![1](https://user-images.githubusercontent.com/13050207/27728962-9c43138a-5d8c-11e7-8d40-8364280916cf.png)
