### ISSUE TITLE
tovprof: При реєстрації юзера URL-адреса не повинна бути обовязкова

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1304]
Відтворення
1 Зареєструвати нового юзера (будь-якого)
2 лишити поле "URL" пустим

Очікувано: немає вимоги щоб URL було обовязковим полем

Фактично: у користувача вимагається URL

![2](https://cloud.githubusercontent.com/assets/13050207/25947746/62805fd6-3659-11e7-9418-bcabd2377040.png)

**Comment by ukrosoft** [comment]
Убрали проверку на обязательное наличие URL
