### ISSUE TITLE
tovprof: При неправильному заповненні полів при реєстрації, повідомлення про помилки відображається на російській мові

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1305]
Відтворення:
1 зареєструвати нового юзера
2 ввести невалідні значення для полів
3 звернути увагу на повідомлення про помилки

Очікувано: мова сторінки співпадає з мовою повідомленнь про помилки

фактично: мова сторінки не співпадає з мовою повідомленнь про помилки

![1](https://cloud.githubusercontent.com/assets/13050207/25947875/f91f8a5c-3659-11e7-9c4d-b8040aab2b29.png)

**Comment by ukrosoft** [comment]
Исправили систему переводов
![screenshot_20170512_113651](https://cloud.githubusercontent.com/assets/16786861/25990133/518c1a18-3707-11e7-9e9b-0d26bb3f7ef0.png)
