### ISSUE TITLE
tovprof: ID лоту відображається у неправильному форматі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1306]
Відтворення:
1 створити лот
2 звернути увагу на ідентифікатор

![3 -](https://cloud.githubusercontent.com/assets/13050207/25949612/bd171604-3660-11e7-9705-d257e6ac191f.png)
![3 -](https://cloud.githubusercontent.com/assets/13050207/25949613/bd186f2c-3660-11e7-82b2-a22e45cf7b79.png)

**Comment by ukrosoft** [comment]
Для неопубликованых лотов убрали вывод внутреннего ID
http://joxi.ru/xAeB0yJT3ovbry
