### ISSUE TITLE
tovprof: помилка у відображенні дати

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1307]
Відтворення:
1 створити лот, вказавши дату проведення завтрашньою
2 перейти на сторінку лоту

очікувано: дати і час до початку коректно відображається

фактично: помилка у відображення часу до початку аукціону

![4](https://cloud.githubusercontent.com/assets/13050207/25949774/62c96020-3661-11e7-9b5f-f240fd7db5a8.png)

**Comment by ukrosoft** [comment]
Ошибки при вычислении даты в обратном отсчете поправили
