### ISSUE TITLE
tovprof: Неможливо встановити годину проведення аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1308]
Відтворення:
1 Перейти на форму створення лоту
2 переглянути форму

фактично: відсутнє поле для встановлення годину проведення лоту

очікувано: ліквідатор має можливість встановити годину лоту

![5](https://cloud.githubusercontent.com/assets/13050207/25949866/babd0016-3661-11e7-890a-8b2b5416bba6.png)

**Comment by ukrosoft** [comment]
Добавили возможность ввода время проведения аукциона:
http://joxi.ru/KAgBG5kT1pGL2l
