### ISSUE TITLE
tovprof: Після натискання "опублікувати" вибиває помилку

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1309]
Відтворення:
1 створити лот
2 нажати "опублікувати" на сторінці лоту

фактично: помилка

очікувано: лот опублікований

![7](https://cloud.githubusercontent.com/assets/13050207/25952212/b206a5ce-3668-11e7-8038-82d30bd7c1f1.png)

**Comment by ukrosoft** [comment]
Добавили ряд проверок для обязательных полей, в частности для поля dgfID, с которым была связана ошибка на скриншоте
