### ISSUE TITLE
tovprof: дублювання опцій при виборі документі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1310]
Відтворення:
1 створити лот
2 додати документ
3 відкрити випадаючий список "тип документа"

очікувано: відсутність дублювання опцій

фактично: дублювання опцій

![6](https://cloud.githubusercontent.com/assets/13050207/25952363/26905048-3669-11e7-8050-b1497475e6da.png)

**Comment by ukrosoft** [comment]
Дублирование убрано
