### ISSUE TITLE
tovprof: тип документу "договір NDA" повинен бути відсутній для майна банків

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1311]
Відтворення:
1 Створити лот майно банів
2 на сторінці лоту додати документ
3 звернути увагу на випадаючий список 

очікувано: відсутній тип документу "договір NDA" для майна банків

фактично: присутній тип документу "договір NDA" для майна банків

![8](https://cloud.githubusercontent.com/assets/13050207/25952651/ef89220e-3669-11e7-8eb6-5ecf58e74975.png)

**Comment by ukrosoft** [comment]
NDA для "майна банків" убрано
