### ISSUE TITLE
tovprof: Відсутня опція тип документу "договір VDR" для прав вимог

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1312]
відтворення:
1 створити лот з прав вимог
2 додати документ
3 відкрити спадний список
4 звернути увагу на відсутність опції "договір VDR"

![9](https://cloud.githubusercontent.com/assets/13050207/25952848/733687e0-366a-11e7-8769-25c3d24973f0.png)

**Comment by ukrosoft** [comment]
В описании сказано, что VDR - это ссылка, а не тип загружаемого документа. Добавление ссылки на VDR у нас реализовано, скриншот прилагается 
![screenshot_20170512_111634](https://cloud.githubusercontent.com/assets/16786861/25989401/a3a01d66-3704-11e7-854d-fba5396807c0.png)
