### ISSUE TITLE
tovprof: При створенні лоту не має можливості передати деякі поля, які відображаються на сторінці лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1313]
відтворення:
1 створити лот
2 перейти до сторінки лоту

![10](https://cloud.githubusercontent.com/assets/13050207/25953286/917f10ae-366b-11e7-9421-5f75c8edaf51.png)

**Comment by ukrosoft** [comment]
Недостающие поля добавлены на форме редактирования аукциона
![screenshot_20170512_112031](https://cloud.githubusercontent.com/assets/16786861/25989511/16a1c15c-3705-11e7-9b20-875899581979.png)
