### ISSUE TITLE
tovprof: Ліквідатор може відмінити аукціон без вказання причини та завантаження документу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1314]
Відтворення:
1 створити лот
2 відмінити лот, залишивши форму абсолютно пустою

очікувано: ліквідатор повинен завантажити документ закритя торгів, та
Можливі прочини задаються майданчиком (drop down):
- Згідно рішення виконавчої дирекції Фонду гарантування вкладів фізичних осіб
- Порушення порядку публікації оголошення 
- Цінові пропозиції, якщо ще не були розкриті,не розкриваються

фактично: відсутність будь яких перевірок

![11](https://cloud.githubusercontent.com/assets/13050207/25953551/6cd41f00-366c-11e7-88e9-215cb51ea540.png)

**Comment by ukrosoft** [comment]
Добавили требование указания причины при отмене
