### ISSUE TITLE
tovprof: Посилання VDR повинно бути відсутнє для майна банків

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1315]
Відтворення:
1 Створити лот
2 додати посилання

очікувано: опція посилання VDR - відсутня

фактично:  опція посилання VDR - присутня

![12](https://cloud.githubusercontent.com/assets/13050207/25990367/29d07dc4-3708-11e7-9d29-d1775303bd3a.png)

**Comment by ukrosoft** [comment]
Исправлено
![screenshot_20170512_120225](https://cloud.githubusercontent.com/assets/16786861/25991166/09de435e-370b-11e7-906c-02c1d7e64835.png)
