### ISSUE TITLE
tovprof: Вкладка дані профілю дублюється

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1317]
Відтворення:
1 перейти в особистий кабінет
2 перейти у вкладку "дані профілю"

очікувано: вкладка не дублюється
фактично: вкладка дублюється

![15](https://cloud.githubusercontent.com/assets/13050207/25993688/7ff3ffe0-3713-11e7-93ac-0782864f6ada.png)

**Comment by ukrosoft** [comment]
Исправлено
![screenshot_20170512_132641](https://cloud.githubusercontent.com/assets/16786861/25994489/b0de6b1a-3716-11e7-9484-30632d313aa7.png)
