### ISSUE TITLE
tovprof: Назва вкладки "документи" не актуальна

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1319]
Відтворення:
1 перейти в особистий кабінет
2 перейти у вкладку документи

фактично: назва вкладки не актуальна

очікувано: назва вкладки повинна бути "документи"

![16](https://cloud.githubusercontent.com/assets/13050207/25993802/fdd2f3bc-3713-11e7-8b26-ec4fc3278604.png)

**Comment by ukrosoft** [comment]
Исправлено
![screenshot_20170512_132741](https://cloud.githubusercontent.com/assets/16786861/25994518/cd6f2b98-3716-11e7-876b-280309b2774f.png)
