### ISSUE TITLE
Пошук тендера за СPV кодом відображається некоректно

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#132]
Протестовано на майданчику та в кабінеті замовника у Firefox, Crome, IE та Opera бравзерах

![incorrect_cpv_search](https://cloud.githubusercontent.com/assets/11062040/6395141/2c45f290-bddf-11e4-9f6d-c418ac3123aa.png)

**Comment by S-Shevchenko** [comment]
Спасибо. В работе.

**Comment by S-Shevchenko** [comment]
Можно закрывать как дубликат задачи 133.
