### ISSUE TITLE
epsilon: Ставки учасників зроблені з майданчика epsilon у json відображені як зроблені з eauction.brizol.net

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1320]
https://tbepsilon.com/

**Опис:** Ставки учасників зроблені з майданчика epsilon у json відображені як зроблені з brizol. Замість owner tbepsilon.com у json фігурує eauction.brizol.net

**Передумова:**
- Залогінитись користувачем epsilon-likvidator@yopmail.com
- Створити аукціон (Мої аукціони - Створити аукціон)
- Заповнити всі необхідні дані тп опублікувати аукціон (кнопка "Зберегти та перейти до публікаціїї")
- Зробити ставки юзерами (не менше початкової вартості + мін крок)
      - epsilon-fizosoba@yopmail.com
      - epsilon-urosoba@yopmail.com
- Дочекатися завершення торгів

**Відтворення:**
1) Переглянути json аукціону https://lb.api-sandbox.ea.openprocurement.org/api/2.4/auctions/317b286b3025412e95abb59b404c2345 на http://jsonviewer.stack.hu/
2) Подивитися розділ bids та оглянути owner ставок зроблених раніше

**Очікуваний результат:** owner є tbepsilon.com, бо з цього майданчика були зроблені ставки

**Фактичний результат:** owner вказано eauction.brizol.net
![json](https://cloud.githubusercontent.com/assets/13050207/25993717/a0935f66-3713-11e7-9ae1-104f5cf56bba.png)

**Comment by IllyaPetrusenko** [comment]
Используется тестовый ключ brizol.

**Comment by SoftserveQC1** [comment]
Не дефект
