### ISSUE TITLE
epsilon: При спробі дискваліфікувати учасника без вказання причини кнопка "дискваліфікації" перестає бути активною

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1321]
https://tbepsilon.com/

**Опис:** У розділі Кваліфікація аукціону у випадку прикріплення файлу відмови учаснику та не вказання причини дискваліфікації у полі чи чекпоксі кнопка "Дискваліфікація" перестає бути активної доки не перезавантажити сторінку

**Передумова:**
- Залогінитись користувачем epsilon-likvidator@yopmail.com
- Створити аукціон (Мої аукціони - Створити аукціон)
- Заповнити всі необхідні дані тп опублікувати аукціон (кнопка "Зберегти та перейти до публікаціїї")
- Зробити ставки юзерами (не менше початкової вартості + мін крок)
      - epsilon-fizosoba@yopmail.com
      - epsilon-urosoba@yopmail.com
- Дочекатися початку кваліфікації

**Відтворення:**
1) Перейти до розділу кваліфікація (Аукціон - Таблиця кваліфікації (правий сайдбар))
2) У розділі Дискваліфікація додати файл (опис причини)
3) Чекбокси "Причини рішення" та/або поле "Опис рішення" не заповняти
4) Дискваліфікувати Учасника (кнопка "Дискваліфікувати" - кнопка "Застосувати")

**Очікуваний результат:** Дискваліфікація не відбувається, але кнопка "Дискваліфікувати" активна та її можна використовувати

**Фактичний результат:** Кнопка "Дискваліфікація" перестає бути активної доки не перезавантажити сторінку
![default](https://cloud.githubusercontent.com/assets/13050207/25994737/c8c30d34-3717-11e7-913f-9f1c67eb666e.png)

**Comment by IllyaPetrusenko** [comment]
Принято и будет исправлено в ближайшее время.

**Comment by IllyaPetrusenko** [comment]
Готово. Прошу закрыть дефект.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![default](https://cloud.githubusercontent.com/assets/13050207/26143832/46538802-3aef-11e7-9f7d-cb25139737e8.png)
