### ISSUE TITLE
epsilon: Замість назви кнопки "Забрати гарантійний внесок" кнопка іменується "Відмовити"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1322]
https://tbepsilon.com/

**Опис:** Для Учасника, що зайняв друге місце у розділі кваліфікація назва кнопки відповідальної за повернення гарантійного внеску та відмови від подальшої участі у аукціоні - "Відмовитись" замість "Забрати гарантійний внесок"

**Передумова:**
- Залогінитись користувачем epsilon-likvidator@yopmail.com
- Створити аукціон (Мої аукціони - Створити аукціон)
- Заповнити всі необхідні дані тп опублікувати аукціон (кнопка "Зберегти та перейти до публікаціїї")
- Зробити ставки юзерами (не менше початкової вартості + мін крок)
      - epsilon-fizosoba@yopmail.com
      - epsilon-urosoba@yopmail.com
- Дочекатися початку кваліфікації

**Відтворення:**
1) Увійти учасником, що зайняв друге місце (Учасник)
2) Перейти до розділу кваліфікація (Аукціон - Таблиця кваліфікації (правий сайдбар))
3) Огянути розділ кваліфікації

**Очікуваний результат:** Під ставкою Учасника присутня кнопка "Забрати гарантійний внесок"

**Фактичний результат:** Під ставкою Учасника присутня кнопка "Відмовитись" замість "Забрати гарантійний внесок"
![default](https://cloud.githubusercontent.com/assets/13050207/25995279/2e2a1468-371a-11e7-9ddc-a761d12ea73c.png)

**Comment by IllyaPetrusenko** [comment]
Принято и будет исправлено в ближайшее время.

**Comment by IllyaPetrusenko** [comment]
Готово. Прошу закрыть дефект.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![default](https://cloud.githubusercontent.com/assets/13050207/26143848/58b5da4a-3aef-11e7-911b-535c15499a98.png)
