### ISSUE TITLE
epsilon: Ліквідатор не отримує повідомлення про повернення гарантійного внеску Учасником із другою ставкою

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1323]
https://tbepsilon.com/

**Опис:** Після повернення гарантійного внеску Учасником із другою ставкою Ліквідатор не отримує про це повідомлення, через відсутність інформації Ліквідатор може прийняти поспішне рішення щодо переможця, не знаючи, що інших кандидатів вже не буде

**Передумова:**
- Залогінитись користувачем epsilon-likvidator@yopmail.com
- Створити аукціон (Мої аукціони - Створити аукціон)
- Заповнити всі необхідні дані тп опублікувати аукціон (кнопка "Зберегти та перейти до публікаціїї")
- Зробити ставки юзерами (не менше початкової вартості + мін крок)
      - epsilon-fizosoba@yopmail.com
      - epsilon-urosoba@yopmail.com
- Дочекатися початку кваліфікації

**Відтворення:**
1) Увійти учасником, що зайняв друге місце (Учасник)
2) Перейти до розділу кваліфікація (Аукціон - Таблиця кваліфікації (правий сайдбар))
3) Натиснути кнопку "Відмовитись"
4) Перевірити пошту Ліквідатора

**Очікуваний результат:** Учасника дискваліфіковано, Ліквідатор отримує повідомлення на пошту та в особистому кабінеті про відмову другого Учасника 

**Фактичний результат:** Ліквідатор не отримує повідомлення на пошту та в особистому кабінетіпро відмову Учасника із другою позицією

**Comment by IllyaPetrusenko** [comment]
Спасибо за рекомендацию.

**Comment by SoftserveQC1** [comment]
Додано повідомлення на пошту Ліквідатору
![2](https://cloud.githubusercontent.com/assets/13050207/26143875/75989972-3aef-11e7-90b5-b77e4ce52e33.png)
