### ISSUE TITLE
tovprof: При заданні запитання зміст його не відповідає заданому

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1324]
Відтворення:
1 Створити лот
2 в якості участника задати запитання
3 перейти до запитання в якості участника (відображається спотворений зміст)

очікувано: питання коректно відображається для всіх

фактично:
участник, який задав запитання
![17](https://cloud.githubusercontent.com/assets/13050207/25995762/9811c1bc-371c-11e7-95da-12b6544a1de2.png)

**Comment by ukrosoft** [comment]
Вывод вопросов исправлен
![screenshot_20170512_164806](https://cloud.githubusercontent.com/assets/16786861/26000758/d691d3bc-3732-11e7-9046-fd27fd63d63f.png)

**Comment by SoftserveQC1** [comment]
баг актуальний
![17](https://cloud.githubusercontent.com/assets/13050207/26053747/a13247b4-3972-11e7-9497-68bbda352143.png)
