### ISSUE TITLE
tovprof: Торги переходять в етап аукціону коли пропозиції ше мали прийматися згідно з вказаним часом

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1325]
Відтворення:
1 створити лот
2 подати 2 пропозиції
3 дочекатись доки він перейде в етап аукціону

![19](https://cloud.githubusercontent.com/assets/13050207/25996018/b2369350-371d-11e7-81aa-5f11f2060d75.png)

**Comment by ukrosoft** [comment]
Вывод дат поправлен (они были перепутаны)
![screenshot_20170512_165219](https://cloud.githubusercontent.com/assets/16786861/26000955/75a7c6dc-3733-11e7-9ea9-1673962c90d3.png)
