### ISSUE TITLE
tovprof: Ліквідатор не може відповісти на запитання

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1326]
Відтворення:
1 Створити лот
2 участником подати запитання
3 ліквідатором перейти до форми із запитаннями

очікувано: присутня кнопка яка дозволяє відповісти на задане запитання

фактично: відсутня можливвіст відповісти на запитання

![18](https://cloud.githubusercontent.com/assets/13050207/25996078/0a25bba4-371e-11e7-8bbb-aa8e99dc739a.png)

**Comment by ukrosoft** [comment]
Функция ответов исправлена
![screenshot_20170512_164917](https://cloud.githubusercontent.com/assets/16786861/26000853/25075c88-3733-11e7-9102-2af2ae22cea0.png)
![screenshot_20170512_165004](https://cloud.githubusercontent.com/assets/16786861/26000852/2505aa64-3733-11e7-8f75-ac902eb3488f.png)
![screenshot_20170512_165027](https://cloud.githubusercontent.com/assets/16786861/26000851/250349d6-3733-11e7-88c2-0a3ef70636e0.png)
