### ISSUE TITLE
tovprof: Дата завершення прийому пропозицій повинна відображатися замість "дата та час завершення торгів"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1327]
Відтворення:
1 Створити лот
2 перейти на сторінку лоту

![20](https://cloud.githubusercontent.com/assets/13050207/25999948/ac0186d6-372f-11e7-8724-bfbc042d5447.png)

**Comment by ukrosoft** [comment]
Вывод дат поправлен (они были перепутаны)
![screenshot_20170512_165219](https://cloud.githubusercontent.com/assets/16786861/26000969/87e0918a-3733-11e7-94bd-2b83053f7cfc.png)
