### ISSUE TITLE
tovprof: Після натискання кнопки "змінити дані" переходить на неактуальну сторінку

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1328]
Відтворення:
1 перейти до раніше створеного лоту
2 нажати кнопку "змінити дані"

очікувано: відкриває форма з даними про лот де їх можна змінити 

фактично: неактуальна сторінка 

![21 - 404](https://cloud.githubusercontent.com/assets/13050207/26002062/13ed8cb6-3737-11e7-8515-86ce2e1335b6.png)

**Comment by ukrosoft** [comment]
В опубликованном аукционе уже отсутствует возможность менять какие-либо данные по аукциону, кроме документов. Указанная здесь страница как раз и служит для редактирования документов, но при отсутствии каких-либо загруженным материалов по аукциону редактировать на ней нечего.
