### ISSUE TITLE
tovprof: немає опції створити аукціон з чернеток чи раніше створеного

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1329]
Відтворення:
1 перейти в мої аукціони

очікувано: присутня кнопка яка копіює аукціон

фактично: відсутня можливість скопіювати аукціон

![17 -](https://cloud.githubusercontent.com/assets/13050207/26002612/e4fec440-3738-11e7-9f98-5444fd66e844.png)

**Comment by ukrosoft** [comment]
Добавили возможность создания нового аукциона на основе существующего
![screenshot_20170512_192659](https://cloud.githubusercontent.com/assets/16786861/26007429/1960fbe4-3749-11e7-9cb9-741d301e1bf4.png)
