### ISSUE TITLE
Пошук тендера за ДКПП кодом відображається некоректно

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#133]
Протестовано на майданчику та в кабінеті замовника у Firefox, Crome, IE та Opera бравзерах

![incorrect_dkpp_search](https://cloud.githubusercontent.com/assets/11062040/6395177/629e08c8-bddf-11e4-905c-7336b0a498b0.png)

**Comment by S-Shevchenko** [comment]
Спасибо. Взяли в работу.Идентичная задача по поиску по классификаторам. Аналогичная задача: #132

**Comment by S-Shevchenko** [comment]
@OksanaPakholok  Виправили, будь-ласка перевірте.

**Comment by OksanaPakholok** [comment]
03/12/2015, http://services.e-tender.biz:100/#/  Перевірено. Не репродюситься.
