### ISSUE TITLE
tovprof: Немає можливості завантажити протокол та договір електронних торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1330]
Відтворення:
1 провести успішні торги 
2 Завершивши торги і завантаживши всі необхідні докуменит (протокол і договір), пепеглянути сторінку торгів

очікувано: є можливість скачати протокол і договір електронних торгів

фактично: завантаженні документи відсутні для завантаження

![22](https://cloud.githubusercontent.com/assets/13050207/26054760/7b6c5bc4-3976-11e7-8f43-7dcabf877b09.png)

**Comment by ukrosoft** [comment]
Исправлено
