### ISSUE TITLE
tovprof: кнопка "скасувати аукціон" відображається коли вона вже не є актуальною

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1332]
Відтворення:
1 провести успішні торги
2 на сторінці аукціону звернути увагу на кнопку "скасувати аукціон (завершити аукціон)"

очікувано: кнопка відсутня

фактично: кнопка присутня

![23](https://cloud.githubusercontent.com/assets/13050207/26054920/48a73820-3977-11e7-9666-6752417a51ec.png)

**Comment by ukrosoft** [comment]
Исправлено
