### ISSUE TITLE
tovprof: Незрозуміла форма яка переводить ліквідатора на сторінку аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1333]
Відтворення:
1 провести торги до етапу кваліфікація
2 на сторінці торгів нажати кнопку "кваліфікація"

![24](https://cloud.githubusercontent.com/assets/13050207/26055886/743b3938-397b-11e7-8684-99b460ebf4a6.png)

**Comment by ukrosoft** [comment]
Исправили, теперь все это на страние результатов аукциона находится, и дисквалификация вынесена на модальное окно
![screenshot_20170516_171629](https://cloud.githubusercontent.com/assets/16786861/26110642/9d271f8e-3a5b-11e7-9850-d90ecb43f8e0.png)
![screenshot_20170516_171700](https://cloud.githubusercontent.com/assets/16786861/26110649/a00833e6-3a5b-11e7-8bee-5498974d42cf.png)
