### ISSUE TITLE
tovprof: участники не отримують посилання з модулем електронного аукціону на електронну пошту та особистий кабінет

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1334]
Відтворення:
1 створити лот
2 в якості участників подати пропозиції
3 дочекатись визначення дати проведення аукціону
4 перевірити пошту та особистий кабінет

очікувано: участники отримають посилання з модулем електронного аукціону на електронну пошту та особистий кабінет

фактично: участники не отримають посилання з модулем електронного аукціону на електронну пошту та особистий кабінет

![25](https://cloud.githubusercontent.com/assets/13050207/26060406/a95419c0-398d-11e7-85d0-c3ff2ef23e7f.png)

**Comment by ukrosoft** [comment]
Исправлено

**Comment by ukrosoft** [comment]
![photo_2017-05-17_14-34-35](https://cloud.githubusercontent.com/assets/16786861/26152031/043c3a58-3b0e-11e7-96b4-3e95705f7c2e.jpg)
