### ISSUE TITLE
tovprof: Для участника який зайняв 2-ге місце відсутня можливість відмовитись від участі (забрати гарантійний внесок)

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1335]
Відтворення:
1 провести торги до етапу кваліфікації
2 участником який зайняв 2-ге місце перейти на сторінку аукціону

очікувано: наявна кнопка яка дозволяє відмовитись від участі

фактично: відсутня кнопка яка дозволяє відмовитись від участі

![26](https://cloud.githubusercontent.com/assets/13050207/26062439/789f9524-3993-11e7-96fc-a9e220f38cca.png)

**Comment by ukrosoft** [comment]
Исправлено
![photo_2017-05-17_16-10-54](https://cloud.githubusercontent.com/assets/16786861/26155580/53b57abe-3b1c-11e7-80aa-a2da2cfb2378.jpg)
