### ISSUE TITLE
Privat: Неможливо додати до профілю користувача документ назва якого містить кирилицю

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1336]
https://lot.pb.ua/#/cabinet/profile

**Відтворення:**
1) Залогінитись користувачем privat-likvidator@yopmail.com
2) Перейти у "Кабінет користувача"
3) Натиснути на посилання "Додати документ"
4) Обрати документ який містить кирилицю у назві (наприклад "Договір")

**Очікуваний результат:** Документ успішно додано до профілю

**Фактичний результат:** Документ не завантажено, з'являється ерор-попап
![default](https://cloud.githubusercontent.com/assets/13050207/26099854/b514c6fe-3a34-11e7-923d-4e0db69939a2.png)

**Comment by pbil** [comment]
fixed

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![abrc](https://cloud.githubusercontent.com/assets/13050207/26110658/a690739a-3a5b-11e7-9274-0d9ef7ab8626.png)
