### ISSUE TITLE
Tirex: Немає можливості завантажувати будь які документи при реєстрації ліквідатора/фізичної особи/юридичної особи/фінансової компанії

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1337]
**Кроки для відтворення:**
1. Відкрити майданчик http://test.eauction-tendersale.com.ua
2. Натиснути кнопку "Зареєструватись"
3. Вибрати тип реєстрації: Організатор аукціонів/Учасник аукціонів
4. Перевірити наявність поля для прикріплення документів (скановані копії рішення дирекції ФГВ щодо призначення, фінансовї ліцензії та ін.)

**Очікуваний результат:** 
На майданчику є поля для прикріплення документів

**Фактичний результат:**
На майданчику немає полів для прикріплення документів

**Comment by IllyaPetrusenko** [comment]
Выполнено. Прошу закрыть дефект.
