### ISSUE TITLE
Tirex: Реєстрація ліквідатора відбувається без введення назви банку та ЄДРПОУ банку

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1338]
**Кроки для відтворення:**

1. Відкрити майданчик http://test.eauction-tendersale.com.ua
2. Натиснути кнопку "Зареєструватись"
3. Заповнити всі обов'язкові поля даними, окрім полів "Повна назва Банку" та "ЄДРПОУ Банку"
4. Натиснути кнопку "Зареєструватись"

**Очікуваний результат:**
Реєстрація користувача не відбувається без введення інформації в обов'язкові поля "Повна назва Банку" та "ЄДРПОУ Банку"

**Фактичний результат:**
Реєстрація користувача відбувається без введення інформації в обов'язкові поля "Повна назва Банку" та "ЄДРПОУ Банку"

**Comment by IllyaPetrusenko** [comment]
Прошу закрыть дефект.
