### ISSUE TITLE
tovprof: Участнику не відображає торги в яких він бере участь на сторінці "актуальні торги"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1339]
Відтворення:
1 Оголосити торги
2 як участник подати пропозицію
3 перейти в "особистий кабінет->актуальні торги"

![27](https://cloud.githubusercontent.com/assets/13050207/26103635/1aed1f54-3a43-11e7-9e29-b528b06d0eb5.png)

**Comment by ukrosoft** [comment]
Убрали из профиля ссылку "актуальные торги", так как такой функционал пока не реализовывался, и в перечень требований на данный момент он не входит
