### ISSUE TITLE
Немає доступу до тестового середовища

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#134]
![no_access](https://cloud.githubusercontent.com/assets/11062040/6409554/fb1de7f6-be6d-11e4-8f98-0c48bba4967b.png)

**Comment by lerich** [comment]
Сори, тестовое окружение перенесено на services.e-tender.biz:100

**Comment by OksanaPakholok** [comment]
Дякую, що повідомили

2015-02-27 12:01 GMT+02:00 Valeriy Nesmashnyy notifications@github.com:
