### ISSUE TITLE
tovprof: Ліквідатору не приходить щоденне нагадування про запитання на яке він не відповів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1340]
**Нагадування повинне приходити поки лот не завершився чи скасований**

відтворення:
1  оголосити лот за кілька днів
2 задати запитання про до лоту
3 не відповідати на запитання
4 дочекатись наступного дня
5 перевірити пошту та особистий кабінет

очікувано: ліквідатору приходить щоденне нагадування про запитання на яке він не відповів

фактично: ліквідатору не приходить щоденне нагадування про запитання на яке він не відповів

![28](https://cloud.githubusercontent.com/assets/13050207/26103891/40bf1b28-3a44-11e7-9457-bc38836f5643.png)

**Comment by ukrosoft** [comment]
Исправлено, уведомления о неотвеченных вопросах теперь будут приходить каждый день в 8 утра
