### ISSUE TITLE
Tirex: Поле "Серія та номер паспорту" не є обов'язковим до заповнення для реєстрації фізичних осіб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1341]
**Кроки для відтворення:**

1. Відкрити майданчик http://test.eauction-tendersale.com.ua
2. Натиснути кнопку "Зареєструватись"
3. Обрати тип реєстрації: Учасник аукціонів
4. Вибрати форму власності: фізична особа-підприємець/фізична особа/фізична особа з релігійними переконаннями
5. Заповнити всі необхідні поля даними, окрім поля "Серія та номер паспорту"

**Очікуваний результат:**
Обліковий запис не створюється без введення даних в обов'язкові поля "Серія та номер паспорту"

**Фактичний результат:**
Обліковий запис створюється без введення даних в обов'язкові поля "Серія та номер паспорту"

**Comment by IllyaPetrusenko** [comment]
Fixed. Прошу проверить и закрыть дефект.
