### ISSUE TITLE
tovprof: кнопка "перейти до аукціону" не працює для участників аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1342]
Відтворення:
1 оголосити торги
2 подати пропозиції
3 дочекавшись визначення дати проведення аукціону, нажати кнопку "перейти до аукціону"

очікувано: відкриється вкладка де участники зможуть зробити свої ставки

фактично: після нажимання нічого не відбувається

![29](https://cloud.githubusercontent.com/assets/13050207/26105065/42a025ae-3a49-11e7-85fe-ddd9bf85aa74.png)

**Comment by ukrosoft** [comment]
Исправлено
