### ISSUE TITLE
Vidrodzhennia: процес реєстрації не проходить до кінця 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1343]
**Опис:** на майданчику Відродження не зберігають дані під час реєстрації у Кабінеті учасника

**Майданчик:** https://e.tbv.com.ua/

**Кроки для відтворення:**
1. Передіть на сторінку реєстрації https://e.tbv.com.ua/registration/
2. Заповність всі необхідні поля -> натисніть кнопку реєстрація
Кабінет Учасника відкритий
3. Заповніть всі необхідні поля та написніть Зберегти\Підтвердити

**Фактичний результат:** Користувач зареєстрований, але всі персональні дані не зберігаються (ЄДРПОУ, коротка та повна назва, адреса, банкіські реквізити), щодного повідомлення про успішне збереження не відображається.

**Очікуваний результат:** Користувач зареєстравоний. Повідомлення про збереження даних показується. Всі персональні дані збережені і відображаються у Кабінеті Учасника.

**Comment by AlexGr7** [comment]
Внесено зміни до порядку перевірки та повідомлення про реєстрацію

**Comment by v-lego** [comment]
Внесено зміни до перевірки форми та повідомлення про реєстрацію

**Comment by SoftserveQC1** [comment]
Дефект виправлено
