### ISSUE TITLE
Vidrodzhennia: Некоректна назва лінки для ресєтрації коистувача

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1344]
**Опис:** Лінка для реєстрації користувача аукціону повинна бути на PROZORRO. ФГВФО

**Майданчик:** https://e.tbv.com.ua/

**Фактичний результат:** сторінка реєстрації вікривається при натиску на PROZORRO.Реєстрація публічних закупівель

**Очікуваний результат:** сторінка реєстрації вікривається при натиску на PROZORRO. ФГВФО

![default](https://cloud.githubusercontent.com/assets/13050207/26105759/0aebe410-3a4c-11e7-8b29-fe380d8ea145.png)

**Comment by v-lego** [comment]
Встановлено всі лінки https://e.tbv.com.ua/#
Лінк торгів по ФГВФО: https://e.tbv.com.ua/
Лінк реєстрації по ФГВФО: https://e.tbv.com.ua/registration/

**Comment by SoftserveQC1** [comment]
Дефект виправлено
