### ISSUE TITLE
tovprof: Помилка при спробі дискваліфікувати участника торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1345]
**можливо відтворюється для двох участників**

Відтворення:
1 провести торги до етапу кваліфікації
2 для першого участника не завантажувати протокол (автоматично дискваліфікується)
3 дискваліфікувати другого участника 

очікувано: участник дискваліфікований

фактично: помилка, участник не дискваліфікований

![30](https://cloud.githubusercontent.com/assets/13050207/26107286/6ce62a7c-3a51-11e7-95be-e07f7a10db59.png)
![30](https://cloud.githubusercontent.com/assets/13050207/26107287/6d247138-3a51-11e7-808c-deaa9ecbe25c.png)

**Comment by ukrosoft** [comment]
Исправлено
![photo_2017-05-17_16-11-05](https://cloud.githubusercontent.com/assets/16786861/26155632/7d71fce2-3b1c-11e7-8dbf-d4d1561efad5.jpg)
