### ISSUE TITLE
Privat: При реєстрації фізичної особи відсутнє підтвердження на обробку персональних даних

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1346]
https://lot.pb.ua/

**Відтворення:**
1) Перейти до реєстраціїї (Увійти->Зареєструватися)
2) Перевірити наявність згоди на обробку персональних даних (чекбокс чи інше)
3) Заповнити необхідні поля та натиснути кнопку "Зареєструватися"
4) Перевірити пошту та перейти за посиланням із листа про реєстрацію
5) Залогінитися та перейти до профілю (Мій кабінет - редагувати)
6) Обрати акаунт - Фізична особа
7) Перевірити можливість дати згоду на обробку персональних даних

**Очікуваний результат:** Користувач фізична особа при реєстрації має надати згоду на обробку персональних даних згідно [Тестових сценаріїв, реєстрація користувачів кейс 3](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.ismabgrv7k)

**Фактичний результат:** Користувач не може дати згоду на обробку персональних даних при реєстрації
![1](https://cloud.githubusercontent.com/assets/13050207/26110335/b3c5a522-3a5a-11e7-9ba7-2b1388a64d39.png)
![2](https://cloud.githubusercontent.com/assets/13050207/26110323/ae8c5678-3a5a-11e7-99cc-c3e6a11713df.png)
![3](https://cloud.githubusercontent.com/assets/13050207/26110339/b5b18df6-3a5a-11e7-9b61-55ffe78508b1.png)

**Comment by pbil** [comment]
fixed

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![fix](https://cloud.githubusercontent.com/assets/13050207/26115918/11c74c2a-3a6a-11e7-953d-b2f89d7669a8.png)
