### ISSUE TITLE
Privat: Користувач не отримує повідомлення про валідацію акаунту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1347]
https://lot.pb.ua/

**Опис:** Користувач не отримує повідомлення на пошту та у особистому кабінеті про активацію створеного акаунта

**Відтворення:**
1) Перейти до реєстраціїї (Увійти->Зареєструватися)
2) Перевірити наявність згоди на обробку персональних даних (чекбокс чи інше)
3) Заповнити необхідні поля та натиснути кнопку "Зареєструватися"
4) Перевірити пошту та перейти за посиланням із листа про реєстрацію
5) Залогінитися та перейти до профілю (Мій кабінет - редагувати)
6) Заповнити всі необхідні дані профілю та підтвердити їх у модератора
7) Після активації акаунту перевірити пошту та повідомлення у кабінеті

**Очікуваний результат:** Користувач після валідації акаунту отримує повідомлення в кабінеті та на пошту про успішну активацію акаунту згідно [Тестових сценаріїв, реєстрація користувачів кейс 1-6](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.ismabgrv7k)

**Фактичний результат:** Користувач не отримує повідомлення про активацію створеного акаунту

**Comment by pbil** [comment]
fixed
