### ISSUE TITLE
Privat: В профілі користувача Фінансової компанії поле "Номер фінансової ліцензії" не є обов'язковим

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1348]
https://lot.pb.ua/

**Опис:** В профілі користувача Фінансової компанії поле "Номер фінансової ліцензії" не є обов'язковим, через незаповнення нього навіть після активації акаунту адміном користувач не зможе робити ставки на аукціони з продажу права вимоги, ставки не будуть прийматися цбд

**Відтворення:**
1) Перейти до реєстраціїї (Увійти->Зареєструватися)
2) Перевірити наявність згоди на обробку персональних даних (чекбокс чи інше)
3) Заповнити необхідні поля та натиснути кнопку "Зареєструватися"
4) Перевірити пошту та перейти за посиланням із листа про реєстрацію
5) Залогінитися та перейти до профілю (Мій кабінет - редагувати)
6) Обрати тип Фінансова компанія та заповнити всі необхідні дані окрім номеру ліцензії
7) Валідувати акаунт у модератора

**Очікуваний результат:** Відправити на валідацію акаунт не вийшло через не заповнене поле "Номер фінансової ліцензії", про що з'являється ерор повідомлення

**Фактичний результат:** Користувач успішно відправляє на активацію Фінансову організацію без вказання "Номеру фінансової ліцензії" але після активації його ставки не будуть прийматися на аукціони з продажу права вимоги

**Comment by pbil** [comment]
fixed

**Comment by SoftserveQC1** [comment]
Виправлено
![1348](https://cloud.githubusercontent.com/assets/13050207/26152729/dc67c152-3b10-11e7-86a6-afcc4de090e9.png)
