### ISSUE TITLE
Privat: Після публікації аукціону Ліквідатор може редагувати інформацію аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1349]
https://lot.pb.ua/

**Опис:** Після публікації аукціону Ліквідатор може редагувати поля аукціону:
- Назва лоту
- Назва лоту російською мовою
- Назва лоту англійською мовою
- Номер лоту в ФГВ
- Номер та дата рішення ФГВ про затвердження умов продажу
- Лот виставляється на торги

**Відтворення:**
1) Залогінитись користувачем privat-likvidator@yopmail.com
2) Натиснути "Створити лот"
3) Заповнити всі поля валідними даними та натиснути "Зберегти"
4) Опублікувати аукціон
5) У тілі аукціону натиснути "редагувати лот"

**Очікуваний результат:** Можливо лише додати чи замінити документи до аукціону

**Фактичний результат:** Можливо редагувати поля аукціону: Назва лоту, Назва лоту російською мовою, Назва лоту англійською мовою, Номер лоту в ФГВ, Номер та дата рішення ФГВ про затвердження умов продажу, Лот виставляється на торги
![default](https://cloud.githubusercontent.com/assets/13050207/26117691/03a818d0-3a70-11e7-9133-89c77af81cd1.png)

**Comment by pbil** [comment]
в авто тестах вимагається редагування цих полів
і у документі https://docs.google.com/document/d/1RDuqCp3hMmKCE6K0SSV4V8mXHBndChQUo6DchHQaR7w/edit#
в розділі: "Можливість редагування лоту (перша ітерація, 6 текстових полів)" теж йде мова про редагування

де правити в автотестеха чи в сценаріях ручних тестів?


З автотестів проходження цих кроків, щодо зміни назв та номеру лоту ФГВ :
------------------------------------------------------------------------------
Неможливість змінити початкову вартість лоту                          | PASS |
------------------------------------------------------------------------------
Неможливість змінити мінімальний крок лоту                            | PASS |
------------------------------------------------------------------------------
Можливість змінити назву лоту українською мовою                       | PASS |
------------------------------------------------------------------------------
Відображення зміненого заголовку лоту                                 | PASS |
------------------------------------------------------------------------------
Можливість змінити опис лоту українською мовою                        | PASS |
------------------------------------------------------------------------------
Відображення зміненого опис лоту українською мовою                    | PASS |
------------------------------------------------------------------------------
Неможливість змінити дані про організатора лоту                       | PASS |
------------------------------------------------------------------------------
Неможливість змінити початок періоду подання пропозицій лоту          | PASS |
------------------------------------------------------------------------------
Неможливість змінити значення фінансового критерію лоту               | PASS |
------------------------------------------------------------------------------
Неможливість змінити гарантування лоту                                | PASS |
------------------------------------------------------------------------------
Можливість змінити номер лоту ФГВ                                     | PASS |
------------------------------------------------------------------------------
Відображення зміненого номера лоту ФГВ                                | PASS |

і так далі

**Comment by SoftserveQC1** [comment]
Згоден, але виник інший кейс
Згідно [змін у регламенті](https://docs.google.com/document/d/1RDuqCp3hMmKCE6K0SSV4V8mXHBndChQUo6DchHQaR7w/edit#) "Можливість редагування з’являється у Ліквідатора виключно після завантаження такого документа від Фонду (або одночасно з завантаженням такого документу)" на майданчику можна проводити редагування не прикріплюючи відповідний документ, та й у переліку доступних до завантаження документів немає документа з погодженням та описом змін (наприклад "Погодження змін у аукціоні від ФГВФО")

**Comment by pbil** [comment]
fixed

**Comment by SoftserveQC1** [comment]
Виправлено, але не дотримується умова "Каждое редактирование требует добавления документа (и предварительного согласования в Фонде)", завантаживши документ один раз користувач може редагувати і далі

**Comment by SoftserveQC1** [comment]
Виправлено
