### ISSUE TITLE
Privat: Відсутні повідомлення Ліквідатору про необхідність заповнити частину обов'язкових полів при створенні аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1350]
https://lot.pb.ua/

**Опис:** До полів Загальний опис (має бути **Загальний опис аукціону**), Кількість, Одиниці виміру відсутні повідомлення про необхідність їх заповнення як для інших обов'язкових полів, рекомендовано додати аналогічні повідомлення в інтерфейсі, бо у разі спроби публікації аукціону з пустими полями текст помилки не містить причину сбою при публікації 

**Відтворення:**
1) Залогінитись користувачем privat-likvidator@yopmail.com
2) Натиснути "Створити лот"
3) Натиснути кнопку "Зберегти" у правому сайдбарі створення аукціону
4) Заповнити всі поля до яких з'явилися ерор-повідомлення валідними даними
5) Натиснути кнопку "Зберегти" у правому сайдбарі створення аукціону
6) Натиснути кнопку "Публікувати лот"

**Очікуваний результат:** До всіх обов'язкових полів у разі іх незаповнення з'являються повідомлення в інтерфейсі

**Фактичний результат:** До полів **Загальний опис аукціону**, Кількість, Одиниці виміру відсутні повідомлення про необхідність їх заповнення
![2](https://cloud.githubusercontent.com/assets/13050207/26121233/40593f28-3a7c-11e7-93f8-e85edafc247d.png)
![0](https://cloud.githubusercontent.com/assets/13050207/26121237/447df594-3a7c-11e7-84d8-82dca3c45642.png)
![1](https://cloud.githubusercontent.com/assets/13050207/26121238/449f7642-3a7c-11e7-9262-d891f4e17645.png)
![default](https://cloud.githubusercontent.com/assets/13050207/26121239/47e068ac-3a7c-11e7-9b0a-80ec0cc2141f.png)

**Comment by pbil** [comment]
fixed

**Comment by SoftserveQC1** [comment]
Виправлено
