### ISSUE TITLE
Privat: В тілі аукціону відсутнє посилання на регламент

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1351]
https://lot.pb.ua/

**Відтворення:**
1) Залогінитись користувачем privat-likvidator@yopmail.com
2) Натиснути "Створити лот"
3) Заповнити всі поля валідними даними та натиснути "Зберегти"
4) Опублікувати аукціон
5) Переглянути опублікований аукціон

**Очікуваний результат:** В тілі аукціону присутнє посилання на [регламент](https://drive.google.com/file/d/0B7KIe21cMRzrbm9oZ3dsS0RsVG8/view?usp=sharing)

**Фактичний результат:** В тілі аукціону відсутнє посилання на регламент
![default](https://cloud.githubusercontent.com/assets/13050207/26121602/7e9910c8-3a7d-11e7-9b4e-bd4318a2403f.png)

**Comment by pbil** [comment]
fixed

**Comment by SoftserveQC1** [comment]
Виправлено
![1351](https://cloud.githubusercontent.com/assets/13050207/26152827/64aae97c-3b11-11e7-806b-8d3ad8d0b91a.png)
