### ISSUE TITLE
Privat: При створенні аукціону обов'язковими є поля "Код та Назва одиниці виміру" в якому немає автозаповнення, а користувач може не знати вірного коду чи абревіатури

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1353]
https://lot.pb.ua/

**Опис:** При створенні аукціону обов'язковим є поле "Код одиниці виміру" в якому немає автозаповнення, а користувач може не знати вірного коду чи назви/скорочення одиниці виміру (шт, штука, штук, одиніць?). Бажано додати дропбок с переліком можливих назв одиниць виміру, а поле код одиниці виміру прибрати

**Відтворення:**
1) Залогінитись користувачем privat-likvidator@yopmail.com
2) Натиснути "Створити лот"
3) Заповнити всі поля (окрім "Код одиниці виміру") валідними даними та натиснути "Зберегти"
4) Опублікувати аукціон

**Очікуваний результат:** Користувач обирає з дропбоксу одиниці виміру, після чого аукціон можна успішно опублікувати

**Фактичний результат:** Присутнє поле "Код одиниці виміру" при тому що код одиниці виміру учасник може не знати, як і вірну назву/скорочення, але опублікувати аукціон не вказавши Код не вийде
![default](https://cloud.githubusercontent.com/assets/13050207/26142950/73a3f32c-3aeb-11e7-83b6-06620cfd5a4c.png)
![default](https://cloud.githubusercontent.com/assets/13050207/26142897/4206ecca-3aeb-11e7-9623-993c3948faac.png)

**Comment by NikTaran** [comment]
fixed
