### ISSUE TITLE
Privat: Лист на пошту із посилання на модуль аукціонну прийшло Ліквідатору за всіх учасників

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1354]
https://lot.pb.ua/

**Опис:** Лист на пошту із посилання на модуль аукціонну прийшло Ліквідатору за всіх учасників, тобто скільки було учасників аукціону, стільки листів із посиланням на модуль аукціону отримав Ліквідатор на пошту + своє посилання. **У кабінеті користувача повідомлення прийшли усім учасникам як потребують того Ручні тести**

**Відтворення:**
1) Залогінитись користувачем privat-likvidator@yopmail.com
2) Натиснути "Створити лот"
3) Заповнити всі поля валідними даними та натиснути "Зберегти"
4) Опублікувати аукціон
5) Зробити ставки учасниками privat-finorg2@yopmail.com та privat-finorg@yopmail.com
6) Попросити модератора прийняти ставки
7) Дочекатися закінчення "періоду пропозицій"
8) Перевірити пошту та особистий кабінет учасниками

**Очікуваний результат:** Після завершення періоду прийому пропозицій отримати посилання на модуль аукціону електронною поштою та у кабінеті Учасника

**Фактичний результат:** Після завершення періоду прийому пропозицій листи на пошту із посиланням на модуль аукціону отримал Ліквідатор замість учасників, в данному прикладі Ліквідатор отримав 3 однакових посилання

**Comment by pbil** [comment]
fixed
