### ISSUE TITLE
Privat: Відсутня функціональність заміни документів у опублікованому аукціоні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1355]
https://lot.pb.ua/

**Опис:** Відсутня функціональність заміни документів у опублікованому аукціоні, можливо лише додати документ

**Відтворення:**
1) Залогінитись користувачем privat-likvidator@yopmail.com
2) Натиснути "Створити лот"
3) Заповнити всі поля валідними даними, додати кілька документів та натиснути "Зберегти"
4) Опублікувати аукціон
5) У тілі аукціону натиснути "редагувати лот"
6) Сбробувати замінити документі

**Очікуваний результат:** Можливо замінити документи до аукціону, стара версія документу відображається перекресленою при перегляді аукціону

**Фактичний результат:** Не можливо замінити документи, лише додати

**Comment by pbil** [comment]
fixed

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![0](https://cloud.githubusercontent.com/assets/13050207/26308198/dcfd122c-3f00-11e7-8af5-a6b2aa2a0b57.png)
![1](https://cloud.githubusercontent.com/assets/13050207/26308199/dcfe411a-3f00-11e7-93ed-94e54db325d4.png)
