### ISSUE TITLE
Privat: Відсутня можливисть дискваліфікувати Учасника на етапі підписання договору

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1357]
https://lot.pb.ua/

**Відтворення:**
1) Залогінитись користувачем privat-likvidator@yopmail.com
2) Натиснути "Створити лот"
3) Заповнити всі поля валідними даними та натиснути "Зберегти"
4) Опублікувати аукціон
5) Зробити ставки учасниками privat-finorg2@yopmail.com та privat-finorg@yopmail.com
6) Попросити модератора прийняти ставки
7) Дочекатися початку кваліфікації Переможця
8) Прикріпити протокол торгів Ліквідатором
9) Підтвердити оплату Переможця
10) Спробувати дискваліфікувати Переможця

**Очікуваний результат:** У ліквідатора є можливість дискваліфікувати учасника 1 або 2 на будь якій стадії

**Фактичний результат:** Після початку періоду "Оплачено, очікується підписання договору" зникає можливість дискваліфікувати Переможця
![default](https://cloud.githubusercontent.com/assets/13050207/26154108/deb54c8a-3b16-11e7-9359-e0b75bd1a7c7.png)

**Comment by pbil** [comment]
fixed

**Comment by pbil** [comment]
Зараз при спробі додати документ дискваліфікації отримуємо помилку від ЦБД:
POST https://lb.api-sandbox.ea.openprocurement.org/api/2.4/auctions/809130ab5732450fa7aa92a623297378/awards/d69e56065f814831a5e65b7007a4325f/documents

	request body: {"data":{"url":"http://public.docs-sandbox.ea.openprocurement.org/get/fe27c08df99d41b7a886fa9cc957b0a0?KeyID=cd1abfdf&Signature=w%2F2ShxQRKc80RJ8MLTiT1MlqMSg2WrmpEp1KRto3M%252BmuXnJVj5EKimc9SnR3dcMjs3Vfmx1YV2py5n%252Bux0OyCg%253D%253D","title":"bike_chase-wallpaper-2560x1600 (1).jpg","hash":"md5:e9dd817fbc096a550d7de52eab936330","format":"image/jpeg"}}

response status:403, 
response	body:{"status":"error","errors":[{"location":"body","name":"data","description":"Can't add document in current (active.awarded) auction status"}]}

    "x-request-id": "req-38d15a73-a1c0-43dd-b9b3-3a1d30cf496f",

**Comment by w-be** [comment]
Відповідно до Олександра Акуленко:
"На цьому етапі має бути можливість дискваліфікувати без завантаження договору, поки ЦБД на цій стадії не пропускає документи."

**Comment by pbil** [comment]
fixed

**Comment by SoftserveQC1** [comment]
Дискваліфікувати можливо, але без додавання документів
Натиснув кнопку "Дискваліфікувати" - і учасника відразу дискваліфіковано
