### ISSUE TITLE
tovprof: Кнопку "скасувати аукціон слід забрати" з торгів які у чернатках

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1358]
Відтворення:
1 Перейти в "особистий кабінет ->мої аукціони"

![31](https://cloud.githubusercontent.com/assets/13050207/26156665/beff46b2-3b1f-11e7-8105-6027ca7ccecb.png)

**Comment by ukrosoft** [comment]
Исправлено
![photo_2017-05-18_12-24-22](https://cloud.githubusercontent.com/assets/16786861/26195582/f62fcf9e-3bc4-11e7-8a57-82247bebdcd2.jpg)
