### ISSUE TITLE
tovprof: участнику який поточним переможцем не приходить сповіщення на пошту та особистий кабінет про те що йому необхідно завантажити протокол протягом 3-ох діб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1359]
Відтворення: 
1 провести торги до етапу кваліфікації
2 перевірити пошту та особистий кабінет 1-го участника
3 дискваліфікувати 1-го участника
4 перевірити пошту та особистий кабінет 2-го участника

очікувано: повідомлення про необхідність завантажити протокол протягом 3-ох діб на пошті та особистому кабінеті

фактично: повідомлення відсутні

![32 3](https://cloud.githubusercontent.com/assets/13050207/26157152/20c3564e-3b21-11e7-9257-d6a45670d4e1.png)

**Comment by ukrosoft** [comment]
Исправлено
![photo_2017-05-18_12-25-39](https://cloud.githubusercontent.com/assets/16786861/26195633/2471e676-3bc5-11e7-99f3-176bb89a5076.jpg)

**Comment by SoftserveQC1** [comment]
Для другого участника не приходить повідомлення (якщо дискваліфікувати 1-го, то 2-ий стає переможцем, йому теж має прийти повідомлення)
На пошту теж нічого не приходить

**Comment by SoftserveQC1** [comment]
Актуально
При запуску ше одного лоту повідомлення не прийшло участникам ні на пошту ні в особистий кабінет

**Comment by ukrosoft** [comment]
Нашли проблему, исправили
