### ISSUE TITLE
tovprof: участнику який зайняв друге місце не приходить повідомлення про можливість не забирати свій гарантіний внесок протягом 15 робочих діб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1360]
відтворення:
1 провести торги до етапу кваліфікації
2 перевірити пошту та особистий кабінет 2-го участника

очікувано: прийшло повідомлення про можливість не забирати свій гарантіний внесок протягом 15 робочих діб на пошту і особистий кабінет

фактично: повідомлення відсутнє

![33 15](https://cloud.githubusercontent.com/assets/13050207/26157405/c8be21ee-3b21-11e7-9a11-a01ee3e42cee.png)

**Comment by ukrosoft** [comment]
Исправлено
![photo_2017-05-18_12-26-25](https://cloud.githubusercontent.com/assets/16786861/26195662/3cf701ae-3bc5-11e7-8071-b53a2055cd72.jpg)

**Comment by SoftserveQC1** [comment]
Актуально
![image](https://cloud.githubusercontent.com/assets/13050207/26208078/e0d39982-3bf1-11e7-8a60-bbc4c9af48ff.png)

**Comment by ukrosoft** [comment]
Нашли проблему, исправили
