### ISSUE TITLE
tovprof: участникам та ліквідатору не приходитять повідомлення про результати аукціону на пошту та особистий кабінет

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1361]
Відтворення:
1 провести торги до етапу кваліфікації
2 перевірити пошту то особистий кабінет участників та ліквідатора

очікувано: прийшло повідомлення з результатами аукціону (хто виграв аукціон по ставкам) в особистий кабінет та на пошту

фактично: повідомлення не прийшло

![32 3](https://cloud.githubusercontent.com/assets/13050207/26157595/4d8d4fee-3b22-11e7-878a-c08333dccd3a.png)
![33 15](https://cloud.githubusercontent.com/assets/13050207/26157593/4d899746-3b22-11e7-9d4b-f7a760b45b88.png)
![34](https://cloud.githubusercontent.com/assets/13050207/26157594/4d8cb28c-3b22-11e7-81a9-bf6c1c11dca6.png)

**Comment by ukrosoft** [comment]
Исправлено
![photo_2017-05-18_12-26-50](https://cloud.githubusercontent.com/assets/16786861/26195695/4df5a26c-3bc5-11e7-88dd-5528b566b957.jpg)

**Comment by SoftserveQC1** [comment]
Актуально (участникам і ліквідатору нічого не прийшло ні на пошту ні в особистий кабінет)
![image](https://cloud.githubusercontent.com/assets/13050207/26208137/0970d666-3bf2-11e7-8694-cac5d120dd1a.png)

**Comment by ukrosoft** [comment]
Нашли проблему, исправили
