### ISSUE TITLE
tovprof: ліквідатору та участникам не приходить повідомлення на пошту та в особистий кабінет з кінцевими результатами торгів 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1362]
Кінцеві результати торгів:
- торги завершено (успішні)
- торги не відбулися (неуспішні, порушився процес)
- торги відмінено (неуспішні, скасовані ліквідатор)

Відтворення:
1 провести торги до одного з трьох можливих кінцевих результатів
2 перевірити пошту та особистий кабінет ліквідатора та участників

![32 3](https://cloud.githubusercontent.com/assets/13050207/26157932/257e8454-3b23-11e7-85c0-352e686fe6e1.png)
![33 15](https://cloud.githubusercontent.com/assets/13050207/26157934/2581e766-3b23-11e7-89db-a5223e05f1bd.png)
![34](https://cloud.githubusercontent.com/assets/13050207/26157933/2580e28a-3b23-11e7-8369-77f449568ed9.png)

**Comment by ukrosoft** [comment]
Исправлено
![photo_2017-05-18_12-23-36](https://cloud.githubusercontent.com/assets/16786861/26195549/dab9df84-3bc4-11e7-9f8e-b47fc0d1978e.jpg)

**Comment by SoftserveQC1** [comment]
Актуально (на пошту нічого не прийшло взагалі нікому, в особистий кабінет лише ліквідатору прийшло, але не по всім торгах, участники - не проінформовані взагалі)

**Comment by ukrosoft** [comment]
Нашли проблему, исправили
