### ISSUE TITLE
tovprof: користувачу не приходить нотицікація в особистий кабінет про успішне завантаження документів на будь якому етапі проведення торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1363]
При завантаженні документів (які стосуються лоту, протоколів, договорів та інших), користувачу який їх завантажив повинна прийти нотифікація, про успішне завантаження документу

![32 3](https://cloud.githubusercontent.com/assets/13050207/26158185/b9f38c42-3b23-11e7-86b2-aced2afd0958.png)
![33 15](https://cloud.githubusercontent.com/assets/13050207/26158188/bb4abfa2-3b23-11e7-95c8-c021c0e5544c.png)
![34](https://cloud.githubusercontent.com/assets/13050207/26158184/b9e7e798-3b23-11e7-95a2-9a82724e00e7.png)

**Comment by ukrosoft** [comment]
Исправлено
![photo_2017-05-18_12-22-30](https://cloud.githubusercontent.com/assets/16786861/26195527/c56b8164-3bc4-11e7-814c-e07b4bdaad1b.jpg)
