### ISSUE TITLE
tovprof: Зникає кнопка "дискваліфікувати" участника після підтвердження оплати

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1364]
Відтворення:
1 провести торги до етапу кваліфікації
2 завантажити протокол та підтвердити оплату

очікувано: кнопка "дискваліфікувати" повинна бути присутньою після підтвердження оплати (під час підписання договору)

фактично: кнопка "дискваліфікувати" відсутня після підтвердження оплати

![36](https://cloud.githubusercontent.com/assets/13050207/26160528/26ac9ff8-3b2a-11e7-8e12-08e217f308a6.png)

**Comment by ukrosoft** [comment]
Исправлено
