### ISSUE TITLE
tovprof: Кнопку "скасувати аукціон" слід прибрати коли етап прийому пропозицій завершено

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1365]
коли йде етап аукціону опція "скасувати аукціон" повинна бути відсутня

Відтворення:
1 оголосити торги 
2 дочекатись завершення прийому пропозицій
3 перейти на сторінку торгів

![35](https://cloud.githubusercontent.com/assets/13050207/26160646/89dc1c02-3b2a-11e7-872b-0071159995cc.png)
![35a](https://cloud.githubusercontent.com/assets/13050207/26161601/0e8b9dfe-3b2d-11e7-8715-d2ce0009ed3d.png)

**Comment by ukrosoft** [comment]
http://dgf.api-docs.openprocurement.org/uk/latest/tutorial.html#cancelling-auction
Організатор (ліквідатор) може скасувати аукціон на будь-якому етапі окрім аукціону в термінальних статусах (unsuccessful, cancelled, complete).
На скриншотах явно не конечные статуы, те.е. в соответствии с API возможность отмены аукциона на этих этапах должна быть

**Comment by ukrosoft** [comment]
Убрали кнопку
![photo_2017-05-18_16-26-43](https://cloud.githubusercontent.com/assets/16786861/26204274/e7cb1306-3be6-11e7-9b67-de86f6814fcb.jpg)
