### ISSUE TITLE
Реєстрація. Недоступні до перегляду Регламен та Договір приєднання.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1366]
https://sale.vertas.com.ua/test/Registration.aspx?&type=registration

Відтворення:
1. Перейтити до реєстрації
2. Натиснути на Регламент / Договір приєднання.

Очікуванно: Відображається регламент/ Договір приєднання.
Фактично: Ресурс не знайдено.
![image](https://cloud.githubusercontent.com/assets/11888281/26199048/48885d9a-3bd1-11e7-8c99-1dba915ae9a7.png)
![image](https://cloud.githubusercontent.com/assets/11888281/26199087/64f12890-3bd1-11e7-9a6f-ab0a2d98e047.png)

**Comment by v-lego** [comment]
Встановлено посилання на сторінки з початковими документами
![default](https://cloud.githubusercontent.com/assets/24773833/26452391/7c0a9bd2-4168-11e7-8f9b-482d8ef4e888.png)
![default](https://cloud.githubusercontent.com/assets/24773833/26452427/9a5e0560-4168-11e7-866b-6b27e7cdf977.png)
