### ISSUE TITLE
Кабінет Учасника. Неможливо завантажити документ.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1367]
https://sale.vertas.com.ua/test/Member_Card.aspx?&id__
учасник: biviktorqc@gmail.com

Відтворення: 
1. Залогуйтесь як щойно зареєстрований учасник
2. Перейдіть до Кабінету.
3. Перейдіть до форми Учасник.
4. Натисніть Додати Документ.
5. Натисніть Обрати Файл

Очікувано: Відкривається вікно вибору файлу.

Фактично: Нічого не відбувається.
![image](https://cloud.githubusercontent.com/assets/11888281/26199972/d33c798c-3bd4-11e7-8ef9-a47b39f01981.png)

**Comment by v-lego** [comment]
Змінено кнопку завантаження документів
![default](https://cloud.githubusercontent.com/assets/24773833/26452543/f63b1d6e-4168-11e7-84ce-e84d70f1aaf1.png)
