### ISSUE TITLE
tovprof: 1-ий участник (переможець) може забрати гарантійний внесок

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1368]
Відтворення:
1 Провести торги до етапу кваліфікації
2 1-им участником перйти на сторінку торгів

очікувано: участник який зайняв перше місце **НЕ** має мати змогу відмовитись від участі

фактично: участник який зайняв перше місце має мати змогу відмовитись від участі

![37 1-](https://cloud.githubusercontent.com/assets/13050207/26206622/04a30950-3bee-11e7-95e1-b2d8ad10fcb5.png)

**Comment by ukrosoft** [comment]
Исправлено
