### ISSUE TITLE
tbetb: Формат телефону при реєстрації не відповідає загальному формату

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1369]
Відтворення:
1 Зареєструвати нового користувача
2 ввести стандартний номер телефону характерний для укр операторів (зразок: +380506070888)

очікувано: система перевіряє загальний формат телефону

фактично: формат телефону який потребує система не є правильним

![1](https://cloud.githubusercontent.com/assets/13050207/26246135/3a362784-3ca0-11e7-8a09-029391b60f21.png)

**Comment by ukrosoft** [comment]
Исправлено на обеих площадках

**Comment by SoftserveQC1** [comment]
Перевірка формату телефону дозвляє ввести невалідний номер
номер повинен строго відповідати українському формату
![1a](https://cloud.githubusercontent.com/assets/13050207/26303538/a1f4da4e-3ef0-11e7-87be-29f4c693dcad.png)

**Comment by ukrosoft** [comment]
Исправлено
