### ISSUE TITLE
Помилка при спробі зареєструвати пропозицію на тендер

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#137]
![registerproposal](https://cloud.githubusercontent.com/assets/11062040/6413609/043f4b28-be9a-11e4-8c9f-3c1754adf910.png)

**Comment by OksanaPakholok** [comment]
Протестовано в Chrome бравзері

**Comment by S-Shevchenko** [comment]
@OksanaPakholok Пожалуйста проверьте.

**Comment by OksanaPakholok** [comment]
Провірено в Сhrome, Firefox, IE, Opera. 
Зараз помилка відтворюється в IE

![error1](https://cloud.githubusercontent.com/assets/11062040/6437602/a73657dc-c0c9-11e4-84fe-13bdf664f141.png)

**Comment by S-Shevchenko** [comment]
Спасибо, Взяли в работу. При прикреплению документов в браузере IE выбрасывает на главную страницу.

**Comment by S-Shevchenko** [comment]
@OksanaPakholok Будь ласка, перевірте.

**Comment by OksanaPakholok** [comment]
03/12/2015, http://services.e-tender.biz:100/#/ Перевірено. Не репродюситься.
