### ISSUE TITLE
tbetb: Дата початку та кінця прийому пропозицій збігаються

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1370]
Відтворення: 
1 Оголосити торги
2 Нажати кнопку опублікувати

Очікувано: аукціон кореткно опублікується зі всіма його даними

фактично: помилка публікації через співпадіння дат та часу початку та кінця прийому пропозицій

![3](https://cloud.githubusercontent.com/assets/13050207/26246739/584a5904-3ca3-11e7-97ec-e9fc8adbf562.png)

**Comment by ukrosoft** [comment]
В неопубликованых аукционах даты больше не отображаются. Ошибка же, приводящая к невозможности опубликовать аукцион на этом скриншоте - неверно заполненный URL в профиле, исправлена добавление контроля формата URL в профиле
