### ISSUE TITLE
tbetb: Повідомлення про успішну реєстрацію користувача не приходить на пошту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1371]
При реєстрації будь якого користувача (ліквідатор, фіз особа, юр особа, фін компанія) повинно приходити повідомлення на пошту, не тільки у особистий кабінет про успішну реєстрацію

Відтворення:
1 зареєструвати користувача
2 перевірити пошту

очікувано: прийшло повідомлення про успішну реєстрацію

фактично: повідомлення відсутнє

![4](https://cloud.githubusercontent.com/assets/13050207/26247037/bebd69fa-3ca4-11e7-9f17-714e4533f085.png)

**Comment by ukrosoft** [comment]
Исправлено
![photo_2017-05-19_16-15-44](https://cloud.githubusercontent.com/assets/16786861/26249255/794a40c8-3cae-11e7-97c8-ff83235ccfa4.jpg)
