### ISSUE TITLE
tbetb: Помилка відображення графічного файлу на сторінці лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1372]
Відтворення:
1 створити лот
2 перейти на сторінку лоту

![5](https://cloud.githubusercontent.com/assets/13050207/26301621/66b60af8-3eea-11e7-8c51-f237611d02be.png)

**Comment by ukrosoft** [comment]
Исправлено: добавили картинку-placeholder для лотов без иллюстрации своей
