### ISSUE TITLE
tbetb: Рекомендовано добавити для участників вкладку в особистому кабінеті для перегляду поданих пропозицій або аукціонів у яких він бере участь

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1373]
Для зручного пошуку аукціонів у яких користувач бере участь, варто створити вкладку в особистому кабінеті, де б відображалися основні дані про аукціон, у якому користувач бере участь, та дані про пропозицію подану на цей аукціон. Відповідно звідки можна було б безпосередньо перейти на сторінку аукціону

**Comment by ukrosoft** [comment]
Сделано
![screenshot_20170522_163709](https://cloud.githubusercontent.com/assets/16786861/26311498/2c21da20-3f0d-11e7-8d58-475cf81fe1ff.png)
