### ISSUE TITLE
tbetb: При спробі подати пропозицію на аукціон в якості юридичної особи, пропозиція не була прийнята

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1374]
**Відтворюється лише для юридичної особи та фінансової компанції**

Відтворення:
1 створити лот
2 подати пропозицію як юридична особа 
3 подати пропозицію як фінансова компанія

очікувано: пропозиція прийнята, користувач має змогу змінити пропозицію

фактично: пропозиція не прийнялась, відображається далі кнопка прийняти пропозицію, аукціон не відбувся

![7](https://cloud.githubusercontent.com/assets/13050207/26305211/104f30f6-3ef7-11e7-8f4d-760bc1e354aa.png)
![7](https://cloud.githubusercontent.com/assets/13050207/26305212/104f7ab6-3ef7-11e7-8dbd-b131edebe210.png)

**Comment by SoftserveQC1** [comment]
**Тепер відтворюється для всіх типів участників**

**Comment by ukrosoft** [comment]
Исправлено, проблема возникала если у аккаунта не был указан телефон
