### ISSUE TITLE
tbetb: Відсутня перевірка наявності документа про те що участник не є позичальником, для фізичних та юридичних осіб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1375]
**Дана перевірка повинна бути присутня лише для фізичних та юридичних осіб**

Відтворення:
1 Створити лот фінансовий актив
2 подати пропозицію як юридична особа
3 подати пропозицію як фізична особа

очікувано: відбувається перевірка наявності документа про те що участник не є позичальником

фактично: перевірка відсутня
![8](https://cloud.githubusercontent.com/assets/13050207/26311520/42b64a50-3f0d-11e7-9bd6-591f7146324b.png)

**Comment by ukrosoft** [comment]
Добавили возможность загрузить документ в момент подачи ставки
![screenshot_20170523_002502](https://cloud.githubusercontent.com/assets/16786861/26329126/64d76bfa-3f4e-11e7-8a5b-c283f91e28b0.png)
