### ISSUE TITLE
tbetb: відсутня нотифікація про успішне завантаження договору

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1378]
Також відсутня можливість завантажити договір (договір повинен бути у вільному доступі)

Відтворення:
1 провести торги
2 звернути увагу на процес завантаження договору

очікувано: після завантаження користувачу на екран відображається повідомлення типу "договір успішно завантажений" чи щось на кшталт

фактично: до кінця незрозуміло чи договір завантажився

**скрін після завантаження договору(ніяких нотифікацій немає)**
![11](https://cloud.githubusercontent.com/assets/13050207/26315110/bef1f5f0-3f18-11e7-99be-464b55af2dc7.png)
**сторінка лоту, де можна було б завантажити договір**
![12](https://cloud.githubusercontent.com/assets/13050207/26315111/bef1e998-3f18-11e7-8d80-543a8e21f878.png)

**Comment by ukrosoft** [comment]
Исправлено

**Comment by SoftserveQC1** [comment]
акутально, нічого не змінилося, договора на сторінці аукціону нема, користувачу ніяких нотифікацій що договір завантажився не показує

**Comment by ukrosoft** [comment]
![photo_2017-05-24_18-10-32](https://cloud.githubusercontent.com/assets/16786861/26410548/573730f2-40ac-11e7-8e95-afa624da0ccb.jpg)
исправлено!
