### ISSUE TITLE
tbetb: 2-ий участник може забрати гарантійний внесок після завершення аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1379]
Відтворення:
1 провести успшні торги
2 2-им участником зайти на сторінку лоту

![12 -](https://cloud.githubusercontent.com/assets/13050207/26315696/9ee8b8e6-3f1a-11e7-9723-a76b1831eb6e.png)

**Comment by ukrosoft** [comment]
Убрали кнопку "забрати внесок" у завершенных аукционов
