### ISSUE TITLE
Тендер залишається в статусі "Зачекайте, закупівля обробляється " більше 20 хв

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#138]
![waiting](https://cloud.githubusercontent.com/assets/11062040/6413836/d2a92d16-be9b-11e4-8da3-3517ffb757ca.png)

**Comment by S-Shevchenko** [comment]
@OksanaPakholok  Заказчик еще создавал тендера? Они тоже провалились?

**Comment by OksanaPakholok** [comment]
Так замовник створив ще один тендр, але він не провалився

**Comment by OksanaPakholok** [comment]
Уточнення: Попередній комент відносився до іншого замовника, якщо створити тендер цим самим замовником, то новий тендер знову залишається у статусі "Зачекайте, закупівля обробляється "

![2_proposal](https://cloud.githubusercontent.com/assets/11062040/6414913/d751264a-bea3-11e4-8df7-f19fb266dfc5.png)

**Comment by S-Shevchenko** [comment]
@OksanaPakholok  Можна скинуть логин и пароль  заказчика ? Спасибо.

**Comment by OksanaPakholok** [comment]
Так можна
login: taraspr
password: tarasPR123

**Comment by S-Shevchenko** [comment]
@OksanaPakholok Пожалуйста проверьте.

**Comment by OksanaPakholok** [comment]
Проблема актуальна в Chrome бравзері

![waiting1](https://cloud.githubusercontent.com/assets/11062040/6437864/5e610bda-c0cc-11e4-8987-94be1d25c24e.png)

**Comment by S-Shevchenko** [comment]
@OksanaPakholok Спасибо. Связана с валидацией url в profile. Пожалуйста поменяйте на валидный урл http://www.mystart.com/

**Comment by OksanaPakholok** [comment]
Дякую, перетестовано. Не репродюситься. Можна закривати

**Comment by S-Shevchenko** [comment]
Спасибо, закрываем.
