### ISSUE TITLE
Agrex: Непотрібне повідомлення з`являється під час реєстрації користувача

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1380]
**Майданчик:** https://sale.agrex.gov.ua/test/

**Кроки для відтворення:**
1. Перейдіть на сторінку реєстрації - https://sale.agrex.gov.ua/test/Registration.aspx?&type=registration
2. Введіть усі коректні дані в поля реєстрації, погодьтеся з умовами
3.  Натисніть Зареєструватися

**Фактичний результат:** Повідомлення "Ссылка на объект не указывает на экземпляр объекта." з`являється. Користувач зареєстравоний.

**Очікуваний результат:** Користувач реєстрований, повідомлення про успішну реєстрацію відображається.
![image](https://cloud.githubusercontent.com/assets/13050207/26343006/ff288190-3fa2-11e7-9f76-835c55af1ae5.png)

**Comment by AlexGr7** [comment]
внесено зміни щодо реєстрації користувача
