### ISSUE TITLE
tabua: Можливо встановити мінімальний крок аукціону нижче 1%

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1381]
http://staging_sale.tab.com.ua

**Відтворення:** 
1) Залогінитись tab-likvidator@yopmail.com
2) Перейти до створення аукціону (Мій кабінет->Мої аукціони-> Створити новий аукціон)
3) Забовнити всы поля валыдними даними
4) В поле "Мінімальний крок аукціону, %" встановити значення 0.1
5) Опублікувати аукціон

**Очікуваний результат:** Аукціон не опубліковано, бо мінімальний крок аукціону має ставновити від 1% (включно) до 100% (включно) від початкової ціни продажу

**Фактичний результат:** Аукціон опубліковано із кроком 0.1%
![default](https://cloud.githubusercontent.com/assets/13050207/26349698/37aed454-3fb9-11e7-8529-b993e0520f2d.png)

**Comment by Givandos** [comment]
Пофікшено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![default](https://cloud.githubusercontent.com/assets/13050207/26358146/4075d21a-3fda-11e7-89ad-b440766e66da.png)
