### ISSUE TITLE
tabua: Відсутня функціональність заміни документів в опублікованому аукціоні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1382]
http://staging_sale.tab.com.ua/

**Опис:** Відсутня функціональність заміни документів у опублікованому аукціоні, можливо лише додати документ

**Відтворення:**
1) Залогінитись користувачем tab-likvidator@yopmail.com
2) Перейти до створення аукціону (Мій кабінет->Мої аукціони-> Створити новий аукціон)
3) Заповнити всі поля валідними даними, додати кілька документів та натиснути "Опублікувати"
4) У тілі аукціону натиснути "Змінити"
6) Сбробувати замінити документи

**Очікуваний результат:** Можливо замінити документи до аукціону, стара версія документу відображається перекресленою при перегляді аукціону

**Фактичний результат:** Неможливо замінити документи, лише додати

**Comment by SoftserveQC1** [comment]
При відображенні опублікованих документів вони усі ідуть у розділі Фотографії і їх не підписано, що призводить до складнощів безпосередньо пов'язаних із описаним дефектом
![default](https://cloud.githubusercontent.com/assets/13050207/26350931/f1c06a52-3fbd-11e7-8b35-712dd8375c99.png)

**Comment by SoftserveQC1** [comment]
Заміну документів додано, але вимога "стара версія документу відображається перекресленою при перегляді аукціону" для учасника не виконана, Учасник як і раніше бачить усі документи
1) Для ліквідатора при заміні документів
![1](https://cloud.githubusercontent.com/assets/13050207/26442321/b1930ae0-413c-11e7-8be5-686971410a02.png)
2) При перегляді учасниками лоту
![2](https://cloud.githubusercontent.com/assets/13050207/26442320/b190f3c2-413c-11e7-972d-df9537bef682.png)

**Comment by Givandos** [comment]
Додано перекреслення старих документів.

**Comment by SoftserveQC1** [comment]
Будь ласка, змініть підпис документів на україномовний, та зробіть трохи більші відступи між рядками зображень, бо нижні зображення перекривають назви верхніх
Прошу прибрати лейб important
![default](https://cloud.githubusercontent.com/assets/13050207/26450788/d1fd3f42-4161-11e7-8a23-7a54b23dd574.png)

**Comment by Givandos** [comment]
http://staging_sale.tab.com.ua/auctions/8f37edfa66589de94974e5dee62b22e6
Виправлено

**Comment by SoftserveQC1** [comment]
Виправлено
