### ISSUE TITLE
tbetb: Посилання які є в листі, що приходять на пошту відкриваються з помилкою

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1383]
Відтворення:
1 Запустити лот
2 задати питання по ньому 
3 завантажити документ
4 зробити ще якісь дії після яких приходить повідомлення на пошту
5 перевірити ссилку в повідомленні

очікувано: відкриється ссилка на лот

фактично: помилка
![13](https://cloud.githubusercontent.com/assets/13050207/26356971/8d896084-3fd6-11e7-85ca-f779186c0e98.png)

**Comment by ukrosoft** [comment]
Поправили генерацию ссылок в письмах
