### ISSUE TITLE
tbetb: торги відображаються у статусі завантаження договору, а насправді перебувають на етапі завантаження протоколу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1384]
Відтворення:
1 провести торги до етапу завантаження протоколу
2 звернути увагу на дані про лот на сторінці лоту

![15](https://cloud.githubusercontent.com/assets/13050207/26357543/451a0950-3fd8-11e7-8727-722a347709e6.png)

**Comment by ukrosoft** [comment]
Исправлено сообщение
![photo_2017-05-23_18-19-48](https://cloud.githubusercontent.com/assets/16786861/26361704/75134f16-3fe4-11e7-8ee2-aba4699dd59d.jpg)
