### ISSUE TITLE
tbetb: 2-ий участник не має змоги забрати свій внесок під час етапу кваліфікації

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1385]
кнокпка "забрати внесок" повинна бути присутня лише під час етапу кваліфікацї, як тільки з переможцем укладено договір, наявність кнокпи не несе змісту, оскільки внесок і так буде повернено

Відтворення:
1 провести торги до етапу кваліфікації
2 2-им участником зайти на сторінку лоту

очікувано: наявна конпка "забрати внесок"

фактично: кнопка відсутня
![14](https://cloud.githubusercontent.com/assets/13050207/26357614/7ee155f8-3fd8-11e7-8578-bc1980f50f89.png)

**Comment by ukrosoft** [comment]
Исправлено, на скриншотах кнопка у второго участника и результат после ее нажатия (меняется статус участника в списке участников)
![photo_2017-05-19_16-15-44](https://cloud.githubusercontent.com/assets/16786861/26361668/539a73dc-3fe4-11e7-9705-7d99a1787373.jpg)
![photo_2017-05-23_18-17-44](https://cloud.githubusercontent.com/assets/16786861/26361672/56f81944-3fe4-11e7-8123-ff259f83d999.jpg)
