### ISSUE TITLE
tbetb: 2 участника дискваліфікуються одночасно після не завантаження протоколу для 1-го

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1386]
Відтворення:
1 провести торги до етапу завантаження протоколу
2 не завантажувати протокол
3 дочекатись доки система сама дискваліфікує участника

очікувано: система дискваліфіковує лише 1-го участника, а 2-го згодом (3 доби не враховуючи акселератор) якшо не завантажувати протокол

фактично: одночасна дискваліфікація двох участників

![17](https://cloud.githubusercontent.com/assets/13050207/26357881/6589e574-3fd9-11e7-897f-c678e1c755f6.png)

**Comment by ukrosoft** [comment]
Проблема возникла из-за слишком большого значения accelerator (1440), поменяли на 300
