### ISSUE TITLE
tabua: В формі скасування аукціону відсутній дроп-бокс/чек-бокси для вказання можливих причин скасування

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1387]
http://staging_sale.tab.com.ua/

**Опис:** В формі скасування аукціону відсутній дроп-бокс/чек-бокси для вказання можливих причин скасування, присутнє лише поле для ручного вводу причини скасування. Можна поле зробити не обов'язковим або прибрати, а додати можливість вибору однієї із двох можливих причин відміни аукціону ("Згідно рішення виконавчої дирекції Фонду гарантування вкладів фізичних осіб" або "Порушення порядку публікації оголошення")

**Відтворення:**
1) Залогінитись користувачем tab-likvidator@yopmail.com
2) Перейти до створення аукціону (Мій кабінет->Мої аукціони-> Створити новий аукціон)
3) Заповнити всі поля валідними даними, додати кілька документів та натиснути "Опублікувати"
4) У тілі аукціону натиснути "Відмінити"
5) Переглянути вікно Скасування аукціону

**Очікуваний результат:** Має бути присутній обов'язковий дроп бокс для вказання одного з двох типів причин скасування, згідно [Тестові сценарії, рівень 1 (Організатор) п3](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#):
   - Згідно рішення виконавчої дирекції Фонду гарантування вкладів фізичних осіб
   - Порушення порядку публікації оголошення 

**Фактичний результат:** Можливо лише вказати причину вручну відмови у відповідному полі
![_001](https://cloud.githubusercontent.com/assets/13050207/26398761/30359526-4083-11e7-860e-8699a7ee153f.png)

**Comment by Givandos** [comment]
Змінено на випадаючий список.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![default](https://cloud.githubusercontent.com/assets/13050207/26448037/f705d438-4153-11e7-9922-57d002db11b0.png)
