### ISSUE TITLE
tbetb: кнопка для 2-го участника зникає після підтвердження оплати для 1-го участника 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1388]
Відтворення:
1 провести торги до етапу кваліфікації
2 завантажити договір і підтвердити оплати для 1-го участника
3 2-им участник перейти на сторінку лоту

очікувано: 2-ий участник має змогу забрати внесок на етапі завантаження договору (для 1-го участника)

фактично: кнопка "забрати внесок відсутня на етапі" завантаження договору
![18](https://cloud.githubusercontent.com/assets/13050207/26404165/8fd05dfc-4099-11e7-8e6a-c78877080a22.png)

**Comment by ukrosoft** [comment]
исправлено!
