### ISSUE TITLE
tbetb: Граматична помилка в повідомлення про завершення аукціону 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1389]
Помилка присутня в повідомленнях у особистому кабінету та на пошті
Помилка відтворюється для всіх троьх варіантів завершення торгів
-торги відмінено
-аукціон не відбувся
-завершений

Відтворення:
1 провести торги до завершення 
2 звернути увагу на повідомлення в особистому кабінету та на пошті
![20](https://cloud.githubusercontent.com/assets/13050207/26407770/a99ec114-40a4-11e7-8078-c09acd505a55.png)
![20](https://cloud.githubusercontent.com/assets/13050207/26407771/a9f67738-40a4-11e7-9f9d-150e49faa210.png)

**Comment by ukrosoft** [comment]
исправлено
![photo_2017-05-24_17-22-10](https://cloud.githubusercontent.com/assets/16786861/26408124/a4af7a9e-40a5-11e7-8041-5e95d4ada0b6.jpg)
