### ISSUE TITLE
Помилка при спробі додати документ до тендера і статусі "Період уточнень"

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#139]
![cannotadddoc](https://cloud.githubusercontent.com/assets/11062040/6414286/ddb3c90c-be9e-11e4-8247-e5fb662b092a.png)

**Comment by S-Shevchenko** [comment]
Спасибо. Знаем.

**Comment by S-Shevchenko** [comment]
Не воспроизводиться

**Comment by lerich** [comment]
Закриваю.

**Comment by OksanaPakholok** [comment]
Прошу перевідкрити. Протестовано в Chrome, Firefox, IE, та Оpera. 
Досі репродюситься в IE

![no_uploading_ie](https://cloud.githubusercontent.com/assets/11062040/6438441/a2b1770c-c0d1-11e4-827c-a3dc358b67bd.png)

**Comment by OksanaPakholok** [comment]
@lerich
