### ISSUE TITLE
tbetb: При публікації(укладанні) договору відсутні поля для вказання номеру договору та дати підписання

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1392]
Обовязкові для заповнення поля **"Номер договору"** та **"Дата підписання"** під час опубліковування (укладання) договору

Відтворення:
1 Провести торги до завантаження договору
2 Завантажити договір
3 звернути увагу на відсутність необхідних полів

Очікувано: Після завантаження договору необхідно заповнити дані  вказаних полів, після заповнення яких договір можна буде укласти

фактично: поля відсутні, система завершує торги просто після завантаження
![22](https://cloud.githubusercontent.com/assets/13050207/26413015/4dd05154-40b3-11e7-87cf-02d075e5873a.png)

**Comment by ukrosoft** [comment]
Поля добавлены

**Comment by ukrosoft** [comment]
![photo_2017-05-25_12-24-33](https://cloud.githubusercontent.com/assets/16786861/26444452/2e265e2e-4145-11e7-8006-3f7e4517c1ee.jpg)
![photo_2017-05-25_12-24-42](https://cloud.githubusercontent.com/assets/16786861/26444457/2f954dd8-4145-11e7-8f12-2efe8f571f9d.jpg)
![photo_2017-05-25_12-24-48](https://cloud.githubusercontent.com/assets/16786861/26444461/31723c92-4145-11e7-9cea-4d5c8deeb4c7.jpg)
