### ISSUE TITLE
tabua: Відсутня функціональність повідомлення Учасників у особистому кабінеті

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1393]
http://staging_sale.tab.com.ua/

**Опис:** Відсутня функціональність повідомлення Учасників у особистому кабінеті згідно [Ручних тестів](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.eye0w8ma7zvx). Мають бути наступні повідомлення:
1) <del>про успішну/неуспішну активацію/валідацію Учасників</del>
2) <del>про запитання до Лоту (Ліквідатору)</del>
3) <del>нагадування (щодня) про запитання без відповіді до Лоту (Ліквідатору)</del>
4) <del>прийняття/відхилення пропозиції Учасника Майданчиком та перевірку гарантійного внеску/банківської гарантії</del>
5) <del>посилання на модуль електронного аукціону (Учасникам які зробили ставки)</del>
6) <del>про скасування Аукціону, на який Учасник задавав запитання чи подавав пропозиції</del>
7) про результати Аукціону, на який Учасник подавав пропозиції (для Уч1 та Уч2)
8) <del>про визнання Учасника переможцем аукціону, та необхідність прикріпити протокол торгів протягом 3х діб (Уч1, Ліквідатору)</del>
9) <del>про визнання Учасника Кандидатом наступним за переможцем (Уч2)</del>
10) <del>про повернення Учасником наступним за переможцем гарантійного внеску (Ліквідатору)</del>
11) <del>про перехід кваліфікаці до Учасника наступного за переможцем у разі дискваліфікації переможця (Ліквідатору, Уч2)</del>
12) <del>про дискваліфікацію учасника (Учаснику якого дискваліфіковано)</del>
13) <del>про відповідь на поставлене питання (Учаснику який поставив питання до лоту)</del>

**Очікуваний результат:** Користувач отримує перелічені в описі повідомлення в особистому кабінеті, усі повідомлення відповідають вимогам "Отримати повідомлення в особистому кабінеті Організатора при наступному вході в нього. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до Лоту.

**Фактичний результат:** Повідомлення в особистому кабінеті не реалізовані на майданчику

**Comment by Givandos** [comment]
Виправлено та допрацьовано.

**Comment by SoftserveQC1** [comment]
Повідомлення мають наступний вигляд
![default](https://cloud.githubusercontent.com/assets/13050207/26580928/eb32bdd6-4542-11e7-949b-9c9954c6c583.png)
![2](https://cloud.githubusercontent.com/assets/13050207/26580929/eb4f192c-4542-11e7-9539-6398e44a1b19.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
