### ISSUE TITLE
tabua: Переможець торгів не може прикріпити протокол результатів електронного аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1394]
http://staging_sale.tab.com.ua/

**Опис:** На етапі кваліфікації відсутня можливість додати протокол результатів електронного аукціону Переможцем аукціону

**Відтворення:**
1) Залогінитись користувачем tab-likvidator@yopmail.com
2) Перейти до створення аукціону (Мій кабінет->Мої аукціони-> Створити новий аукціон)
3) Заповнити всі поля валідними даними, додати кілька документів та натиснути "Опублікувати"
5) Залогінитись користувачем tab-fizosoba@yopmail.com
6) Зробити ставку до аукциону у розмірі початкова вартість+мін. крок (Аукціон->Подати заявку)
7) Залогінитись користувачем tab-yurosoba@yopmail.com
6) Зробити ставку до аукциону у розмірі початкова вартість+мін. крок (Аукціон->Подати заявку)
8) Дочекатися початку етапу кваліфікації
9) Перейти переможцем до аукціону та переглянути можливість додати протокол торгів

**Очікуваний результат:** Кандидат може завантажити до документів підписаний протокол результатів електронного аукціону

**Фактичний результат:** Неможливо завантажити протокол результатів електронного аукціону
![1](https://cloud.githubusercontent.com/assets/13050207/26450220/f0298a50-415e-11e7-9054-9a4ebf2c30fc.png)
![2](https://cloud.githubusercontent.com/assets/13050207/26450221/f02bd382-415e-11e7-80a3-07ae6b448162.png)

**Comment by Givandos** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![default](https://cloud.githubusercontent.com/assets/13050207/26578889/52d94f08-453a-11e7-8ebe-b62b7b039660.png)
