### ISSUE TITLE
tabua: На етапі підписання договору неможливо дискваліфікувати Учасника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1395]
http://staging_sale.tab.com.ua/

**Опис:** На етапі підписання договору неможливо дискваліфікувати Учасника. Ліквідатору з'являється повідомлення, що на даному статусі аукціону неможливо додавати документи

**Передумова:**
- Залогінитись користувачем tab-likvidator@yopmail.com
- Перейти до створення аукціону (Мій кабінет->Мої аукціони-> Створити новий аукціон)
- Заповнити всі поля валідними даними, додати кілька документів та натиснути "Опублікувати"
- Залогінитись користувачем tab-fizosoba@yopmail.com
- Зробити ставку до аукциону у розмірі початкова вартість+мін. крок (Аукціон->Подати заявку)
- Залогінитись користувачем tab-yurosoba@yopmail.com
- Зробити ставку до аукциону у розмірі початкова вартість+мін. крок (Аукціон->Подати заявку)
- Дочекатися початку етапу кваліфікації

**Відтворення:**
1) Прикріпити протокол торгів Ліквідатором (Аукціон->Завантажити протокол)
2) Підтвердити оплату Переможцем (Аукціон->Підтвердити оплату)
3) Дискваліфікувати переможця (Відхилити пропозицію->Заповнити причину та додати документ)

**Очікуваний результат:** Учасника дискваліфіковано, кваліфікація починається для другого кандидата

**Фактичний результат:** Учасника не дискваліфіковано, з'являється еррор-повідомлення
![default](https://cloud.githubusercontent.com/assets/13050207/26450393/d812c728-415f-11e7-8ea3-c01a53ff8a43.png)

**Comment by Givandos** [comment]
Виправлено не обов"язковістю додавання файлу.
Зі сторони ЦБД це невеличкий баг, тому повністю функціонал (мається на увазі додавання файлу) не прибирали з форми, спробуємо знайти/дочекатись рішення.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
