### ISSUE TITLE
vidrodzhennia: Неможливо виставити параметр "Лоти висталяються", через що неможливо створити аукціон

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1404]
https://e.tbv.com.ua/auction/

**Опис:** При створенні аукціону неможливо виставити параметр "Лоти висталяються" бо воно фіксоване, через що неможливо створити аукціон, з'являється помилка з вимогаю виставити значення параметру "Лоти висталяються"

**Відтворення:**
1) Залогінитись користувачем vidr-likvidator@yopmail.com
2) Натиснути кнопку "Новий аукціон"
3) Заповнити всі необхідні поля
4) Натиснути кнопку "Зберегти"

**Очікуваний результат:** Параметр "Лоти висталяються" можливо виставити згідно [ручних тестів](https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.eye0w8ma7zvx)

**Фактичний результат:** Параметр "Лоти висталяються" виставити не можливо, він виглядає фіксованим, а при спробі зберегти чернетку із заповненими іншими необхідними даними майданчик видає помилку, таким чином створити аукціон неможливо
![default](https://cloud.githubusercontent.com/assets/13050207/26496365/e41f737e-422f-11e7-853f-ebbc5264dc6f.png)

**Comment by v-lego** [comment]
Сторінку оновлено
![default](https://cloud.githubusercontent.com/assets/24773833/26498344/6bb095c8-4237-11e7-9f70-979f65f28054.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
після Ctrl + F5
