### ISSUE TITLE
vertas: Позначка обовязковості заповнення поля, перенесена на наступний рядок у назві поля

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1406]
Відтворення:
1 Відкрити форму реєстрації
2 звернути увагу на поле "Адреса у населенному пункті"

очікувано: знак "*" знаходиться у тому ж рядку що і назва

фактично: знак "*" пенесено на наступний рядок
![1](https://cloud.githubusercontent.com/assets/13050207/26547041/b4f4725a-4475-11e7-9e7a-2ffe98bf409f.png)

**Comment by v-lego** [comment]
просимо оновити сторінку
![default](https://cloud.githubusercontent.com/assets/24773833/26569333/b1c12b44-4512-11e7-97b1-401216b75579.png)
