### ISSUE TITLE
vertas: типи документів "Договір NDA" та "посилання VDR" повинні бути відсутні для майна банків

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1407]
Відтворення:
1 оголосити аукціон з майна банків
2 додати документ
3 звернути увагу на типи документів які відображаються у спадному списку

очікувано: типи документів "Договір NDA" та "посилання VDR" повинні бути відсутні для майна

фактично: типи документів "Договір NDA" та "посилання VDR" присутні для майна
![3 nda i vdr](https://cloud.githubusercontent.com/assets/13050207/26547141/38e728aa-4476-11e7-959a-571cdcb4cec9.png)

**Comment by v-lego** [comment]
Внесено зміни, просимо оновити сторінку
