### ISSUE TITLE
vertas: При доданні документу "публічний паспорт активу" до лоту, не відображається його тип 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1409]
Відтворення:
1 створити лот, опублікувати
2 завантажити тип документу "публічний паспорт активу"

Очікувано: назва даного типу документу відображається біля документу

фактично: назва не відображається
![4](https://cloud.githubusercontent.com/assets/13050207/26548037/b1591dc6-447a-11e7-8cd6-a461f59863be.png)
![4](https://cloud.githubusercontent.com/assets/13050207/26548038/b15a9818-447a-11e7-84dd-edb9fc946a42.png)

**Comment by v-lego** [comment]
Внесено зміни до довідника типів документів
https://sale.vertas.com.ua/test/Auction.aspx?CN=0&id=24e2de3ee5434de5b520d40895796ee2
![default](https://cloud.githubusercontent.com/assets/24773833/26569215/f4e4e1f0-4511-11e7-96cc-d9d493fd1bb6.png)
