### ISSUE TITLE
ЕЛЕГ, у Firefox та IE бравзерах немає прев'ю документа при друкуванні

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#141]
![print_ff_ie](https://cloud.githubusercontent.com/assets/11062040/6465280/ce92a0a6-c1c8-11e4-80f0-e0e14413034d.png)

![print_chrome_opera](https://cloud.githubusercontent.com/assets/11062040/6465289/d8b08260-c1c8-11e4-881b-308f49eda887.png)

Протестовано 03/03/2015 у Firefox, IE, Opera та Chrome бравзерах
на http://services.e-tender.biz:100/#/

**Comment by S-Shevchenko** [comment]
Можно, закрывать.
