### ISSUE TITLE
vertas: При спробі оновити документ на формі відображається некоректна назва шляху до файлу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1410]
Відображається шлях до документа який був завантажений останній

Відтворення: 
1 Оголосити торги
2 додати декілька документів (мінімум 3)
3 нажати кнопку "оновити"
4 звернути увагу на шлях яких відображається на формі
![5](https://cloud.githubusercontent.com/assets/13050207/26548118/2970e730-447b-11e7-86c4-284e179fd106.png)
![5](https://cloud.githubusercontent.com/assets/13050207/26548119/2970fbc6-447b-11e7-8aab-7e726dc702ec.png)

**Comment by v-lego** [comment]
![default](https://cloud.githubusercontent.com/assets/24773833/26555375/629dc650-449d-11e7-8dda-1d3dcb488ccd.png)
Оновлено форму : відображується тільки ім'я файлу
