### ISSUE TITLE
vertas: При скасуванні лоту немає спадного списку для вибору причини скасування

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1411]
При скасуванні лоту ліквідатор повинен вказати причину зі спадаючого списку:
- Згідно рішення виконавчої дирекції Фонду гарантування вкладів фізичних осіб
- Порушення порядку публікації оголошення 
При цьому можуть бути присутні додаткові поля

Відтворення:
1 Оголосити лот
2 скасувати лот
3 звернути увагу на форму скасування лоту

очікувано: присутній спадний список з вказаними опціями

фактично: список відсутній
![6](https://cloud.githubusercontent.com/assets/13050207/26548254/eb2d11aa-447b-11e7-8e06-5086f9afbc9d.png)

**Comment by v-lego** [comment]
Встановлено вибір зі списку
![default](https://cloud.githubusercontent.com/assets/24773833/26569768/557143a8-4515-11e7-8330-09fd90c26a36.png)
