### ISSUE TITLE
vertas: Посилання на аукціон не приходить на пошту участників

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1413]
посилання приходить лише в особистий кабінет

Відтворення:
1 Оголосити торги 
2 подати пропозиції
3 дочекатись встановлення дати та часу проведення аукціону

очікувано: на пошту участників приходить повідомлення з посилання на аукціон

фактично: повідомлення з посиланням відсутнє
![8](https://cloud.githubusercontent.com/assets/13050207/26548764/6834fc56-447e-11e7-8290-4c5b0f66f95a.png)
![8](https://cloud.githubusercontent.com/assets/13050207/26548765/68379e3e-447e-11e7-9e46-ca6826a4098d.png)

**Comment by v-lego** [comment]
Змінено параметри надсилання листів
