### ISSUE TITLE
vertas: Дані які відображаються під час та після кваліфікації логічно невпорядковані 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1414]
Дані які відображаються під час та після кваліфікації логічно невпорядковані та не вирівняні.
Користувач не одразу зрозуміє яка інформація чого стосується.
Рекомендовано деякі дані структурувати та відоокремити від інших

Відтворення:
1 Провести торги до етапу кваліяікації
2 1-го участника дискваліфікувати
3 2-го визнати переможцем

очікувано: вся інформація логічно впорядкована, вирівняна та відображається структуровано
![10](https://cloud.githubusercontent.com/assets/13050207/26550147/11ed1728-4485-11e7-9dc4-eda62a73ac23.png)
![10](https://cloud.githubusercontent.com/assets/13050207/26550148/11ee2bb8-4485-11e7-9c91-76c2a65878fd.png)
![10](https://cloud.githubusercontent.com/assets/13050207/26550146/11ed295c-4485-11e7-958f-55f876da0b18.png)

**Comment by v-lego** [comment]
Проведено переформатування елементів
![default](https://cloud.githubusercontent.com/assets/24773833/26569091/19aceb1e-4511-11e7-8a1c-e1bc84db0a40.png)
