### ISSUE TITLE
vertas: накладання елементів при поданні пропозиції

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1415]
Відтворення:
1 Оголосити торги
2 спробувати подати пропозицію
З Звернути увагу на накладення елементів
![11](https://cloud.githubusercontent.com/assets/13050207/26550630/45a56bea-4487-11e7-8052-dc6a0e9a198e.png)

**Comment by v-lego** [comment]
Змынено розташування
![default](https://cloud.githubusercontent.com/assets/24773833/26571831/4f4080ec-4520-11e7-88ec-285cd0b67d4a.png)
