### ISSUE TITLE
vertas: Тип документу "додатки до договору" не відображає своєї назви типу після завантаження

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1416]
Відтворення:
1 Провести торги до етапу кваліфікації
2 Завантажити протокол, підтвердити оплату
3 Завантажити документ "додатки до договору"
4 звернути увагу на відображення інформації про завантажений тип документу

очікувано: відображається назва типу документу

фактично: назва типу документу не відображається
![12](https://cloud.githubusercontent.com/assets/13050207/26553545/c92ab90e-4494-11e7-846c-33047d1e8897.png)

**Comment by v-lego** [comment]
Внесено зміни до довідника
![default](https://cloud.githubusercontent.com/assets/24773833/26568910/a8b3809a-450f-11e7-865f-a492db15f106.png)
