### ISSUE TITLE
tabua: Можливо задвоїти аукціон змінюючи його поля під час публікації

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1417]
http://staging_sale.tab.com.ua/

**Опис:** Можливо задвоїти аукціон змінюючи його поля під час публікації. **!!ВАЖЛИВО!! Дефект відтворюється лише коли до аукціону додано багато документів, через що є час щоб просколити сторінку до полів (наприклад "дата проведення аукціону") і змінити значення**

**Відтворення:**
1) Залогінитись користувачем tab-likvidator@yopmail.com
2) Перейти до створення аукціону (Мій кабінет->Мої аукціони-> Створити новий аукціон)
3) Заповнити всі поля валідними даними 
4) Додати **!усі можливі!** типи документів та натиснути "Опублікувати"
5) Проскролити сторінку до поля "Дата проведення аукціону" та змінити значення (Поки публікація не відбулась)
6) Дочекатися опублікування аукціону
7) Переглянути список аукціонів

**Очікуваний результат:** Аукціон успішно опубліковано з даними на момент натискання кнопки "Опублікувати"

**Фактичний результат:** Аукціон має "клона" який не може редагувати Ліквідатор,на який можна робити ставки, котрі будуть приймати участь у подальшому аукціоні
![default](https://cloud.githubusercontent.com/assets/13050207/26575389/aa98965c-452d-11e7-9a7f-0b3d0c04000f.png)
Відео-відтворення: https://www.screencast.com/t/CrzF1FT09

**Comment by scoolic** [comment]
@w-be Витя, этот дефект уже закрыт?

**Comment by SoftserveQC1** [comment]
Відмінено роль Ліквідатора.
