### ISSUE TITLE
Адреса учасника

### ISSUE THREAD

**Issue by prozorro-support** [openprocurement/frontend#142]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [21](https://prozorro.zendesk.com/agent/#/tickets/21)
**Priority:** normal
**Zendesk assignee:** Служба підтримки/A

**Original ticket content:**

Вітання,

https://api.openprocurement.org/api/0.6/tenders/1cc3856fed764f7b9b985e11012cb3f6/bids/974c9dc9a2bc49b6a179573de3f230aa має всю адресу в одному полі streetAddress:

{
"countryName": "Україна",
"locality": "",
"postalCode": "",
"region": "",
"streetAddress": "42009, Сумская обл., г. Ромны, ул. Маяковского, 49А"
}

Очікувана структура адреси:
{
"countryName": "Україна",
"locality": "м.Ромни",
"postalCode": "42009",
"region": "Сумська обл.",
"streetAddress": "вул. Маяковського, 49А"
}

Мирослав

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-03-03 15:55:42 UTC:_

<p>Вітання,</p>

<p><a href="https://api.openprocurement.org/api/0.6/tenders/1cc3856fed764f7b9b985e11012cb3f6/bids/974c9dc9a2bc49b6a179573de3f230aa" rel="nofollow" target="_blank">https://api.openprocurement.org/api/0.6/tenders/1cc3856fed764f7b9b985e11012cb3f6/bids/974c9dc9a2bc49b6a179573de3f230aa</a> має всю адресу в одному полі streetAddress:</p>

<p>{
<br />&quot;countryName&quot;: &quot;Україна&quot;,
<br />&quot;locality&quot;: &quot;&quot;,
<br />&quot;postalCode&quot;: &quot;&quot;,
<br />&quot;region&quot;: &quot;&quot;,
<br />&quot;streetAddress&quot;: &quot;42009, Сумская обл., г. Ромны, ул. Маяковского, 49А&quot;
<br />}</p>

<p>Очікувана структура адреси:
<br />{
<br />&quot;countryName&quot;: &quot;Україна&quot;,
<br />&quot;locality&quot;: &quot;м.Ромни&quot;,
<br />&quot;postalCode&quot;: &quot;42009&quot;,
<br />&quot;region&quot;: &quot;Сумська обл.&quot;,
<br />&quot;streetAddress&quot;: &quot;вул. Маяковського, 49А&quot;
<br />}</p>

<p>Мирослав</p>

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-03-03 17:07:37 UTC:_

<p>Цей bid прийшов з IT-Enterprise (smarttender.biz), то ж &quot;закидую&quot; цю задачу їм.</p>

**Comment by w-be** [comment]
Зараз адреса записується добре.
