### ISSUE TITLE
vertas: На сторінці аукціону відображається зайвий номере телефону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1421]
Відтворення:
1 Оголосити торги
2 На сторінці торгів звернути увагу на пункт "телефон"
![16](https://cloud.githubusercontent.com/assets/13050207/26586348/971c0062-4557-11e7-8abc-ab2d6d7da520.png)

**Comment by v-lego** [comment]
Внесено зміни, потребує оновлення сторінки
![default](https://cloud.githubusercontent.com/assets/24773833/26588193/3f6f1b46-455d-11e7-9e79-a7519d1ff3c7.png)
