### ISSUE TITLE
vertas: Не видно чекбокс біля "Гарантійний внесок буде сплачено" при поданні пропозиції

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1422]
Відтворення:
1 Оголосити торги
2 подати пропозицію
3 звернути увагу на поле "Гарантійний внесок буде сплачено"

очікувано: біля поля наявний і видно чекбокс

фактично: **чекбокс є але його не видно**
![17](https://cloud.githubusercontent.com/assets/13050207/26621784/993a9a18-45f0-11e7-9aac-a3bf3eedaa1a.png)
![17](https://cloud.githubusercontent.com/assets/13050207/26621785/993e8a88-45f0-11e7-902f-b24065ed776a.png)

**Comment by v-lego** [comment]
Внесено зміни до стилів відображеня
![default](https://cloud.githubusercontent.com/assets/24773833/26624405/6b0915bc-45f9-11e7-9089-b8bf3acdc18d.png)
