### ISSUE TITLE
E-auction: Можливо встановити мінімальний крок аукціону нижче 1% при створенні аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1424]
http://uatasset.e-auction.ua

**Опис:** Можливо встановити мінімальний крок аукціону менше 1% від вартості лоту при створенні аукціону, хоча згідно [вимог](https://docs.google.com/document/d/14Yav0iwWOHd-6NeZ_P4fHlNT8e22Hlo24RVz6rSed4M/edit) мінімальний крок має складати від 1% до 100% від вартості лоту включно

**Відтворення:**
1) Залогінитись як Замовник (derZamovnik)
2) Створити аукціон (Кабінет->Створит оголошення з продажу активу->Майно Замовника)
3. Заповнити всі поля валідними значеннями окрім мінімального кроку
4. Внести значеннями мінімального кроку менше 1% від початкової вартості
5. Опублікувати аукціон (кнопка Створити оголошення з продажу активу)

**Очікуваний результат:** система видасть повідомлення про помилку, що мінімальний крок повинен бути не менше 1% від початкової вартості згідно с.9 [ТЗ](https://docs.google.com/document/d/14Yav0iwWOHd-6NeZ_P4fHlNT8e22Hlo24RVz6rSed4M/edit) (мінімальний крок має складати від 1% до 100% від вартості лоту)

**Фактичний результат:** створено аукціон із значенням мінімального кроку менше 1% від вартості лоту включно
![1](https://user-images.githubusercontent.com/13050207/27859594-f5abbd34-6181-11e7-8f06-8ae065b5aa52.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![1](https://user-images.githubusercontent.com/13050207/27866972-f8c4dd42-61a0-11e7-829f-b5b1fc4a8a0c.png)

**Comment by SoftserveQC1** [comment]
Під час редагування лоту згідно [ТЗ Редагування вартості лоту Опис технічної частини п3](https://docs.google.com/document/d/1yqQvFCquJAMqoZFXcwR-oQ0eyTLyFioOplnhHLAJZ5U/edit#) "Для полів guarantee.amount і minimalStep.amount відсоткового обмеження на зниження немає, збільшити значення неможливо", тобто при редагуванні мінімальний крок може становити <1% від початкової вартості, можна прибрати це обмеження в 1% поріг і для створення лоту

**Comment by OlegNekovalev** [comment]
Виписка з регламенту
крок аукціону – мінімальна надбавка, на яку в ході електронного аукціону може здійснюватися підвищення цінової пропозиції. Крок аукціону визначається в діапазоні від 1 до 10% від початкової ціни реалізації майна (активів)/права або початкової орендної плати;

**Comment by SoftserveQC1** [comment]
Вже не дефект, згідно нових пояснень "При цьому фінальні значення полів мають відповідати регламенту та сценаріям тестування. Наразі для мін. Кроку 1-10%, для гарантійного поки обмежень немає. Розмір може змінюватись. На стороні майданчика рекомендуємо виводити підказки про значення цих полів" в іншому випадку відповідальність на стороні Замовника за невалідні дані
