### ISSUE TITLE
Prom: При редагуванні аукціону можна змінити вартість лота лише на суму <50%, замість <=50%

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1426]
https://zakupki.dz-test.net/

**Опис:**  При редагуванні дозволяється знижувати вартість лоту не більше ніж на 50% від поточної вартості (value.amount) за один раз, тобто в діапазоні від 0% до 50% включно. При тестуванні виявлено, що можно зменшити вартість лота лише строго менше 50%, хоча має бути <=50%.

**Відтворення:**
1. Залогінитись як Замовник prom-organizator@yopmail.com
2. Створити нові торги (Аукціони->Новий аукціон)
3. Заповнити всі поля валідними значеннями окрім мінімального кроку
4. Внести значення початкової вартості 5000грн
5. Опублікувати аукціон (кнопка Оголосити аукціон)
6. Натиснути кнопку "Редагувати аукціон"
7. Змінити вартість лоту з 5000 на 2500грн
8. Опублікувати зміни

**Очікуваний результат:** Зміни успішно опубліковано

**Фактичний результат:** Зміни не опубліковано, Замовник бачить повідомлення "Не можна встановити початкову ціну продажі лота більш ніж на 50% менше попередньої ціни", хоча ціна зменшена ріно на 50%.
![1](https://user-images.githubusercontent.com/13050207/27866142-f00215b0-619d-11e7-80a8-0f8d2fddd74b.png)
![2](https://user-images.githubusercontent.com/13050207/27866143-f0034b6a-619d-11e7-9552-958f0a480b51.png)

**Comment by niksdorf** [comment]
фикс уже на проде

**Comment by SoftserveQC1** [comment]
Дефект виправлено та перевірено.
