### ISSUE TITLE
Prom: Відсутня можливість додати документ "Погодження змін до опису лоту" при редагуванні лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1427]
https://zakupki.dz-test.net/

**Відтворення:**
1. Залогінитись як Замовник prom-organizator@yopmail.com
2. Створити нові торги (Аукціони->Новий аукціон)
3. Заповнити всі поля валідними значеннями
4. Опублікувати аукціон (кнопка Оголосити аукціон)
6. Натиснути кнопку "Редагувати аукціон"
7. У розділі "Завантаження документації" додати файл (Завантажити документ)
8. Переглянути можливий тип завантаженого файлу із випадаючого меню

**Очікуваний результат:** Учасник при необхідності може додати документ "Погодження змін до опису лоту" згідно [ТЗ](https://docs.google.com/document/d/1yqQvFCquJAMqoZFXcwR-oQ0eyTLyFioOplnhHLAJZ5U/edit#) с.1 розділ "Логіка роботи" п.1-а

**Фактичний результат:** Немає можливості додати документ "Погодження змін до опису лоту"
![2](https://user-images.githubusercontent.com/13050207/27899727-24ffc8b6-6234-11e7-9619-7f7a74ce9d8b.png)

**Comment by niksdorf** [comment]
фикс уже на продакшене

**Comment by SoftserveQC1** [comment]
Дефект виправлено та перевірено.
