### ISSUE TITLE
Синхронізація опису

### ISSUE THREAD

**Issue by prozorro-support** [openprocurement/frontend#143]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [25](https://prozorro.zendesk.com/agent/#/tickets/25)
**Priority:** normal
**Zendesk assignee:** Служба підтримки/Мирослав

**Original ticket content:**

Тендер d945b04bb731476d86d400c8554280a1 має опис "крісла офісні ISO chrome\n> 4 ніжки, м’яке сидіння і спинка.\n> Матеріал каркасу –хромований метал, колір –хром\n> Оббивка – з тканини або шкірзамінників, колір –чорний, сірий\n> \n> Доставка з 1.04.15 до 30.04.15 за адресою 79006, м.Львів, пл.Ринок, 1"

на http://dz.prom.ua/view/1059 він не відображається.

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-03-04 09:32:33 UTC:_

<p>Тендер d945b04bb731476d86d400c8554280a1 має опис &quot;крісла офісні ISO chrome\n&gt; 4 ніжки, м’яке сидіння і спинка.\n&gt; Матеріал каркасу –хромований метал, колір –хром\n&gt; Оббивка – з тканини або шкірзамінників, колір –чорний, сірий\n&gt; \n&gt; Доставка з 1.04.15 до 30.04.15 за адресою 79006, м.Львів, пл.Ринок, 1&quot;</p>

<p>на <a href="http://dz.prom.ua/view/1059" rel="nofollow" target="_blank">http://dz.prom.ua/view/1059</a> він не відображається.</p>

<p>ЦБД та Аукціон</p>

**Comment by prozorro-support** [comment]
_Comment from Zendesk by a.hlyakin@smartweb.com.ua at 2015-03-04 09:57:18 UTC:_

<p>Все верно. Так будет и с другими тендерами, я так понимаю, с Элеганса. </p>

<p>Этот текст относится к описанию всего тендера. Мы его не парсим т.к. есть описание item’а, которое мы и СМАРТ используем. Это в перспективе перехода на 0.7 в таком случае актуально использовать так. </p>

<p>-- 
<br />Andrii Khliakin
<br /><a href="http://prom.ua" rel="nofollow" target="_blank">http://prom.ua</a>
<br />+380 (67) 230 90 90</p>

<p>среда, 4 марта 2015 г. в 11:32, Мирослав (ProZorro) написал:</p>

**Comment by myroslav** [comment]
Мова йде про те, що не потрібно чекати 0.7 (щоб повноцінно цю інформацію вносити), а потрібно додати відображення такої інформації якщо вона присутня в ЦБД

**Comment by prozorro-support** [comment]
*Comment from Zendesk by a.hlyakin@smartweb.com.ua at 2015-03-04 09:57:18 UTC:*

<p>Все верно. Так будет и с другими тендерами, я так понимаю, с Элеганса. </p>

<p>Этот текст относится к описанию всего тендера. Мы его не парсим т.к. есть описание item’а, которое мы и СМАРТ используем. Это в перспективе перехода на 0.7 в таком случае актуально использовать так. </p>

<p>-- 
<br />Andrii Khliakin
<br /><a href="http://prom.ua" rel="nofollow" target="_blank">http://prom.ua</a>
<br />+380 (67) 230 90 90</p>

<p>среда, 4 марта 2015 г. в 11:32, Мирослав (ProZorro) написал:</p>

**Comment by prozorro-support** [comment]
_Comment from Zendesk by a.hlyakin@smartweb.com.ua at 2015-03-04 09:57:18 UTC:_

<p>Все верно. Так будет и с другими тендерами, я так понимаю, с Элеганса. </p>

<p>Этот текст относится к описанию всего тендера. Мы его не парсим т.к. есть описание item’а, которое мы и СМАРТ используем. Это в перспективе перехода на 0.7 в таком случае актуально использовать так. </p>

<p>-- 
<br />Andrii Khliakin
<br /><a href="http://prom.ua" rel="nofollow" target="_blank">http://prom.ua</a>
<br />+380 (67) 230 90 90</p>

<p>среда, 4 марта 2015 г. в 11:32, Мирослав (ProZorro) написал:</p>

**Comment by darchik** [comment]
Данная проблема исчезнет при вводе в эксплуатацию ITEM's.

**Comment by prozorro-support** [comment]
_Comment from Zendesk by a.hlyakin@smartweb.com.ua at 2015-03-04 09:57:18 UTC:_

<p>Все верно. Так будет и с другими тендерами, я так понимаю, с Элеганса. </p>

<p>Этот текст относится к описанию всего тендера. Мы его не парсим т.к. есть описание item’а, которое мы и СМАРТ используем. Это в перспективе перехода на 0.7 в таком случае актуально использовать так. </p>

<p>-- 
<br />Andrii Khliakin
<br /><a href="http://prom.ua" rel="nofollow noreferrer" target="_blank">http://prom.ua</a>
<br />+380 (67) 230 90 90</p>

<p>среда, 4 марта 2015 г. в 11:32, Мирослав (ProZorro) написал:</p>

**Comment by prozorro-support** [comment]
_Comment from Zendesk by a.hlyakin@smartweb.com.ua at 2015-03-04 09:57:18 UTC:_

<p>Все верно. Так будет и с другими тендерами, я так понимаю, с Элеганса. </p>

<p>Этот текст относится к описанию всего тендера. Мы его не парсим т.к. есть описание item’а, которое мы и СМАРТ используем. Это в перспективе перехода на 0.7 в таком случае актуально использовать так. </p>

<p>-- 
<br />Andrii Khliakin
<br /><a href="http://prom.ua" rel="nofollow noreferrer" target="_blank">http://prom.ua</a>
<br />+380 (67) 230 90 90</p>

<p>среда, 4 марта 2015 г. в 11:32, Мирослав (ProZorro) написал:</p>
