### ISSUE TITLE
DTO: Учасник торгів отримує повідомлення про редагування лоту лише після оплати гарантійного внеску

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1437]
http://www.dz3.byustudio.in.ua/

**Опис:** Учасник торгів отримує повідомлення про редагування лоту лише після оплати гарантійного внеску. Якщо були редагування до моменту сплати гарантійного внеску, то Учасник повідомлення про них не отримає

**Передумова:**
- Залогінитись як Замовник dto-zamovnyk@yopmail.com
- Натиснути кнопку "Створити аукціон"
- Заповнити усі поля валідними даними та опублікувати аукціон
- Залогінитись як Учасник checkdto1@gmail.com
- Зробити валідну ставку по раніше створеному лоту

**Відтворення:**
1) Замовником зменшити початкову вартість (наприклад на 10%)
2) Перевірити пошту/особистий кабінет Учасника на наявність повідомлення про зміни
3) Підтвердити ставку в Адміна
4) Замовником зменшити початкову вартість (наприклад на 10%)
5) Перевірити пошту/особистий кабінет Учасника на наявність повідомлення про зміни
6) Внести гарантійний внесок Учасником (відповідна кнопка у тілі аікціону)
7) Замовником зменшити початкову вартість (наприклад на 10%)
8) Перевірити пошту/особистий кабінет Учасника на наявність повідомлення про зміни

**Очікуваний результат:** Учасник отримує повідомлення про зміни в аукціоні на який він подав пропозицію починаючи з моменту коли він зробив ставку по лоту, тобто починаючи із 1 кроку (першого редагування лоту Замовником) і далі після кроків 4 та 7

**Фактичний результат:** Учасник не отримує повідомлення про зміни доки не внесе гарантійний внесок по аукціону. Фактично Учасник отримав листа лише про третє редагування аукціону на 7 кроці

**Comment by OSerhii** [comment]
Допоки учасник не сплатив гарантійний внесок - пропозиція не подана і в ЦБД її немає. Згоден із вашою думкою вцілому, можливо в майбутньому переробимо. Проте це не слід розглядати як невідповідність ТЗ. Бо у ньому чітко сказано "інформувати про факт редагування користувачів, які вже зробили ставки, у особистому кабінеті та\або на пошту", а у контексті описаного дефекту ставка не подана :) 

Прошу закрити дефект.
