### ISSUE TITLE
UACE: В тілі створеного аукціону відсутнє посилання на регламент торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1439]
http://test-eauction.uace.com.ua/

**Опис:** Згідно [Ручних тестів розділ Тестові сценарії, рівень 1 (Замовник) Створення Лоту пункт 2](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#) В тілі аукціону присутнє посилання на [регламент](https://docs.google.com/document/d/1iQ4lTWf3XLeNQZXZMj2fKqh6ADs9bHhqKCIB-HmdfyE). Повідомлення може бути у хедері, футері самому аукціоні, тобто у місці легко доступному для ознайомлення користувача

**Відтворення:**
1) Залогінитись як Замовник dto-zamovnyk@yopmail.com
2) Створити аукціон (Мої аукціони-Створити аукціон)
3) Заповнити усі поля валідними даними 
4) Опублікувати аукціон (кнопка "Зберегти та перейти до публікації")
5) Переглянути опублікований аукціон

**Очікуваний результат:** В тілі аукціону присутнє посилання на [регламент](https://drive.google.com/file/d/0B7KIe21cMRzrbm9oZ3dsS0RsVG8/view?usp=sharing)

**Фактичний результат:** В тілі створеного аукціону відсутнє посилання на регламент торгів
![1](https://user-images.githubusercontent.com/13050207/28259023-ef8ad6ec-6adc-11e7-8d9e-9739bfb96678.png)
![2](https://user-images.githubusercontent.com/13050207/28259022-ef885228-6adc-11e7-8e18-2013d2101d66.png)

**Comment by w-be** [comment]
Дадай, будь-ласка, посилання на вимоги.

**Comment by SoftserveQC1** [comment]
Додано посилання в опис дефекта

**Comment by SoftserveQC1** [comment]
Відтворюється на 25h8 http://test.25h8.auction/

**Comment by SoftserveQC1** [comment]
Відтворюється на govfound http://test.gov.auction

**Comment by OSerhii** [comment]
Колеги, на всіх майданчиках регламент доступний із меню в хедері. Проектний офіс підтвердив що цього достатньо.
![_200](https://user-images.githubusercontent.com/17930388/29312135-c07fd518-81bc-11e7-9151-edb500258cdc.png)
Прошу закрити дефект.
