### ISSUE TITLE
E-auction: Відсутня можливість обрати CAV 08000000-0 Корпоративні права при створенні лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1440]
http://uatasset.e-auction.ua

**Відтворення:**
1. Залогінитись як Замовник (derZamovnik)
2. Створити аукціон (Кабінет->Створит оголошення з продажу активу->Майно Замовника)
3. Заповнити всі поля валідними значеннями
4. У розділі "Позиція аукціону" натиснути на CAV класифікатор
5. Переглянути можливі класифікатори

**Очікуваний результат:** Можливо обрати класифікатор із наступних розділів:
- 04000000-8 Нерухоме майно
- 05000000-5 Цілісний майновий комплекс або майновий комплекс - комплекс активів підприємства
- 06000000-2 Земельні ділянки
- 07000000-9 Права вимоги за кредитними договорами
- 08000000-0 Корпоративні права

**Фактичний результат:** Розділ 08000000-0 Корпоративні права відсутній до обрання
![1](https://user-images.githubusercontent.com/13050207/28268392-d614540c-6b06-11e7-886d-632e0dbc7d6b.png)

**Comment by OlegNekovalev** [comment]
Пофиксили
![default](https://user-images.githubusercontent.com/23699721/28306708-0272c54a-6ba9-11e7-98c8-700fe8f1e832.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
