### ISSUE TITLE
E-auction: Розділ класифікатора CAV/CAP неможливо "розгорнути" повторно при створенні аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1441]
http://uatasset.e-auction.ua

**Опис:** Розділ останнього у списку класифікатора CAVчи CAP неможливо "розгорнути" повторно при створенні аукціону (дивись [Відео](https://www.screencast.com/t/1WgSA2Bb3Q))
**Відтворення:**
1. Залогінитись як Замовник (derZamovnik)
2. Створити аукціон (Кабінет->Створит оголошення з продажу активу->Майно Замовника)
3. Заповнити всі поля валідними значеннями
4. У розділі "Позиція аукціону" натиснути на CAV класифікатор
5. Переглянути можливі класифікатори
6. Розгорнути класс 07000000-9 натисканням + зліва від класифікатора
7. Згорнути класс 07000000-9 натисканням - зліва від класифікатора

**Очікуваний результат:** Розділи класифікаторів можливо переглядати безліч разів

**Фактичний результат:** Розділ класифікатора 07000000-9 після згортання неможливо знову переглянути
![1](https://user-images.githubusercontent.com/13050207/28270811-6dafa69c-6b0f-11e7-9206-fd52f3396404.png)

**Comment by OlegNekovalev** [comment]
Пофиксили

**Comment by SoftserveQC1** [comment]
Виправлено частково, при згортанні/розгортанні розділу 07, розділ 08 зникає, відтворення на [відео](https://www.screencast.com/t/Cn4WQlOSxbT)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
