### ISSUE TITLE
E-auction: В тілі створеного аукціону відсутнє посилання на регламент торгів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1442]
http://uatasset.e-auction.ua

**Опис:** Згідно [Ручних тестів розділ Тестові сценарії, рівень 1 (Замовник) Створення Лоту пункт 2](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#) В тілі аукціону присутнє посилання на [регламент](https://docs.google.com/document/d/1iQ4lTWf3XLeNQZXZMj2fKqh6ADs9bHhqKCIB-HmdfyE). Повідомлення може бути у хедері, футері самому аукціоні, тобто у місці легко доступному для ознайомлення користувача

**Відтворення:**
1) Залогінитись як Замовник derZamovnik
2) Створити аукціон (Кабынет-Створити оголошення з продажу активу)
3) Заповнити усі поля валідними даними 
4) Опублікувати аукціон (кнопка "Зберегти та перейти до публікації")
5) Переглянути опублікований аукціон

**Очікуваний результат:** В тілі аукціону присутнє посилання на [регламент](https://drive.google.com/file/d/0B7KIe21cMRzrbm9oZ3dsS0RsVG8/view?usp=sharing)

**Фактичний результат:** В тілі створеного аукціону відсутнє посилання на регламент торгів
![1](https://user-images.githubusercontent.com/13050207/28317169-88dca716-6bce-11e7-8b6a-446a06c582fd.png)
![2](https://user-images.githubusercontent.com/13050207/28317170-88de282a-6bce-11e7-90b8-3ca29fb80353.png)
![3](https://user-images.githubusercontent.com/13050207/28317171-88df2ed2-6bce-11e7-9eab-c32a87f54605.png)

**Comment by OlegNekovalev** [comment]
Посилання на регламент пристнє
![default](https://user-images.githubusercontent.com/23699721/28317707-bf749444-6bd0-11e7-8a8b-d52eba493e21.png)
