### ISSUE TITLE
Smart: У загальному списку аукціонів аукціон з "оренди майна" відображено як акціон з "продажу майна"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1444]
http://test.smarttender.biz

**Відтворення:**
1. Залогінитись як Замовник (PPR_TEST_FGI)
2. Створити аукціон (Prozorro.Продажі(Майно)(Тестові)->Додати)
3. Обрати процедуру "Оренда майна" у дропбоксі
4. Заповнити всі поля валідними значеннями
5. Опублікувати аукціон (далі "Зберегти"->Реєстрація =>“Надіслати вперед”)
6. Переглянути аукціон у загальному списку (приклад http://test.smarttender.biz/tenders?mode=sale&f=UA-PS-2017-07-21-000001-3)

**Очікуваний результат:** При перегляді аукціону у загальному списку форма аукціону вказана як "Оренда майна"

**Фактичний результат:** У загальному списку аукціонів аукціон з "оренди майна" відображено як акціон з "продажу майна"
![1](https://user-images.githubusercontent.com/13050207/28467155-a45aef8c-6e37-11e7-8de7-77b3609129f1.png)

**Comment by f3man** [comment]
![image](https://user-images.githubusercontent.com/16836558/28569159-5fba7a66-7141-11e7-9231-557ccc37915d.png)

Ситуацію вирішено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
