### ISSUE TITLE
Smart: Відсутня можливість обрати класифікатори CAV при створенні аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1445]
http://test.smarttender.biz

**Відтворення:**
1. Залогінитись як Замовник (PPR_TEST_FGI)
2. Створити аукціон (Prozorro.Продажі(Майно)(Тестові)->Додати)
3. Обрати процедуру "Оренда майна" у дропбоксі
4. Оглянутиможливі класифікатори активу у розділі "Позиціїї аукціону"-"Класифікація"(F10)

**Очікуваний результат:** Можливо обрати класифікатор CAV із наступних розділів:
- 04000000-8 Нерухоме майно
- 05000000-5 Цілісний майновий комплекс або майновий комплекс - комплекс активів підприємства
- 06000000-2 Земельні ділянки
- 07000000-9 Права вимоги за кредитними договорами
- 08000000-0 Корпоративні права

**Фактичний результат:** Можливо обрати лише класифікатори CPV
![2](https://user-images.githubusercontent.com/13050207/28467450-9a5c2b1c-6e38-11e7-9331-e29aafc89132.png)

**Comment by f3man** [comment]
![image](https://user-images.githubusercontent.com/16836558/28520160-1464af84-7077-11e7-8d9d-b2ced029b4ea.png)

треба обрати відповідний тип класифікації

**Comment by SoftserveQC1** [comment]
Дякую, закриваю, не баг
