### ISSUE TITLE
Smart: Користувач може обрати одиниці виміру позицій аукціону відмінні від "м.кв" при створенні аукціону Оренди

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1446]
http://test.smarttender.biz

**Опис:** Користувач може обрати одиниці виміру позицій аукціону відмінні від "метри квадратні" при створенні аукціону Оренди, хоча згідно з [ТЗ розділ Робота з класифікаторами CPV + CAV + CPVS пункт 3-с](https://docs.google.com/document/d/1yqQvFCquJAMqoZFXcwR-oQ0eyTLyFioOplnhHLAJZ5U/edit#) - "При заведенні лоту, в items вказувати площу приміщення у м.кв. Обмежити для користувача можливість вибрати інші одиниці виміру у випадку вибору варіанту Оренда"

**Відтворення:**
1. Залогінитись як Замовник (PPR_TEST_FGI)
2. Створити аукціон (Prozorro.Продажі(Майно)(Тестові)->Додати)
3. Обрати процедуру "Оренда майна" у дропбоксі
4. Заповнити всі поля валідними значеннями
5. Одиниці виміру активів обрати не метр квадтратний (наприклад літр)
6. Опублікувати аукціон (далі "Зберегти"->Реєстрація =>“Надіслати вперед”)

**Очікуваний результат:** При створенні аукціону Оренди користувач може обрати одиниці виміру позицій аукціону лише м.кв

**Фактичний результат:** При створенні аукціону Оренди користувач може обрати будь-які одиниці виміру позицій аукціону
![1](https://user-images.githubusercontent.com/13050207/28467909-0d24330a-6e3a-11e7-8fa6-e55f4cb8cb1a.png)

**Comment by f3man** [comment]
Питання вирішено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
