### ISSUE TITLE
Smart: Можливо встановити мінімальний крок аукціону нижче 1% при створенні/редагуванні аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1447]
http://test.smarttender.biz

**Відтворення:**
1. Залогінитись як Замовник (PPR_TEST_FGI)
2. Створити аукціон (Prozorro.Продажі(Майно)(Тестові)->Додати)
3. Обрати процедуру "Оренда майна" у дропбоксі
4. Заповнити всі поля валідними значеннями (вартість 100.000, крок 10, внесок 100)
5. Опублікувати аукціон (далі "Зберегти"->Реєстрація =>“Надіслати вперед”)

**Очікуваний результат:** Аукціон не буде опубліковано через те що мінімальний крок складає менше 1% від початкової вартості лоту, про що користувача буде попереджено відповідним повідомленням

**Фактичний результат:** Аукціон успішно опубліковано із кроком менше 1%
![1](https://user-images.githubusercontent.com/13050207/28511954-59392e60-7058-11e7-909c-6a7fa242de81.png)
![2](https://user-images.githubusercontent.com/13050207/28511983-833f1670-7058-11e7-9033-c1d6cec5b0ca.png)

**Comment by f3man** [comment]
Ситуацію вирішено:
![image](https://user-images.githubusercontent.com/16836558/28526407-219ad6ba-7090-11e7-95b1-6f23f1de1d90.png)
![image](https://user-images.githubusercontent.com/16836558/28526415-275e1ab2-7090-11e7-9d3e-74eb380ea9f9.png)

**Comment by SoftserveQC1** [comment]
Дефект виправлено
