### ISSUE TITLE
Smart: Відсутня можливість додати документ "Погодження змін до опису лоту" при редагуванні лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1448]
http://test.smarttender.biz

**Відтворення:**
1. Залогінитись як Замовник (PPR_TEST_FGI)
2. Створити аукціон (Prozorro.Продажі(Майно)(Тестові)->Додати)
3. Обрати процедуру "Оренда майна" у дропбоксі
4. Заповнити всі поля валідними значеннями
5. Опублікувати аукціон (далі "Зберегти"->Реєстрація =>“Надіслати вперед”)
6. Перейти до редагування опублікованого аукціону ("Змінити")
7. Додати документ ("Завантаження документаціїї"->"Додати"->"ОК")
8. Переглянути можливий до обрання тип документа

**Очікуваний результат:** Замовник при необхідності може додати документ "Погодження змін до опису лоту" згідно [ТЗ](https://docs.google.com/document/d/1yqQvFCquJAMqoZFXcwR-oQ0eyTLyFioOplnhHLAJZ5U/edit#) с.1 розділ "Логіка роботи" п.1-а

**Фактичний результат:** Немає можливості додати документ "Погодження змін до опису лоту", такий документ у переліку відсутній
![1](https://user-images.githubusercontent.com/13050207/28512164-5aa2698c-7059-11e7-922a-0c4975627775.png)

**Comment by f3man** [comment]
![image](https://user-images.githubusercontent.com/16836558/28519525-9e8cac28-7074-11e7-8264-f3cbc43395a7.png)
додано тип документу

**Comment by SoftserveQC1** [comment]
Дефект виправлено
