### ISSUE TITLE
Smart: Можливо опублікувати документ до аукціону не вказуючи його тип

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1449]
http://test.smarttender.biz

**Відтворення:**
1. Залогінитись як Замовник (PPR_TEST_FGI)
2. Створити аукціон (Prozorro.Продажі(Майно)(Тестові)->Додати)
3. Обрати процедуру "Оренда майна" у дропбоксі
4. Заповнити всі поля валідними значеннями
5. Додати документ не вказуючи його тип ("Завантаження документаціїї"->"Додати"->"ОК")
6. Опублікувати аукціон (далі "Зберегти"->Реєстрація =>“Надіслати вперед”)

**Очікуваний результат:** Аукціон не опубліковано, з'являється повідомлення "Оберіть тип документу"

**Фактичний результат:** Аукціон опубліковано, доданий документ відображено без вказання його типу
![1](https://user-images.githubusercontent.com/13050207/28512295-f921c36e-7059-11e7-974d-3cc2ad3133e4.png)

**Comment by f3man** [comment]
![image](https://user-images.githubusercontent.com/16836558/28526227-9506ad5a-708f-11e7-9c05-a5a8fb1fe49f.png)
Додано поняття "Інший тип"

**Comment by SoftserveQC1** [comment]
Дефект виправлено
