### ISSUE TITLE
Мова одиниць виміру

### ISSUE THREAD

**Issue by prozorro-support** [openprocurement/frontend#145]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [27](https://prozorro.zendesk.com/agent/#/tickets/27)
**Priority:** normal
**Zendesk assignee:** Служба підтримки/A

**Original ticket content:**

В поле Tender.items[0].unit.name потрібно записувати українську назву одиниці виміру, а англійську записувати в Tender.items[0].unit.name_en (російську відповідно в Tender.items[0].unit.name_ru)

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-03-04 09:50:46 UTC:_

<p>В поле Tender.items[0].unit.name потрібно записувати українську назву одиниці виміру, а англійську записувати в Tender.items[0].unit.name_en (російську відповідно в Tender.items[0].unit.name_ru)</p>

<p>ЦБД та Аукціон</p>

**Comment by S-Shevchenko** [comment]
исправлено.
