### ISSUE TITLE
u-studio: Відсутня можливість обрати класифікатор CAV розділу Корпоративні права при заведенні лота

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1451]
http://dgf.byustudio.in.ua/

**Опис:** Відсутня можливість обрати класифікатор CAV розділу Корпоративні права при заведенні лота. Повний список класифікаторів можна оглянути у [документі](http://standards.openprocurement.org/classifiers/cav/uk.json)

**Відтворення:**
1) Залогінитись як likvidator@yopmail.com
2) Створити аукціон (Мої аукціони-Створити аукціон)
3) Переглянути можливі коди СAV активу у розділі Склад лоту

**Очікуваний результат:** У склад можливих класифікаторів входить розділ 08000000-6 : "Корпоративні права" та його похідні

**Фактичний результат:** Розділ 08000000-6 : "Корпоративні права" відсутній до обрання відповідного класифікатора актива
![default](https://user-images.githubusercontent.com/13050207/28624462-df3875b4-7221-11e7-9c52-30ef45b1ab7e.png)

**Comment by OSerhii** [comment]
Пофіксили, можна перевіряти.

**Comment by olyamalysh** [comment]
Виправлено, можна закривати. https://gyazo.com/4b6fafe5374089b2fe85b168cfc7ab1a
