### ISSUE TITLE
u-studio: При редагуванні чернетки копії аукціону з продажу майна неможливо додати посилання на VDR

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1452]
http://dgf.byustudio.in.ua/

**Відтворення:**
1) Залогінитись користувачем likvidator@yopmail.com
2) Створити аукціон (Мої аукціони-Створити аукціон)
3) Обрати тип "Майно банка"
4) Заповнити всі поля валідними даними та "Зберегти" чернетку
5) Скопіювати чернетку (Копіювати аукціон - у правому сайдбарі)
6) Перейти до редагування скопійованого лоту (Редагувати оголошення - у правому сайдбарі) 
7) У розділі документи переглянути типи можливих до додання документів натиснувши "Додати посилання/інформацію щодо порядку ознайомлення"

**Очікуваний результат:** Можливо додати посилання на VDR при редагуванні копії аукціону з продажу майна банків

**Фактичний результат:** При редагуванні копії аукціону з продажу майна неможливо додати посилання на VDR. Проте така можливість є при редагуванні копії аукціону з продажу "Прав вимоги"

**Comment by oleksandrakulenko** [comment]
https://github.com/openprocurement/frontend/issues/1452 - тут ок, в сценаріях тестування прописано
"Посилання на VDR (у випадку “Права вимоги”) (необов’язкове)"

**Comment by SoftserveQC1** [comment]
не дефект
