### ISSUE TITLE
u-studio: Відсутні повідомлення Ліквідатору про перебіг аукціону на пошту та у особистому кабінеті

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1455]
http://dgf.byustudio.in.ua/

1. Про початок кваліфікації/авордінгу Учасника та необхідність додати протокол торгів протягом 4х діб
2. Про поставлене запитання до аукціону
3. Про повернення Учасником який зайняв друге місце гарантійного внеску та відмову від подальшої участі у аукціоні

**Comment by olyamalysh** [comment]
Дефект відтворюється. Повідомлення Ліквідатору відсутні.
Приклад аукціону UA-EA-2017-08-15-000007-2, пошта на яку мали  надходити повідомлення malyshevaolya02@gmail.com.

**Comment by SoftserveQC1** [comment]
Зараз не вимагається, так як функціонал реалізований у Єдиному Кабінеті.
