### ISSUE TITLE
Prom: При редагуванні опублікованого аукціону присутня функціональність додати нові предмети продажу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1456]
https://zakupki.dz-test.net/

**Опис:** При редагуванні опублікованого аукціону присутня функціональність додати нові предмети продажу, хоча після збереження змін вони й не будуть обпубліковані, після оновлення сторінки одразу зникнуть

**Відтворення:**
1. Залогінитись як Замовник prom-organizator@yopmail.com
2. Створити нові торги (Аукціони->Новий аукціон)
3. Обрати тип торгів "Оренда" та заповнити всі поля валідними значеннями
4. Опублікувати аукціон (кнопка Оголосити аукціон)
5. Натиснути кнопку "Редагувати аукціон"
6. Проскролити вниз сторінки до предметів продажу

**Очікуваний результат:** В опублікованому аукціоні відсутня можливість додавати нові предмети продажу

**Фактичний результат:** При редагуванні опублікованого аукціону присутня функціональність додати нові предмети продажу, хоча після збереження змін вони й не будуть обпубліковані
![1](https://user-images.githubusercontent.com/13050207/28671142-441a1b64-72e4-11e7-847e-3ae7f17ff517.png)

**Comment by znakharenko** [comment]
Исправлено

**Comment by SoftserveQC1** [comment]
Все ще відтворюється
Chrome Version 59.0.3071.115 (Official Build) (64-bit), Firefox 54.0.1 (64-бит); Mac OS Sierra 10.12.1 (16B2659)
prom-organizator@yopmail.com
UA-PS-2017-08-01-000064-2
![1](https://user-images.githubusercontent.com/13050207/28824652-b8086400-76cb-11e7-958e-f8b3a48cde3e.png)

**Comment by niksdorf** [comment]
фикс уже на проде

**Comment by SoftserveQC1** [comment]
Дефект виправлено та перевірено.
