### ISSUE TITLE
Prom: При створенні аукціону поле "Термін дії договору" відображено як "Номер кредитного договору"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1457]
https://zakupki.dz-test.net/

**Відтворення:**
1. Залогінитись як Замовник prom-organizator@yopmail.com
2. Створити нові торги (Аукціони->Новий аукціон)
3. Обрати тип торгів "Оренда"
4. Проскролити вниз сторінки до предметів продажу, оглянути неймінг полів

**Очікуваний результат:** Поле в якому при заведенні лоту можна вказати термін дії договору (оренди) називається "Термін дії договору"

**Фактичний результат:** При створенні аукціону поле "Термін дії договору" відображено як "Номер кредитного договору"
![1](https://user-images.githubusercontent.com/13050207/28671486-8ba30fa8-72e5-11e7-86d5-74c4ef59e80d.png)

**Comment by znakharenko** [comment]
Исправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
![1](https://user-images.githubusercontent.com/13050207/28824482-d6bbb7fe-76ca-11e7-82dd-7fa59057a4d1.png)
