### ISSUE TITLE
Телефон контактної особи замовника

### ISSUE THREAD

**Issue by prozorro-support** [openprocurement/frontend#146]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [29](https://prozorro.zendesk.com/agent/#/tickets/29)
**Priority:** normal
**Zendesk assignee:** Служба підтримки/A

**Original ticket content:**

В тендері  c1f80c7ea8094151a364b7957e1a865f є контактна особа (включно з телефоном), і її телефон не відображається на http://dz.prom.ua/view/1100

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-03-04 14:16:28 UTC:_

<p>В тендері  c1f80c7ea8094151a364b7957e1a865f є контактна особа (включно з телефоном), і її телефон не відображається на <a href="http://dz.prom.ua/view/1100" rel="nofollow" target="_blank">http://dz.prom.ua/view/1100</a></p>

<p>ЦБД та Аукціон</p>

**Comment by darchik** [comment]
Fixed
![2015-05-22 15 03 32](https://cloud.githubusercontent.com/assets/5691919/7770150/c2f44e66-0093-11e5-8bc8-a1326d54b0b4.png)
