### ISSUE TITLE
Smart: Можливо встановити причину скасування аукціону "Згідно рішення ФГВФО"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1460]
http://test.smarttender.biz

**Опис:** Під час скасування аукціону можливо встановити причину скасування "Згідно рішення виконавчої дирекції Фонду гарантування вкладів фізичних осіб". При сбробі скасувати аукціон із даною причиною з'явиться наступна [помилка](https://drive.google.com/open?id=0B8BDu9E3O4chS2VKWW1ONWxNbGs) та скасування не відбудеться

**Відтворення:**
1. Залогінитись як Замовник (PPR_TEST_FGI)
2. Створити аукціон (Prozorro.Продажі(Майно)(Тестові)->Додати)
3. Обрати процедуру "Оренда майна" у дропбоксі
4. Заповнити всі поля валідними значеннями
5. Опублікувати аукціон (далі "Зберегти"->Реєстрація =>“Надіслати вперед”)
6. Натиснути  кнопку "Скасування аукціону" та переглянути можливі причини скасування

**Очікуваний результат:** Існують лише дві можливі причини скасування аукціону згідно [Ручних тестів](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#):
- Згідно рішення виконавчої дирекції Замовника
- Порушення порядку публікації оголошення

**Фактичний результат:** Окрім необхідних причин скачування присутня причина із ЦБД-1 "Згідно рішення виконавчої дирекції Фонду гарантування вкладів фізичних осіб"
![default](https://user-images.githubusercontent.com/13050207/28767009-c8a914b8-75da-11e7-86db-751496194cdf.png)

**Comment by f3man** [comment]
![image](https://user-images.githubusercontent.com/16836558/28775610-aaa32550-75fb-11e7-867b-4ebfc7afd77e.png)
питання вирішено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
