### ISSUE TITLE
Prom: Причина скасування аукціону "Згідно рішення ФГВФО" замість "Згідно рішення Замовника"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1461]
https://zakupki.dz-test.net/

**Відтворення:**
1. Залогінитись як Замовник prom-organizator@yopmail.com
2. Створити нові торги (Аукціони->Новий аукціон)
3. Обрати тип торгів "Оренда" та заповнити всі поля валідними значеннями
4. Опублікувати аукціон (кнопка Оголосити аукціон)
5. В тілі аукціону натиснути кнопку "Скасувати аукціон" та оглянути можливі причини

**Очікуваний результат:** Існують лише дві можливі причини скасування аукціону згідно [Ручних тестів](https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#):
- Згідно рішення виконавчої дирекції Замовника
- Порушення порядку публікації оголошення

**Фактичний результат:** Замість причини скасцвання "Згідно рішення виконавчої дирекції Замовника" присутня причина із ЦБД-1 "Згідно рішення виконавчої дирекції Фонду гарантування вкладів фізичних осіб" [приклад](https://lb.api-sandbox.ea2.openprocurement.net/api/2.3/auctions/9b66fe05df2b4d04820dc06eebac7f22)
![default](https://user-images.githubusercontent.com/13050207/28768281-ac342340-75df-11e7-9f89-85518e70d438.png)
![2](https://user-images.githubusercontent.com/13050207/28768282-ac35f71a-75df-11e7-8552-5298d41bab8d.png)

**Comment by niksdorf** [comment]
фикс уже давно на продакшене

**Comment by SoftserveQC1** [comment]
Дефект виправлено та перевірено.
