### ISSUE TITLE
Smart: При створенні аукціону назви класифікаторів предмету продажу відмінні від CAV, CPV

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1462]
http://test.smarttender.biz

**Опис:** При створенні аукціону назви класифікаторів предмету продажу фігурують "ДК 021 ДО: 2015" замість CPV, та "Класифікатор аукціонів держмайна" замість CAV

**Відтворення:**
1. Залогінитись як Замовник (PPR_TEST_FGI)
2. Створити аукціон (Prozorro.Продажі(Майно)(Тестові)->Додати)
3. Обрати процедуру "Оренда майна" у дропбоксі
4. Перейти до розділу пропозиції та натиснути на дропбокс "Класифікація"
5. Переглянути можливий до обрання тип класифікатора

**Очікуваний результат:** Користувач може обрати класифікації товару з груп CAV та CPV

**Фактичний результат:** Замість груп CAV та CPV користувач обирає класифікацію між "Класифікатор аукціонів держмайна" та "ДК 021 ДО: 2015" відповідно
![1](https://user-images.githubusercontent.com/13050207/28771860-075ed546-75ed-11e7-9e90-164060f13ec0.png)

**Comment by f3man** [comment]
![image](https://user-images.githubusercontent.com/16836558/28817924-5f409e14-76b2-11e7-896d-329653c18103.png)
Ситуацію вирішено

**Comment by SoftserveQC1** [comment]
Дефект виправлено
