### ISSUE TITLE
Контактна особа замовника

### ISSUE THREAD

**Issue by prozorro-support** [openprocurement/frontend#147]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [30](https://prozorro.zendesk.com/agent/#/tickets/30)
**Priority:** normal
**Zendesk assignee:** Служба підтримки/A

**Original ticket content:**

В тендері c1f80c7ea8094151a364b7957e1a865f є інформація про контактну особу (включно з телефоном), інформації про контактну особу немає на http://e-tender.biz/#/tenderDetailes/c1f80c7ea8094151a364b7957e1a865f

Мирослав

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-03-04 14:20:33 UTC:_

<p>В тендері c1f80c7ea8094151a364b7957e1a865f є інформація про контактну особу (включно з телефоном), інформації про контактну особу немає на <a href="http://e-tender.biz/#/tenderDetailes/c1f80c7ea8094151a364b7957e1a865f" rel="nofollow" target="_blank">http://e-tender.biz/#/tenderDetailes/c1f80c7ea8094151a364b7957e1a865f</a></p>

<p>Мирослав</p>

<p>ЦБД та Аукціон</p>

**Comment by S-Shevchenko** [comment]
Спасибо, взяли в работу.

**Comment by S-Shevchenko** [comment]
Исправили.
