### ISSUE TITLE
kpmg: In the registration page fields` tooltips about wrong users input are not translated into Ukrainian

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1471]
https://uat.kpmgdealroom.com/public/prozorro

**Description:** In the registration page fields` tooltips about wrong users input are not translated into Ukrainian

**Steps to reproduce:**
1) Enter https://uat.kpmgdealroom.com/public/prozorro in address bar of a browser
2) Select Ukrainian in the language drop-down list
3) Click into the "Реєструйся" button in the "Зацікавлені?" column
4) Fill in 4 necessary fields with valid user data
5) Click the button "Надіслати"
6) Enter into the "Tax Identification Number" field literal symbols

**Expected result:** The user receives tooltip about wrong input message and with information about correct input example in Ukrainian

**Actual result:** The user receives tooltip about wrong input message in English and without information about correct input example
![1](https://user-images.githubusercontent.com/13050207/29175905-0457aff4-7df3-11e7-8734-ceed794e2524.png)

**Comment by w-be** [comment]
Fixed except one tool-tip:
![image](https://user-images.githubusercontent.com/11888281/33083181-54a4b20a-cee7-11e7-979d-2a220dcaa2e0.png)
https://uat.kpmgdealroom.com/Account/Register/05b3f9ff-4b2e-4bad-ab6f-6e1224437999

**Comment by w-be** [comment]
Now there is no validation for the fields except name, surname, email, phone.
![screenshot-2017-12-12 deal room -](https://user-images.githubusercontent.com/11888281/33898976-b7d67b38-df72-11e7-8b02-8de29ff65037.png)

**Comment by bhanupasham** [comment]
Except firstname, lastname, email and phone number, all other fields are not mandatory so that's the reason why you are not able to see validation messages for other fields.

**Comment by scoolic** [comment]
@w-be
