### ISSUE TITLE
kpmg: The user has to fill in all information about his firm after registration again in his profile

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1473]
https://uat.kpmgdealroom.com/Profile?ReturnUrl=/Dashboard

**Description:** After registration and approving the account, the user has to fill in all information about his firm again in his profile

**Steps to reproduce:**
1) Enter https://uat.kpmgdealroom.com/public/prozorro in address bar of a browser
2) Select Ukrainian in the language drop-down list
3) Click into the "Реєструйся" button in the "Зацікавлені?" column
4) Fill in 4 necessary fields with valid user data
5) Click the button "Надіслати"
6) Fill in all necessary fields with valid user data, use email you can check
7) Click the button "Надіслати"
8) Ask admins to approve your account
9) Check the email adress and approve your account by link
10) Create and approve your password
11) Log in under your account 

**Expected result:** The user can successfully work under his account 

**Actual result:** The user has to fill in all information about his firm again in his profile
![1](https://user-images.githubusercontent.com/13050207/29177924-b757afc8-7df8-11e7-9e0d-7872b8421dd7.png)

**Comment by bhanupasham** [comment]
This is fixed and ready for re-testing.

**Comment by scoolic** [comment]
@w-be
