### ISSUE TITLE
ЕЛЕГ, у IE8 - немає доступу на продакшин і sandbox 

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#148]
![ie_8_production](https://cloud.githubusercontent.com/assets/11062040/6506233/1a09117a-c352-11e4-99be-da539e0c3076.png)

![ie_8_sandbox](https://cloud.githubusercontent.com/assets/11062040/6506244/2cbf6a12-c352-11e4-9140-47867d0f0b16.png)

**Comment by S-Shevchenko** [comment]
@OksanaPakholok  Згідно вимог  ТЗ розроблення велося з версій IE 10 ...

**Comment by OksanaPakholok** [comment]
У "Регламент роботи майданчика", а саме п.5 "Загальні характеристики Системи. Режим роботи Системи", ст. 5, зазначено: 
"Доступ до інформації, що розміщується в Системі, може бути здійснений за допомогою використання поширених веб-оглядачів, включаючи Internet Explorer версії 6.0 і вище."
@SergeyShevchenko1

**Comment by S-Shevchenko** [comment]
@OksanaPakholok  Дякую, нам дуже приємно з вами працювати.

**Comment by S-Shevchenko** [comment]
Внесли зміни в регламент.
