### ISSUE TITLE
[Polonex] Частина форми зворотнього зв'язку допомоги надана англійською мовою

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1485]
Відтворення:
1 Залогуватись на http://test.polonex.in.ua
2 Перейти на допомогу
3 В ролі учасника створити питання

Очікувано: Текс написаний українською мовою

Фактично: Частина тексту написана  англійською

![1](https://user-images.githubusercontent.com/13050207/30067402-5e572550-9263-11e7-81b4-2601e6ffeec3.png)

**Comment by greeschenko** [comment]
виправлено, перевірте будьласка

**Comment by SoftserveQC1** [comment]
виправлено, дякую
