### ISSUE TITLE
Поле “Початкова ціна продажу лоту” приймає значення з кількістю знаків після коми більше двох

### ISSUE THREAD

**Issue by olyamalysh** [openprocurement/frontend#1491]
Description
Поле “Початкова ціна продажу лоту” приймає значення з кількістю знаків після коми більше двох

Steps to reproduce
1. Увійти в аккаунт, під роллю “Замовника”
2. Натиснути лінку “Створити лот”
3. Заповнити всі поля валідними даними
4. Поле “Початкова ціна продажу лоту” заповнити значенням з кількістю знаків після коми >2
5. Натиснути кнопку “Зберегти”
6. Натиснути кнопку “Опублікувати лот”

Actual result
Поле “Початкова ціна продажу лоту” приймає значення з кількістю знаків після коми більше двох 
https://gyazo.com/181922d2cc44623703fabc421a92b7d3 

Expected result
Поле “Початкова ціна продажу лоту” приймає значення з кількістю знаків після коми не більше двох

**Comment by pbil** [comment]
виправлено

**Comment by SoftserveQC1** [comment]
пофикшено
