### ISSUE TITLE
У Учасника, якого визнано наступним за переможцем на етапі Кваліфікація відсутня можливість (функція\кнопка) забрати гарантійний внесок

### ISSUE THREAD

**Issue by olyamalysh** [openprocurement/frontend#1492]
http://auction.privatbank.ua

Description
У Учасника, якого визнано наступним за переможцем на етапі Кваліфікація відсутня можливість (функція\кнопка) забрати гарантійний внесок

Steps to reproduce
1. Увійти в аккаунт, під роллю “Учасника”
2. Перейти на сторінку аукціону, до якого була раніше подана Пропозиція
3. Дочекатися початку аукціону
4. Перейти за посиланням на елетронні торги
5. Успішно пройти етапи аукціону, та зайняти наступне місце за переможцем
6. Перейти на сторінку аукціону в кабінеті

Actual result
У Учасника, якого визнано наступним за переможцем на етапі Кваліфікація відсутня можливість (функція\кнопка) забрати гарантійний внесок

Expected result
В кабінеті у Учасника, якого визнано наступним за переможцем, на сторінці аукціону на етапі Кваліфікація є можливість (функція\кнопка) забрати гарантійний внесок.

**Comment by pbil** [comment]
виправлено

**Comment by SoftserveQC1** [comment]
Перевірено
