### ISSUE TITLE
При створені аукціонів з продажу\оренди Замовник має можливість додати посилання на VDR

### ISSUE THREAD

**Issue by olyamalysh** [openprocurement/frontend#1497]
http://auction.privatbank.ua

Description
При створені аукціонів з продажу\оренди Замовник має можливість додати посилання на VDR

Steps to reproduce
Увійти в аккаунт, під роллю “Замовника”
Натиснути лінку “Створити лот”
Обрати в полі “Оголошення аукціону з” значення “оренди” (наприклад)
Перейти до блоку “Загальні додатки”
Натиснути кнопку “Додати текстовий додаток”
Відкрити випадаючий список з обранням типу текстового додатка

Actual result
При створені аукціонів з продажу\оренди Замовник має можливість додати посилання на VDR
https://gyazo.com/834ac5c50711c8f342c3455420cd6e31 

Expected result
При створені аукціонів з продажу\оренди у Замовника відсутня можливість додати посилання на VDR

**Comment by pbil** [comment]
виправлено

**Comment by SoftserveQC1** [comment]
не пофікшено :
![92e8895a44](https://user-images.githubusercontent.com/13050207/36784829-847493d4-1c89-11e8-95c4-ca2cb0e9fc9f.png)

**Comment by SoftserveQC1** [comment]
Але з'явилося інформаційне повідомлення, і зберегти такий аукціон немає можливості
![1ca760d670](https://user-images.githubusercontent.com/13050207/36790262-ebc3b2fa-1c9c-11e8-95b6-6aedf02d1964.png)
