### ISSUE TITLE
Вопрос на ПРОМ от СМАРТ пришел, а ответ - нет

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#15]
1-СМАР-АК-01
Вопрос СМАР-АК-03

**Comment by andriykucherenko** [comment]
Мирослав пишет: в ЦБД по 1-СМАР-АК-01 (59b1fbcadf504dba86492b66388cfed4) питанню Вопрос СМАР-АК-03 (2d12d716f74b4219878b492cffdd5362) відповіді ще нема
А в тонком клиенте ответ есть:
![image](https://cloud.githubusercontent.com/assets/9398532/5873081/6c798a6a-a2fb-11e4-883b-016cffa8384f.png)

**Comment by AlexRudenko** [comment]
Не установлена галочка
![image](https://cloud.githubusercontent.com/assets/10192570/5873146/2c04deb6-a2fc-11e4-9202-244059f029c0.png)
Закрывай вопрос
