### ISSUE TITLE
ЕЛЕГ, при реєстрації, поле "Логін" приймає значення "_" (нижнє підкреслення)

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#150]
![underscore_login](https://cloud.githubusercontent.com/assets/11062040/6524271/78e33dde-c400-11e4-8437-b98cb15ba1fa.png)

Репродюситься в Firefox, Chrome, IE та Оpera

**Comment by lerich** [comment]
задачка в работе.

**Comment by S-Shevchenko** [comment]
Символ является допустимым , согласно тех. задания.
