### ISSUE TITLE
Хронологія надходження повідомлень в особистому кабінеті Учасника не відповідає фактичним діям у системі

### ISSUE THREAD

**Issue by olyamalysh** [openprocurement/frontend#1504]
http://auction.privatbank.ua

Description
Хронологія надходження повідомлень в особистому кабінеті Учасника не відповідає фактичним діям у системі (голландський аукціон)

Steps to reproduce

1. Подати пропозицію до аукціону 
2. Дочекатися апруву від майданчика
3. Скасувати лот (роль Ліквідатора)
4. Перейти на сторінку повідомлень в особистому кабінеті Учасника

Actual result
Хронологія надходження повідомлень в особистому кабінеті Учасника не відповідає фактичним діям у системі (голландський аукціон) 
https://gyazo.com/ee74a4ddd967406f4c8afbe0c24fc812

Expected result
Повідомлення надходять у хронологічному порядку та відповідають етапності дій користувача у системі

**Comment by pbil** [comment]
fixed

**Comment by olyamalysh** [comment]
Дефект відтворюється https://gyazo.com/8906687e2e680a346d521d5ae2ae7fb5

**Comment by pbil** [comment]
fixed

**Comment by olyamalysh** [comment]
Виправлено
