### ISSUE TITLE
ЕЛЕГ, чи очікувана поведінка, що замовник (учасник) може задавати пусті запитання до тендера, в періоді уточнень?

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#151]
![empty_question](https://cloud.githubusercontent.com/assets/11062040/6530485/f872cd60-c439-11e4-8ad9-206208e7faee.png)

**Comment by myroslav** [comment]
ЦБД не накладає обмеження.

**Comment by OksanaPakholok** [comment]
Дякую за відповідь
