### ISSUE TITLE
Не надходить повідомлення про скасування аукціону електронною поштою Учаснику, що задав питання до аукціону

### ISSUE THREAD

**Issue by olyamalysh** [openprocurement/frontend#1518]
http://www.dz3.byustudio.in.ua/

Description
Не надходить повідомлення про скасування аукціону електронною поштою Учаснику, що задав питання до аукціону

Steps to reproduce
1.  Задати запитання до аукціону
2. Дочекатися його публікації
3. Скасувати в ЄК аукціон, до якого було подано запитання
4. Перейти до електронної пошти учасника

Actual result
Не надходить повідомлення про скасування аукціону електронною поштою Учаснику, що задав питання до аукціону. Приклад аукціону UA-EA-2017-09-14-000046-1

Expected result
Надходить повідомлення про скасування аукціону електронною поштою Учаснику, що задав питання до аукціону.

**Comment by OSerhii** [comment]
@olyamalysh Пофіксили, прошу перевірити і закрити дефект.

**Comment by olyamalysh** [comment]
Виправлено
