### ISSUE TITLE
ЕЛЕГ, прінти працюють некоректно

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#152]
Усі нище подані сторінки були роздруковані на принтері (без зміни розміру) та відскановані.
У всіх бравзерах після доданих файлів, відображається - шлях доданих файлів, до пропозиції, і до тендера. 

Примітка: у файлі Proba.docx (13.5 MB) та Proba2.docx (27.0 MB) шлях не відображається

1) Firefox

![ff_proposal](https://cloud.githubusercontent.com/assets/11062040/6532070/7851c21e-c446-11e4-96f1-239fcabb1bf1.png)

![ff_active_enquiries_3](https://cloud.githubusercontent.com/assets/11062040/6532117/d9429986-c446-11e4-84d5-c450d30f9575.png)

2) У IE відображається також вихід за межі документу

![ie_active_tendering_1](https://cloud.githubusercontent.com/assets/11062040/6534734/6b53e8ba-c448-11e4-84ba-d5d5e996b430.png)
![ie_active_tendering_2](https://cloud.githubusercontent.com/assets/11062040/6534736/718d0432-c448-11e4-8960-d3b5eff9729f.png)
![ie_active_tendering_3](https://cloud.githubusercontent.com/assets/11062040/6534745/79043988-c448-11e4-8c3c-7deb21d9d1d4.png)

3) У Сhrome - зображення дуже маленьке, теж відмічається вихід за межі

![chrome_active_tendering_1](https://cloud.githubusercontent.com/assets/11062040/6534780/d9d96260-c448-11e4-87a4-b12bc0840a69.png)

4) У Оpera - також зображення дуже маленьке, і є вихід за межі документу.

![opera_active_tendering_1](https://cloud.githubusercontent.com/assets/11062040/6534815/103e7156-c449-11e4-8534-920e63debcd2.png)

**Comment by S-Shevchenko** [comment]
Проверьте пожалуйста.

**Comment by S-Shevchenko** [comment]
Исправлено.
