### ISSUE TITLE
Тестове середовище для майданчика ПРОМ

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#153]

**Comment by myroslav** [comment]
Андрію, чи є якісь прогнози по строках запуску такого середовища?

**Comment by darchik** [comment]
Мирослав, дам ответ в ближайшее время. Извиняюсь за долгий ответ. Только увидел сообщение.

**Comment by darchik** [comment]
Тестовый сервер находится по адресу http://dz.dz-test.net
