### ISSUE TITLE
Не приходять листи - підтвердження про реєестрацію,запитання ,пропозицію,завершення торгів

### ISSUE THREAD

**Issue by Ipyt** [openprocurement/frontend#1530]
TOVPROF
http://proz-test.aykcion.com.ua
Опис
Не приходять листи -підтвердження на електронну скриньку
Кроки
1 Зареєеструватися на майданчику
2 Поставити запитання до лоту
3 Зробити пропозицію до лоту
4 Оновити пропозицію-завантажити новий документ до пропозиції
5 Подати пропозицію до лоту з найближчим часом проведення аукціону щоб перевірити підтвердження про те що аукціон не відбувся /завершений
Очікуваний результат
На всі дії повинно з'являтися повідомлення у особистому кабінеті і на реєстровану електронну сриньку повинні надходити електронні листи
Фактичний результат
Повідомлення про пропозицію з'являються у особистому кабінеті.
Жоден лист не прийшов на електронну скриньку.

**Comment by ukrosoft** [comment]
Проблему отправки почтовых сообщений устранили

![screenshot_20170918_181911](https://user-images.githubusercontent.com/16786861/30549654-ffb80cc2-9c9d-11e7-9df4-5cb042deb9b5.png)

**Comment by Ipyt** [comment]
Виправлено .
Перевірено .
