### ISSUE TITLE
Навігація стрілочками по сторінках аукціонів обнулює заданий пошук

### ISSUE THREAD

**Issue by Ipyt** [openprocurement/frontend#1531]
TOVPROF
http://proz-test.aykcion.com.ua
Кроки
1 Обрати тип аукціону,статус
2 Натиснути пошук
3 Переходити зі сторінки на сторінку  по номерах сторінок
4 Переходити зі сторінки на сторінку  стрілочками
Очікуваний результат
Навігація зі сторіни на сторрінку відбувається у межах заданого пошуку незалежно від способу(номер сторінки чи стрілка)
Фактичний результат
Навігація по номерах сторінок відбувається у межах пошуку.
Навігація стрілками обнулює пошук до "всіх " аукціонів

**Comment by ukrosoft** [comment]
Исправлено

**Comment by Ipyt** [comment]
Виправлено
Перевірено.
