### ISSUE TITLE
Не надходить повідомлення про скасування Аукціону, на який Учасник подавав пропозиції

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1533]
http://test-eauction.open-tender.com.ua/

**Description**
На електронну пошту  не надходить повідомлення про скасування Аукціону, на який Учасник подавав пропозиції

**Steps to reproduce**
Подати заяву на участь у Голландському аукціоні
В ЄК скасувати аукціон, до якого було подано пропозицію
Перевірити повідомлення на пошті учасника

**Actual result**
На електронну пошту та не надходить повідомлення про скасування Аукціону, на який Учасник подавав пропозиції.

**Expected result**
Отримати повідомлення про скасування Організатором Аукціону електронною поштою
Якщо скасування відбулось до розкриття пропозицій, пропозиції, подані на скасований аукціон, не розкриваються та не оприлюднюються

**Comment by olyamalysh** [comment]
Виправлено
