### ISSUE TITLE
Учасникам не приходять листи про завершення торгів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1547]
https://zakupki.e-commodity.fbp.com.ua/Bid/ViewBid?nBidID=3900
UA-EA-2017-10-04-000025-2 
ecommod1@yopmail.com
ecommod2@yopmail.com

Кроки відтворення:
0. 1-й Учасник виграв торги. 2-й заняв 2-е місце.
1. Ліквідатор завантажує протокол.
2. Ліквідатор завантажує договір.
3. Ліквідатор завершує торги.

Очікувано:
Обидва учасники отримують повідомлення про завершення торгів.

Фактично: 
Учасники не отримують повідомлень

**Comment by SDiesel** [comment]
Виправили
