### ISSUE TITLE
Кваліфікація. В повідомленнях учасника неправильний час на забирання внеску і підписання протоколу.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1548]
https://zakupki.e-commodity.fbp.com.ua/Bid/ViewBid?nBidID=3900
UA-EA-2017-10-04-000025-2
ecommod1@yopmail.com
ecommod2@yopmail.com

Кроки відтворення:
0. 1-й Учасник виграв торги. 2-й заняв 2-е місце.
1. Другий учасник захобить на майданчик.
2. Другий учасник перевіряє свою поштову скриньку.

Очікувано:
Уаснику що зайняв 2-е місце і в особистому кабінеті і на емейлі повідомляється: Час на забирання гарантійного внеску 20 днів.

Фактично:
Учаснику повідомляється не правильний час на забирання гарантійного внеску (15 днів)

Рекомендація проетного відділу: Брати цей час з ЦБД, так як він може змінюватись.

![image](https://user-images.githubusercontent.com/11888281/31184240-7d04fe98-a931-11e7-9571-7c359e8d30c3.png)

**Comment by SDiesel** [comment]
Виправили 15 на 20 днів, дійсно пропустили.
