### ISSUE TITLE
Кваліфікація. Учасник не має можливості завантажити протокол. 

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1549]
http://proz-test.tbetb.com.ua/auctions?kw=%D0%B1%D0%B2%D0%B2&type=&status=&auctionID=
tbetb1@yopmail.com

Кроки відтворення:
0. 1-й учасник знаходиться на кваліфікації.

Учасник переходить до торгів.
Учасник переходить до своєї ставки.
Очікувано:
Учасник може завантажити протокол.

Фактично:
Учасник не може завантажити протокол

**Comment by w-be** [comment]
Кнопка і відповідний діалог є, але документ до award-у не додається.
https://lb.api-sandbox.ea.openprocurement.org/api/2.5/auctions/4a45da9430d24710a3fb9e1da68605e1
http://proz-test.tbetb.com.ua/auctions/UA-EA-2017-10-09-000063-2
![image](https://user-images.githubusercontent.com/11888281/31336922-bea66638-ad01-11e7-89f7-afa29897b8e6.png)
https://lb.api-sandbox.ea.openprocurement.org/api/2.5/auctions/4a45da9430d24710a3fb9e1da68605e1

**Comment by ukrosoft** [comment]
Загрузка документа исправлена
http://proz-test.tbetb.com.ua/auctions/UA-EA-2017-10-09-000063-2
На этой странице на вкладке "Результаты торгов" можно видеть загруженные документы

**Comment by SoftserveQC1** [comment]
Виправлено
Протокол додається на вкладці "Результати торгів" до позиціїї переможця. Також протокол доданий на вкладці "Документи аукціону" з типом "Протокол торгів"
