### ISSUE TITLE
Кваліфікація. Учасник що зайняв 2-ге місце не може забрати гарантійний внесок.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1550]
http://proz-test.tbetb.com.ua/auctions?kw=%D0%B1%D0%B2%D0%B2&type=&status=&auctionID=
tbetb1@yopmail.com
tbetb2@yopmail.com

Кроки відтворення:
0. 1-й учасник знаходиться на кваліфікації. 2-й зайняв 2-ге місце і чекає розгляду.
1. Учасник 2 переходить до торгів.
2. Учасник 2 переходить до своєї ставки.

Очікувано:
Учасник що заняв 2-е місце може одразу забрати свій внесок .

Фактично:
Учасник що заняв 2-е місце не може забрати внесок.

**Comment by w-be** [comment]
Зараз кнопка забрати внесок веде на: "Сторінк не знайдено".
http://proz-test.tbetb.com.ua/awards/cancel/2104
UA-EA-2017-10-09-000062-2
![image](https://user-images.githubusercontent.com/11888281/31337242-180f646c-ad03-11e7-9e6e-bfe6091b0ad1.png)

**Comment by ukrosoft** [comment]
Поправлено, кнопка отмены ставки теперь работает

**Comment by SoftserveQC1** [comment]
Виправлено
