### ISSUE TITLE
Повідомлення про зайнятя Учасником 2-го місце не містить інформацію про можливасть не забирати внесок протягом 20 днів. 

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1556]
http://proz-test.tbetb.com.ua/accounts/notifications
tbetb2@yopmail.com

Відтворення:
0. Учасник заняв 2-е місце.
1. Учасник перевіряє свої повідомлення та електрону пошту:

Очікувано: Учаснику повідомляють що він може не забирати внесок напротязі 20 днів поки триває кваліфікація.

Фактично: 
"09.10.2017 14:49:02 - Друге місце в аукціоні
Ви зайняли друге місце в аукціоні:UA-EA-2017-10-09-000060-2
Ви можете забрати гарантійний внесок зараз"

![image](https://user-images.githubusercontent.com/11888281/31337470-2d9de334-ad04-11e7-8f3f-9cad83dbb385.png)

**Comment by ukrosoft** [comment]
Необходимая надпись добавлена в уведомления

**Comment by SoftserveQC1** [comment]
Виправлено
