### ISSUE TITLE
Повідомлення та емейли містять не правильні посилання.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1557]
1. Повідомлення та емейли "Торги розпочались/закінчились" не містять значень в тегах {$auction_link}.
2. Всі інші повідомленях містять некоректні посилання на аукціон.

http://proz-test.tbetb.com.ua/accounts/notifications
tbetb2@yopmail.com

Відтворення:
0. Учасник в різних аукціонах: заняв 2-е, 1-ше місця. був дикваліфікований, його торги почались/закінчились, здобув перемогу в торгах.
1. Учасник перевіряє свої повідомлення та електрону пошту:

Очікувано: 
1. Замість тегу підставленне значення UA id та лінк на аукціон.
2. Лінк на аукціон правильний.

Фактично:
1. тег не підставлений.
2: посилання має зайву частину: http://proz-test.tbetb.com.ua/accounts/proz-test.tbetb.com.ua/auctions/UA-EA-2017-10-09-000059-2
![image](https://user-images.githubusercontent.com/11888281/31337987-4e96c194-ad06-11e7-9529-adc377c2e82c.png)

**Comment by ukrosoft** [comment]
Все ссылки, добавляемые в уведомления, исправлены

**Comment by SoftserveQC1** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Виправлено
