### ISSUE TITLE
Повідомлення про зайнятя Учасником 2-го місце не містить інформацію про можливасть не забирати внесок протягом 20 днів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1558]
https://my.zakupki.dz-test.net/cabinet/purchases/state_auction/view/662338
UA-EA-2017-10-10-000065-2
prom2@yopmail.com

Відтворення:
0. Учасник заняв 2-е місце.
1. Учасник перевіряє свої повідомлення та електрону пошту:

Очікувано: Учаснику повідомляють що він може не забирати внесок напротязі 20 днів поки триває кваліфікація.

Фактично:
"Ваше предложение в торгах [ТЕСТУВАННЯ] БВВ - 3 второе в очереди на рассмотрение Организатором торгов. В случае отклонения первого предложения, у вас появится возможность приобрести лот.
Если вы не желаете продолжать участие, отзовите свое предложение на странице аукциона с помощью кнопки "Забрать гарантийный взнос"
![image](https://user-images.githubusercontent.com/11888281/31398874-15ab5e56-adf3-11e7-8be6-c97b40d0c0bf.png)

**Comment by znakharenko** [comment]
Додайте будь ласка посилання на данну вимогу

**Comment by w-be** [comment]
PROZORRO.продажи: Ручные тесты -> Учасник->п10:
https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.1fap1z6or798

**Comment by znakharenko** [comment]
Дякую, проте не розумію що це означає, а 21 день учасник може не забирати? А якщо оберуть першого раніше, то йому гроші повернуться.
Ми переглянемо текст, можливо змінимо.

**Comment by w-be** [comment]
Перевірено на UA-EA-2017-10-11-000080-2 - вже працює.
