### ISSUE TITLE
Кваліфікація. Учасник не може забрати гарантійний внесок.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1559]
https://my.zakupki.dz-test.net/cabinet/purchases/state_auction/view/662338
UA-EA-2017-10-10-000065-2
prom1@yopmail.com

Відтворення:
0. Учасник заняв 2-е місце.
1. Учасник переходить до торгів
2. Учаник натискає кнопку Забрати гарантійний внесок.

Очікувано: Статус пропозиції переходить в відмінено. Кнопка зникає з інтерфейсу. Відправляється емейл на електрону пошту учасника.

Фактично: Кнопка зникає з інтерфейсу. Відправляється емейл на електрону пошту учасника.

**Comment by niksdorf** [comment]
на dz-test был выключен функционал который и повлек за собой данный кейс
вопрос решен.
