### ISSUE TITLE
Кваліфікація. Учасник не може завантажити протокол торгів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1564]
http://e-auction.pro/#/tenderDetailes/a75866235fee479d85329bce4fc86a7d
eauc2@yopmail.com
UA-EA-2017-10-12-000087-2

Відтворення:
0. Учасник виграв аукціон і знаходиться на стадії кваліфікації.
1. Зайти учасником на торги
2. Перейти до діалогу завантаження документу.
3. Завантажити документ протокол.
4. Почекати 5 хв.
5. Перевірити наявність докумунту зі сторони ліквідатор чи в json-і торгів.

Очікувано: Підчас кваліфікації можна додавати до пропозиції документи - протокол.

Фактично: Документ додається тільки на майданчику і є видимий тільки з майданчика. і не відображається ліквідатору. (pdf-sample.pdf, [Поки не експортовано])
![image](https://user-images.githubusercontent.com/11888281/31539747-3d7d75f6-b012-11e7-977e-5dd31c965e02.png)

**Comment by OlegNekovalev** [comment]
Виправили
![default](https://user-images.githubusercontent.com/23699721/31664363-cb9ca8c8-b34d-11e7-830b-fbea8afd5f09.png)
