### ISSUE TITLE
ЕЛЕГ, на аукціоні, учасник має можливість змінити ціну на "-1"

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#157]
![minus_bid](https://cloud.githubusercontent.com/assets/11062040/6579806/44353e40-c755-11e4-9921-e7df0cc7853a.png)

**Comment by ktarasz** [comment]
вже проблема виправлена і зміни поступили на http://auction-sandbox.openprocurement.org/

**Comment by OksanaPakholok** [comment]
03/11/2015, http://services.e-tender.biz:100/#/ 
Не репродюситься
