### ISSUE TITLE
Closed auction. Contract document is not displayed for successful auction.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1576]
https://uat.kpmgdealroom.com/ExternalExchange/Bids/Phases/6515edbe-fcfa-47eb-836e-64d91aa9927c
kpmg2@yopmail.com
UA-EA-2017-11-24-000011-2

Steps to reproduce:
1. Find finished auction.
2. Open auction details.
3. Go to the bids
4. Check winner's documents

Expected result: Documents contains contract.

Actual result: There is no contract displayed in finished auction.

![image](https://user-images.githubusercontent.com/11888281/33324093-38f82df0-d457-11e7-8253-e4407a7d12de.png)

**Comment by w-be** [comment]
Behavior is the same:
![image](https://user-images.githubusercontent.com/11888281/33901198-b69bcf6e-df79-11e7-8dd5-80366f69f3f3.png)
https://test.kpmgdealroom.com/ExternalExchange/Bids/Phases/03d47888-be76-434e-b4bf-37f7241fc0e7

**Comment by bhanupasham** [comment]
Viktor, contract documents will be availble on the Dataroom page after the auction is completed
![image](https://user-images.githubusercontent.com/34480924/33989388-3cd2f454-e0bf-11e7-8109-a53848d243f6.png)
![image](https://user-images.githubusercontent.com/34480924/33989401-48e712ca-e0bf-11e7-9900-0bb5e15df2c3.png)

**Comment by medhavinautiyal** [comment]
Hi Victor, please note that we have now fixed this issue and the contract documents are available on the bids page 
<img width="960" alt="contractonbidspage" src="https://user-images.githubusercontent.com/29541311/34300151-b37317e6-e71e-11e7-901f-5d1d23c05e52.png">

**Comment by medhavinautiyal** [comment]
Please verify the fix. Thanks!

**Comment by scoolic** [comment]
@w-be
