### ISSUE TITLE
Mailing/Messaging. No message for auction finish.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1577]
https://uat.kpmgdealroom.com/ExternalExchange/Bids/Phases/6515edbe-fcfa-47eb-836e-64d91aa9927c
kpmg2@yopmail.com
kpmg7@yopmail.com
UA-EA-2017-11-24-000011-2

Steps to reproduce:
0. On clarification 1-st user is on first place 2-d on send place. 
1. Clarify first user as winner - by liquidator.
2. Upload contract and close auction. - by liquidator.
3. Check the winner's mailbox.
4. Check the winner's messages.
5. Check the mailbox of user on 2-nd place.
6. Check the messages of user on 2-nd place.

Expected result: The involved users are informed about auction finish.

Actual result: There are no messages and emails about auction finish to involved users: awarding 1-st place and awarding 2-nd place.

**Comment by w-be** [comment]
It is still reproduced.
kptest1@yopmail.com
kptest2@yopmail.com
https://test.kpmgdealroom.com/ExternalExchange/ca03ad7a-d1ce-4036-acb0-989ce758eb23
UA-EA-2017-12-13-000009-2

**Comment by bhanupasham** [comment]
Hi Viktor, i have checked it now and both users can see the system and email notification.
![image](https://user-images.githubusercontent.com/34480924/33991842-38d4c8ba-e0c8-11e7-929d-b725df569206.png)
![image](https://user-images.githubusercontent.com/34480924/33991851-4535bc40-e0c8-11e7-935d-312ebd8aacbc.png)
Can you please try again

**Comment by bhanupasham** [comment]
Hi Viktor, 
I tried the same scenario and after the auction is completed after signing the contracts and everything, both bidders are able to receive the email and system notifications.

Buyer1: System notification
![image](https://user-images.githubusercontent.com/34480924/34000679-dea96aee-e0e5-11e7-8982-d02aa92f5bae.png)

Buyer1: Email notification
![image](https://user-images.githubusercontent.com/34480924/34000693-eb0beb36-e0e5-11e7-84cf-7208066d2bb6.png)

Buyer 2 Email notification:
![image](https://user-images.githubusercontent.com/34480924/34000716-fbe18830-e0e5-11e7-9910-4ae6ae513621.png)

**Comment by w-be** [comment]
The bug is reproduced on UA-EA-2017-12-14-000017-2 with users kptest1@yopmail.com and kptest2@yopmail.com. Could it be relate to Ukrainian language of buyers?

**Comment by tejasshukla** [comment]
Hi @w-be , we have now fixed the issue. Could you please retest this and confirm.

**Comment by scoolic** [comment]
@w-be
