### ISSUE TITLE
ЕЛЕГ, "Internal Server Error" при створенні тендера

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#158]
Зараз, був доданий новий функціонал, при створенні тендера - "Координати", і тільки одне обов'язкове поле - "Довгота". При заповненні тендера (усіх обов'язкових полів) виникає помилка.

![create_tender_new](https://cloud.githubusercontent.com/assets/11062040/6581410/6cd7497e-c75f-11e4-9e48-cf7784e5b199.png)

**Comment by S-Shevchenko** [comment]
Дякую,помилка буде виправлена в поточному білді.

**Comment by S-Shevchenko** [comment]
@OksanaPakholok Виправили, будь ласка перевірте.

**Comment by OksanaPakholok** [comment]
Чи є певна валідація на поля координат?
Зараз помилки немає, але можна ввести наприклад таке "◄☼►"
Чи це очікувана поведінка аплікації?

@SergeyShevchenko1

**Comment by OksanaPakholok** [comment]
Також поправти будь-ласка UI

![improvement](https://cloud.githubusercontent.com/assets/11062040/6616117/5715a5a4-c8b3-11e4-8d21-02e332dfdc0b.png)

**Comment by lerich** [comment]
Валидации нет, так как не известно по каким правилам валидировать. Валидация должна быть по единым правилам с ЦБД. Вопрос поднимал на коле, но не получил ответа.

**Comment by OksanaPakholok** [comment]
На даний час, на етапі створення тендера, при заповненні всіх обовязкових полів, тендер не створюється (залишається у тому ж стані)

![same_position](https://cloud.githubusercontent.com/assets/11062040/6636060/1e47954e-c975-11e4-86b8-19b561f32480.png)

@lerich

**Comment by OksanaPakholok** [comment]
https://github.com/openprocurement/frontend/issues/167

**Comment by S-Shevchenko** [comment]
Исправлено.Можно закрывать.
