### ISSUE TITLE
DTO: На сторінці реєстрації користувача є тип BUYERS#2, поля якого дублюють поля для типу Замовник

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1580]
http://www.dz3.byustudio.in.ua/registration/buyers

Відтворення:
1. Перейти на майданчик
2. Натиснути кнопку "Реєстрація"
3. Оглянути перелік "Тип Реєстрації"

Очікуваний результат: Можливо обрати такі типи: 
1. Замовник
2. Учасник
3. Гість

Фактичний результат: Присутній тип "BUYERS#2"
![type](https://user-images.githubusercontent.com/13050207/33433269-96de7658-d5e3-11e7-86be-a18275af0bcf.png)

**Comment by IllyaPetrusenko** [comment]
Данная площадка работает с ЦБД-1 и ЦБД-2 . Замовник - регистрация Организатора для ЦБД-1, BUYERS#2 - регистрация Замовника для ЦБД-1 
Прошу закрыть дефект.

**Comment by w-be** [comment]
Не український тест не припустимий. Замовник в ЦБД 1 то "Ліквідатор".

**Comment by SoftserveQC1** [comment]
Відтворюється

**Comment by SoftserveQC1** [comment]
![2018-03-02_1436](https://user-images.githubusercontent.com/13050207/36900302-7028bc90-1e2b-11e8-85ee-ed3049e5ab91.png)
пофікшено
