### ISSUE TITLE
DTO: Вкладка "Налаштування" у кабінеті Учасника переміщається у "гамбургер" меню "Ще"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1582]
Microsoft Edge
http://www.dz3.byustudio.in.ua

Відтворення:
1. Увійти у систему як Учасник.
2. Натиснути на вкладку "Налаштування".

Фактичний результат: Сторінка налаштувань відкрита але вкладка зникла.
3. Натиснути на "гамбургер" меню "Ще"
Фактичний результат: у "гамбургер" меню є "Налаштування" та "Вихід".
4. Перезавантажити сторінку.
Фактичний результат: Вкладка "Налаштування" повернулась на своє місце.
![step1](https://user-images.githubusercontent.com/13050207/33435370-abbcfaa2-d5ea-11e7-92f0-86d94cd0e067.png)
![step2](https://user-images.githubusercontent.com/13050207/33435379-b094ee9a-d5ea-11e7-9b32-64d22480a9b6.png)

Очікуваний результат: вкладка "Налаштування" не має нікуди переміщуватись.

**Comment by IllyaPetrusenko** [comment]
Если пункт влазит на страницу, то он отображается в "нав-баре", если нет, то прячется в "Ще".
Прошу закрыть открытый дефект.
