### ISSUE TITLE
При створенні аукціону з Оренди відсутня можливість обрати одиниці виміру, константно встановлено м.кв.

### ISSUE THREAD

**Issue by olyamalysh** [openprocurement/frontend#1583]
Description
При створенні аукціону з Оренди відсутня можливість обрати одиниці виміру, константно встановлено "м.кв."

Steps to reproduce

Увійти в аккаунт, під роллю “Замовника”
Натиснути лінку “Створити аукціон”
Обрати тип "Оренда"
Перейти до блоку "Склад лоту"

Actual result
В аукціоні з Оренди відсутня можливість обрати одиниці виміру, константно встановлено "м.кв."

Expected result
В аукціоні з Оренди є можливість обрати одиниці виміру, окрім випадку, коли обрано CAV нерухомість

**Comment by IllyaPetrusenko** [comment]
Виправлено. Можете перевіряти та закривати дефект.

**Comment by olyamalysh** [comment]
Перевірено. Дефект не відтворюється.
