### ISSUE TITLE
DTO:  відсутні причини скасування аукціону.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1584]
http://www.dz3.byustudio.in.ua/

Передумова:
1. Залогінитись як Замовник 
2. Натиснути кнопку "Створити аукціон"
3. Обрати тип оголошення "Оренда"
4. Заповнити усі поля валідними даними та опублікувати аукціон

Відтворення:
1. Обрати попередньо створений аукціон з оренди
2. Внизу тіла аукціону натиснути кнопку "Відмінити"
3. Натиснути кнопку "ОК" на повідомленні "Ви дійсно бажаєте відмінити оголошення про аукціон?"
4. Завантажити документ.
5. Вказати причину.
6. Натиснути "Зберегти"

Очікуваний результат:  У вікні "Причини скасування аукціону", замість причин є один радіобаттон "111"
![cancel](https://user-images.githubusercontent.com/13050207/33603533-7f1567f8-d9bb-11e7-8e89-3390a0e8dfdf.png)

Фактичний результат: Замовник може скасувати аукціон завантаживши документ та вибравши причину скасування. Причини:
1. Згідно рішення виконавчої дирекції Замовника
2. Порушення порядку публікації оголошення

**Comment by IllyaPetrusenko** [comment]
Исправлено. Прошу закрыть дефект.

**Comment by SoftserveQC1** [comment]
Дефект виправлено і перевірено.
