### ISSUE TITLE
OpenTender: Замовник НЕ отримуе нагадування (щодня) про запитання до Лоту електронною поштою

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1585]
open-tender
http://test-eauction.open-tender.com.ua

**Передумова:**
1. Залогінитись як Замовник
2. Натиснути кнопку "Створити аукціон"
3. Обрати тип оголошення "Оренда"
4. Заповнити усі поля валідними даними та опублікувати аукціон

**Відтворення:**
1. Залогінитись як Учасник
2. Вибрати створенний аукицон
3. Натиснути кнопку "Запитання-вiдповiдi"
4. Заповнити усі поля та створити запитання
5. Замовник ни вiдповiдае на запитання на протязi доби

**Очікуваний результат:**
Замовник отримуе нагадування (щодня) про запитання до Лоту електронною поштою

**Фактичний результат:** 
Замовник НЕ отримуе нагадування (щодня) про запитання до Лоту електронною поштою

**Comment by IllyaPetrusenko** [comment]
Принято.

**Comment by IllyaPetrusenko** [comment]
Ми посилаємо нагадування на наступні сутки. У перші сутки нотіфікація є у кабінеті.
 Прошу перевірити та закрити дефект.
