### ISSUE TITLE
DTO: Замовник не може дискваліфікувати переможця бо не завантажується документ

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1589]
http://www.dz3.byustudio.in.ua
Передумови:
1. Увійти як Замовник
2. Створити аукціон
3. Провести аукціон для визначення переможця.
4. Відкрити аукціон зі статусом "Кваліфікація переможця"
5. Проскролити сторінку вниз до пункту "Кваліфікація переможця"
6. Натиснути кнопку "Дискваліфікувати"
7. Завантажити документ та натиснути кнопку "Додати"

Очікуваний результат: Документ доданий, всі поля заповнені і після натискання "Зберегти" учасника дискваліфіковано.

Фактичний результат: після вибору документа та натискання кнопки "Додати" форма стає пуста, тому не можливо дискваліфікувати учасника.

**Comment by IllyaPetrusenko** [comment]
Виправлено. Прошу закрити дефект.

**Comment by SoftserveQC1** [comment]
Документи завантажуються. Дефект виправлено і перевірено.
