### ISSUE TITLE
ЕЛЕГ, дублікація атачменту при підписанні контракту

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#159]
![duplication_contract_1](https://cloud.githubusercontent.com/assets/11062040/6595371/77a333a2-c7f2-11e4-9b93-dd6e37deee40.png)

Результат, при повторному нажатті кнопки "Контракт"

![duplication_contract_2](https://cloud.githubusercontent.com/assets/11062040/6595421/e03abe30-c7f2-11e4-9b78-0e7338aee801.png)

**Comment by S-Shevchenko** [comment]
Задача устаревшая. Исправлено с новым функционалом.
