### ISSUE TITLE
DTO: Замовник не може завантажити протокол 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1590]
http://www.dz3.byustudio.in.ua
Передумови:
1. Зареєструватись як Замовник
2. Створити аукціон
3. Провести аукціон для визначення переможця
4. Перейти на сторінку аукціону зі статусом "Кваліфікація переможця"

Очікуваний результат: Замовник має завантажити та підтвердити протокол.
Фактичний результат: Для Замовника не реалізовано можливості завантажити протокол, він може переглянути документи додані учасником до пропозиції.

**Comment by IllyaPetrusenko** [comment]
Виправлено. Прошу закрити дефект

**Comment by SoftserveQC1** [comment]
Дефект виправлено і перевірено.
