### ISSUE TITLE
Govfound: Замовник НЕ отримує нагадування (щодня) про запитання до Лоту електронною поштою 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1591]
open-tender
http://test.gov.auction

**Description**
Залогінитись як Замовник
Натиснути кнопку "Створити аукціон"
Обрати тип оголошення "Оренда"
Заповнити усі поля валідними даними та опублікувати аукціон

**Steps to reproduce**
Залогінитись як Учасник
Вибрати створенний аукицон
Натиснути кнопку "Запитання-вiдповiдi"
Заповнити усі поля та створити запитання
Замовник ни вiдповiдае на запитання на протязi доби

**Actual result**
Замовник НЕ отримує нагадування (щодня) про запитання до Лоту електронною поштою

**Expected result**
Замовник отримуе нагадування (щодня) про запитання до Лоту електронною поштою

**Comment by IllyaPetrusenko** [comment]
Ми посилаємо нагадування на наступні сутки. У перші сутки нотіфікація є у кабінеті.

**Comment by IllyaPetrusenko** [comment]
Прошу це перевірити та закрити дефект

**Comment by SoftserveQC1** [comment]
На наступну добу повідомлення так і не прийшло

**Comment by IllyaPetrusenko** [comment]
А аукцион в каком статусе?

**Comment by SoftserveQC1** [comment]
Пофикшено!
