### ISSUE TITLE
Govfound: При створенні аукціону з Оренди відсутня можливість обрати одиниці виміру, константно встановлено м.кв.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1592]
open-tender
http://test.gov.auction

**Description**
При створенні аукціону з Оренди відсутня можливість обрати одиниці виміру, константно встановлено "м.кв."

**Steps to reproduce**
Увійти в аккаунт, під роллю “Замовника”
Натиснути лінку “Створити аукціон”
Обрати тип "Оренда"
Перейти до блоку "Склад лоту"

**Actual result**
В аукціоні з Оренди відсутня можливість обрати одиниці виміру, константно встановлено "м.кв."

**Expected result**
В аукціоні з Оренди є можливість обрати одиниці виміру, окрім випадку, коли обрано CAV нерухомість

**Comment by IllyaPetrusenko** [comment]
Виправлено. Прошу закрити дефект

**Comment by SoftserveQC1** [comment]
Не відображаються зміни
![image](https://user-images.githubusercontent.com/13050207/33839846-fa8e53ba-de9b-11e7-8b0e-f7b8f1badde1.png)

**Comment by IllyaPetrusenko** [comment]
http://storage8.static.itmages.com/i/17/1212/h_1513066262_2133620_9019408b50.jpeg
Не воспроизводится.

**Comment by SoftserveQC1** [comment]
Теперь все ок
