### ISSUE TITLE
OpenTender: Замовник не може завантажити протокол 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1593]
open-tender
http://test-eauction.open-tender.com.ua

**Передумови:**
1. Зареєструватись як Замовник
2. Створити аукціон
3. Провести аукціон для визначення переможця
4. Перейти на сторінку аукціону зі статусом "Кваліфікація переможця"

**Очікуваний результат:** 
Замовник має завантажити та підтвердити протокол.

**Фактичний результат:** 
Для Замовника не реалізовано можливості завантажити протокол.

**Comment by IllyaPetrusenko** [comment]
виправлено. прошу закрити дефект.
