### ISSUE TITLE
OpenTender: Учасник не може завантажити протокол 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1594]
open-tender
http://test-eauction.open-tender.com.ua

**Передумови:**
1. Зареєструватись як Учасник
2. Взяти участь в аукціоні і перемогти в ньому
3. Перейти на сторінку аукціону зі статусом "Кваліфікація переможця"

**Очікуваний результат:**
Учасник має завантажити та підтвердити протокол.

**Фактичний результат:**
Для Учасника не реалізовано можливості завантажити протокол.

**Comment by IllyaPetrusenko** [comment]
Виправлено. Прошу закрити дефект
