### ISSUE TITLE
Govfound: після завершення аукціону учаснику приходить неправильний текст у листі на пошту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1596]
Стосується першого в списку учасника, який знаходиться на розгляді ![941fde1b9e](https://user-images.githubusercontent.com/13050207/33835410-1327b91e-de8f-11e7-936d-316a1a875f24.png)

**Comment by IllyaPetrusenko** [comment]
Виправлено, прошу закрити дефект.

**Comment by SoftserveQC1** [comment]
Пофикшено
