### ISSUE TITLE
Govfound: неправильний текст в листі до переможця, якщо учасник був один

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1597]
Не зрозуміло, що учасник є переможцем та не описані наступні дії ![05734ae09b](https://user-images.githubusercontent.com/13050207/33836099-259ec68a-de91-11e7-9e24-38ce0ed47c60.png)

**Comment by IllyaPetrusenko** [comment]
Виконано.

**Comment by SoftserveQC1** [comment]
Пофикшено
