### ISSUE TITLE
Govfound: внести зміни до пропозиції можна без підтвердження майданчиком

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1598]
open-tender
http://test.gov.auction

**Description**
Після підтвердження майданчиком ставки учасник може її змінити без підтвердження майданчиком.

**Steps to reproduce**
Увійти в аккаунт, під роллю “Учасника”
Зайти в аукціон
Відправити пропозицію
Дочекатися підтвердження пропозиції майданчиком
Внести зміни

**Actual result**
Ставка успішно змінена, підтвердження модератора не потрібне.

**Expected result**
Тест-кейс25: Учасник в особистому кабінеті отримує повідомлення про прийняття пропозиції Майданчиком та початку валідації Учасника та/або перевірку гарантійного внеску/банківської гарантії

**Comment by IllyaPetrusenko** [comment]
Предложение проверяется площадкой при первой подаче. Проверяются документы, оплата гар. взноса. Изменить предложение по регламенту участник имеет право до завершения срока приёма предложений. Это реализовано.
