### ISSUE TITLE
Govfound: помилка після зміни поточної дати підписання договору, яка вибрана за замовчуванням

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1599]
**open-tender**
http://test.gov.auction

**Description**

**Steps to reproduce**
Увійти в аккаунт під роллю “замовника”
Створити аукціон
Дочекатися закінчення строку подачі пропозицій
Дочекатися початку періоду кваліфікацій
Перейти до таблиці кваліфікацій
Завантажити протокол
Натиснути "перейти до підписання контракту"
Дочекатися появи кнопки "контракт", натиснути її
Завантажити договір, ввести назву та змінити час підписання

![image](https://user-images.githubusercontent.com/13050207/33838782-370d9cae-de99-11e7-8afd-a4f04320df09.png)
**Actual result**
Помилка

![image](https://user-images.githubusercontent.com/13050207/33838411-2113994a-de98-11e7-968e-cd3ec75703eb.png)

**Expected result**
Контракт успішно завантажується, через деякий час з'являється кнопка "Завершити електронні торги"

**Comment by IllyaPetrusenko** [comment]
Принято.

**Comment by IllyaPetrusenko** [comment]
Виправлено.

**Comment by SoftserveQC1** [comment]
Пофикшено
