### ISSUE TITLE
ЕЛЕГ, учасник не бачить факту зміни та версійності файлів, що замовник змінив чи видалив в "Період уточнень"

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#160]
![notvisible_changedfiles](https://cloud.githubusercontent.com/assets/11062040/6602735/38264e74-c826-11e4-885e-912688e6a369.png)

Посилання на https://github.com/openprocurement/frontend/issues/92

**Comment by S-Shevchenko** [comment]
Дякую, задача в роботі.

**Comment by SergeDmitriev** [comment]
Виправили, тепер біля полів все відображається коректно

**Comment by SergeDmitriev** [comment]
Випавлено, тепер все відображається коректно

**Comment by SergeDmitriev** [comment]
Випавлено, тепер все відображається коректно
