### ISSUE TITLE
Place a bid. It is not possible to add/update document in submitted bid.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1602]
https://test.kpmgdealroom.com/ExternalExchange/Bids/Submit/f21444cb-dfa6-4277-a05d-d41679a6f5ba?bidPhaseId=1c5f0714-0c02-43c7-9a21-95514bfd1a05
kptest2@yopmail.com
UA-EA-2017-12-12-000012-2

Steps to reproduce:
1. Find the auction in the tendering state.
2. Open it.
3. Navigate to Bid tab (Заявки).
4. Please a bid.
5. Add documents to the bid.
6. Send the bid to aproove
7. Try to add document. Try to replace document.

Expected result: There is functionality for add document to approved bid. There is a functionality for replace document. 

Actual result: There only possibility for replacing/adding documents are cancel bid and place it one more time.

![image](https://user-images.githubusercontent.com/11888281/33882536-19e14f56-df41-11e7-9750-37b8a83ea615.png)

**Comment by bhanupasham** [comment]
![image](https://user-images.githubusercontent.com/34480924/33895701-fefc98b8-df58-11e7-8baa-2ffd0f00e58e.png)
User can click on reset button and upload documents. Please can you retry using this button
