### ISSUE TITLE
Auction Cancellation. There is no notification about action cancellation for auction buyer take part.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1603]
https://test.kpmgdealroom.com/ExternalExchange/Faq/91bafc22-820b-424d-b647-83c96d8c5590
UA-EA-2017-12-12-000015-2
kptest1@yopmail.com
kptest2@yopmail.com

Steps to reproduce:
1. Find the auction tendering period.
2. Open auction.
3. Ask the question to the auction.
4. Login with different buyer.
5. Find the same auction.
6. Open it.
7. Place a bid.
8. Open auction with it's creator.
9. Cancel the auction.
10. Check mailboxes and messages of involved users.

Expected result:
There are messages in application and in email box about auction cancellation for buyer who a) ask question; b) place bid.

Actual result:
There are no messages in application and in email box about auction cancellation for buyer who a) ask question; b) place bid.

![image](https://user-images.githubusercontent.com/11888281/33884350-f802ce44-df47-11e7-97b5-8a05f23d73ac.png)

**Comment by bhanupasham** [comment]
![image](https://user-images.githubusercontent.com/34480924/33892046-abedfb70-df4f-11e7-8f8f-f76834af8d44.png)
I followed your steps and i can see the system notification and email notification as well.

Can you recheck it please.

**Comment by w-be** [comment]
I'm still able to reproduce bug. Please, find video in Slack. https://files.slack.com/files-pri/T1H659USE-F8DDGGPJ4/record-16.48.51_13.12.2017__1603
