### ISSUE TITLE
Katerynoslav: всі учасники крім переможця отримують повідомлення, що вони є кандидатами, наступними за переможцем

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1604]
https://sale-tbe.com.ua/test/
Передумови:
1. Увійти як Замовник
2. Створити аукціон
Відтворення:
1. Увійти як учасник 1
2. подати пропозицію до аукціону
3. Увійти як Учасник 2 і подати пропозицію до аукціону з кроку 2.
4. Увійти як Учасник 3 і подати пропозицію до аукціону з кроку 2.
5. Всі учасники переходять до аукціону і беруть в ньому участь.

Очікуваний результат: 
1. учасник з найбільшою ціновою ставкою стає переможцем і отримує повідомлення в кабінеті і на пошті.
2. учасник з другою по величині ціновою ставкою стає кандидатом, наступним за переможцем і отримує відповідне повідомлення в кабінеті і на пошті.
3. Всі решта учасники отримують повідомлення на пошту і в кабінет про можливість забрати гарантійний внесок.
4. У випадку дискваліфікації переможця, переможцем стає учасник з другою ціновою пропозицією.
5. У випадку дискваліфікації і другого переможця аукціон переходить у статус не відбувся.

Фактичний результат: Перший переможець, а всі решта - кандидати, наступні за переможцем. У випадку дискваліфікації двох перших, переможцем стає наступний  (3) учасник.
![image](https://user-images.githubusercontent.com/13050207/33936861-c067f08c-e009-11e7-9852-19ca75d3fb57.png)
![35 2 ua-ps](https://user-images.githubusercontent.com/13050207/33937116-e2b1ec3c-e00a-11e7-9026-a1b95b4c1a35.png)

![36 1 ua-ps-2017-12-12-000115-2 - google chrome 2017-12-13 13 31 46](https://user-images.githubusercontent.com/13050207/33936936-0ad1f71c-e00a-11e7-9210-3395c3e910cd.png)

**Comment by SoftserveQC1** [comment]
Відтворюється на майданчику http://sets.org.ua/
![33](https://user-images.githubusercontent.com/13050207/34299233-882b5556-e72a-11e7-9eec-06538e92affd.png)

**Comment by slavavitrenko** [comment]
Исправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено та перевірено.
