### ISSUE TITLE
NewTend: Користувач НЕ отримує повідомлення електронною поштою 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1605]
NewTend
https://cdb2-dev.newtend.com

**Передумови:**
1. Зареєструватись як Замовник / Учасник
2. Заповнити необхіднi поля значеннями потрібного типу 

**Очікуваний результат:**
1. Користувач отримує повідомлення про те, що обліковий запис знаходиться в стадії перевірки.
2. Користувач отримує повідомлення електронною поштою про те, що його запис або активований, або треба виправити помилки.

**Фактичний результат:**
1. Користувач НЕ отримує повідомлення про те, що обліковий запис знаходиться в стадії перевірки.
2. Користувач НЕ отримує повідомлення електронною поштою про те, що його запис або активований, або треба виправити помилки.

**Comment by SlaOne** [comment]
исправили настройки почтовика.
необходимо, было, дополнительно зарегистрироваться пользователями с "живыми" почтовыми адресами отличными от @mailinator.com, @yopmail.com... и так далее.

**Comment by SoftserveQC1** [comment]
1605 - Pass - Fixed - особенности настройки почтового сервера
