### ISSUE TITLE
Utsb: всі учасники крім переможця отримують повідомлення, що вони є кандидатами, наступними за переможцем

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1606]
https://tb.kiev.ua/test

**Передумови:**
Увійти як Замовник
Створити аукціон

**Відтворення:**
Увійти як учасник 1
подати пропозицію до аукціону
Увійти як Учасник 2 і подати пропозицію до аукціону з кроку 2.
Увійти як Учасник 3 і подати пропозицію до аукціону з кроку 2.
Всі учасники переходять до аукціону і беруть в ньому участь.

**Очікуваний результат:**
Учасник з найбільшою ціновою ставкою стає переможцем і отримує повідомлення в кабінеті і на пошті.
Учасник з другою по величині ціновою ставкою стає кандидатом, наступним за переможцем і отримує відповідне повідомлення в кабінеті і на пошті.
Всі решта учасники отримують повідомлення на пошту і в кабінет про можливість забрати гарантійний внесок.
У випадку дискваліфікації переможця, переможцем стає учасник з другою ціновою пропозицією.
У випадку дискваліфікації і другого переможця аукціон переходить у статус не відбувся.

**Фактичний результат:** 
Перший переможець, а всі решта - кандидати, наступні за переможцем. У випадку дискваліфікації двох перших, переможцем стає наступний (3) учасник.
![default](https://user-images.githubusercontent.com/13050207/33999009-eca20316-e0f1-11e7-9375-468d8fcff76f.jpg)

**Comment by v-lego** [comment]
Внесено зміни; тільки другий претендент отримує повідомлення "Вашу пропозицію визнано кандидатом, наступним за переможцем. ..."
Інші - "Вас не обрано до переліку претендентів, виконайте запит на повернення гарантійного внеску"

**Comment by SoftserveQC1** [comment]
Пофикшено
