### ISSUE TITLE
Utsb: в Edge не правильно відображається час до початку аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1607]
https://tb.kiev.ua/test

**Передумови:**
Увійти як Замовник
Створити аукціон

**Відтворення:**
Увійти як учасник 1 і подати пропозицію до аукціону
Увійти як Учасник 2 і подати пропозицію до аукціону з кроку 2.
Всі учасники переходять до аукціону і беруть в ньому участь.

**Очікуваний результат:**
Перед початком аукціону у верхній частині сторінки відображається таймер зі зворотнім відліком часу до початку аукціону однаково для всіх учасників та у всіх браузерах.

**Фактичний результат:**
В браузері Edge час не співпадає з тим же часом у браузері Chrome у іншого учасника аукціону.

**Comment by v-lego** [comment]
На жаль, відображення відображення проведення аукціону проводиться не на майданчику

**Comment by SoftserveQC1** [comment]
Закриваємо
