### ISSUE TITLE
Utsb: повідомлення з посиланням на проведення аукціону не достатньо інформативне

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1608]
https://tb.kiev.ua/test

**Передумови:**
Увійти як Замовник
Створити аукціон

**Відтворення:**
Увійти як учасник 1 і подати пропозицію до аукціону
Увійти як Учасник 2 і подати пропозицію до аукціону з кроку 2
Дочекатися завершення періоду пропозицій

**Очікуваний результат:**
Учасники отримують повідомлення з посиланням, з якого буде зрозуміло, що аукціон буде проводитися за цим посиланням. Потрібно змінити текст, наприклад на "Аукціон буде проводитися за Посиланням"

Фактичний результат:
В тексті повідомлення зайва кома та неузгоджені члени речення
![1d4e157f26](https://user-images.githubusercontent.com/13050207/33999607-90aed60e-e0f3-11e7-81ff-6b554c38beaa.png)

**Comment by v-lego** [comment]
Було пропущено час аукціону
Внесено зміни
![default](https://user-images.githubusercontent.com/24773833/34105212-14a4439e-e3fc-11e7-88a4-3a6a12dfeeb7.png)

**Comment by SoftserveQC1** [comment]
Пофікшено
