### ISSUE TITLE
Utsb: на останніх хвилинах періоду прийому пропозицій не відображається час до закінчення

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1609]
https://tb.kiev.ua/test

Передумови:
Увійти як Замовник або Учасник
Перейти на сторінку зі списком аукціонів
Дочекатися, поки в одного з активних аукціонів період подання пропозицій буде підходити до завершення

Очікуваний результат:
Час відображається до останньої хвилини в зворотному порядку

Фактичний результат:
В певний момент у прогресбарі час не відображається

![29f3f6e2d1](https://user-images.githubusercontent.com/13050207/33999868-5c481ee2-e0f4-11e7-9210-0210529ab525.png)

**Comment by v-lego** [comment]
Внесли відображення секунд для останньої хвилини
![default](https://user-images.githubusercontent.com/24773833/34105622-c17bc24e-e3fd-11e7-9fb7-7bad683e3a1e.png)

**Comment by SoftserveQC1** [comment]
Пофікшено
