### ISSUE TITLE
ЕЛЕГ, Замовник, що зайшов під своїм обліковим записом, не бачить повідомлення про нове запитання (яке створив учасник)

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#161]
![no_message](https://cloud.githubusercontent.com/assets/11062040/6603252/88fe17ac-c829-11e4-97b3-4e13bb358efd.png)

Посилання на https://github.com/openprocurement/frontend/issues/91

**Comment by S-Shevchenko** [comment]
Дякую, взяли в роботу

**Comment by S-Shevchenko** [comment]
Задача не актуальна, функционал по сообщениям будет реализован в другом формате. может закрывать.
