### ISSUE TITLE
Utsb: В Edge важлива інформація на різних етапах не підсвічена жовтим фоном

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1610]
https://tb.kiev.ua/test
На різних етапах створення аукціону, підтвердження кваліфікації інформація з подальшими кроками не виділена жовтим фоном.
![1e52341eb1](https://user-images.githubusercontent.com/13050207/34000102-fef32f74-e0f4-11e7-9674-85dcd500f045.jpg)

![9baaeafce4](https://user-images.githubusercontent.com/13050207/34000254-649ea8e4-e0f5-11e7-8268-e0c395725d6c.png)

**Comment by v-lego** [comment]
Внесено зміни до кольору
![default](https://user-images.githubusercontent.com/24773833/34107811-40b3e8f4-e406-11e7-9505-a8313835f918.png)

**Comment by SoftserveQC1** [comment]
Перевірено
