### ISSUE TITLE
Utsb: Чернетка після публікації залишається в списку лотів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1611]
https://tb.kiev.ua/test

**Передумови:**
Увійти як Замовник
Створити чернетку аукціону
Опублікувати аукціон

**Очікуваний результат**
Чернетка перетворилася в активний аукціон

**Фактичний результат**
Чернетка знаходиться в списку аукціонів, та не має статусу "чернетка".
![9baaeafce4](https://user-images.githubusercontent.com/13050207/34000306-9017f660-e0f5-11e7-93f6-0f2add6e0a7d.png)
Доступні дії "скасувати" та "створити копію". Опублікувати чернетку неможливо.
![9baaeafce4](https://user-images.githubusercontent.com/13050207/34000479-1afff336-e0f6-11e7-8cd9-7497777de389.png)

**Comment by v-lego** [comment]
Внесено зміни: опубліковані чернетки не відображуються

**Comment by SoftserveQC1** [comment]
Пофікшено
