### ISSUE TITLE
Utsb: не можливо подати питання на окрему позицію, лише на лот в цілому

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1612]
https://tb.kiev.ua/test

**Передумови:**
Увійти як Замовник
Створити аукціон
Увійти як Учасник
Подати запитання

**Очікуваний результат:**
Є можливість подати запитання на окрему позицію та на лот в цілому

**Фактичний результат:**
Є можливість подати запитання лише  на лот в цілому
![6a20a19e9f](https://user-images.githubusercontent.com/13050207/34001186-0331f6d0-e0f8-11e7-8a71-2aac096e32ec.jpg)

**Comment by v-lego** [comment]
Можливість подання питання за позицією знаходиться під самою позицією

![default](https://user-images.githubusercontent.com/24773833/34103987-50dd581e-e3f7-11e7-8b6d-aca753f025ef.png)
![default](https://user-images.githubusercontent.com/24773833/34104011-6efa95fa-e3f7-11e7-9dae-dfc0b04a30cb.png)

**Comment by SoftserveQC1** [comment]
Пофікшено
