### ISSUE TITLE
Utsb: при реєстрації замовника не приходить повідомлення про стадію перевірки, не має валідації зі сторони майданчика

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1613]
https://tb.kiev.ua/test

На пошту приходить лише лист такого змісту:
![c20e2ae82a](https://user-images.githubusercontent.com/13050207/34001264-3bf50700-e0f8-11e7-92f4-a5b5804649af.png)
Можливо спрощена процедура лише на тестовому майданчику.

**Comment by v-lego** [comment]
Так на тестовому майданчику для спрощення реєстрація проходить автоматично.
І навіть на тестовому майданчику лист про підтвердження реєстрації приходить.
Але можемо продемонструвати і відмову у реєстрації за вказаним Учасником.

**Comment by v-lego** [comment]
Для зручності тестування функціонал реєстрації та відхилення надано самому користувачу.
Для чого після підтвердження даних картки учасника користувачу необхідно скористатися кнопками "Зареєструвати" та "Відкинути". На продуктиві це функціонал адміністратора майданчика
![default](https://user-images.githubusercontent.com/24773833/34162050-1d1069ec-e4db-11e7-9b59-94f38ff4ca65.png)

**Comment by SoftserveQC1** [comment]
Пофікшено
