### ISSUE TITLE
Utsb: при реєстрації підвал сайту статичний, тому кнопка та чек-бокси можуть накладатися або розміщуватися під підвалом

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1614]
При реєстрації можна також додати пусту категорію, та одну і ту ж область декілька раз.
![a41a3c7a5d](https://user-images.githubusercontent.com/13050207/34001913-f25a18cc-e0f9-11e7-9818-5838117c2f58.png)

**Comment by v-lego** [comment]
Внесено зміни:
- неможливо додати пусту категорію
- неможливо додати повторно елемент
- змінено параметри розташування елементів

**Comment by SoftserveQC1** [comment]
Пофикшено
