### ISSUE TITLE
Utsb: при виборі сьогоднішньої дати підписання договору висвічується помилка "договір не може буди підписаний у майбутньому"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1615]
https://tb.kiev.ua/test

**Передумови:**
Увійти як Замовник.
Створити аукціон.
Увійти як Учасник1, подати пропозицію.
Увійти як Учасник2, подати пропозицію.
Дочекатися початку періоду "кваліфікація".
Замовником додати протокол та підписаний договір з Учасником1.
Дискваліфікувати Учасника1.
Додати протокол та договір Учаснику2 (дата є заповненою з попереднього кроку).

**Очікуваний результат:**
З'явилася кнопка для завершення продажу.

**Фактичний результат:**
Висвічується помилка, що дата у майбутньому. Для вирішення проблеми необхідно вибрати сьогоднішню дату ще раз.
![c20e2ae82a](https://user-images.githubusercontent.com/13050207/34035210-fefe66ce-e189-11e7-8c65-5fc4dcc77f1d.png)

**Comment by v-lego** [comment]
Потрібно було б зачекати хвилину. 
При співпадінні дати оновленя контракту і дати підписання. остання виставляється як "Дата зміни контракту" + 1 хвилина.
так для Аукціону UA-PS-2017-12-14-000094-1, "Дата зміни контракту" була 2017-12-14T14:37:07.337546+02:00.
О 14:37:23.749 Вами було надіслано час підписання 2017-12-14T14:38:00.000000+02:00
(38 хвилина)
от воно і було в майбутньому. 
Зараз встановили додавання 5 секунд до "Дата зміни контракту"

**Comment by SoftserveQC1** [comment]
Пофікшено
