### ISSUE TITLE
biddingtime: Користувач НЕ отримує повідомлення про успішну/неуспішну активацію профіля

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1616]
https://etm.biddingtime.com.ua

**Передумови**
Пройти реєстрацію як учасник/замовник.
Отримати листа на пошту про успішну подачу заявки та розгляд адміністратором.
![big](https://user-images.githubusercontent.com/13050207/34045323-1dba7e14-e1b1-11e7-8f11-25f722ace73d.png)

**Фактичний результат**
Користувач НЕ отримує повідомлення про те, що обліковий запис було перевірено та активовано/відмовлено у активації.

**Очікуваний результат** 
Після перевірки користувач на пошті ТА в особистому кабінеті отримує повідомлення з результатами.

**Comment by neros3** [comment]
пофиксили, это из-за очереди писем было

**Comment by SoftserveQC1** [comment]
Пофікшено і перевірено
