### ISSUE TITLE
NewTend: НЕмає типу документа "Кваліфікаційні вимоги до Учасника" для завантаження 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1617]
NewTend
https://cdb2-dev.newtend.com

**Передумови:**
1. Зареєструватись як Замовник
2. Створити аукцioн
3. Перейти в розділ документи
4. Завантажити документ
5. Тип документа

**Очікуваний результат:**
В випадаючoму списоку є тип документа "Кваліфікаційні вимоги до Учасника"

**Фактичний результат:**
НЕмає типу документа "Кваліфікаційні вимоги до Учасника" для завантаження

**Comment by SlaOne** [comment]
http://dgf.api-docs.ea2.openprocurement.io/uk/latest/standard/document.html
Список названий документов берем из единого источника. возможно разбежность в переводах. уточните к какому типу должны принадлежать.

**Comment by SoftserveQC1** [comment]
https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#
Стр. 7, Тест 1
На основе этого документа:
Завантаження документації
Кваліфікаційні вимоги замовника

**Comment by SlaOne** [comment]
взяли в работу, добавляем тип документа - 
согласно тех документации - 
evaluationCriteria - Критерії оцінки

Інформація про те, як будуть оцінюватись пропозиції.
http://dgf.api-docs.ea2.openprocurement.io/uk/latest/standard/document.html

**Comment by SlaOne** [comment]
переименовали название документа

**Comment by SoftserveQC1** [comment]
1617 - Pass - Fixed - типу документа "Кваліфікаційні вимоги до Учасника"
