### ISSUE TITLE
NewTend: Замовник НЕ може видалити завантажений документ

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1618]
NewTend
https://cdb2-dev.newtend.com

**Передумови:**
1. Зареєструватись як Замовник
2. Створити аукцioн
3. Перейти в розділ документи
4. Завантажити документ

**Очікуваний результат:**
Замовник може видалити завантажений документ

**Фактичний результат:**
Замовник НЕ може видалити завантажений документ

**Comment by SlaOne** [comment]
у нас документы грузятся сразу в ЦБД и на площадке не хранятся, а из ЦБД пути обратно - нет.

**Comment by SoftserveQC1** [comment]
1618 - Non Issue - загрузка документа в ЦДБ
