### ISSUE TITLE
NewTend: Замовник НЕ може змінити опис лоту та опис конкретного предмету лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1619]
NewTend
https://cdb2-dev.newtend.com

**Передумови:**
1. Зареєструватись як Замовник
2. Створити аукцioн
3. Редагувати аукцiон
4.1. Зміна опису лоту
4.2. Зміна опису конкретного предмету лоту

**Очікуваний результат:**
Замовник може:
1. Змінити опис лоту
2. Змінити опис конкретного предмету лоту

**Фактичний результат:**
Замовник НЕ може:
1. Змінити опис лоту
2. Змінити опис конкретного предмету лоту

**Comment by SlaOne** [comment]
согласно сценариям - ```https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.o4o76qftsq60```
```Внести зміни до Лоту, опублікувати в ЦБД - дії користувача
				
Внести наступні зміни:
Додавання документу. 
У випадку помилкового завантаженого документу користувач може змінити цей документ (просто видалити документ не можна, лише замінити)
Перевірити, що  інші редагування неможливі для опублікованого аукціону, такі як поля description, items, procuringentity, окрім value.amount, та полів, що з ним пов’язані)```

**Comment by SoftserveQC1** [comment]
1619 - Non Issue - Замовник НЕ може змінити опис лоту та опис конкретного предмету лоту 
Замовник может менять только сумму (в сторону уменьшения) и документы
