### ISSUE TITLE
ЕЛЕГ, кнопка "Анулювати переможця" не працює

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#162]
Після проведення аукціону, та відміненні переможця, при нажиманні кнопки "Анулювати переможця" - жодні зміни не відбуваються

![no_changes_dismissal](https://cloud.githubusercontent.com/assets/11062040/6603903/8e630186-c82d-11e4-88dd-eabc306892db.png)

**Comment by S-Shevchenko** [comment]
не воспроизводится.можно закрывать
