### ISSUE TITLE
Інструкція учасника. Замість інструкції ФДМ розміщена інструкція для ФГВФО.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1620]
http://test.smarttender.biz/WEBPARTS/(S(yeagp1o0q3z20ttbo21vr2xf))/?id=_PERSONALCABINET&itLanguage=uk&cspin=1#
smatest1@yopmail.com

Відтворення:
1. Зайти в аплікацію.
2. Перейти до особистого кабінету.
3. перейти до Інструкції.
4. Скачати та відкрити "Інструкція «Торги з продажу і оренди майна активів державних підприємств (ФДМ)». Учасник.pdf"
5. Перевірити назву та вміст скачаного документу.

Очікувано: а) Назва документу співпадає з підписом на сторінці. б) Вміст описує роботу учасника аукціону майна та оренди державних підприємств.

Фактично: а) Назва не співпадає: "Інструкція_для_подачі_пропозиції_в_торгах_з_продажу_майна.pdf" б) Вміст відноситься до роботи учасника аукціонів ФГВФО.

![image](https://user-images.githubusercontent.com/11888281/34050018-0d0a3da0-e1c2-11e7-9bfc-2c5cedb18c98.png)

**Comment by f3man** [comment]
Ситуацію вирішено
