### ISSUE TITLE
NewTend: Замовник НЕ отримуе нагадування (щодня) про запитання до Лоту електронною поштою та в особистому кабінеті 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1621]
NewTend
https://cdb2-dev.newtend.com

**Передумова:**
1. Залогінитись як Замовник
2. Натиснути кнопку "Створити аукціон"
3. Обрати тип оголошення "Оренда"
4. Заповнити усі поля валідними даними та опублікувати аукціон

**Відтворення:**
1. Залогінитись як Учасник
2. Вибрати створенний аукицон
3. Натиснути кнопку "Запитання-вiдповiдi"
4. Заповнити усі поля та створити запитання
5. Замовник ни вiдповiдае на запитання на протязi доби

**Очікуваний результат:**
Замовник отримуе нагадування (щодня) про запитання до Лоту електронною поштою та в особистому кабінеті 

**Фактичний результат:**
Замовник НЕ отримуе нагадування (щодня) про запитання до Лоту електронною поштою та в особистому кабінеті

**Comment by SlaOne** [comment]
взяли в работу перепроверяем, что к чему.

**Comment by SlaOne** [comment]
исправили выявленный баг на стороне площадки.
для того что бы письмо пришло - нужно создать процедуру без ускорителя, и задать туда вопрос.
напоминание придет утром на следующий день!
