### ISSUE TITLE
biddingtime: не можливо подати питання на окрему позицію, лише на лот в цілому 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1622]
https://etm.biddingtime.com.ua

**Передумови:**
Увійти як Замовник
Створити аукціон
Увійти як Учасник
Подати запитання

**Очікуваний результат:**
Є можливість подати запитання на окрему позицію та на лот в цілому

**Фактичний результат:**
Є можливість подати запитання лише на лот в цілому
![803e27898d](https://user-images.githubusercontent.com/13050207/34110072-38cfec3e-e40e-11e7-9587-b73f3093b898.png)

**Comment by neros3** [comment]
![default](https://user-images.githubusercontent.com/13747286/34148411-cd9e7a74-e4a9-11e7-970a-119032f1719c.png)

синяя кнопка - на лот
зеленые - на каждый актив

**Comment by SoftserveQC1** [comment]
Не очевидне місце розташування кнопки для запитання про лот в цілому, але можливість реалізовано.
