### ISSUE TITLE
biddingtime: Замовник НЕ може опублікувати договір без перевірки оплати

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1623]
https://etm.biddingtime.com.ua

**Передумови:**
Увійти як Замовник
Створити аукціон
Увійти як Учасник
Подати пропозицію
Дочекатися періоду "кваліфікація переможця"
Замовником завантажити протокол торгів

**Очікуваний результат:**
Є можливість опублікувати договір без перевірки оплати

**Фактичний результат:**
Є можливість лише підтвердити оплату, або дискваліфікувати учасника
![bidd](https://user-images.githubusercontent.com/13050207/34110254-beee21c8-e40e-11e7-9af2-08d2ccbd1200.jpg)

**Comment by neros3** [comment]
пофиксили

**Comment by SoftserveQC1** [comment]
пофикшено
