### ISSUE TITLE
biddingtime: В кабінеті користувача немає жодних повідомлень

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1624]
https://etm.biddingtime.com.ua

В багатьох кейсах користувач має отримувати повідомлення в особистому кабінеті. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не прочитає повідомлення/перейде до аукціону і так далі.

**Comment by neros3** [comment]
![2017-12-19 11-06-18](https://user-images.githubusercontent.com/13747286/34149129-c3873c9e-e4ac-11e7-9a40-09c274b38238.png)

сверху красным выделено сколько новых сообщений

**Comment by SoftserveQC1** [comment]
Пофікшено
