### ISSUE TITLE
biddingtime:  в листах немає сроків 6 та 20 днів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1626]
https://etm.biddingtime.com.ua

У випадку перемоги у аукціоні користувачу має приходити лист з інформацією, що у нього 6 діб на підписання протоколу та 20 днів на підписання договору.
Другий кандидат за переможцем має отримувати листа з текстом що є 20 днів, коли переможець може бути дискваліфікований і є можливість не забирати гарантійний внесок у цей час.

**Comment by neros3** [comment]
пофиксили

**Comment by SoftserveQC1** [comment]
Пофікшено, перевірено
