### ISSUE TITLE
Замовнику та Учасникам надходять повідомлення про "Відбулися зміни" але змін до аукціону не вносилось

### ISSUE THREAD

**Issue by olyamalysh** [openprocurement/frontend#1627]
https://sale.uub.com.ua/test/

Передумови:
Увійти як Замовник
Створити аукціон

Відтворення:
Подати пропозицію до аукціону 
Увійти як Учасник 1 і подати пропозицію до аукціону 
Увійти як Учасник 2 і подати пропозицію до аукціону 

Фактичний результат 
Надходять повідомлення Учаснику та Замовнику в з текстом "Відбулися зміни" (зміни в аукціон внесені не були).

**Comment by v-lego** [comment]
Внесено зміни: формування повідомлень при зміні полів аукціону
![default](https://user-images.githubusercontent.com/24773833/34117292-ef1721f0-e423-11e7-9d9d-1a1a937d71d7.png)

**Comment by olyamalysh** [comment]
Виправлено
