### ISSUE TITLE
NewTend: Учасник НЕ отримауе повідомлення про неуспішну валідацію до Лоту електронною поштою та в особистому кабінеті

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1628]
NewTend
https://cdb2-dev.newtend.com

**Передумова:**
1. Залогінитись як Замовник
2. Заповнити усі поля валідними даними та опублікувати аукціон

**Відтворення:**
1. Залогінитись як Учасник
2. Вибрати створенний аукицон
3. Подати пропозицію
4. Зробити неуспішну валідацію

**Очікуваний результат:**
Учасник отримауе повідомлення про неуспішну валідацію до Лоту електронною поштою та в особистому кабінеті

**Фактичний результат:**
Учасник НЕ отримауе повідомлення про неуспішну валідацію до Лоту електронною поштою та в особистому кабінеті

**Comment by SlaOne** [comment]
уведомления приходят с задержкой. задержки связанные с синхронизацией.

**Comment by SoftserveQC1** [comment]
1628 - Pass - Fixed - Учасник НЕ отримауе повідомлення про неуспішну валідацію до Лоту електронною поштою та в особистому кабінеті
