### ISSUE TITLE
NewTend: Невiрний текст в повiдомленнi "Необхiдно пiдписати Протокол торгiв протягом шести дiб"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1629]
NewTend
https://cdb2-dev.newtend.com

**Передумова:**
1. Залогінитись як Замовник
2. Заповнити усі поля валідними даними та опублікувати аукціон

**Відтворення:**
1. Залогінитись як Учасник
2. Вибрати створенний аукицон
3. Подати пропозицію
4. Після завершення періоду прийому пропозицій отримати повідомлення про перемогу: електронною поштою та в кабінеті Учасника.
![1](https://user-images.githubusercontent.com/13050207/34151892-7747a856-e4b5-11e7-9cb7-2f2b15b2322a.png)

**Очікуваний результат:**
Учасник отримауе повідомлення про електронною поштою та в особистому кабінеті 
"Необхiдно пiдписати Протокол торгiв протягом  шести дiб"

**Фактичний результат:**
Учасник отримауе повідомлення про електронною поштою та в особистому кабінеті 
"Необхiдно пiдписати Протокол торгiв протягом трьох дiб"

**Comment by SlaOne** [comment]
исправили " три дня" на "шесть дней в уведомлениях

**Comment by SoftserveQC1** [comment]
1629 - Pass - Fixed - тест сообщения "Необхiдно пiдписати Протокол торгiв протягом шести дiб"
