### ISSUE TITLE
ЕЛЕГ, "Адреса доставки" не зберігається при редагуванні тендера, в періоді уточнень

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#163]
![adress_notsave](https://cloud.githubusercontent.com/assets/11062040/6620028/f1e538d8-c8d6-11e4-9620-d87cf66a03b3.png)

**Comment by S-Shevchenko** [comment]
Дякую, завдання в роботі.
@lerich

**Comment by S-Shevchenko** [comment]
Функционал поменялся.  Можно закрывать.
![image](https://cloud.githubusercontent.com/assets/10655287/7631352/9f42aca6-fa49-11e4-98f8-9f723a500561.png)
