### ISSUE TITLE
ubiz: на головній сторінці в Edge в текста зник фон

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1630]
http://test.ubiz.com.ua/

![ubiz2](https://user-images.githubusercontent.com/13050207/34154000-ad2d77d2-e4bc-11e7-8ed5-0f1dc95f219d.jpg)

**Comment by SergeAntonets** [comment]
Поправлено!

**Comment by SergeAntonets** [comment]
Очистить кэш нужно будет

**Comment by SoftserveQC1** [comment]
Пофикшено, проверила
