### ISSUE TITLE
NewTend: Учасник НЕ отримауе повідомлення про скасування Організатором Аукціону електронною поштою та в особистому кабінеті 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1631]
NewTend
https://cdb2-dev.newtend.com

**Передумова:**
1. Залогінитись як Замовник
2. Заповнити усі поля валідними даними та опублікувати аукціон

**Відтворення:**
1. Залогінитись як Учасник
2. Вибрати створенний аукицон
3. Подати запитання
4. Замовник скасовує аукціон

**Очікуваний результат:**
NewTend: Учасник отримауе повідомлення про скасування Організатором Аукціону електронною поштою та в особистому кабінеті 

**Фактичний результат:**
NewTend: Учасник НЕ отримауе повідомлення про скасування Організатором Аукціону електронною поштою та в особистому кабінеті

**Comment by SlaOne** [comment]
проверено/исправлено
1 создать аукцион (создатель)
2 задать вопрос (участником)
3 отменить Аукцион (создатель)
4 Зайти в "колокольчик" (участником, который задал вопрос [может занять некоторое время, до 10 минут - синхронизация])
![question_cancel](https://user-images.githubusercontent.com/15046328/34265334-376ceef6-e67e-11e7-8acd-c70cd90539b3.jpg)

**Comment by SoftserveQC1** [comment]
1631 - Pass - Fixed - поведомлення про скасування аукциону, на который был задан вопрос
