### ISSUE TITLE
NewTend: Замовник НЕ може створити аукціон на основі раніше створеного из чернетки

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1632]
NewTend
https://cdb2-dev.newtend.com

**Відтворення:**
1. Зареєструватись як Замовник
2. Створити аукцioн
3. Створити чернетку
4. Редагувати чернетку
5. Збільшити очікувану ціну

![-](https://user-images.githubusercontent.com/13050207/34161211-91baeba8-e4d8-11e7-86c5-31d9e063bc1a.png)

**Очікуваний результат:**
Замовник може створити аукціон на основі раніше створеного из чернетки

**Фактичний результат:**
Замовник НЕ може створити аукціон на основі раніше створеного из чернетки

**Comment by SlaOne** [comment]
исправили возможность изменять "ожидаемую цену" в большую сторону

**Comment by SoftserveQC1** [comment]
Fail
Не получилось создать аукцион из Черновика с увеличением цены

**Comment by SoftserveQC1** [comment]
1632 - Pass - Fixed - Замовник может редактировать аукцион из черновика / копии с увеличением цены лота
Особенности NewTend - здесь создаётся копия помимо черновика.
