### ISSUE TITLE
NewTend: Замовник НЕ може завершити продаж без підтвердження оплати

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1633]
NewTend
https://cdb2-dev.newtend.com

**Відтворення:**
1. Зареєструватись як Замовник
2. Створити аукцioн
3. Увійти як Учасник
4. Подати пропозицію
5. Дочекатися періоду "кваліфікація переможця"
6. Замовником завантажити протокол торгів
7. Замовником завантажити підписаний договір

![default](https://user-images.githubusercontent.com/13050207/34201968-f876c14a-e57e-11e7-9daa-c08ae87bc5c5.png)

**Очікуваний результат:**
1. Замовник може завершити продаж без підтвердження оплати 
2. є кнопка "Закiнчити торги"

**Фактичний результат:**
1. Замовник НЕ може завершити продаж без підтвердження оплати 
2. Немає кнопки "Закiнчити торги"

**Comment by SlaOne** [comment]
разбираемся

**Comment by SlaOne** [comment]
1. аукцион в статусе квалификация
2. выбрать победителя (статус участника - "ожидает оплаты")
3. зайти в победителя
4. есть кнопка "Принять без подтверждения"
4.1. По нажатию на эту кнопку аукцион переходит в статус - "рассмотрен" и можно загружать договор, после чего можно завершать процесс!
![no_payment_1](https://user-images.githubusercontent.com/15046328/34270029-6cd140cc-e68f-11e7-9c38-67d2a9a08b90.jpg)
![no_payment_2](https://user-images.githubusercontent.com/15046328/34270030-6ced6dd8-e68f-11e7-9ead-dbf4b317317e.jpg)

**Comment by SoftserveQC1** [comment]
1633 - Pass - NewTend: Замовник НЕ може завершити продаж без підтвердження оплати
