### ISSUE TITLE
Запитання. На електронній пошті відсутьнє нагадування про запитання без відповіді.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1634]
http://test.smarttender.biz/webclient/(S(gb2dkjmo5eni1gftchbllxz2))/?testmode=1&proj=it_uk&tz=2
UA-PS-2017-12-15-00019
osmatest@yopmail.com
smatest1@yopmail.com

Відтворення:

1. Створити торги.
2. Залогінитись Учасником.
3. Задати запитання.
4. Почекати 24 години
5. Перевірити пошту організатора.

Очікувано: Організатор отримує нагадування про питання без відповіді в аплікації та на електроннну пошту.

Фактично: Організатор не отримує нагадування на електронну пошту про питання без відповіді через 24 години.

**Comment by f3man** [comment]
поправив, та запустив щоб надіслало листа, тобто вже можна перевірити наявність листа
![image](https://user-images.githubusercontent.com/16836558/34416914-78aa44f6-ebfe-11e7-8087-76bc2aeaf584.png)
