### ISSUE TITLE
NewTend: Учасник 2 НЕ може завантажити протокол після дискваліфікації Учасника 1

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1635]
NewTend
https://cdb2-dev.newtend.com

**Відтворення:**
1. Зареєструватись як Замовник
2. Створити аукцioн
3. Провести аукціон з двома учасниками
4. Дочекатися періоду "кваліфікація переможця"
5. Замовник дискваліфікує Учасника 1

**Очікуваний результат:**
Учасник 2 може завантажити протокол

**Фактичний результат:**
Учасник 2 НЕ може завантажити протокол

**Comment by SlaOne** [comment]
![2-nd_place_protocol](https://user-images.githubusercontent.com/15046328/34214182-6b67618e-e5aa-11e7-8eb4-5bd7e9eb72c0.jpg)
(особенности реализации на площадке)
1. Участник номер-2 должен зайти в раздел "документы"
2. Кнопка "загрузить документы"
3. загрузить протокол

**Comment by SoftserveQC1** [comment]
1635 - Pass - Non-issue - Учасник 2 НЕ може завантажити протокол після дискваліфікації Учасника 1 - Особенности реализации
