### ISSUE TITLE
NewTend: Учасник 2 НЕ отримує повідомлення про те, що він стає переможцем після дискваліфікації Учасника 1

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1636]
NewTend
https://cdb2-dev.newtend.com

**Відтворення:**
1. Зареєструватись як Замовник
2. Створити аукцioн
3. Провести аукціон з двома учасниками
4. Дочекатися періоду "кваліфікація переможця"
5. Замовник дискваліфікує Учасника 1

**Очікуваний результат:**
Учасник 2 отримує повідомлення про те, що він стає переможцем

**Фактичний результат:**
Учасник 2 НЕ отримує повідомлення про те, що він стає переможцем

**Comment by SlaOne** [comment]
перепроверяем, исследуем.

**Comment by SlaOne** [comment]
исправлено, уведомления приходят

**Comment by SoftserveQC1** [comment]
1636 - Pass - Учасник 2 НЕ отримує повідомлення про те, що він стає переможцем після дискваліфікації Учасника 1
Приходит сообщение, что:
"Ваша пропозиція чекає рішення в аукціоні" - это решение NewTend о таком сообщении
