### ISSUE TITLE
ubiz: користувач НЕ отримує щодня нагадування про запитання без відповіді

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1637]
http://test.ubiz.com.ua

**Передумова:**
Залогінитись як Замовник
Натиснути кнопку "Створити аукціон"
Обрати тип оголошення "Оренда"
Заповнити усі поля валідними даними та опублікувати аукціон

**Відтворення:**
Залогінитись як Учасник
Вибрати створений аукіцон
Натиснути кнопку "Запитання-вiдповiдi"
Заповнити усі поля та створити запитання
Замовник не вiдповiдає на запитання на протязi доби

**Очікуваний результат:**
Замовник отримує нагадування (щодня) про запитання до Лоту електронною поштою та в особистому кабінеті

**Фактичний результат:**
Замовник НЕ отримує нагадування (щодня) про запитання до Лоту електронною поштою та в особистому кабінеті

**Comment by SergeAntonets** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
Есть!
