### ISSUE TITLE
ubiz: користувач НЕ отримує повідомлення про скасування аукціону, на який подавав пропозицію чи питання

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1638]
http://test.ubiz.com.ua

**Передумова:**
Залогінитись як Замовник
Натиснути кнопку "Створити аукціон"
Обрати тип оголошення "Оренда"
Заповнити усі поля валідними даними та опублікувати аукціон

**Відтворення:**
Залогінитись як Учасник
Вибрати створений аукіцон
1) Натиснути кнопку "Запитання-вiдповiдi"
Заповнити усі поля та створити запитання
2) Подати пропозицію
Під Замовником скасувати аукціон

**Очікуваний результат:**
Користувач отримує повідомлення про скасування аукціону в особистому кабінеті та електронною поштою
**Фактичний результат:**
Користувач не отримує жодних повідомлень

**Comment by SergeAntonets** [comment]
![image](https://user-images.githubusercontent.com/7313452/34218879-24066188-e5b8-11e7-9d30-1767d911c14e.png)
![image](https://user-images.githubusercontent.com/7313452/34218893-2d26834c-e5b8-11e7-9fef-9e47f07b4e8a.png)

Уведомления участнику в кабинет приходило. Почту поправил!

**Comment by SoftserveQC1** [comment]
Пофикшено
