### ISSUE TITLE
ubiz: користувач НЕ отримує повідомлення про неуспішну активацію Замовника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1639]
http://test.ubiz.com.ua

**Відтворення:**
Зареєструватися як замовник
Дочекатися відмови від майданчика

**Очікуваний результат:**
Користувач отримує повідомлення електронною поштою та в особистому кабінеті про те, що його запис не активований і треба виправити помилки.

**Фактичний результат:**
Користувач бачить статус в особистому кабінеті про те, що його профіль ще не активований (у стані перевірки)

**Comment by SergeAntonets** [comment]
Поправлено

**Comment by SoftserveQC1** [comment]
Уведомление сделали
