### ISSUE TITLE
ubiz: Замовник може дискваліфікувати учасника без прикріплення документів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1640]
http://test.ubiz.com.ua

**Відтворення:**
Створити аукціон
Дочекатися завершення торгів
Замовником дискваліфікувати учасника

**Очікуваний результат:**
Потрібно вказати причину та додати документ

**Фактичний результат:**
Можна дискваліфікувати учасника без додавання документу

**Comment by SergAntonec** [comment]
![image](https://user-images.githubusercontent.com/7313452/34213878-42c70e88-e5a9-11e7-9bfd-70e86e8fa179.png)

**Comment by SergeAntonets** [comment]
Fixed

**Comment by SoftserveQC1** [comment]
Поправили
