### ISSUE TITLE
Створення торгів. В поле "лот виставляється" не можливо внести значення "невідомо".

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1641]
http://test.smarttender.biz/webclient/(S(gb2dkjmo5eni1gftchbllxz2))/?testmode=1&proj=it_uk&tz=2
osmatest@yopmail.com

Відтворення:

1. Зайти на сторінку створення торгів
2. Спробувати вибрати в полі Лот Виставляється "невідомо"

Очікувано: Можна вказати що лот виставляється невідому кількість раз.

Фактично: Випадайка Лот Виставляється не містить Невідомо.

![image](https://user-images.githubusercontent.com/11888281/34214114-2b67ee6e-e5aa-11e7-9a5e-67ed69c32b53.png)

**Comment by w-be** [comment]
В створенні тепер є, додайте, будь-ласка, до редагування чернетки: ![image](https://user-images.githubusercontent.com/11888281/34252576-edd8d812-e64c-11e7-8748-24a8e7b9f737.png)

**Comment by f3man** [comment]
Ситуацію вирішено
