### ISSUE TITLE
tsbgalcontract: Користувач не може створити копію аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1642]
https://sales.tsbgalcontract.org.ua/test/

Передумови:
Поле "Контактна особа"  заповнене.

Кроки для відтворення:
1. Зареєструватися як замовник.
2. Створити аукціон1.
3. Натиснути на кнопку "Створити копію"

Очікуваний результат:
3. Успішно створена копія аукціона1.

Фактичний результат:
3. Повідомлення про помилку "Довжина значення поля повинна бути між 1 та 200." відображається на сторінці.
Поле "Контактна особа"  пусте та виділене червонном кольором.
![auction_copy1](https://user-images.githubusercontent.com/13050207/34216718-d3143e36-e5b1-11e7-8d4f-73538b77558e.png)
![auction_copy2](https://user-images.githubusercontent.com/13050207/34216721-d90d44d6-e5b1-11e7-9ad8-0a6c981830db.png)

**Comment by v-lego** [comment]
Необхідно повністю заповнити картку користувача у кабінеті.
Контактна особа заповнюється з даних картки користувача.
