### ISSUE TITLE
NewTend: Замовник НЕ може підтвердити оплату без завантаження договору 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1643]
NewTend
https://cdb2-dev.newtend.com

*Відтворення:*
1. Зареєструватись як Замовник
2. Створити аукцioн 
3. Увійти як Учасник 1,2
4. Подати пропозицію
5. Дочекатися періоду "кваліфікація переможця"
6. Уч1. завантажує протокол протягом до 6 діб 

**Очікуваний результат:**
Замовник може підтвердити оплату без завантаження договору 

**Фактичний результат:**
Замовник НЕ може підтвердити оплату без завантаження договору

**Comment by SlaOne** [comment]
1. дождаться квалификации (создатель аукциона)
2. перейти во вкладку торги (создатель аукциона)
3. выбрать победителя (статус - "ожидает оплаты")
4. зайти в "победителя"
4.1. нажать на кнопку - "Подтвердить получение оплаты"
4.2. появится модальное окно "Подтверждение оплаты"
4.3. кнопка "подтвердить" - активна, можно нажать на нее без добавления документов в этом модальном окне.
4.4. Получение оплата будет подтверждена.
![payment_1](https://user-images.githubusercontent.com/15046328/34269727-206f4964-e68e-11e7-88eb-b0de1ae30157.jpg)
![payment_2](https://user-images.githubusercontent.com/15046328/34269729-208d1c0a-e68e-11e7-8235-548928e3b9bc.jpg)

**Comment by SoftserveQC1** [comment]
1643 - Pass - Замовник НЕ може підтвердити оплату без завантаження договору 
Осуществить можно после Refresh Page !
Что не удобно пользователям.
