### ISSUE TITLE
Кваліфікація. Учасник не може вказати Тип Документів що додає.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1644]
http://test.smarttender.biz/bid/upload/docs/3108298/
smatest2@yopmail.com
UA-PS-2017-12-20-000029-3

Відтворення:
1. Знайти аукціон де учасник є переможцем.
2. Відкрити аукціон, перейти своєї ставки.
3. Спробувати додати документи вказавши тип документів.

Очікувано:
На етапі кваліфікації можна додати/замінити такі типи документів:
commercialProposal - Цінова пропозиція
qualificationDocuments - Документи, що підтверджують кваліфікацію
eligibilityDocuments - Документи, що підтверджують відповідність (в тому числі, відповідність вимогам ст. 17)
auctionProtocol - Протокол торгів

Фактично: Тип документів не можливо задати.
![image](https://user-images.githubusercontent.com/11888281/34220133-2a68747c-e5bc-11e7-9cb5-ed96e075769f.png)

**Comment by f3man** [comment]
Можна посилання на документ, де цей процес описано? Я шукав тут [https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#heading=h.gcy7t13y7obd](url) та не знайшов

**Comment by w-be** [comment]
Там тільки протокол, тип протокол торгів. Документи брав тут: http://dgf.api-docs.openprocurement.org/uk/latest/standard/document.html, в секції bid. Я так розумію користувач підчас кваліфікації може додати всі ті самі документи, що і підчас ставки + протокол.

**Comment by f3man** [comment]
доробив:
![image](https://user-images.githubusercontent.com/16836558/34437498-7068c746-eca7-11e7-896c-72dd4f1b4060.png)
