### ISSUE TITLE
Забирання гарантійного внеску. Кнопка підтверження не закриває діалогове вікно.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1645]
http://test.smarttender.biz/auktsiony-na-prodazh-aktyviv-derzhpidpryemstv/3108298/
UA-PS-2017-12-20-000029-3
smatest3@yopmail.com

Відтворення:
1. Відрити торги в яких присутьня ставка учасника, і ставка чекає розгляду(не 1-ша в черзі).
2. Натиснути кнопку Відмовляюсь від участі.
3. Натиснути в вікні-підтверженні Так
4. Натиснути в додатковому вікні-підтверженні Так

Очікувано: Ставка відмінена. Діалогове вікно закрите.

Фактично: Ставка відмінена. Діалогове вікно залишається відкрите. Діалог закривається при натисканні на кнопку "Ні", або на клавіші Alt+PrntScr.

![image](https://user-images.githubusercontent.com/11888281/34220655-0c2246f8-e5be-11e7-84a7-bf7cbf69ea2b.png)

**Comment by f3man** [comment]
Ситуацію вирішено
