### ISSUE TITLE
Пошук аукціонів повертає не працюючі посилання в MS Edge

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1646]
Не відтворюється в FF, GC.
http://test.smarttender.biz/test-tenders/?mode=prop&f=%D0%B1%D0%B2%D0%B2%20-%20%D1%81%D0%BC%D0%B0%D1%80%D1%82&nh=1
smatest2@yopmail.com

Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

Відтворення:
Залогуватись в MS E як учасник.
Перейти до тестових аукціонів і оренди.
Пошукати створені аукціони по назві (бвв - смарт)
Перейти за 1 з знайдених посиланнь

Очікувано: а) В списку знайдених торгів лінк замаскований назвою посилання. б) Лінк робочий - відкриває сторінку торгів.

Фактично: а) В списку знайдених торгів відображається частина адреси сторінки торгів. б)Лінк не робочий - відкривівається заглушка Bad Request.

![image](https://user-images.githubusercontent.com/11888281/34253002-79e71cbe-e64e-11e7-87d2-bc72d1260fb8.png)

**Comment by w-be** [comment]
Зараз нічого не шукає. Тільки в Edge
![image](https://user-images.githubusercontent.com/11888281/34411353-ca09e8d0-ebde-11e7-9da8-6b980e6cce66.png)

**Comment by f3man** [comment]
Шукає, ви просто не у тестових шукаєте

**Comment by f3man** [comment]
ситуацію з некоректним відображенням вирішено, наразі працює очікувано
