### ISSUE TITLE
KME: Неможливо створити аукцiон окремо по Продажу або Оренди майна

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1647]
KME
statesale.kme.net.ua 

**Відтворення:**
1. Зареєструватись як Замовник
2. Додати аукціон
3. Перейти до випадаючого списку "Тип аукціону"

![kme](https://user-images.githubusercontent.com/13050207/34257777-f3ab8020-e663-11e7-9e0a-e26d2c4924c2.png)

**Очікуваний результат:**
Замовник може вибрати "Продаж майна" або "Оренда майна"

**Фактичний результат:**
Замовник НЕ може вибрати "Продаж майна" або "Оренда майна"

**Comment by slavavitrenko** [comment]
Исправлено
