### ISSUE TITLE
KME: При создании аукциона есть лишние обязательные поля

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1648]
KME
statesale.kme.net.ua 

**Відтворення:**
1. Зареєструватись як Замовник
2. Додати аукціон

![kme](https://user-images.githubusercontent.com/13050207/34257777-f3ab8020-e663-11e7-9e0a-e26d2c4924c2.png)

**Очікуваний результат:**
Наступні поля необов'язкові:
- Публічний паспорт активу 
- Терміни поставки товарів 
- Умови поставки товарів

**Фактичний результат:**
Наступні поля обов'язкові:
- Публічний паспорт активу 
- Терміни поставки товарів 
- Умови поставки товарів

**Comment by slavavitrenko** [comment]
Исправлено
