### ISSUE TITLE
KME: Код відповідного класифікатору лоту: CAV або CPV відсутній

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1649]
KME
statesale.kme.net.ua 

**Відтворення:**
1. Зареєструватись як Замовник
2. Додати аукціон

**Очікуваний результат:**
Код відповідного класифікатору лоту: CAV або CPV присутній

**Фактичний результат:**
Код відповідного класифікатору лоту: CAV або CPV відсутній

**Comment by slavavitrenko** [comment]
Исправлено
