### ISSUE TITLE
ЕЛЕГ, "Internal Server Error" при додаванні файлів великого об'єму

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#165]
При завантаженні файлу 87MB.pdf - аплікація видає помилку.

![error_big_file](https://cloud.githubusercontent.com/assets/11062040/6624302/1b6628d8-c8f1-11e4-975a-b300396e7fb7.png)

Згідно зазначеного у https://github.com/openprocurement/frontend/issues/44, аплікація поводить себе коректно, але при завантаженні файлів великих розмірів - аплікація поводить себе не зовсім коректно, а саме -  видає помилку.

Очікуваний результат:
видати користувачу повідомлення, що максимальний розмір не повинен перевищувати певного розміру, або зазначити під кнопкою "Завантажити", який максимальний розмір файлу можна завантажити у аплікацію.

**Comment by S-Shevchenko** [comment]
Дякую. взяли в работу.

**Comment by S-Shevchenko** [comment]
Бага воспроизводится.
