### ISSUE TITLE
ALL (KME): Аукціон не стартує

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1653]
KME
statesale.kme.net.ua 

**Відтворення:**
1. Зареєструватись як Замовник
2. Додати аукціон
3. Увійти як Учасник 1,2
4. Подати пропозицію
5. Дочекатися періоду "Cтарт аукцiону"

![-](https://user-images.githubusercontent.com/13050207/34359296-6a6e798e-ea5f-11e7-8da0-df0ced535332.png)

**Очікуваний результат:**
Аукціон стартує

**Фактичний результат:**
Аукціон не стартує

**Comment by neros3** [comment]
касается общего модуля аукционов, на всех площадках эта проблема была.

**Comment by w-be** [comment]
Вже працює.
