### ISSUE TITLE
Створення торгів. При оренді можливо встановити ті ж одиниці виміру що і в продажі.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1654]
http://uatasset.e-auction.ua/#/tenderDetailes/e5f237d8f7654806b9a1da15e5dbf831
eauco@yopmail.com
UA-PS-2017-12-26-000072-2

Відтворення:
1. Перейти на сторінку створення торгів державного майна.
2. Перецти до створення Оренди.
3. Спробувати обрати будьяку одиниці виміру крім М кв.

Очікувано: неможливо обрати одиниці виміру. Тільки М кв.

Фактично: можливо обрати будьякі одиниці виміру прийняті для майна.
![image](https://user-images.githubusercontent.com/11888281/34361686-1b1cf6e2-ea75-11e7-9b54-4912cf8b0e29.png)

**Comment by OlegNekovalev** [comment]
Виправили не можливість обрати іншу одиницю виміру крім м.кв. для класифікаторів 04…\70…

**Comment by w-be** [comment]
Відтворюється:
![image](https://user-images.githubusercontent.com/11888281/34437483-555276be-eca7-11e7-886d-84ad7c03640f.png)
http://uatasset.e-auction.ua/#/tenderDetailes/cf7b053fea3d42409ae842fbcd10e5da

**Comment by OlegNekovalev** [comment]
м.кв виключно для класифікаторів 04…\70…
