### ISSUE TITLE
Редагування торгів. Учасник що задав питання не повідомляється про зміни в торгах.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1656]
http://uatasset.e-auction.ua/#/tenderDetailes/de122ee32fb04a0abeabc109907d583c
eauco@yopmail.com
eauc2@yopmail.com
UA-PS-2017-12-27-000023-2

Відтворення:
Знайти учасником створенний аукціон
Задати учасником запитання
Залогінитись Замовником, який створював аукцін
Відредагувати аукціон: зменшити вартість, крок, внесок.
Залогуватись учасником
Перевірити особисті повідомлення та пошту учасника.

Очікувано: Учасник повідомлений про зміни в аукціоні на який він задав питання, в особистий кабінет та на пошту.

Фактично: Учасник не повідомляється про зміни в аукціоні на який він задав запитання

**Comment by OlegNekovalev** [comment]
Виправили, перевірте будь ласка
