### ISSUE TITLE
Пошук по М кв не реалізований.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1657]
http://uatasset.e-auction.ua/#/
eauc1@yopmail.com

Відворення:
1. Залогуватись учасником
2. Перейти до торгів - майно/оренда держ організацій
3. Натиснути на Параметри
4. Вибрати Оренда
5. Спробувати ввести обмеження пошуку по М кв: верхнє, нижнє.

Очікувано:
Є можливість шукати по діапазону М кв.

Фактично:
Не реалізована можливість шукати за діапазоном М кв.

![image](https://user-images.githubusercontent.com/11888281/34382766-e384ddb2-eb19-11e7-9453-4d189def3f27.png)

**Comment by OlegNekovalev** [comment]
Виправили, перевірте будь ласка
