### ISSUE TITLE
Створення торгів. Можливо вибрати інші одиниці виміру крім м кв. при оренді майна.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1658]
http://test.smarttender.biz/webclient/(S(nnvy1eyfruoipgubyfqo1xiu))/?proj=it_ru&testmode=1&tz=2
osmatest@yopmail.com

Відтворення:
1. Залогуватись в аплікацію як замовник.
2. Перейти до створення торгів.
3. Встановити тип торгів Оренда
4. Вибрати 1 з класифікаторів нерухомого майна.
5. Спробувати встановити одиниці виміру не м кв

Очікувано: Встановити щось крім м кв не можливо.

Фактично: Можливо встановити інші одиниці виміру, наприклад пачки.

![image](https://user-images.githubusercontent.com/11888281/34405912-a1c2ac38-ebbe-11e7-9594-88564e87d11a.png)

**Comment by f3man** [comment]
![image](https://user-images.githubusercontent.com/16836558/34409562-303b6cac-ebd3-11e7-8c08-ef1ddecb206f.png)
У нас є такі Замовники
https://docs.google.com/document/d/1rlwxiBYcsIkwQL_IsDZh88wpqa14_e5wFpISbA61ZV4/edit#

**Comment by w-be** [comment]
Дерево класифікаторів 04... - це тільки нерухоме майно, Дерево 70... це тільки Послуги у сфері нерухомості. При виборі інших товарів/ послуг м кв. не обов"язкові.

**Comment by f3man** [comment]
реалізовано
для класифікацій:
CPV - 70...
CAV-PS - 04... 
доступна одиниця виміру тільки **м. кв.**
