### ISSUE TITLE
Повідомлення. Редагування аукціону не повідомляється учаснику, що задав питання.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1659]
http://test.smarttender.biz/WEBPARTS/(S(jetq03w1ashs030ztufjd2jz))/?id=_PERSONALCABINET&itLanguage=uk&cspin=1#
UA-PS-2017-12-28-000005-3
osmatest@yopmail.com
smatest2@yopmail.com

Відтворення:
1. Створити замовником торги.
2. Знайти торги учасником
3. Задати запитання учасником.
4. Замовником відредагувати торги, зберегти зміни.
5. Перелогуватись учасником в апплікацію
6. Перейти в особистий кабінет -  повідомлення
7. Перевірити електронну пошту учасника.

Очікувано: Учаснику що задав запитання повідомляється зміна в торгах в особистий кабінет, та на електронну пошту.

Фактично: Учаснику, що задав питання, не приходять повідомлення про редагування торгів.

![image](https://user-images.githubusercontent.com/11888281/34407290-474b712e-ebc6-11e7-8792-588623856fc4.png)

**Comment by f3man** [comment]
Ви подали запитання під одним юзером(smatest1@yopmail.com), а очікуєте повідомлення під іншим(
smatest2@yopmail.com).

якщо подивитись особистий кабінет юзера smatest1@yopmail.com, то можна побачити ці самі повідомлення:
![image](https://user-images.githubusercontent.com/16836558/34415115-8d672f66-ebf5-11e7-8e67-dc0030db4a56.png)
ви їх до речі прочитали
