### ISSUE TITLE
ЕЛЕГ, як саме і де повинно бути зазначено, що пропозиція учасника є дискваліфікована?

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#166]
На даному етапі, після відміни пропозиції, ні в кабінеті замовника, ні в кабінеті учасника (пропозицію, якого відмінили) не зазначено, про відміну його пропозиції.

![disqualified](https://cloud.githubusercontent.com/assets/11062040/6637709/6ef977da-c986-11e4-84b0-eacc883c7cfa.png)

Посилаючись на https://github.com/openprocurement/frontend/issues/98

**Comment by S-Shevchenko** [comment]
Спасибо, знаем.

**Comment by S-Shevchenko** [comment]
Реалізовано:
![screenshot_16](https://cloud.githubusercontent.com/assets/10655287/7609852/14602bf0-f980-11e4-8cdf-c8bcfec5d5f3.jpg)
