### ISSUE TITLE
Повідомлення. Не приходять повідомлення на електронну пошту учасникам, що подали ставку/запитання про редагування торгів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1660]
http://test.smarttender.biz/WEBPARTS/(S(jetq03w1ashs030ztufjd2jz))/?id=_PERSONALCABINET&itLanguage=uk&cspin=1#
UA-PS-2017-12-28-000005-3
osmatest@yopmail.com
smatest1@yopmail.com
smatest2@yopmail.com

Відтворення:
1. Створити замовником торги.
2. Знайти торги учасником 1
3. Подати пропозицію учасником 1
4. Знайти торги учасником 2
5. Задати запитання учасником 2
6. Замовником відредагувати торги, зберегти зміни.
7. Перевірити електронну пошту учасників

Очікувано: Учаснику, що задав запитання або зробив ставку, повідомляється зміна в торгах на електронну пошту.

Фактично: Учаснику, що задав питання або зробив ставку, на електронну пошту не приходять повідомлення про редагування торгів

![image](https://user-images.githubusercontent.com/11888281/34407290-474b712e-ebc6-11e7-8792-588623856fc4.png)

Пересікається з 1659: нема листа задавшому питання.

**Comment by f3man** [comment]
поправив, тепер відправляється лист на пошту
