### ISSUE TITLE
Пошук за Орендою та площею не реалізований.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1661]
http://test.smarttender.biz/ru/auktsiony-na-prodazhu-aktivov-gospredpriyatiy/
smatest2@yopmail.com

Відтворення:
1. Залогуватись як учасник
2. Перейти до Аукціони на продаж активів держ підприємств.
3. Відкрити розширений пошук
4. Вибрати Форму торгів Оренда
5. Задати мінімальну та максимальну площу нерухомості.

Очікувано: Можна шукати за видом торгів Оренда. Можна шукати за плщою коли вибрана форма торгів Оренда.

Фактично шукати за площею та формою торгів оренда неможливо.

![image](https://user-images.githubusercontent.com/11888281/34410805-651e32e4-ebdb-11e7-8527-c65b4c0f4c1f.png)

**Comment by f3man** [comment]
![image](https://user-images.githubusercontent.com/16836558/34413134-16586aee-ebea-11e7-9917-e73c91f63e14.png)
пошук за орендою реалізовано

**Comment by f3man** [comment]
![image](https://user-images.githubusercontent.com/16836558/34434882-f4085b22-ec91-11e7-851f-81f9a668d5fc.png)
пошук за площею реалізовано

**Comment by w-be** [comment]
Пошук за орендою працює нормально.

**Comment by w-be** [comment]
http://test.smarttender.biz/test-tenders/?mode=prop&extfilter=1&statuses=%2B&sqmt=5&f=UA-PS-2017-12-30-000003-1&nh=1
площа 15.123
Пошук за м кв. працює не докінця: а) При введенні мінімального обмеження не знаходить; б) Максимальне поле не працює. 
![image](https://user-images.githubusercontent.com/11888281/34450014-cabc1980-ed08-11e7-8fc0-3e39b3e16597.png)

**Comment by f3man** [comment]
поправив, буде діяти для цього аукціона та усіх нових створених
