### ISSUE TITLE
Vidol: Користувач НЕ отримує повідомлення електронною поштою

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1664]
1. Отримання повідомлення про успішну/неуспішну активацію Замовника
2. Користувач НЕ отримує повідомлення про те, що обліковий запис знаходиться в стадії перевірки.
3. Користувач НЕ отримує повідомлення електронною поштою та в особистому кабінеті про те, що його запис або активований, або треба виправити помилки

**Comment by SergeAntonets** [comment]
фикс
