### ISSUE TITLE
Vidol: Посилання невалиднi

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1667]
![link auk](https://user-images.githubusercontent.com/13050207/34440674-6a35200a-ecbf-11e7-84fa-829299aa1f7f.png)
**Фактичий результат**
Писилання невалиднi
(тільки цей вірний і переводить на аукціон - "Для участі в аукціоні перейдіть за посиланням." )

**Comment by SergeAntonets** [comment]
фикс
