### ISSUE TITLE
Кваліфікація. Не можливо дискваліфікувати 2-го учасника.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1668]
http://test.smarttender.biz/webclient/(S(3240gymzcemhfb4xo5jbinxo))/?promptLogin=1&proj=it_uk&testmode=1&tz=2
osmatest@yopmail.com
UA-PS-2017-12-29-000085-2

Відтворення:

1. Залогуватись в аплікацію як замовник.
2. Перейти до своїх торгів в стані кваліфікація.
3. Дискваліфікувати 1- го учасника.
4. Спробувати дискваліфікувати 2-ого учасника.

Очікувано:
Другий учасник дискваліфікується

Фактично: 
З"являється помилка. Учасник очікує завантаження протоколу.

![image](https://user-images.githubusercontent.com/11888281/34447252-df20dc80-ecea-11e7-8529-7ae9a2392336.png)

**Comment by f3man** [comment]
виправлено, учасник фактично був дискваліфікований, але аукціон не було синхронізовано

**Comment by w-be** [comment]
Можна дисквалійікувати.
Нема можливості прикріпити файл при дискваліфікації.

**Comment by f3man** [comment]
виправив

**Comment by f3man** [comment]
виправив
