### ISSUE TITLE
Кваліфікація. Можливо додати протокол після закінчення 6 днів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1669]
Можна додати протокол і перейти до підписання контракту після періоду протоколу 6 днів(36 хв з прискоренням 240)

UA-PS-2017-12-29-000042-3
http://test.smarttender.biz/webclient/(S(3240gymzcemhfb4xo5jbinxo))/?promptLogin=1&proj=it_uk&testmode=1&tz=2
osmatest@yopmail.com

Відтворення:

1. Залогуватись в аплікацію як замовник.
2. Перейти до своїх торгів в стані кваліфікація.
3. Дочекатись щоб пройшло 6 днів (36 хвилин на пісочниці, прискорення 240)
4. Спробувати додати протокол

Очікувано:
Протокол додати не можливо - вийшов час.

Фактично:
Можливо додати протокол.
![image](https://user-images.githubusercontent.com/11888281/34447879-c90f9d36-ecf0-11e7-871a-f14d220f87a6.png)

**Comment by f3man** [comment]
виправив, тепер система при натисканні кнопки "Кваліфікація" буде повідомляти про прострочення вкладення протоколу:
![image](https://user-images.githubusercontent.com/16836558/34482799-0fc831aa-efc3-11e7-95d6-97c3e8f0d16d.png)

також
1. Кнопка "Перегляд" для додавання файлів стає неактивною
2. Кнопка "Підтвердити перевірку протоколу" стає не активною
3. Кнопка "Відхилити пропозицію" залишається єдиною можливою дією
![image](https://user-images.githubusercontent.com/16836558/34482913-c0083e02-efc3-11e7-9471-5153886d15e7.png)
