### ISSUE TITLE
ЕЛЕГ, вкажіть будь-ласка, які поля при створенні тендера є обов'язковими?

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#167]

**Comment by myroslav** [comment]
Є обмеження, які накладає ЦБД, починати варто з http://api-docs.openprocurement.org/en/latest/standard/tender.html і далі по посиланнях, обов'язкові поля позначаються як _required_. 

Майданчик має право (MAY) вимагати більше полів як обов'язкові, згідно з іншими бізнес процесами, які пов'язані з їх бізнес процесами (наприкад при реєстрації вимагати URL сайту організації).

Залишу це повідомлення як відкрите і віддам @lerich щоб він прокоментував, чи є в них додаткові вимоги. @OksanaPakholok якщо вважаєте питання вичерпаним, - то закривайте.

**Comment by S-Shevchenko** [comment]
Наступні поля:
Назва закупівлі
Детальний опис закупівлі
Максимальна сума закупівлі, грн.
Мінімальний крок аукціону, грн.
Дата завершення прийому запитань
Період прийому пропозицій
Детальний опис предмету закупівлі
Кількість
Одиниця виміру
Класифікатор CPV
Класифікатор ДКПП

**Comment by YuraOvramets-SoftServe** [comment]
Уточніть, будь ласка, на рахунок періоду прийому пропозицій - мається на увазі початкова дата прийому пропозицій і кінцева чи тільки кінцева? 
Ці поля є обов’язковими тільки для ЕЛЕГ чи вони актуальні для всіх майданчиків?

**Comment by S-Shevchenko** [comment]
На малюнку 1 - початкова дата, 2 - кінецева дата.
![screenshot_15](https://cloud.githubusercontent.com/assets/10655287/7609647/b6a3e5e4-f97d-11e4-94a1-a9d282009b76.jpg)
Поля обовязкові згідно ЦБД, назви можуть відрізнятися.

**Comment by myroslav** [comment]
Обов'язковими з точки зору ЦБД є кінцеві строки подачі запитань та кінцевий строк подачі пропозицій. Початкові строки можна не вказувати. Майданчик має право вимагати більше даних ніж вимагає ЦБД
