### ISSUE TITLE
Повідомлення. 2-й часник не отримує листа і повідомлення в особистому кабінеті про те, що він може не забирати гарантійний внесок.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1670]
http://test.smarttender.biz/auktsiony-na-prodazh-aktyviv-derzhpidpryemstv/3114670/
smatest2@yopmail.com
UA-PS-2017-12-29-000042-3

Відтворення:
1. Подати ставку на аукціон.
2. Посісти друге місце в аукціоні.
3. Перевірити електронну пошту, перевірити особисті повідомлення.

Очікувано: Користувачу повідомляється про те, що він може не забирати гарантійний внесок 20 днів в особистому кабінеті та на електронній пошті.

Фактично: ніяких повідомлень не приходить учаснику який заняв 2-ге місце.

![image](https://user-images.githubusercontent.com/11888281/34448219-1ffe530a-ecf4-11e7-9097-13c9bc00e74a.png)

**Comment by f3man** [comment]
виправив, тепер повідомлення приходить
![image](https://user-images.githubusercontent.com/16836558/34528564-f4d5791c-f0b1-11e7-87a6-bb609bf2a256.png)
