### ISSUE TITLE
Кваліфікація. Неможливо закрити торги без підтверження оплати.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1671]
http://test.smarttender.biz/webclient/(S(ckdgxjz53vxm2y2igsf5yp3o))/?proj=it_uk&promptLogin=1&testmode=1&tz=2
osmatest@yopmail.com
UA-PS-2017-12-29-000011-2

Відтворення:
1. Залогуватись в аплікацію як замовник.
2. Знайти торги в статусі кваліфікації.
3. Завантажити протокол.
4. Спробувати Завантажити та підтвердити протокол.

Очікувано: Замовник може закрити торги без підтверження оплати.

Фактично: Замовник не може закрити торги без підтверження оплати.

![image](https://user-images.githubusercontent.com/11888281/34449411-62953d9e-ed00-11e7-9aea-d9c378fa5ea1.png)

**Comment by f3man** [comment]
поправив
