### ISSUE TITLE
vapol: не приходять повідомлення учасникам в кабінет та на пошту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1672]
Відсутні такі повідомлення:
1. Повідомлення з посиланням на модуль електронного аукціону.
2. Отримати повідомлення про скасування Аукціону, на який Учасник задавав запитання̈
3. Отримати повідомлення про визнання Учасника переможцем аукціону
4. Отримати повідомлення про визнання Учасника Кандидатом наступним за переможцем
5. Учасники - отримали сповіщення на e-mail та/або особистий кабінет, про завершення/результат торгів с посиланням на сторінку аукціону.

**Comment by greeschenko** [comment]
причина була в невірно налаштованій таймзоні програмного середовеща веб серверу
зараз все має працювати.

**Comment by SoftserveQC1** [comment]
Дефект виправлено та перевірено.
