### ISSUE TITLE
Skyline: Exception trace при спробі відмінити участь в аукціоні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1673]
1. Голландський аукціон.  
2. Прийняти участь
3. Завершити аукціон
4. Зайти на деталі аукйціону
5. Натиснути кнопку "Відмінити"

Актуальній результат:
Трейс з помилкою (див аттач)

Очікуваний результат:
Інформативне сповіщення, яке можна побачити, якщо натиснути повернутись в браузері.

p.s. Також будь-ласка перевірте, що гарантійний внесок повертається.
[cancel_trace.txt](https://github.com/openprocurement/frontend/files/1604483/cancel_trace.txt)

**Comment by greeschenko** [comment]
Додали додаткових перевірок, зараз не має бути помилки

**Comment by SoftserveQC1** [comment]
Closing as fixed
