### ISSUE TITLE
Skyline: Відсутні сповіщення на електронну адресу та в кабінеті користувача

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1674]
1)Отримати повідомлення про успішну валідацію пропозиції.Виконується після подання Учасником пропозиції
"Отримати повідомлення в особистому кабінеті Учасника при наступному вході в нього. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до аукціону. 
Отримати повідомлення електронною поштою. 
В повідомленні повідомляється про публікацію в ЦБД пропозиції, дату і час публікації, дату і час початку аукціону і посилання на аукціон в режимі учасника"

2)Отримати повідомлення про неуспішну валідацію пропозиції. Виконується після подання Учасником пропозиції
"Отримати повідомлення в особистому кабінеті Учасника при наступному вході в нього. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до аукціону. 
Отримати повідомлення електронною поштою. 
В повідомленні повідомляється про неуспішне проходження валідації (з вказанням причини) або відсутність гарантійного внеску / банківської гаранії та лінк на пропозицію для внесення змін"

3)Отримати посилання на модуль електронного аукціону
Після завершення періоду прийому пропозицій отримати посилання на модуль аукціону електронною поштою та у кабінеті Учасника.

4)Отримати повідомлення про скасування Аукціону, на який Учасник задавав запитання чи подавав пропозиції
"Отримати повідомлення про скасування Організатором Аукціону в особистому кабінеті при наступному вході в нього.
Отримати повідомлення про скасування Організатором Аукціону  електронною поштою
Якщо скасування відбулось до розкриття пропозицій, пропозиції, подані на скасований аукціон, не розкриваються та не оприлюднюються"

**Comment by greeschenko** [comment]
1) повідомлення не спрацювали так як в системі увімкнено автоматичну акцептацію пропозицій для спрощення тестування (коли будете готові протестувати цей кейс напишіть нам в тестовий канал і ми вимкнемо авто режим)

2) ми не відмовляємо клієнтам якщо є якісь проблеми чи питання з клієнтом особисто зв'язується менеджер та вирішує всі питання 

3) та 4) в нас була проблема з планувальником розсилки, причина в невірно налаштованій таймзоні програмного середовеща веб серверу
зараз все має працювати.

**Comment by SoftserveQC1** [comment]
Closing as fixed
