### ISSUE TITLE
Документи. Учасник не може додити всіх типів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1675]
https://sale.akc.biz.ua/test/auction/UA-EA-2018-01-05-000196-2/
akc1@yopmail.com

Вітворення:
1. Знайти учасником торги в статусы подача пропозиції
2. Подати пропозицію.
3. Додати до пропозиції документи.
4. Виграти торги.
5. Додати документи до пропозиції.

Очікувано: Підчас подачі пропозиції можна подавати: 
1. commercialProposal - Цінова пропозиція
2. qualificationDocuments - Документи, що підтверджують кваліфікацію
3. eligibilityDocuments - Документи, що підтверджують відповідність (в тому числі, відповідність вимогам ст. 17)
4. financialLicense - Ліцензія (доступно лише для dgfFinancialAssets процедури, див. Фін. туторіал) , так як є - ок: "Фінансова Ліцензія/ Розписка"

Підчас кваліфікації можна додати всі ті самі + auctionProtocol - Протокол торгів

Фактично: Учасник може додати тільки документи типу: financialLicense "Фінансова Ліцензія/ Розписка"

![image](https://user-images.githubusercontent.com/11888281/34615235-d71e1258-f23c-11e7-91c0-7ce737463b57.png)

**Comment by v-lego** [comment]
не можемо прийняти.
За стандартними сценаріями 
"Якщо аукціон йде по процедурі dgfFinancialAssets або dgfInsider (Голландський аукціон) - можливість завантаження фінансової ліцензії\розписки"
