### ISSUE TITLE
Skyline. Відсутні сповіщеня про початок аукціонів крім Голландських

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1676]
Відсутні сповіщення про початок аукціону в UI та email для аукціонів:
-Продаж права вимоги
-Продаж майна банків

Текст сповіщення:Увага! Аукціон скоро розпочнеться - Переглянути або Взяти участь

Note: Сповіщення **працює** для Голландських аукціонів

**Comment by greeschenko** [comment]
Ми протестували цей кейс 2 рази підряд і всі повідомлення пришли 

Також ми перевірили код і надсилання повідомлень не залежить від типу аукціону

Перевірьте будь ласка ще раз і якщо будуть затримки відразу пишіть нам в слек канал ми розглянемо статуси виконання планувальника розсилки

**Comment by SoftserveQC1** [comment]
Closing as non reproducible
