### ISSUE TITLE
Skyline: Відсутні сповіщення для кейсу відміни участі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1677]
Відсутні сповіщення для кейсу відміни участі в аукціоні (користувач посів друге місце і хоче забрати внесок)
Додайте будь-ласка для UI та email нотіфікації для всіх трьох видів аукціонів

**Comment by greeschenko** [comment]
Не зовсім зрозуміло для якої ролі мають бути ці сповіщення, адже організатор має працювати на единому кабінеті і саме система единого кабінету має відслідковувати зміни статусів та сповіщати організатора

щодо сповіщення майданчика, так як робота з гарантійкою проходить в ручному режимі забирати гарантійний клієнт буде через менеджера

**Comment by SoftserveQC1** [comment]
Користувач, який відмінив участь в аукціоні і хоче повернути гарантійній внесок має отримати повідомлення в кабінеті та email нотифікацію.
Наприклад: "Участь відмінено, чекайте на повернення внеску"

**Comment by greeschenko** [comment]
Так  як робота з коштами крім подачі пропозиції до голландського аукціону проходить в ручному режимі повернення гарантійного в будь якому разі буде проходити через менеджера і всі учасники абсолютно точно будуть знати про цю дію

плюс надсилання сповіщення про дію яку сам користувач і виконав ми вважаємо надлишковою

**Comment by SoftserveQC1** [comment]
Closing as designed
