### ISSUE TITLE
Skyline: Невірно доставлені сповіщення о перемозі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1678]
![1](https://user-images.githubusercontent.com/13050207/34776944-4034ef2c-f621-11e7-9e58-8e052cae0755.png)
![2](https://user-images.githubusercontent.com/13050207/34776945-40579b80-f621-11e7-8531-81e176460f4b.png)

http://test.skyline.auction/prozorrosale/auctions/4720
bitvova7@gmail.com фин комп
GekdwOIxWT
Переміг

tolkemek@gmail.com физ
VkZfKrwwTq
Отримав сповіщення о перемозі

1.Створюємо аукціон
2. Робимо однакові ставки двома учасниками

Актуальний результат:
Сповіщення о перемозі надіслано користувачеві посівшему друге місце

Очікуваний результат:
Сповіщення о перемозі надіслане користувачеві посівшему перше місце

**Comment by greeschenko** [comment]
додали фікс

**Comment by SoftserveQC1** [comment]
Closing as fixed
