### ISSUE TITLE
DTO: не можна відредагувати вартість лоту в сторону збільшення.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1684]
http://www.dz3.byustudio.in.ua/
 
**Відтворення:**
1. Залогуватись як Замовник.
2. Створити новий аукціон.
3. Після публікації аукціону з пункту 2 в тілі аукціону натиснути кнопку "Редагувати".
4.  У полі "Початкова ціна продажу лоту" ввести більше значення.
5. Натиснути кнопку "Зберегти".

**Очікуваний результат**: Зміни зі збільшенням вартості лоту успішно збережені

**Фактичний результат**: Зміни не збережено з помилкою "Будь ласка, введіть правильне значення " біля поля "Початкова ціна продажу лоту".

**Comment by PaulBoroday** [comment]
Згідно з проточною редакцією ТЗ, зазначена дія заборонена. Знаю про плани, але наразі, бага безпідставна

**Comment by PaulBoroday** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено та перевірено.
