### ISSUE TITLE
BiddingTime: неможливо редагування вартості лоту і полів, пов’язаних з вартістю, в бік збільшення

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1685]
https://etm.biddingtime.com.ua/

**Кроки для відтворення:**
1. Увійти в аккаунт, під роллю “Замовника”
2. Створити аукціон із заповненням всіх необхідних полів
3. Опублікувати аукціон
4. Редагувати створений вище аукціон
5. Редагувати наступні поля в бік збільшення значення
5.1. Початкова ціна
5.2. Розмір гарантійного внеску
5.3. Мін. крок торгів, грн

**Фактичний результат**
1. НЕможливо редагування вартості лоту і полів, пов’язаних з вартістю, в бік збільшення
2. Виникає повідомлення "Дозволяється тільки зменшувати суму"

**Очікуваний результат**
1. Можливо редагування вартості лоту і полів, пов’язаних з вартістю, в бік збільшення

**Kоментар**
Проблема в документації "ТЗ для майданчиків"
п.1. У межах існуючої процедури на ЦБД-2 реалізовано можливість редагування вартості лоту і полів, пов’язаних з вартістю (дозволяється лише пониження).
п.1.а. Від тепер поля value.amount , guarantee.amount та minimalStep.amount можна редагувати.

**Comment by reactlogic** [comment]
Исправлено 31.01.2018 (неправильно поняли документацию)

**Comment by SoftserveQC1** [comment]
Проверено - PASS
