### ISSUE TITLE
Надходить повідомлення про внесені зміни до аукціону після того, як Учасником було задане питання

### ISSUE THREAD

**Issue by olyamalysh** [openprocurement/frontend#1689]
http://test.neb.org.ua

Надходить повідомлення про внесені зміни до аукціону після того, як Учасником було задане питання

Кроки для відтворення:
1. Подати пропозиції до аукціону
2. Задати запитання до аукціону
3. Перевірити пошту Учасників, що подали пропозиції до аукціону

Очікуваний результат
На пошту надходить повідомлення лише Учаснику, що ставив питання, про те, що його питання прийняте

Фактичний результат
Надходить додатково повідомлення всім учасникам, які подавали пропозиції, що до аукціону внесено зміни 
https://gyazo.com/32c5fe6fca0c6b71c71e88ee0554ebf8

**Comment by IllyaPetrusenko** [comment]
Исправлено. Можете проверять и закрыть дефект.

**Comment by olyamalysh** [comment]
Дефект відтворюється https://gyazo.com/b2530285b8479dcdf9512e96ae5beedf

**Comment by IllyaPetrusenko** [comment]
А сейчас?)

**Comment by olyamalysh** [comment]
Дефект не відтворився. Дякую!
