### ISSUE TITLE
ЕЛЕГ, користувач не має можливості задавати запитання, коли тендер перебуває на етапі "Період уточнень"

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#169]
Згідно "Регламенту роботи майданчика", п. 1. "Визначення понять", ст.1  "Користувач – відвідувач, який перейшов за посиланням http://e-tender.biz/ в мережі Інтернет без проходження процедури реєстрації" 

Згідно "Регламенту роботи майданчика", п. 8. "Запитання", ст. 7, "Всі Користувачі мають право задавати питання Замовнику щодо оголошеної закупівлі протягом періоду, визначеного Замовником в оголошенні, але до початку подання пропозицій."

![no_questions](https://cloud.githubusercontent.com/assets/11062040/6672406/f512084c-cc14-11e4-9c0e-9e9e436e029e.png)

Про це також зазначено у "Керівництві користувача", п.1 "Визначення понять", ст.3 - "Користувач - ..." та п.2, ст.4, "Початок роботи у системі. Знайомство з ресурсами сайту" - "Користувачі можуть задавати питання Замовнику щодо закупівлі"

та у "Керівництві Замовника", п.1 "Визначення понять", ст.3 - "Користувач - ..." та п. 7, ст.22 "Питання по тендеру від Користувачів".

**Comment by lerich** [comment]
Да, совершенно верно! Надо переделать на "Зареєстрований Користувач". Учтем
в новой версии инструкции и регламента.

2015-03-16 20:09 GMT+02:00 OksanaPakholok valeriy.nesmashnyy@gmail.com:

> Згідно "Регламенту роботи майданчика", п. 1. "Визначення понять", ст.1
> "Користувач – відвідувач, який перейшов за посиланням http://e-tender.biz/
> в мережі Інтернет без проходження процедури реєстрації"
> 
> Згідно "Регламенту роботи майданчика", п. 8. "Запитання", ст. 7, "Всі
> Користувачі мають право задавати питання Замовнику щодо оголошеної
> закупівлі протягом періоду, визначеного Замовником в оголошенні, але до
> початку подання пропозицій."
> 
> [image: no_questions]
> https://cloud.githubusercontent.com/assets/11062040/6672406/f512084c-cc14-11e4-9c0e-9e9e436e029e.png
> 
> Про це також зазначено у "Керівництві користувача", п.1 "Визначення
> понять", ст.3 - "Користувач - ..." та п.2, ст.4, "Початок роботи у системі.
> Знайомство з ресурсами сайту" - "Користувачі можуть задавати питання
> Замовнику щодо закупівлі"
> 
> та у "Керівництві Замовника", п.1 "Визначення понять", ст.3 - "Користувач
> - ..." та п. 7, ст.22 "Питання по тендеру від Користувачів".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openprocurement/frontend/issues/169.

## 

С уважением,
Мельник Иванна
