### ISSUE TITLE
Prom: відсутня можливість використовувати коди класифікатора CAV-PS

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1691]
https://my.zakupki.dz-test.net/

**Pre-Conditions:** 
Увійти як Замовник 

**Description:**
Почати створювати аукціон будь-якого типу (продаж\оренда).
При заповненні інформації предметів продажу обрати класифікатор.

**Expected result:** 
Обрати між CAV-PS та CPV

**Actual result:** 
Маємо лише класифікатор CPV
![946ce7ea61](https://user-images.githubusercontent.com/13050207/35975350-17e34cb4-0ce5-11e8-9651-b590727615e8.png)

**Comment by znakharenko** [comment]
https://my.zakupki.dz-test.net/cabinet/purchases/state_auction/view/745553

вот вы создавали, как раз с CAV
http://prntscr.com/ibyoqn

у нас кнопка называется CPV, но по факту там намешаны CPV и CAV

**Comment by SoftserveQC1** [comment]
Следует изменить название кнопки на CPV/CAV-PS

**Comment by niksdorf** [comment]
done on dz-test
