### ISSUE TITLE
NewTend: Нема повідомлення про валідацію ставки, якщо ставка менше стартової ціни лота

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1692]
https://cdb2-dev.newtend.com

**Кроки для відтворення:**
1. Увійти в акаунт Замовника.
2. Створити і опублікувати Аукціон 
Стартова ціна реалізації лота (UAH) - 10 000 
3. Увійти в акаунт Учасника_1.
4. Подати пропозицію на Аукціон від Учасника_1.
Цінова пропозиція - 11 000
5. Відредагувати Аукціон_1 Замовником таким чином, щоб стартова ціна аукціону  була вище цінової пропозиції учасника
Стартова ціна реалізації лота (UAH) - 15 000 
6. Увійти в акаунт Учасника_1 и перейти в Аукцioн
7. Натиснути кнопку "Підтвердити ставку"

**Фактичний результат:** 
Повідомлення "Сталася помилка. Будь ласка, зв'яжіться з нашою службою підтримки"

**Очікуваний результат:** 
Повідомлення про валідацію ставки:
"Ваша ставка нижча за стартову ціну лота. Будь ласка, поміняйте ставку"

**Comment by SlaOne** [comment]
Исправлено, при попытке подтвердить меньшую ставку чем новая цена лота - "Ставка должна быть больше или равна стартовой цене лота"

**Comment by SoftserveQC1** [comment]
**Проверено**
Изменено через отмену ставки со следующим сообщением:
"В условия аукциона были внесены изменения
Если стартовая цена реализации лота увеличилась, то необходимо отменить ставку и сделать новую"

При нажатии кнопки "Подтвердить ставку" выводит сообщение
"Ставка должна быть больше или равна стартовой цене лота"

**Comment by SoftserveQC1** [comment]
Check - PASS
Проверено - Пройдено
Баг закрыт
