### ISSUE TITLE
Prom: користувач не отримує повідомлення про зміни в особистому кабінеті, на пошту приходить не вірний текст

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1693]
https://my.zakupki.dz-test.net/

**Pre-Conditions:**
Увійти як Замовник.
Створити аукціон.

**Description:**
Під роллю Учасника подати пропозицію до аукціону. 
Замовником внести зміни до аукціону.

**Expected result:**
Користувач отримує лист на пошту та повідомлення у особистий кабінет з таким текстом:
“Організатор торгів змінив умови проведення аукціону, всі закриті цінові пропозиції деактивовано. Вам необхідно підтвердити або змінити свою закриту цінову пропозицію для участі в аукціоні.”

**Actual result:**
Учасник отримує лист на пошту із текстом 
"Торги [*******], до яких ви подали пропозицію, були відредаговані організатором. Ви можете ознайомитись зі змінами на сторінці торгу."
![946ce7ea61](https://user-images.githubusercontent.com/13050207/35976295-5cb5e65a-0ce8-11e8-99a2-56733617772b.png)

**Comment by niksdorf** [comment]
done on dz-test

**Comment by SoftserveQC1** [comment]
В особистому кабінеті все ще немає жодних повідомлень

**Comment by SoftserveQC1** [comment]
Особливості майданчика, відображено у звіті
