### ISSUE TITLE
NewTend: Нема можливості підтвердити згоду з умовами Аукціону при підтвердженні ставки Учасником

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1694]
https://cdb2-dev.newtend.com

**Кроки для відтворення:**
1. Увійти в акаунт Замовника.
2. Створити і опублікувати Аукціон
3. Увійти в акаунт Учасника_1.
Подати пропозицію на Аукціон від Учасника_1.
4. Відредагувати Аукціон_1 Замовником 
5. Увійти в акаунт Учасника_1 и перейти в Аукцioн
Натиснути кнопку "Підтвердити ставку"

**Фактичний результат:**
Нема можливості підтвердити згоду з умовами Замовника\З умовами Аукціону 
(оферта, чекбокс, будь-які інші варіанти)

**Очікуваний результат:**
Є можливість підтвердити згоду з умовами Замовника\З умовами Аукціону 
(оферта, чекбокс, будь-які інші варіанти)

**Comment by SlaOne** [comment]
особенность реализации на площадке.
при регистрации пользователь отмечает чек боксы согласия с офертой и регламентом.
когда участник делает ставку, даже если он это сделал неосознанно, или пытался навредить "системе", ставка публикуется в статусе "черновик" и ждет подтверждения со стороны администратора площадки. Подтверждение ставка получает только после зачисления гарантийного взноса на счет площадки. И только после этого пользователь должен самостоятельно опубликовать свою ставку

**Comment by SoftserveQC1** [comment]
Close - As Design
