### ISSUE TITLE
Prom: неможливо опублікувати відредагований аукціон у браузері Edge

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1695]
https://my.zakupki.dz-test.net/

**Description:**
Увійти як Замовник.
Створити аукціон, опублікувати, внести до нього зміни.

**Expected result:**
Аукціон успішно оновлено

**Actual result:**
Поле з датою проведення аукціону очищене, та обов'язкове для заповнення. Відредагувати його не можна, а разом із тим оновити аукціон.
![cefe043e3b](https://user-images.githubusercontent.com/13050207/35976904-369aab34-0cea-11e8-9b55-04ae09650e49.jpg)

**Comment by niksdorf** [comment]
done
фикс уже на zakupki.dz-test.net

**Comment by SoftserveQC1** [comment]
Перевірено
