### ISSUE TITLE
Prom: учасник отримує на пошту лист російською, який дублюється і стосується змін в аукціоні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1696]
https://my.zakupki.dz-test.net/

**Description:**
Увійти як Замовник.
Створити аукціон, опублікувати.
Учасником подати пропозицію.
Замовником внести зміни до аукціону.

**Expected result:**
Учасник на пошту отримує лист з текстом: "Організатор торгів змінив умови проведення аукціону, всі закриті цінові пропозиції деактивовано. Вам необхідно підтвердити або змінити свою закриту цінову пропозицію для участі в аукціоні.”

**Actual result:**
Учасник на пошту отримує 3 листи, 2 з яких від іншого відправника та написані російською.
![946ce7ea61](https://user-images.githubusercontent.com/13050207/35982749-36172930-0cf9-11e8-9572-83b2a022c1fe.png)

**Comment by niksdorf** [comment]
done on dz-test
