### ISSUE TITLE
NewTend: Кнопка  "Підтвердити ставку" активна пiсля підтвердження ставки учасником

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1697]
https://cdb2-dev.newtend.com

**Кроки для відтворення:**
1. Увійти в акаунт Замовника.
2. Створити і опублікувати Аукціон 
3. Увійти в акаунт Учасника_1.
4. Подати пропозицію на Аукціон від Учасника_1.
5. Відредагувати Аукціон_1 Замовником 
6. Увійти в акаунт Учасника_1 и перейти в Аукцioн
7. Натиснути кнопку "Підтвердити ставку"

**Фактичний результат:** 
Кнопка  "Підтвердити ставку" активна
Повторне натискання кнопки призводить до повідомлення 
"Сталася помилка. Будь ласка, зв'яжіться з нашою службою підтримки"

**Очікуваний результат:** 
1. Учасник отримує повідомлення "Ваша ставка підтверджена" или "Ваша пропозиція активована"
2. Кнопка "Підтвердити ставку" зникає
3. З'являється кнопка "Змінити ставку" з відповідним функціоналом

**Comment by SlaOne** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
Проверено - Пройдено

Рекомендуется выводить, что подтверждение ставки прошло успешно на экран монитора для удобства пользователя (не только в виде сообщения по почте)
