### ISSUE TITLE
ЕЛЕГ: не могу создать профиль

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#17]
Заполнил все поля. Кстати, в почтовом индексе у нас только пять знаков :)
В любом случае, в конце получил ошибку:

![image](https://cloud.githubusercontent.com/assets/9398532/5873628/19875674-a301-11e4-9761-b057b098a2c3.png)

**Comment by S-Shevchenko** [comment]
Исправили.
Валидация "Повна назва" +  "Індекс"

**Comment by andriykucherenko** [comment]
Что означает Валидация "Повна назва" + "Індекс"?
Я опять получил быстро исчезнувшую ошибку "Интернал еррор...", которую я даже не успел заскриншотить. Обычный пользователь точно не разберется, что у него пошло не так.

**Comment by andriykucherenko** [comment]
![image](https://cloud.githubusercontent.com/assets/9398532/5887031/1a2d2022-a3c4-11e4-96b4-d5de162b9fd8.png)
