### ISSUE TITLE
ЕЛЕГ, немає доступу до тестового середовища на http://services.e-tender.biz:100/#/

### ISSUE THREAD

**Issue by OksanaPakholok** [openprocurement/frontend#170]

**Comment by lerich** [comment]
Извините, тестовое окружение переносится на другую машину. Напишим когда закончим работы.

**Comment by yuliyaSoftserve** [comment]
@lerich  @myroslav  Прошу повідомити чи є апдейти щодо цього запиту?

**Comment by lerich** [comment]
добрый день. Сори. Новое тестовое окружение uat.e-tender.biz
