### ISSUE TITLE
NewTend: Редагування можливо після Кінця періоду редагування

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1703]
https://cdb2-dev.newtend.com

**Кроки для відтворення:**
1. Увійти в акаунт Замовника.
2. Створити і опублікувати Аукціон 
3. Дочекатися фактичного часу кінця періоду редагування

**Фактичний результат:** 
1. Редагування аукціону можливо після зазначеної дати Кінця періоду редагування
2. Кнопка "редагувати аукціон" активна

**Очікуваний результат:** 
1. Редагування аукціону НЕможливо після зазначеної дати Кінця періоду редагування
2. Кнопка "редагувати аукціон" відсутня

**Comment by SlaOne** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
Check - PASS
Проверено - ПРОЙДЕНО
