### ISSUE TITLE
NewTend: Учасник НЕ отримує нагадування електронною поштою зміни в умови проведення аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1704]
https://cdb2-dev.newtend.com

**Кроки для відтворення:**
1. Увійти в акаунт Замовника.
2. Створити і опублікувати Аукціон
3. Увійти в акаунт Учасника_1.
Подати пропозицію на Аукціон від Учасника_1.
4. Відредагувати Аукціон_1 Замовником 
5. Дочекатися періоду 24 години або наступного дня

**Фактичний результат:**
Учасник НЕ отримує нагадування електронною поштою та в особистому кабінеті, що містить такий текст: 
“Організатор торгів зміни в умови проведення аукціону, всі закриті цінові пропозиції деактивовано. Вам необхідно підтвердити або змінити свою закриту цінову пропозицію для участі в аукціоні.”

**Очікуваний результат:**
Учасник отримує нагадування електронною поштою та в особистому кабінеті, що містить такий текст: 
“Організатор торгів зміни в умови проведення аукціону, всі закриті цінові пропозиції деактивовано. Вам необхідно підтвердити або змінити свою закриту цінову пропозицію для участі в аукціоні.”

**Comment by SlaOne** [comment]
тоже починили

**Comment by SoftserveQC1** [comment]
Check - PASS
Проверено - ПРОЙДЕНО
