### ISSUE TITLE
Prom: неможливо додати/замінити документ після закінчення періоду редагувань

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1709]
https://my.zakupki.dz-test.net/

**Description:**
Увійти як Замовник.
Створити аукціон, опублікувати.
Зачекати поки закінчиться період редагувань.

**Expected result:**
Є можливість лише додати/замінити документ до аукціону чи активу. При заміні попередній документ відображається перечеркнутим, а ставки учасників не інвалідуються.

**Actual result:**
Редагування неможливе.

**Comment by niksdorf** [comment]
done on dz-test

**Comment by SoftserveQC1** [comment]
Документи не завантажуються, показується лише лоадер
![fc91b2865d](https://user-images.githubusercontent.com/13050207/36413552-97ac1304-1627-11e8-833a-2bfdb89b7bee.jpg)

**Comment by SoftserveQC1** [comment]
Пофикшено
