### ISSUE TITLE
NewTend: ставки учасників інвалідуються, якщо при редагуванні не вносити зміни до аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1710]
https://cdb2-dev.newtend.com

**Кроки для відтворення:**
1. Увійти в акаунт Замовника.
2. Створити і опублікувати Аукціон 
3. Учасником подати пропозицію.
4. Замовником натиснути "редагувати" створенiй вище Аукцiон 
5. НЕ вносити зміни, зберегти аукціон.

**Фактичний результат:** 
Ставки інвалідовано, учасник отримав листа на пошту про зміну аукціону.

**Очікуваний результат:** 
Ставки учасників не інвалідуються. 
Нічого не оновлюється.

**Comment by SlaOne** [comment]
кнопка "сохранить" изменения не активна, если не было никаких взаимодействий с полями. 
если хоть какой-то символ был заменен, удален, добавлен - то сохранить изменения можно

**Comment by SoftserveQC1** [comment]
Check - PASS
Проверено - ПРОЙДЕНО
