### ISSUE TITLE
Smarttender: не всі обов'язкові для заповнення поля відмічені зірочкою

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1711]
http://test.smarttender.biz

**Передумови**
Увійти на сторінку реєстрації

**Очікуваний результат**
Обов'язкові для заповнення поля відмічені зірочкою

**Фактичний результат**
Деякі обов'язкові поля не виділені

![2](https://user-images.githubusercontent.com/13050207/37038124-9fa8f1ae-215c-11e8-931e-f0e9c9e2d7d8.jpg)
Наприклад, як в блоці "Контактна інформація"
![2 1](https://user-images.githubusercontent.com/13050207/37038182-ca0f361a-215c-11e8-8284-038a83d7eb4f.png)

**Comment by f3man** [comment]
Поправив
