### ISSUE TITLE
Smarttender: в деяких місцях має місце російський переклад

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1712]
http://test.smarttender.biz

**Передумови**
Увійти на сторінку реєстрації
Обрати роль "учасник" - "фізична особа"

**Очікуваний результат**
Всі тексти написані українською мовою

**Фактичний результат**
В блоці с завантаженням документів російський переклад
![1](https://user-images.githubusercontent.com/13050207/37038392-5770f9e4-215d-11e8-9368-af4f9a556657.jpg)

При виборі ролі у випадаючому списку:
![7437d40922](https://user-images.githubusercontent.com/13050207/37085662-4a60938a-21fe-11e8-819a-07156d34987b.jpg)

**Comment by f3man** [comment]
Поправив
