### ISSUE TITLE
Smarttender: текст майже зливається з іконками, не вистачає пробілу між ними

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1713]
http://test.smarttender.biz

**Передумови**
Увійти на сторінку реєстрації

**Фактичний результат** 
Між іконками та текстом не має вільного місця
![5](https://user-images.githubusercontent.com/13050207/37039908-4a117914-2161-11e8-971b-6cdb09462781.png)

**Очікуваний результат**
З пробілом виглядає краще та читабельніше
![6](https://user-images.githubusercontent.com/13050207/37039910-4bc8ea6c-2161-11e8-85df-434f42dd515c.png)

**Comment by f3man** [comment]
Поправив
