### ISSUE TITLE
Створення об'єкту МП | Не працює валідація.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1719]
Логін: sprozorro@gmail.com
Тестове середовище: http://test.e-trading.kiev.ua/prozorrosale2/auctions/assets-create
microsoft EDGE

**Відтворення:**
Зайти юридичною особою - органом приватизації в аплікацію.
Натиснути "Реєстр активів" -> "Додати обєкт МП" для створення.
Заповнити потрібні поля інформацією.
Натиснути "Зберегти об"єкт у реєстрі"

**Очікуваний результат1:** Об"єкт створено.
**Очікуваний результат2:** У разі заповнення полів невалідними даними -> Отримання помилки при збереженні з зрозумілими кроками для виправлення.  

**Фактичний результат:** Об"єкт не створено. Помилка Not Implemented (#501). Незрозумілий опис.

![r1 error 501](https://user-images.githubusercontent.com/13050207/40971523-9f13ec2e-68c6-11e8-8fb2-2c67cab172b1.PNG)

**Comment by greeschenko** [comment]
ця помилка була пов'язана з обмеженнями по довжині деяких параметрів на стороні нашого бекенду
наразі це виправлено

**Comment by SoftserveQC1** [comment]
перевірено, виправлено
