### ISSUE TITLE
На сторінці "Створення об'єкту МП" відображаються поля різними мовами

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1721]
Тестове середовище: http://test.biddingtime.com.ua
Логін: test.prozorro.participant01@gmail.com

Відтворення:
Зайти в "Об'єкти МП"
Натиснути на клавішу 'Додати об'єкт МП'.

Очікуваний результат: Всі поля іменовані українською мовою

Фактичний результат: Поля іменовані в перемішку, є поля українською та англійською мовами

**Comment by SoftserveQC1** [comment]
![localization](https://user-images.githubusercontent.com/13050207/41421752-1bf1794c-7000-11e8-88c1-da21bec5667e.JPG)

**Comment by w-be** [comment]
Duplicate #1722
