### ISSUE TITLE
На сторінці "Створення об'єкту МП" поля відображаються різними мовами

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1722]
Тестове середовище: http://test.biddingtime.com.ua
Логін: test.prozorro.participant01@gmail.com

Відтворення:
Натиснути на "Об'єкти МП" 
Натиснути на клавішу 'Додати об'єкт МП'.

Очікуваний результат1: Всі поля відображаються на українській мові

Фактичний результат: Поля відображаються різними мовами
![localization](https://user-images.githubusercontent.com/13050207/41422417-8bf06180-7001-11e8-927e-95983c41d64a.JPG)

**Comment by neros3** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
перевірено, виправлено
