### ISSUE TITLE
Інформаційне повідомлення можна редагувати через 48 годин.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1723]
https://my.zakupki.dz-test.net/cabinet/purchases/state_privatization_lot/view/715154
https://public.api-sandbox.ea2.openprocurement.net/api/2/lots/82a09a99f0fe40cdb709720ffd5ea8f7
promop@yopmail.com

Відтворення:
0. Інформаціїне повідомлення опубліковане в ЦБД більше наж 48 годин
1. Залогуватись користувачом з інформаційним повідомленням.
2. Знайти його.
3. Спробувати відредагувати інформаційне повідомлення і зберегти зміни.

Очікувано: Інформаційне повідомлення не можна редагувати якщо пройшло 48год з моменту публікації. 

Фактично: Інформаційне повідомлення редагується і воно збереженне в ЦБД.
![image](https://user-images.githubusercontent.com/11888281/41764434-c2b53e62-7609-11e8-9780-fccbf7446665.png)

**Comment by niksdorf** [comment]
поправили синхронизацию, должно быть ок

**Comment by olyamalysh** [comment]
Перевірено. Редагування аукціону неможливе
