### ISSUE TITLE
Інформаційне повідомлення. Повідомлення про синхронізацію не зникає після 5 хв.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1725]
https://my.zakupki.dz-test.net/cabinet/purchases/state_privatization_lot/view/715608
promop@yopmail.com

Відтворення:
1. Залогуватись користувачем Органом Приватизації.
2. Створити О'бєкт приватизації.
3. Створити Інормаційне Повідомлення.
4. Відредагувати Інформаційне повідомлення.
5. Зачекати 5 хв.

Очікувано: немає ніякого повідомлення що іде синхронізація з ЦБД.

Фактично Повідомлення про синхронізацію з ЦБД не зникає і через 10 хв.

![image](https://user-images.githubusercontent.com/11888281/41766075-abe89bac-760e-11e8-833d-b64bda7197b4.png)

**Comment by niksdorf** [comment]
поправили синхронизацию на dz-teste, должно быть ок

**Comment by olyamalysh** [comment]
перевірено. Після зміни статусу немає ніякого повідомлення що іде синхронізація з ЦБД.
