### ISSUE TITLE
Інформаційне повідомлення. Поле час і місце проведення огляду о'бєкту не зберігається.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1726]
https://my.zakupki.dz-test.net/cabinet/purchases/state_privatization_lot/edit/715611
promop@yopmail.com

Відтворення: 
1. Залогуватися Органом Приватизації, що має Інформаційне Повідомлення.
2. Відкрийте для редагування Інформаційне Повідомлення.
3. Внесіть зміни в поле "Час і місце проведення огляду об'єкту"
4. Збережіть зміни.
5. Перегляньте інформаційне повідомлення.

Очікувано: Внесенна інформація збережена.
Фактично: Інформація в поле "Час і місце проведення огляду об'єкту" втрачається.
![image](https://user-images.githubusercontent.com/11888281/41767510-73336446-7612-11e8-891d-e39e6928fbee.png)

**Comment by niksdorf** [comment]
готово
фикс на https://zakupki.dz-test.net/

**Comment by olyamalysh** [comment]
перевірено. Приклад інформаційного повідомлення UA-LR-SSP-2018-07-04-000196-2
