### ISSUE TITLE
Інформаційне повідомлення створюється автоматично.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1727]
https://my.zakupki.dz-test.net/cabinet/purchases/state_privatization_lot/view/715664
promop@yopmail.com

Відтворення:
1. Залогуватись Органом Приватизації.
2. Перейти до Об'єків приватизації.
3. Створити об\єкт приватизації.
4. Перевірити чи створено таке саме інформаційне повідомлення.

Очікувано: Інформацій повідомлення не створене автоматично. Можливо створити інформаційне повідомлення на основі об'єкта приватизації.

Фактично: Інформаційне повідомлення одразу створене у ЦБД. з відсутністю великої частини полів, які можна заповнити напротязі 48 годин. Пропускається статус інформаційного повідомлення Чернетка і валідація полів при першій публікації Інформаційного Повідомлення.
![image](https://user-images.githubusercontent.com/11888281/41773133-a73eb504-7623-11e8-8fa2-28cd2948abf9.png)

**Comment by olyamalysh** [comment]
перевірено. Виправлено
