### ISSUE TITLE
Інформацієне Повідомлення містить не точні назви атрибутів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1728]
Відтворення:
1. Створити інформаційне повідомлення
2. Перевірити назви полів.

Очікувано: Використовуються назви: 
а) Інформаційне повідомлення
б) Тип 1-го аукціону:  Аукціон
в) Тип 2-го аукціону:  Аукціон із зниженням стартової ціни
 г) тип 3-го фукціону:  Аукціон за методом покрокового зниження стартової ціни та подальшого подання цінових пропозицій

Фактично: Назви взяті з Продажу Держ Майна:
а) Лот,
б.в) Англійский аукціон,
г) Голанський аукціон.

![image](https://user-images.githubusercontent.com/11888281/41773214-f7ca7666-7623-11e8-8a84-1538fbca187e.png)

**Comment by niksdorf** [comment]
готово, фикс на https://zakupki.dz-test.net/

**Comment by olyamalysh** [comment]
https://gyazo.com/8754e670d0786c048785c18dd0bfb9a8

виправлено частину неймінгу. "Лот" присутній в системі

**Comment by niksdorf** [comment]
готово

**Comment by olyamalysh** [comment]
перевірено. Виправлено
