### ISSUE TITLE
Об'єкт приватизаії. Пошук. Не реалізовано повідомлення користувача про те що об'єкт вже є всистемі.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1729]
https://my.zakupki.dz-test.net/cabinet/purchases/state_privatization_asset/all?q=UA-AR-P-2018-06-22-000047-2
promop@yopmail.com

Відтворення:
1. Залогуватись Органом приватизації, що має об'єкт в реєстрі.
2.  Знайти Обєкт приватизації

Очікувано: користувачу повідомляється: “Об’єкт вже додано до переліку. Прохання використати існуючий об’єкт для публікації інформаційного повідомлення”.

Фактично: користувачу просто показується знайдений об'єкт.

![image](https://user-images.githubusercontent.com/11888281/41774045-c68d12b8-7626-11e8-81c9-3c143cdeb605.png)

**Comment by niksdorf** [comment]
готово

**Comment by olyamalysh** [comment]
Перевірено. Виправлено https://gyazo.com/653628caeb932dd12eb6104cd13a1091
