### ISSUE TITLE
Роль Огран Приватизації не втілено.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1730]
https://zakupki.dz-test.net/registration/supplier

Відтворення: 
1. Зайти на майданчик
2. Перейти на реєстрацію нового користувача.
3. Спробувати зареєструвати користувача Орган Приватизації.

Очікувано:
Можливо зареєструвати Орган Приватизації, який немає відношення до Регламентів, не може створювати аукціони напряму, не може приймати участь в аукціонах. Може Створювати Об'єкти Приватизації та інформаційні повідомлння, має доступ до їх реєстрів.

Фактично:
Можливість працювати з приватизацією надано ролі Організатор Торгів [з продажу держ майна].

![image](https://user-images.githubusercontent.com/11888281/41774617-2da7975a-7629-11e8-8470-ad265ca3ee3c.png)

**Comment by niksdorf** [comment]
особенность реализации площадкой

**Comment by niksdorf** [comment]
готово https://prnt.sc/k24v31

**Comment by olyamalysh** [comment]
Роль Органу приватизації втілено
https://gyazo.com/b0516d6d7bf62fe45c53840166ce9dad
