### ISSUE TITLE
Реєстри об'єктів малої приватизації і інформаційних повідомлень містять тільки те, що створив користувач.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1731]
https://my.zakupki.dz-test.net/cabinet/purchases/state_privatization_asset/all
promop@yopmail.com

Відтворення:
1. Зайти Органом приватизації.
2. Перейти до Реєстру Об'єктів/ Інформаційних повідомлень.

Очікувано: Реєстр містить список всіх Об'єктів/ Інформаційних повідомлень в ЦБД.

Фактично: Реєстр містить тільки список Об'єктів/ Інформаційних повідомлень внесених власноруч.
![image](https://user-images.githubusercontent.com/11888281/41774971-8f8396da-762a-11e8-8795-97d842187c59.png)

**Comment by niksdorf** [comment]
готово

**Comment by olyamalysh** [comment]
перевірено. Виправлено https://gyazo.com/753ce6e9f23d364a4a82c7fe5a8b698d
