### ISSUE TITLE
Об'єкт приватизації має обмеження назви 256 символів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#1733]
https://my.zakupki.dz-test.net/cabinet/purchases/state_privatization_asset/add
promop@yopmail.com

Відтворення.
1. Залогуватись Об\єктом Приватизації.
2. Перейти До створення Об'єкту.
3. Спробувати ввести великий текст в назву об\єкта приватизації.

Очікувано: В поле можна ввести приблизно 4 тисячі символів в розрахунку: 400 *10 (можливе перерахування кількох сотень об'єктів з деталізацією. )

Фактично в поле назва можна ввести 255 символів.
![image](https://user-images.githubusercontent.com/11888281/41775412-79cdb7a6-762c-11e8-91c4-1789fdfe6f88.png)

**Comment by niksdorf** [comment]
готово
фикс уже на https://zakupki.dz-test.net/

**Comment by olyamalysh** [comment]
https://gyazo.com/98156b50c836fe45bd5dc6d01f884797

перевірено. не відтворюється
