### ISSUE TITLE
Помилка при редагуванні asset - HTTP Client Exception

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1734]
Тестове середовище: http://test.biddingtime.com.ua
Логін: sprozorro@gmail.com

Відтворення:
Обрати новостворений "Об'єкти МП"
Натиснути на клавішу 'Редагувати'-> внести бажані зміни-> Натиснути "Зберегти".

Очікуваний результат: Відповідні зміни збережено.

Фактичний результат: отримано помилку при збереженні "HTTP Client Exception – yii\httpclient\Exception" 
![error on editing](https://user-images.githubusercontent.com/13050207/42384474-be34924a-8142-11e8-8624-ab327d53e66d.PNG)
"Unable to detect format for content parsing. Raw response:

Http-Code: 404
Content-Type: text/plain; charset=UTF-8
Date: Fri, 06 Jul 2018 14:32:55 GMT
Server: nginx/1.10.2
X-Content-Type-Options: nosniff
X-Request-Id: req-26a023bb-28bc-4d97-bafd-a78a2fa724f6
Content-Length: 68
Connection: Close

404 Not Found

The resource could not be found.

/api/2.3/assets/"

**Comment by neros3** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
перевірено, виправлено
