### ISSUE TITLE
Інформація про балансоутримувача не редагується у чорнетці

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1735]
Тестове середовище: http://test.biddingtime.com.ua
Логін: sprozorro@gmail.com

Відтворення:
1. Обрати новостворений "Об'єкти МП" у статусі Чернетка
2. Натиснути на клавішу 'Редагувати'-> внести бажані зміни до сектору "Інформація про балансоутримувача" 
3. Натиснути "Зберегти".

Очікуваний результат: Відповідні зміни збережено.
Фактичний результат: Зміни в секторі "Інформація про балансоутримувача" не збережено.

[![Screenshot from Gyazo](https://gyazo.com/518abf7e8307db62d2f3a44df5f0f21d/raw)](https://gyazo.com/518abf7e8307db62d2f3a44df5f0f21d)

**Comment by neros3** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
перевірено, виправлено,
