### ISSUE TITLE
Історія редагування документів об'єкту НЕ виводиться на майданчику

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1736]
Тестове середовище: http://test.biddingtime.com.ua
Логін: sprozorro@gmail.com

Відтворення:
1. Обрати власний "Об'єкти МП" зі статусом "Опубліковано. Очікування інформаційного повідомлення" (pending)
2. Натиснути на клавішу 'Замінити' документ-> внести бажані зміни та зберегти.

Очікуваний результат: Відповідні зміни збережено. відображено історію змін документів.

Фактичний результат: Редагування документів відбувається за стандартною схемою роботи з документами (історія редагування документів зберігається та виводиться на майданчику)
![default](https://user-images.githubusercontent.com/13050207/42386415-1ad80090-8148-11e8-9a2d-e69713dea219.png)

**Comment by neros3** [comment]
исправлено

**Comment by neros3** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
перевірено, виправлено
