### ISSUE TITLE
Неможливо встановити  'Крок аукціону' для №3 ('dutchSteps')

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1737]
Тестове середовище: http://test.biddingtime.com.ua
Логін: sprozorro@gmail.com

Відтворення:

1. Обрати власне "Інформаційне повідомлення" зі статусом "Публікація інформаційного повідомлення" (composing)
2. Внести інформацію про аукціони.

Очікуваний результат: для третього 'dutchSteps' (опціонально), дефолтна кількість кроків 99. користувач може змінити в межах 1-99 включно.

Фактичний результат: Аукціон за методом покрокового зниження стартової ціни та подальшого подання цінових пропозицій 'dutchSteps' не редагується.

![3](https://user-images.githubusercontent.com/13050207/42389121-5b44fd7e-8150-11e8-9d66-e55cdc135cd9.PNG)

**Comment by neros3** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
перевірено, виправлено
