### ISSUE TITLE
Найменування полів не відповідає вимогам МП.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1738]
Тестове середовище: http://test.biddingtime.com.ua
Логін: sprozorro@gmail.com

Відтворення:
Перевірити відповідність у найменуванні полів Обєкту МП/Інформаційного повідомлення МП

Очікуваний результат: Відповідають ТЗ по МП.
Фактичний результат: Не відповідають ТЗ по МП.

![default](https://user-images.githubusercontent.com/13050207/42389836-9f854550-8152-11e8-98ed-2bf789816551.PNG)
![2](https://user-images.githubusercontent.com/13050207/42389837-9fa116f4-8152-11e8-9bea-0a28820f4c48.PNG)
![default](https://user-images.githubusercontent.com/13050207/42389838-9fbfb604-8152-11e8-9d28-783088517053.PNG)
![default](https://user-images.githubusercontent.com/13050207/42389839-9fe054f4-8152-11e8-883b-371af30339af.png)
![decisions](https://user-images.githubusercontent.com/13050207/42389840-9ffd4b90-8152-11e8-978c-e249947a4c39.PNG)
![default](https://user-images.githubusercontent.com/13050207/42389841-a0192f18-8152-11e8-9148-13135cebd5d7.PNG)
![2](https://user-images.githubusercontent.com/13050207/42389842-a0364206-8152-11e8-9874-0fe559e4d087.PNG)
![default](https://user-images.githubusercontent.com/13050207/42389843-a0559ade-8152-11e8-9148-699d648ebba5.PNG)
![default](https://user-images.githubusercontent.com/13050207/42389844-a07dfb1e-8152-11e8-8e9c-b9d9eabff9b1.PNG)

**Comment by neros3** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
перевірено, виправлено
