### ISSUE TITLE
Помилка при спробі публікації чорнетки об'єкту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1739]
Тестове середовище: http://test.e-trading.kiev.ua/prozorrosale2/
Логін: sprozorro@gmail.com

Відтворення:
   1. Обрати новостворений об'єкт у статусі Чернетка
   2. Натиснути на клавішу 'Редагувати об'єкт МП'
   3. Натиснути на клавішу 'Опублікувати об'єкт у реєстрі'

Очікуваний результат: Статус об'єкта змінюється на - 'Опубліковано. Очікування інформаційного повідомлення'
Фактичний результат: Статус об'єкта змінюється на - 'Опубліковано. Очікування інформаційного повідомлення', на екрані видається помилка про збереження - 
Not Implemented (501)
"Помилка збереження активу {"status_code":500,"header":"HTTP\/1.1 500 Internal Server Error\r\nContent-Type: text\/plain\r\nDate: Sun, 08 Jul 2018 10:15:01 GMT\r\nServer: nginx\/1.10.2\r\nContent-Length: 21\r\nConnection: keep-alive\r\n\r\n","url":"https:\/\/lb.api-sandbox.ea2.openprocurement.net\/api\/2.3\/assets\/fb04fd2b06c84b83a0f6519e1320350c\/items\/0ede0711436d41ee953411d2d4c6f9b0?acc_token=9aa3acdddbe144d398fd449f562e7041"}"

**Comment by SoftserveQC1** [comment]
![2018-07-08_1250](https://user-images.githubusercontent.com/13050207/42418900-f28372a2-82b2-11e8-9397-79b8dbe3c7ff.png)

**Comment by greeschenko** [comment]
Нажаль не вдається відтворити цю помилку
деякий час назад ми дійсно іноді її отримували але зараз ні 
загалом за 2 останні дні було здійснено дуже велику кількість публікацій об'єктів МП  і жодного помилка не була помічена

якщо у Вас вийде відтворити помилку пришліть будьласка скріншоти заповнених даних у формі

**Comment by SoftserveQC1** [comment]
перевірено, виправлено
