### ISSUE TITLE
Відсутній механізм оновлення існуючих документів та перегляду їх змін

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1740]
Тестове середовище: http://test.e-trading.kiev.ua/prozorrosale2/
Логін: sprozorro@gmail.com

Відтворення:

  1. Обрати об'єкт у статусі "Опубліковано. Очікування інформаційного повідомлення".
  2. Натиснути на клавішу 'Редагувати об'єкт МП'
  3. Замінити існуючий документ на новий, та переглянути історію змін, натиснути на клавішу 'Зберегти об'єкт у реєстрі'

Очікуваний результат: Документи зберігаються, є можливість переглянути історію змін
Фактичний результат: Відсутній механізм оновлення існуючих документів та перегляду їх змін

**Comment by greeschenko** [comment]
додано фікс

**Comment by SoftserveQC1** [comment]
перевірено, виправлено
