### ISSUE TITLE
Відсутня імплементація виключення об'єкту з переліку

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#1741]
Тестове середовище: http://test.e-trading.kiev.ua/prozorrosale2/
Логін: sprozorro@gmail.com

Відтворення:

   1. Обрати об'єкт у статусі "Опубліковано. Очікування інформаційного повідомлення".
   2. Виключити об'єкт з переліку шляхом натискання відповідної кнопки з обов'язковою перевіркою на наявність завантаженого необхідного документу (documentType: cancellationDetails)
   3. Перевірити статус об'єкту після завершення операції 

Очікуваний результат: Обєкт змінює статус на - 'Виключено з переліку' 
Фактичний результат: Відсутня імплементація виключення об'єкту з переліку

**Comment by greeschenko** [comment]
Користувачу доступна кнопка видалення об'єкту з переліку тільки після виконання всіх умов доступності видалення а саме наявності документу з відповідним типом та відсутність прив'язаного до об'єкта інформаційного повідомлення
![20180709-211953_1366x768](https://user-images.githubusercontent.com/2754533/42475988-173d5c3e-83d5-11e8-811d-53d273377184.png)
![20180709-212009_1366x768](https://user-images.githubusercontent.com/2754533/42475993-1b61b832-83d5-11e8-9e27-a60019e4ad1f.png)

**Comment by SoftserveQC1** [comment]
перевірено, виправлено
