### ISSUE TITLE
ЕЛЕГ, лист активації на сайті

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#176]
![untitled](https://cloud.githubusercontent.com/assets/11783631/6982302/a1c37c18-da18-11e4-9ca1-0f62873d22f1.png)
1. Чи повинен лист активації звертатись до користувача по логіну чи по імені ?
2. Прошу підтвердити, що текст в листі є коректний.
3. Чи повинна бути присутня 5 стрічка щодо створення персонального сайту в цьому листі ?
4. Чи повинен бути відсутній номер телефону служби підтримки
5. Чи повинен лист активації приходити з etendermail@yandex.ru

**Comment by S-Shevchenko** [comment]
Задача не актуальна. 
Добрий день, Шпигель Генрих Петрович!
Ми раді Вас вітати на ресурсі E-tender.

На нашому порталі Ви можете:
- Розмісти інформацію про Вашу компанію.
- Створити персональний сайт та отримати можливість просування компанії в пошукових мережах.
- Організовувати процес закупівлі товарів та послуг та приймати участь у них.
  Для подальшої роботи з ресурсом E-tender пропонуємо Вам зайти в особистий кабінет.
  У разі виникнення питань завжди готові Вам допомогти.

Служба підтримки
Телефон: (094) 822 92 45
Email: support@e-tender.biz
