### ISSUE TITLE
ЕЛЕГ, Відновлення паролю. Користувач може змінити пароль залишивши поле "Підтвердіть пароль" порожнім.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#177]
http://uat.e-tender.biz/#/sendEmail
1. Надішліть запит на відновлення паролю на пошту, перейдіть по посиланню
2. Введіть в поле "Пароль:" Password1
3. Поле "Підтвердіть пароль" залиште пустим
4. Натисніть кнопку "Змінити пароль"

Пароль змінено успішно

**Comment by S-Shevchenko** [comment]
Спасибо, в работе.
