### ISSUE TITLE
Не видно маркера новых вопросов/ответов в списке закупок

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#18]
Видно только в карточке. Но это означает, что закупкщикам нужно несколько раз в день мониторить все свои торги. Мне кажется, есть смысл добавить новый признак еще и в списке:

![image](https://cloud.githubusercontent.com/assets/9398532/5873769/9341fd24-a302-11e4-8a45-854958075ec1.png)

**Comment by darchik** [comment]
Все верно, для этого на списке есть значек с сообщением. Он будет в понедельник-вторник.
