### ISSUE TITLE
ЕЛЕГ, Якщо пароль складається з пробілів, то система пропускає його і є можливість створити юзера з таким паролем

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#181]
1. Перейдіть по цьому посиланню http://uat.e-tender.biz/#/register
2. Введіть валідні дані, в поле Пароль: введіть "        " - 8 пробілів
3. В поле Підтвердіть пароль: "        " - 8 пробілів
4. Натисніть кнопку Реєстрація
   Результат:
5. Ми отримуєм зареєстрованого користувача який неможе залогінитись в систему

**Comment by S-Shevchenko** [comment]
Спасибо. взяли в работу....

**Comment by lerich** [comment]
Виправлено
