### ISSUE TITLE
ЕЛЕГ, при реєстрації немає перевірок для паролю, таких як при відновленні паролю

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#182]
1. Перейдіть по цьому посиланню http://uat.e-tender.biz/#/register
2. У поле пароль введіть: "password"
3. У поле Підтвердіть пароль введіть також "password"

Результат:
У кроці-2 повинна відбуватись перевірка:
1. На кількість символів (вона відбувається)
2. Присутність верхнього та нижнього реєстру
3. Присутність одного нелітерального знаку,
 Так, як це відбувається при відновленні паролю:
"Має бути хоча б одна літера верхнього та нижнього регістра та один нелітеральний знак (цифра або символ). Довжина паролю має бути 8-20 символів."

**Comment by hkhim** [comment]
Додана валідація при реєстрації
