### ISSUE TITLE
ЕЛЕГ, Відновлення паролю. Пароль більше 20 символів невалідується коректно

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#185]
1. Надішліть запит на відновлення паролю на пошту, перейдіть по посиланню
   Введіть в поле "Пароль:" "Strictly21symbol11111" - пароль містить 21 символ
   2.1. Під полем червоне повідомлення: "Довжина паролю має бути 8-20 символів."
2. В поле "Підтвердіть пароль" введіть: "Strictly21symbol11111" 
   3.1. Під полем червоне повідомлення: "Паролі не збігаються."
3. Натисніть кнопку "Змінити пароль".

Результат:
1. Пароль змінено успішно, незважаючи на повідомлення про довжину паролю. (Крок-4)
2. Повідомлення про те що паролі не збігаються, хоча вони збігаються. (Крок-3.1)
3. Залогінитись за цього користувача неможливо оскільки, кнопка Логін незявляється, якщо пароль довший, ніж 20 символів.

**Comment by S-Shevchenko** [comment]
Спасибо. взята в работу.

**Comment by hkhim** [comment]
Якщо пароль більше 20 символів, то немає кнопки "Змінити пароль"
![2015-07-03 15_41_47-](https://cloud.githubusercontent.com/assets/12292248/8499300/2f2606ac-219a-11e5-9238-b084c802041f.png)
