### ISSUE TITLE
ЕЛЕГ, Реєстрація. При неунікальному логіні, зявляється помилка з текстом:  "Користувач з таким ім'ям вже існує"

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#186]
1. В мене зареєстрований користувач з логіном misha
2. Я намагаюсь зареєструвати ще одного користувача, з таким самим логіном

2.1. З'являється повідомлення з текстом, що "Користувач з таким ім'ям вже існує"
А має з'являтись "Користувач з таким логіном вже існує"

**Comment by S-Shevchenko** [comment]
Спасибо, взяли в работу

**Comment by hkhim** [comment]
![2015-07-03 15_49_04-](https://cloud.githubusercontent.com/assets/12292248/8499397/11b0b10c-219b-11e5-9370-cc06c8b74df6.png)
