### ISSUE TITLE
ЕЛЕГ, лист відновлення паролю

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#189]
![untitled](https://cloud.githubusercontent.com/assets/11783631/7006576/f98af736-dc8a-11e4-9fd4-0eb381ac2be2.png)
1. Чи повинен лист до мене звертатись, по повній назві компанії, чи по мому імені?
2. Прошу підтвердити, що текст в листі є коректний

**Comment by SergeDmitriev** [comment]
Виправили проблему, тепер в листі ми звертаємося до користувачів по ПІБ
