### ISSUE TITLE
ПРОМ: Не прошли вопросы 

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#19]
Торги 1-СМАР-АК-02
От ПРОМ не прошел вопрос ПРОМ-АК-04 
на ПРОМ не прошли вопросы/ответы ЕЛЕГ-СВ-03 и СМАР-АК-05
Проблема явно на стороне ПРОМ, т.к. ЕЛЕГ и СМАР корректно обменялись вопросами и ответами

**Comment by darchik** [comment]
Это исправили.
