### ISSUE TITLE
ЕЛЕГ, Редагування профілю. Після первинної модерації поля профілю розширюються на всю ширину таблиці

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#191]
![image](https://cloud.githubusercontent.com/assets/11783631/7041242/5e9f8ac8-dde0-11e4-9fb6-0af0f6524267.png)

**Comment by S-Shevchenko** [comment]
Спасибо, в работе. Воспроизводиться и  во время создания профиля.

**Comment by S-Shevchenko** [comment]
Исправлено
