### ISSUE TITLE
ЕЛЕГ, Закупівля. Відсутня можливість прикріпити файл при створені закупівлі (тендера).

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#200]
1. Залогіньтесь на сайт http://uat.e-tender.biz/ за користувача, який має змогу створювати закупівлі.
2. Перейдіть на сторінку створення закупівлі.
   ![image](https://cloud.githubusercontent.com/assets/11783631/7087487/a2988526-df94-11e4-91bd-34e71bee4250.png)
3. Незрозуміло, як прикріпити документ до закупівлі, хоча в "Регламент роботи електронного майданчика" сказано, що комплект електронних документів, що містить всю необхідну і достатню інформацію про предмет закупівлі - невід'ємний додаток до оголошення про закупівлі.

**Comment by SergeDmitriev** [comment]
В нас реалізовано таким чином, що документи до закупівлі додаються після створення тендеру.
