### ISSUE TITLE
ЕЛЕГ, Закупівлі зависають в статусі "Зачекайте, закупівля обробляється", якщо користувач був непідтвердженим модератором з першого разу.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#201]
1. Створіть користувача, активуйте акаунт
2. Подайте першу заявку на модерацію
3. Відмініть заявку оператором
4. Подайте ще раз заявку модератору
5. Підтвердіть користувача модератором
6. Створіть тендер в тестовому режимі (він зависне у стані "Зачекайте, закупівля обробляється")
7. Подайте заявку на модерацію, ще раз
8. Створіть тендер в режимі реальних закупівель (він також зависне у стані "Зачекайте, закупівля обробляється")
   ![image](https://cloud.githubusercontent.com/assets/11783631/7088669/7b11f438-df9e-11e4-9754-f224ea24eb2f.png)
   ![image](https://cloud.githubusercontent.com/assets/11783631/7088769/249669bc-df9f-11e4-973c-abcf6649b279.png)
   Тендер UA-2015-04-09-000058 - тайтл нормально тендера, а на скріншоті він суттєво відрізняється

**Comment by S-Shevchenko** [comment]
Не воспроизводится.
