### ISSUE TITLE
Public-bid, Реєстрація. Лист, що містить ключ-доступу, також містить pdf файл, вміст якого нечитабельний.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#203]
![image](https://cloud.githubusercontent.com/assets/11783631/7133814/9a7fc45e-e29f-11e4-8a43-9a0515b55e7a.png)

![image](https://cloud.githubusercontent.com/assets/11783631/7133795/71f52c04-e29f-11e4-88f7-72a9c55303e3.png)

**Comment by DanilMarchyshyn** [comment]
Виправлено

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, тепер текст читабельний. Закриваю.
