### ISSUE TITLE
Public-bid, Реєстрація. Після проходження реєстрації, з ключем-доступу, користувач переадресований на сторінку з неповним контентом.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#204]
![image](https://cloud.githubusercontent.com/assets/11783631/7133901/8dbb77bc-e2a0-11e4-92d2-9a7118d5af92.png)
Після натискання кнопки "Так", залишається вікно без контенту сайту
![image](https://cloud.githubusercontent.com/assets/11783631/7133833/cfc42880-e29f-11e4-9102-7594cfbf4ef9.png)

**Comment by DanilMarchyshyn** [comment]
Виправлено

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
