### ISSUE TITLE
Public-bid, Головна сторінка у ІЕ(11) відображається некоректно

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#205]
![image](https://cloud.githubusercontent.com/assets/11783631/7134430/722b8c44-e2a5-11e4-9299-ee1a34b84284.png)

**Comment by maksimmaksimov** [comment]
Ошибка исправлена

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
