### ISSUE TITLE
Public-bid, Створення закупівлі. При створення закупівлі відсутня перевірка на коректність вказаних дат.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#208]
Знизу вказано, що:
1. Дата завершення періоду уточнень вказана ранішою, ніж дата створення закупівлі.
2. Дата завершення прийому пропозицій, вказана через годину після завершення прийому пропозицій, та все ж давніша від теперішньої дати.
![image](https://cloud.githubusercontent.com/assets/11783631/7136329/877e6748-e2b8-11e4-887b-b508a449ab1b.png)

**Comment by DanilMarchyshyn** [comment]
Виправлено

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
