### ISSUE TITLE
Public-bid, Питання стосовно безпеки

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#209]
http://public-bid.com.ua/
Обмін даними відбувається по протоколу http, тобто і логін і пароль передаються в нешифрованому вигляді, чи планується імплементація безпеки і якщо так, то як саме ?
![image](https://cloud.githubusercontent.com/assets/11783631/7136906/da03c382-e2bd-11e4-9469-66201e553172.png)

**Comment by maksimmaksimov** [comment]
Перешли на https

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, тепер зловивши купу пакетів прочитати їх не вдається. Закриваю.
