### ISSUE TITLE
Неправильное название даты в списке

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#21]
Должно быть: дата завершения подачи предложений
А сейчас: дата аукциона

![image](https://cloud.githubusercontent.com/assets/9398532/5874259/1688c6b8-a308-11e4-83ff-de8acbc65bfd.png)

**Comment by darchik** [comment]
Исправим

**Comment by darchik** [comment]
Исправлено. 

http://grab.by/E8si
