### ISSUE TITLE
Public-bid. Встановленя Паролю при реєстрації, Зміна Паролю. Валідація не є коректною.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#211]
З Інструкції користувача замовника:
"6. В формі «Зміна паролю» ввести та підтвердити новий пароль (Рис. 9).
Примітка. Пароль повинен містити літери верхнього та нижнього регістра та принаймні один, нелітеральний знак (цифра або символ). Довжина паролю має бути 8-20 символів"

адресса: http://public-bid.com.ua
Кроки відтворення:
1. Залогінитись в Мій Кабінет
2. Перейти до зміни паролю
3. Спробувати ввести різні види паролів. наприклад "11111111", "!!!!!!!!", "Йцукенг1". 
4. Спробувати ввести пароль з 20 символів

Очікувана поведінка:
а. Поле сприймає 20 символів
б. Реалізована валідація на пароль в системі: "Довжина паролю має бути 8-20 символів і містити  нелітеральні знаки та латинські літери" 

Реалізована поведінка:
а. Поле сприймає 15 символів
б. "Довжина паролю має бути 8-20 символів та містити нелітеральний знак"

![image](https://cloud.githubusercontent.com/assets/11888281/7134022/82026e66-e2a1-11e4-8b4b-78c27696392b.png)

**Comment by DanilMarchyshyn** [comment]
Виправлено
