### ISSUE TITLE
Public-bid, Чи коректна поведінка збереження сесії в межах браузера?

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#213]
1. Залогінитись за користувача в одному браузері
2. Закрити вкладу залогіненим користувачем
3. Відкрити нову вкладку та перейти за посиланням http://public-bid.com.ua/ (відображено знизу)
   ![image](https://cloud.githubusercontent.com/assets/11783631/7137956/dc6cc134-e2c5-11e4-9de5-5ac701114d8a.png)
4. Натиснути кнопку Реєстрація/ Вхід (відображено знизу)
   ![image](https://cloud.githubusercontent.com/assets/11783631/7137928/c161de88-e2c5-11e4-9d6e-4fb71657237c.png)

Результат:
3. В кроці-3 сторінка виглядає, так наче ніхто незалогінений в систему
4. Користувач перенаправлений в кабінет залогіненого користувача з кроку-1.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Також відтворюється при наступному сценарії:
1. Залогуйтесь в систему
2. Натисніть в браузері кнопку back (поверніться на одну сторінку назад)
3. Перейдіть на вкладку Закупівлі, та виберіть Моїй закупівлі
![image](https://cloud.githubusercontent.com/assets/11783631/7138672/767716a4-e2ca-11e4-8b47-28643d8a69d8.png)

**Comment by RudDaryna** [comment]
Це корректна поведінка системи.  Фільтр "Мої закупівлі" буде прибрано з публічної сторінки.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@RudDaryna другий випадок відтворення винесений окремим запитанням.
https://github.com/openprocurement/frontend/issues/221

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@RudDaryna Перше запитання все, ще потребує уточнень:
Якщо вкладка з сесією користувача була просто закрита в браузері, після цього була відкрита нова вкладка, то чи повинен користувач бути залогованим чи ні ?

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Если вкладка была закрыта, а потом снова открыта - пользователь остается залогиненым и его сессия хранится 30 минут. Т.е. данное поведение считается корректным.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov дякую за відповідь. Поведінка залишається некоректною при наступному сценарії:
1. Залогуйтесь в систему https://public-bid.com.ua/
2. Відкрийте в цьому ж браузері ще одну вкладку та перейдіть за посиланням https://public-bid.com.ua/
Очікуваний результат:
2. В правому верхньому куті користувач буде бачити свої дані, та контрол на вихід з системи
Фактичний результат:
2. Користувач бачить контрол Реєстрація/Вхід

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe  не совсем так. В системе реализованы 2 страницы:
1) public-bid.com.ua
2) public-bid.com.ua/user (личный кабинет)
Первая доступна всем пользователям, вторая доступна только зарегистрированным пользователям. И если вы перейдете не по ссылке public-bid.com.ua, а по ссылке public-bid.com.ua/user - вы попадете в личный кабинет.
Т.е. данное поведение не является некорректным.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov ці дві сторінки пересікаються, між собою і можуть заплутати користувача з наступним сценарієм:
1. Залогуйтесь в систему https://public-bid.com.ua за користувача з:
логіном: misha.a@meta.ua
паролем: Password1
2. Відкрийте ще одну вкладку в межах браузера та введіть https://public-bid.com.ua
3. На новій відкритій вкладці, Натисніть контрол Закупівлі
4. Натисніть кнопку Нова закупівля
5. Оберіть будь-яку організацію від якої бажаєте оголосити закупівлю
6. Натисніть кнопку Обрати

Очікуваний результат:
6. Користувачу повинне відкритись вікно з формою створення закупівлі
Фактичний результат:
6. Він залишається на виборі організації і неможе рухатись далі

**Comment by maksimmaksimov** [comment]
Пользователь пытается не из личного кабинета создать закупку. То что кнопка "Нова закупівля" доступна на странице public-bid.com.ua - является некорректным. Уберем.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov також хочу звернути увагу, що там присутній фільтр Мої закупівлі, також варто забрати.
![image](https://cloud.githubusercontent.com/assets/11783631/7319605/5a9bf6d4-ea9f-11e4-9e14-15bcc44c8ee2.png)

**Comment by maksimmaksimov** [comment]
Принято

**Comment by maksimmaksimov** [comment]
Ошибка исправлена
