### ISSUE TITLE
Public-bid. Встановлення Паролю. Чекбокс Ознака підтверженя.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#215]
Що означає чекбокс Ознака підтверження і чи потрібен він на формі?
В системі передбачено 3 стани для чекбоксів: 
"не зазначено користувачем/системою",
"відчеканий"
"зачеканий"
Чекбокс в стані - "не зазначено користувачем/системою" і його не можна редагувати. 

![untitled](https://cloud.githubusercontent.com/assets/11888281/7138792/1e18c3c6-e2cb-11e4-9234-a1156d78ec72.png)

**Comment by maksimmaksimov** [comment]
@w-be чекбокс Ознака підтверження заменили на поле "Статус"

**Comment by w-be** [comment]
Перевірив, працює.
