### ISSUE TITLE
Public-bid, 1024x768 Сторінка авторизації. Розмір полів "Вкажіть e-mail" та "Пароль" неоднакової довжини. Тільки у ІЕ та Firefox

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#217]
![image](https://cloud.githubusercontent.com/assets/11783631/7139771/b94377b0-e2d0-11e4-9d48-5da66e1f29f7.png)
![image](https://cloud.githubusercontent.com/assets/11783631/7139821/f5a49112-e2d0-11e4-9c1d-116de2c9089a.png)

**Comment by DanilMarchyshyn** [comment]
Виправлено
