### ISSUE TITLE
Public-bid, 1024x768 Сторінка залогованого користувача обрізана.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#218]
![image](https://cloud.githubusercontent.com/assets/11783631/7153631/b95bb66e-e356-11e4-83ea-cd55ecab0604.png)
![image](https://cloud.githubusercontent.com/assets/11783631/7153643/debde26a-e356-11e4-84ce-60c3c09fcb5b.png)
![image](https://cloud.githubusercontent.com/assets/11783631/7153669/19aba308-e357-11e4-85b2-6a3b96936933.png)
Chrome Version 41.0.2272.118 m

**Comment by DanilMarchyshyn** [comment]
Виправлено

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
