### ISSUE TITLE
Торги перешли в статус Аукцион, а ссылка не присвоилась

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#22]
Ни публичная (пусто) и персональная (некликабельный текст "Аукцион проходит по ссылке)

![image](https://cloud.githubusercontent.com/assets/9398532/5874313/d1a13e30-a308-11e4-833e-b17467f99079.png)

**Comment by darchik** [comment]
Бывало такое, но ссылки потом появлялись. Мы протестируем еще этот кейс.
