### ISSUE TITLE
Public-bid, 1024x768 Сторінка створення закупівлі, зайві скрол-бари

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#220]
1. Відкрийте ІЕ 11, та залогуйтесь за користувача з правом створювати закупівлі.
2. Перейдіть на сторінку створення закупівлі
   ![image](https://cloud.githubusercontent.com/assets/11783631/7154066/c566988a-e35a-11e4-9804-7ec5dcf28527.png)
3. Виконайте крок 1 та 2 тільки у браузері Firefox 37.0.1
   ![image](https://cloud.githubusercontent.com/assets/11783631/7154080/f321ab2a-e35a-11e4-8117-2a8a41f5c1ab.png)

**Comment by DanilMarchyshyn** [comment]
Виправлено

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
