### ISSUE TITLE
Public-bid, Чи повинен користувач бути вилогуваним, при натисканні кнопки (back) в браузері ?

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#221]
1. Відкрийте будь-який браузер та перейдіть по посиланню http://public-bid.com.ua/
2. Залогуйтесь в систему та натисніть кнопку, як показано на скріншоті 
   ![image](https://cloud.githubusercontent.com/assets/11783631/7156874/fb5703e0-e372-11e4-8e5b-5119fb0638c6.png)

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@RudDaryna прошу дати відповідь на питання.

**Comment by RudDaryna** [comment]
Ні, вилогуваним користувач має бути тільки у випадку натискання кнопки "Вихід"

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@RudDaryna дякую, за розяснення. Закриваю.
