### ISSUE TITLE
Public-bid, Помилка запису до ЦБД, при спробі оголосити або додати як тестову закупівлю

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#223]
1. Залогуйтесь за користувача з правами створювати закупівлі
2. Заповніть форму закупівлі валідними даними
3. Натисніть Додати як тестову (Зявляється помилка: "Помилка запису до ЦБД" як зображено на скріншоті)
4. Натисніть Оголосити (Зявляється помилка: "Помилка запису до ЦБД" як зображено на скріншоті)
   ![image](https://cloud.githubusercontent.com/assets/11783631/7177392/01b34d4a-e42f-11e4-91f5-7c8d8e338040.png)

**Comment by DanilMarchyshyn** [comment]
Виправлено

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, більше не відтворюється. Закриваю.
