### ISSUE TITLE
ЕЛЕГ, Створення закупівлі. Два повідомлення про помилку без пояснень причин помилки.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#224]
1. Залогуйтесь за користувача з правом створювати закупівлі.
2. Перейдіть на вкладку створення закупівлі, створіть закупівлю
3. Зайдіть в цю закупівлю, та добавте файлу спочатку коректного розширення *.pdf, а потім файл з розширенням *.png (недозволеного формату файлу)
   ![image](https://cloud.githubusercontent.com/assets/11783631/7178788/2e6bdd2e-e43a-11e4-98bc-2f03014e6c4e.png)
   Результат, людині не повідомляє про причину помилки завантаження файла.

**Comment by S-Shevchenko** [comment]
Спасибо. Задача в работе
