### ISSUE TITLE
Public-bid, Головна сторінка. Непрацює сортування колонок, для не авторизованого користувача.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#225]
1. Перейдіть за посиланням http://public-bid.com.ua
2. Натисніть на будь-який заголовок стовпця для сортування даних.
   ![image](https://cloud.githubusercontent.com/assets/11783631/7180093/df4674e0-e446-11e4-9278-96196209719d.png)
   Результат:
   Сортування не відбувається.

**Comment by maksimmaksimov** [comment]
Исправлена

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
