### ISSUE TITLE
Public-bid, Лист запрошення містить некоректне посилання.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#226]
1. Надішліть собі запрошення на тестову електронну пошту
2. Перейдіть за посиланням запрошення
   ![image](https://cloud.githubusercontent.com/assets/11783631/7180542/22ba49be-e44b-11e4-80c8-39e3d0ee1b67.png)
   ![image](https://cloud.githubusercontent.com/assets/11783631/7180571/81211d48-e44b-11e4-9d2d-77be17ccfc2f.png)

На цьому скріншоті зображено результат переходу за посиланням, яке містилось в листі

**Comment by RudDaryna** [comment]
Прохання повторити сценарій, на даний момент нам його відтворити не вдалось

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@RudDaryna 
Лист запрошення містить дві лінки:
Слово "реєстрації" містить - http://public-bid.com.ua/?action=registration&invited=1 - коректну лінку
Слово "посиланням" містить - http://public-bid.com.ua/?action=# - некоректну лінку, результат якої показано на скріншоті зверху.
![image](https://cloud.githubusercontent.com/assets/11783631/7200679/f3b2e096-e507-11e4-8bb2-81f1053a8e33.png)

**Comment by maksimmaksimov** [comment]
Данная ошибка воспроизводится на почтовике **Meta.ua**. Например на **i.ua** ссылка приходит корректная - см. скриншот.
![000282](https://cloud.githubusercontent.com/assets/8382283/7227497/d109d834-e759-11e4-85f9-cc4ca61aac45.jpg)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe ошибка исправлена. Просьба проверить

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov перевірено, тепер посилання http://public-bid.com.ua/?action=info веде на сторінку з контентом "Розділ в розробці". Закриваю.
