### ISSUE TITLE
Public-bid, Сторінка реєстрації непрацює відтворюється тільки у ІЕ (11)

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#227]
1. Відкрийте Інтернет експлорер 11 версії, як зображено на скріншоті
2. Натисність кнопки Відновити пароль, Я новий користувач, Я маю запрошення, Вхід
   ![image](https://cloud.githubusercontent.com/assets/11783631/7180658/86999ae2-e44c-11e4-98db-32f8448313c8.png)
   Результат:
   Жодна кнопка не виконує жодних дій

**Comment by DanilMarchyshyn** [comment]
Виправлено

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@DanilMarchyshyn досі відтворюється версія ІЕ 11.0.9600.17691
![image](https://cloud.githubusercontent.com/assets/11783631/7205091/650f0072-e52f-11e4-8c61-ed0631ab9631.png)
Маю два однакових ІЕ однакової версії, на одному відтворюється на другому не відтворюється...
Буду досліджувати

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@DanilMarchyshyn було досліджено, що на особливому ІЕ 11.0.9600.17691, при дебагінгу вилазить наступна помилка
![image](https://cloud.githubusercontent.com/assets/11783631/7255849/95c7319e-e854-11e4-862b-f2fee2284db3.png)
Перевірте будь-ласка на совму тестовому ІЕ такої ж версії, можливо у вас також знайдеться такий самий браузер з такою ж помилкою.

**Comment by maksimmaksimov** [comment]
Спасибо, в работу взяли.

**Comment by maksimmaksimov** [comment]
Не получается повторить ошибку

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Проблема досі відтворюється і я не можу з'ясувати різницю між двома браузерами однакової версії. Прошу добавити мене в скайпі Mykhailo Shtabaliuk для подальшого зв'язку (можливо ремоут сесії)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe дело в том, что повторить ошибку пытался не я, а разработчик, и он мне сообщил, что не может воспроизвести

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov якщо є можливість, то хотілось би звязатись з ним, можливо він зясує в чому проблема.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Попробую посодействовать

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Пофіксано, перевірено. Дякую за плідну роботу, Закриваю.
