### ISSUE TITLE
Не прошло через ЦБД предложение, поданное на своей же площадке

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#23]
Статус не изменился: (по состоянию на 14:10 то же самое)

![image](https://cloud.githubusercontent.com/assets/9398532/5874333/f819c15e-a308-11e4-9d2c-bd7a4f2fb80d.png)

Предложение я подавал и через ПРОМ (см ниже) и через СМАР:

![image](https://cloud.githubusercontent.com/assets/9398532/5874391/7bdc4188-a309-11e4-8355-3f46d3255eb2.png)

На СМАР предложение от ПРОМ не попало:
![image](https://cloud.githubusercontent.com/assets/9398532/5874398/a21b5546-a309-11e4-9387-0f6835a4c084.png)

Вчера была аналогичная проблема на стороне ПРОМ. Похоже, она не ушла, так что пока вешаю ошибку на ПРОМ, а там разберемся

**Comment by andriykucherenko** [comment]
UPD: в 14:13 этот аукцион получил "правильный" статус - Квалификация. 
Проблема в том, что на тендеры, объявленные через ПРОМ, вы запрещаете подавать предложение точно в момент, определенный в объявлении торгов. А по тендерам, пришедшим с других площадок, есть задержка по времени- см второй снизу скриншот, я подал уточнение в 14:02

**Comment by andriykucherenko** [comment]
UPD2: уточнение, которое я подавал в 14:02 и система "съела" без ошибок, сейчас пропало:
![image](https://cloud.githubusercontent.com/assets/9398532/5874487/dbf9d64c-a30a-11e4-8da9-ce7e5303358c.png)

@darchik, обрати внимание

**Comment by AlexRudenko** [comment]
Была проблема с неверным форматом электронного адреса. Исправили.

**Comment by AlexRudenko** [comment]
Вопрос решен
