### ISSUE TITLE
Public-bid. Закупівля, Оскарженя.Відсутня нотифікація при оскаржені.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#231]
http://public-bid.com.ua/

При Обговорені система надсилає листи учасникам обговорення, що є нове питання/відповідь.

Чи планується така ж поведінка для нового оскарження/при рішені по оскарженю?

**Comment by maksimmaksimov** [comment]
Данная ошибка известна и на данный момент проводятся работы по устранению.

**Comment by maksimmaksimov** [comment]
Ошибка исправлена. Уведомления при добавлении и рассмотрении жалоб ходят. Уведомление о рассмотрении жалобы будет доработано.

**Comment by maksimmaksimov** [comment]
Ошибка исправлена, все уведомления доработаны
