### ISSUE TITLE
Public-bid, Відсутня синхронізація між майднчиком та українським часом.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#232]
![image](https://cloud.githubusercontent.com/assets/11783631/7182321/429d5768-e459-11e4-9b6d-46a256f57769.png)

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Час останньої синхронізації відображається в іншому форматі, ніж час майданчика.

**Comment by DanilMarchyshyn** [comment]
Виправлено

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, формат та час тепер співпадають.
