### ISSUE TITLE
Public-bid. Закупівля, Оскарженя. Неможливо подивитись історію оскаржень.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#233]
Після завершення закупівлі неможливо подивитись, що оскаржувалось, і які відповіді отримано.
Це робить сестему не зовсім прозорою.
Хоча мабуть і персональні дані варто було б приховувати.

**Comment by RudDaryna** [comment]
Кнопка "Скарги" доступна після завершення закупівлі. Підкажіть, будь ласка, яка була проблема з переглядом скарг на прикладі.
Особисті дані приховаємо

**Comment by w-be** [comment]
користувач: vbilos@softserveinc.com / qwertyu1
Картка закупівлі № UA-2015-04-16-000049
Закупівля в статусі: "Закупівля не відбулась"

**Comment by RudDaryna** [comment]
@w-be, у вказаній закупівлі були точно додані скарги?  Кнопка "Скарги" активна, перехід на картку перегляду скарг є, просто скарг немає. 
![image](https://cloud.githubusercontent.com/assets/11630727/7275295/c6e7f2f6-e90b-11e4-8b2e-76366921cc56.png)

![image](https://cloud.githubusercontent.com/assets/11630727/7275273/96e1339c-e90b-11e4-88d4-bcce161c0257.png)

**Comment by maksimmaksimov** [comment]
Данное замечание не является ошибкой, к закупке UA-2015-04-16-000049 не было добавлено жалоб, соответственно и истории жалоб нет.

**Comment by w-be** [comment]
Закриваю, як не баг.
