### ISSUE TITLE
Public-bid, Назви кнопок при відміні закупівлі неоднозначні.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#237]
![image](https://cloud.githubusercontent.com/assets/11783631/7202093/a677aaae-e517-11e4-9aae-21f7fa13f6da.png)
Використання слова Відміна/Відмінити в одному повідомленні з двома різними функціями плутає користувача.

Очікуваний результат:
Повідомлення з текстом: "Ви дійсно бажаєте відмінити закупівлю?"
кнопки: "Так", "Ні"

**Comment by maksimmaksimov** [comment]
Исправлено.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
