### ISSUE TITLE
Public-bid, Як часто відбувається синхронізація ? І з чим вона саме вона відбувається з іншими майданчиками чи з ЦБД ?

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#238]
![untitled](https://cloud.githubusercontent.com/assets/11783631/7204533/b49e2fb8-e52b-11e4-8b3f-2ef6b14bb9c2.png)

**Comment by maksimmaksimov** [comment]
Cинхронізація відбувається кожну хвилину з ЦБД

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov чому тоді виникає майже година різниці, між останньою синхронізацією та реальним часом ?

**Comment by maksimmaksimov** [comment]
Якщо з боку ЦБД не було змін, то дата не змінюється

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Дякую, тепер зрозуміло. Закриваю
