### ISSUE TITLE
Public-bid. Період уточнень закупівлі. Відповідаючи на запитання після того як файл було прикріплено до відповіді, відсутня можливість змінити прикріплений файл.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#241]
1. Створіть тендер (закупівлю), почекайте поки закупівля буде в періоді Уточнень
2. Задайте  запитання щодо закупівлі
3. Даючи відповідь на запитання, прикріпіть файл
4. Спробуйте змінити прикріплений файл до відповіді
   ![image](https://cloud.githubusercontent.com/assets/11783631/7232948/0f21ee0e-e787-11e4-9b84-0e9ebc71c75a.png)
   Результат:
   Якщо користувач прикріпив помилково не той файл, йому прийдеться відміняти відповідь і знвоу переходити до того ж запитання, що б випадковий файл не був прикріплений до відповіді.

**Comment by RudDaryna** [comment]
Зазначена можливість не передбачена системою, ми додамо вказаний функціонал.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe возможность удаления прикрепленного файла добавили.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov дякую, перевірено. Закриваю.
