### ISSUE TITLE
Public-bid, Період Уточнень. Відсутня перевірка на унікальність назви прикріпленого файлу.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#242]
![image](https://cloud.githubusercontent.com/assets/11783631/7233034/8825b272-e787-11e4-8312-e2dea250b0b4.png)

**Comment by RudDaryna** [comment]
Доброго дня, 
вказана перевірка у нас не передбачена системою. Якщо це критично, її можна додати.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@RudDaryna це б на мою думку створило зручність для користувача. На випадок якщо йому треба прикріпити з десяток файлів, і що б не заплутатись і помилково не прикріпити той самий файл двічі.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe  т.к. у нас в системе уже реализовано удаление прикрепленных файлов при ответе на вопросы, если пользователь вдруг добавит 2+ раза один и тот же файл - он сможет без проблем его удалить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov згоден, реалізація можливості видаляти прикріплений файл, вирішила проблему. Закриваю.
