### ISSUE TITLE
[ЕЛЕГ] При реєстрації учасника відображається помилка з текстом "An internal error occured during your request!"

### ISSUE THREAD

**Issue by MaryanaDemtsyukh-SoftServe** [openprocurement/frontend#243]
Кроки для відтворення:
1. Відкрити лінку http://uat.e-tender.biz/#/
2. Перейти до Реєстрації
3. Заповнити обов'язкові текстові поля валідними даними
4. Клікнути на кнопку Реєстрація
Актуальний результат: помилка з текстом "An internal error occured during your request!" відображається в правому нижньому кутію (див. скріншот).
Очікуваний результат: учасник  повинен бути успішно зареєстрований в систему, ніяких помилок не повинно відображатись.

![default](https://cloud.githubusercontent.com/assets/11995699/7233785/d98c180a-e78b-11e4-83a6-2f2c68a273c1.png)

При повторному натисканні кнопки Реєстрація відображається помилка з текстом "Користувач з таким ім'ям вже зареєстрований." (див. скріншот).

![-1](https://cloud.githubusercontent.com/assets/11995699/7233796/e9b4c5b0-e78b-11e4-8dfc-80c34aee440f.png)

**Comment by S-Shevchenko** [comment]
@MaryanaDemtsyukh-SoftServe Спасибо. Исправили. Проверьте пожалуйста.

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
Дефект виправлено.
