### ISSUE TITLE
[ЕЛЕГ] Помилка "Invalid user name or password" відображається при логуванні попередньо зареєстрованим Учасником

### ISSUE THREAD

**Issue by MaryanaDemtsyukh-SoftServe** [openprocurement/frontend#245]
Кроки для відтворення:
1. Відкрити гіперпосилання http://uat.e-tender.biz у будь-якому бравзері
2. Клікнути на лейбу Вхід
3. Заповнити необхідні текстові поля валідними даними (напр. логін: tester пароль: 012345678 або логін: victor_qc пароль: 12345678)
4. Клікнути на кнопку Логін

Актуальний результат: помилка "Invalid user name or password" відображається при логуванні попередньо зареєстрованого Учасника.
Очікуваний результат: Учасник з валідними логіном та паролем повинен бути успішно залогований в систему під своїм обліковим записом.

![login defect](https://cloud.githubusercontent.com/assets/11995699/7250019/66517794-e827-11e4-9108-bd2e4168d327.png)

**Comment by S-Shevchenko** [comment]
@MaryanaDemtsyukh-SoftServe  Спасибо. Исправили.  Проверьте пожалуйста.

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
Для даних користувачів (логін: tester пароль: 012345678 або логін: victor_qc пароль: 12345678) дефект відтворюється і результат залишається незмінним - ці користувачі не можуть авторизуватись у систему. Однак для нових зареєстрованих користувачів цієї проблеми немає.
Підтвердіть будь ласка що вище згадані користувачі присутні в базі даних користувачів цього майданчику.

**Comment by S-Shevchenko** [comment]
@MaryanaDemtsyukh-SoftServe Немає.

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
Дефект вже невалідний
