### ISSUE TITLE
Public-bid, Реєстрація користувача. Неможливо зареєструвати користувача, якщо користувач вказав в полі "Прізвище, ім'я та по батькові" вказав " ' " апостороф

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#246]
Кроки для відтворення:
1. Перейдіть за посиланням https://public-bid.com.ua/
2. Натисніть кнопку Реєстрація/Вхід
3. Натисніть кнопку Я новий користувач
4. Введіть коректний, валідний емейл в поле "Ваш унікальний e-mail"
5. В поле "Прізвище, ім'я та по батькові*" введіть: "Прізвищенко Мар'ян Батькович"
6. Поставте галочку згоди з умовами використання сервісу
7. Натисніть кнопку Далі
8. Залиште всі поля пустими та натисніть кнопку Зареєструвати угоду

Очікуваний результат:
Повідомлення про те що поля місять невірні дані/не містять дані

Фактичний результат:
Навіть, якщо користувач потратив час на введення всіх даних в поля, його договір не був збережений, а після натискання кнопки "Зареєструвати угоду", користувач був переадресований на головну сторінку без будь-яких повідомлень.

**Comment by maksimmaksimov** [comment]
Исправлена, просьба проверить

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
