### ISSUE TITLE
Public-bid, Мій кабінет. Діючі угоди. Некоректне згортання та розгортання, якщо у користувача більше однієї угоди.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#247]
1. Перейдіть за посиланням https://public-bid.com.ua
2. Залогуйтесь за користувача з:
   логіном: misha.a@meta.ua 
   паролем: Password1
3. Зайдіть в > Мій кабінет > Діючі угоди
4. Натисніть на контрол для розгортання угоди №465, та угоди №440
5. Натисніть на загальну кнопку угоди 465 "Згорнути/розгорнути усі вкладки" двічі
6. Натисніть по кожній вкладці: Учасники угоди, Запрошення, Документація

Очікуваний результат:
5. Вкладки угоди 465 повинні бути розгорнуті
6. Кожна окрема вкладка угоди 465 повинна розгортатись окремо
Фактичний результат:
5. Вкладки угоди 440 були розгорнуті, та згорнуті
6. Кожна вкладка угоди 440 була розгорнути, то згортання було неуспішне.

**Comment by maksimmaksimov** [comment]
Изменили поведение при раскрытии информации об угоде, теперь одновременно может быть раскрыта информация только по одной угоде.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
