### ISSUE TITLE
[ЕЛЕГ] Помилка відображається при навігації до останньої сторінки списку закупівель

### ISSUE THREAD

**Issue by MaryanaDemtsyukh-SoftServe** [openprocurement/frontend#248]
Кроки для відтворення:
1. Відкрити гіперпосилання http://uat.e-tender.biz у будь-якому бравзері
2. Перейти на вкладку Вхід
3. Заповнити необхідні текстові поля валідними даними Замовника (логін: Operator1 пароль: Oo123456)
4. Клікнути на кнопку Логін
5. Перейти на вкладку Торговельний майданчик
6. Перейти відразу на останню сторінку за допомогою навігації розміщеної під списком закупівель

Фактичний результат: помилка відображається при навігації до останньої сторінки списку закупівель. Відображається лоудінг індикатор. Користувач не має змоги продовжити роботу з системою.
Очікуваний результат: Користувач повинен мати змогу переглянути всі елементи списку закупівель. Ніяких помилок не повинно відображатись.

![navigation](https://cloud.githubusercontent.com/assets/11995699/7252855/f65e934e-e840-11e4-8d18-92a857ab740e.png)

**Comment by S-Shevchenko** [comment]
@MaryanaDemtsyukh-SoftServe Спасибо, взяли в работу.

**Comment by S-Shevchenko** [comment]
не воспроизводится.
