### ISSUE TITLE
Public-bid, Реєстрація Організації. При спробі зареєструвати угоду з пустим полем ЄДРПОУ воно не підсвічується червоним, та з'являється повідомлення з невірним текстом.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#249]
1. Перейдіть за посиланням //public-bid.com.ua
2. Натисніть Реєстрація/Вхід > Я новий користувач, заповніть поля та натисніть Далі
3. Натисніть Зареєструвати угоду, не заповнюючи жодне поле

Очікуваний результат:
3. Напис "ЄДРОПУ *" повинен бути підсвічений, як усі інші поля без даних
3. Повинно з’являтись повідомлення з текстом: "Поле обов’язкове для заповнення" біля поля "ЄДРПОУ"
Фактичний результат:
3. Напис "ЄДРОПУ *" не підсвічується, як обов'язковий, та зявляється повідомлення з невірним текстом "Невірний формат поля"

**Comment by maksimmaksimov** [comment]
Исправлено, ЕДРПОУ подсвечивается цветом.
