### ISSUE TITLE
Public-bid, Реєстрація Організації. Поле ЄДРОПУ пропускає двоцифрові коди.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#250]
1. Перейдіть за посиланням //public-bid.com.ua
2. Натисніть Реєстрація/Вхід > Я новий користувач, заповніть поля та натисніть Далі
3. Введіть в поле "ЄДРОПУ" : "11" 
4. Залиште решту полів пустими та натисніть кнопку Зареєструвати угоду

Очікуваний результат:
4. Мало б зявитись повідомлення про помилку, що "введений код невірний" чи "Невірний формат поля"

Фактичний результат:
4. Система пропускає двоцифрове значення в поле ЄДРОПУ, при тому що згідно статті http://zakon3.rada.gov.ua/laws/show/z1287-12 :
а) код клієнта за ЄДРПОУ (доповнюється зліва нулями до восьми цифр, якщо значущих цифр менше 8);
Іншими словами, поле ЄДРПОУ неповинно пропускати код менше восьми символів.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe в системе реализовано автоматическое добавление нулей в начало кода. Вы можете открыть список организаций (после авторизации) и найдете организацию с кодом 00000011

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Перевірено, дійсно є. Закриваю.
