### ISSUE TITLE
Public-bid, Реєстрація Організації. Невірне текстове повідомлення для поля "Область *"

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#251]
1. Перейдіть за посиланням //public-bid.com.ua
2. Натисніть Реєстрація/Вхід > Я новий користувач, заповніть поля та натисніть Далі
3. Натисніть Зареєструвати угоду, не заповнюючи жодне поле
   ![image](https://cloud.githubusercontent.com/assets/11783631/7254304/eb46bae0-e84a-11e4-9524-d5aebdbcbdfc.png)

Очікуваний результат:
3. Біля поля "Область *" повинне зявитись повідомлення загального типу "Поле обов’язкове для заповнення"
Фактичний результат:
3. Біля поля "Область *" зявляється повідомлення "Область: Поле обов’язкове для заповнення" іншого формату, ніж для всіх решта полів

**Comment by maksimmaksimov** [comment]
Исправлена, просьба проверить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
