### ISSUE TITLE
Public-bid, Реєстрація Організації. Поле "Адреса організації (індекс) *" пропускає 10 символів.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#252]
1. Перейдіть за посиланням //public-bid.com.ua
2. Натисніть Реєстрація/Вхід > Я новий користувач, заповніть поля та натисніть Далі
3. Введіть в поле "Адреса організації (індекс)" : "123456789я"
4. Натисніть кнопку Зареєструвати угоду

Очікуваний результат: 
4. Біля поля "Адреса організації (індекс)" повинне зявитись повідомлення: "Невірний формат поля"

Фактичний результат:
4. Система пропускає десятизначний індекс, та інші символи окрім цифр.

Якщо зайти на сайт http://services.ukrposhta.com/postindex_new/ і спробувати пошукати населений пункт, то система пропускає тільки п'ятизначний код і тільки цифри.

**Comment by maksimmaksimov** [comment]
Исправлено, просьба проверить

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Перевірено, тепер поле пропускає тільки 5 символів. Але досі пропускає не тільки цифри.
![image](https://cloud.githubusercontent.com/assets/11783631/7318960/c1e78f34-ea99-11e4-80eb-0d65c27cdbda.png)

**Comment by maksimmaksimov** [comment]
Принято, в требованиях к системе не было предусмотрено никакой защиты от дурака в данном поле. Добавим.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, Тепер з'являється повідомлення з наступним текстом: "Поштовий індекс має бути введений у форматі 00000". Закриваю
