### ISSUE TITLE
Public-bid. Реєстрація другої та кожної наступної угоди. З'являється повідомлення з некоректним текстом

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#253]
1. Перейдіть за посиланням https://public-bid.com.ua/
2. Натисніть Реєстрація/Вхід
3. Введіть email: misha.a@meta.ua та валідне прізвище імя
4. Натисніть Далі
5. Введіть валідні дані та натисніть Зареєструвати угоду
6. Залогуйтесь на пошту 
   login: misha.a@meta.ua 
   password: Password1
7. Дочекайтесь листа з ключем доступу, перейдіть на сторінку де потрібно ввести ключ та решту інформації.
8. Введіть ключ з емейлу, так в полі емейл вкажіть misha.a@meta.ua
9. Заповніть решту форми, та натисніть продовжити реєстрацію

Очікуваний результат:
Користувач побачить повідомлення про те, що до його електронної пошти додано угоду

Фактичний результат:
Користувач отримує повідомлення про те, що На вашу електронну адресу надіслано повідомлення. (Користувача обманули, тому що більше ніякий лист не приходить)
![image](https://cloud.githubusercontent.com/assets/11783631/7254827/10743e02-e84e-11e4-8d31-b01f7269b784.png)

**Comment by maksimmaksimov** [comment]
Данное замечание известно и на данный момент проводятся работы по устранению.

**Comment by maksimmaksimov** [comment]
Исправлено. Сообщение пользователю поменяли.

**Comment by maksimmaksimov** [comment]
Ошибка на доработке.

**Comment by maksimmaksimov** [comment]
Ошибка исправлена. Если пользователь регистрируется второй и т.д. раз - он получает сообщение: "Вітаємо, реєстрацію завершено, бажаємо приємного користування"

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
![image](https://cloud.githubusercontent.com/assets/11783631/7489812/8841f9ce-f3e3-11e4-981b-9188528db357.png)
Перевірено, тепер з'являється таке повідомлення. При реєстрації додаткового договору.
