### ISSUE TITLE
Public-bid, Мій кабінет. Мої організації. Некоректне відображення статусу

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#254]
![image](https://cloud.githubusercontent.com/assets/11783631/7255242/aede6584-e850-11e4-8df5-9bd95c17f5dc.png)
Незрозумілий формат відображення статусу, та значення позначене червоною стрілкою.

**Comment by maksimmaksimov** [comment]
Данная ошибка известна, будет исправлена.

**Comment by maksimmaksimov** [comment]
Исправлена

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov 
1. Незрозуміло, чому статус організації "Неактивний", можливо варто замінити на "Не підтверджений" адміністратором
2. Ознака державної реєстрації відображається як "true" можливо варто замінити на чекбокс чи на "Присутня" "Відсутня".
![image](https://cloud.githubusercontent.com/assets/11783631/7343417/1884ffd4-ecca-11e4-9e7b-e969169e45e7.png)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe статус организации "Неактивний" устанавливается до того момента, пока пользователь не подтвердит регистрацию, как только пользователь подтвердил регистрацию, статус организации меняется на "Тимчасова".
По поводу true/false внесем изменения.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Стосовно статусу:
Я правильно розумію, що користувач має підтвердити реєстрацію тільки на елетронній пошті ?
Чи це має відбутись іншим чином ?

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe вы правильно понимаете, пользователь когда переходит по ссылке на форму ввода пароля тем самым подтверждает регистрацию в системе.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov В мене виникла наступна ситуація:
1. Залогуйтесь за користувача:
login: misha.multi@meta.ua
password: Password1
2. Перейдіть в Мій кабінет та натисніть Мої Організації
3. Розгорніть детальну інформацію про організацію
Зараз Організація цього користувача в статусі Неактивний, хоча користувач вже й підтвердив себе, при встановленні паролю.
Перегляньте будь-ласка цей випадок і скажіть чи це коректно чи ні?

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe очень странно, я сегодня регистрировал нового пользователя с новой организацией, и до того момента, пока пользователь не подтвердил регистрацию, статус организации был Неактивна, а после того как пользователь подтвердил регистрацию, статус организации поменялся на Тимчасова.
А вы регистрировали договор с существующей организацией?

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Ні, я зареєстрував нову організацію.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe ясно, сейчас попробую воспроизвести ситуацию.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe ситуация подтвердилась, статус организации остался Неактивна. Обсудим данную ситуацию с аналитиками.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Исправлено, просьба проверить. Статус организации должен быть "Тимчасова".

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Підтверджую, тепер статус організації "Тимчасова". Я правильно розумію, що тепер по сценарію цей статус має змінити адміністратор ?

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Да, все верно, пользователь связывается с администратором вне системы, и администратор меняет статус организации/договора и пользователя.

**Comment by maksimmaksimov** [comment]
Можно закрывать issue

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov досі відтворюється, чи вважати це коректною поведінкою ?
![image](https://cloud.githubusercontent.com/assets/11783631/7387744/570fe90e-ee68-11e4-8ab7-bf1c9ef8fd74.png)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe я не обратил на это внимание, пока исправляется.
