### ISSUE TITLE
Public-bid, Реєстрація Організації. Незрозуміле текстове повідомлення для поля "Сайт"

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#255]
1. Перейдіть за посиланням //public-bid.com.ua
2. Натисніть Реєстрація/Вхід > Я новий користувач, заповніть поля та натисніть Далі
3. Введіть в поле сайт: "www.google.com.ua"
4. Натисніть зареєструвати угоду
   ![image](https://cloud.githubusercontent.com/assets/11783631/7269220/7e2b5228-e8da-11e4-896b-c23b4faa394a.png)
   Очікуваний результат:
5. Поле не повинно підсвічуватись, та повідомлення з текстом Невірний формат поля неповинно з'являтись.

Фактичний результат:
4. Поле підсвічується наче в нього введені невірні дані. Повідомлення про помилку не містить зразку вірного формату.

**Comment by maksimmaksimov** [comment]
Исправлено, просьба проверить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
