### ISSUE TITLE
Public-bid, Реєстрація Організації. Чи повинні поля обов'язкові для заповнення пропускати значення " " - один пробіл.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#256]
1. Перейдіть за посиланням //public-bid.com.ua
2. Натисніть Реєстрація/Вхід > Я новий користувач, заповніть поля та натисніть Далі
3. Введіть у всі поля з червоними стрілочками по одному пробілу
4. Натисніть Зареєструвати угоду
   ![image](https://cloud.githubusercontent.com/assets/11783631/7269327/9e2b7584-e8db-11e4-97cf-65a187701701.png)
   Очікуваний результат:
5. Зазвичай поля які фігурують як обов'язкові, повинні відрізати пробіли зліва та зправа, також не допускати до подальшої реєстрації, якщо введено тільки один пробіл.
   Фактичний результат:
6. Зазначені поля не показують повідомлень про помилку отже, користувач може заповнити обов'язкові поля пробілами і проходити реєстрацію далі.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe нет, такого быть не должно, данная ошибка известна. Будет исправлена.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov ще одне поле, яке пропускає пробіл
![image](https://cloud.githubusercontent.com/assets/11783631/7269885/4004da04-e8e0-11e4-9c04-24b4db3ce35d.png)

**Comment by maksimmaksimov** [comment]
Спасибо, принято.

**Comment by maksimmaksimov** [comment]
Ошибка исправлена

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
