### ISSUE TITLE
Public-bid, Сторінка реєстрації. Повідомлення про помилку переміщаються в залежності від довжини опису типу угоди.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#257]
1. Перейдіть за посиланням //public-bid.com.ua
2. Натисніть Реєстрація/Вхід > Я новий користувач
3. Поставте галочку в чек бокс "Я згоден з умовами угоди використання сервісу "Public Bid""
4. Натисніть Далі
   ![image](https://cloud.githubusercontent.com/assets/11783631/7269590/d7860356-e8dd-11e4-9c45-26b7428f5036.png)
   ![image](https://cloud.githubusercontent.com/assets/11783631/7269594/e4d88baa-e8dd-11e4-94d7-cb598aa02dbe.png)
   ![image](https://cloud.githubusercontent.com/assets/11783631/7269603/002e0d9e-e8de-11e4-9aa0-a75fee5ba6c8.png)
   Очікуваний результат:
5. Повідомлення про те що поле обов'язкове для заповнення повинно бути одразу біля самого поля, а не переміщатись в залежності від довжини тексту опису типу угоди

**Comment by maksimmaksimov** [comment]
Исправлена, просьба проверить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
