### ISSUE TITLE
Public-bid, Підтвердження реєстрації, встановлення паролю. Описка у повідомленні про помилку.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#258]
1. Перейдіть за посиланням http://public-bid.com.ua/?action=change_pwd&activation_code=d55c79d9-2632-4f77-8f1f-7c239be67c50
2. Введіть в поле Новий пароль *: Password1
3. Введіть в поле Підтвердження паролю *: Password2
4. Натисніть Змінити пароль
   ![image](https://cloud.githubusercontent.com/assets/11783631/7271467/4d8dbda6-e8ec-11e4-9331-18099e7af0a9.png)
   Очікуваний результат:
5. Повідомлення з текстом: "Введені паролі не співпадають" або "Новий пароль та підтвердження не співпадають"

Фактичний результат:
4. Повідомлення з текстом: "Новий пароль та підтвердження на співпадають."

**Comment by maksimmaksimov** [comment]
Исправлено.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, тепер текст виглядає коректно "Новий пароль та підтвердження не співпадають." Закриваю.
