### ISSUE TITLE
Public-bid, Підтвердіть будь-ласка, що форма авторизації при появі повідомлень про помилку повинна зсуватись вліво.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#259]
![image](https://cloud.githubusercontent.com/assets/11783631/7271837/f6a86e52-e8ee-11e4-8998-bfb5a6b7a2b2.png)
![image](https://cloud.githubusercontent.com/assets/11783631/7271846/079af806-e8ef-11e4-8e09-1522e167ef50.png)

**Comment by RudDaryna** [comment]
Доброго дня, 
така поведінка системи нормальна

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Дякую за підтвердження. Закриваю.
