### ISSUE TITLE
Запаздывает переход статуса

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#26]
Аналогично проблеме, которую ПРОМа, которую мы только что обсуждали голосом
Тендер, созданный на ПРОМ в 15:00 (момент завершения приема заявок) изменил статус, а на СМАР продолжает быть в статусе "Прием предложений":

![image](https://cloud.githubusercontent.com/assets/9398532/5875077/a789c316-a311-11e4-847f-f83d2a277f86.png)

**Comment by AlexRudenko** [comment]
У нас был отключен дэмон. Все нормально
