### ISSUE TITLE
Public-bid, Зареєстрований користувач. З діючою угодою в статусі Тимчасова, має можливість запрошувати користувачів в систему.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#260]
1. Зареєструйте користувача з тимчасовою угодою
2. Зайдіть в Мій кабінет > Діючі угоди > Учасники угоди
3. Надішліть запрошення в систему на будь-який доступний вам емейл
4. Залогуйтесь на емейл на який надіслано запрошення, та спробуйте завершити реєстрацію запрошеного користувача.

Очікуваний результат:
4. Користувач повинен бути успішно зерєстрований
![image](https://cloud.githubusercontent.com/assets/11783631/7274173/39676a7c-e903-11e4-945f-91d18528631a.png)

Фактичний результат:
4. Користувач отримує помилку: "Код недійсний. Для продовження реєстрації зареєструйте, будь-ласка, договір"

Навіть після реєстрації договора, код дійсним не стає. Можливості надіслати повторно запрошення даному користувачеві немає, оскільки запрошення вже надіслано.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe подскажите, пожалуйста, при регистрации договора, в который вы пытаетесь пригласить пользователя, какое количество пользователей было указано?

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov було вказано значення за замовчуванням 1.
Якраз працюю над занесенням цього дефекту, що користувач з тимчасовою угодою в якій зазначений тільки один користувач може запрошувати інших користувачів.

**Comment by maksimmaksimov** [comment]
У нас проверка выполняется в момент регистрации приглашенного пользователя, а не в момент отправки приглашения

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov 
Добре, тоді потрібно поправити текст повідомлення про помилку.
Також потрібно заборонити користувачеві з 1 людиною зазначеною в угоді надсилати запрошення.

**Comment by RudDaryna** [comment]
@Mykhailo-Shtabaliuk-SoftServe внесемо обмеження в систему для угод з вказаним 1 користувачем. В повідомлення внесемо зміни

**Comment by maksimmaksimov** [comment]
Исправлено

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
![image](https://cloud.githubusercontent.com/assets/11783631/7388043/db312fde-ee6a-11e4-92a8-4a760d888300.png)
@maksimmaksimov підтвердіть будь ласка, що дане повідомлення про максимальну кількість користувачів реалізовано і відображається вірно.

**Comment by maksimmaksimov** [comment]
Да, реализовано верно

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
дякую, Закриваю.
