### ISSUE TITLE
Public-bid, Мій кабінет. Діючі Угоди. Відсутнє найменше значення по замовчуванню для вікна надсилання запрошень користувачам.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#261]
1. Залогуйтесь в систему за учасника з можливістю надсилати запрошення
2. Мій кабінет > Діючі угоди > Відкрийте вікно надсилання запрошень
3. Зменшіть розмір поля запрошень до такого як на скріншоті
   ![image](https://cloud.githubusercontent.com/assets/11783631/7274227/b0712626-e903-11e4-8640-6ac1b6c4d0b8.png)
4. Закрийте це вікно за допомогою чорного хрестику
5. Натисніть повторно кнопку Надіслати запрошення
   ![image](https://cloud.githubusercontent.com/assets/11783631/7274274/1980993a-e904-11e4-9843-07dc2c2e7b0f.png)

Очікуваний результат:
5. Поле надсилання запрошення повинне прийняти найменше значення за замовчуванням

Фактичний результат:
5. Користувач втратив можливість користуватись даною, функцією.

**Comment by maksimmaksimov** [comment]
Пользователю доступно изменение размеров данного окна, и соответственно пользователь не потерял возможность пользоваться данной функцией.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Коли користувач починає працювати з вікном, йому доступний зправа знизу трикутник, який дозволяє змінювати розміри вікна.
На скріншоті в кроці 5 користувач немає можливості ним скористатись.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe я данную ситуацию проверил в Opera, IE, FF и во всех браузерах я мог менять размер окна, в каком браузере у вас это получилось воспроизвести?

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov У браузері google chrome версія 42.0.2311.90 m

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe у меня идентичная версия браузера, и изменение размеров окна доступно
![000294](https://cloud.githubusercontent.com/assets/8382283/7275040/47732c4e-e90a-11e4-9742-9246dcfdbdb5.png)

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov у мому браузері все виглядає наступним чином:
![image](https://cloud.githubusercontent.com/assets/11783631/7275102/9d22274e-e90a-11e4-9b98-31040a9f9ed6.png)

**Comment by maksimmaksimov** [comment]
Странно, уберем возможность менять размеры окна.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov дякую, за розуміння

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe убрали возможность менять размер окна.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
