### ISSUE TITLE
Public-bid, Мій кабінет > Зміна Паролю. Залогований користувач, який незнає поточного паролю, може змінити пароль.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#262]
1. Залогуйтесь в систему за будь-якого існуючого користувача
2. Перейдіть в > Мій кабінет > Зміна паролю
3. В поле "Поточний пароль" введіть "  " - два пробіли
4. В поле "Новий пароль" введіть: Password2
5. В поле "Підтвердіть пароль" введіть: Password2
6. Натисніть кнопку змінити пароль

Очікуваний результат:
6. Користувачеві повинне з'явитись повідомлення про те що поточний пароль введено невірний.

Фактичний результат:
6. Пароль залогованого користувача був змінений на Password2

**Comment by maksimmaksimov** [comment]
Исправлена, просьба проверить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, тепер система не пропускає два пробіли замість поточного паролю. Закриваю.
