### ISSUE TITLE
Public-bid. Підтвердіть будь-ласка, що дане повідомлення про відсутність права на реєстрацію закупівлі реалізовано вірно.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#263]
1. Залогуйтесь в систему за користувача без ознаки держ реєстрації
2. Спробуйте створити закупівлю
   ![image](https://cloud.githubusercontent.com/assets/11783631/7275879/03b2a980-e90f-11e4-9139-0e17f35e5ffc.png)

**Comment by RudDaryna** [comment]
все вірно

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@RudDaryna дякую, закриваю.
