### ISSUE TITLE
Public-bid, Період уточнень. Обговорення. Користувач який задав питання, не може завантажити файл, який був прикріплений до відповіді

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#264]
1. Перейдіть за посиланням та залогуйтесь в систему
2. Знайдіть закупівлю в періоді уточнень
3. Задайте запитання
4. Дайте відповідь користувачем, який створив закупівлю та прикріпіть файл
5. Попробуйте завантажити цей файл користувачем, який задав запитання

Очікуваний результат:
5. Повинна бути можливість завантажити файл, який є частиною відповіді
Фактичний результат:
5. Користувачеві відображається некоректна лінка, не на файл.
![image](https://cloud.githubusercontent.com/assets/11783631/7276579/3c22a514-e913-11e4-8c72-741e975bcfcd.png)

**Comment by maksimmaksimov** [comment]
Ошибка исправлена, проверить можно будет только на новых вопросах.
