### ISSUE TITLE
Publick-bid. IE10. Контроли трошки не на місці.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#265]
IE v. 10.0.9200.17267

На 11 версії все ок.
![image](https://cloud.githubusercontent.com/assets/11888281/7293383/54a4cbfe-e9ad-11e4-8c68-cc92e1428e67.png)

Зараз на 10 ІЕ все виглядає практично, як і на 11.
Питання більше чи взагалі 10 ІЕ підтримується?

**Comment by maksimmaksimov** [comment]
Исправлено.
