### ISSUE TITLE
Public-bid, Сторінка авторизації. Невірний текст у повідомленні про помилку, при введені коректної електронної адреси та некоректного паролю.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#266]
1. Перейдіть по посиланню https://public-bid.com.ua/
2. Натисніть на контрол Реєстрація/Вхід
3. Введіть адресу яка не зареєстрована у Public Bid та будь-який пароль
4. Натисніть кнопку Вхід, результат зображено на скріншоті
   ![image](https://cloud.githubusercontent.com/assets/11783631/7294524/cc3214e8-e9b6-11e4-92e4-45d3d7933a1f.png)
5. Введіть на цей раз коректну (зареєстровану адресу у Public Bid), та некоректний пароль
6. Натисніть Вхід

Очікуваний результат:
6. Користувач побачить повідомлення про те, що введений пароль невірний.

Фактичний результат:
6. Зявляється повідомлення про те, що "Невірний логін або праоль"
![image](https://cloud.githubusercontent.com/assets/11783631/7294572/32bbc42a-e9b7-11e4-9e72-b2e0f7dfea79.png)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe данное поведение системы абсолютно корректное. Просьба закрыть это замечание - в сообщении сказано, что неверный логин или пароль.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov добре, оскільки ви підтвреджуєте, що дане повідомлення коректне, тоді закриваю.
