### ISSUE TITLE
[Public-bid] Частина інформації залишається не відображеною після зменшення розміру вікна браузера

### ISSUE THREAD

**Issue by MaryanaDemtsyukh-SoftServe** [openprocurement/frontend#267]
Кроки для відтворення:
1. Перейти за гіперпосиланням https://public-bid.com.ua/
2. Перейти на Реєстрацію/Вхід
3. Вибрати "Я новий користувач"
4. Заповнити всі обов'якові поля валідними даними
5. Поставити галочку "Я згоден з умовами угоди..."
6. Перейти Далі
-> користувач знаходиться на сторінці "Картка організації"
7. Заповнити поле "ЄДРПОУ" валідним значенням (напр.0), яке вже збережене системою і містить велику кількість символів в полях "Скорочена назва організації", "Деталізація адреси організації"
8. Вийти з повно-екранного режиму/зменшити розмір вікна 

Фактичний результат: ширина діалогу з даними по введеному коду ЄДРПОУ більша за ширину вікна браузера, тому інформація не відображається повністю (див. скріншот). При натисканні на горизонтальний скролбар - діалог з даними перестає відображатись.
Очікуваний результат: користувач повинен мати змогу переглянути всю інформацію на діалозі з запропонованими кодами ЄДРПОУ. 

![window minimaze](https://cloud.githubusercontent.com/assets/11995699/7296628/f76ed64c-e9c9-11e4-9148-e0df43011499.png)

**Comment by maksimmaksimov** [comment]
@MaryanaDemtsyukh-SoftServe в принципе, необходимая информация об организации присутствует в выпадающем списке, не влазит только адрес организации, но его можно посмотреть, воспользовавшись прокруткой:
![000302](https://cloud.githubusercontent.com/assets/8382283/7316420/8b949086-ea7f-11e4-91af-0918297d6e19.png)

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
Так, зараз є можливість скористатись горизонтальним скролбаром. 
Також є можливість переглянути адресу, однак дуже довгі адреси залишаються "обрізаними" і не переносяться в наступний рядок:
![default](https://cloud.githubusercontent.com/assets/11995699/7316779/9bb03e86-ea82-11e4-8ca6-6f62e8f8ec92.png)

**Comment by maksimmaksimov** [comment]
Обратите, пожалуйста, внимание, что это тестовые данные и адрес написан одним словом, в котором содержится 100+ символов без (!) пробелов - не думаю что в реальной жизни существуют подобные адреса. А значения с пробелами отображаются корректно в данном выпадающем списке.

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
Перевірено з іншими тестовими даними. Проблема ліквідована.
