### ISSUE TITLE
Public-bid, Відновлення паролю. Приходить лист з некоректною лінкою, користувач не в змозі відновити пароль

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#269]
1. Зареєструйте користувача на https://public-bid.com.ua
2. Перейдіть на сторінку відновлення пароля, та введіть емейл зареєстрованого користувача
3. Натисніть Відновити пароль

Очікуваний результат:
3. Лист на пошті, з посиланням на відновлення паролю

Фактичний результат:
3. Лист містить некоректне посилання на відновлення паролю.
![image](https://cloud.githubusercontent.com/assets/11783631/7297812/094e9e06-e9d4-11e4-88a8-9afadfbb5455.png)

**Comment by maksimmaksimov** [comment]
Ошибка известна, ведутся работы по исправлению.

**Comment by maksimmaksimov** [comment]
Ссылку поправили, просьба проверить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Тепер лист приходить з коректною лінкою та є можливість змінити пароль. Закриваю.
