### ISSUE TITLE
После завершения аукциона аттачменты не открываются через сайт

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#27]
Торги 1-ПРОМ-АК-02 

![image](https://cloud.githubusercontent.com/assets/9398532/5875514/7c74d76a-a316-11e4-909e-16b6bac37b6e.png)

**Comment by AlexRudenko** [comment]
Кнопка "Квалификационные документы" служит для добавления документов. Для просмотра необходимо нажимать на кнопку "Результаты тендера"
![image](https://cloud.githubusercontent.com/assets/10192570/5876446/de78ab04-a31f-11e4-8d99-b906bade4c7e.png)
