### ISSUE TITLE
Public-bid, Мій кабінет. Функція "Видалити мене з системи" працює некоректно

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#270]
1. Залогуйтесь в систему https://public-bid.com.ua/
2. Перейдіть в > Мій кабінет
3. Натисніть видалити мене з системи
4. Натисніть кнопку підтвердження "Видалити"

Очікуваний результат:
4. Користувач вилогований і більше не може залогуватись в систему. - базується на повідомленні з яким погодився користувач, текст повідомлення: "Ви дійсно бажаєте видалити свій обліковий запис з Public bid без можливості відновлення?"

Фактичний результат:
4. Користувач переадресований на головну сторінку, та після натискання кнопки Реєстрація/Вхід все виглядає так ніби він знову залогінений в системі. Змінився тільки статус на Неактивний. Якщо користувач видалився з системи нелогічно залишати його залогованим, для можливості все таки знайти, якісь доступні йому функції.
![image](https://cloud.githubusercontent.com/assets/11783631/7297065/e970ed56-e9cd-11e4-97df-2c02ec7a0eef.png)
Якщо вилогуватись і спробувати залогуватись знову за видаленого користувача отримуєм повідомлення з некоректним текстом, мало писати, що користувач видалився з системи, чи щось в тому дусі.
![image](https://cloud.githubusercontent.com/assets/11783631/7298135/400da39a-e9d6-11e4-8e1c-5ac3261b5691.png)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe а почему вы считаете, что пользователю выдается сообщение с некорректным текстом? У вас есть требование/спецификация/техническое задание, в котором сказано, какое должно быть сообщение? По-моему сообщение не является некорректным.

**Comment by maksimmaksimov** [comment]
Дополню так же, что пользователь фактически не удаляется из системы, ему только присваивается признак удаления. Так же, сообщение, которое появляется сейчас, полностью соответствует требованиям к системе.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Тому що коли користувач намагався видалитись, я очікував, що він буде вилогованим. Ні у мене немає, вимог та специфікацій.
Мене бентежить той факт, що після того, як користувач підтверджує своє бажання бути видаленим, він одразу ж бачить, що його обманули і залишили просто неактивним.
Варто проінформувати користувача, при процедурі видалення, що він не буде видаленим, а тільки переведеним у неактивний стан.

**Comment by maksimmaksimov** [comment]
Я имел в виду сообщение со второго скриншота, а то, что пользователь остается авторизован - это ошибка, и её исправят.

**Comment by maksimmaksimov** [comment]
Исправлено удаление пользователя. Просьба проверить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, тепер користувач при видаленні себе автоматично вилоговується з системи.
Під час процедури видалення у повідомленні пише, що користувача буде видалено з системи, а при спробі залогуватись користувач розуміє, що він не видалений, а тільки залишився без діючих договорів.

**Comment by maksimmaksimov** [comment]
Данное поведение считаем корректным. Согласно требований к системе, пользователь физически не удаляется из БД. Данное сообщение пользователю считаем корректным.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov добре, дякую за розяснення. Закриваю.
