### ISSUE TITLE
Public-bid, Реєстрація угоди. Тултіпи містять некоректні символи

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#271]
1. Перейдіть по силанню https://public-bid.com.ua/
2. Натисніть контрол Реєстрація/ Вхід
3. Натисніть Я новий користувач
4. Натисніть на дропдаун Тип угоди, та навігуйте курсор миші на кожен тип договороу зокрема

Очікуваний результат:
4. Спливаючі повідомлення без "<br>" - тегів
![image](https://cloud.githubusercontent.com/assets/11783631/7298361/c3b8ebfe-e9d7-11e4-822d-e6b2c13445c2.png)

Фактичний результат:
4. Кожне спливаюче повідомлення містить символи переносу рядка

**Comment by maksimmaksimov** [comment]
Исправлена, просьба проверить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено. Закриваю.
