### ISSUE TITLE
Public-bid, Неможливо змінити поточний пароль, на пароль зі спец символами

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#272]
1. Залогуйтесь за зареєстрованого користувача https://public-bid.com.ua/
2. Зайдіть в Мій кабінет
3. Перейдіть на сторінку зміни паролю
4. В поле поточний пароль введіть поточний пароль
5. В поле Новий пароль введіть: "Password!"
6. В поле Підтвердження паролю введіть: "Password!"
7. Натисніть кнопку Змінити пароль

Очікуваний результат:
7. Пароль залогованого користувача повинен бути змінений на "Password!"
Фактичний результат:
7. Користувач отримує повідомлення про помилку.
![image](https://cloud.githubusercontent.com/assets/11783631/7300073/8bb524ba-e9e2-11e4-9360-f9a22566858b.png)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Ошибка исправлена

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, тепер спец символи латинської мови підтримуються полем пароль.
Підтвердіть будь ласка, що кириличні спецсимволи та й загалом кирилиця неповинна підтримуватись цим полем

**Comment by maksimmaksimov** [comment]
Кириллица поддерживается для паролей, я успешно изменил пользователю пароль на "Парольq1"

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Я пробую змінити пароль на "Пароль№№" - у мене зявляється повідомлення:
"Довжина паролю має бути 8-20 символів і містити нелітеральні знаки та латинські літери"

**Comment by maksimmaksimov** [comment]
Покажите, пожалуйста, где в слове "Пароль№№" латинские буквы?

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перепрошую, зрозумів свою помилку. Закриваю.

**Comment by maksimmaksimov** [comment]
ничего, :)
