### ISSUE TITLE
Public-bid, Реєстрація угоди. Підтвердіть будь-ласка що повідомлення про помилку містить коректний текст.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#274]
1. Перейдіть за посиланням https://public-bid.com.ua/
2. Натисніть контрол Реєстрація/Вхід
3. В поле Прізвище, ім'я та по батькові\* введіть: "!" 
4. Підтвердіть згоду з умовами угоди використання сервісу та натисніть Далі

Очікуваний результат:
4. Біля поля Прізвище, ім'я та по батькові\* з'явиться повідомлення про те, що Невірний формат поля
Фактичний результат:
4. Повідомлення з текстом: "Невірно введено ім'я"
![image](https://cloud.githubusercontent.com/assets/11783631/7301228/0882ace0-e9ea-11e4-9256-f0a78287740b.png)

**Comment by maksimmaksimov** [comment]
абсолютно корректный текст

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov дякую, закриваю.
