### ISSUE TITLE
[Public-bid] [Реєстрація] Значення "Ознаки державної реєстрації" відображені булівським типом даних

### ISSUE THREAD

**Issue by MaryanaDemtsyukh-SoftServe** [openprocurement/frontend#275]
Веб-браузер: Google Chrome v.42.0.2311.90 
                       Mozilla Firefox 37.0.2
Кроки для відтворення:
1. Відкрити гіперпосилання public-bid.com.ua
2. Перейти до Реєстрації
3. Заповнити форму Реєстрація угоди валідними даними
4. Перейти Далі
5. В поле ЄДРПОУ ввести значення (напр. "4")
-> відображається діалог з кодами ЄДРПОУ

Фактичний результат: Дані в колонці Ознака державної реєстрації відображені булівським типом (true/false) (див.скріншот).
Очікуваний результат: Значення повинні відображатись типом даних зрозумілим користувачеві напр. символьним.

![default](https://cloud.githubusercontent.com/assets/11995699/7314938/06c9a70e-ea72-11e4-9628-9d72b48e2aae.png)

**Comment by maksimmaksimov** [comment]
Исправлено.

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
Дефект виправлено
