### ISSUE TITLE
[Public-bid] [Реєстрація] Користувач не може ввести повну адресу так як поле "Деталізація адреси організації" приймає тільки 5 символів

### ISSUE THREAD

**Issue by MaryanaDemtsyukh-SoftServe** [openprocurement/frontend#276]
Веб-браузер: Google Chrome v.42.0.2311.90; Mozilla Firefox 37.0.2
Кроки для відтворення:
1. Відкрити гіперпосилання public-bid.com.ua
2. Перейти до Реєстрації
3. Заповнити форму Реєстрація угоди валідними даними
4. Перейти Далі
5. Ввести дані в поле "Деталізація адреси організації"

Фактичний результат: користувач не може ввести повну адресу так як поле "Деталізація адреси організації" приймає тільки 5 символів (див.скріншот).
Очікуваний результат: користувач повинен мати змогу ввести повну адресу організації.

![default](https://cloud.githubusercontent.com/assets/11995699/7315433/200781b0-ea76-11e4-8e61-a4dae85295aa.png)

**Comment by maksimmaksimov** [comment]
Исправлена, просьба проверить.

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
Перевірено. Дефект виправлено.
