### ISSUE TITLE
[Public-bid] [Реєстрація] Після введення неправильного ключа доступу користувач повертається на головну сторінку майданчика

### ISSUE THREAD

**Issue by MaryanaDemtsyukh-SoftServe** [openprocurement/frontend#277]
Веб-браузер: Google Chrome v.42.0.2311.90; Mozilla Firefox 37.0.2
Кроки для відтворення:
1. Відкрити гіперпосилання public-bid.com.ua
2. Перейти до Реєстрації
3. Заповнити форму Реєстрація угоди валідними даними
4. Перейти Далі
5. Заповнити форму Картка реєстрації валідними даними
-> на вказану пошту адресу приходить мейл з ключем доступу
6. Перейти за гіперпосиланням "продовження реєстрації", яке вказане в мейлі
7. На формі Реєстрація користувача заповнити обо'язкові поля наступним чином:
- в поле ключ доступу вставити значення з мейлу, скопійоване з знаком пунктуації (".")
- Поля "Прізвище", "Ім'я" та "e-mail" заповнити валідними значеннями
  1. Змінити положення "Захист від автореєстраці" на крайнє праве
  2. Поставити галочки в чекбоксах "Я згоден...", "Я ознайомлений..."
  3. Настиснути на Продовжити реєстрацію

Фактичний результат: повідомлення про неправильний формат поля Ключ доступу відображається на кілька секунд (<5), після чого відображається головна сторінка майданчику. користувач щоб повторно ввести ключ доступу і продовжити реєстрацію повинен повторити дії починаючи з 6 кроку.
Очікуваний результат: повідомлення про неправильний формат повинно відображатись до моменту наступної успішної валідації цього поля. користувач повинен залишатись на цій самій сторінці.

**Comment by maksimmaksimov** [comment]
Исправлено, просьба проверить.

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
Дефект виправлено.
