### ISSUE TITLE
Public-bid, Мій кабінет, Зміна паролю. Користувач більше не може встановити пароль довжиною у 8 символів.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#278]
1. Залогуйтесь за існуючого користувача у систему https://public-bid.com.ua/
2. Зайдіть в Мій кабінет
3. Перейдіть на функцію Змінити пароль
4. Введіть в поле Поточний пароль: поточний пароль коректний
5. Введіть в поле Новий пароль: "Passwor1" - 8 символів
6. Введіть в поле Підтвердження паролю: "Passwor1" - 8 символів
7. Натисніть кнопку Змінити пароль

Очікуваний результат:
7. Пароль користувача повинен бути змінений
Фактичний результат:
7. Користувач отримує помилку і не розуміє в чому справа

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Якщо користувач існував з паролем у 8 символів при авторизації, він отримує повідомлення, яке є також некоректним.
![image](https://cloud.githubusercontent.com/assets/11783631/7317350/8bf18472-ea88-11e4-97b7-b268268c585f.png)

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Неможливо залогуватись в систему за адміністратора, оскільки він має пароль довжиною у три символи
![image](https://cloud.githubusercontent.com/assets/11783631/7317474/d6d75e8e-ea89-11e4-8b5a-6b5c8fdf3b01.png)

**Comment by maksimmaksimov** [comment]
Ошибка, относительно смены пароля в моем кабинете уже была заведена здесь https://github.com/openprocurement/frontend/issues/278

**Comment by maksimmaksimov** [comment]
Ошибки исправлены, просьба проверить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірно. Закриваю.
