### ISSUE TITLE
Public-bid. Період уточнень закупівлі. Файли прикріплені до відповіді не підсвічуються, а виглядають як простий текст.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#279]
1. Перейдіть по посиланню https://public-bid.com.ua
2. Знайдіть закупівлю UA-2015-04-24-000023
3. Перейдіть до обговорень

Очікуваний результат:
3. Назви прикріплених файлів відрізняються від звичайного тексту

Фактичний результат:
3. Вигляд прикріплених файлів такий самий, як і звичний текст і користувач може помилково не зауважити, що там міститься посилання на файл. 
![image](https://cloud.githubusercontent.com/assets/11783631/7316738/3c246afa-ea82-11e4-8be9-39013ec521d9.png)

**Comment by maksimmaksimov** [comment]
Замечание исправлено.
