### ISSUE TITLE
После завершения аукциона статус торгов не изменился

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#28]
`id`: `dbf161224e6549a9851f761f3565e0cf`

Аукцион закончился в 15:36
В 15:44 статус по-прежнему "Аукцион" а не "Квалификация"

![image](https://cloud.githubusercontent.com/assets/9398532/5875529/be3d8430-a316-11e4-9f09-c80098f08898.png)

**Comment by darchik** [comment]
У нас синхронизация раз в 10 минут. Судя по вводным данным, надо было еще 2 минуты подождать и статус бы изменился.
