### ISSUE TITLE
Public-bid. Відновленя паролю. приходить 2 листа замість 1.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#280]
користувач vbilos@softserveinc.com
1. Зайдіть на public-bid
2. Натисніть Реєстрація/Вхід
3. Натисніть Відновити пароль
4. Введіть свою електронну адресу
5. Перевіряйте свою електрону адресу напротязі приблизно 10 хв

Очікувано: 1 лист з посиланням встановленя нового паролю

Фактично: 2 листа з однаковим вмістом. 2 приходить через 7хв після першого.
![image](https://cloud.githubusercontent.com/assets/11888281/7317783/1fd0da5e-ea8d-11e4-8694-21ce2a18b958.png)

Також відтворюється з листом результату проведення аукціону:
![image](https://cloud.githubusercontent.com/assets/11888281/7317707/5039aab4-ea8c-11e4-88f5-2d4f013043ae.png)

**Comment by maksimmaksimov** [comment]
Просьба проверить данную ситуацию повторно, сегодня приблизительно в это же время, как вы получили сообщения, проводились работы в системе.
