### ISSUE TITLE
Public-bid, При повторному переході по посиланні відновлення паролю, користувач переадресований на сторінку з неповним контентом.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#281]
1. Надішліть запит на відновлення паролю існуючого користувача системи https://public-bid.com.ua/
2. Перейдіть по посиланню відновлення паролю, та змініть його на інший
3. Перейдіть повторно по посиланню відновлення паролю

Очікуваний результат:
3. Користувач буде повідомлений, що дана лінка відновлення паролю вже неактивна
Фактичний результат:
3. Користувач переадресований на сторінку з неповним контентом
![image](https://cloud.githubusercontent.com/assets/11783631/7320856/93580230-eaa7-11e4-8222-4d25514d17bb.png)

**Comment by maksimmaksimov** [comment]
Исправлена, просьба проверить.
