### ISSUE TITLE
Public-bid, Створення закупівлі. Некоректне текстове повідомлення для поля кількість.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#282]
1. Залогуйтесь за користувача з правом створювати закупівлі в систему https://public-bid.com.ua/
2. Перейдіть на форму створення закупівлі
3. Заповніть всі поля окрім поля кількість валідними даними
4. В поле кількість введіть: 0 - нуль
5. Натисніть кнопку Зберегти

Очікуваний результат:
5. Користувач повинен бути повідомлений, що поле не може містити нульове значення

Фактичний результат:
5. Користувач повідомлений про те, що поле може містити значення від 0.01 до 10000000000
Але в дійсності користувач немає можливості вводити дробове значення в це поле.
Потрібно або добавити можливість, вводити в дане поле дробові значення або поправити текстове повідомлення.
![image](https://cloud.githubusercontent.com/assets/11783631/7321046/a714a26e-eaa8-11e4-8be2-e9c95cc5eec2.png)

**Comment by maksimmaksimov** [comment]
Принято, ошибка известна (ранее была исправлена, но снова воспроизводится). В поле "Кількість" должна быть возможность ввода дробных значений (разделитель "точка"). Исправим.

**Comment by maksimmaksimov** [comment]
Ошибка исправлена.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Тепер зявляється повідомлення з наступним текстом:
'10.....1' має бути знаковим десятковим числом (дробове з роздільником . або ,). Приклад: 198.23
Питання: чи коректний текст повідомлення, оскільки не дуже зрозуміло, що означає знакове число?

**Comment by maksimmaksimov** [comment]
Сообщение поменяем.

**Comment by maksimmaksimov** [comment]
Сообщение для поля "Кількість" поменяли на: 
"Не вірний формат поля, допускаються цілі числа, або дробові (роздільник крапка)"
