### ISSUE TITLE
Public-bid, Підтвердіть будь-ласка, що наступні поля відображаються вірно.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#283]
1. Зарєструйте нову організацію на ресурсі https://public-bid.com.ua/
2. Залогуйтесь куратором організації
3. Зайдіть в Мій кабінет та натисніть на Мої організації

Фактичний результат:
3. Вміст полів: "Повна назва організації", "Скорочена назва організації" та "Деталізація адреси організації" змінився на записи верхнім регістром.
![image](https://cloud.githubusercontent.com/assets/11783631/7343634/600dcda2-eccc-11e4-8bdf-00eb6299274f.png)

**Comment by maksimmaksimov** [comment]
Значения перечисленных полей не должны переводиться в верхний регистр. Ошибку исправим.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
![image](https://cloud.githubusercontent.com/assets/11783631/7373004/ab438742-edd2-11e4-984f-8238c2bcdf81.png)
@maksimmaksimov також прошу розглянути наступний кейс:
Користувач при реєстрації вказує своє подвійне ім'я через дефіс наприклад "Анна-Марія" але в процесі проходження реєстрації тільки перша буква залишається з великої літери.
Погоджуюсь, що загалом людей з подвійним ім'ям небагато але все ж вони можуть обурюватись, чи коректна така поведінка ?

**Comment by maksimmaksimov** [comment]
Данное поведение ошибочное. Будет исправлено.

**Comment by maksimmaksimov** [comment]
Исправлено, убрали перевод значений в верхний регистр.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, більше не відображається все верхнім регістром.
![image](https://cloud.githubusercontent.com/assets/11783631/7394864/f3fd6e86-ee9e-11e4-89c8-31ca94863a22.png)
Бага з подвійним ім'ям все ще відтворюється

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Да, ошибку с двойным именем ещё не исправили

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Ошибку с двойным именем исправили.
