### ISSUE TITLE
Public-bid, Підтвердіть будь-ласка, що дане повідомлення для запрошеного користувача вірне.

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#284]
1. Запросіть користувача куратором організації.
2. Перейдіть за посиланням з листа
3. Заповніть всі поля валідними даними
4. Натисніть кнопку продовження реєстрації

Очікуваний результат:
4. Користувач буде повідомлений про те що йому надіслано лист з лінкою для встановлення паролю
Фактичний результат:
4. Користувач отримує повідомлення: "Вітаємо, реєстрацію завершено, бажаємо приємного користування".
![image](https://cloud.githubusercontent.com/assets/11783631/7344407/d825110e-ecd3-11e4-877f-64b6931edcb3.png)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe нет, данного сообщения для приглашенного пользователя быть не должно. Вносим изменения в сообщения при регистрации, будет исправлено.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Ошибка исправлена.
