### ISSUE TITLE
Public-bid, Створення закупівлі. Інформація про організацію відображається не повністю

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#286]
1. Залогуйтесь в систему за користувача з можливістю створювати закупівлі
2. Перейдіть в мій кабінет на сторінку як показано на скріншоті
   ![image](https://cloud.githubusercontent.com/assets/11783631/7346368/3c1c8e0a-ece6-11e4-8cc6-910f406e7186.png)
3. Перейдіть на сторінку створення закупівлі
   ![image](https://cloud.githubusercontent.com/assets/11783631/7346393/7feb574c-ece6-11e4-831f-977e52d3ce2d.png)
   Очікуваний результат:
   Дані про Країну та Область повинні відображатись при створені закупівлі
   Фактичний результат:
   Дані про Країну та Область не відображаються на формі створення закупівлі

**Comment by maksimmaksimov** [comment]
Исправлена.
