### ISSUE TITLE
Public-bid, Як має поводитись система за умови, що куратор (засновник організації, укладач договору) запросив ще одну людину в договір. Потім видалився з системи?

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#287]
1. Залогуйтесь в систему користувачем з угодою де фігурує більше однієї людини в договорі
2. Запросіть ще одну людину в затверджену угоду
3. Залогуйтесь знову за куратора цієї ж угоди з двома людьми та видаліться з системи

Фактичний результат:
Залишилась діюча угода без куратора, проте засновник оргнаізації та куратор тепер відсутній, що повинно відбуватись ?
1. Чи повинен запрошений користувач мати можливість діяти в рамках укладеної угоди ?
2. Чи повинен запрошений користувач ставати куратором даної угоди/організації ?

**Comment by RudDaryna** [comment]
@Mykhailo-Shtabaliuk-SoftServe,
1) Повинен мати змогу діяти в рамках угоди
2) Ні, куратором автоматично його призначено не буде, за необхідності він зможе написати запит до адміністратора, який зможе переназначити куратора.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@RudDaryna Дякую, за розяснення. Закриваю
