### ISSUE TITLE
Public-bid. Вікно підтверженя пропозиції. Відсутьна назва вікна та знак питання вкінці речення.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#288]
![image](https://cloud.githubusercontent.com/assets/11888281/7346842/074ca2c8-eceb-11e4-80b0-e617556dd9b5.png)
1. Знаходим закупівлю в статусі період прийому пропозицій.
2. Відкриваєм закупівлю
3. Заповняєм всі обов"язкові поля
4. Натискаємо Зареєструвати пропозицію

Очікувано: 
а) В кінці запитання знак "?"
б) Вікно запитання має заголовок 

Фактично:
а) В кінці запитання немає знаку "?"
б) Вікно запитання не має заголовок

**Comment by maksimmaksimov** [comment]
@w-be заголовка не будет. Знак вопроса добавим

**Comment by maksimmaksimov** [comment]
Знак вопроса добавили.
