### ISSUE TITLE
Public-bid, Користувач який належить до організації в статусі Неактивний, може створювати та оголошувати закупівлі

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#291]
1. Перейдіть за посиланням https://public-bid.com.ua/
2. Залогуйтесь за користувача:
   login: misha.a@meta.ua
   password: Password3
3. Зайдіть в Мій кабінет та переконайтесь, що організація "МІШААМЕТАЮА" в статусі Неактивний
   ![image](https://cloud.githubusercontent.com/assets/11783631/7366048/2d2d8f1c-ed9e-11e4-921e-213823a55ac6.png)
4. Перейдіть на Закупівлі, та оберіть фільтр Мої закупівлі
   ![image](https://cloud.githubusercontent.com/assets/11783631/7366120/a4d8baf0-ed9e-11e4-86da-7ff0ffe2b0e4.png)

Фактичний результат:
4. UA-2015-04-28-000020 - ви бачите закупівлю створену та оголошену від організації в статусі Неактивний
Очікуваний результат:
4. Закупівля неповинна бути доступною для оголошення або взагалі для створення.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Подскажите, пожалуйста код угоди и какой статус угоди? Статус организации не влияет на возможность создания и объявления закупок. Проверяется статус угоди

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov номер угоди 440, статус угоди Підтверджений

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe угода подтверждена - объявление закупок разрешено.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov добре, дякую за розяснення. Закриваю.
