### ISSUE TITLE
Public-bid. Створення закупівлі. В додатковому предметі закупівлі повідомлення про обов'язкові поля містить лишній текст.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#292]
![image](https://cloud.githubusercontent.com/assets/11888281/7366224/54f6b144-ed9f-11e4-8e60-dc53cc09e96f.png)
1. Натиснути Нова закупівля.
2. Натиснути в Деталях закупівлі Додати предмет
3. Заповнити обов"язкові поля до Додаткового предмету
4. Натиснути Зберегти

Очікувано: З'являються повідомлення: "Поле обов'язкове для заповненя".

Фактично: З'являються повідомлення типу: "mForm:data:j_idt1912: Поле обов'язкове для заповненя".

**Comment by maksimmaksimov** [comment]
@w-be Ошибка известна. Будет исправлена.

**Comment by maksimmaksimov** [comment]
Были переделаны сообщения пользователю. Ошибка исправлена.
