### ISSUE TITLE
Public-bid, При спробі оновоити прикріплений файл до закупівлі в періоді уточнень, відображається некоректне ім'я файлу

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#293]
1. Перейдіть за посиланням https://public-bid.com.ua
2. Залогуйтесь за користувача з можливістю створювати закупівлі
3. Створіть закупівлю та дочекайтесь до статусу Період уточнень
4. Зайдіть на картку закупівлі та оновіть прикріплений файл, файлом з іншим іменем.

Очікуваний результат:
4.Попередньо прикріплений файл буде відображено, як перекреслений, а імя нового файлу буде відображатись.
Фактичний результат:
4. Імя попереднього файлу перекреслюється і зявляється знову те саме ім'я, а не дійсне імя нової версії файлу.
![image](https://cloud.githubusercontent.com/assets/11783631/7366412/bf3a9614-eda0-11e4-8677-93865bf915e0.png)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Не является ошибкой, первый файл, который был загружен, попадает в ЦБД, и при обновлении изменить название уже нет возможности, т.к. в ЦБД отсутствует возможность удаления файлов.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov тобто, якщо я спершу завантажив файл, з розширення *.doc, а потім почались запитання і я замінив файл на *.xls де добавив уточняючі параметри, то файл для всіх буде видимий як *.doc і ніхто його просто непрочитає.
Це коректна поведінка ?

**Comment by maksimmaksimov** [comment]
Уточню у разработчиков.

**Comment by maksimmaksimov** [comment]
Ошибка. Будет исправлена.

**Comment by maksimmaksimov** [comment]
Исправлено
