### ISSUE TITLE
[Public-bid] [Оцінка учасника] Кандидат немає можливості додати кваліфікаційні документи через відсутність контролів

### ISSUE THREAD

**Issue by MaryanaDemtsyukh-SoftServe** [openprocurement/frontend#294]
Веб-браузер: Google Chrome v.42.0.2311.90; Mozilla Firefox 37.0.2
Передумови: користувач зареєстрований і авторизаний у системі (pavlo.ukrop@outlook.com <Password1>), подав пропозицію на участь в аукціоні, успішно відбувся аукціон, користувач зареєстрований як кандидат на перемогу, відповідний електронний лист прийшов на адресу користувача
Кроки для відтворення:
1. Відкрити електронний лист про рестрацію кандидата на перемогу (pavlo.ukrop@outlook.com <Password123456>
2. Перейти за посилання щоб доповнити кваліфікаційну пропозицію
-> Відкривається Картка пропозиції
3. Перейти до Кваліфікаційної інформації

Фактичний результат: у розділі Кваліфікаційна інформація відсутні контроли щоб додати документи (див.скріншот).
Очікуваний результат: розділі Кваліфікаційна інформація повинен містити відповідний контрол щоб коритувач мав змогу додати необхідні документи, про які йдеться у електронному листі.

![default](https://cloud.githubusercontent.com/assets/11995699/7366692/c016b818-eda2-11e4-99bc-52aa51f7f6a0.png)

**Comment by maksimmaksimov** [comment]
@MaryanaDemtsyukh-SoftServe ссылки из уведомлений ведут на форму предложения без авторизации. Для того чтобы добавить предложение надо авторизоваться и найти свое предложение.

**Comment by maksimmaksimov** [comment]
Данное замечание не является ошибкой, просьба закрыть.
