### ISSUE TITLE
[Public-bid] [Оцінка учасника] Замовник не може дискваліфікувати або присвоїти звання переможця аукціону якщо попередньо не додав рішення тендерного комітету

### ISSUE THREAD

**Issue by MaryanaDemtsyukh-SoftServe** [openprocurement/frontend#295]
Веб-браузер: Google Chrome v.42.0.2311.90; Mozilla Firefox 37.0.2
Передумови: користувач зареєстрований і авторизаний у системі Замовником (petro.ukrop@outlook.com <Password1>), оголосив закупівлю, учасники подали пропозиції, успішно відбувся аукціон, закупівля перебуває в статусі Кваліфікація переможця
Кроки для відтворення:
1. Перейти в Мій кабінет
2. Вибрати Мої закупівлі
3. Знайди закупівлю № UA-2015-04-28-000015 
4. Перейти в картку закупівлі
5. Вибрати Результати аукціону
6. Вибрати Учасники аукціону
7. Вибрати Оцінити
8. Вибрати Присвоїти звання переможця аукціону
-> повідомлення "Ви не додали рішення тендерного комітету" відображається
9. Вибрати Завантаження рішення і додати валідний файл

Фактичний результат 1:  після завантаження рішення кнопки "Дискваліфікація учасника" та "Присвоїти звання переможця аукціону" залишаються неактивними (див.скріншот). Замовник має можливість або зберегти оцінку або вийти.
Очікуваний результат 1: після завантаження рішення кнопки "Дискваліфікація учасника" та "Присвоїти звання переможця аукціону" повинні стати активними і Замовник повинен мати можливість оцінити учасника.
![default](https://cloud.githubusercontent.com/assets/11995699/7367822/0c319a62-edab-11e4-9c07-675429dffa12.png)
10. Вибрати Зберегти оцінку
Фактичний результат 2: відображається повідомлення про загальну помилку (див. скріншот)
Очікуваний результат 2: повідомлення про загальну помилку не повинно відображатись; Замовник не повинен мати змоги зберігати оцінку якщо учасник не дикваліфікований або не призначений переможцем аукціону.
![default](https://cloud.githubusercontent.com/assets/11995699/7367827/13bb1d3a-edab-11e4-813d-372aff288507.png)

**Comment by maksimmaksimov** [comment]
@MaryanaDemtsyukh-SoftServe Загальна помилка - это проблема нехватки места на сервере БД, сейчас решаем эту проблему.

**Comment by maksimmaksimov** [comment]
@MaryanaDemtsyukh-SoftServe По сценарию оценки кандидатов заказчиком, в нашей системе реализовано следующим образом:
1.Если необходимо дисквалифицировать участника, необходимо а) открыть форму "Результаты оценки"; б) прикрепить документ в) нажать кнопку "Дискваліфікувати учасника"; г) выбрать причину (причины) дисквалификации; д) сохранить изменения.
2.Для присвоения звания победителя, необходимо а) открыть форму "Результаты оценки"; б) прикрепить документ; в) нажать на кнопку "Присвоїти звання переможця"; г) сохранить изменения.
Т.е. по описанному вами сценарию, когда пользователь нажал на кнопку "Присвоїти звання переможця" (из шага 8) кнопка "Дискваліфікувати учасника" уже не может быть активной, т.к. мы пытаемся в данном случае определить победителя.

**Comment by maksimmaksimov** [comment]
@MaryanaDemtsyukh-SoftServe а ещё вопрос, откуда такое требование:
Очікуваний результат 2: Замовник не повинен мати змоги зберігати оцінку якщо учасник не дикваліфікований або не призначений переможцем аукціону.
?
По описанному мной сценарию, пользователь либо выбирает победителя, либо дисквалифицирует участника - и он должен иметь возможность сохранить оценку.

**Comment by maksimmaksimov** [comment]
@MaryanaDemtsyukh-SoftServe Загальной помилки уже быть не должно.

**Comment by MaryanaDemtsyukh-SoftServe** [comment]
Дякую за уточнення сценарію оцінки учасників Замовником.
Суть дефекту полягає в певній невідповідності:  форма оцінки учасників не дозволяє користувачеві продовжити наступнії дії щодо оцінки якщо не доданий обов'язковий файл (так як кнопки неактивні), а натомість форми реєстрації користувачів та створення закупівель дозволяють "повертатись" щоб заповнити/редагувати обов'язкові поля і дозволяють завершити дії.

**Comment by maksimmaksimov** [comment]
Не совсем так, если вы при оценке кандидата нажали на кнопку "Дискваліфікувати учасника" или "Присвоїти звання переможця" и перед этим не добавили документ - вы можете документ добавить, после чего сохранить результаты оценки.
Т.е. форма оценки позволяет пользователю продолжить следующие действия по оценке, если не был добавлен обязательный файл - кнопки перестают быть активными, т.к. мы уже перешли в один из режимов - "Дисквалификация" или "Присвоение звания победителя"

**Comment by maksimmaksimov** [comment]
Данное замечание не является ошибкой, просьба закрыть.
