### ISSUE TITLE
Public-bid, Мій кабінет, Зміна паролю, з'являється незрозуміле повідомлення про помилку

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#296]
1. Залогуйтесь в систему https://public-bid.com.ua
2. Перейдіть в Мій кабінет > Натисніть змінити пароль
3. Заповніть поля:

Поточний пароль: "Password1" - має бути недійсним паролем
Новий пароль: "Password2"
Підтвердження пароля: "Password3"
Натисніть кнопку змінити пароль (Зявляється повідомлення про те що паролі не співпадають)
4. Заповінть поля:

Поточний пароль: "Password1"
Новий пароль: "Password2"
Підтверждення: "Password2"
Натисніть кнопку Змінити пароль
Результат зображено на скріншоті:
![image](https://cloud.githubusercontent.com/assets/11783631/7371772/9993ffec-edcb-11e4-8fed-a45fe646f898.png)

**Comment by maksimmaksimov** [comment]
Ошибка известна, на данный момент проводятся работы по устранению.

**Comment by maksimmaksimov** [comment]
Ошибка исправлена.
