### ISSUE TITLE
Public-bid, Підтвердіть будь ласка, що користувач при реєстрації має мати можливість вибрати Неактивну організацію та продовжити реєстрацію

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#297]
1. Перейдіть на https://public-bid.com.ua
2. Натисніть Реєстрація/Вхід > Я новий користувач
3. Введіть валідні дані та натисніть Далі
4. Введіть код ЄДРПОУ організації зі статусом "Неактивний"
5. Натисніть Продовжити реєстрацію

Фактичний результат:
5. Користувачеві з'являється повідомлення про те що "Угоду успішно зареєстровано. Ключ надіслано на Вашу електронну адресу!"

**Comment by maksimmaksimov** [comment]
Пользователь может выбирать неактивную организацию. Требованиями это не запрещено.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov якщо я правильно розумію, то такі угоди в подальшому має заблокувати або просто не підтвердити адміністратор ?

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe все верно, так и есть

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Дякую, зрозуміло. Закриваю
