### ISSUE TITLE
Public-bid, Якщо користувач спочатку зареєструвався, як спостерігач, а потім дореєстрував Мульти Угоду то він має можливість створювати і оголошувати закупівлі без будь-яких підтверджень Адміністратора

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#298]
Пройдіть тест сценарій який показано на скріншотах:
1. Перейдіть по посиланню https://public-bid.com.ua/
2. Натисніть кнопку Реєстрація/Вхід
3. Заповніть поля:
Ваш унікальний e-mail: misha.observer@meta.ua
Прзівище, Ім'я та по батькові: Споглядач Михайло УгодоСпостерігачович
Тип угоди: Угода спостерігача
4. Натисніть Далі
5. З отриманого листа візьміть ключ-доступу та завершіть реєстрацію
6. Зайдіть в систему та переконайтесь, що ви спостерігач та вийдіть
7. Перейдіть на форму реєстрації, таку ж яка описана в кроці 2
8. Заповніть поля:
Ваш унікальний e-mail: misha.observer@meta.ua
Прзівище, Ім'я та по батькові: ЗамСпоглядачча Михайла МультиСпостерігачович
Тип угоди: Мульти-угода
9. Натисніть далі та завершіть реєстрацію
10. Залогуйтесь в систему, створіть закупівлю та оголосіть
11. Зайдіть в Мій кабінет та перейдіть на вкладку Діючі угоди

Очікуваний результат:
10. Користувач не повинен мати змогу створювати закупівлі та оголошувати її, поки він не підтверджений адміністратором (угода, та організація в статусі Тимачасовий)
11. Діючі угоди повинні бути зареєстровані на імена та прізвища користувачів, які вказувались при реєстрації угоди
Фактичний результат:
10. Користувач має змогу створити та оголосити закупівлю, не зважаючи на те, що його Угода і Організація знаходяться в статусі Тимчасовий
11. Діючі угоди зареєстровані на першого користувача який підтверджував угоду тільки Спостерігача.

В моїй голові я бачу наступний сценарій:
Існує компанія з корпоративною поштою misha.observer@meta.ua:
1. Директор компанії каже одному з працівників, йди зареєструйся, як спостерігач на цьому сайті подивись, яким чином там все працює.
2. Працівник реєструється на сайті з корпоративним емейлом з угодою спостерігача.
3. Проходить час і він підтверджує директору компанії, що там все прозоро зрозуміло, чітко розписаний процес торгівель, закупівель і тоді директор вирішує сам реєструється на цьому ж таки сайті використовуючи ту саму корпоративну електронну пошту.
4. Після реєстрації, директор не розуміє, чому йому не прийшов лист 
![image](https://cloud.githubusercontent.com/assets/11783631/7392628/add95e4a-ee91-11e4-9437-fe2fce4eb0cc.png)
5. Кличе працівника і з'ясовує, що пароль до даної електронної пошти вже встановив його працівник, коли раніше реєстрував угоду спостерігача.
6. Директор компанії заходить в систему в Мій кабінет і бачить наступну картину:
Організація його є, договір його присутній але зареєструвалось усе чомусь на ім'я та прзівище працівника(спостерігача)
Що побачити цей сценарій повністю з середини пропоную зайти в систему:
misha.observer@meta.ua
Password1 - пароль однаковий і на електронній пошті і в системі
При необхідності можу добавити скріншоти з послідовною реєстрацію, де при реєстрації вказуються різні Імена і Прізвища.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe По требованиям к системе:
1) Пользователь может иметь сколько угодно договоров с площадкой паблик-бид;
2) Тимчасовий пользователь имеет право создавать закупки. Объявлять не может - и я это проверил, действительно объявление закупки запрещено.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov 
Так у тому то й справа, що користувач який спостерігач зразу заходить в систему і він має статус підтвердженого, а не Тимачсового.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Такое требование у нас к системе

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Через цю вимогу, з'являється діра в системі, користувач стає підтвердженим бо він спостерігач, реєструє собі додаткову мульти-угоду і при тому залишається підтвердженим і може створювати і оголошувати закупівлі.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe проверю эту дыру.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe  Также добавлю по этому пункту:
"4. Після реєстрації, директор не розуміє, чому йому не прийшов лист "
От вас уже поступало подобное замечание и на данный момент проводятся работы по исправлению.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov так, я вже заводив цю помилку і нагадую про неї ще раз оскільки в окремому питанні https://github.com/openprocurement/frontend/issues/253 останній комент каже, що вона виправлена.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe мы помним

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe По данному замечанию:
1) Ситуацию, когда пользователь зарегистрировался как наблюдатель, а потом зарегистрировал мульти-договор поправили, теперь объявлять закупки нет возможности.
2) По поводу того, что во втором договоре указано ФИО первого пользователя - такая логика работы нашей системы, в таблице пользователей создается запись, в приведенном вами примере это: misha.observer@meta.ua с ФИО Споглядач Михайло УгодоСпостерігачович. И когда вы создаете на эту же почту нового пользователя, в БД новая запись не создается, а берется существующая.
Т.е. предполагается что связка "email - username" должна быть уникальной при регистрации договоров.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov стосовно першого зауваження:
1. Перевірено, тепер користувач який був Підтвердженим добавивши нову угоду стає знову Тимчасовим. - це виправило ситуацію.
2. Перевірено також, якщо користувач був спостерігачем, а потім був запрошеним в Мульти-угоду також стає Тимчасовим, після того його призначили куратором.
3. Користувач який тільки но став куратором видаляє з угоди людину яка, взяла його в угоду.
4. Самий перший користувач, залишається в статусі Тимчасовий і тільки з угодою спостерігача, що виглядає мені трохи некоректним.
Іншими словами, коли користувач з Спостерігача стає ще кимось він стає Тимчасовим, а коли повертає собі єдину роль Спостерігача назад Підтвердженим не стає.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe на самом деле в этой ситуации только пользователь является Тимчасовим, его договор является Підтвердженим. А подтверждать пользователя может только администратор.
