### ISSUE TITLE
Не відбулося перепланування тендеру при "збої" в ЦБД

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#30]
1-ЕЛЕГ-СВ-02
торги находятся в статусе "Аукцион" по состоянию на 24.01.15 12:02
При переходе по ссылке на страницу аукциона видим, что аукцион завершился накануне, в 16:42

**Comment by myroslav** [comment]
Тендер `699dc15d9c9947999c6e83121729a714` має відбутися о 2015-01-23T16:15:00+02:00 і це пов'язане з тим, що ЦБД не працювала вчора, в той момент, коли мав відбуватся аукціон (не вдалося результати аукціону внести в ЦБД), відповідно ЦБД його перепланувала "через добу". Що буде сьогодні в 16:15 - це треба "дожити" :) і побачимо, чи аукціон відбудеться знову.

**Comment by andriykucherenko** [comment]
Виходить, така позаштатна ситуація у нас некоректно відпрацьовує.
На Майданчику дата стара: https://my.prom.ua/cabinet/purchases/state_purchase/view/462
І на сторінці аукціону все вже відбулось: http://auction-sandbox.openprocurement.org/tenders/699dc15d9c9947999c6e83121729a714
тільки фактичного "Розкриття" не відбулось в кінці аукціону

**Comment by myroslav** [comment]
З точки зору ЦБД - стан є "очікування результатів аукціону", є неточність, що http://auction-sandbox.openprocurement.org/tenders/699dc15d9c9947999c6e83121729a714 показує результати попередньої спроби, а мав би показувати "попрожній" аукціон, ми з цим розберемося.

**Comment by myroslav** [comment]
Є більше інформації: не відпрацював механізм перепланування у випадку "позаштатної ситуації". Зараз розбираємося чому, чи через те, що коли відбувалося перепланування не працювала ЦБД, чи через те, що тендер мав "турбо режим"...

**Comment by myroslav** [comment]
Оскільки в момент закінчення аукціону не працювало API, то він не мав можливості повернути результату, відповідно аукціон вважається таким, який не відбувся, і має відбутися його перепланування, щоб його провести ще раз.

Підтверджено помилку в функціоналі перепланування (він не мав обробки випадку "API недоступне").

**Comment by myroslav** [comment]
Конкретно цей тендер ми вчора ввечері "штовхнули", і аукціон відбувся, тендер перейшов в кваліфікацію. Цей issue я закрию, коли ми виправимо код, щоб такого більше не траплялося.
