### ISSUE TITLE
Public-bid, Скажіть будь ласка, якщо закупівля в статусі "Завершена закупівля" чи повинна бути реалізована перевірка на коректніть дати підписання договору ?

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#300]
![image](https://cloud.githubusercontent.com/assets/11783631/7410846/4d416014-ef3b-11e4-85e5-65c09f0f8af1.png)
На даний момент така перевірка відсутня і гіпотетично замовник може переплутати день підписання договору і поставити там дату, на тиждень раніше від сьогоднішнього дня.
Також скажіть будь-ласка чи повинна бути реалізована нотифікація переможця через емейл, з приблизним текстом: "Вам призначили дату підписання договору, ознайомтесь будь ласка з договором"

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Требованиями к системе не предусмотрены подобные нотификации.
Проверка даты подписания договора, также не предусмотрена требованиями.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov Дякую за відповідь. Закриваю.
