### ISSUE TITLE
Public-bid, Реєстрація користувача. Користувач зависає на другому етапі реєстрації з ключем доступу, без жодних повідомлень про помилку

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#301]
1. Перейдіть за посиланням https://public-bid.com.ua/
2. Натисніть кнопку Реєстрація/Вхід
3. Пройдіть процедуру реєстрації до отримання ключа доступу
4. Введіть всі дані як показано на скріншоті та настисніть кнопку Продовжити реєстрацію
   ![image](https://cloud.githubusercontent.com/assets/11783631/7411418/8695db1a-ef40-11e4-82b6-300d5eb97e04.png)

Очікуваний результат:
4. Користувач продовжить реєстрацію
Фактичний результат:
4. Або кнопка не функціональана або користувача не повідомляється про те що далі має відбуватись, він залишається на цій же сторінці.

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe Просьба повторно выполнить регистрацию, должна работать.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@maksimmaksimov перевірено, вже пропускає далі. Закриваю
