### ISSUE TITLE
Public-bid, Період уточнень. Якщо завантажити файл, та одразу ж оновити старий файл. Завантажений файл зникає без попереджень/повідомлень

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#302]
1. Залогуйтесь в систему за користувача:
   login:  misha.uch@meta.ua
   password: Password1
2. Перейдіть до закупівлі UA-2015-04-30-000040
3. Завантажте файл будь-якого формату - не натискаючи кнопку Зберегти
4. Оновіть файл який існував раніше, а не був тільки но завантажений
5. Натисніть кнопку Зберегти

Очікуваний результат:
5. Файл який було завантажено, та файл який було оновлено повинно відображати
Фактичний результат:
5. Файл який було оновлено успішно збережено. Файл який було завнтажено зник без будь-яких повідомлень

**Comment by maksimmaksimov** [comment]
Ошибка будет исправлена.

**Comment by maksimmaksimov** [comment]
Ошибка исправлена

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Бага описана в першому сценарії вже пофіксана. Перевірено.
Виникла наступна бага:
1. Створіть тендер і дочекайтесь до періоду уточнень
2. Завантажте 1 документ та збережіть
3. Завантажте ще 1 документ 
4. Оновіть перший файл який був завантажений, та спробуйте оновити другий 

Очікуваний результат:
Файл буде оновлено або проніформовано мене, як користувача, що я повинен спочатку зберегти закупівлю, а тоді я зможу оновити інший файл
Фактичний результат:
Користувач отримує повідомлення про загальну помилку, та навіть після зберігання закупівлі оновити можна тільки файл, який був вже оновлений, а інші файли оновити неможливо
![image](https://cloud.githubusercontent.com/assets/11783631/7588304/f2db7eaa-f8c4-11e4-99ac-3457e3bd8c07.png)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe ошибку с "Загальной помилкой" исправили.
