### ISSUE TITLE
Public-bid, Неможливо переглянути результати аукціону з розгорнутої картки закупівлі

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#303]
1. Залогуйтесь в систему https://public-bid.com.ua/

login: misha.uch@meta.ua
password: Password1
2. Знайдіть аукціон UA-2015-04-30-000049
3. Розгорніть аукціон та натисніть кнопку Відкрити детальну інформацію
4. На картці закупівлі натисніть кнопку Результати аукціону
![image](https://cloud.githubusercontent.com/assets/11783631/7468527/65726e14-f312-11e4-964b-62ffdf95b826.png)

Очікуваний результат:
4. Користувач (учасник) повинен побачити результати аукціону
Фактичний результат:
4. Кнопка не виконує жодних функцій

**Comment by maksimmaksimov** [comment]
По неизвестным причинам кнопка "сломалась". Ошибка будет исправлена.

**Comment by maksimmaksimov** [comment]
Ошибка исправлена.
