### ISSUE TITLE
Неткаст. Кабінет Редагуваня Профіля. Неможливо завантажити лого компанії.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#305]
http://www.dz2.byustudio.in.ua/cabinet/profile
1. Залогінитись
2. Натиснути профіль
3. Прокрутити сторінку в низ
4. Натиснути Додати файл
5. Вибрати невеликий графічний файл (jpeg)
6. Натиснути кнопку Зберегти

Очікувано: В контролі Аватар залишається завантажена картинка. 

Фактично: В контролі Аватар стандартна картинка порожнього аватару. Ще й активна функція видаленя аватару.
![image](https://cloud.githubusercontent.com/assets/11888281/7472433/4c370fee-f33b-11e4-9be3-e9cc883ce025.png)

**Comment by kvskkvsk** [comment]
Исправлено
