### ISSUE TITLE
Неткаст. Кабінет та Логін. Лишні символои на панелі головного меню.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#306]
http://www.dz2.byustudio.in.ua/cabinet/notices
1. Залогуйтесь
2. Перейдіть до сторінки Повідомлення

Очікувано: На панелі меню Повідомлення під заголовком: а) порожньо; або б) знаходиться пояснювальний текст.

Фактично: На панелі меню Повідомлення під заголовком знаходяться лишні символи: "ві"
![image](https://cloud.githubusercontent.com/assets/11888281/7473638/4fa8440e-f345-11e4-9513-d483d01e0139.png)

Така ж поведінка на 
Кабінет-Налаштування:
![image](https://cloud.githubusercontent.com/assets/11888281/7473665/727b8072-f345-11e4-9e46-3a7615824b8d.png)
Логін:
![image](https://cloud.githubusercontent.com/assets/11888281/7473680/89ed59f6-f345-11e4-8b2b-2cf77f442b28.png)

Також лишні літери на Профіль- Коротко про організацію
![image](https://cloud.githubusercontent.com/assets/11888281/7473983/588f8c24-f347-11e4-93b8-2fd87104dd5a.png)

**Comment by hkhim** [comment]
Також на сторінці реєстрації: http://www.dz2.byustudio.in.ua/registration
![_ 2](https://cloud.githubusercontent.com/assets/12292248/7511892/400e33f6-f4b1-11e4-8a95-f7ac0b8c3e30.png)

**Comment by PaulBoroday** [comment]
Недоработанное исправили. Остальное - это "заглушки" под контент, который сейчас пишется
