### ISSUE TITLE
Неткаст. Кабінет. Повідомлення. Некоректний текст про відсутність повідомлень.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#307]
http://www.dz2.byustudio.in.ua/cabinet/notices

Передумова: У користувача не повинно бути повідомлень.
1. Залогінтесь
2. Перейдіть повідомлень
Очікувано:
Як і на їнших сторінках відображено текст:"Наразі немає записів, що відповідали б критеріям пошуку"

Фактично:
відображено код фрази: "?:no notice"
![image](https://cloud.githubusercontent.com/assets/11888281/7474111/f23b13f2-f347-11e4-90a6-be54dbd56c19.png)

**Comment by PaulBoroday** [comment]
Fixed
