### ISSUE TITLE
NewTend, Створення тендера, незвичний функціонал меню вибору класифікатора

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#309]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Перейдіть на сторінку створення закупівлі http://dev23.newtend.com/openprocurement/#/create-tender
3. Натисніть по будь-якому полі класифікатор

Очікуваний результат:
Зправа з'являється поле з великим чорним хрестиком в правому верхньому куті, звикла поведінка більшості аплікацій, що цей хрестик повинен закривати вікно. 

Фактичний результат:
В даній реалізації чорний хрестик очищає вміст поля.
Варто було б добавити якесь значення за замовчуванням для цього поля де користувач має вводити імя класифікатора, наприклад: "Введіть ім'я класифікатора" - як це реалізовано для інших полів таких як "Краткое описание предмета закупки"
![image](https://cloud.githubusercontent.com/assets/11783631/7475180/ba882830-f34e-11e4-82d4-47347d9f3540.png)

**Comment by w-be** [comment]
Текст добавили, хрестик лишили великий. 
![image](https://cloud.githubusercontent.com/assets/11888281/8060523/92235f72-0ece-11e5-91e4-2d4a5d782578.png)
