### ISSUE TITLE
Не отображаются торги 1-ПРОМ-АК-02

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#31]
`id`: `dbf161224e6549a9851f761f3565e0cf`

На ПРОМ и ЕЛЕГ они есть. на СМАР - нет.
Статус "тендер не состоялся" - верный (не было подано предложений)

**Comment by DimasSmartTender** [comment]
Можно получить идентификатор тендера в ЦБД?

**Comment by AlexRudenko** [comment]
Андрей, мы включились в работу
Просьба комуницировать и со мной и с Дмитрием

**Comment by myroslav** [comment]
`id`: `dbf161224e6549a9851f761f3565e0cf`

**Comment by DimasSmartTender** [comment]
Я искал именно отмененный тендер, судя по вопросу.
На самом деле в ЦБД статус "active.awarded", у нас он добавлен "23.01.15 13:11".
![image](https://cloud.githubusercontent.com/assets/10280562/5891224/23372eb0-a491-11e4-91d5-09a4a91883ae.png)
![image](https://cloud.githubusercontent.com/assets/10280562/5891240/5ef3711a-a492-11e4-96f6-0842c5d93088.png)

**Comment by myroslav** [comment]
@andriykucherenko: тендер `UA-2015-01-23-000004 (dbf161224e6549a9851f761f3565e0cf)`: `1-ПРОМ-АК-02`  в ЦБД є в статусі `active.awarded` який може означати або те, що очікується підписання контракту, або відкинули всі пропозиції, і йде stand-still період, під час якого можна подати скаргу на рішення про відкидання пропозицій.

Є ставка `ecb6680ccd9a46cea4ff7f0d81bc9d13` по якій є award `6c2f6fdf9edb4e688504024a0bce3d50`, який прийнято, і є contract `8e08f40d47384a4ea99b2f38707d5dec`, який чекає на документи.
