### ISSUE TITLE
NewTend, Створення тендера, одиниці виміру

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#310]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Перейдіть на сторінку створення закупівлі http://dev23.newtend.com/openprocurement/#/create-tender
3. Відкрийте дроп-даун меню для поля одиниці виміру:

Очікуваний результат:
Оскільки слово "Пачка" провідміняли і в нас присутній варіант "Пачок", то потрібно провідміняти всі інші одиниці вимірювання, бо виходить якось дивно якщо замовник буде створювати закупку:
524 "ящик". Чи 2 "послуга" або 2 "місяць"

Фактичний результат:
Одиниці виміру присутні деякі в однині та множині, а деякі ні.

Також варто поправити описку: "тони" замінити на "тонни" або "тонн"
![image](https://cloud.githubusercontent.com/assets/11783631/7475361/cdd01262-f34f-11e4-856e-82ec15150f0c.png)

**Comment by znakharenko** [comment]
Units are syncing with http://opendata.org.ua/dataset/recommended-units-of-measure
