### ISSUE TITLE
Неткаст. Головне меню. Підтвердіть будь-ласка необхідність 2-х виходів на формі.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#311]
http://www.dz2.byustudio.in.ua/cabinet/notices

![image](https://cloud.githubusercontent.com/assets/11888281/7475082/2bf8ec58-f34e-11e4-9b45-28633dc8511e.png)

Прошу розглянути пропозицію видалити іконку виходу (найлівіший контрол в меню).
1. Цей контрол вже є продубльований досить зручним і звичним чином - напис "ВИХІД" найправіший контрол в меню.
2. Зазвичай такі контроли ставлять один справа в верхньому куті біля імені користувача, - спочатку меню якось не звично - тобто перша дія яка пропонується - вилогуватись.
3. Іконка Вихід є видима на логін формі, але при кліку нічого не відбувається.
4. У іконки Вихід немає вспиваючої підказки (тултіп) - Звичніше коли іконки мають тултіпи, так як немажуть містити текст, як наприклад кнопки.

**Comment by PaulBoroday** [comment]
Підтверджую
