### ISSUE TITLE
NewTend, Кваліфікація переможця. Незрозуміло чому на цьому етапі внизу екрану відображається можливість зробити ставку

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#316]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Перейдіть до тендера, аукціон якого вже завершився

Очікуваний результат:
Користувач не повинен бачити можливість робити ставку оскільки аукціон вже відбувся
Фактичний результат:
Користувач бачить можливість зробити ставку по завершенні аукціону
![image](https://cloud.githubusercontent.com/assets/11783631/7490585/7c1a1044-f3ea-11e4-8a63-ea08c058e4d0.png)

**Comment by znakharenko** [comment]
This input was there for testing purposes. Should be fixed now
