### ISSUE TITLE
NewTend, Кваліфікація переможця. Відсутня можливість видалити випадково прикріплений документ

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#317]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Перейдіть до тендера, аукціон якого вже завершився
3. Призначте переможця
4. Натисніть кнопку "Загрузить договор" та прикріпіть файл
5. Спробуйте видалити випадково прикріплений файл

Очікуваний результат:
5. Користувач повинен мати можливість видалити випадково прикріплений файл (теоретично користувач може прикріпити файл вміст якого не призначений для публічного перегляду)

Фактичний результат:
5. Користувач немає можливості видалити випадково прикріплений файл
![image](https://cloud.githubusercontent.com/assets/11783631/7490666/06a59fee-f3eb-11e4-9d96-5b288ba48749.png)

**Comment by znakharenko** [comment]
Same as Issue #330
