### ISSUE TITLE
NewTend, Кваліфікація переможця. Підтвердіть будь ласка, що файл audit.yaml повинен відображатись в тендерній документції після аукціону

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#318]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Перейдіть до тендера, аукціон якого вже завершився
3. Перегляньте документи тендера
![image](https://cloud.githubusercontent.com/assets/11783631/7490713/81047ef4-f3eb-11e4-9153-e9570f61b8f2.png)

**Comment by znakharenko** [comment]
Why it shouldn't be displayed? Documents tab contains all docs uploaded by user (customer), tender docs, qualification docs, contacts etc.
