### ISSUE TITLE
Неткаст. Логін. Не зрозумілий підпис поля підтверження при введені некоректного пароля.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#319]
http://www.dz2.byustudio.in.ua/cabinet
1. На формі логіна ввести неправильний пароль і правельний логін
2. Натиснути кнопку Вхід в кабінет
3. Повторити 3 рази

Очікувано: З'являється поле, яке допомагає залогінитись(нагадати пароль)

Фактично: З'являється поле, яке має підпис-заглушку: "?:u check"
![image](https://cloud.githubusercontent.com/assets/11888281/7492755/f26b5d0c-f403-11e4-88b6-f4da28d78d18.png)

**Comment by PaulBoroday** [comment]
Fixed
