### ISSUE TITLE
Не прошел вопрос ПРОМ-АК-05 к торгам 1-СМАР-АК-04, с ПРОМ на СМАР

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#32]
ID торгов:  53604802633a4dc5abbc93d719313f85 
На ПРОМ я вижу два вопроса к торгам:

![image](https://cloud.githubusercontent.com/assets/9398532/5893072/7b9869ea-a4df-11e4-8cc1-227cd24db80b.png)

в тонком клиента СМАР - только один:
![image](https://cloud.githubusercontent.com/assets/9398532/5893087/f6056278-a4df-11e4-986a-ed35b99f7f16.png)

@myroslav , глянь, плз, у кого проблема?

**Comment by myroslav** [comment]
В ЦБД тільки 1 запитання `53604802633a4dc5abbc93d719313f85`: `"Вопрос СМАР-АК-04"`. Тендер в стані `active.tendering` і не приймає більше запитань. Запитання можна було подавати до `2015-01-25 21:00`.

**Comment by myroslav** [comment]
Імовірно при подачі запитання "вилетіла" наступна помилка, принаймні вона в нас зафіксована о `2015-01-25 17:43:38.735 UTC`:

```
[
   {
      "location":"body",
      "name":"author",
      "description":{
         "contactPoint":{
            "uri":"Rogue field"
         }
      }
   }
]
```

Пов'язано з некоректними даними по автору запитання.

Неуспішність подачі запитання жодним чином не прокомунікувано.

**Comment by darchik** [comment]
Исправлено.
