### ISSUE TITLE
Неткаст. Не реалізована функція зміни пароля, якщо користувач забув пароль.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#320]
http://www.dz2.byustudio.in.ua/cabinet/profile

Загальна практика: надати користувачу тимчасову лінку з можливістю встановленя нового пароля. 

Фактично:
У випадку якщо користувач забув пароль йому надається можливість залогінитись з особистою лінкою. Що впринципі ніяк не допомагає згадати пароль, а просто заміняє спосіб входженя в систему.

Основним недоліком є те що пароль важче скопіювати - він маскований усюди крім як в реєстраційному листі. Лінка ж буде зберігатись десь на робочій станції (в листі).

**Comment by PaulBoroday** [comment]
Реализовано в ЛК пользователя - http://prntscr.com/74bbiq (/cabinet/settings)

**Comment by w-be** [comment]
Просто змінити пароль можливо; неможливо змінити якщо користувач не пм'ятає старий пароль.
![image](https://cloud.githubusercontent.com/assets/11888281/7981065/1b421fd2-0ab5-11e5-9790-1163177d48bc.png)

**Comment by kvskkvsk** [comment]
Добавлена возможность получения старого пароля на СМС

**Comment by w-be** [comment]
Працює добре.
