### ISSUE TITLE
NewTend, Кабінет замовника, підтвердіть будь ласка, що функціонал кабінету ще в розробці

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#321]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Перейдіть за посиланням http://dev23.newtend.com/cabinet/customer
![image](https://cloud.githubusercontent.com/assets/11783631/7493582/e8fc3244-f40a-11e4-82cc-c83a3d1678ce.png)

Очікуваний результат: 
Контроли зображені на скріншоті, повинні бути не в одному рядку
Фактичний результат:
Контроли підкреслені на скріншоті в одному рядку, між ними немає відступу, що може заплутати користувача.

**Comment by znakharenko** [comment]
This is our "commercial" part. We really appreciate if you are willing to test it for us but I don't think you should :)
