### ISSUE TITLE
Неткаст. Картка Закупівлі.При наведені курсора на вкладку Закупівлі вказівник не перетворюється на руку.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#324]
http://www.dz2.byustudio.in.ua/tenders/3381
1. Залогуйтесь як постачальник
2. Натисніть на Закупівлі
3. Відкрийте будьяку закупівлю
4. Наведіть курсор на Закупівлі.

Очікувано: вказівник курсора перетворюється на руку, як і на інших меню, що повідомляє, що при натисканю буде перехід на іншу сторінку.

Фактично: З"являється вертикальна раска як при редагуванні текстових полів.

![image](https://cloud.githubusercontent.com/assets/11888281/7496204/5ea8793e-f41b-11e4-94bc-8c2aa221b7ae.png)

**Comment by PaulBoroday** [comment]
Fixed
