### ISSUE TITLE
Неткаст. Незрозуміла обов"язковість заповнення факсу і веб-сайту замовника

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#325]
У багатьох дрібних замовників сайту нема. Навіщо його вимагати?
Те ж саме про факс. Ви збираєтесь надсилати їм факси?

**Comment by kvskkvsk** [comment]
Эти поля не обязательные. А адрес сайта не компании, а контактного лица (http://api-docs.openprocurement.org/uk_UA/latest/standard/organization.html#contactpoint)

**Comment by w-be** [comment]
Наразі поля Офіційний Сайт і Факс не є обов'язковими до заповнення.
![image](https://cloud.githubusercontent.com/assets/11888281/7981696/5ac431a0-0ab9-11e5-81e3-6083278b8bbe.png)
