### ISSUE TITLE
Неткаст. Не виписані правила оплати

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#326]
![netcast-1- -](https://cloud.githubusercontent.com/assets/9398532/7499048/d76407c8-f42d-11e4-9840-f0be584e8e03.png)

**Comment by w-be** [comment]
@kvskkvsk виглядає ніби цей функціонал забрали з майданчика - підтвердіть, будьласка.

**Comment by kvskkvsk** [comment]
Заказчиком было принято решение, что это излишне в этом месте. Частично эту информацию было перенесено на страницу тендера в состоянии приема предложений. Пользователь ее видит в случае нажатия подачи предложения

**Comment by w-be** [comment]
Дякую, закриваю.
