### ISSUE TITLE
Неткаст. При реєстрації постачальника виводиться "Примірне положення" замовника

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#327]
Тут варто замість примірного положення виводити регламент роботи ВАШОГО майданчика

**Comment by w-be** [comment]
Зараз виводиться договір майданчика.
![image](https://cloud.githubusercontent.com/assets/11888281/7981898/d6885162-0aba-11e5-9dad-540081a36d6b.png)
