### ISSUE TITLE
Неткаст. Реєстрація користувача. Граматична помилка у слові "реєструєтесь"

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#329]
![_](https://cloud.githubusercontent.com/assets/12292248/7511690/899dbf0c-f4af-11e4-9d07-fecbdc84f967.png)
Перейти до http://www.dz2.byustudio.in.ua/registration

**Comment by hkhim** [comment]
Також на сторінці кабінету користувача, коли відправлене зауваження до договору: Договір №1236478907052015-1 на уточнеННі
![_ _](https://cloud.githubusercontent.com/assets/12292248/7512334/f06ff4ca-f4b4-11e4-97d1-04d57f80c9d0.png)

**Comment by hkhim** [comment]
Також подвійна кома у листі підтвердження реєстрації користувача:
![_ _ _](https://cloud.githubusercontent.com/assets/12292248/7512579/acf92a98-f4b6-11e4-80cd-e1ab3acbf165.png)

**Comment by hkhim** [comment]
Також граматична помилка у слові "ОпублікУвати" на сторінці створення закупівлі: 
![_](https://cloud.githubusercontent.com/assets/12292248/7513801/bfa7bec6-f4bf-11e4-9462-99a6f368247d.png)

**Comment by hkhim** [comment]
Зайвий пробіл перед комою у повідомленні після редагування закупки.
1. Перейти на http://dz2.byustudio.in.ua
2. Залогуватися як покупець.
3. Зайти на вкладку "Мої Закупівлі"
4. Вибрати закупівлю > Проскролити сторінку донизу > Редагувати
5. Зробити зміни і зберегти

Актуальний результат:
Пробіл перед комою у повідомленні:
![_ _](https://cloud.githubusercontent.com/assets/12292248/7515607/132901c0-f4d1-11e4-85ef-24f50e57f838.png)

**Comment by hkhim** [comment]
Пропущена буква у мітці на сторінці створення закупівлі
![_ _ _ _](https://cloud.githubusercontent.com/assets/12292248/7516531/ba98a1ac-f4d8-11e4-8766-db9f6e5b2a65.png)

**Comment by PaulBoroday** [comment]
Fixed
