### ISSUE TITLE
NewTend, Підтвердіть будь ласка що  під час створення тендеру, не має бути можливості видалити прикріплений файл

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#330]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Перейдіть до створення тендера
3. Створіть тендер, та перейдіть до прикріплення файлів
4. Прикріпіть файл
5. Спробуйте замінити прикріплений файл

Очікуваний результат:
Попередня версія файлу, мала б бути видалена, оскільки ми ще тільки на етапі створення тендеру
Фактичний результат:
Відсутня можливість видалити випадково прикріплений файл на етапі створення тендеру

**Comment by znakharenko** [comment]
As I know, files couldn't be deleted in any case. You are able to replace it with blank file or something like that. This is requirement from CDB.
