### ISSUE TITLE
NewTend, Тендер > Період уточнень > Оновлені файли через NewTend не відображаються для інших майданчиків

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#332]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Створіть тендер, та прикріпіть до нього два будь-яких файли
3. Перейдіть на https://public-bid.com.ua/ та знайдіть свій тендер по номеру закупівлі > переконайтесь що файли прикріплені через нютенд видимі і доступні
4. Перейдіть на http://uat.e-tender.biz та знайдіть свій тендер по номеру закупівлі > переконайтесь що файли прикріплені через нютенд видимі і доступні
5. Обновіть/замініть прикріплені файли через нютенд
6. Виконайте крок 3 та крок 4

Очікуваний результат:
6. Користувач має побачити оновлені файли
Фактичний результат:
6. Користувач, що створив тендер оновив документацію, а цього ніхто крім нього (користувачів майданчика нютенд) побачити неможе.

![image](https://cloud.githubusercontent.com/assets/11783631/7512302/cb80a66e-f4b4-11e4-8884-5971a51f8f9c.png)
![image](https://cloud.githubusercontent.com/assets/11783631/7512328/ebd225dc-f4b4-11e4-9d35-9fa1203fb721.png)
![image](https://cloud.githubusercontent.com/assets/11783631/7512353/0bbc4670-f4b5-11e4-9f5e-9e3202c205f8.png)

**Comment by znakharenko** [comment]
Are you sure that sync was performed by other clients?
Please check actual data at CDB.

If CDB contains correct data then that's not Newtend issue and it should be reassigned.

**Comment by YuraOvramets-SoftServe** [comment]
Проблема тільки з E-Tender. Неткаст і Public-bid відображають зміни файлів коректно.

![image](https://cloud.githubusercontent.com/assets/12292125/7750380/6cad45b0-ffdc-11e4-9dc2-8ff775b72871.png)

Результати в ЦБД:

![image](https://cloud.githubusercontent.com/assets/12292125/7750397/92880d2e-ffdc-11e4-8d13-ba7f0fcb8bb0.png)

**Comment by S-Shevchenko** [comment]
Дякую.Виправлено
