### ISSUE TITLE
NewTend. Тендер не змінює статус з "Опубликовано" 

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#333]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
1. Створіть тендер з валідними даними
2. Дочекайтесь початку періоду уточнень

Очікуваний результат:
Статус тендера змінився на "Период Уточнений".

Фактичний результат:
Статус тендера завжди "Опубликовано".
![image](https://cloud.githubusercontent.com/assets/12292125/7512394/4b55afc4-f4b5-11e4-93f2-97e69b4c95f2.png)

**Comment by YuraOvramets-SoftServe** [comment]
Зараз статуси змінюються коректно, але є одне питання:

Якщо при створенні тендера в полі "Начало периода уточнений" вказати, н-д завтрашній день, то після збереження статус тендера буде "Уточнение", але по факту ніхто не зможе задавати питання, бо період уточнень починається з завтрашнього дня. Тому було б добре залишати статус  "Опубликовано", поки не настане період уточнень.

**Comment by znakharenko** [comment]
We are mapping CDB statuses, so tender status is active.enquiries and this is equal to our "Уточнение". Will improve this later.

**Comment by SlaOne** [comment]
We got hints to the current statuses, nowadays, so user may see what's going on with tender.
You may find Hints by placing the cursor to "status" field.
