### ISSUE TITLE
Неткаст. Домашня сторінка. Кнопки ВЗЯТИ УЧАСТЬ та ОГОЛОСИТИ АУКЦІОН не працюють для зареєстрованого користувача.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#334]
http://www.dz2.byustudio.in.ua/

![image](https://cloud.githubusercontent.com/assets/11888281/7512149/754f1f42-f4b3-11e4-9951-2fec7a28bbac.png)
1. Залогінтесь зареєстрованим користувачем(наприклад учасником)
2. Натисніть на "ДЕРЖЗАКУПІВЛІ.ОНЛАЙН"
3. Натисніть кнопку ВЗЯТИ УЧАСТЬ

Очікувано: Користувача перекидає на список аукціонів - пропускаючи реєстрацію.
Фактично: Відкривається порожня форма реєстрації.
1. Натисніть на "ДЕРЖЗАКУПІВЛІ.ОНЛАЙН"
2. Натисніть кнопку ОГОЛОСИТИ АУКЦІОН

Очікувано: З"являється повідомленя яке пояснює, що користувач вже зареєстрований як учасник тому не може створювати аукціони; або користувачу пропонується вилогуватись і після підтверженя відкривається працююча реєстраційна форма.
Фактично: Відкривається порожня форма реєстрації.

**Comment by kvskkvsk** [comment]
Работают. Только для зарегистрированных эти страницы выдают 403ю страницу, которая не заполнена текстом.

**Comment by kvskkvsk** [comment]
Исправлено

**Comment by w-be** [comment]
@kvskkvsk kvskkvsk
Кнопка ВЗЯТИ УЧАСТЬ у постачальника 
![image](https://cloud.githubusercontent.com/assets/11888281/8185424/00bf14b6-144d-11e5-8502-7f4eb3aa539f.png)
веде на http://www.dz2.byustudio.in.ua/tenders
![image](https://cloud.githubusercontent.com/assets/11888281/8185487/6430227e-144d-11e5-80a1-01d01d9f165f.png)
а треба, мабуть, на http://www.dz2.byustudio.in.ua/tenders/current

**Comment by kvskkvsk** [comment]
Верно. 
Исправлено.
