### ISSUE TITLE
NewTend. Один і той самий тендер зберігається безліч разів

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#336]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Перейдіть до форми створення нового тендера
3. Заповніть поля валідними даними
4. Клікніть по кнопці "Опубликовать"
5. Коли з’явилось діалогове вікно з запитом на прикріплення документів, клікніть по будь-якому місці на формі.
6. Натисніть кнопку "Опубликовать" знову
7. В діалоговому вікні натисніть "Не будет документов"
8. Перейдіть на головну сторінку

Очікуваний результат:
Тендер створений тільки один раз

Фактичний результат:
Тендер створився два рази (залежить від к-ті повторень кроків 4-5)
![image](https://cloud.githubusercontent.com/assets/12292125/7512794/13f20b7e-f4b8-11e4-94ff-21b57e10e1cc.png)

**Comment by znakharenko** [comment]
Backdrop is disabled, so you are forced to select action in modal dialog.
