### ISSUE TITLE
Неткаст. Реєстрація. Перехід по лінці з правилами та назад стирає всю введену інформацію на формі.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#337]
http://www.dz2.byustudio.in.ua/registration
1. Зайдіть на сайт
2. Натисніть ОГОЛОСИТИ АУКЦІОН
3. Заповніть усі поля
4. Натисніть лянку в "Я погоджуюсь з усіма правилами користування Сайтом ?:confirm all rules2" щоб подивитись правила.
5. Натисніть кнопку бравзера назад.

Очікувано:
З"являється форма еєстрації з внесиною користувачем інформацією.
Фактично: 
З"являється порожня форма еєстрації.

**Comment by PaulBoroday** [comment]
Fixed

**Comment by PaulBoroday** [comment]
Fixed
