### ISSUE TITLE
Неткаст. Немає можливості завантажити на сервер підписаний договір

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#338]
1. Зареєструватися як Покупець.
   Актуальний результат:
   На сторінці кабінету немає можливості завантажити на сайт підписаний договір
   ![default](https://cloud.githubusercontent.com/assets/12292248/7512984/7b9acf12-f4b9-11e4-8c82-955571fd321e.png)

Очікуваний результат:
Має бути можливість завантажити підписаний договір

**Comment by kvskkvsk** [comment]
Не должо быть.

**Comment by PaulBoroday** [comment]
Это наш внутренний документооборот. Он не имеет никакого отношения ни к ЦБД ни к работе с ней.
