### ISSUE TITLE
Неткаст. Неправильний діалог у вікні відміни закупівлі

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#339]
1. Перейти на http://dz2.byustudio.in.ua
2. Залогуватися як Покупець
3. Оголосити закупівлю
4. Зайти на вкладку "Мої Закупівлі" > вибрати закупівлю > проскролити вниз по сторінці > Відмінити закупівлю

Актуальний результат:
З*являється діалогове вікно з неправильним написом (доданий скріншот)

Очікуваний результат:
З*являється діалогове вікно із написом: "Ви впевнені, що хочете відмінити закупівлю?"
![_ _](https://cloud.githubusercontent.com/assets/12292248/7513894/d4a36aae-f4c0-11e4-80cf-03440726a466.png)

**Comment by hkhim** [comment]
Те саме для наступного вікна, яке з*являється після підтвердження діалогу відміни закупівлі:
![_ _ 2](https://cloud.githubusercontent.com/assets/12292248/7514194/e87b9eae-f4c3-11e4-87ae-25cb5ebb22ac.png)

**Comment by PaulBoroday** [comment]
Fixed
