### ISSUE TITLE
Неткаст. Реєстрація. Незачекані чекбокси погодженя з умовама не завжди підсвічуються.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#340]
http://www.dz2.byustudio.in.ua/registration
1. Зайдіть на сторінку.
2. Заповніть всю інформацію крім контактного телефона (не чіпайте чекбокси)
3. Натисніть Зареєструватись (контактний телефон та чекбокси стануть помаранчевими)
4. Введіть підходящий телефон
5. Натисніть Зареєструватись

Очікувано: Контактний телефон стане чорним а чекбокси: 
"Я підтверджую коректність наданої мною інформації
Я надаю згоду на збереження та обробку моїх персональних даних
Я погоджуюсь з усіма правилами користування Сайтом"
Залишуться помаранчевими.

Фактично: Контактний телефон  та чекбокси стають чорними.

Багаторазове натискання на кнопку Зареєструватись призвиде до зміни кольору чекбоксів з чорного на помаранчевий і навпаки.

**Comment by kvskkvsk** [comment]
Исправлено
