### ISSUE TITLE
Неткаст. Неправильна назва лінки на сторінці відміненої закупівлі

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#341]
1. Залогуватися на http://dz2.byustudio.in.ua як Покупець
2. Зайти на вкладку "Мої Закупівлі" (треба щоб була хоча б одна відмінена закупівля, якщо такої нема, то створити і відмінити закупівлю)
3. Вибрати закупівлю зі статусом "Відмінений"
4. Зайти на сторінку відміненої закупівлі > проскролити вниз, де є лінка, яка відкриває вікно з інформацією про закупівлю.
5. Клікнути на лінку

Актуальний результат:
Лінка має неправильну назву:
![_ _](https://cloud.githubusercontent.com/assets/12292248/7514737/cd7c727c-f4c8-11e4-9623-545500b401ee.png)
Коли клікнути на лінку, то у вікритому вікні лейбли також нелокалізовані:
![_ _ _](https://cloud.githubusercontent.com/assets/12292248/7514752/05b1da9c-f4c9-11e4-936f-e72e448e5905.png)

Очікуваний результат:
Всі лінки і лейбли мають українську назву.

**Comment by PaulBoroday** [comment]
Fixed
