### ISSUE TITLE
NewTend. Поля "Бюджет" і "Шаг" дозволяють ввести значення, яке починається з крапки

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#343]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Перейдіть до форми створення нового тендера
3. В поля "Бюджет" і "Шаг" введіть значення, яке починається з крапки (н-д: ".3")
4. Решту полів заповніть валідними даними і опублікуйте тендер

Очікуваний результат:
Поля "Бюджет" і "Шаг" повинні підереслитись червоним кольором і тендер не опублікується

Фактичний результат:
Тендер опобліковується і в полях "Бюджет" і "Шаг" відображаються не коректні значення

![image](https://cloud.githubusercontent.com/assets/12292125/7515504/3b791576-f4d0-11e4-8d1c-c40be36c12cd.png)

**Comment by znakharenko** [comment]
It is possible to enter decimal numbers, they should be cut to two decimals after point.
