### ISSUE TITLE
Public-bid, Період Уточнень. Користувач який задав своє питання не бачить відповіді, отриманої через NewTend

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#347]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Створіть тендер, та дочекайтесь періоду уточнень
3. Залогуйтесь на https://public-bid.com.ua

login: misha.mul@meta.ua
password: Password1
4. Задайте запитання до тендера створеного через нютенд майданчик
5. Дайте собі відповідь через нютенд

Очікуваний результат:
Користувач з майданчику паблік бід повинен бачити отриману відповідь
![image](https://cloud.githubusercontent.com/assets/11783631/7516666/7ecff9da-f4d9-11e4-98e4-109f8a54f6c7.png)
відповідь опрацьована ЦБД, оскільки її відображає http://uat.e-tender.biz/
Фактичний результат:
Користувач з майданчику паблік бід не бачить відповіді
![image](https://cloud.githubusercontent.com/assets/11783631/7516579/05c896e6-f4d9-11e4-8312-8e3226766900.png)

**Comment by maksimmaksimov** [comment]
Будет исправлено

**Comment by maksimmaksimov** [comment]
Исправлено, просьба проверить.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Перевірено, закриваю. Тепер відповіді видимі для користувача, який їх задав.
