### ISSUE TITLE
NewTend, Період уточнень. Відповіді на запитання. Користувач може відповісти на одне запитання декілька раз

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#348]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Перейдіть до свого тендеру, якому задали запитання та натисніть кнопку "Ответить"
3. Дайте відповідь та ще раз натисніть Ответить
4. Повторно натисніть кнопку "Ответить"
5. Повторно дайте відповідь та натисніть "Ответить"
![image](https://cloud.githubusercontent.com/assets/11783631/7516218/661dfdcc-f4d6-11e4-838c-be8fb90364e5.png)
Очікуваний результат:
Кожна наступна відповідь не повинна затирати попередню або взагалі неповинно бути можливо відповідати на одне запитання декілька разів
Фактичний результат:
Кожна наступна відповідь затирає попередню

**Comment by znakharenko** [comment]
Answer works as edit. This is not limited by CDB.
We've improved UI, so previous answer on particular question is placed in the text area.

**Comment by znakharenko** [comment]
@myroslav could you clarify, is it ok that we have edit answer functionality?

**Comment by SlaOne** [comment]
поскольку фактически нет ошибки в таком поведении ответа на вопрос - задачу закрываю, редактировать ответ на вопрос не возбраняется, его можно дополнить или сократить.
