### ISSUE TITLE
Public-bid, Картка закупівлі відображає некоректно прикріплені файли через NewTend

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#349]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Створіть закупівлю через нютенд майданчик та прикріпіть до неї, хоча б два документи(файли)
3. Залогуйтесь в https://public-bid.com.ua/ 
login: misha.mul@meta.ua
password: Password1
Відкрийте вікна, як зображено на скріншоті

Очікуваний результат:
Прикріплені документи будуть відображатись так само, як їх прикріпив користувач на нютенді

Фактичний результат:
Користувач бачить файли, як 5 разів оновлені
![image](https://cloud.githubusercontent.com/assets/11783631/7516874/97e91f36-f4da-11e4-96e5-7c8238fde6b8.png)

**Comment by maksimmaksimov** [comment]
Будет исправлена

**Comment by maksimmaksimov** [comment]
Ошибка исправлена
