### ISSUE TITLE
Неткаст. Лінка на скаргу не працює із сторінки Повідомлень

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#350]
1. Перейти на http://dz2.byustudio.in.ua
2. Залогуватися як Покупець.
3. Перейти на сторінку повідомлень (попередньо створити скаргу)
4. Розгорнути скаргу, натиснувши "Детальніше" і клікнути на "Перейти"

Актуальний результат:
Лінка "Перейти" не працює.
Адреса змінюється з http://www.dz2.byustudio.in.ua/cabinet/notices на http://www.dz2.byustudio.in.ua/cabinet/notices#
![_ _](https://cloud.githubusercontent.com/assets/12292248/7517484/f9ee730e-f4dd-11e4-9047-30d97762ee66.png)

Очікуваний результат:
При натисканні на лінку "Перейти", юзер має перейти на сторінку зі скаргою.

**Comment by kvskkvsk** [comment]
Исправлено для последующих уведомлений
