### ISSUE TITLE
Неткаст. Деталі закупівлі. Обговорення. Контрол скарги зміщується в низ. Тільки ГуглХром та ІЕ11

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#352]
http://www.dz2.byustudio.in.ua/tenders/3385/questions
1. Зайдіть в систему
2. Натисніть на Закупівлі
3. Відкрийте будьяку закупавлю
4. Натисніть на Обговорення

Очікувано: Контрол Скарги залишиться на місці поруч з контролом Обговорення

Фактично: Контрол Скарги переміщується нижче контрола Обговорення
![image](https://cloud.githubusercontent.com/assets/11888281/7518875/47d75218-f4e6-11e4-9503-d3db01e02abf.png)

**Comment by kvskkvsk** [comment]
Исправлено
