### ISSUE TITLE
Public-bid, назва тендера створеного через NewTend не відображається в Public-bid

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#353]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Перейдіть до тенедера UA-2015-05-01-000007
3. Залогуйтесь в https://public-bid.com.ua/
login: misha.mul@meta.ua
password: Password1
4. Перейдіть до закупівлі UA-2015-05-01-000007

Очікуваний результат:
Значення з полів: "Название", "Описание закупки", "Краткое описание" предмета закупки повинні бути видимими для користувачів Public-bid
![image](https://cloud.githubusercontent.com/assets/11783631/7518981/0a4aa8c2-f4e7-11e4-8ff2-60528165e885.png)
Фактичний результат:
Користувачі Public-bid не мають змоги побачити вміст поля "Название"

Вважаю це помилкою майданчика паблік-бід оскільки користувачі майданчику e-tender мають змогу побачити всі три поля http://uat.e-tender.biz/#/tenderDetailes/11a2ce8f424846db8d9e8a11d70afc3f
![image](https://cloud.githubusercontent.com/assets/11783631/7519002/2b478bee-f4e7-11e4-95eb-28a9ab007c10.png)

**Comment by maksimmaksimov** [comment]
@Mykhailo-Shtabaliuk-SoftServe ошибка исправлена, проверить можно будет только на новых закупках.

**Comment by YuraOvramets-SoftServe** [comment]
Створив нову закупівлю, тепер в Public-bid Назва закупівлі завжди "Без назви".

![image](https://cloud.githubusercontent.com/assets/12292125/7729705/ec6633ac-ff1e-11e4-9d3c-23113422c455.png)

**Comment by maksimmaksimov** [comment]
Исправим

**Comment by maksimmaksimov** [comment]
Ошибка исправлена, название закупки отображается
