### ISSUE TITLE
Неткаст. ІЕ10. Некоректне повідомлення при спробі зайти з ІЕ10

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#354]
http://www.dz2.byustudio.in.ua/
1. Спробуйте на сайт майданчику з ІЕ10

Очікувано: а) ІЕ10 не підтримується - відображене повідомленя накшталт: "Ви використовуєте застарілу версію IE. Будьласка встановіть версію 11, або вижче".
б) IE10 підтримується - Сайт відкривається добре.

Фактично:
Сайт не відкривається, з"являється повідомлення що ІЕ7 не підтримується (на англійскій).

**Comment by w-be** [comment]
![image](https://cloud.githubusercontent.com/assets/11888281/7519994/5040a3b8-f4ec-11e4-998b-2dbbd119da12.png)

**Comment by kvskkvsk** [comment]
Исправлено

**Comment by w-be** [comment]
Відтворюється, ще на 2-х робочих станціях, але з 11 версією:
![untitled 4](https://cloud.githubusercontent.com/assets/11888281/7588852/3a8233ae-f8c8-11e4-9542-69a522d6cec5.png)

**Comment by kvskkvsk** [comment]
У нас в IE11 все работает (http://prntscr.com/74nqjm)
Есть ли у вас возможность в вашем IE11 узнать, какие заголовки запроса он отправляет?

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
![image](https://cloud.githubusercontent.com/assets/11783631/7606743/500cf3e8-f964-11e4-96ef-a4fb7e2bc591.png)
@kvskkvsk якщо ви мали на увазі, інші заголовки то уточніть, будь ласка які саме

**Comment by kvskkvsk** [comment]
Именно эти
Только вот (на первой фотке) в строке User-Agent указано, что у вас MSIE 7.0
Ваш браузер не переведен ли в режим совместимости с ИЕ7?

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
![image](https://cloud.githubusercontent.com/assets/11783631/7608638/00d63d4c-f974-11e4-8a18-5ae784355c75.png)
ні, в звичайному режимі

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@kvskkvsk якщо добавите мене в скайп (Mykhailo Shtabaliuk - там таких більше небуло по імені мало б знаходити) тоді зможу надати вам прямий доступ до віртуалки, де це репродюситься

**Comment by kvskkvsk** [comment]
режим для 11 версии нужен Edge (https://msdn.microsoft.com/ru-ru/library/dn255001%28v=vs.85%29.aspx), а у вас 5я

**Comment by kvskkvsk** [comment]
> С помощью параметров совместимости для интрасети: установлен флажок "Отображать сайты интрасети в режиме совместимости" в разделе Параметры просмотра в режиме совместимости.
