### ISSUE TITLE
Неткаст. Чи буде реалізована мультифільтрація у фільтруванні закупівель?

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#356]
1. Залогуватися http://dz2.byustudio.in.ua як Покупець
2. Зайти на сторінку Мої Закупівлі > Поточні Тендери
3. Створити фільтр, наприклад, за кодом ДКПП

Актуальний результат:
Виглядає так, що користувач має можливість застосувати декілька умов для фільтрування завдяки боксу з умовою.
![_](https://cloud.githubusercontent.com/assets/12292248/7533050/935df3d2-f576-11e4-9061-75a4dfd03d06.png)
Підтвердіть, чи буде реалізована мультифільтрація чи користувач зможе застосовувати лише одну умову для фільтру?

**Comment by kvskkvsk** [comment]
Она давно там есть. При выборе необходимо держать нажатой кнопку Ctrl
