### ISSUE TITLE
Неткаст. Не працює пошук по чернетках на сторінці Мої Закупівлі

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#359]
1. Залогуватися у http://dz2.byustudio.in.ua як Покупець.
2. Зайти на сторінку Мої Закупівлі > Поточні Тендери
3. Налаштувати фільтр за статусом "Чернетка" > зробити пошук.
4. Налаштувати фільтр за всіма статусами і ключовим словом > ввести назву закупівлі, яка знаходиться у вкладці "План Закупівель" і має статус "Чернетка"

Актуальний результат:
Пошук за статусом "Чернетка" не виводить значень.
Пошук за ключовим словом закупівлі, яка має статус "Чернетка" не виводить значень.
![_ _](https://cloud.githubusercontent.com/assets/12292248/7533584/58fcd294-f57b-11e4-9a28-3942c4157d3d.png)
![_](https://cloud.githubusercontent.com/assets/12292248/7533590/6393c0e6-f57b-11e4-9cec-83e39d35f0bc.png)
![_ _ 2](https://cloud.githubusercontent.com/assets/12292248/7533592/6801475c-f57b-11e4-9b00-e85cf3f8753e.png)
Очікуваний результат:
Пошук за статусом "Чернетка" виводить закупівлі із статусом "Чернетка"
Пошук із фільтром "Всі статуси" та "за ключовим словом" виводить також закупівлі із статусом "Чернетка".

**Comment by kvskkvsk** [comment]
Исправлено.
Черновики только в черновиках.
Все запланированные тендера тоже являются ченовиками и публикуются автоматом после указанной даты и переходят из плана в текущие.
