### ISSUE TITLE
NewTend. Несвоєчасне відображення нового тендера в списку тендерів

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#360]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Перейдіть до створення нового тендера і заповніть поля валідними даними
3. Натисніть кнопку "Опубликовать"
4. В діалоговому вікні з питанням про додання документів натисніть на Х
5. Перейдіть до списку тендерів

Очікуваний результат:
Новостворений тендер повинен відображатись в списку тендерів

Фактичний результат:
Новостворений тендер не відображається в списку тендерів. Тендер з’явиться після оновлення сторінки з браузера або після переходу на якусь іншу сторінку (н-д: відкрити вже існуючий тендер, Архив...)
![image](https://cloud.githubusercontent.com/assets/12292125/7533651/ea86e4d4-f57b-11e4-884c-c12b690842ab.png)

**Comment by znakharenko** [comment]
Unable to reproduce.
Please recheck and clarify step #5: Перейдіть до списку тендерів

**Comment by YuraOvramets-SoftServe** [comment]
Більше не відтворюється
