### ISSUE TITLE
NewTend, Public-bid, ЕЛЕГ, Запитання та відповіді в періоді уточнень

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#361]
1. Залогуйтесь в будь-який вище згаданий майданчик та створіть закупівлю
2. Дочекайтесь поки закупівля перейде в статус Період уточнень
3. Задайте питання та напишіть відповідь, яка буде містити більше, ніж одну стрічку тексту, наприклад як на скрнішоті
   ![image](https://cloud.githubusercontent.com/assets/11783631/7533889/d7670c10-f57d-11e4-94da-bf19ab41631a.png)

Очікуваний результат:
Повідомлення (запитання або відповідь) повинно відображатись в такому ж вигляді як створювалось, а не бути зліпленим в одну суцільну стрічку
Фактичний результат:
Кожен перехід на наступну стрічку було видалено з повідомлення і ми отримали одну довгу стрічку запитання або відповіді
![image](https://cloud.githubusercontent.com/assets/11783631/7533937/42c975a6-f57e-11e4-8649-7a77ebdef710.png)

**Comment by SlaOne** [comment]
fixed
