### ISSUE TITLE
Неткаст. Неткаст не комунікує з іншими майданчиками

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#362]
1. Залогуватися на http://dz2.byustudio.in.ua як Покупець
2. Створити закупівлю.
3. Залогуватися на http://uat.e-tender.biz/ і зробити пошук за номером створеної закупівлі
4. Залогуватися на https://public-bid.com.ua/ і зробити пошук за номером створеної закупівлі.

Актуальний результат:
Закупівля не відображається на інших майданчиках. Натомість існує інша закупівля під таким же номером і пошук виводить її.
![_](https://cloud.githubusercontent.com/assets/12292248/7534316/338a01ec-f582-11e4-899e-e9f29a89e22d.png)
![e-tender_](https://cloud.githubusercontent.com/assets/12292248/7534319/3d3fdf40-f582-11e4-90ab-f5ada0d1fa6f.png)
![public_bid_](https://cloud.githubusercontent.com/assets/12292248/7534321/3e5ecd82-f582-11e4-92f2-4a367a6e638a.png)

**Comment by kvskkvsk** [comment]
Интересно, а эти 2 другие площадки на какой версии ЦБД работаю? 
www.dz2.byustudio.in.ua на 08.05.2015 работает с версией 0.8, и на локальной копии все приходит.

**Comment by hkhim** [comment]
@myroslav підкажи, будь ласка, на якій версії ЦБД працюють ці два майданчики?

**Comment by myroslav** [comment]
В п'ятницю в обід я просив продуктивні майданчики перемкнути свої Acceptance Testing портали на 0.8. Нажаль я не маю він них feedback-у, чи вони перемкнулися, і щоб це вияснити, треба оголошувати закупівлю через кожен і тоді підглядати, в яку версію вони "пішли"...

**Comment by lerich** [comment]
Мы вчера переключились и почистили uat. Создали тестовые тендеры. Тестируем.

**Comment by hkhim** [comment]
Створила закупівлю UA-2015-05-12-000039 
Закупівлі немає на https://public-bid.com.ua/

**Comment by myroslav** [comment]
Тендер потрапив на 0.8 версію з ID `420a888fc3794855a72df464c15e109b`, і доступний на http://uat.e-tender.biz/#/tenderDetailes/420a888fc3794855a72df464c15e109b (який працює з sandbox v0.8).

**Comment by myroslav** [comment]
На PublicBid я бачу тендер `UA-2015-05-12-000038` з `3ad61af7c73848f3b7c32328000e389c` id, який розміщено в sandbox 0.7

**Comment by w-be** [comment]
@maksimmaksimov Чи плануєти ви перевести Public-Bid на sandbox 0.8? Коли?

**Comment by kvskkvsk** [comment]
Обнаружено, что public-bid.com.ua и http://dev23.newtend.com создают тендера без mode=test следовательно в тестовом режиме на Неткаст этих тендеров нет.

**Comment by znakharenko** [comment]
This option is switchable in NEWTEND, seems you are using user with disabled test mode.

**Comment by w-be** [comment]
Підтвержую: всі вище згадані майданчики в тест середовищі працюють на версії ЦБД 0.8, і мають доступ до всіх закупівель цієї ЦБД.
