### ISSUE TITLE
Неткаст. Чи планується впровадити для користувача можливість вказувати крім дати публікацій і т.п. ще й годину?

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#364]
1. Залогуватися http://dz2.byustudio.in.ua як Покупець.
2. Оголосити Закупівлю > перейти до блоку "Дати та Терміни"

Актуальний результат:
Користувач може вибирати дати, але не має можливості вибирати години.
![_](https://cloud.githubusercontent.com/assets/12292248/7535199/619424f6-f58b-11e4-854a-812abd4ef017.png)
Чи буде реалізована можливість вибирати ще й час, а не лише дати?

**Comment by kvskkvsk** [comment]
Нет, так как согласно правилам ЦБД в рабочем режиме время для всех дат необходимо устанавливать в 16:00

**Comment by hkhim** [comment]
На інших майданчиках є можливість встановлювати час, який хоче користувач:
![etender_ _ _](https://cloud.githubusercontent.com/assets/12292248/7537030/21ef9e62-f59e-11e4-81b4-7657ec04d5fe.png)

![publicbid_date_time](https://cloud.githubusercontent.com/assets/12292248/7537032/27cb0db2-f59e-11e4-803e-53fce26a6243.png)
