### ISSUE TITLE
NewTend, Створення тендера, Поле кількість обрізає дробові числа відкидаючи все що знаходиться після крапки/коми

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#365]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Перейдіть до створення тендеру
3. Створіть закупівлю та в полі "Количество" введіть 1.5 або 1,5 гектарів

Очікуваний результат:
З'явиться повідомлення про те, що в цьому полі можна вводити тільки цілі числа (на інших майданчиках, це поле підтримує також дробові числа)
Фактичний результат:
Дробове число введене в це поле через крапку та через кому автоматично обрізається і закупівельник, який хотів придбати 1.5 гектари землі по факту оголосив закупівлю на 1 гектар землі.

**Comment by w-be** [comment]
Все одно 1 гектар замість 1.5; "1,5" підкреслює червоним.
![image](https://cloud.githubusercontent.com/assets/11888281/8059907/07f06ed8-0ecb-11e5-817d-8a51ed039eae.png)

**Comment by znakharenko** [comment]
Float(decimal) values are prohibited, only integers are allowed.
Could you explain what do you mean under (на інших майданчиках, це поле підтримує також дробові числа)?
Please refer to http://api-docs.openprocurement.org/en/latest/standard/item.html

"quantity:  

integer

OpenContracting Description: The number of units required"

**Comment by w-be** [comment]
Так ви праві - дупустиме тільки ціле значення, на одному іншому майданчику є баг.

**Comment by w-be** [comment]
Однак даний баг варто виправити.
