### ISSUE TITLE
NewTend, Public-bid, E-Tender. Одиниці виміру не стандартизовані між площадками

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#366]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Перейдіть до створення нового тендера
3. В полі "Единицы Измерения" виберіть "ящик"
4. Заповніть решту полів валідними даними і опублікуйте тендер
5. Залогуйтесь в https://public-bid.com.ua/
   login: misha.mul@meta.ua
   password: Password1
6. Перегляньте створений тендер

Очікуваний результат:
Поле "Одиниця виміру" повинно містити "ящик"

Фактичний результат:
Поле "Одиниця виміру" порожнє. Той самий результат і для E-Tender.

Перелік проблемних одиниць виміру:
1. Ящик
2. Блок
3. Гектар
4. Місяць
5. Пачок (на E-Tender відображається як "упаковка")
6. Упаковка
7. Пачка

![image](https://cloud.githubusercontent.com/assets/12292125/7535643/e79a5828-f58f-11e4-883a-502950ad569f.png)

**Comment by znakharenko** [comment]
Seems label should be changed to other client. We are syncing unit names with CDB.

**Comment by YuraOvramets-SoftServe** [comment]
Колеги, звертаюсь до NewTend, Public-Bid і E-Tender.

Чи є можливість якось стандартизувати одиниці виміру? Бо виходить так, що на деяких майданчиках поле Одиниці виміру просто порожнє

**Comment by znakharenko** [comment]
As I've said at https://github.com/openprocurement/frontend/issues/310
We are syncing units with http://opendata.org.ua/dataset/recommended-units-of-measure

**Comment by maksimmaksimov** [comment]
@w-be В public-bid единицы измерения добавили

**Comment by w-be** [comment]
@znakharenko Перепровірив NewTend, послідовно змінюючи одиниці виміру в закупівлі і порівнюючи з рекомендованим списком.
В словнику NewTend є 2 значення: "блок", 2-ге неправильне:
JSON закупівлі: https://api-sandbox.openprocurement.org/api/0.8/tenders/730c1e3a36f3463abda7af99dac21590
![image](https://cloud.githubusercontent.com/assets/11888281/8128139/28a49a8c-1105-11e5-91ac-9e40e161d723.png)

Рекомендований список: https://github.com/openprocurement/openprocurement.api/issues/9 (в кінці)
JSON Visulisation: http://chris.photobooks.com/json/

**Comment by znakharenko** [comment]
@w-be NEWTEND, duplicate "block" unit was removed

**Comment by w-be** [comment]
По NEWTEND більше нема питань по одиницям виміру.
