### ISSUE TITLE
Неткаст. Не працює пошук за номером у вікні визначення класу за ДКПП

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#367]
1. Залогуватися на http://dz2.byustudio.in.ua як Покупець.
2. Зайти на сторінку "Мої Закупівлі" > Поточні Тендери 
3. Налаштувати фільтр даних за кодом ДКПП (або CРV) > натиснути на текстбокс "визначте класи ДКПП" > в рядку пошуку ввести номер ДКПП

Актуальний результат:
Пошук за номером не видає результатів.
![_ _ _](https://cloud.githubusercontent.com/assets/12292248/7536271/18a89554-f597-11e4-8c4f-67f9febf3807.png)

**Comment by PaulBoroday** [comment]
Поиск по номеру не предусмотрен функционалом
