### ISSUE TITLE
ЦБД. Уточніть, будь ласка, який статус має бути у Тендера, коли попередній період закінчився, а наступний ще не почався

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#368]
@myroslav , уточніть, будь ласка, який статус має бути у Тендера, коли попередній період закінчився, а наступний ще не почався, н-д:

Період Уточнень закінчується в 15:30, а період реєстрації пропозицій починається в 15:45.

Наразі статус залишається "Період уточнень", але фактично ми вже не можемо задавати питань і ще не можемо вносити пропозицій.

Питання стосується всіх майданчиків.

**Comment by myroslav** [comment]
Це все ще період уточнень, оскільки в цей час замовник відповідає на заппитання, що були задані в останній момент, і все ще має право вносити зміни в умови тендера (тому це ще називається "період уточнень", оскільки можливі уточнення умов).
