### ISSUE TITLE
Неткаст. Сторінка вантажиться, коли користувач зберігає закупівлю, не заповнивши всі обов'язкові поля.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#369]
1. Залогуватися на http://dz2.byustudio.in.ua як Покупець.
2. Зайти на сторінку "Мої Закупівлі" > вибрати закупівлю і редагувати її.
3. Видалити деякі значення з обов*язкових полів > зберегти

Актуальний результат:
Сторінка вантажиться, зміни не зберігаються.
![_ _](https://cloud.githubusercontent.com/assets/12292248/7536807/c01d242c-f59b-11e4-8a55-01b66bde32cc.png)

**Comment by kvskkvsk** [comment]
Исправлено
