### ISSUE TITLE
Public-bid, Відображає некоректно файли закупівлі, які були завантажені та оновлені через NewTend

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#370]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement

login: openprocurement
pass: test
Пользователь: openprocurement@mailinator.com
пароль: 123123
2. Створіть тендер, прикріпіть до нього два документи
3. Один з них обновіть декілька разів
4. Залогуйтесь в систему https://public-bid.com.ua/
login: misha.mul@meta.ua
password: Password1
5. Відкрийте цей тендер наприклад UA-2015-05-08-000040

Очікуваний результат:
Користувачі паблік біду повинні побачити всі попередні файли, та останню версію оновленого файлу
Фактичний результат:
Користувачі паблік біду бачать, версію файлу, яка була оновлена один раз, а коли файл був оновлений вдруге він вже не видимий для користувачів паблік біду.
![image](https://cloud.githubusercontent.com/assets/11783631/7537228/c342a894-f59f-11e4-900a-25ad8bf5243f.png)

**Comment by maksimmaksimov** [comment]
Ошибка исправлена.

**Comment by YuraOvramets-SoftServe** [comment]
З’явилась нова проблема: 
1. Створити нову закупівлю на NewTend
2. Прикріпити до неї 1 файл
3. Впевнитись, що на Public-bid відображається доданий документ
4. Вернутись на NewTend і замінити існуючий

Очікуваний результат:
Всі зміни відображаються на Public-bid

Фактичний результат:
На Public-bid не відображаються зміни до вже існуючого файла

Зміни відображаються тільки у випадку, коли замінювати файли одразу після створення тендера, тобто коли Public-bid ще не синхронізнувся з ЦБД

![image](https://cloud.githubusercontent.com/assets/12292125/7730255/dafcbae8-ff21-11e4-816b-578cedc2a643.png)

Вміст json:

![image](https://cloud.githubusercontent.com/assets/12292125/7730263/e9c230a8-ff21-11e4-945a-e339f8096d46.png)

**Comment by maksimmaksimov** [comment]
Ошибка исправлена. Уточнение: обновление файла в закупке, созданной на площадке NewTend в Public-bid будет видно не сразу, время ожидания, при тестировании, составило 8-10 минут.
