### ISSUE TITLE
Public-bid. Поле "Замовник", для тендера створеного через NewTend, пусте в Public-Bid

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#371]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Створіть новий тендер з валідними даними
3. Залогуйтесь в https://public-bid.com.ua/
   login: misha.mul@meta.ua
   password: Password1
4. Перейдіть до новоствореного тендера і перегляньте детальну інформацію

Очікуваний результат:
Поле "Замовник" повинно містити коректну назву замовника

Фактичний результат:
Поле "Замовник" порожнє
![image](https://cloud.githubusercontent.com/assets/12292125/7537236/db07ac54-f59f-11e4-968e-d43e6b8539db.png)

**Comment by maksimmaksimov** [comment]
@YuraOvramets-SoftServe У нас по требованиям к системе, поле "Замовник" - это составное значение атрибутов [Фамилия] + [Имя] + [Отчество] из таблицы "Пользователи". Но так как это не наша закупка, в таблице "Пользователи" нет записи о пользователе openprocurement, соответственно в этом поле пусто.
У нас есть только данные, которые приходят от ЦБД:
"contactPoint":{
"telephone":"openprocurement",
"name":"openprocurement openprocurement ",
"email":"openprocurement@mailinator.com"
}
Мы только можем взять значение "name" и записать его в текстовое поле "Відповідальний за закупку".
