### ISSUE TITLE
Неткаст. Поштовий індекс користувача повинен містити лише 5 цифр

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#372]
1. Зайти на http://dz2.byustudio.in.ua
2. Зареєструвати нового користувача, ввести більше, ніж 5 цифр у поле "Індекс"

Очікуваний результат:
Користувач не може ввести більше, ніж 5 цифр у поле "Індекс". З*являється повідомлення, що  Iндекс повинен містити 5 цифр. Користувач не може зареєструватися з невалідними даними.
Те саме при редагуванні профіля існуючого користувача.

Актуальний результат:
Користувач може ввести більше, ніж 5 цифр і зберегти дані.
Те саме при редагуванні профіля існуючого користувача.
![_](https://cloud.githubusercontent.com/assets/12292248/7538413/5959bb26-f5a8-11e4-9d1e-6d030ee16bf6.png)

**Comment by kvskkvsk** [comment]
Исправлено
