### ISSUE TITLE
NewTend->Створення тендера. Клік по найменуванню поля "Классификатор" відкриває список класифікаторів ДКПП

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#373]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Перейдіть до створення нового тендера
3. Клікніть по найменуванню поля "Классификатор"

Очікуваний результат:
Нічого не відбувається, напис не повинен реагувати на клік по ньому

Фактичний результат:
Відкривається список класифікаторів ДКПП
![image](https://cloud.githubusercontent.com/assets/12292125/7539367/2ac71284-f5af-11e4-9c9e-119fa7eb549f.png)

**Comment by neretin** [comment]
This is expected behavior.
http://stackoverflow.com/questions/18432376/what-does-for-attribute-do-in-label-tags
http://www.w3schools.com/tags/att_label_for.asp

**Comment by YuraOvramets-SoftServe** [comment]
Якщо це очікувана поведінка, тоді було б правильно добавити такий же самий напис і для поля Класифікатор CPV, бо якось не логічно, що текстовий напис знаходиться біля поля вибору Класифікатора CPV, а по кліку відкривається список Класифікаторів ДКПП. 
Пропозиція поредагувати існуючий текстовий напис "Классификатор" на "Классификатор CPV" і добавити ще один напис для Класифікаторів ДКПП - "Классификатор ДКПП"
