### ISSUE TITLE
Неткаст. Реєстрація. У деякі поля при реєстрації користувача можливо ввести невалідні дані.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#375]
1. Зайти на http://dz2.byustudio.in.ua > Зареєструватись
2. Заповнити поля пробілами, цифрами або спецсимволами

Очікуваний результат:
Користувач не має змоги ввести на зберегти невалідні дані.
Висвітлюється повідомлення, що введені некоректні дані.

Актуальний результат:
Користувач може ввести невалідні дані (пробіл, цифри і спецсимволи) у наступні поля і вони пройдуть перевірку на валідність:

> Назва юридичної особи
> Населений пункт
> Адреса
> Прізвище
> Ім'я
> По-батькові
> ![_ _](https://cloud.githubusercontent.com/assets/12292248/7539406/79163564-f5af-11e4-9c51-4d5f1df683a7.png)

Замітка:
Якщо ввести у ці поля пробіли, то вони пройдуть валідацію, але користувач не зможе зареєструватися.
Якщо ж ввести цифри або спецсимволи, то користувач зможе зареєструватися.

**Comment by PaulBoroday** [comment]
Fixed

**Comment by hkhim** [comment]
Поля "Назва юридичної особи" та "Адреса" проходять валідацію на пробіли та спецсимволи.
Дані з спецсимволами та цифрами у цих полях можуть бути збережені.

**Comment by PaulBoroday** [comment]
Адрес и название компании - поля, в которых могут быть и пробелы и спецсимволы. Именно эти два поля мы оставляем "на откуп" регистрирующемуся, рассчитвая, что название и адрес он знает лучше нас. Поэтому в этой части считаю валидацию настроенной корректно
