### ISSUE TITLE
Неткаст. Кабінет. Профіль. Користувач може вводити невалідні дані у деякі поля на сторінці зміни профілю.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#376]
1. Залогуватися як Покупець у http://dz2.byustudio.in.ua
2. Зайти на сторінку "Профіль"
3. Ввести цифри або спецсимволи у деякі текстові поля та зберегти зміни.

Очікуваний результат:
Некоректні дані не проходять валідацію і користувач не може зберегти зміни.

Актуальний результат:
Користувач може ввести невалідні дані у наступні поля і зберегти зміни:

> Населений пункт
> Адреса
> ![_ _ _](https://cloud.githubusercontent.com/assets/12292248/7540032/f8b12258-f5b3-11e4-93af-1ef2220db218.png)

Замітка:
Якщо у деякі поля ввести пробіли, то дані проходять валідацію, але зберегти їх користувач не може: з*являється повідомлення: "Це поле необхідно заповнити"
![_ _ _ 2](https://cloud.githubusercontent.com/assets/12292248/7540087/72176396-f5b4-11e4-987b-341b3405c972.png)

**Comment by PaulBoroday** [comment]
Fixed
