### ISSUE TITLE
NewTend->Створення тендера. UI дейтпікера у FF

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#377]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement login: openprocurement pass: test Пользователь: openprocurement@mailinator.com пароль: 123123
2. Перейдіть до створення нового тендеру і клікніть по іконці вибору дати
3. Клікніть по кнопці з назвою місяця і роком

Очікуваний результат:
Замість чисел з’явився перелік місяців, UI дефекти відсутні

Фактичний результат:
Замість чисел з’явився перелік місяців, але присутні наступні UІ дефекти:
1. Текст "листопад" - обрізаний
2. Кнопка "Done" змістилась
3. Якщо клікнути по кнопці з номером роком, то з’явиться перелік доступних років і номери років дуже зліплені один до одного.
Прикріпляю скріни з FF i Google Chrome

![image](https://cloud.githubusercontent.com/assets/12292125/7582947/961b0138-f89a-11e4-8198-1cdbd97825b7.png)

**Comment by hkhim** [comment]
Неправильна локалізація місяців у календарі. Майданчик сам російськомовний, а назви місяців у календарі - українські

**Comment by znakharenko** [comment]
Datepicker design changed
