### ISSUE TITLE
Неткаст. Подання пропозиції. Нелокалізоване повідомлення у діалоговому вікні після подання пропозиції

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#378]
1. Залогуватися у http://dz2.byustudio.in.ua як Постачальник.
2. Вибрати закупівлю із статусом "Прийом пропозицій" та подати пропозицію.

Очікуваний результат:
З'являється повідомлення, що пропозиція подана.

Актуальний результат:
З'являється діалогове вікно із нелокалізованим повідомленням:
![_ _](https://cloud.githubusercontent.com/assets/12292248/7583809/692537be-f8a1-11e4-97b2-25ba65ecf2ca.png)

**Comment by PaulBoroday** [comment]
Fixed
