### ISSUE TITLE
Неткаст. Подання пропозиції. Нелокалізоване повідомлення при видаленні доданого документа

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#379]
1. Залогуватися у http://dz2.byustudio.in.ua як Постачальник.
2. Вибрати закупівлю із статусом "Подання пропозицій" 
3. Проскролити меню до панелі подання пропозиції > Документи > Додати документ > завантажити документ
4. Натиснути іконку видалення завантаженого документа:
   ![_ _ 1](https://cloud.githubusercontent.com/assets/12292248/7584016/17bbaf96-f8a3-11e4-931f-721c86df1324.png)

Очікуваний результат:
З'являється діалог з повідомленням підтвердження видалення документа.

Актуальний результат:
З'являється діалог з НЕЛОКАЛІЗОВАНИМ текстом.
![_ _](https://cloud.githubusercontent.com/assets/12292248/7584104/c14d9196-f8a3-11e4-96bb-e80a31928eb2.png)

**Comment by PaulBoroday** [comment]
Fixed

**Comment by hkhim** [comment]
Не весь тест локалізований:
![_ _ 2](https://cloud.githubusercontent.com/assets/12292248/7584397/e464b4be-f8a5-11e4-9732-fccd7ec0ef62.png)

**Comment by kvskkvsk** [comment]
Эти кнопки принадлежат браузеру
