### ISSUE TITLE
Неткаст.Реєстрація. Неможливо зареєструвати користувача із апострофом в імені

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#380]
1. Зайти на http://dz2.byustudio.in.ua
2. Відкрити сторінку реєстрації > ввести дані з апострофом у поля "Прізвище", "Ім'я", "По-батькові"

Очікуваний результат:
Введені дані проходять валідацію і користувач може бути зареєстрованим.

Актуальний результат:
Дані не проходять валідацію
![_](https://cloud.githubusercontent.com/assets/12292248/7586244/a378a178-f8b3-11e4-8a86-83c180953d68.png)

**Comment by kvskkvsk** [comment]
Исправлено
