### ISSUE TITLE
Неткаст. Кваліфікація учасників. Неможливо відкрити прикріплений постачальником документ

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#381]
1. Залогуватися на http://dz2.byustudio.in.ua як Покупець.
2. Зайти на сторінку Мої Закупівлі > вибрати закупівлю із статусом "Кваліфікація"
3. У стовпчику "Документи" вибрати документ з пропозицією:
   ![_](https://cloud.githubusercontent.com/assets/12292248/7588954/ba04add2-f8c8-11e4-87ff-eac389118cd8.png)

Очікуваний результат:
Користувач може відкрити прикріплений документ.

Актуальний результат:
Користувач бачить діалогове вікно з помилкою. 
Документ не завантажується.
![_ 2](https://cloud.githubusercontent.com/assets/12292248/7589007/fff306fe-f8c8-11e4-9f6f-807aa749a0a8.png)

**Comment by hkhim** [comment]
Те саме, коли користувач натискає на "Дискваліфікувати" і "Визнати переможцем"

**Comment by kvskkvsk** [comment]
Исправлено. 

ПС: если вы авторизованы, то необходимо выйти и авторизоваться заново.
