### ISSUE TITLE
Неткаст->Додавання документації. Некоректне ім’я доданого файла

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#382]
1. Залогуватись, як покупець в http://dz2.byustudio.in.ua
2. Перейти до сторінки оголошення закупівлі
3. У секції "Тендерна документація" додати .doc файл (н-д: Test)
4. Заповнити решту полів валідними даними і оголосити закупівлю
5. Поредагуйте закупівлю і в секції "Тендерна документація" замість існуючого файлу додайте інший документ (н-д: Test2) і збережіть зміни
6. Впевніться, що назви доданих файлів коректні
7. Повторіть крок 5 і замініть файл на новіший (н-д: Test3) і збережіть зміни

Очікуваний результат:
Всі додані файли повинні мати коректні імена

Фактичний результат:
Всі застарілі файли мають назву файлу з кроку 3 (Test)

![image](https://cloud.githubusercontent.com/assets/12292125/7589064/4c4e24b6-f8c9-11e4-9c72-e1c43a8fad6d.png)

**Comment by kvskkvsk** [comment]
Исправлено
