### ISSUE TITLE
Неткаст. Зміна статусу закупівлі. Не міняється статус для тестових закупівель кожні 10 хвилин

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#383]
1. Залогуватися на http://dz2.byustudio.in.ua як Закупівельник.
2. Створити закупівлю > проставити всі однакові дати (Дата публікації, Завершення періоду обговорення, Завершення періоду прийому пропозицій, Кінцева дата поставки)
3. На майданчику http://uat.e-tender.biz/ знайти створену закупівлю, перевірити її статус.
4. Почекати 10 хв, перевірити статус закупівлі на Неткасті, на Е-Тендері.

Актуальний результат:
Статуси закупівель не міняються.
![_ _](https://cloud.githubusercontent.com/assets/12292248/7590181/ccc648ca-f8cf-11e4-9776-70f42b6c342b.png)

![_ _](https://cloud.githubusercontent.com/assets/12292248/7590296/78e5c856-f8d0-11e4-9854-3850cea9caa5.png)
![_ _ 2](https://cloud.githubusercontent.com/assets/12292248/7590297/79f0f27a-f8d0-11e4-93cf-b0044eec9b3d.png)

**Comment by kvskkvsk** [comment]
А на что должно поменяться, если "Завершення періоду обговорення" 13.05.2015, сейчас только 12.05.2015?
