### ISSUE TITLE
Неткаст->Питання/Відповідь. У питаннях і відповідях не відображається текст в кутових дужках

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#384]
1. Залогуватись, як Постачальник в http://dz2.byustudio.in.ua
2. Перейти до закупівлі в статусі "Обговорення"
3. Перейти до секції обговорення
4. В полях "Суть вашого запитання" і "Зміст запитання" введіть текст в кутових дужках "<>" і надішліть запитання

Очікуваний результат:
Увесь введений текст відображається коректно.

Фактичний результат:
Текст, який міститься у кутових дужках - не відображається. Це саме стосується і відповіді на поставлене запитання Покупцем.

![image](https://cloud.githubusercontent.com/assets/12292125/7606970/5b3da936-f966-11e4-8a76-ef1cc6889fa0.png)

**Comment by kvskkvsk** [comment]
Политика безопасности:
Текст в "<>" для браузеров это тег. А поля эти предназначены для текста.
А если вписать < img alt="" src="http://www.mydomain.com/spacer.png" onload="..." > то в onload можно вписать команду, которая передаст мне информацию необходимую для взлома той или иной площадки.
