### ISSUE TITLE
Неткаст. Кваліфікація. При завантаженні більше одного документа на етапі дискваліфікації або визнання переможцем відображається лише перший документ.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#386]
1. Залогуватися на http://dz2.byustudio.in.ua як Закупівельник.
   2.На етапі Кваліфікації вибрати учасника > Дискваліфікувати (або Визнати Переможцем) > Прикріпити більше ніж один документ.

Очікуваний результат:
При перегляді Протоколу всі додані документи можна переглянути.

Актуальний результат:
Видимий лише перший завантажений документ:
![_ _](https://cloud.githubusercontent.com/assets/12292248/7607768/bebcf9ac-f96c-11e4-9f53-54f619b38606.png)

**Comment by kvskkvsk** [comment]
По базе в этой квалификации лишь 1 документ
и в ЦБД тоже
https://api-sandbox.openprocurement.org/api/0.8/tenders/885a5aecf07d400989aa471ebfb7face
