### ISSUE TITLE
Неткаст. Прийом пропозицій. На етапі прийому пропозицій змінюється задана закупівельником кількість товару

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#387]
1. Залогуватися на http://dz2.byustudio.in.ua як закупівельник.
2. Створити пропозицію > задати кількість одиниць товару (я задавала 1000 шт.)
3. На етапі прийому пропозицій перевірити кількість одиниць товару.

Очікуваний результат:
Кількість одиниць товару не змінилася.

Актуальний результат:
Кількість одиниць товару зменшилася:
![_ _](https://cloud.githubusercontent.com/assets/12292248/7609884/761e793c-f980-11e4-81db-7adee76bde0c.png)

**Comment by kvskkvsk** [comment]
Исправлено
