### ISSUE TITLE
НетКаст, Скажіть будь ласка, де можна отримати "?:tender auction code"

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#388]
1. Залогуйтесь в систему http://www.dz2.byustudio.in.ua
2. Створіть аукціон
3. Зареєструйтесь на аукціон подавши пропозицію
4. Перейдіть до етапу отримання лінки на аукціон

Очікуваний результат:
Лінка "АУКЦІОН МІЖ УЧАСНИКАМИ ТЕНДЕРУ" повинна переадресовувати на аукціон в ролі учасника аукціону

Фактичний результат:
Лінка "АУКЦІОН МІЖ УЧАСНИКАМИ ТЕНДЕРУ" переадресовує на аукціон в ролі спостерігача

![image](https://cloud.githubusercontent.com/assets/11783631/7610624/f2fbf3a2-f986-11e4-97e6-855061e68931.png)

**Comment by kvskkvsk** [comment]
Задумано заказчиком:
Получить ссылку можно после ввода СМС-кода, который отправляется на мобильный телефон участника. Правда, сам СМС сервис не оплаченный и смс-ки не отправляются.

Был второй вариант еще на почту, но его отключили.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@kvskkvsk я правильно розумію, що зараз потрапити на аукціон в ролі учасника поки тимчасово неможливо?

**Comment by kvskkvsk** [comment]
Да. Временно невозможно.

**Comment by kvskkvsk** [comment]
Уже возможно
