### ISSUE TITLE
ДУС: При попытке поставить цену выше начальной, нас выкинуло из аукциона.

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#39]
При попытке поставить цену выше начальной, нас выкинуло из аукциона. 
Forbidden
Access denied: access_denied

**Comment by myroslav** [comment]
Ми пробували зрозуміти, чи це від нас, чи не від нас, і не придумали, коли таке могло статися і за якої умови.

Нам принаймні треба ID аукціону, про який іде мова, а бажано screenshot і приблизний час, коли це сталося.

Більше я по цій задачі не зможу нічого сказати :(

Чи можемо ми просити замовників одразу цю інформацію нотувати?

**Comment by myroslav** [comment]
Я поки не маю додаткової інформації від замовника. Якщо її не буде до кінця тижня, то буду закривати цей Issue.
