### ISSUE TITLE
НетКаст, Підтверідть будь ласка, що файл audit.yaml повинен бути доданий до тендерної документації, та оновлений

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#390]
1. Залогуйтесь в систему http://www.dz2.byustudio.in.ua/
2. Перейдіть до закупівлі http://www.dz2.byustudio.in.ua/tenders/3459
3. Або знайдіть закупівлю за імям: "Предмет закупівлі Tester@dz2.byustudio.in.ua оголошений"

Фактичний результат:
До закупівлі прикріплений та оновлений файл audit.yaml

**Comment by kvskkvsk** [comment]
Это вопрос к ЦБД. автоматом добавляется.

**Comment by YuraOvramets-SoftServe** [comment]
@myroslav , підкажіть, будь ласка, чи файл audit.yaml має додавтись до тендерної документації після завершення аукціону?

**Comment by myroslav** [comment]
Такий документ з'являється в кожному тендері після закінчення аукціону
