### ISSUE TITLE
НетКаст, користувачі які мають зареєстровану електронну пошту на сайті meta.ua не отримують жодних емейлів

### ISSUE THREAD

**Issue by Mykhailo-Shtabaliuk-SoftServe** [openprocurement/frontend#391]
1. Зареєструйте екаунт використовуючи пошту ****@meta.ua
2. Перевірте пошту, чи отримали ви лист з паролем

Очікуваний результат:
Користувачі які користуються сервісами пошти meta.ua повинні мати можливість користуватись сервісами НетКаст ресурсу.

Фактичний результат:
Мною було зареєстровано два екаунти :
misha.mul@meta.ua
misha.invited@meta.ua
password: Password1
![image](https://cloud.githubusercontent.com/assets/11783631/7612192/f5433dcc-f991-11e4-9d39-f8db50e9eec4.png)
жоден з них не отримав листа з паролем для роботи в системі

**Comment by kvskkvsk** [comment]
Попробуйте еще раз, т.к. все письма отправлялись от рамлеровской почты, которая находится в черном списке www.spamcop.net 
Сейчас сменили адрес отправителя

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
@kvskkvsk 
Перевірив знову з поштою:
 misha.a@meta.ua
Password1
Лист реєстрації не прийшов

**Comment by kvskkvsk** [comment]
Проверил на misha.a@meta.ua через кнопку "Забули пароль?". Уже все приходит, но в спам.

**Comment by Mykhailo-Shtabaliuk-SoftServe** [comment]
Вже приходять, закриваю
