### ISSUE TITLE
Неткаст->Визначення переможця. При дискваліфікації всіх учасників статус закупівлі переходить на "Підписання договору"

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#392]
1. Створіть новий тендер в http://dz2.byustudio.in.ua
2. На етапі подання пропозицій подайте пропозицію
3. Дочекайтесь етапу Визначення переможця і дискваліфікуйте всіх учасників

Очікуваний результат:
Закупівля переходить в статус "Невдалий"

Фактичний результат:
Закупівля переходить в статус "Підписання договору", хоча по факту немає з ким підписувати договір

![image](https://cloud.githubusercontent.com/assets/12292125/7613891/29740e78-f99c-11e4-99c5-60c217bf0c70.png)

**Comment by kvskkvsk** [comment]
Статусы меняет ЦБД

**Comment by YuraOvramets-SoftServe** [comment]
@myroslav , можеш перевірити в ЦБД? Статус для даної закупівлі повинен бути "Невдалий", а в Неткасті він відображається, як "Підписання договору", що є не коректним.

**Comment by kvskkvsk** [comment]
ЦБД возвращает статус 'active.awarded' что означает "пройден этап квалификации", но нет разделения на есть ли победитель или всех отклонили. 
В статус "Невдалий" ЦБД переводит через сутки для тестового режима и через 10 для рабочего режима
https://api-sandbox.openprocurement.org/api/0.8/tenders/8c0e2ba199bd49b9bac1841de2669452

**Comment by YuraOvramets-SoftServe** [comment]
Після 24-ох годин статус змінився на "Невдалий".
