### ISSUE TITLE
Неткаст. Відміна закупівлі. Неможливо відкрити причину відміни закупівлі на Неткасті, якщо закупівля створена на e-тендері.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#393]
1. Залогуватися на http://dz2.byustudio.in.ua як Постачальник.
2. Створити закупівлю на http://uat.e-tender.biz/
3. Подати пропозицію з Неткасту.
4. На Е-тендері відмінити закупівлю.

Очікуваний результат:
Закупівля на Неткасті має статус "Відмінений".
Користувач може переглянути причини відміни закупівлі.

Актуальний результат:
Коли користувач клікає на лінку "Причина відміни закупівлі" з'являється діалогове вікно з кодом помилки 404.
![_ _ _](https://cloud.githubusercontent.com/assets/12292248/7634119/71c846ba-fa61-11e4-8fb2-9b8d196ab143.png)

**Comment by kvskkvsk** [comment]
## Выполнено согласно вот этому:

Змінений функціонал відміни тендерів (необхідність вказання причини, і можливість долучення протоколів та ін. документації) доступний на пісочниці API 0.8 за адресою https://api-sandbox.openprocurement.org/api/0.8

Документація: http://api-docs.openprocurement.org/en/latest/tutorial.html#canceling-tender

Опис в ТЗ: https://docs.google.com/document/d/1uriNzZ554KbsNam21aTzf7DOifnFuh6xf5hR1U019t0/edit#bookmark=id.g13qlla4ief1

## Попереднє обговорення: https://groups.google.com/d/topic/open-procurement-api/KwTgCeqaf5s/discussion

В вашем случае (http://www.dz2.byustudio.in.ua/tenders/3542) тендер не имеет ни причины отмены, ни документов. Т.е. новый механизм не реализован на другой площадке, а ЦБД отменяет без этих данных почему-то, хотя согласно новому правилу не должно.

**Comment by hkhim** [comment]
Пофіксано

**Comment by w-be** [comment]
В даній закупівлі : http://www.dz2.byustudio.in.ua/tenders/4884 є причина відміни та немає документа.
Відображення причини відміни без документа не працює.
![image](https://cloud.githubusercontent.com/assets/11888281/8257210/a49a0d2a-16b4-11e5-94c7-245165c0e9dd.png)
При відміні, прикріплення докумету може бути, як не обов"язковим, так і обов"язковим. 
Відображення причини відміни без документа є обов'язковим.
Відображення причини відміни з документом є обов'язковим.

**Comment by kvskkvsk** [comment]
Исправлено
