### ISSUE TITLE
NewTend. Не відображається ім’я учасника аукціону, якщо ставка зроблена через Неткаст.

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#394]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement login: openprocurement pass: test Пользователь: openprocurement@mailinator.com пароль: 123123
2. Створіть новий тендер з валідними даними
3. В періоді очікування пропозиції залогіньтесь в Неткаст і зробіть пропозицію для створеного тендера (http://dz2.byustudio.in.ua login: admin pass: uStudio Email: yovr@softserveinc.com Пароль: Password1)
4. Поверніться в NewTend і також зробіть пропозицію
5. Дочекайтесь періоду "Кваліфікація" і перейдіть на сторінку Торги

Очікуваний результат:
Ім’я учасника акціону з Неткасту відображається в списку

Фактичний результат:
Поле ім’я пусте для користувача Неткасту

У json-файлі для тендера видно, що не передається параметр  "legalName": для користувача Неткаст

![image](https://cloud.githubusercontent.com/assets/12292125/7681562/d114a81e-fd79-11e4-9a15-4a5c826a9de5.png)

![image](https://cloud.githubusercontent.com/assets/12292125/7681543/b88b5248-fd79-11e4-9507-d2e85e8e612d.png)

**Comment by PaulBoroday** [comment]
Ну вот почему в аукционе на стороне ЦБД все отображается (http://auction-sandbox.openprocurement.org/tenders/b68745ad379e48c28dfb894375e970db), а на внутренней реализации аукциона конкретной площадки (http://dev23.newtend.com/openprocurement/#/tender/b68745ad379e48c28dfb894375e970db/auction) - нет, я не могу знать... :)

**Comment by znakharenko** [comment]
We are going to show name instead of legalName (per our discussion with Myroslav).
