### ISSUE TITLE
Неткаст. Стрес тест. Кваліфікація переможця. Неможливо додати документ до пропозиції.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#399]
Передумови:
ЦБД зависла.
Закупівля в стані Кваліфікація Переможця.
1. Залогуйтесь як постачальник
2. Перейдіть до своїх пропозицій
3. Відкрийте пропозицію/закупівлю в стані Кваліфікація переможця
4. Додайте документ до пропозиції

Очікувано: Замість відкриття діалога додавання документа з"являється повідомлення назразок "Наразі неможливо додати документ". Або кнопка взагалі не доступна, як Зробити Пропозицію і подібні.

Фактично: веб сторінка зависає. (після  перегрузки сторінки, можна продовжувати працювати).
![image](https://cloud.githubusercontent.com/assets/11888281/7702716/ebb6b5f6-fe3a-11e4-94e6-5f513427d8e0.png)

**Comment by kvskkvsk** [comment]
Уточните, пожалуйста, т.к. проверено из-под вашего аккаунта и все выдает
![1](https://cloud.githubusercontent.com/assets/11290871/7703564/73b3a17a-fe41-11e4-9520-b6a0fad0c979.jpg)

**Comment by w-be** [comment]
Перепровірив на іншому бравзурі/компі - тільки в мене відтворюється!
В мне ІЕ10.
На FF та ІЕ11 все ок.

Підтвердіть, що можна закрити (якщо ІЕ10 не підтримується).

**Comment by kvskkvsk** [comment]
Исправили. Особенности ИЕ8-10
