### ISSUE TITLE
Не пришел на ПРОМ вопрос ЕЛЕГ-АК-01 к торгам 1-ПРОМ-АК-12 

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#40]

**Comment by darchik** [comment]
![2015-01-29 18 26 43](https://cloud.githubusercontent.com/assets/5691919/5961303/6a80b47a-a7e4-11e4-9dfc-8cfc55352ed8.png)
Он?

**Comment by andriykucherenko** [comment]
Скажи честно, руками протолкнул? ))
А если серьезно, то да, долетело. Странно то, что по другим торгам мы уже обменялись вопросами-ответами, а по этим торгам вопрос затупил... интересно, почему?
Но тикет закрываю

**Comment by darchik** [comment]
Ничего не трогал :) Завтра попрошу глянуть лог, может найдем причину.
