### ISSUE TITLE
NewTend > Stress Testing. Запитання. Чи правильне повідомлення, яке відображається користувачеві, коли він зберігає зміни при вимкненій ЦБД?

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#404]
Передумови:
1. ЦБД вимкнена.

Кроки:
1. Залогуватися на http://dev23.newtend.com/openprocurement/#/home/page/1 як Закупівельник (openprocurement@mailinator.com)
2. Створити закупівлю > Опублікувати

Актуальний результат:
З*являється повідомлення про помилку:
![2015-05-19 18_00_40-mozilla firefox](https://cloud.githubusercontent.com/assets/12292248/7706204/9e6c8584-fe51-11e4-9ef6-9c9d48a8610a.png)

Чи це повідомлення правильне чи можливо, має з'являтися більш інформативне повідомлення, наприклад, "ЦБД тимчасово не доступна, спробуйте пізніше"?

**Comment by znakharenko** [comment]
This error message looks fine :) We are going to improve messages later.
Look at this issue number, it is so symbolic :) #404
