### ISSUE TITLE
NewTend->Реєстрація контракту. Підтвердіть, будь ласка, чи правильною є можливість додавати декілька контрактів при визначенні переможця.

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#406]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Оголосіть тендер з валідними даними
3. В періоді "Очікування пропозицій" зробіть хоча б одну пропозицію
4. В періоді "Кваліфікація" виберіть переможця
5. Використовуючи функціонал "Загрузить договор" додайте декілька файлів

Підтвердіть, будь ласка, чи правильною є можливість додавати декілька контрактів при визначенні переможця?

**Comment by znakharenko** [comment]
@myroslav please answer this question

**Comment by myroslav** [comment]
Можна завантажувати кілька документів, договір, додатки, інші документи, які стосуються контракту.
