### ISSUE TITLE
NewTend. Оголошення закупівлі. Відсутність повідомлення про введення невалідних даних.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#407]
1. Залогуватися на http://dev23.newtend.com/cabinet/customer як Закупівельник.
2. Перейти на сторінку Оголошення Закупівлі http://dev23.newtend.com/openprocurement/#/create-tender 
3. Ввести невалідні дані у деякі поля (наприклад, Бюджет, Шаг, Количество) > Опублікувати

Очікуваний результат:
З'являється повідомлення про неправильно заповнені поля і ті поля підсвічуються червоним.

Актуальний результат:
Закупівля не створюється, користувач залишається на тій самій сторінці, але немає жодного повідомлення про те, що поля заповнені неправильними даними
![2015-05-20 13_37_26-mozilla firefox](https://cloud.githubusercontent.com/assets/12292248/7724051/aab1cc14-fef6-11e4-9790-c0ff44f38675.png)

**Comment by znakharenko** [comment]
They are marked with red, look at your own screenshot. Are you issue about text error message absence? If so, please improve description "але немає жодного повідомлення про те, що якісь поля заповнені неправильно"

**Comment by hkhim** [comment]
Побачила, що поля підсвічуються червоним=)
Тоді виникає питання про те, що поля з невалідними даними підсвічуються дуже тьмяно. Це підкреслення важко помітити.
