### ISSUE TITLE
NewTend->Кваліфікація. Статус учасника, якого визнали переможцем не змінюється з "Ожидает решения"

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#408]
1. Залогуйтесь в систему http://dev23.newtend.com/openprocurement
   login: openprocurement
   pass: test
   Пользователь: openprocurement@mailinator.com
   пароль: 123123
2. Створіть тендер з валідними даними
3. На етапі "Прийом пропозицій" зробіть хоча б одну пропозицію
4. На етапі "Кваліфікація" визнайте якогось з учасників переможцем

Очікуваний результат:
Статус учасника змінюється на "Победитель"

Фактичний результат:
Статус учасника залишається "Ожидает решения"

Статус учасника цього самого тендера на Нетккаст змінюється на "Переможець"

![image](https://cloud.githubusercontent.com/assets/12292125/7725362/a7a93190-ff02-11e4-8ec6-1d596daa115d.png)

**Comment by SlaOne** [comment]
![accepted](https://cloud.githubusercontent.com/assets/15046328/11341918/3aa4bb98-920d-11e5-8cc9-319fcf33076f.jpg)
problem fixed
