### ISSUE TITLE
NewTend->Подання пропозиції. Нема валідації на введені дані в полі "Ваше предложение"

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#411]
1. Залогуйтесь в NewTend як Закупівельник
2. Оголосіть тендер з валідними даними
3. Дочекайтесь періоду "Предложения" і залогіньтесь як Постачальник
4. Знайдіть створений трендер і натисніть на "Сделать ставку"
5. Введіть з допомогою лічильника введіть від’ємне значення, 0, більше за бюджет і натисніть "Сделать предложение"

Очікуваний результат:
Користувач сповіщений про те, що введені дані не є валідними, або кнопка "Сделать предложение" стає не активною.

Фактичний результат:
Користувач не є сповіщеним про те, що дані не є валідними і має змогу натиснути на кнопку "Сделать предложение", але пропозиція насправді не зберігається.

**Comment by YuraOvramets-SoftServe** [comment]
Було б добре також унеможливити ввід суми, яка перевищує бюджет.

**Comment by znakharenko** [comment]
It should work. Could you provide steps that fail described scenario. Link to tender.

**Comment by YuraOvramets-SoftServe** [comment]
Прошу вибачення, після рефрешу сторінки сценарій не відтворюється.
