### ISSUE TITLE
NewTend. Редагування закупівлі. Відсутня кнопка, яка дозволяє завантажувати нові документи.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#413]
1. Залогуватися на http://dev23.newtend.com/cabinet/customer як Закупівельник.
2. Перейти на http://dev23.newtend.com/openprocurement/#/home/page/1 і вибрати свою закупівлю в періоді Уточнення, яка має прикріплені документи.
3. Перейти на вкладку "Документи"

Очікуваний результат:
У вкладці "Документи" є кнопка "Загрузить Документ", яка дозволяє користувачеві завантажити нові документи до закупівлі.

Актуальний результат:
Відсутня кнопка "Загрузить Документ". Користувач не має змоги завантажити нові документи до закупівлі, а лише замінити існуючі.
![2015-05-21 14_26_20-mozilla firefox](https://cloud.githubusercontent.com/assets/12292248/7747809/e763cbfa-ffc6-11e4-9c13-fee9938bf438.png)

**Comment by znakharenko** [comment]
It is present actually, however it is placed below green bar :)
Layout issue, will be fixed soon.
