### ISSUE TITLE
NewTend->Створення закупівлі(Не ігровий режим). Поле "Заказчик" порожнє.

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#416]
1. Залогуйтесь в NewTend як Закупівельник в "Не ігровому режимі" (login - openprocboss@mailinator.com pass - 123123)
2. Оголосіть закупівлі з валідними даними

Очікуваний результат:
Поле "Заказчик" містить назву замовника

Фактичний результат:
Поле "Заказчик" порожнє і в ЦБД назва замовника не передається

![image](https://cloud.githubusercontent.com/assets/12292125/7767163/eb5a95b0-0078-11e5-88d5-01ef90c45873.png)

**Comment by znakharenko** [comment]
I've missed to enter short name for this Company :)
Fixed, please try to create a new tender and recheck.
