### ISSUE TITLE
Проблеми з отриманням лінку на аукціон

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#42]
Торги a687f0fb524f463499f8e569a3e89f10 
на ПРОМ нема лінку
на ЕЛЕГ лінки є, але не відкриваються
публічний: http://auction-sandbox.openprocurement.org/tenders/a687f0fb524f463499f8e569a3e89f10
лінк учасника: http://auction-sandbox.openprocurement.org/tenders/a687f0fb524f463499f8e569a3e89f10/login?bidder_id=27013db4077e4f1091aa1a9c3dd38b0a&hash=835a22414cec5ef114c7ad47d6c5ca13e5278274

якщо я зарано зайшов, я ж мав отримати повідомлення "Аукіон почнеться...", хіба ні?

**Comment by myroslav** [comment]
ПРОМ мав отримати посилання, в ЦБД є посилання auctionURL, і відповідно по ньому мав би бути видимий аукціон.

Підтверджую, що є проблеми в самого аукціону, зараз розбираємося, з чим це пов'язано

**Comment by myroslav** [comment]
Зараз поки не відбувається аукціон (через проблеми) відбувається перепланування аукціону, і майданчики мають періодично отримувати нову дату проведення аукціону.

**Comment by myroslav** [comment]
Частину проблеми вирішили, після перепланування URL вже будуть робочі, але аукціони ще не йдуть.

**Comment by myroslav** [comment]
Аукціони запустили
