### ISSUE TITLE
Неткаст. Домашня сторінка. Стурбований смайлик захопив сторінку, стало не зручно читати текст.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#422]
http://www.dz2.byustudio.in.ua/
1. Зайдіть на домашню сторінку Неткаст.

Очікувано: Все виглядає дружньо для користувача.

Фактично: Використаний задній фон (стурбований смайлик) погано контрастує з текстом, текст читати не зручно. Також смайл помітно меншого розміру ніж фон який він займає, з'являється піксилізація.
![image](https://cloud.githubusercontent.com/assets/11888281/7794302/7da97cb0-02d1-11e5-8651-e02ec4c418c0.png)

**Comment by kvskkvsk** [comment]
Почистите кеш и обновите страницу
