### ISSUE TITLE
Неткаст. Реєстрація користувача. Несхожість перевірки цифрових полів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#423]
http://www.dz2.byustudio.in.ua/registration/buyers

Пропоную зробити валідацію на поле Поштовий Індикс таку ж як і на поле Код ЄДРПОУ / ІПН - на рівні доступності вводу: фіксована кількість знаків (5) та тільки цифри.

![image](https://cloud.githubusercontent.com/assets/11888281/7794546/61cd7304-02d4-11e5-8d5a-01fcd4c4b22c.png)

**Comment by kvskkvsk** [comment]
Готово
