### ISSUE TITLE
Неткаст. Реєстрація. Не коректна перевірка поля Факс.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#424]
http://www.dz2.byustudio.in.ua/registration/sellers
1. Зайдіть на сайт.
2. Перейдіть до реєстрації користувача.
3. Помістіть курсор в поле Факс
4. Перемістіть курсор в інше поле

Очікувано: Поле Факс залишиться не підсвіченим.

Фактично: Поле Факс починає підсвічуватись оранжевим начебто воне є обов'язковим для заповнення.

![image](https://cloud.githubusercontent.com/assets/11888281/7794909/46b18a2a-02d8-11e5-93e3-b7fd41bbf96c.png)

**Comment by kvskkvsk** [comment]
Исправлено
