### ISSUE TITLE
Неткаст. Реєстрація. Чекбокси погодження з умовами не впливають на можливість реєстрації.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#425]
http://www.dz2.byustudio.in.ua/registration/sellers
1. Зайдіть на сторінку реєстрації нового користувача.
2. Заповніть всі поля допустимими значенями.
3. Залишіть чекбокси погодженя з умовами порожніми
4. Натисніть Зареєструватись

Очікувано: обов'язкові чекбокси підсвічуються оранжевим.

Фактично: обов'язкові чекбокси підсвічуються оранжевим, але система пириходить до наступного кроку: перевірки коду з мобільного.

![image](https://cloud.githubusercontent.com/assets/11888281/7795061/db57443e-02d9-11e5-86cc-d2a41a3b7118.png)

**Comment by kvskkvsk** [comment]
Исправлено
