### ISSUE TITLE
Неткаст. Нелокалізоване повідомлення у діалозі підтвердження відміни закупівлі.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#426]
1. Залогуватися на http://dz2.byustudio.in.ua як Постачальник.
2. Подати пропозицію > Відмінити подану пропозицію.

Очікуваний результат:
Діалог підтвердження відміни пропозиції українською мовою.

Актуальник результат:
Діалог підтвердження відміни пропозиції нелокалізований.
![2015-05-25 12_25_34- -](https://cloud.githubusercontent.com/assets/12292248/7795276/0503828c-02dc-11e5-9832-0dd14d4e1a0a.png)

**Comment by PaulBoroday** [comment]
Fixed
