### ISSUE TITLE
Неткаст. Відміна пропозиції. Після відміни пропозиції з'являється некоректне повідомлення.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#427]
1. Залогуватися на http://dz2.byustudio.in.ua як Постачальник.
2. Подати пропозицію до закупівлі.
3. Відкликати пропозицію.

Очікуваний результат:
З'являється повідомлення про те, що пропозицію відкликано.

Актуальний результат:
З'являється повідомлення про те, що пропозицію прийнято.
![2015-05-25 12_48_44- -](https://cloud.githubusercontent.com/assets/12292248/7795349/bce0abe6-02dc-11e5-8fbd-a28a3f9f2cf7.png)

**Comment by kvskkvsk** [comment]
Исправлено

**Comment by hkhim** [comment]
В мене далі відтворюється.

**Comment by kvskkvsk** [comment]
Почистите кеш и обновите страницу. Все работает.

**Comment by hkhim** [comment]
Тепер інше неправильне повідомлення:
![2015-05-26 17_28_22- -](https://cloud.githubusercontent.com/assets/12292248/7816149/563c65a2-03d5-11e5-9dd5-4f7a13391406.png)

**Comment by kvskkvsk** [comment]
Изменено
