### ISSUE TITLE
Неткаст->Додавання документації(IE). Неможливо додати документацію до закупівлі.

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#428]
1. Залогуватися на http://dz2.byustudio.in.ua як Закупівельник через браузер Internet Explorer
2. Перейти до оголошення закупівлі
3. У секції Тендерна документація додайте файл

Очікуваний результат:
Файл доданий

Фактичний результат:
З’являється індикатор завантаження і сторінка постійно вантажиться. Результат валідний для всіх випадків додавання файлу (при поданні пропозиції, при відповіді на скаргу....)

![image](https://cloud.githubusercontent.com/assets/12292125/7795410/8543ad36-02dd-11e5-9701-5a2063babe0e.png)

**Comment by kvskkvsk** [comment]
Если это ИЕ10 и в имени файла есть кириллические буквы, то он этого и не сделает, глючит его.

**Comment by YuraOvramets-SoftServe** [comment]
Тестую в ІЕ11, взяв файл з іменем "Silent" - сторінка вантажиться вже ~40 хв

**Comment by kvskkvsk** [comment]
Сам механизм работает, но в ИЕ действительно наблюдаются залипания при отправке файла, правда, не всегда. При этом сам ИЕ не выдаёт каких-либо ошибок по сети или яваскрипту.

**Comment by YuraOvramets-SoftServe** [comment]
Тобто це проблема в самому ІЕ і ми неможемо її вирішити?

**Comment by kvskkvsk** [comment]
Проверили еще раз. Проблема в самом ИЕ. Причем она не проявляется, если открыта "Панель разработчика" - кнопка F12
