### ISSUE TITLE
Неткаст. Реєстрація. Неможливо зареєструвати мейл з цифрами у його імені

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#431]
1. Зайти на сторінку реєстрації http://www.dz2.byustudio.in.ua/registration/sellers
2. Ввести електронну пошту, яка містить цифри. 

Очікуваний результат:
Користувач з такю поштою може бути зареєстрований.

Актуальний результат:
Така пошта не проходить валідації.
![2015-05-26 18_51_13-](https://cloud.githubusercontent.com/assets/12292248/7816737/b5f8741a-03d8-11e5-9f27-097ce06362a1.png)

**Comment by kvskkvsk** [comment]
struby4a@ukr.net уже есть в системе
