### ISSUE TITLE
Неткаст. Після реєстрації користувача неможливо виконати жодних дій з майданчиком.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#433]
Точних кроків не знаю, в мене це сталося так:
1. Зареєструватися на http://dz2.byustudio.in.ua
2. Погодитися з умовами угоди.
3. Натиснути плючик, щоб поповнити рахунок.

Актуальний результат:
При натисканні плюсика відкривалося пусте вікно.
Після того як закрила це вікно і обновила сторінку, на майданчику неможливо зробити жодних дій і вилогуватися.
![2015-05-27 12_01_36-mozilla firefox](https://cloud.githubusercontent.com/assets/12292248/7832801/5e9fb8e4-046a-11e5-9a5e-ba5ca704b3bf.png)

**Comment by hkhim** [comment]
Те саме після поповнення рахунку, підтвердження поповнення з адмінки, після перезавантаження сторінки.

**Comment by kvskkvsk** [comment]
Tester@dz2.byustudio.in.ua предназначен лишь для подтверждения оплаты и договоров в тестовом режиме
В админке есть кнопка выход.
Потом идете на сайт и авторизируетесь как другой ТЕСТЕР, который был действительно зарегистрирован через сайт
