### ISSUE TITLE
Неткаст. Учасник. Поповнення рахунку. Опечатка в слові.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#434]
1. Залогуватися на http://dz2.byustudio.in.ua як Учасник.
2. Натиснути на плюсик, щоб поповнити рахунок.

Актуальний результат:
Появляється вікно. У слові "згенеровано" граматична помилка:
![2015-05-27 12_45_40--](https://cloud.githubusercontent.com/assets/12292248/7833334/ae197762-046e-11e5-9948-fbf0e5ac55c8.png)

**Comment by PaulBoroday** [comment]
Fixed

**Comment by hkhim** [comment]
Репродюситься:
![2015-06-04 11_24_57-- 3](https://cloud.githubusercontent.com/assets/12292248/7979951/69012866-0aac-11e5-924a-41ccddea0775.png)
