### ISSUE TITLE
Неткаст->Оголошення закупівлі. Підтвердіть, будь ласка, що макс. сума бюджету не повинна передищувати 9999999.99

### ISSUE THREAD

**Issue by YuraOvramets-SoftServe** [openprocurement/frontend#436]
Якщо так, то було б добре виводити повідомлення на етапі оголошення закупівлі при введенні в поле "Максимальний бюджет" суми більшої, ніж 9999999.99 грн.

**Comment by kvskkvsk** [comment]
Увеличено до 99999999999.99
Думаю этого точно хватит.
