### ISSUE TITLE
Неткаст. Отримання коду на аукціон. Смс-код приходить двічі.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#437]
1. Залогуватися на http://dz2.byustudio.in.ua як Учасник.
2. Подати пропозицію на закупівлю (впевнитися, що це не єдина пропозиція до цієї закупівлі)
3. Дочекатися періоду аукціону.

Актуальний результат:
Коли починається період аукціону, на номер учасника приходить смс з кодом доступу на аукціон.
Коли він заходить на закупівлю і натискає на лінку, де можна ввести код, за декілька секунд приходить новий код. Попередній вже стає неактуальний. Фактично, кожного разу, коли користувач переходить на цю лінку, приходить новий смс код.
Чи така поведінка є правильною?

**Comment by kvskkvsk** [comment]
> Коли починається період аукціону, на номер учасника приходить смс з кодом доступу на аукціон.

Автоматом код не приходит. Только после нажатия на ссылку. Специально проверено.

> Фактично, кожного разу, коли користувач переходить на цю лінку, приходить новий смс код.
> Чи така поведінка є правильною?

Да.
