### ISSUE TITLE
Неткаст. Нелокалізоване повідомлення при відміні перемоги.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#439]
1. Залогуватися як Закупівельник на http://dz2.byustudio.in.ua
2. Вибрати закупівлю із статусом "Підписання договору"
3. Вибрати опцію "Відмінити перемогу"

Очікуваний результат:
Діалог підтвердження відміни перемоги має бути українською мовою

Актуальний результат:
Діалог підтвердження відміни перемоги нелокалізований:
![2015-05-27 16_25_33- -](https://cloud.githubusercontent.com/assets/12292248/7837068/8d58fe98-048d-11e5-8015-54453c69ebad.png)

**Comment by PaulBoroday** [comment]
Fixed

**Comment by hkhim** [comment]
Схожа поведінка:
![2015-06-04 11_21_31- -](https://cloud.githubusercontent.com/assets/12292248/7979917/0847cdf4-0aac-11e5-964b-c2cdf31400bb.png)

**Comment by hkhim** [comment]
Пофіксано
![2015-07-01 13_38_22-](https://cloud.githubusercontent.com/assets/12292248/8452768/7d539146-1ff6-11e5-8b80-832ca84ddf69.png)
