### ISSUE TITLE
Тендер. Секція - Документи - Який максимальний розмір файла можна завантажити у аплікацію? 

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#44]

**Comment by myroslav** [comment]
Зараз на рівні ЦБД діє обмеження в 1Мб, але за кілька днів ми піднесемо обмеження до 50Мб.

**Comment by lerich** [comment]
установили 50Мб, было 100Мб

**Comment by OksanaPakholok** [comment]
Скажіть будь-ласка, який на даний момент максимальний розмір файла, що можна завантажити у аплікацію?
@myroslav

**Comment by myroslav** [comment]
На production - 50Мб брутто, тобто 50Мб вже має не "влізти", а 49Мб ще має пустити. На sandbox - 1Мб брутто, відповідно 1000Кб - має пройти.
