### ISSUE TITLE
Неткаст. ІЕ11. Подання пропозиції. Кнопка Зберегти не працює.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#440]
http://www.dz2.byustudio.in.ua/tenders/4055
1. Залогуйтесь постачальником
2. Знайдіть закупівлю в статусі подання пропозицій
3. Відкрийте її
4. Спробуйте додати свою пропозицію.

Очікувано: Створюється пропозиція

Фактично: Сторінка зависає. 

Також неможливо змінити чи відкликати пропозицію. Додати Документ.
![image](https://cloud.githubusercontent.com/assets/11888281/7838710/085d08d8-0497-11e5-95b0-16fa460a5314.png)

**Comment by kvskkvsk** [comment]
Исправлено
