### ISSUE TITLE
Неткаст. Подача/Зміна пропозиції.Пропоную змінити валідацію поля Цінова Пропозиція.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#441]
http://www.dz2.byustudio.in.ua/tenders/3640

Пропоную заборонити вводити не цифрові значення та від'ємні цифри в поле.
Дозволити тільки арабські цифри, кому, крапку.
Таксамо, як це реалізовано на сторінці створення закупівлі.
1. Зайдіть за постачальника
2. Знайдіть закупівлю в періоді подачі пропозиції
3. Відкрийте закупівлю
4. Спробуйте подати не цифрову суму

Очікувано: в цифрове поле можна ввести тільки цифри.

Фактично: Можна вводити всі символи.

**Comment by kvskkvsk** [comment]
Уточните, пожалуйста, т.к. тут это поле ведет себя также - проверенно FF.

**Comment by kvskkvsk** [comment]
Проявлялось после подачи/сохранения предложения.
Исправлено
