### ISSUE TITLE
Неткаст. Подача/Зміна пропозиції.В полі Цінова Пропозиція кома не заміняється на крапку.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#442]
http://www.dz2.byustudio.in.ua/tenders/3640

Заміна кома на крапку реалізована на сторінці створення закупівлі, отже і тут мала б.
1. Зайдіть за постачальника
2. Знайдіть закупівлю в періоді подачі пропозиції
3. Відкрийте закупівлю
4. Спробуйте вписати суму з комою (12,45)

Очікувано: кома автоматично заміниться на крапку.

Фактично: Кома залишається, сума валідується як значення неправильного формату.

**Comment by kvskkvsk** [comment]
Уточните, пожалуйста, т.к. тут это поле ведет себя также - проверенно FF.

**Comment by kvskkvsk** [comment]
Проявлялось после подачи/сохранения предложения.
Исправлено
