### ISSUE TITLE
Неткаст. Реєстрація. Можливо зареєструвати той самий номер телефону для різних користувачів. Чи ця поведінка є нормальною?

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#445]
1. Зайти на http://dz2.byustudio.in.ua
2. Заресєтрувати користувача.
3. Зареєструвати нового користувача, вказавши той самий номер телефону.

Актуальний результат:
Неткаст дозволяє реєструвати різних користувачів на той самий номер телефону.

Питання:
Чи це зроблено лише для тестового режиму?
Чи для реальних закупівель така поведінка є нормальною?

**Comment by kvskkvsk** [comment]
Да. Телефоны не уникальные поля. Только адрес электронной почты.
Мобильный только для информирования СМС, а остальные для подстановки при создании тендера.
У компании могут быть куча подразделений, которые проводят закупки, а контроль, скажем, только у директора
Ну и для закупщиков особая схема подписания договора с непосредственным участием администрации, ну и, соответственно, проверкой данных компании.
