### ISSUE TITLE
Неткаст. Некоректна сума оплати участі в закупівлі.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#447]
1. Залогуватися на http://dz2.byustudio.in.ua  як Учасник.
2. Перейти до закупівлі у період подання пропозицій.

Актуальний результат:
Сума оплати за участь у закупівлі 170 грн. на сайті.
![2015-06-04 13_29_00- - 1](https://cloud.githubusercontent.com/assets/12292248/7982231/115718f2-0abe-11e5-9634-0d43b3ac2c0a.png)

Очікуваний результат:
У технічному завданні вказано, що сума оплати за участь в закупівлі становить 175грн.
![2015-06-04 13_21_43- _v1 02 - google](https://cloud.githubusercontent.com/assets/12292248/7982229/0dc80944-0abe-11e5-8cdd-670bf063f67a.png)

**Comment by w-be** [comment]
Поремонтовано:
![image](https://cloud.githubusercontent.com/assets/11888281/8035340/647ee7e8-0df8-11e5-887e-f16dc9e3b28f.png)
