### ISSUE TITLE
Неткаст. IE11. Відміна закупівлі. Некоректні назви кнопок у діалозі підтвердження відміни.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#449]
1. Залогуватися на http://www.dz2.byustudio.in.ua як Закупівельник у ІЕ11.
2. Перейти на закупівлю у статусі "Підписання договору" > Відмінити її

Очікуваний результат:
Діалог підтвердження відміни має кнопки з українськими назвами.

Актуальний результат:
В ІЕ11 діалог підтвердження має кнопки з двома однаковими нелокалізованими назвами.
![2015-06-11 11_36_24- - internet explorer](https://cloud.githubusercontent.com/assets/12292248/8103361/91863496-1030-11e5-852c-4d559d806555.png)

В Мозілі і Хромі кнопки з російськими назвами:
![2015-06-11 11_54_31-](https://cloud.githubusercontent.com/assets/12292248/8103381/aaeaeecc-1030-11e5-91cd-cbbe4465ae6c.png)

**Comment by kvskkvsk** [comment]
Исправлено
