### ISSUE TITLE
Newtend. Деталі закупівлі. Якщо в одиницях виміру закупівлі вказаний тільки код одиниці виміру або правильний код і не правильне і'мя, одиниці виміру не відображаються.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#450]
Узгоджено з Мирославом.

http://dev23.newtend.com/dz/#/tender/94ffe180019d459787aafe290cd300e2/overview
0. Створена закупівля, з одиницями виміру в яких не вказане ім'я одиниць виміру, або містить не правильне ім'я одиниць виміру.
1. Зайти на майданчик
2. Знайти закупівлю
3. Відкрити деталі

Очікувано: Одиниці виміру пребмета (units) відображаються, якщо код вказаний вірно.

Фактично: Одиниці виміру пребмета (units) відображаються, якщо код і ім'я вказані вірно.

![image](https://cloud.githubusercontent.com/assets/11888281/8129993/98260dac-1117-11e5-9407-bf4d4386c4cf.png)

**Comment by myroslav** [comment]
Важливо, щоб майданчик коректно відображав одиницю у випадку, коли не заповнена назва.

Пропонований пріоритет при відображенні назви одиниції:
- Unit.name
- з Unit.code використовуючи http://opendata.org.ua/dataset/recommended-units-of-measure
- з Unit.code використовуючи ваш власний набір одиниць
- з Unit.code використовуючи http://opendata.org.ua/dataset/codes-for-units-of-measure (неперекладені)

Пріоритет джерел можна міняти впливаючи на те, чи вірите ви name яке вклали в дані інші майданчики.

**Comment by znakharenko** [comment]
The logic is following:
- Name from Unit.code using http://opendata.org.ua/dataset/recommended-units-of-measure
- Unit.name if code is not found
- Unit.code if code is not found and Unit.name is empty

**Comment by w-be** [comment]
Зараз при правильному коді і не правильному імені одиниці виміру товару, відображається правильне ім'я з словника майданчика Ньютенд.
