### ISSUE TITLE
Неткаст. Відміна пропозиції. Описка у слові.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#453]
1. Залогуватися на http://www.dz2.byustudio.in.ua/ як Постачальник.
2. Відмінити зроблену пропозицію

Актуальний результат:
Описка у діалозі підтвердження відміни.
![2015-06-16 17_27_29- 1](https://cloud.githubusercontent.com/assets/12292248/8185549/c504d176-144d-11e5-931e-47eb7f4a3954.png)

**Comment by kvskkvsk** [comment]
Исправлено
