### ISSUE TITLE
ЕЛЕГ. Відсутній блок причини відміни закупівлі та супроводжуючі документи, якщо закупівля створена на іншому майданчику.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#454]
1. Створити закупівлю на Неткасті > відмінити її, вказавши причину і додавши документи
2. Залогуватися на http://uat.e-tender.biz/ і знайти створену закупівлю на Неткасті.

Очікуваний результат:
На E-Tender є присутній блок з  причиною відміни закупівлі та прикріпленими документами.
![2015-06-19 18_10_18-](https://cloud.githubusercontent.com/assets/12292248/8256261/86ff0140-16ae-11e5-97df-93e8024c98ee.png)

Актуальний результат:
Якщо закупівля створена на іншому майданчику, то на e-Tender немає блоку з вказаною причиною відміни і прикріпленими документами. Перевірено, із закупівлями, створеними на Неткасті та Промі.
![2015-06-19 18_12_40-](https://cloud.githubusercontent.com/assets/12292248/8256307/eebb309c-16ae-11e5-8e92-7b06eb8a8385.png)

**Comment by S-Shevchenko** [comment]
Спасибо. В работе.
