### ISSUE TITLE
Ньютенд. Створення закупівлі. Адреса доставки. Поля допускають невалідні значення

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#459]
1. Залогуватися на http://dev23.newtend.com/openprocurement/#/home/page/1 як Закупівельник > Оголосити закупівлю
2. Натиснути на "Адрес доставки" > ввести у поля "Регіон" і "Населений пункт" цифрові значення або будь-які спецсимволи.
3. У поле "Поштовий код" ввести алфавітні значення/спецсимволи/цифрові значення, довші, ніж 5 символів.

Очікуваний результат:
Поля  "Адрес доставки", "Регіон" і "Населений пункт" не дозволяють введення цифрових значеннь, і спецсимволів (крім апострофа)
Поле "Поштовий код" допускає введення лише п'ятицифрового значення
![2015-07-06 12_47_16- - openprocurement openprocurement](https://cloud.githubusercontent.com/assets/12292248/8519929/c31d5fae-23de-11e5-842c-d0f34f72ed3e.png)

Актуальний результат:
Всі згадані поля допускають введення невалідних значеннь

**Comment by znakharenko** [comment]
@myroslav We are following CDB structure http://api-docs.openprocurement.org/en/latest/standard/organization.html#address

Please explain, do we need to implement our own validation rules?
I'm not sure this is correct approach. 

Address
Schema
streetAddress:  

string

OpenContracting Description: The street address. For example, 1600 Amphitheatre Pkwy.
locality:   

string

OpenContracting Description: The locality. For example, Mountain View.
region: 

string

OpenContracting Description: The region. For example, CA.
postalCode: 

string

OpenContracting Description: The postal code. For example, 94043.
countryName:    

string, required

OpenContracting Description: The country name. For example, United States.

**Comment by w-be** [comment]
Власна валідація це зовсім необов"язковий додаток, який зазвичай присутній в сучасних аплікаціях. Впринципі баг можна закрити зі статусом - не буде зроблено(would not fix).

**Comment by SlaOne** [comment]
почтовый индекс принимает теперь только пять и только цифр. все поля обязательны.
