### ISSUE TITLE
NewTend. Перегляд Закупівлі. Документи. Час від часу сторінка не догружається з помилкою.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#460]
http://dev23.newtend.com/openprocurement/tenders#/tender/c06ddf13163540aeb612aec1c2cc97fa/edit
openprocurement@mailinator.com / 123123

1.Залогуйтесь 
2.Створіть закупівлю 
3.Переходьте по табам меню: Описание-Уточнения-Торги-Документы
Примітка: Помилка не відтворюється якщо переходити Описание-Документы

Очікувано: З'являється вміст таби Документи: "Загрузить документ", і вже додані документи.

Фактично: Часто таба недогружається: повідомлення про помилку + не показуються додані документи + ктопка Загрузить Документ не активна. 
![image](https://cloud.githubusercontent.com/assets/11888281/8522893/b297b078-23fa-11e5-87aa-e78337bca7d6.png

**Comment by znakharenko** [comment]
This is temp issue. I'll update you when it will be solved.

**Comment by znakharenko** [comment]
Solved
