### ISSUE TITLE
ЕЛЕГ. Створення або редагування закупівлі. При заміні файлу відбувається додавання нового файла, а не заміна існуючого.

### ISSUE THREAD

**Issue by hkhim** [openprocurement/frontend#463]
1. Залогуватися на http://uat.e-tender.biz/ як Закупівельник.
2. Перейти до тендера у періоді уточнень > Додати документи > Замінити поданий документ.

Очікуваний результат:
Документ є замінений на новий, при цьому користувач бачить назву старого документа і новий документ.

Актуальний результат:
Додається новий файл, попередній файл при цьому не видаляється.
![2015-07-07 15_53_49-](https://cloud.githubusercontent.com/assets/12292248/8546559/83a926a8-24c1-11e5-8585-44dbe8d76762.png)

![2015-07-07 15_54_26-](https://cloud.githubusercontent.com/assets/12292248/8546564/87fea282-24c1-11e5-96ca-cb4842efcda7.png)

**Comment by S-Shevchenko** [comment]
Дякую.Виправлено.
