### ISSUE TITLE
ЕЛЕГ. Деталі закупівлі. Неможливо задати запитання в перідоді уточнення.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#464]
http://uat.e-tender.biz/#/tenderDetailes/762dec1a5b2b4c049fa1392fa4e4a343
користувач: Provider2/Qa123456 
1. Зологінтесь провайдером(постачальником)
2. Відрийте закупівлю в статусі Період Уточнень
3. Прогорніть сторінку

Очікувано: Є можливість задати питання (кнопка Задати Питання).

Фактично:Немає можливості задати питання.

![image](https://cloud.githubusercontent.com/assets/11888281/8747373/fa765798-2c9a-11e5-9893-d29614333bbe.png)

**Comment by lerich** [comment]
Re: [frontend] ЕЛЕГ. Деталі закупівлі. Неможливо задати запитання в перідоді уточнення. (#464)

Так и должно быть. 
Если организация не прошла модерацию, вопросы и др. делать нельзя

С уважением,Валерий Несмашный
E-tender

http://uat.e-tender.biz/#/tenderDetailes/762dec1a5b2b4c049fa1392fa4e4a343
користувач: Provider2/Qa123456 

Зологінтесь провайдером(постачальником)
Відрийте закупівлю в статусі Період Уточнень
Прогорніть сторінку

Очікувано: Є можливість задати питання (кнопка Задати Питання).
Фактично:Немає можливості задати питання.

**Comment by w-be** [comment]
@lerich дякую за інформацію. 
Для автоматизованих тестів потрібно щоб користувач(організація) пройшов модерацію.
Колись був нам наданий адмін: operator1; зараз він вже не адмін.
Чи можна у вас попросити іншого адмін-користувача, або просто підтвердіть модерацію Provider2 ?
