### ISSUE TITLE
NewTend. Пошук закупівлі. Не знаходиться щойно створена закупівля по UAid.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#467]
http://dev23.newtend.com/openprocurement/#/tender/b6c089dbd62a4bea9fca0477ee67f9f5/overview
        login: openprocurement@mailinator.com
        password: 123123 
1. Залогуйтесь в аплікацію
2. Створіть закупівлю.
3. Переконайтесь що закупівля створена - відображається в списку закупівель.
4. Введіть UAid в стрічку пошуку

Очікувано: В списку закупівель залишиться 1 закупівля з відповідним UAid.

Фактично: Відображається повідомлення про те що закупівля не знайдена.

Примітка: деякі закупівлі (старіші) знаходяться без проблем.

![2015-08-26 13 11 20](https://cloud.githubusercontent.com/assets/11888281/9491237/38dfea10-4bf6-11e5-90f6-906cee6cfaf6.png)
![2015-08-26 13 11 31](https://cloud.githubusercontent.com/assets/11888281/9491238/38dffa3c-4bf6-11e5-9bc4-3a4f31364207.png)

**Comment by fashust** [comment]
поскольку сервер тестовый, авторотация поисковых индексов отключена, индексы обновляются в "ручном режиме")
для автоматизации будет удобней использовать прямую ссылку на тендер
ссылка имеет следующий вид - http://dev23.newtend.com/dz/#/tender/tender_id
tender_id - приходит в ответ после создания тендера в поле response

```
{  
   "action":{  
      "can_upload_tender_docs":true,
      "tender_owner":true,
      "can_edit_tender":true,
      "can_invite":true,
      "can_replay_questions":true,
      "show_invites":true,
      "can_cancel_tender":true
   },
   "errors":{  

   },
   "result":true,
   "response":"a2e2ef2daf1b4cfaaa0eb8879273e3c7"
}
```
