### ISSUE TITLE
ЕЛЕГ. Редагування закупівлі. Не активна кнопка Зберегти Зміни після внесення змін.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#468]
http://uat.e-tender.biz/#/updateTender/96deba61c68543f8957526bbe4fe4ff7
Misha2/ Password1

_Кроки до відтворення:_
1. залогуватись замовником
2. перейти у вкладку мої закупівлі 
3. вибрати закупівлю яка знаходиться в статусі "період уточнень", або створити нову закупівлю і перейти на цю ж закупівлю
4. натиснути елемент "редагувати закупівлю"
5. внести будь-які валідні зміни
6. натиснути елемент "зберегти зміни"

_Очікуваний результат:_
Зміни збереглись 
Знаходимось у вкладці "мої закупівлі"

_Фактичний результат:_
Елемент "зберегти зміни неактивний"

![image](https://cloud.githubusercontent.com/assets/11888281/9609306/abcfbebc-50db-11e5-9205-88bbe1d7eb8e.png)

**Comment by S-Shevchenko** [comment]
В работе
