### ISSUE TITLE
ЕЛЕГ. Відсутня кнопка Створити закупівлю

### ISSUE THREAD

**Issue by yboi** [openprocurement/frontend#484]
http://e-tender.biz/#/
Owner1/ Password1

Кроки до відтворення:
1. залогуватись замовником
2. перейти у вкладку мої закупівлі
3. Натиснути кнопку "Створити закупівлю"

Очікуваний результат:
- Логінимось успішно
- Кнопка створити закупівлю відображається і працює

Фактичний результат:
Неможливо створити тендер, відсутня кнопка "Створити закупівлю"
1. переходимо на домашню сторінку, бачимо що є одинакові заголовки і по дві клавіші "Вхід" "Реєрестрація"
   ![2015-09-30 13_36_02](https://cloud.githubusercontent.com/assets/13013223/10191873/aa54f47e-6780-11e5-8826-4529a12e623c.png)
2. Натискаємо клавішу вхід у другому заголовку
   ![2015-09-30 13_36_23](https://cloud.githubusercontent.com/assets/13013223/10192209/6d2c11c4-6783-11e5-9654-8e71a06d1fb3.png)

![2015-09-30 13_36_37](https://cloud.githubusercontent.com/assets/13013223/10191938/3e517aee-6781-11e5-849e-f9fabf2f9f2d.png)

![2015-09-30 13_36_42](https://cloud.githubusercontent.com/assets/13013223/10192219/7ca958aa-6783-11e5-8126-792f266ca62d.png)

![2015-09-30 13_36_42](https://cloud.githubusercontent.com/assets/13013223/10192238/908ef438-6783-11e5-9c5a-3e7e82667c4a.png)
![2015-09-30 13_36_52](https://cloud.githubusercontent.com/assets/13013223/10192409/dd9c8fc8-6784-11e5-90ed-0b614402d431.png)
1. натискаємо "вхід" у першому заголовку, переходить http://bid.e-tender.biz/#/login і логінимось 
   Owner1/ Password1
   ![2015-09-30 13_39_45](https://cloud.githubusercontent.com/assets/13013223/10192287/ea03a43c-6783-11e5-97f9-6fac566b315f.png)
   3.1. Натиснути на "Мої закупівлі", немає кнопки "Створити тендер"
   ![2015-09-30 13_37_46](https://cloud.githubusercontent.com/assets/13013223/10192324/1ef91f0a-6784-11e5-968c-79c3f8a746c9.png)
2. Не можливість задати питання до тестової закупівлі, в статусі Період уточнень
   ![2015-09-30 13_38_20](https://cloud.githubusercontent.com/assets/13013223/10192351/5fae4778-6784-11e5-99ad-bbba07731210.png)

![2015-09-30 13_38_39](https://cloud.githubusercontent.com/assets/13013223/10192360/762c3488-6784-11e5-9fff-1b3937756c19.png)
1. Користувач активований
   ![2015-09-30 13_40_01](https://cloud.githubusercontent.com/assets/13013223/10192368/9294ce3c-6784-11e5-8e3d-c47fc07a8721.png)

**Comment by S-Shevchenko** [comment]
@yboi Дякую. Неможливо створити тендер та подати запитання коростувачам,  які не пройшли модерацію. Дивись коментар @lerich https://github.com/openprocurement/frontend/issues/464

**Comment by selurvedu** [comment]
@yboi, не все так погано. Справа в тому, що production-сервер змінив адресу на http://bid.e-tender.biz/, а тестовий – на http://bid.uat.e-tender.biz/. Стара адреса http://uat.e-tender.biz/ зараз показує таку саму "welcome page", як і http://e-tender.biz/ .

**Comment by myroslav** [comment]
@S-Shevchenko було б добре, якби http://uat.e-tender.biz/ була хоч якось інтегрована з http://bid.uat.e-tender.biz/, бо зараз всі посилання ведуть на продуктивній сайт і дізнатися про існування http://bid.uat.e-tender.biz/ непросто.

Зауважу, що оскільки зараз тестове та продуктивні середовища переплетені є потенційна можливість загнати дані з тестів в продуктивну ЦБД.
