### ISSUE TITLE
NewTend.Подача пропозиції неможлива.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#495]
http://dev23.newtend.com/dz/#/tender/fa813a43be034547b7592cc50355cacd/overview
login: openprocurement@mailinator.com
password: 123123

Відтворення:
1. Залогуйтесь провайдером
2. Знайдіть закупівлю в встатусі подача пропозицій
3. Відкрийте її
4. Подайте пропозицію

Очікувано: Пропозицію можна подати. 

Фактично: Пропозицію не можливо подати. Відсутні відповідні контроли.
![image](https://cloud.githubusercontent.com/assets/11888281/11340252/c8531d48-9205-11e5-86e5-d32027a9c7d9.png)

**Comment by SlaOne** [comment]
Відтворення:
1. Залогуйтесь провайдером.
You should Log in as PROVIDER in the first. The screen you attached - is from Customer's cabinet.

**Comment by w-be** [comment]
@SlaOne Вибачте скріншот дійсно був від Закупівельника, Ось від провайдера, не працює всеодно
![image](https://cloud.githubusercontent.com/assets/11888281/11363989/ed1ba80c-92a5-11e5-8be4-02b0ff51eebd.png)

**Comment by w-be** [comment]
можливо питання в старих (чи поганих) користувачах, я маю таких:  
Закупівельник/Ігровий режим
openprocurement@mailinator.com
Pwrd: 123123 
Постачальник/Ігровий режим
qtest@mailinator.com
Pwrd: 123123 
Постачальник/Режим реальних закупівель
openprocboss@mailinator.com
Pwrd: 123123

**Comment by SlaOne** [comment]
дело не столько в "пользователе", сколько в режиме тендера.
предложенный вами тендер, похоже, создан не в "Тестовом" режиме. Соответственно Вы не можете сделать предложение "Тестовым" пользователем в "Не Тестовый" тендер. 
У меня же получилось сделать ставку "Не Тестовым" пользователем в предоставленный вами тендер.
![bid_made](https://cloud.githubusercontent.com/assets/15046328/11364577/e172b744-92a9-11e5-8fae-008d791095af.jpg)
Обратите внимание на ответ от ЦБД по вашему тенедеру - 
},
tenderID: "UA-2015-11-24-000004",
-enquiryPeriod: {
startDate: "2015-11-24T11:49:12.645733+02:00",
endDate: "2015-11-24T11:58:00+02:00"
},
id: "c94d1b68ad5540498c36016b24e058cb",
dateModified: "2015-11-24T12:41:33.858057+02:00",
awardCriteria: "lowestCost"
}

И по "Тестовому" тендеру от нашей площадки - 
},
tenderID: "UA-2015-11-24-000006",
title_ru: "[ТЕСТИРОВАНИЕ] ",
-enquiryPeriod: {
startDate: "2015-11-24T00:00:00+02:00",
endDate: "2015-11-24T12:13:00+02:00"
},
id: "e663e75b266d4e81903ce948aa64f658",
mode: "test",
dateModified: "2015-11-24T12:11:30.727107+02:00",
awardCriteria: "lowestCost"
}

**Comment by w-be** [comment]
@SlaOne Ви абсолютно праві. Так на тестові тендери, я можу створювати ставки. Проблема дійсно в не відповідності користувачів: Тестовий - Не тестовий. 
Та зараз я вже не можу створити тестовий тендер. видає помилку: 
![image](https://cloud.githubusercontent.com/assets/11888281/11368244/55aaa48e-92c1-11e5-90c0-7bbe6b275ce7.png)
Тож блокуюча проблема: неможливо створити закупівлю тестовим закупівельником. А щоб подати ставку на "реальну" закупівлю, в мене нема користувача.

**Comment by w-be** [comment]
виношу в окрему багу, цю закриваю.
