### ISSUE TITLE
NewTend. Сворення закупівлі не можливе новоствореним користувачом.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#497]
Користувач:
biviktorqc@gmail.com / 3M9EJcQDQk
1. Вікриваєм аплікацію по лінці: http://dev23.newtend.com/ 
2. Логінемось
3. Переходимо до кабінету закупівуельника: копіюєм лінку в адресну стрічку + Ентер. Лінка: http://dev23.newtend.com/openprocurement/#/home/page/1 
4. Натискаєм стрворити закупівлю.
5. Заповнюєм всі поля.
6. Натискаєм Опублікувати.

Очікувано: створюється тестова закупівля.
Фактично: З"являється помилка.

![image](https://cloud.githubusercontent.com/assets/11888281/11395331/0cb67e3a-9373-11e5-9e54-6911b26c5f9f.png)

**Comment by SlaOne** [comment]
ответ в консоли приходит какой? "not a government company"???
вновь созданные пользователи, на нашем сервисе, не имеют обозначение Гос Компания!
Вновь созданные пользователи должны пройти валидацию в колл-центре, после чего им устанавливается флаг - Гос компания, после чего можно создавать торги.
Так что поведение - ожидаемое и правильное.
могу переключить вашего пользователя.

**Comment by w-be** [comment]
@SlaOne так, переключіть будь-ласка.

**Comment by SlaOne** [comment]
user - ten2312@mailinator.com, pass - 123123 - гос компания, тестовый, может создавать тендеры
user - ten2315@mailinator.com, pass - 123123 - тестовый, поставщик, не может создавать тендеры
вашего пользователя переключил в тестовый, гос компания, может создавать тендеры.
путь в кабинет провайдера - http://dev23.newtend.com/dz/provider

**Comment by w-be** [comment]
Дякую за наданих користувачів - якраз те що треба.
