### ISSUE TITLE
ЕЛЕГ. Мій кабінет незавантажуєтья "Мої закупівлі".

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#498]
User: misha2 / Password1
link: http://bid.uat.e-tender.biz/#/profile

Відткорення:
1. Залогінитись в систему Закупівельником.
2. Пернейти до меню Мої Закупівлі.

Очікувано: Меню загрузилось. Є можливість натиснути кнопку Створити Закупівлю.

Фактично: З"являється помилка в сервер ерор в нижньому правому куті. Завантаження зависає. Кнопка Створити Закупівлю неактивна.

![image](https://cloud.githubusercontent.com/assets/11888281/11396579/208a8548-937b-11e5-93aa-30de4b300cc7.png)

**Comment by lerich** [comment]
Проверяйте, работает
