### ISSUE TITLE
NewTend. Картка закупівлі. Підкажіть як кваліфікувати переможця.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#499]
Користувач:
ten2312@mailinator.com, pass - 123123
Лінка: http://dev23.newtend.com/dz/#/tender/f19a1eaecd3948c3a9800eaea4100f44/auction

Підкажіть, будь-ласка, як кваліфікувати переложця?
Етап - кваліфікація переможця, Тендер відкрито тим хто створював, через меню мої закупівлі. Взяло участь 3 учасника 1 з них є не підтверженим(не кваліфікованим) перможцем. Скріншот на табі торги. Може на ньютенді, ще є якийсь таймаут перед підтверженням перемоги?
![image](https://cloud.githubusercontent.com/assets/11888281/11423386/9442639e-944c-11e5-925b-9dfea03741fa.png)

**Comment by SlaOne** [comment]
тайм аутов - нет. сейчас перепроверим, что к чему, в понедельник работало. может связано с изменениями на тестовом сервере

**Comment by SlaOne** [comment]
тендер по какой-то причине не засинкался (работаем над устранением подобных причин). можете проверять. теперь работает
