### ISSUE TITLE
При яких умовах тендер міняє статус з «Заявки» на «Помилковий»?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#50]

**Comment by myroslav** [comment]
В ЦБД немає статусу "Помилковий" якщо майданчик реалізує такий статус - то буду вдячний за розшифровку.

**Comment by S-Shevchenko** [comment]
Майданчик - e-tender
Заявка - active.enquiries
Помилковий -  unsuccessful

**Comment by myroslav** [comment]
Кращий прееклад статусу `active.enquiries` - "Період уточнень", "Уточнення", "Питання/відповіді".

Заявки подаються в період `active.tendering`, який можна перекласти як "Прийом/подача заявок/пропозицій".

Кращий преклад татусу `unsuccessful` є "**Неуспішний**" цей стан набувається у виападку коли:
1. не було жодної пропозиції, тоді одразу після періоду прийому пропозицій тендер туди потрапляє
2. всі пропозиції були відхилені, минув stand-still період (10 днів), і тоді тендер помічається як неуспішний

**Comment by lerich** [comment]
Давайте вынесем это в доку на украинском языке и сделаем на всех площадках одинаково

**Comment by myroslav** [comment]
Давайте: https://drive.google.com/open?id=17bTdLCnOnT8fu5dIyBez3i1mVym_OiSdUXXAHf6RSuA

**Comment by lerich** [comment]
сделали
