### ISSUE TITLE
Період уточнення. Не можна задати питання. Немає контролів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#501]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
Тендер ID:  UA-2015-11-27-000002

Відтворення:
1. Залогінтесь в аплікацію провайдером
2. Знайдіть закупівлю в періоді уточнення
3. Відкрийте її
4. Перейдіть на вкладку уточнення

Очікувано: є можливість задати питання.

Фактично: на основній табі та табі уточнення не має ніяких контролів - задати питання.

![image](https://cloud.githubusercontent.com/assets/11888281/11472630/89e6437a-9776-11e5-9aff-86faa8269005.png)

**Comment by sergejbondik** [comment]
Исправлено. Вопросы может задавать только авторизованный пользователь
