### ISSUE TITLE
Період уточнення. Не можна оскаржити закупівлю. Натискання кнопки не працює.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#502]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
Тендер ID: UA-2015-11-27-000002

Відтворення:
1. Залогінтесь в аплікацію провайдером
2. Знайдіть закупівлю в періоді уточнення
3. Відкрийте її
4. Перейдіть на вкладку Жалобы
5. Натисніть кнопку Подать жалобу

Очікувано: Відкривається форма подачі скарги.

Фактично: Нічого не відбувається.

**Comment by sergejbondik** [comment]
При нажатии на кнопку вызывается функция написания письма через почтовый клиент.
