### ISSUE TITLE
ПРОМ. Створення закупівлі. Закупівля не отримує TenderID

### ISSUE THREAD

**Issue by yboi** [openprocurement/frontend#503]
http://my.dz-test.net/cabinet/purchases/state_purchase/add
користувач:
vbilos@softserveinc.com
Qw123456

Відтворення:
1. Заклогінтесь на майданчик як закупівельник
2. Відкрийте форму створення закупівлі
3. Введіть усі потрібні дані (валідні) 
4. Збережіть закупівлю

Очікувано: Закупівля отримує TenderID: "приклад" UA-2015-10-19-000032 
Фактично: ID: ожидание...
TenderID: ожидание...
![2015-11-30 16 01 14](https://cloud.githubusercontent.com/assets/13013223/11473671/585e9b94-977c-11e5-9e24-ee5b0e133e85.png)

Примітка: цю закупівлю ми не можемо знайти іншими користувачами.

**Comment by Rzaporozhets** [comment]
Fixed

2015-11-30 16:08 GMT+02:00 yboi notifications@github.com:

> http://my.dz-test.net/cabinet/purchases/state_purchase/add
> користувач:
> vbilos@softserveinc.com
> Qw123456
> 
> Відтворення:
> 1. Заклогінтесь на майданчик як закупівельник
> 2. Відкрийте форму створення закупівлі
> 3. Введіть усі потрібні дані (валідні)
> 4. Збережіть закупівлю
> 
> Очікувано: Закупівля отримує TenderID: "приклад" UA-2015-10-19-000032
> Фактично: ID: ожидание...
> TenderID: ожидание...
> [image: 2015-11-30 16 01 14]
> https://cloud.githubusercontent.com/assets/13013223/11473671/585e9b94-977c-11e5-9e24-ee5b0e133e85.png
> 
> Примітка: цю закупівлю ми не можемо знайти іншими користувачами.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openprocurement/frontend/issues/503.

## 

---

Best regards,

Zaporozhets Roman

QA Automation Engineer

Prom.ua, Tiu.ru, Deal.by, Satu.kz

address: Kharkivske Highway, 201/203, office 316, 02000, Kiev, Ukraine

phone: +38 (067) 99-416-00

skype: zaporogech

**Comment by Rzaporozhets** [comment]
Fixed
