### ISSUE TITLE
IE. Картка закупівлі - Не відображаються значення полів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#504]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
Тендер ID: UA-2015-11-27-000002

Відтворення:
1. Зайдіть в аплікацію в ІЕ 11
2. Знайдіть закупівлю
3. Відкрийте її

Очікувано: Картка закупівлі нормально відображається.

Фактично: Не відображаються значення полів.

Версія ІЕ:
![image](https://cloud.githubusercontent.com/assets/11888281/11475608/f4abbe6e-9786-11e5-9e05-ac7f3a0ab169.png)

![image](https://cloud.githubusercontent.com/assets/11888281/11475575/c5400004-9786-11e5-8d0d-e09ce1b353a8.png)

**Comment by sergejbondik** [comment]
Поддержка данного браузера - обязательное условие?
Стандартно поддерживаем Firefox, Chrome

**Comment by w-be** [comment]
@dn080985bsa Насскільки я знаю - це необов"язкова умова. Баг не критичний.
@myroslav Підтвердіть, будь-ласка, щоб вже напевно.

**Comment by sergejbondik** [comment]
Официально площадкой поддерживаются следующие браузеры Firefox, Chrome. Корректная работа в других браузер не гарантируется.

Возможная причина текущей ошибки: примите сертификат тестовых серверов площадки ПриватМаркет.

**Comment by w-be** [comment]
"Возможная причина текущей ошибки: примите сертификат тестовых серверов площадки ПриватМаркет." - сертефикат принятий, як і на інших браузерах.

**Comment by w-be** [comment]
Відповідно до результатів наради: не суттєво.
