### ISSUE TITLE
Пошук закупівлі, та картка закупівлі. Багатопредметний тендер представлений, як набір однопридметних закупівель.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#505]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
Тендер ID: UA-2015-11-27-000002 (багатопридметний тендер)

Відтворення:
1. Зайдіть в аплікацію
2. Знайдіть закупівлю по UA_id
3. Відкрийте її

Очікувано: Знаходиться одна закупівля, яка при відкриті містить 2(чи більше) блоків предмет закупівлі, з розрахунку 1 блок на 1 предмет.

Фактично: Багатопридметний тендер відображаєьться, як список майже однакових однопридметних тендерів, в яких відміний предмет закупівлі.

![image](https://cloud.githubusercontent.com/assets/11888281/11478529/44ad8b54-9796-11e5-8987-36fd92863d6f.png)

**Comment by sergejbondik** [comment]
![default](https://cloud.githubusercontent.com/assets/15994869/11627129/e3f3b346-9cf0-11e5-9692-65f5d922eea7.png)
![default](https://cloud.githubusercontent.com/assets/15994869/11627130/e40d5e36-9cf0-11e5-8efc-d71d9d972676.png)

исправлено.

**Comment by w-be** [comment]
Тепер зникли позиції:
![image](https://cloud.githubusercontent.com/assets/11888281/11691953/f053b0c6-9ea5-11e5-92ec-95f2fb2b5351.png)

**Comment by sergejbondik** [comment]
Исправлено
