### ISSUE TITLE
Відмінена закупівля. Не відображається причина та час відміни закупівлі.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#506]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
Тендер ID: UA-2015-12-01-000005-1

Відтворення:
1. Зайдіть в аплікацію
2. Знайдіть закупівлю по UA_id
3. Відкрийте її

Очікувано: Якщо закупівля в статусі Відмінена, відображеється час і причина відміни.

Фактично: На картці закупівлі, чи на табі, чи в попапі, немає інформації про відміну: час і причина.

![image](https://cloud.githubusercontent.com/assets/11888281/11498803/6429896c-982a-11e5-9eea-c829fcbfb332.png)

**Comment by sergejbondik** [comment]
Исправлено 03.11.2015 9:00

**Comment by sergejbondik** [comment]
![506](https://cloud.githubusercontent.com/assets/15994869/11556068/1a78c4f2-99ad-11e5-8bff-1e26b690c4a8.png)
![default](https://cloud.githubusercontent.com/assets/15994869/11556069/1a79523c-99ad-11e5-9a74-205bea1696a4.png)
