### ISSUE TITLE
ПРОМ. Створення закупівлі. Створення якісного показника.

### ISSUE THREAD

**Issue by yboi** [openprocurement/frontend#508]
http://my.dz-test.net/cabinet/purchases/state_purchase/add
користувач:
vbilos@softserveinc.com
Qw123456

Відтворення:
1. Заклогінтесь на майданчик як закупівельник
2. Відкрийте форму створення закупівлі
3. Введіть усі потрібні дані (валідні) 
4. Натиснути "Додати показник"

Очікувано: Відображається 2-ві кнопки одна на "Додати показник" інша "Видалити показник"
Фактично: Відображається 2-ві кнопки "Додати показник" 
![2015-12-01 13 52 59](https://cloud.githubusercontent.com/assets/13013223/11500196/3d653c9a-9834-11e5-9333-8144c2ec6c8e.png)
Примітка: При відображенні двох одинакових кнопок, перша кнопка "Додати показник" виконує ф-цію для "Видалення показника". Друга кнопка  "Додати показник" додає ще один показник.

**Comment by darchik** [comment]
fixed
