### ISSUE TITLE
ПРОМ. Створення нецінових показників для рівня предмета закупівлі не імплементовано

### ISSUE THREAD

**Issue by yboi** [openprocurement/frontend#509]
http://my.dz-test.net/cabinet/purchases/state_purchase/add
користувач:
vbilos@softserveinc.com
Qw123456

Відтворення:
1. Заклогінтесь на майданчик як закупівельник
2. Відкрийте форму створення закупівлі
3. Введіть усі потрібні дані (валідні) 

Очікувано: Можливість створення нецінових показників для рівня предмета закупівлі 
Фактично: Немає можливості для створення нецінових показників для рівня предмета закупівлі 
![2015-12-01 15 25 50](https://cloud.githubusercontent.com/assets/13013223/11501835/d0e22d9c-983f-11e5-995e-eef47c449855.png)

Примітка: Є можливість створення нецінових показників для рівня всієї закупівлі

**Comment by Rzaporozhets** [comment]
​​
Сейчас все работает, один нюанс в переводе кнопок (
http://joxi.ru/E2pvx8esBBpeLr ) - первая кнопка удаляет показатель, 2
добавляет еще 1. Скоро поправим

2015-12-01 15:26 GMT+02:00 yboi notifications@github.com:

> http://my.dz-test.net/cabinet/purchases/state_purchase/add
> користувач:
> vbilos@softserveinc.com
> Qw123456
> 
> Відтворення:
> 1. Заклогінтесь на майданчик як закупівельник
> 2. Відкрийте форму створення закупівлі
> 3. Введіть усі потрібні дані (валідні)
> 
> Очікувано: Можливість створення нецінових показників для рівня предмета
> закупівлі
> Фактично: Немає можливості для створення нецінових показників для рівня
> предмета закупівлі
> [image: 2015-12-01 15 25 50]
> https://cloud.githubusercontent.com/assets/13013223/11501835/d0e22d9c-983f-11e5-995e-eef47c449855.png
> 
> Примітка: Є можливість створення нецінових показників для рівня всієї
> закупівлі
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openprocurement/frontend/issues/509.

## 

---

Best regards,

Zaporozhets Roman

QA Automation Engineer

Prom.ua, Tiu.ru, Deal.by, Satu.kz

address: Kharkivske Highway, 201/203, office 316, 02000, Kiev, Ukraine

phone: +38 (067) 99-416-00

skype: zaporogech

**Comment by yboi** [comment]
Так тут немає можливості для створення нецінових показників для рівня предмета закупівлі  (http://joxi.ru/J2b6eoKu4xb8n2)

**Comment by Rzaporozhets** [comment]
Это еще в разработке и скоро будет реализовано, пока так.

2015-12-01 15:59 GMT+02:00 yboi notifications@github.com:

> Так тут немає можливості для створення нецінових показників для рівня
> предмета закупівлі (http://joxi.ru/J2b6eoKu4xb8n2)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openprocurement/frontend/issues/509#issuecomment-160977327
> .

## 

---

Best regards,

Zaporozhets Roman

QA Automation Engineer

Prom.ua, Tiu.ru, Deal.by, Satu.kz

address: Kharkivske Highway, 201/203, office 316, 02000, Kiev, Ukraine

phone: +38 (067) 99-416-00

skype: zaporogech
