### ISSUE TITLE
Чи можна в подальшому якось працювати з Помилковими тендерами? Чи це передбачено в поточній реалізації?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#51]

**Comment by myroslav** [comment]
Будь який тендер можна скасувати. Якщо ви розшифруєте термін  "помилковий тендер" - то розповім більше.

**Comment by yuliyaSoftserve** [comment]
я мала на увазі статус - "Помилковий", при яких вхідних даних тендер має такий статус?

**Comment by myroslav** [comment]
Виглядає, що це "неуспішний" тендер (`unsuccessful`), цей статус є "термінальний", і з нього неможливо вийти. Цей статуцс свідчить, що не вдалося знайти постачальника.

**Comment by lerich** [comment]
Функциональность ЦБД
