### ISSUE TITLE
Тестовий режим не імплементовано.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#510]
На майданчику для ролей провайдер та переглядач(не потребує логування) відображається тільки реальні тендери. Зайти на майданчик в тестовому режимі не можливо.
Чи є відсутність цієї функціональності критичним багом з огляду того, що майданчик не має ролі закупівельник?

Детальний опис:
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
Відтворення:
0. Створіть тестовий тендер на іншому майданчику.
1. Залогінтесь в аплікацію як провайдер
2. спробуйте знайти тестовий тендер

Очікувано: Провайдер має можливість працювати в тестовому режимі: знаходити тендери та робити заявки на участь.

Фактично: На майданчику відображаються тільки реальні тендери.

**Comment by sergejbondik** [comment]
Реализовано
![default](https://cloud.githubusercontent.com/assets/15994869/11864501/cbec9788-a4a5-11e5-856f-1f200e0c44d7.png)
