### ISSUE TITLE
Подача пропозиції неможлива - З"являється помилка оновлення бази данних.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#512]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
Тендер ID: UA-2015-12-02-000011-2 (тендер в статусі прийом пропозицій)

Відтворення:
1. Зайдіть в аплікацію як провайдер
2. Знайдіть закупівлю по UA_id
3. Відкрийте її
4. Натисніть кнопку Заявка

Очікувано: Відкривається форма подачі заявки

Фактично: З"являється помилка оновлення бази даних
![image](https://cloud.githubusercontent.com/assets/11888281/11528269/5e171b60-98ee-11e5-8ab4-ac9d13c2652b.png)

**Comment by sergejbondik** [comment]
Исправлено 03.11.2015 10:00
![2015-12-03 11 11 08](https://cloud.githubusercontent.com/assets/15994869/11556438/3691b43a-99af-11e5-9e88-44d62d9c23ec.png)
