### ISSUE TITLE
Логін. Неможливо залогуватись.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#519]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
користувач: 0978563295 / Qw123456

Відтворення:
1. Зайдіть на майданчик
2. Натисніть Мой Кабинет
3. Введіть логін та пароль
4. Натисніть Войти

Очікувано: корестувач логінеться.

Фактично: з"являється "Внутренняя ошибка сервера".

![image](https://cloud.githubusercontent.com/assets/11888281/11590576/dc808a3e-9a99-11e5-9014-bcf4394770d6.png)

**Comment by sergejbondik** [comment]
Исправлено

**Comment by w-be** [comment]
Після логування видно помилку на місці списку тендерів:
![image](https://cloud.githubusercontent.com/assets/11888281/11628198/bce8ee76-9cf8-11e5-98c2-dbd9ad51fe18.png)
