### ISSUE TITLE
Чи є можливість видалити Помилкові  тендери?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#52]

**Comment by myroslav** [comment]
Тендер можна скасовувати, після скасування він залишається в системі в скасованому статусі. В залежності від реалізації конкретного майданчика може вводитися статус "чорновик", в якому аукціон не потрапляє в Центральну Базу Даних (ЦБД), і тоді майданчик може пропонувати можливість знищувати такий Тендер (до публікації в ЦБД).

**Comment by yuliyaSoftserve** [comment]
Дякую, мене цікавить чи є можливість скасувати помилковий тендер для майданчика №3 (http://services.e-tender.biz:99/#/)? якщо так то вкажіть де саме

**Comment by lerich** [comment]
на етендере помилковый тендер скасувуется заказчиком, внизу кнопка "Відмінити тендер"
