### ISSUE TITLE
Не цінові показники не відображаються в ставці в режимі перегляду неавторизованим користувачом.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#520]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
Тендер ID:  UA-2015-12-02-000019-1 (має ставку з неціновими показниками)
https://api-sandbox.openprocurement.org/api/0.9/tenders/16386f46082f401b990609220c7fb974

Відтворення:
1. Зайдіть в аплікацію
2. Знайдіть закупівлю по UA_id
3. Відкрийте її
4. Знайдіть нецінові показники в ставці

Очікувано: Нецінові показники, зменшуючий коефіцієнт, приведина ціна відображається в ставці учасника, претендента.

Фактично: Нецінові показники в ставці не відображаються.

![image](https://cloud.githubusercontent.com/assets/11888281/11687387/15ab2820-9e8f-11e5-8c70-a2b014bbe2e6.png)

**Comment by sergejbondik** [comment]
добавлены

**Comment by w-be** [comment]
Все ок крім приведеної суми.
На попапі не правильно рахується Приведена сума, треба: сума поділити на понижуючий коефіцієнт. (id= UA-2015-12-10-000010-2, тут 20000)
![image](https://cloud.githubusercontent.com/assets/11888281/11741525/551013da-a002-11e5-8679-d38dc99a54a6.png)

**Comment by sergejbondik** [comment]
Исправлено
![2015-12-11 14 43 58](https://cloud.githubusercontent.com/assets/15994869/11744091/fae014aa-a015-11e5-94fa-29381d7ef27e.png)
