### ISSUE TITLE
Аукціон. Продавець не отримує лінку для участі.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#521]
https://pmarket-rc.privatbank.ua/app_dev.php/shop/tenders/row/20472722
Тендер ID: UA-2015-12-09-000007-2

Відтворення:
1. Залогінтесь в аплікацію як продавець
2. Перейдіть на вкладку Мій кабінет - Тендери
3. Відкрийте тендер в якому є зроблена вами ставка і який в статусі Аукціон.
4. Перейдіть по лінці, щоб прийняти участь в аукціоні

Очікувано: Користувач має можливість зайти в аукціон, в якості продавця і мати змогу торгуватись.

Фактично: Користувач заходить на аукціон в якості спостерігача.

![image](https://cloud.githubusercontent.com/assets/11888281/11715506/24f92a90-9f4b-11e5-8639-b0863fd493c8.png)

**Comment by w-be** [comment]
Крім того ставка робиться від імені іншого користувача:
![image](https://cloud.githubusercontent.com/assets/11888281/11716708/798a0bde-9f54-11e5-90bb-85eae56bda98.png)

**Comment by sergejbondik** [comment]
1. Ссылка добавлена.
2.  Мосик  - это и есть поставщик.  он ФЛП.
