### ISSUE TITLE
В секції кваліфікація учасників не відображаються наявність документів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#524]
https://pmarket-rc.privatbank.ua/app_dev.php/shop/tenders/row/20472722
Тендер ID:  UA-2015-12-10-000008-2

Відтворення:
1. Зайдіть в аплікацію
2. Знайдіть закупівлю в статусі кваліфікація
3. Перевірте документи учасників та претиндента в секції кваліфікація

А секції Учасники всі документи є а в секції Кваліфікація немає. Це може привести до помилкового враження, що кандидат на перемогу не має документів. Чи варто було б їх подати в обох секціях?

**Comment by sergejbondik** [comment]
Исходили из того, что в квалификации отображаются только документы квалификации, а не заявки на участие. Напр.  Протокол

**Comment by eyvil** [comment]
при реалізації, ми виходили з того, в інформації закупівлі, що приходить від ПроЗорро, документи пропозицій та документи кваліфікації рзділені

**Comment by sergejbondik** [comment]
Доработано.  Документы отображаются в обоих блоках
