### ISSUE TITLE
Кваліфікація. Продавець не може додати документи.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#525]
https://pmarket-rc.privatbank.ua/app_dev.php/shop/tenders/row/20472722
 UA-2015-12-10-000008-2

Відтворення:
1. Залогінтесь в аплікацію як продавець
2. Перейдіть на вкладку Мій кабінет - Тендери
3. Відкрийте тендер в якому ви зараз на кваліфікації як переможець.
4. Додайте документи
5. Проапдейтуйте документи

Очікувано: Користувач має можливість додавати нові документи та оновляти вже існуючі, або щойнододані.

Фактично: Нема можливості додавати документи продавцем в періоді кваліфікація.

![image](https://cloud.githubusercontent.com/assets/11888281/11745428/b371ccca-a020-11e5-857a-e4c8bf592bc1.png)

**Comment by sergejbondik** [comment]
Исправлено.  
1. Клик по участнику. 
2. Если есть право вкладывать - то можно добавить/удалить файлы

**Comment by w-be** [comment]
Видалення документа видаляє тільки з інтерфейсу Приватмаркета. На іншому майданчику і в json видно всі документи.
UA-2015-12-09-000007-2, https://lb.api-sandbox.openprocurement.org/api/0.9/tenders/57d22ae9cc92432ab9e31c62831eba90

**Comment by eyvil** [comment]
не подивились, що можливості видалення документів через API ProZorro на даний момент немає. Прибрали цей функціонал з майданчика ПриватМаркет для тих документів, що вже потрапили до ЦБД

**Comment by sergejbondik** [comment]
Удаление не предусмотрено по АПИ:
1. удалеям если еще не было синхронизации с ЦБД.
2. добавлена возможность замены файла.

**Comment by w-be** [comment]
Продавець знов не може додавати документи в періоді кваліфіказія. UI_id: UA-2015-12-11-000002-1(назва закупівлі: short) 
![image](https://cloud.githubusercontent.com/assets/11888281/11870973/e5af50aa-a4d4-11e5-9268-443f972cc01f.png)
