### ISSUE TITLE
Кваліфікація. Дублікується рішення відміни з посиланням на скаргу.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#526]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
 UA-2015-12-11-000002-1

Відтворення:
1. Залогінтесь в аплікацію як продавець
2. Перейдіть на вкладку Мій кабінет - Тендери
3. Відкрийте тендер в якому Ваша пропозиція відхилена в етапі кваліфікації.

Очікувано: В секції кваліфікація є запис про відміну.

Фактично: В секції кваліфікація є 2 записи про відміну. 1 з них пише що скарга відхилина, хоч ніякої скарги не подавалось.

![image](https://cloud.githubusercontent.com/assets/11888281/11746939/11141768-a029-11e5-9b71-ccb3bb12054a.png)

**Comment by eyvil** [comment]
при синхронизації, за посиланням https://lb.api-sandbox.openprocurement.org/api/0.9/tenders/348c1d68e97f4aad98863a379539e52e в секції awards(кваліфікація) отримано 2 записи за пропозицією. це штатна ситуація і в цьому віпадку потрібно групувати подібні записи? за яким критерієм?

**Comment by sergejbondik** [comment]
Исправлено
