### ISSUE TITLE
Подача пропозиції. Нема можливості видалити документ.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#527]
https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
 UA-2015-12-11-000004-1 
Примітка: як обхід можна скасувати пропозицію і подати заново.

Відтворення:
1. Зайдіть в аплікацію як постачальник
2. Знайдіть закупівлю в статусі подача пропозиції, 
3. Подайте пропозицію
4. Додайте документи
5. Видальте документ

Очікувано: Документ можна видалити. 

Фактично: Нема можливості видалити документ.

![image](https://cloud.githubusercontent.com/assets/11888281/11747970/ab5c149c-a02e-11e5-8214-8872e6ed11b9.png)

**Comment by sergejbondik** [comment]
Вернуть себе - это не отмена. Отмена становится доступной после возврата себе. Условно Возврат себе - это доступ к редактированию.
