### ISSUE TITLE
Кваліфікація. Оновлення контракту виглядає, як окремі файли.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#528]
https://pmarket-rc.privatbank.ua/app_dev.php/shop/tenders/row/20472722
 UA-2015-12-11-000004-1 
Тендер має завантажені стару і нову версії контракту.

Відтворення:
1. Залогінтесь в аплікацію як продавець
2. Перейдіть на вкладку Мій кабінет - Тендери
3. Відкрийте тендер в якому ви зараз як кваліфікований переможець.
4. Відкрийте документи В кваліфікації

Очікувано: Файли відображаються, як 2-і версії 1-ого файлу (старіша перекреслена).

Фактично: Файли відображаються, як 2 окремих файли.
![image](https://cloud.githubusercontent.com/assets/11888281/11749246/4b143ab8-a035-11e5-891d-e7c313cb8c33.png)

**Comment by eyvil** [comment]
згортання версій файлів реалізовано. чи вірно я розумію із задачі, що контракт може бачити тільки учасник, до якого він відноситься?

**Comment by sergejbondik** [comment]
Исправлено
