### ISSUE TITLE
Пропозиції розлянуті. Не відображається статус на картці закупівлі.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#529]
https://pmarket-rc.privatbank.ua/app_dev.php/shop/tenders/row/20472722
UA-2015-12-11-000004-1 

Статус в https://api-sandbox.openprocurement.org/api/0.9/tenders/9016d5c9a9ec4cc593483094cc953af8 
"status": "active.awarded"

Відтворення:
1. Залогінтесь в аплікацію 
2. Відкрийте тендер в якому пропозиції розглянуті, є переможець і контракт не підписаний.

Очікувано: Статус Предложения рассмотрены

Фактично: Статус -
![image](https://cloud.githubusercontent.com/assets/11888281/11749821/9ac3e65a-a038-11e5-8dfb-6c8d6bd9d581.png)

**Comment by w-be** [comment]
Також не відображається статус Закінчено:
![image](https://cloud.githubusercontent.com/assets/11888281/11781247/235522d8-a271-11e5-863a-a6033d9f4c6a.png)

**Comment by sergejbondik** [comment]
Исправлено
