### ISSUE TITLE
Тендер. Час «Початку аукціону» - визначається автоматично. Який алгоритм визначення?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#53]

**Comment by myroslav** [comment]
Зараз алгоритм наступний:

> аукціон назначається на наступний день після закінчення прийому пропозицій, якщо в тому дні ще є "місце" для аукціону, якщо немає - то на наступний день, якщо немає - то на наступний і т.д. Аукціони з тією самою CPV групою не мають перекриватися почасу.

Це коротко, насправді зараз є деякі компроміси між "точністю" та зручністю, і тому алгоритм може давати перекривання по часу.
