### ISSUE TITLE
Обговорення. Тестовий режим. Не можна задати питання, довге і/або з спец символами.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#532]
Примітка: Недовгий текст без спеціальних символів не спричиняє помилки.

https://pmarket-rc.privatbank.ua/app_dev.php/business/tenders
UA-2015-12-17-000002-1 
Спецсимволи: ~!@#$%^&*()_+{ }:"|<>?`-=[];,./\'№

Відтворення: 
1. Зайти в аплікацію, як продавець.
2. Перейти в тестовий режим.
3. Знайти закупівлю в періоді уточнення
4. Спробувати задати питання з великою кількістю знаків і/або зспец символами.

Очікувано: Можливо задати питання.

Фактично: Питання задати не можливо. Помилка бази даних.

![image](https://cloud.githubusercontent.com/assets/11888281/11867139/d93fef36-a4b7-11e5-883f-7e86662e5a93.png)

**Comment by sergejbondik** [comment]
Исправлено.

**Comment by w-be** [comment]
Всеодно бачу помилку: 
![image](https://cloud.githubusercontent.com/assets/11888281/11872458/133261d0-a4de-11e5-9f15-cc1236b1e887.png)
