### ISSUE TITLE
Запитання. Неможливо задати запитання.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#536]
http://ubiz.iov.zt.ua/tender/question/2286
vbilos@softserveinc.com / Qw123456

Відтворення:
1. Знайдіть закупівлю в статусі Уточнення.
2. Відкрийте її
3. Перейдіть до таби Питання/Відповіді.
4. Внесіть текст заголовок, тіло
5. Натисніть Задати питання

Очікувано: Питання задане. З"явилось підтвержуюче повідомлення.

Фактично:З"являється повідомлення про помилку.

![image](https://cloud.githubusercontent.com/assets/11888281/11958021/f889279e-a8cd-11e5-88cd-d430e991f3db.png)

**Comment by iovzt** [comment]
Останнім часом часто повертається помилка "тендер не знайдено", нижче повні запит/відповідь:

REQUEST:

POST /api/0/tenders/6a1cc79b842f4964b95139d271451ed2/questions?acc_token= HTTP/1.1
Authorization: Basic MWEyNGQ1M2ViYzdhNDZiZmFkNTFiM2ZiMTU3ZjA5ZmI6
Host: lb.api-sandbox.openprocurement.org
Connection: close
Accept-Encoding: gzip, deflate
User-Agent: Zend\Http\Client
Content-Type: application/json; charset=UTF-8
Content-Length: 1053
Cookie: SERVER_ID=6bc693057290cb7bd62642255a79c7fec9caa21982449b5819e83302bed2ec024a7867afbb539dfd352bf00d5efb81a2a9a7df13df8ea72a38e12f71e2391029; AWSELB=27F925171E32E6922BE4D34F0A3E9F60974F1EB419A26E5E9F7C5955688F80D15F208A357E9FFEE14865DBC4F839920569396F64579E1B83BA2249EF168A509DA0509D0E5BCC0008F353684D1ECD8A9DE58B20E168
Expect: 100-continue

{"data":{"author":{"name":"Віктор тест","identifier":{"scheme":"UA-EDR","id":"12345671","legalName":"Віктор тест"},"address":{"streetAddress":"м. Львів Головна 14","locality":"Дрогобицький район","region":"Львівська область","postalCode":"12345","countryName":"Україна"},"contactPoint":{"name":"Білостенний Віктор","email":"vbilos@softserveinc.com","telephone":"+3800978563295"}},"title":"тестове запитання","description":"тестове запитання"}}

RESPONSE:

HTTP/1.1 404 Not Found
Content-Type: application/json; charset=UTF-8
Date: Tue, 22 Dec 2015 20:42:14 GMT
Server: nginx/1.4.7
X-Request-ID: req-7ba64775-f7a0-41b1-9e8f-fe8a8bcd0af2
Content-Length: 101
Connection: Close

{"status": "error", "errors": [{"location": "url", "name": "tender_id", "description": "Not Found"}]}

**Comment by w-be** [comment]
Спробував на інших закупівлях: питання задається.
