### ISSUE TITLE
Пошук закупівлі по UA_id не працює.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#537]
http://ubiz.iov.zt.ua/tender/index?query=UA-2015-10-22-000032
vbilos@softserveinc.com / Qw123456

Відтворення:
1. Зайдіть на сторінку з списком тендерів.
2. Внесіть в пошукову стрічку UI_id ( UA-2015-10-22-000032 )
3. Натисніть пошук.

Очікувано: Закупівля знайдена.

Фактично: Список закупівель оновлюється. Перша закупівля в списку не та яку шукали.
![image](https://cloud.githubusercontent.com/assets/11888281/11975197/e5d849da-a973-11e5-85fc-a3a2564ff151.png)

**Comment by iovzt** [comment]
виправив
