### ISSUE TITLE
Словник кодів товарів/послуг містить зайві значення.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#541]
Лишні опції в словнику unit які не не підтримуються іншими майданчиками, код (ім'я):
1 (1), 11 (11), 3 (3), 44617100-9 (item), кг (кг), RH (людино година), т (т) шт (шт).

Також в інтерфейсі вжито англійську назву: TNE (Metric tone) замість TNE (тони) (російська).

Рекомендуємі коди: http://standards.openprocurement.org/unit_codes/recommended/uk.json
Лінка на закупівлю через апі: https://api-sandbox.openprocurement.org/api/0.9/tenders/55e3d9011f3d48d3872fae29a876108e
http://ubiz.iov.zt.ua/tender/update/3937
vbilos@softserveinc.com / Qw123456

Відтворення:
1. Залогуйтесь як закупівельник
2. Відкрийте Закупівлю в статусі обговорення.
3. Змініть код товару/послуги.
4. Збережіть закупівлю.
5. Перевірте результат в ЦБД.

Очікувано: допустимі коди такі ж, як і рекомендуємі.

Фактично: Є зайві коди одиниць: дублікати, не існуючі коди.
![image](https://cloud.githubusercontent.com/assets/11888281/11978821/fe6fa290-a996-11e5-85c0-96649fe742c7.png)

**Comment by w-be** [comment]
Такж дивно в ЦБД виглядають кілометри:
  "code": "KMT",
  "name": "\tкм\t"
Це не критично адже код стандартний.

**Comment by iovzt** [comment]
виправлено
