### ISSUE TITLE
Створення закупівлі. Регіон та місто зберігаються як код, а не як текст.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#542]
Лінка на закупівлю через апі: https://api-sandbox.openprocurement.org/api/0.9/tenders/7975e684397d4681b1062a7665abf26e
http://ubiz.iov.zt.ua/tender/3949
vbilos@softserveinc.com / Qw123456

Відтворення:
1. Залогуйтесь як закупівельник
2. Створіть закупівлю
3. Перевідкрийте закупівлю (без редагування)
4. Перевірте "region": та "locality"

Очікувано:Область та район прописані текстом на інтерфейсі та в ЦБД.

Фактично: Область та район прописані кодом. В ЦБД також код, тож інші майданчики також не "зрозуміють".

![image](https://cloud.githubusercontent.com/assets/11888281/11979531/c6646844-a99c-11e5-91bf-49b6a55a28a5.png)

**Comment by iovzt** [comment]
виправив
