### ISSUE TITLE
Квалівікація і пізніше. На картці закупівлі немає посилання на аукціон (історію)

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#543]
Чи доцільно було б добавити? 
На етапі Аукціон така кнопка і лінка є на картці закупівлі.

http://ubiz.iov.zt.ua/tender/2714
vbilos@softserveinc.com / Qw123456

Відтворення:
1. Знайдіть закупівлю в статусі Завершена (в неї має бути більше 1 закупівельника).
2. Відкрийте її
3. Перейдіть на історію аукціона.

Очікувано: Є десь кнопка, зсилка : https://auction-sandbox.openprocurement.org/tenders/78c1c56391e942028ece686b34816e43

Фактично: Не можна подивитись на історію аукціона, не знаючи лінки. 

![image](https://cloud.githubusercontent.com/assets/11888281/11994928/4ecc1f02-aa50-11e5-8ae7-3415d0b4d315.png)

**Comment by iovzt** [comment]
виправив
