### ISSUE TITLE
Питання не з"являється, якщо задане через інший майданчик.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#544]
http://ubiz.iov.zt.ua/tender/question/3943
vbilos@softserveinc.com / Qw123456
TenderID: UA-2015-12-23-000029

Відтворення:
Закупівля створена і в статусі уточнення.
Задайте запитання на іншому майданчику. 
1. Знайдіть закупівлю
2. Відкрийте її
3. Перейдіть до таби Питання/Відповіді.
4. Зачекайте 30 хв.

Очікувано: Питання відображається на вкладці Питання/Відповідь

Фактично: Питання не з"явилось навіть через навіть через 30 хв.

![image](https://cloud.githubusercontent.com/assets/11888281/11995327/7c1d02ee-aa57-11e5-85a6-92c89e581923.png)

**Comment by iovzt** [comment]
виправив, була проблема з дуже довгим заголовком питання.
а взагалі, якесь обмеження повинно бути на довжину заголовку питання? зараз обмеження складає 4096 символів.

**Comment by w-be** [comment]
@iovzt про обмеження сказати не можу. Тест був розрахований, на відображення максимальної кількості символів, які можна внести через цей чи інші майданчики.
