### ISSUE TITLE
Редагування закупівлі. Зміна опису придмета подвоює придмет закупівлі.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#545]
http://ubiz.iov.zt.ua/tender/3968
vbilos@softserveinc.com / Qw123456
UA-2015-12-24-000005

Відтворення:
1. Створіть закупівлю
2. Відкрийте її
3. Перейдіть до редагування
4. Допишіть текст в поле Що купуємо? *
5. Натисніть Оновити

Очікувано: Закупівля збережена з новим описом придмета.

Фактично: Опис придмета дублюється: блок зі старим описом + блок з новим описом. Виглядає наче багатопридметна закупівля. В ЦБД зберігається тільки новий блок. Не зникає після перелогування в аплікацію.

![image](https://cloud.githubusercontent.com/assets/11888281/11995480/e01dffd0-aa59-11e5-89d6-822cd8236bfe.png)

**Comment by iovzt** [comment]
виправив
