### ISSUE TITLE
Картка закупівлі. Старі документи не відображаються.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#547]
http://ubiz.iov.zt.ua/tender/3994
vbilos@softserveinc.com / Qw123456
UA-2015-12-25-000008

Відтворення:
1. Залогуйтесь як закупівельник
2. Відкрийте Закупівлю в статусі обговорення (закупівля повинна мати 1 доданий документ).
3. Обновіть документ - замініть на новішу версію.
4. Збережіть закупівлю.
5. Перевірте наявність документів

Очікувано: Обидва документи відображаться в одному блоці, як новіша і старіша версія.  Наприклад назва старішої версії написана перекресленим шрифтом. Обидва документа можна скачати. 

Фактично: Відображається і доступний для скачування тільки остання версія.
![image](https://cloud.githubusercontent.com/assets/11888281/12003100/34e53288-ab1b-11e5-9113-ebd6435edd0d.png)

**Comment by iovzt** [comment]
ЦБД не повертає інформацію про версії файлу, якщо реалізовувати на майданчику то вийде тільки для тих закупівель, які були створені саме на ньому, а як тоді бути з закупівлями інших майданчиків?

**Comment by w-be** [comment]
@iovzt Вибачаюсь за не однозначність.
Окремого параметра "версія" нема. Під тим що "Обидва документи відображаться в одному блоці, як новіша і старіша версія."  я мав на увазі, що необхідно ці 2 групи документів візуально розмежовувати. Наприклад: шрифтом, горизонтальним відступом, випадайкою старіша версія, затемненим фоном, навіть просто сортуванням.

**Comment by iovzt** [comment]
@w-be Пробачте, це я не побачив що ЦБД повертає старий і новий файл під одним ID. а що зробити я зрозумів, дякую!

**Comment by iovzt** [comment]
http://ubiz.iov.zt.ua/tender/3994
виправив

**Comment by w-be** [comment]
Знову не відображаються: Закупівля: http://ubiz.iov.zt.ua/tender/4047 
![image](https://cloud.githubusercontent.com/assets/11888281/12033369/f53d69f8-ae2a-11e5-8fff-16b622a5da82.png)
![image](https://cloud.githubusercontent.com/assets/11888281/12033366/eb905082-ae2a-11e5-9721-aa98e628c2c9.png)

**Comment by w-be** [comment]
Через ~5 хв почали відображатись.
