### ISSUE TITLE
Подача пропозиції. Не можливо установити максимальну ціну.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#548]
http://ubiz.iov.zt.ua/tender/bid/3994
vbilos@softserveinc.com / Qw123456

Відтворення:
1. Залогуйтесь як почтачальник
2. Відкрийте Закупівлю в статусі Подача пропозиції.
3. Подайте пропозицію з максимальною ціною.

Очікувано: Можна подати пропозицію з максимальною ціною, яка рівна бюджету закупівлі.

Фактично: Максимально можлива пропозиція це: бюджет закупівлі - 1 грн.
В даній закупівлі: бюджет 123;
Максимальна пропозиція 122.

![image](https://cloud.githubusercontent.com/assets/11888281/12019661/db731fcc-ad7b-11e5-8386-63626baab0d6.png)

**Comment by iovzt** [comment]
виправлено
