### ISSUE TITLE
Кваліфікація. Продавець не може оновити/додати файли до пропозиції.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#550]
http://ubiz.iov.zt.ua/tender/4048
b.iktorqc@gmail.com / Qw123456

Відтворення:
1. Залогуйтесь як Продавець
2. Відкрийте Закупівлю в статусі Кваліфікація і на розгляді саме Ваша пропозиція.
3. Додайте та/або оновіть існуючий документ

Очікувано: а) Можна Оновити вже доданий документ. б) Можна додати новий документ.

Фактично: Відповідні контроли відсутні на сторінці.

![image](https://cloud.githubusercontent.com/assets/11888281/12088185/a65eb10a-b2e1-11e5-82d3-d08ea20f0e1d.png)

**Comment by w-be** [comment]
Вимоги - ТЗ (https://docs.google.com/document/d/1uriNzZ554KbsNam21aTzf7DOifnFuh6xf5hR1U019t0/edit?pli=1), Сторінка 35 (Процесс 4. «Оценка»), 2-ий абзац, 2-га частина речення:
"... и запрос квалификационных документов, которые не были обязательными в момент регистрации предложения.". 
Примітка: Хоч тут говориться тільки про запит не доданих документів, на практиці найчастіше саме запит проходить оффлайн, а додавання документів (відповідь на запит) через майданчик.

**Comment by iovzt** [comment]
виправлено

**Comment by w-be** [comment]
http://ubiz.iov.zt.ua/tender/4048
Додати і Заміникти файли можна. Але старі файли при заміні не відображаються:
![image](https://cloud.githubusercontent.com/assets/11888281/12389266/55999a32-bde0-11e5-90d5-04690d5e2ad3.png)

**Comment by w-be** [comment]
Старі документи з"являється через пару хв: 
![image](https://cloud.githubusercontent.com/assets/11888281/12389396/250b6bc4-bde1-11e5-9c9b-1491b21cec75.png)
