### ISSUE TITLE
Netcast. Створення мультилотової закупівлі з неціновими критеріями. Можливість видалити опцію нецінового показника.

### ISSUE THREAD

**Issue by yboi** [openprocurement/frontend#551]
homepage: "http://dz2.byustudio.in.ua"
login: ovramet.s@gmail.com
password: Password1

Відтворення:
1. Залогуватись замовником
2. Натиснути створити закупівлю
3. Вибрати тип закупівлі "Мультилотова закупівля з неціновими критеріями"
4. Додати націнову опцію в рамках лоту

Очікувано: можемо видаляти опцію нецінового показника
Фактично: Немає можливості видалити опцію нецінового показника
![db3dc9c561](https://cloud.githubusercontent.com/assets/13013223/12118461/4defd988-b3cf-11e5-89f7-9f97600019d6.jpg)

**Comment by kvskkvsk** [comment]
Исправлено. Необходимо почистить кеш или Ctrl+F5

**Comment by yboi** [comment]
@kvskkvsk  все працює!
