### ISSUE TITLE
Кваліфікація. Не можливо відмінити перемогу.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#553]
http://ubiz.iov.zt.ua/tender/4046 
UA-2015-12-29-000005-2
vbilos@softserveinc.com / Qw123456

Відтворення: 
1. Залогуйтесь закупівельником що має закупівлі в статусі кваліфікація.
2. Відкрийте 1 таку закупівлю.
3. Підтвердіть перемогу.
4. Відмініть перемогу.

Очікувано: Можливо відмінити перемогу.

Фактично перемогу відмінити не можливо. З"являється не відома помилка.

![image](https://cloud.githubusercontent.com/assets/11888281/12264350/e4fc3d8e-b93e-11e5-917f-1757b8ed7f55.png)

**Comment by iovzt** [comment]
виправлено

**Comment by w-be** [comment]
Відтворюється тим же користувачом на закупівлі: http://ubiz.iov.zt.ua/tender/4047
![image](https://cloud.githubusercontent.com/assets/11888281/12392379/4c8b94e2-bdf7-11e5-8494-56692098a94d.png)

**Comment by w-be** [comment]
Зараз поведінка така: Перемога притендента відміняється; Ця сама ставка йде на розгляд. Виглядає як помилка ЦБД.
