### ISSUE TITLE
Підписання Договору неможливе.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#554]
http://ubiz.iov.zt.ua/tender/3276
UA-2015-12-17-000004-1
zd116@ukr.net / qwertyuiop

Відтворення: 
1. Залогуйтесь закупівельником що має закупівлю в статусі пропозиції розглянуто та вже пройшов stend still період.
2. Відкрийте цю закупівлю.
3. Додайте в форму реєстрації договору документ(и).
4. Підтвердіть підписання договору.

Очікувано: Договір можна підписати.

Фактично: Договір не можна підписати. З"являється не відома помилка.
![image](https://cloud.githubusercontent.com/assets/11888281/12265448/bf4fd422-b945-11e5-9520-f53708d34464.png)

**Comment by iovzt** [comment]
Я також спробував, віддає наступну помилку:

X-Request-ID: req-9775f53e-e5a5-47aa-b192-003c381b7bfd
{"status": "error", "errors": [{"location": "url", "name": "tender_id", "description": "Not Found"}]}

**Comment by w-be** [comment]
Працює нормально, тест закупівля http://ubiz.iov.zt.ua/tender/4046.
