### ISSUE TITLE
Створення/Редагування закупівлі. Немає перевірки на перші 5 цифр ДКПП.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#555]
http://my.dz-test.net/cabinet/purchases/state_purchase/view/27254
vbilos@softserveinc.com
Qw123456
TenderID:UA-2016-01-19-000008-2

Відтворення:
1. Залогуйтесь Закупівельником.
2. Перейдіть до створення закупівлі.
3. Додайте 1 лот.
4. Заповніть Всі необхідні поля.
5. Становіть ДКПП щоб вони відрязнялись після 4-ої цифри, наприклад: "01.13.11 Спаржа" та "01.13.21 Кавуни"
6. Спробуйте зберегти закупівлю.

Очікувано: Закупівля не зберігається. З"являється повідомлення про те, що перші п'ять символів коду класифікатора ДК мають співпадати з кодом ДК всієї процедури.

Фактично: Можна зберегти закупівлю.

ТЗ Мультилоти, 3-я ст.:
https://docs.google.com/document/d/1VbHvplYTN-z-l7lFnErAOw5sLk_arc_zj-r6DYGYmnM/edit#
"Перевірки:
перші п'ять символів коду класифікатора ДК мають співпадати з кодом ДК всієї процедури."

![image](https://cloud.githubusercontent.com/assets/11888281/12422693/df3cf748-bed0-11e5-8d81-b840b597ad47.png)

**Comment by darchik** [comment]
fixed
