### ISSUE TITLE
ПриватМаркет. Не можливо подати пропозицію до мультилотової закупівлі

### ISSUE THREAD

**Issue by yboi** [openprocurement/frontend#558]
https://pmarket-rc.privatbank.ua/app.php/business/

Кроки до відтворення:
1. Залогуватись 
2. Перейти в мультилотову закупівлю 
3. Подати пропозицію до закупівлі(до лоту)

Очікувано що після того як натискаємо Подати заявку логінимось тими ж данними що і ввійшли на майданчик і можемо подати заявку
Фактично нас не впускає коли викрнуємо друге логування для подачі пропозиції.
![3956497a7b](https://cloud.githubusercontent.com/assets/13013223/12448048/287f3a96-bf7c-11e5-8cc8-26ed5971488e.jpg)
![fcdd733438](https://cloud.githubusercontent.com/assets/13013223/12448047/287cb4ce-bf7c-11e5-9821-14c2b4b09cca.jpg)

**Comment by sergejbondik** [comment]
Исправлено. В момент авторизации произошел сбой передачи данных между тестовыми серверами (редеплой приложения отвечающего за отображение тендеров).

**Comment by yboi** [comment]
@dn080985bsa пока у меня та ж ошибка http://joxi.ru/Vm66yEnux3R1Zm

**Comment by sergejbondik** [comment]
Почистите кеш и куки браузера и поробуйте снова

**Comment by yboi** [comment]
@dn080985bsa почистив я кеш браузера і також пробував ці кроки відтворити в браузері в якому ще не відкривалась ця лінка. Неможу другий раз залогінитись. І чи це потрбіно друге логуваня?

**Comment by sergejbondik** [comment]
1. Второго входа не нужно. Это была ошибка. Тендерная площадка  - другой сайт нашего проекта.
2. должна открыться страница подачи заявки (в случае сбоя попросит залогиниться еще раз на ПриватМакркете).  напр. тендер UA-2016-01-18-000016-1
   ![57260_ua-2016-01-18-000016-1](https://cloud.githubusercontent.com/assets/15994869/12508854/294f5e06-c107-11e5-8884-330e1cdeaa83.png)

**Comment by w-be** [comment]
Пробував, на GC і на FF - в мене  пише таке: 
![image](https://cloud.githubusercontent.com/assets/11888281/12612975/2290eaca-c4ff-11e5-98a6-bb308f0376ca.png)
Закупівля: https://pmarket-rc.privatbank.ua/app.php/business/tenders#/57534

**Comment by sergejbondik** [comment]
Баг с авторизацией на тестовом через интернет в работе. ориентировочный срок: 29.01.2016. 

Обходной путь: авторизоваться получить выше указанную ошибку. Нажать Выход и авторизоваться повторно.

**Comment by sergejbondik** [comment]
Исправлено.

**Comment by w-be** [comment]
Відтворюється. 
https://drive.google.com/file/d/0B6oFE7nKdcs3N0JKSHI5UU1yZ1k/view?usp=sharing - лінк на відео з відтворенням.
Припускаю: я не в приват мережі, я не правильно поставив сертифікати, в мене не всі сертифікати, в мене не має якоїсь бібліотеки чи оновленя віндовс.

**Comment by w-be** [comment]
Була проблема з даними користувача. Зараз виправлено.
