### ISSUE TITLE
Netcast. Період аукціону. Посилання на аукціон.

### ISSUE THREAD

**Issue by yboi** [openprocurement/frontend#564]
homepage: "http://dz2.byustudio.in.ua"
login: ovramet.s@gmail.com
password: Password1

Кроки до відтворення:
1. Залогуватись 
2. Створити мультилотову закупівлю 
3. Подати пропозицію до закупівлі(до лоту)
4. Дочекатись початку аукціону

Очікувано: дата і час відображають коли почнеться аукціон, посилання на аукціон появляється одразу після завершення прийому пропозицій
Фактично: дата відображається но немає часу коли саме відбудеться аукціон, посалання на аукціон немає.
![d91ac066b8](https://cloud.githubusercontent.com/assets/13013223/12512491/5e933cc6-c121-11e5-888d-f2207bedd7ff.jpg)

**Comment by kvskkvsk** [comment]
На представленной фотке имеется и дата и время аукциона
Если говорить о столбике справа, там где написано "АУКЦИОН дд.мм.гггг", то там так и должно быть - ибо так задумано.
Дата со временем указана в общих данных в поле "Дата та час редукціону"

> посилання на аукціон появляється одразу після завершення прийому пропозицій

Технически это не так. Даже ЦБД меняя состояние тендера не сразу дописсывает ссылку на аукцион + еще нужно время для синхронизации на самой площадке + состояние тендера может и не стать "Аукцион".

**Comment by yboi** [comment]
@kvskkvsk я розумію, що є варіанти коли може відбутись аукціон, (коли немає пропозиці), саме в цьому терндері є подано декілька пропозицій. Аукціон повинен був відбутись 22 січня. Але досих пір нічого не відбулось і тендер повернувся в статус прийом пропозицій.
Скрін зроблений щойно. 
![image](https://cloud.githubusercontent.com/assets/13013223/12549355/78c2d570-c365-11e5-8bf6-74b35fdd200c.png)

**Comment by kvskkvsk** [comment]
Этот тендер не обновится. и многие другие. В связи с запуском в тест планов по закупкам 21.01 был изменен адрес доступа к АПИ по версии с 0.10 на 0.11
Все те тендера, что были в версии 0.10 не действительны в версии 0.11, т.к. ЦБД тендера по версиям не синхронизирует.
