### ISSUE TITLE
Створення закупівлі. Немає опцій Одночасне/Послідовне розкриття.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#569]
http://my.dz-test.net/cabinet/purchases/state_purchase/add
vbilos@softserveinc.com/ Qw123456

Відтворення:
1. Залогуйтесь в плікацію закупівельником.
2. Перейдіть до форми створення закупівлі.

Очікувано: На формі є опція яка визначає послідовне чи одночасне розкриття пропозиція після аукціону.

Фактично опції послідовне/ одночасне розкриття немає.

**Comment by w-be** [comment]
![image](https://cloud.githubusercontent.com/assets/11888281/12548890/20adc3ac-c362-11e5-9c8f-c67d0ab5aef0.png)

**Comment by darchik** [comment]
not bug. так и договаривались, что будет одна процедура раскрытия.
