### ISSUE TITLE
Выводить ID тендера в объявлении

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#57]
Также, должна быть возможность искать тендер по ID

**Comment by dmarghania** [comment]
Чтоб принцип "все видят все" был реально реализован в системе, на площадках поиск закупок должен осуществляться по следующим показателям:
1. Номер закупки ( ID)
2. Закупщик (Поиск с 3-го символа названия)
3. Поставщик (Поиск с 3-го символа названия)
4. Статус закупки
5. Коды классификаторов (Поиск с 3-го символа названия)
6. Дата статуса (когда была объявлена, когда аукцион  итд.)
7. Объявленная цена закупки (от/до)
8.Цена контракта (от/до)

**Comment by nevdaha** [comment]
Вопрос всё еще открыт. 
Сейчас поиск по tender ID невозможен, в объявлении отображается на вкладке Анализ/№ в ЦБД. Поиск реализован по полям: внутренний 6-значный номер, организатор, категория, статус.
Следует переработать поиск по параметрам указанным в комментариях выше.

**Comment by AlexRudenko** [comment]
Готово (Id,Number) добавили. Поиск по ним тоже есть. Задание закрываю.
![image](https://cloud.githubusercontent.com/assets/10192570/10330208/d106b088-6cd2-11e5-9465-ff497709d5e9.png)
