### ISSUE TITLE
Редагування закупівлі. Нема можливості оновити документ.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#574]
https://test-prozorro.aps-tender.com/
owner1@dp23231.ua 345345345
TenderID: UA-2016-01-25-000004-1

Примітка: Додати можна, оновити - неможна.

Відтворення: 
1. Залогуйтесь Закупівельником.
2. Відкрийте свою закупівлю, яка є в статусі Уточнення, і має документ.
3. Перейдіть в режим редагування.
4. Замініть документ новою версією.

Очікувано: Документ можна замінити, як результат повині відображатись обидві версії документу. З індикацією, яка версія є новіша, наприклад: старіші версії під новішою і назви перекресленим шрифтом.

Фактично: Нема контролів, щоб оновити документ.
![image](https://cloud.githubusercontent.com/assets/11888281/12555610/a9f2f786-c38a-11e5-8abe-e41729dbb1b8.png)

**Comment by chekanovskyy** [comment]
Для підвантаженя файлів (оновлення файлів), необхідно натиснути "Обзор" і підвантажити файл. Якщо підвантажується файл, який підвантажувався вже раніше, то попередньо-завантажений файл перекреслюється. Обидва файли   доступні для підвантаження.
