### ISSUE TITLE
Який алгоритм визначення переможця?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#58]

**Comment by myroslav** [comment]
Пропозиції розглядає кваліфікаційна комісія закупівельника, але тільки від дешевшої пропозиції до дорожчої. Як тільки серед пропозицій знаходиться така, яка задовільняє критерії закупівельника - її автор визнається "переможцем".

Між подачою початкових пропозицій і етапом, коли відбувається їх розгляд є етап аукціону, де в 3-х раундах учаники можуть знизити свої ставки (від своїх початкових). В кожному з раундів учасники дають свої ставки по черзі, кожному учаснику виділено по 2 хв. Черговість учасників визначає їх остання ставка (і у випадку однакових ставок - час їх подання: той хто подав першим, то має можливість знижувати свою ціну останнім). Після кожного з раундів послідовність "оновлюється" з врахуванням остаточних ставок (від більших до менших).

Врахуйте, що рішення кваліфікаційної комісії може бути оскаржене, і якщо орган розгляду скарг задовольняє скаргу, то процес розгляду пропозицій в тендері повертається до розгляду тієї пропозиції, оскарження рішення на яку було задоволено.
