### ISSUE TITLE
Аукціон. На картці закупівлі немає лінки для перегляду аукціона.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#592]
https://test.aps-market.com/tenderView.aspx?TenderID=8830
TenderID: UA-2016-02-10-000004-1
Закупівля в статусі аукціон.
owner1@dp23231.ua 345345345

Відтворення:
1. Залогуйтесь Закупівельником
2. Відкрийте свою закупівлю в статусі аукціон

Очікувано: Закупівельнику і переглядачу відображаються лінки переглядача на аукціон.

Фактично: Лінка за якою можна подивитись на перебіг аукціону не відображається.

Примітки: 
а) Для учасника все ок.
б)Лінка переглядача повинна відображатись в статусі аукціон і в пізніших статусах.

![image](https://cloud.githubusercontent.com/assets/11888281/12948404/a145a02a-d00a-11e5-823d-170140255cc1.png)

**Comment by AndreyStatkevich** [comment]
Если вы говорите про эту ссылку на тендер, то она сейчас есть в таком виде:

![image](https://cloud.githubusercontent.com/assets/16881210/12949335/e54eb946-d00f-11e5-82c6-a6b57e1749a4.png)

**Comment by w-be** [comment]
Можу тільки прокоментувати що, не очевидно і до аукціону вона нікуди не веде.

Не баг.
