### ISSUE TITLE
Підписання контракту неможливе.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#596]
https://test.aps-market.com/tenderView.aspx?TenderID=8830
TenderID: UA-2016-02-10-000004-1
Переможець закупівлі вибраний Stand Still період (1 день на тестовому сервері) вже пройшов
owner1@dp23231.ua 345345345

Відтворення:
1. Залогуйтесь закупівельником
2. Знайдіть свою закупівлю з переможцем і закінчившимся Stand Still періодом
3. Підтвердіть факт підписання контракту, в тому числі додайте документ(и).

Очікувано: Контракт можливо підписати, додати документи контракту, як наслідок закупівля перейде в стан завершена.

Фактично: Підписання контракту неможливе - немає відповідних контролів.  

![image](https://cloud.githubusercontent.com/assets/11888281/13045652/450ca476-d3dd-11e5-84c2-d4707f05d09f.png)
![image](https://cloud.githubusercontent.com/assets/11888281/13045668/662052d4-d3dd-11e5-9154-e5f2ea80accb.png)

**Comment by AndreyStatkevich** [comment]
Тут могло быть одна или две проблемы:
1) проблемы совместимости апи 0.9 с 0.11
2) не отображались ошибки прозорро, которые не давали изменить статус победителя.
Всё это полечили, - проверяем.
