### ISSUE TITLE
Створення/Редагування закупівлі. Коди деяких одиниць містять зайвий пробіл.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#598]
https://test.aps-market.com/tenderedit.aspx
https://api-sandbox.openprocurement.org/api/0.11/tenders/e43d7c840e614c7aa46e57a0101d4e4a
Рекомендований словник:
http://standards.openprocurement.org/unit_codes/recommended/uk.json

Відтворення:
1. Залогуйтесь Закупівельником
2. Своріть закупівлю з назвою одиниць номенклатури "лот" (або Упаковка, Пара, Пачка).
3. Перевірте json закупівлі в ЦБД.

Очікувано: Код одиниць номенклатури відповідає рекомендованому словнику.

Фактично:
Лот, Упаковка, Пара, Пачка містять в кінці коду зайвий пробіл.

Є -> Потрібно:
"LO "->"LO", "PK "->"PK", "PR "->"PR", "RM "->"RM"

![image](https://cloud.githubusercontent.com/assets/11888281/13053951/d01fceb2-d40f-11e5-88b5-145a0b056ebd.png)

**Comment by AndreyStatkevich** [comment]
Исправлен хранимый и передаваемый тип
