### ISSUE TITLE
Відміна закупівлі. Спостерігач не бачить документів та дати відміни.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#599]
https://test.aps-market.com/tenderView.aspx?tab=3
TenderID: UA-2016-02-16-000091-2
Закупівля відмінена і містить доданий до відміни документ.

Відтворення:
1. Зайдіть на майданчик як спостерігач (чи продавець)
2. Знайдіть відмінену закупівлю
3. Перейдіть до вкладки Підсумки.
4. Перегляньте інформацію про відміну.

Очікувано: Документ(и) та дата відображаються.

Фактично: Документ і дата відміни не відображається.

Примітки:
а) У закупівельника документ відміни нормально відображається на вкладках Підсумки і Кваліфікація. 
б) Дата відміни не відображається у всіх користувачів.

![image](https://cloud.githubusercontent.com/assets/11888281/13074552/da7fa942-d4ad-11e5-85e1-d19b790090ea.png)

**Comment by AndreyStatkevich** [comment]
Исправили
