### ISSUE TITLE
В оголошенні на сайті не видно стартової ціни та кроку понижуючого аукціону 

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#6]

**Comment by AlexRudenko** [comment]
Андрей, все видно.
![image](https://cloud.githubusercontent.com/assets/10192570/5832833/9e348964-a153-11e4-934a-929935b901af.png)

**Comment by andriykucherenko** [comment]
Видно только на момент подачи предложения. Но плановая стоимость - важный
элемент принятия участником решения о том, подавать или не подавать
предложение вообще на данные торги.

Решать, конечно же вам, но на конкурирующих площадках участники видят эту
инфу сразу. А вы скрываете ее аж до момента завершения периода уточнений.
Совершенно непонятно, почему
21 січ. 2015 09:55, користувач "AlexRudenko" notifications@github.com
написав:

**Comment by DimasSmartTender** [comment]
Добрый день! Добавлено поле "Начальная ставка".
![image](https://cloud.githubusercontent.com/assets/10280562/6505109/6e2c737e-c347-11e4-8901-2e9d6c5e3067.png)
