### ISSUE TITLE
Скасування закупівлі.Не відображаються документи пропозицій.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#600]
https://test.aps-market.com/tenderView.aspx?TenderID=4425
TenderID: UA-2016-02-16-000074
Закупівля скасована в статусі Аукціон. Вона має декілька пропозицій з документами.

Відтворення:
1. Зайдіть Спостерігачем (або продавцем).
2. Знайдіть відмінену закупівлю з пропозиціями.
3. Перевірте пропозиції.

Очікувано: Документи пропозицій відображаються.

Фактично: Документи пропозиції не відображаються.
![image](https://cloud.githubusercontent.com/assets/11888281/13078306/cb4caaba-d4c6-11e5-90ee-b19ec364f756.png)

**Comment by AndreyStatkevich** [comment]
![image](https://cloud.githubusercontent.com/assets/16881210/13078547/79a69052-d4c8-11e5-8d95-a726fdb05201.png)
Открыл - документы есть, повторить не получилось.
Может, поможет кликнуть на ссылку с документами, чтобы она раскрылась....
