### ISSUE TITLE
Зміна пропозиції. Не зберігаються змінені та додані документи.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#601]
https://test.aps-market.com/tenderView.aspx?tab=3
TenderID: UA-2016-02-16-000098

Відтворення:
1. Створіть закупівлю.
2. Подайте пропозицію до закупівлі.
3. Змініть пропозицію в тому числі додайте новішу версію документа і 1 новий документ.

Очікувано: Цифра змінилась і документи змінились.

Фактично Цифра змінилась, а документи ні.

Пропозиція:
![image](https://cloud.githubusercontent.com/assets/11888281/13079159/804842e0-d4cb-11e5-989a-cda083f60069.png)
Кваліфікація:
![image](https://cloud.githubusercontent.com/assets/11888281/13079253/f9788a08-d4cb-11e5-98a2-9a6e57648eb3.png)

**Comment by w-be** [comment]
Відтворюється, перевіряв на закупівлі: TenderID: UA-2016-02-26-000039-2, користувач test1@test66.ua. До тогож не додається і не оновлюється документ в кваліфікації:
![image](https://cloud.githubusercontent.com/assets/11888281/13350826/4bafb41a-dc8b-11e5-9e2e-2d8fb2c3f32b.png)

**Comment by AndreyStatkevich** [comment]
Да действительно, проблема раньше присутствовала.
Не отправленные файлы датируются временем отправки:
2016-02-16 16:36:42.361526 +02:00   для MOCK_TEST_DOCX_V2.docx и новой версией MOCK_TEST_DOCX.docx.
После (19-23.02.16) - проблема была устранена, но ранее не переданные файлы так и остались.

**Comment by AndreyStatkevich** [comment]
> До тогож не додається і не оновлюється документ в кваліфікації

Такой эффект может быть, так как при квалификации сейчас документы показываются только те, что вернулись обратно из Прозорро. Периодически они сразу после выгрузки обратно не возвращаются, и только обновив страницу через пару минут они появятся (после регламентного обмена).

**Comment by w-be** [comment]
Все ок, перевірено на: UA-2016-02-29-000068-1.
