### ISSUE TITLE
Обговорення. Не відображається до якого лоту питання.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#602]
https://m.it.ua/cp_smart/discuss/135894
vbilos@softserveinc.com / qwerty
UA-2016-02-22-000034

Примітка:
До того ж запитання не зовсім правильно створюється - "questionOf": всюди ставиться, як "tender".
Наприклад в даній закупівлі (json: https://api-sandbox.openprocurement.org/api/0.12/tenders/5c5659a39f494cf68c40a73497369b19)
Є:
"id": "e59aab2c26bd48a6bd5c939a9a2492df",
"questionOf": "tender"
Має бути:
"id": "e59aab2c26bd48a6bd5c939a9a2492df",
"questionOf": "lot"

Відтворення:
1. Залогінтесь продавцем.
2. Зайдіть в закупівлю в періоді обговорення
3. Перейдіть до обговорення
4. Задайте пидання до всієї закупівлі і до окремих лотів
5. Перевірте відображення запитань на сторінці обговорення.

Очікувано: Питання відображаються так, щоб було зрозуміло до якого лоту(чи всього тендера) вони стосуються.

Фактично: всі запитання відображаються, як ті, що стосуються тендера.
![image](https://cloud.githubusercontent.com/assets/11888281/13220464/fa7f055a-d97e-11e5-81cf-e1bd92dbf414.png)

**Comment by AlexRudenko** [comment]
Готово. Дякую.
![image](https://cloud.githubusercontent.com/assets/10192570/13255516/293b865e-da4f-11e5-883e-c52904bcfe38.png)
