### ISSUE TITLE
Редагування закупівлі. Помилка при спробі зберегти закупівлю з доданою в лот номенклатурою.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#603]
UA-2016-02-22-000034
Логин: PPR_AK. Пароль: 123321
Версия: 2016.04.00.02

Примітка: Результат редагування всеж зберігається в ЦБД.

Відтворення:
1. Залогуйтесь, як закупівельник в IT enterprise 2016
2. Знайдіть свою закупівлю в статусі уточнення.
3. Добавте 1-у номенклатуру в 1 з лотів
4. Натисніть зберегти.

Очікувано:
Закупівлю можна модифікувати до настання статусу прийом пропозицій.

Фактично:
З"являється полилка при спробі збарегти зміни: "System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта."

![image](https://cloud.githubusercontent.com/assets/11888281/13222958/0ed53bbc-d98b-11e5-924b-c6af344df3df.png)

**Comment by AlexRudenko** [comment]
Поправили. Спасибо за вопрос.
