### ISSUE TITLE
Редагування закупівлі на рівні Лот не можливе.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#604]
UA-2016-02-22-000034
Логин: PPR_AK. Пароль: 123321
Версия: 2016.04.00.02

Відтворення:
1. Залогуйтесь, як закупівельник в IT enterprise 2016
2. Знайдіть свою закупівлю в статусі уточнення.
3. Спробуйте відредагувати інформацію рівня лот

Очікувано:
Закупівлю можна модифікувати до настання статусу прийом пропозицій, в тому числі рівня Лот.

Фактично:
Рівень лот редагувати немодливо - текстові поля недоступні для редагування.

![image](https://cloud.githubusercontent.com/assets/11888281/13224120/cccaacf2-d98f-11e5-8cf2-1c9e6c491376.png)

**Comment by AlexRudenko** [comment]
Поправили. Дякуємо.
