### ISSUE TITLE
Створення закупівлі. Не зберігається поле Опис опції не цінового показника.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#607]
Логин: PPR_AK. Пароль: 123321
Версия: 2016.04.00.02
UA-2016-02-23-000066
https://api-sandbox.openprocurement.org/api/0.12/tenders/0d819eaf02d24faca968a1159805e524

Відтворення:
1. Залогуйтесь, як закупівельник в IT enterprise 2016
2. Перейдіть до створення закупівлі.
3. Додайте декілька лотів і в них по пару номенклатур.
4. Додайте нецінові показники - заповніть всі поля в тому числі опис опції нецінового показника.
5. Збережіть та опублікуйте закупівлю.
6. Перевідкрийте закупівлю і перевірте поля опис опції не цінового показника.

Очікувано: Поле заповнене.

Фактично: Поле порожнє.

![image](https://cloud.githubusercontent.com/assets/11888281/13250150/f017c70c-da30-11e5-8a6d-536c009a8868.png)

**Comment by AlexRudenko** [comment]
Підправили. Дякую.
