### ISSUE TITLE
Картка закупівлі. Не можливо скачати документ закупівлі.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#608]
https://m.it.ua/cp_smart/tenders?f=UA-2016-02-23-000066

Відтворення:
1. Зайдіть на сайт як переглядач чи продавець.
2. Знайдіть закупівлю з документами.
3. Спробуйте завантажити документи рівня закупівля

Очікувано: Це можливо.

Фактично: При кліку на посилання з"являється помилка.
![image](https://cloud.githubusercontent.com/assets/11888281/13250898/6f1cc800-da35-11e5-9e18-d987fadb5e9e.png)

Примітка: посилання містить пробіли:
![image](https://cloud.githubusercontent.com/assets/11888281/13250809/cbdd17e4-da34-11e5-8d16-d3d1b73edda3.png)

**Comment by AlexRudenko** [comment]
Поправили

**Comment by w-be** [comment]
Знову не працює:
![image](https://cloud.githubusercontent.com/assets/11888281/13356761/ac6716c6-dcaf-11e5-8844-e41233db3cb4.png)
![image](https://cloud.githubusercontent.com/assets/11888281/13356727/8ef81342-dcaf-11e5-9466-5c048782eb98.png)

**Comment by AlexRudenko** [comment]
Вікторе, звісно не працює...Перепрошую, але старі адреси m.it.ua - вже недоступні. Варто тестити на test.smarttender.biz

**Comment by w-be** [comment]
Вибачаюсь за не однозначність в коментарі.
Я працюю з новою адресою - то просто лінка нового сайте веде на старий сайт.
В адресній стрічці на першому скріншоті новий сайт. Скріншот: https://cloud.githubusercontent.com/assets/11888281/13356761/ac6716c6-dcaf-11e5-8844-e41233db3cb4.png
При наведені на якийсь документ відображається посилання на документ (в лівому нижньому кутку на тому ж скріншоті) і воно не правильне: а) Присутні пробіли; б) Воно веде на старий сайт.

Другий скріншот(https://cloud.githubusercontent.com/assets/11888281/13356727/8ef81342-dcaf-11e5-9466-5c048782eb98.png) це результат кліку по документу.

Відтворюється також на щойно створеній закупівлі: http://test.smarttender.biz/tenders?p=1&mode=gov&f=UA-2016-03-04-000087-1

**Comment by AlexRudenko** [comment]
Дякуємо за запитання. поправили
![image](https://cloud.githubusercontent.com/assets/10192570/13569501/0ee40c6e-e471-11e5-8664-63baf8f5a5c1.png)
