### ISSUE TITLE
Картка закупівлі. Не відображаються документи рівня номенклатура.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#609]
https://m.it.ua/cp_smart/tenders?f=UA-2016-02-23-000066

Відтворення:
1. Зайдіть на сайт як переглядач чи продавець.
2. Знайдіть закупівлю з мультилотами і документами на рівні номенклатура.
3. Відкрийте лот.
4. Спробуйте завантажити документи рівня номенклатура.

Очікувано: Це можливо.

Фактично: Документи рівня номенклатура не відображаються.

![image](https://cloud.githubusercontent.com/assets/11888281/13250986/250a6532-da36-11e5-840e-294be201145a.png)

**Comment by AlexRudenko** [comment]
Треба дивитись трошки не там. Вибираємо "Аналіз"
![image](https://cloud.githubusercontent.com/assets/10192570/13255699/e39e100c-da4f-11e5-8f8a-f242bbecf6e8.png)
Натискаємо "Документація"
Обираємо в дереві номенклатуру і бачимо документ.
![image](https://cloud.githubusercontent.com/assets/10192570/13255738/270063e0-da50-11e5-8ff0-4f9a28dda7f8.png)
