### ISSUE TITLE
"Internal Server Error" при спробі відновити пароль і вказати інший email ніж той який вказали при реєстрації

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#61]
![default](https://cloud.githubusercontent.com/assets/10761162/6019925/8bace416-abae-11e4-9681-ce58e124c566.png)

**Comment by S-Shevchenko** [comment]
Не воспроизводиться. Можно закрывать

**Comment by yuliyaSoftserve** [comment]
03/02/2015, http://services.e-tender.biz:100/#/, не відтворюється
