### ISSUE TITLE
Подача пропозиції не працює.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#610]
https://m.it.ua/cp_smart/tenders?f=UA-2016-02-23-000066
vbilos@softserveinc.com / qwerty

Відтворення:
1. Зайдіть на сайт, як  продавець.
2. Знайдіть закупівлю з мультилотами, документами та неціновими.
3. Відкрийте лот.
4. Спробуйте подати пропозицію.

Очікувано: Це можливо.

Фактично: При натисканні кнопки подати пропозицію з"являється помилка.

Помилка при переходу з перегляду лоту:
![image](https://cloud.githubusercontent.com/assets/11888281/13251267/c35c2c56-da37-11e5-8f64-487e5019c62e.png)
Помилка при переході з перегляду закупівлі:
![image](https://cloud.githubusercontent.com/assets/11888281/13251204/7724a82c-da37-11e5-8201-c1e75e802970.png)

**Comment by AlexRudenko** [comment]
Дякую за запитання. Ми перевірили, все працює. Спробуйте переглянути аналогічну ситуацію на тенедрі https://m.it.ua/cp_smart/Etp/WidgetProposal.aspx?tenderId=136202 .
