### ISSUE TITLE
Нецінові показники не відображені на етапі обговорення.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#611]
https://m.it.ua/cp_smart/tenders?mode=gov&f=UA-2016-02-24-000074-2
vbilos@softserveinc.com / qwerty

Відтворення:
1. Зайдіть на сайт, як продавець/переглядач.
2. Знайдіть закупівлю з мультилотами, документами та неціновими, в статусі обговорення.
3. Відкрийте інформацію про нецінові показники.

Очікувано: Це можливо.

Фактично: Немає елементів які показують нецінові(якісні) показники закупівлі на етапі обговорення.

![image](https://cloud.githubusercontent.com/assets/11888281/13292231/9fd3862a-db23-11e5-8594-7083acbcbd43.png)

**Comment by AlexRudenko** [comment]
Якщо зайти в аналіз - то там все видно

**Comment by AlexRudenko** [comment]
![image](https://cloud.githubusercontent.com/assets/10192570/13325814/153e1bdc-dbec-11e5-8a35-7afc943e24a0.png)

**Comment by w-be** [comment]
Майже все, не вистачає: 1. оипсу показника, 2. опису опції показника, 3. назви відповідної номенклатури/лоту (рівень тендеру може бути ніяк не відмічений).
![image](https://cloud.githubusercontent.com/assets/11888281/13356160/b627c9ba-dcac-11e5-8c44-600f1edaa912.png)

**Comment by w-be** [comment]
Також футер перекриває частину показників (іний тендер - UA-2016-03-02-000061):
![image](https://cloud.githubusercontent.com/assets/11888281/13459774/82632a04-e07e-11e5-9745-5db88d400eb9.png)

**Comment by AlexRudenko** [comment]
Вікторе,дякуємо. Фікс зробили. Тепер виглядає корректно і красиво
![image](https://cloud.githubusercontent.com/assets/10192570/13649895/a71edcf6-e648-11e5-8b9f-0596073ee364.png)
