### ISSUE TITLE
Нецінові. Неможливо додати неціновий показник в періоді уточнення.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#612]
Логин: PPR_AK. Пароль: 123321
Версия: 2016.04.00.02
UA-2016-02-24-000074-2

Відтворення:
1. Залогуйтесь, як закупівельник в IT enterprise 2016
2. Знайдіть свою закупівлю з мультилотамиі неціновими в статусі обговорення.
3. Відкрийте закупівлю на редагування.
4. Додайте неціновий показник

Очікувано: Всі поля можна заповнити.

Фактично: Для нового нецінового показника неможливо заповнити поля:
Лот(Номенклатура), Название, Детальное описание.

Примітка: Ці поля також не можливо змінити в при спробі відредагувати неціновий показник.

![image](https://cloud.githubusercontent.com/assets/11888281/13293032/bf42ef98-db26-11e5-9f70-3ec004fa2c7a.png)

**Comment by AlexRudenko** [comment]
Поправили. Дякую
