### ISSUE TITLE
Редагування закупівлі. Не можливо видалити лот.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#613]
Логин: PPR_AK. Пароль: 123321
Версия: 2016.04.00.02
UA-2016-02-22-000034

Відтворення:
1. Залогуйтесь, як закупівельник в IT enterprise 2016.
2. Перейдіть до списку закупівель.
3. Відкрийте закупівлю з мультилотами в статусі обговорення.
4. Натисніть на якийсь лот.
5. Натисніть кнопку видалити.
6. Натисніть кнопку зберегти.

Очікувано: З"являється повідомлення що закупівлю збережено, лот видаляється з закупівлі.

Фактично: З"являється помилка. Лот не видаляється.

![image](https://cloud.githubusercontent.com/assets/11888281/13293909/5aa3c676-db2a-11e5-8dce-ee6c317ca985.png)

**Comment by AlexRudenko** [comment]
Вікторе не бачу такого тендеру у нас. Спробую відтворити на новому тендері. У вас вже не проявляється? Дякую за запитання.

**Comment by w-be** [comment]
Первірив на закупівлі : UA-2016-02-29-000056, Версия: 2016.04.00.07.
Зараз при спробі видалити лот з закупівлі, що є в періоді уточнення, з"являється помилка: "Удалять лот после публикации тендера запрещено! Выполните отмену лота."

Це суперечіть вимозі з ТЗ Мультилоти(https://docs.google.com/document/d/1VbHvplYTN-z-l7lFnErAOw5sLk_arc_zj-r6DYGYmnM/edit?usp=sharing), пункт Вимоги до Майданчика: "Можливість Замовника змінювати структуру лотів, додавати нові і видаляти існуючі -- до завершення періоду уточнень"

**Comment by AlexRudenko** [comment]
Вікторе, доброго дня!
Спілкувався по даному питанню з Мирославом Опиром. Технічно неможливо зробити видалння лоту, якщо на нього щось ссилається (item/question/document). Тобто його можна тільки відмінити.
