### ISSUE TITLE
Завершена закупівля не відображається для її власника.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#615]
https://test.aps-market.com/tenderView.aspx?TenderID=8015
owner1@dp23231.ua 345345345
UA-2016-02-26-000043-2
Закупівля готова до підписання контракту (stand still період пройшов).

Відтворення:
1. Залогуйтесь закупівельником
2. Знайдіть свою закупівлю з переможцем і закінчившимся Stand Still періодом
3. Підтвердіть факт підписання контракту, в тому числі додайте документ(и).

Очікувано: Закупівля стає завершена. Закупівля відображається в режимі перегляду.

Фактично: Закупівля стає завершена. Замість картки закупівлі користувачу(власнику закупівлі) відображається помилка "Ошибка сервера в приложении '/'."

Примітка: Відтворюється для закупівельника, переглядач(не залогований) все бачить добре.

![image](https://cloud.githubusercontent.com/assets/11888281/13392153/509f2ade-dee1-11e5-9154-9daca479679d.png)

**Comment by AndreyStatkevich** [comment]
Исправлено
