### ISSUE TITLE
Подача пропозиції. Неможливо подати пропозицію до окремого лоту якщо є нецінові критерії.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#619]
http://test.smarttender.biz/Etp/WidgetProposal.aspx?tenderId=137312
vbilos@softserveinc.com

Відтворення:
1. Залогуйтесь продавцем.
2. Знайдіть закупівлю з мультилотами і неціновими в періоді прийому пропозицій
3. Відкрийте закупівлю.
4. Спробуйте подати пропозицію тільки до одного лоту.

Очікувано: Пропозицію можна подати до окремого лоту.

Фактично: Пропозицію можна подати тільки до всього лоту разом.

Примітка: Ящо закупівля без нецінових - подати пропозицію до окремого лоту можливо.

![image](https://cloud.githubusercontent.com/assets/11888281/13467466/0b0bb31c-e0a7-11e5-8dba-bde7d5d3b595.png)

**Comment by AlexRudenko** [comment]
Ситуація локалізована. Прохання перепровірити. На приведеному прикладі не вдалось це зробити, так як період подачі пропозицій завершився. Дякуємо.
