### ISSUE TITLE
При третій спробі залогуватись з невірним паролем - зявляється додатковий елемент на формі - "Я не робот" і reCAPCHA. Чи це є очікувана поведінка аплікації?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#62]
![recapcha](https://cloud.githubusercontent.com/assets/10761162/6020079/49d92f20-abb0-11e4-89bc-aab6bd9ad0f3.png)

**Comment by lerich** [comment]
это так сделали для того, чтобы не подбирали пароль
