### ISSUE TITLE
Кваліфікація. Немає можливості прочитати додані продавцем документи.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#620]
Версия: 2016.04.00.06
Логин: PPR_AK.
UA-2016-03-02-000068-1 - Закупівля в стані кваліфікація, ставка (bid) має вкладені документи.

Відтворення:
1. Залогуйтесь закупівельником в IT Enterprise 2016
2. Відкрийте свою закупівлю
3. Перейдіть до пропозицій
4. Спробуйте переглятути документи додані до пропозиції. - ПКМ на пропозиції-"Прочие"-"Вложения". 

В контекстному меню "Документы", в обох його пенктах теж нема доданих до пропозиції документів.

Очікувано: Закупівельник має змогу прочитати додані продавцем документи.

Фактично: немає ніякої змоги прочитати додані в ставку документи.

![image](https://cloud.githubusercontent.com/assets/11888281/13493998/4ccdcf9e-e14a-11e5-9ad4-d16214e3e1ce.png)

**Comment by AlexRudenko** [comment]
Дійсно. Питання було. Зараз все ок. треба просто перезайти до клієнта.
![image](https://cloud.githubusercontent.com/assets/10192570/13499593/b43dfdbc-e167-11e5-8bde-cbe33c4c08e9.png)
Дякую.
