### ISSUE TITLE
Кваліфікація. Продавець немає можливості довантажити документи..

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#621]
http://test.smarttender.biz/tenders?mode=gov&f=UA-2016-03-02-000068-1
Логин: jdvornyk@gmail.com

Відтворення:
1. Залогуйтесь продавцем
2. Відкрийте закупівлю в статусі кваліфікація в якій є Ваша ставка.
3. Спробуйте відкрити вашу ставку

Очікувано: З"являється Ваша ставка з оновленою сумою з аукціону, в якій можна обновляти та додавати документи.

Фактично: Відтривається ще одна вкладка та з"являється повідомлення про те що користувач не залогований. 

Примітка: Інших елементів управління які б могли вести на екран додавання/оновлення документів я не виявив.

![image](https://cloud.githubusercontent.com/assets/11888281/13495046/f8e5dbcc-e150-11e5-80d7-33ee21845715.png)

**Comment by AlexRudenko** [comment]
Добрый день. Ви мабуть зайшли анонімно. Зараз ми перевірили. По однолотових процедурах є кнопка "Кваліфікаційні документи". Вона працює. 
![image](https://cloud.githubusercontent.com/assets/10192570/13526736/9c9df6fc-e212-11e5-8d27-7c183027c50b.png)
Далі можна вкласти документи
![image](https://cloud.githubusercontent.com/assets/10192570/13526740/a770d8e2-e212-11e5-8e06-16e90ba8cdb5.png)
Дякую за запитання

**Comment by w-be** [comment]
Дана закупівля багатолотова, кнопки "Кваліфікаційні документи" немає на сторінці:
![image](https://cloud.githubusercontent.com/assets/11888281/13567210/a0ae79a4-e462-11e5-8fb1-836891d4e8c2.png)

**Comment by AlexRudenko** [comment]
Вікторе, дякую за звернення.
Відповідаю на прикладі, який ви описали(під тим же аккаунтом):
1) Кнопка вже є :
![image](https://cloud.githubusercontent.com/assets/10192570/13665214/f7b42fca-e6b3-11e5-9762-4737a23015a5.png)
2) При натисканні переходимо до віконця вкладення документів.
![image](https://cloud.githubusercontent.com/assets/10192570/13665254/286621d2-e6b4-11e5-9370-ca593d4c08e5.png)
