### ISSUE TITLE
Назви одиниць номенклатур відрізняються від рекомендованого словника.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#622]
Логин: PPR_AK
Версия: 2016.04.00.07
UA-2016-02-29-000056 - Закупівля в статусі обговорення.
Рекомендований словник:http://standards.openprocurement.org/unit_codes/recommended/uk.json
Json закупівлі: https://api-sandbox.openprocurement.org/api/0.12/tenders/55a1b3b383864b2b87808be33313aae9

Відтворення:
1. Залогуйтесь в IT Enterprise 2016.
2. Відкрийте свою закупівлю для редагування.
3. Виставте певні типи товарів з рекомендованого словника
4. Збережіть закупівлю.
5. Перевірте що повернулось в json-і з api
6. Повторіть кроки 2-6 до повного перебору всіх можливих значень з рекомендованого словника і інтерфейса алікації.

Очікувано: Рекомендований словник співпадає з використаними в аплікації значенями.

Фактично: В аплікації трохи інші значення назв одиниць товарів/послуг, а саме:
1. В аплікації є надлишкова назва: "пос.ед." - що кодується як "PR" - що на інших майданчиках буде виглядати, як "пара".
2. В аплікації бракує: 
"RM", "PK", "NMP", "BX", "MON", "D64", "HAR".

![image](https://cloud.githubusercontent.com/assets/11888281/13531850/4a374d22-e231-11e5-93c7-4f97e99c6ec4.png)

![image](https://cloud.githubusercontent.com/assets/11888281/13531268/59e0145a-e22e-11e5-8d5f-012eebef4f6b.png)

**Comment by AlexRudenko** [comment]
Дякую за запитання. Одиниці виміру актуалізовані. Тепер їх 19. Надлишкова ОВ недоступна.
Єдине, що не добавили на майданчику, це ОВ "NMP"- т.я. не розуміємо її змісту.
![image](https://cloud.githubusercontent.com/assets/10192570/13637298/48192d12-e60f-11e5-8803-a65f5b4361a1.png)
