### ISSUE TITLE
Документи не розділені по рівням Тендер та Лот.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#624]
http://dev23.newtend.com/opc/tenders#/tender/e3e7acc5b85c49c49bf8eed50f964b7c/documents
ten2312@mailinator.com
UA-2016-03-14-000070-1

Відтворення:
1. Залогуйтесь закупівельником
2. Створіть закупівлю
3. Додайте документи окремо до рівнів Лот, Закупівля, Номенклатура.

Очікувано: Необхідно мати змогу розрізняти рівні документів Закупівля та Лот (виокремлення рівня Номенклатура необов"язкове).

Фактично: Всі документи додаються до рівня тендер.

Примітка: така ж поведінка при подачі пропозиції - документи не поділяються на рівні.

![image](https://cloud.githubusercontent.com/assets/11888281/13776483/107f7354-eab3-11e5-9e8f-780abb68aef6.png)

**Comment by SlaOne** [comment]
fixed
