### ISSUE TITLE
Кваліфікація. Неправильно рахуються коефіцієнти для лотів.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#626]
http://dev23.newtend.com/opc/tenders#/tender/f19b8960f65343a1bd5b4eec5dbdd873/auction
UA-2016-03-14-000118-2
ten2312@mailinator.com

Відтворення:
1. Залогуйтесь закупівельником.
2. Знайдіть свою закупівлю в статусі кваліфікація з пропозиціями.
3. Перейдіть до вкладки Торги.
4. Перевірте понижуючі коефіцієнти.

Очікувано: В обрахування коефіцієнтів по лоту не вхотять нецінові показники з інших лотів.

Фактично: В кожен коефіціент входять всі нецінові показники незалежно від лоту. Це призводить до неправильного значення коефіцієнту. І в даній закупівлі навіть до помилкової зміни переможця.

В даній закупівлі нецінові показники 1,2,4,5,6 - відносяться до першого лоту та показники 1,3,7 до другого лоту. 

![image](https://cloud.githubusercontent.com/assets/11888281/13784909/ccb1a8f0-ead9-11e5-9d0e-e2bb512eab1e.png)
![image](https://cloud.githubusercontent.com/assets/11888281/13785294/b8deb2c6-eadb-11e5-9148-63877fb2daac.png)

**Comment by SlaOne** [comment]
насколько мне известно - площадки сами не назначают победителя. мы смотрим, что нам возвращает ЦБД, из того и исходим. в даннос случае нам пришел ответ - 
"awards": [
{
    "status": "pending",
    "lotID": "a4bd8c4050c87589095fcb090fa85cac",
    "complaintPeriod": 
{
    "startDate": "2016-03-14T20:13:22.751379+02:00"
},
"suppliers": 
[
{
    "contactPoint": 
{
    "telephone": "99966677",
    "name": "ten2315 utf ",
    "email": "ten2315@mailinator.com"
},
"identifier": 
{
    "scheme": "UA-EDR",
    "id": "98798734",
    "legalName": ""
},
"name": "ten2315",
"address": 
        {
            "countryName": "Украина",
            "streetAddress": "dfjhgdslk dsifjlksjf isjfisjf 454",
            "region": "Черниговская область"
        }
    }
],
"bid_id": "ce062de6d1ae42589472c3df8e94b5b6",
"value": 
    {
        "currency": "UAH",
        "amount": ​28000.0,
        "valueAddedTaxIncluded": true
    },
    "date": "2016-03-14T20:13:22.768679+02:00",
    "id": "0da18213dfc84b57a436f4763764d657"
},
у нас он помечен как - "Ожидает решения". 
поправьте, пожалуйста, если я ошибаюсь

**Comment by w-be** [comment]
Майже все так: тільки "status": "pending", має транслюватись в "Очікує розгляду"; а "status": "active" має транслюватись в "Очікує на рішення". Active - це переможець, якого зараз розглядають. 
Але не схоже що це проблема перекладу тегів. В закупівлі UA-2016-03-14-000080-1 тільки 1 учасник, там award в статусі active.

**Comment by w-be** [comment]
Тепер деякі показники повторюються:
![image](https://cloud.githubusercontent.com/assets/11888281/13957665/e75887ce-f055-11e5-91ae-b17c031fe26a.png)

**Comment by SlaOne** [comment]
в новых тендерах такого нет. со старыми - возможны проблемы.
тендер созданный после внесения изменений - c10c03ccc15c4c3abb36541591a51957

2016-03-22 17:46 GMT+02:00 Viktor Bilostennyi notifications@github.com:
