### ISSUE TITLE
Підписання контракту. Неможливо завантажити документ.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#627]
http://dev23.newtend.com/opc/tenders#/tender/cde6cdc2d89d4a0e931f93c2d9bb0f1b/auction
UA-2016-03-14-000070-1 - Закупівля в статусі розглянута.
ten2312@mailinator.com

Відтворення:
1. Залогуйтесь закупівельником
2. Знайдіть свою закупівлю в статусі розглянута.
3. Перейдіть до вкладки Торги.
4. Натисніть кнопку Завантажити Договір
5. Виберіть якийсь файл для завантаження.
6. Підтвердіть завантаження файлу в стандартному діалозі ОС.

Очікувано: Файл завантажений, з"являється відповідне повідомлення.

Фактично: З"являється повідомлення "Виникла помилка. Будь ласка, зв'яжіться з нашою службою підтримки.", файл не додається до закупівлі.

![image](https://cloud.githubusercontent.com/assets/11888281/13948386/625eb2dc-f028-11e5-86bc-70dbb9c0bd8b.png)

**Comment by SlaOne** [comment]
fixed
