### ISSUE TITLE
Не має можливості створити тендер - відсутня кнопка "Створити тендер"

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#67]
В режимі навчання не має кнопки щоб "Створити тендер"

![button_createtender_notavailable](https://cloud.githubusercontent.com/assets/10761162/6043901/75b04f96-ac98-11e4-871e-203e2190f59e.png)

**Comment by lerich** [comment]
временно отключали возможность создания роли заказчик. Сейчас включили назад.
