### ISSUE TITLE
Прикріплення документу. Неможливо додати файл розміром більше 1 MB

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#679]
Майданчик: http://www.dz2.byustudio.in.ua/ (Неткаст).

Неможливо додати файл розмір, якого більший, ніж 1 MB (і замовником, і учасником) (в будь-якому місці, де прикріпляються файли: до тендерної документації закупівлі, до пропозиції, до скарги).
Кроки для відтворення (замовником):
1. Зайти в систему як замовник ( sboz@softserveinc.com / ZS561aRk3 ) і створити допорогову закупівлю.
2. Прикріпити до тендерної документації закупівлі файл розміром більше 1 MB.
3. Через 5 хв відкрити закупівлю для редагування.

Очікуваний результат: Файли розміром до 20 MB завантажуються в базу даних.
Фактичний результат: Файл не завантажений в базу даних.
![2016-05-12 14_36_35-www dz2 byustudio in ua_tenders_4883_edit - copy](https://cloud.githubusercontent.com/assets/17542973/15214177/3df2436a-1854-11e6-9b0b-b4ce9b8954df.png)

Кроки для відтворення (учасником):
1. Зайти як учасник ( halyna.khimka@gmail.com / JHO5VUp5n ).
2. Подати свою пропозицію на створену закупівлю, прикріпивши файл розміром більше 1 MB.

Очікуваний результат: Файли розміром до 20 MB завантажуються в базу даних.
Фактичний результат: Файл не завантажений в базу даних.
![2016-05-04 13_43_11- - -](https://cloud.githubusercontent.com/assets/17542973/15216066/33be8ba6-185e-11e6-870a-71735cceaa07.png)

Фактичний результат при поданні скарги:
![2016-05-11 20_17_21- - 2 -](https://cloud.githubusercontent.com/assets/17542973/15216172/b8ce31de-185e-11e6-9370-f2746e74384c.png)

Примітка: Краще, щоб повідомлення про те, що розмір файлу є завеликим, відображалось українською мовою.
Також необхідно додати таке повідомлення для замовника, коли він прикріпляє до тендерної документації файл, завеликий за розміром.

**Comment by kvskkvsk** [comment]
Ну так это ограничение ЦБД в песочнице, площадка ваш файл приняла
