### ISSUE TITLE
При реєстрації нового користувача на його профайлі не має галочки замовник

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#68]
![customer](https://cloud.githubusercontent.com/assets/10761162/6045088/210b75ee-aca0-11e4-8605-495b3caa508d.png)

**Comment by OksanaPakholok** [comment]
Ця проблема перевірена і вже вирішена. Не репродюситься. ЇЇ можна закривати

**Comment by lerich** [comment]
Закриваю.
