### ISSUE TITLE
Користувач не може увійти в кабінет в браузері IE 10. Некоректне відображення сайту

### ISSUE THREAD

**Issue by johnylviv** [openprocurement/frontend#683]
http://zakupki.dz-test.net/?sign_in=1&next=/cabinet/purchases/state_purchase/view/99604#login
Tender ID:UA-2016-05-24-000065-1
test@test12.com

**Браузер:** IE 10.0.9200.17609

**Відтворення:**
1. Користувач використовує браузер ІE 10.0, щоб зайти на сайт за посиланням
http://zakupki.dz-test.net/?sign_in=1&next=/cabinet/purchases/state_purchase/view/99604#login
2. Користувач натискає кнопку "Увійти в кабінет"

**Очікувано:** Користувач може увійти в кабінет в IE 10
**Фактично:** Користувач не може увійти в кабінет в IE 10
Повідомлення "Ви користуєтесь застарілою версією браузера Internet Explorer"

![ie 10 0](https://cloud.githubusercontent.com/assets/17986894/15505348/d1f705de-21cb-11e6-8ef6-e127ad56ab5d.png)

**Comment by Rzaporozhets** [comment]
Пробовали в разных варисия IE так и не получилось воиспроизвести данную
проблему.

2016-05-24 16:33 GMT+03:00 johnylviv notifications@github.com:

> http://zakupki.dz-test.net/?sign_in=1&next=/cabinet/purchases/state_purchase/view/99604#login
> Tender ID:UA-2016-05-24-000065-1
> test@test12.com
> 
> Відтворення:
> 1. Користувач використовує браузер ІE 10.0, щоб зайти на сайт
> 2. Користувач натискає кнопку "Увійти в кабінет"
> 
> Очікувано: Користувач може увійти в кабінет в ЇE 10
> Фактично: Користувач не може увійти в кабінет в ЇE 10
> Повідомлення "Ви користуєтесь застарілою версією браузера Internet
> Explorer"
> 
> [image: ie 10 0]
> https://cloud.githubusercontent.com/assets/17986894/15505348/d1f705de-21cb-11e6-8ef6-e127ad56ab5d.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/openprocurement/frontend/issues/683

## 

---

Best regards,

Zaporozhets Roman

QA Automation Engineer

Prom.ua, Tiu.ru, Deal.by, Satu.kz

address: Kharkivske Highway, 201/203, office 316, 02000, Kiev, Ukraine

phone: +38 (067) 99-416-00

skype: zaporogech

**Comment by ghost** [comment]
Спробуй змінити Browser Mode (на IE10). В тебе, мабуть, Browser Mode IE10 Compatibility View.

**Comment by johnylviv** [comment]
Так, проблема в настройках IE
**Рішення**
Servise -> Compatibility View settings
uncheked 'Display internet sites in Compatibility View'
