### ISSUE TITLE
При повторному вході, на Авторизації галочка "Запам'ятати мене" не запамятовує пароль.

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#69]
![default](https://cloud.githubusercontent.com/assets/10761162/6063493/6a202ef8-ad60-11e4-840a-0cd5bdc20ccf.png)

**Comment by S-Shevchenko** [comment]
Неактуально. Функционал временно убран.

**Comment by lerich** [comment]
Закриваю.
