### ISSUE TITLE
NewTend: Два обо'язкових поля "Назва закупівлі" та "Назва закупівлі (EN)" не підсвічуються червоним, якщо намагатись зберегти форму без введення даних у цих полях

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#697]
http://dev23.newtend.com/opc/tenders#/create-tender/multilot/aboveThresholdEU

Відтворення:
1. Залогуйтесь в аплікацію закупівельником (юзер: ten2312@mailinator.com)
2. Клікніть створити закупівлю
3. У дропдауні "Процедура закупівлі" виберіть опцію "Відкриті торги з публікацією англійською мовою"
4. Клікніть на "Мультилотова закупівля"
5. Клікніть на кнопку "Опублікувати"
6. Заповніть коректними даними всі поля, які позначені червоним
7. Клікніть на кнопку "Опублікувати"

Фактично:
З"являється повідомлення "Заповніть обов'язкові поля (підкреслені червоним)", аже жодне поле не позначене червоним. 
Якщо ввести дані в поля "Назва закупівлі" та "Назва закупівлі (EN)", то закупівля буде збережена без помилок. 
![default](https://cloud.githubusercontent.com/assets/13050207/17055654/dbb28606-5016-11e6-9489-ed03425a1f22.png)

Очікувано:
Всі обов"язкові поля мають підсвічуватись червоним кольором, якщо намагатись зберегти закупівлю без введених даних у цих полях

**Comment by SlaOne** [comment]
взяли в работу

**Comment by SoftserveQC1** [comment]
Така ж проблема відтворюється і з полем "Короткий опис предмету закупівлі"

**Comment by SlaOne** [comment]
исправлено много месяцев назад. нет возможности нажать на кнопку "Опубликовать" если не заполнены все обязательные поля
