### ISSUE TITLE
NewTend: Поля часу поставок перемістились у другу лінійку у браузері Chrome

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#699]
http://dev23.newtend.com/opc/tenders#/create-tender/multilot/aboveThresholdEU
Відтворюється у браузері Chrome 51

Відтворення:
1. Залогуйтесь в аплікацію закупівельником (юзер: ten2312@mailinator.com)
2. Клікніть створити закупівлю
3. У дропдауні "Процедура закупівлі" виберіть опцію "Відкриті торги з публікацією англійською мовою"
4. Клікніть на "Мультилотова закупівля"
5. Перейдіть вниз сторінки та огляньте поля часу для "Дата з якої очікується поставка", "Необхідний граничний термін постачання" та "Кінцевий строк подання тендерних пропозицій"

Фактично:
Поля для введення часу перемістились в другу лінійку
![chrome51](https://cloud.githubusercontent.com/assets/13050207/17060560/35bae866-5033-11e6-9304-9616b6a7dc48.png)

Очікувано:
Поля для введення часу мають знаходитись на одному рівні із полями для вибору дат (як у браузері Firefox)
![firefox](https://cloud.githubusercontent.com/assets/13050207/17060608/71185128-5033-11e6-9178-8e44dce747f8.png)

**Comment by SlaOne** [comment]
очень похоже, на то что масштаб в браузере более 100%
