### ISSUE TITLE
Не видно пропозиції, поданої учасником

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/frontend#7]
Після повідомлення "Пропозиція прийнята" подивитись її учасник не може

**Comment by AlexRudenko** [comment]
Может. Необходимо еще раз зайти в тендер, нажать кнопку "Подать предложение" и стоимость подтянется из поданного ранее предложения

**Comment by andriykucherenko** [comment]
Стоимость подтянется, но документа не видно. Это может сильно смущать
участников.
21 січ. 2015 09:51, користувач "AlexRudenko" notifications@github.com
написав:

**Comment by AlexRudenko** [comment]
Андрей, это стандартная схема, которую используют все наши поставщики. И еще никто вопроса по поводу документов не поднимал. Считаю пока что можно этой опцией пренебречь.
