### ISSUE TITLE
Як можна взнати код тендера?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#70]
Для того щоб отримати дані про тендер з бази даних, можна використати URL - 
http://services.e-tender.biz:99/#/tenderDetailes/e7cd0eb88433433c93681b8a417f1c5d , де e7cd0eb88433433c93681b8a417f1c5d - це код тендера

**Comment by lerich** [comment]
В деталях рядом со словом Тендер есть UA-2015-02-05-000011, это и есть уникальный идентификатор в рамках ЦБД.  e7cd0eb88433433c93681b8a417f1c5d - это уникальный идентификатор в рамках площадки
