### ISSUE TITLE
NewTend: Період уточнень не закінчується за 10 днів до кінцевого строку подання пропозицій

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#703]
http://dev23.newtend.com/opc/tenders#/create-tender/multilot/aboveThresholdEU

Відтворення:
1. Залогуйтесь в аплікацію закупівельником (юзер: ten2312@mailinator.com)
2. Клікніть створити закупівлю
3. У дропдауні "Процедура закупівлі" виберіть будь-яку опцію (наприклад, "Відкриті торги з публікацією англійською мовою")
4. Клікніть на "Мультилотова закупівля"
5. Заповніть всі необхідні поля коректними даними
6. Натисніть "Опублікувати"
7. Відкрийте закупівлю та перегляньте дату закінчення періоду уточнень

Фактично:
Період уточнень закінчується в день, що передує кінцевому терміну подання пропозицій
![2](https://cloud.githubusercontent.com/assets/13050207/17106299/7c996a2a-5293-11e6-9902-bf58a37f7001.JPG)
![default](https://cloud.githubusercontent.com/assets/13050207/17106316/87b450f0-5293-11e6-86b2-86bd7f3f37e3.JPG)

Очікувано:
Період уточнень має закінчуватись за 10 днів до кінцевого строку подання пропозицій (Сценарій тестування рівень 3, пункт 1.2, очікуваний результат 5.4)

**Comment by SlaOne** [comment]
1. на тестовом сервере включен режим ускорителя. (1 минута реального времени - 1 день "тестовый")
   1.1. 23-50 минус 00-00 - получается 10 минут реального времени, что приравнивается к 10 дням "тестовым". ЦБД - назначило дату правильно с учетом ускорителя.
2. наша площадка не назначает временные периоды в послепороговых процедурах.
