### ISSUE TITLE
NewTend: Опції причини скасування закупівлі не перекладаються на вибрану мову інтерфейсу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#705]
http://dev23.newtend.com

Відтворення:
1. Залогуйтесь в аплікацію закупівельником (юзер: ten2312@mailinator.com)
2. Клікніть створити закупівлю
3. У дропдауні "Процедура закупівлі" виберіть будь-яку опцію (наприклад, "Відкриті торги з публікацією англійською мовою")
4. Клікніть на "Мультилотова закупівля"
5. Заповніть всі необхідні поля коректними даними
6. Натисніть "Опублікувати"
7. Виберіть Інтерфейс "UA" або "EN"
8. Внизу форми натисніть "Скасувати закупівлю"
9. Клікніть на дропдаун "Виберіть причину скасування"
10. Огляньте доступні опції

Фактично:
Опції в дропдауні відображаються російською мовою
![default](https://cloud.githubusercontent.com/assets/13050207/17139199/21269e74-534c-11e6-8524-362d5a15517b.JPG)

Очікувано:
Опції мають бути перекладені на ту мову яка вибрана в "Інтерфейс"

**Comment by SlaOne** [comment]
проблемы с переводом интерфейса к сожалению имеют место. работаем над этим.

**Comment by SlaOne** [comment]
![translate](https://user-images.githubusercontent.com/15046328/34046396-a159d662-e1b5-11e7-8024-5ecb4aa0cd67.jpg)
![translate_1](https://user-images.githubusercontent.com/15046328/34046397-a179b248-e1b5-11e7-814d-18fb6ddb095e.jpg)
исправлено
