### ISSUE TITLE
NewTend: Кнопка "Запитати" у вкладці "Уточнення" для постачальника не зникає після закінчення періоду звернень за роз'ясненнями

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#707]
http://dev23.newtend.com

Відтворення:
1. Залогуйтесь в аплікацію закупівельником (юзер: ten2312@mailinator.com)
2. Створіть нову закупівлю і опублікуйте її
3. Залогуйтесь в аплікацію постачальником (юзер: ten2316@mailinator.com)
4. Відкрийте створену закупівлю (у пункті 2)
5. Дочекайтесь поки завершиться період "Звернення за роз'ясненнями"
6. Натисніть "Уточнення"
7. Натисніть "Запитати"
8. Заповніть всі поля та натисніть "Запитати"

Фактично:
Кнопка "Запитати" доступна після завершення періоду звернень за роз'ясненнями, але запитання не зберігається (з'являється повідомлення, що виникла помилка)
![default](https://cloud.githubusercontent.com/assets/13050207/17177213/013fa48e-5419-11e6-9a59-dded2345a566.png)

Очікувано:
Кнопка "Запитати" не має бути доступна після завершення періоду звернень за роз'ясненнями

**Comment by SlaOne** [comment]
статус тендера не пересинхронизировался в ЦБД. задержки в синхронизации возможны до 5-7 минут (практическое наблюдение. даже принудительная пересинхронизация конкретного тендера не всегда дает результат). соответственно кнопка еще доступна (мы не отсчитываем время самостоятельно - но орентируемся на статусы от ЦБД), но вопрос задать - ЦБД не позволяет.
