### ISSUE TITLE
NewTend: Відкриті торги з публікацією англійською - Конфіденційні документи видимі всім учасникам

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#708]
http://dev23.newtend.com

Відтворення:
1. Залогуйтесь в аплікацію закупівельником (юзер: ten2312@mailinator.com)
2. Створіть нову закупівлю і опублікуйте її
3. Залогуйтесь в аплікацію постачальником (юзер: ten2316@mailinator.com)
4. Відкрийте створену у пункті 2 закупівлю та зробіть ставку
5. Додайте конфіденційні документи, які мають бути доступні на етапі прекваліфікації
6. Залогуйтесь в аплікацію постачальником (юзер: ten2314@mailinator.com)
7. Повторіть кроки 4-5
8. Дочекайтесь етапу прекваліфікації
9. Перегляньте документи доступні у вкладці прекваліфікація для кожного юзера

Фактично:
Конфіденційні документи завантажені юзером ten2316@mailinator.com доступні для юзера ten2314@mailinator.com.
Якщо постачальник буде намагатись скачати конфіденційні документи іншого постачальника, то отримає помилку:
{"status": "error", "errors": [], "status_code": 403, "code": 1200, "result": false, "action": {"can_edit_bid": false, "can_upload_bid_docs": false, "can_complain": false, "show_bids": false, "show_must_accept": true, "tender_closed": false, "can_claim": false, "can_create_bids": false, "show_invites": false, "can_qualification_complain": false, "can_award_complain": false, "can_ask_questions": false, "show_admit": false, "can_invite": false, "can_award_claim": false}, "message": "Forbidden", "response": {}}
![ten2314](https://cloud.githubusercontent.com/assets/13050207/17218983/58478902-54f2-11e6-8941-c0a95c742f8b.JPG)
![ten2316](https://cloud.githubusercontent.com/assets/13050207/17218990/5f1b439a-54f2-11e6-8db1-c05979be0431.JPG)

Очікувано:
Конфіденційні файли мають бути доступні лише для Замовника

**Comment by SlaOne** [comment]
ЦБД возвращает список всех документов. соответсвенно мы его отображаем, но вот скачать их у вас не получилось, потому как для скачивания они доступны только закупщику.  "message": "Forbidden", "response":
