### ISSUE TITLE
Не можливо залогуватись з новим паролем в систему

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#71]
1. На "Авторизація" вибрати "Забув пароль"
2. Внести електронну адресу яка була вказана при реєстрації користувача
3. Відновити пароль
4. Спробувати залогуватись з новим паролем - як результат "не вірний пароль або логін"

**Comment by myroslav** [comment]
якого з майданчиків стосується ця проблема?

**Comment by OksanaPakholok** [comment]
ЕЛЕГ

**Comment by S-Shevchenko** [comment]
не  воспроизводиться

**Comment by lerich** [comment]
Закриваю
