### ISSUE TITLE
NewTend: Кнопка "Опублікувати" не стає активною після введення даних у всі обов'язкові поля

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#714]
http://dev23.newtend.com/opc/tenders#/create-tender/singlelot/reporting
Дефект відтворюється для всіх процедур закупівлі

Відтворення:
1. Залогуйтесь в аплікацію закупівельником (юзер: ten2312@mailinator.com)
2. Натисніть "Створити закупівлю"
3. У дропдауні "Процедура закупівлі" виберіть будь-яку опцію (наприклад, "Звіт про укладені договори"
4. Клікніть на "Безлотова закупівля" або на "Мультилотова закупівля"
5. Клікніть на кнопку "Опублікувати" внизу форми
6. Заповніть коректними даними всі поля, які позначені червоним
7. Клікніть на кнопку "Опублікувати"

Фактично:
Кнопка "Опублікувати" не активна і позначена сірим кольором
![default](https://cloud.githubusercontent.com/assets/13050207/17729656/e9fa1088-646d-11e6-8176-6b2178d2dbf7.JPG)

Очікувано:
Кнопка "Опублікувати" бає бути активна

**Comment by SlaOne** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
Виправлено
