### ISSUE TITLE
Замовник і учасник які подали однакові пропозиції по 100 грн, не мають можливості їх редагувати під час аукціону, в жодному раунді.

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#73]
![cannotchangesum](https://cloud.githubusercontent.com/assets/10761162/6077168/d3976e5c-adf4-11e4-9d2a-6323ea565a4c.png)

**Comment by myroslav** [comment]
Аукціон має 2 варіанти:
- перегляд
- участь

Чи скористалися ви посиланням для участі?

**Comment by yuliyaSoftserve** [comment]
Це була участь

**Comment by myroslav** [comment]
Якби це була участь, то учасник був би позначений як "Ви"... Тому я роблю висновок, що учасник потрапив на перегляд аукціону як спостерігач.

**Comment by yuliyaSoftserve** [comment]
У мене є 2 учасники та 1 замовник (і ще один той що створив тендер), усі подали свої пропозиції на участь в аукціоні, і всі перейшли за посиланням "Прийняти участь в аукціоні", причому в Хромі, Експлорері та ФаєрФоксі, за 5 - 10хв. до початку аукціону, і жоден з них (окрім замовника, що створив тендер - він дійсно не має право редагувати ціну, лише переглядати як проходить аукціон), не мав можливості редагувати ціну в жодному з раундів. І не позначався як "Ви".

**Comment by yuliyaSoftserve** [comment]
Ця проблема була сьогодні глибше досліджена в https://github.com/openprocurement/frontend/issues/78.

**Comment by S-Shevchenko** [comment]
Дубликат  #78(актуальная таска).
