### ISSUE TITLE
APS: Після закінчення періоду уточнень закупівля не перейшла у статус прийняття пропозицій

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#732]
https://test.aps-market.com/Tenders/293510
TenderID: UA-2016-09-23-000260, UA-2016-09-23-000327

Відтворення:
1. Залогуйтесь в аплікацію (наприклад, під користувачем: zakupnyk-1@mail.ua)
2. Створіть допорогову закупівлю та опублікуйте її
3. Дочекайтесь початку періоду надання пропозицій

Фактично:
Тендер UA-2016-09-23-000260 не перейшов у статус прийняття пропозицій після закінчення періоду уточнень, тому по ньому неможливо подати пропозицію (на інших майданчиках статус тендера відображається коректно)
![default](https://cloud.githubusercontent.com/assets/13050207/18789603/3d139aa6-81b4-11e6-9ccc-3744ed238290.jpg)

Очікувано:
Після закінчення періоду уточнень тендер має переходити у статус прийняття пропозицій

**Comment by SoftserveQC1** [comment]
Дефект більше не відтворюється

**Comment by AndreyStatkevich** [comment]
В данном случае на сервере производились технические работы, обмены были выключены. После включения - все синхронизировалось.
