### ISSUE TITLE
Newtend: Запис про скасування аукціону додається двічі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#739]
http://ea.newtend.com/auction/#/tender/072c595695ec4297ac052f482755a2f6/auction

Відтворення:
1. Залогуйтесь в аплікацію під користувачем: auc001@mailinator.com
2. Створіть аукціон "Права вимоги" та опублікуйте його
3. Натисніть скасувати 
4. Вкажіть причину скасування та прикріпіть документ
5. Натисніть Скасувати
6. Перейдіть у вкладку Торги

Фактично:
Запис про скасування аукціону доданий двічі
![default](https://cloud.githubusercontent.com/assets/13050207/19066510/512ef7bc-8a22-11e6-801b-1009cd7fc6bc.JPG)

Очікувано:
Лише один запис про скасування аукціону має бути доданий

**Comment by SlaOne** [comment]
взяли в работу

**Comment by SlaOne** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
Дефект вже не відтворюється
