### ISSUE TITLE
Де саме зберігається інформація про користувачів системи? чи є можливість переглянути її?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#74]
Мене цікавить конкретний юзер - usertest_1
Чи його імейл - usertest_1@mailinator.com?
Коли останній раз була зміна паролю для цього юзера?
чи новий пароль - TestTest1

**Comment by lerich** [comment]
Такого пользователя нет. по этому емайлу есть пользователь usertest1
Время последней модификации по этому пользовалю 2015-02-05 19:06:26.107
пароль верный
