### ISSUE TITLE
Newtend: Немає валідації на коректні дані при створенні користувача

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#740]
http://ea.newtend.com/signin/#/profile/login

Відтворення:
1. Натисніть кнопку Реєстрація
2. У полях Ім'я та Прізвище внесіть цифри та спеціальні символи
3. У полі Телефон внесіть букви
4. Внесіть E-mail адресу пароль та натисніть "Далі"
5. Виберіть будь-яку роль
6. У полях Повна назва банку та ЄДРПОУ банку внесіть цифри та спеціальні символи
7. Всі інші поля заповніть коректними даними та натисніть Зберегти

Фактично:
Користувач успішно збережений із невалідними даними у полях Ім'я, Прізвище, Телефон, Повна назва банку та ЄДРПОУ Банку
![1](https://cloud.githubusercontent.com/assets/13050207/19067331/4225e146-8a26-11e6-9579-62e87fdcdd95.JPG)
![2](https://cloud.githubusercontent.com/assets/13050207/19067336/46c7c886-8a26-11e6-9d11-8d4f8f492090.JPG)

Очікувано:
Користувач не має бути збережений із невалідними даними

**Comment by SlaOne** [comment]
на площадке будет использоваться валидация пользователей администратором. Пользователи не будут допущены к взаимодействию с аукционами до того как администратор провалидирует пользователей. на этапе MVP данная функциональность выключена.

**Comment by SoftserveQC1** [comment]
У зв'язку з валідацією користувачів адміністратором необхідність валідації полів лишається на розсуд представників майданчика. Дефект закриваємо
