### ISSUE TITLE
Newtend: Кнопка Створити аукціон активна якщо процедура закупівлі не вибрана

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#741]
http://ea.newtend.com/auction/#/tender/072c595695ec4297ac052f482755a2f6/auction

Відтворення:
1. Залогуйтесь в аплікацію під користувачем: auc001@mailinator.com
2. Натисніть "Створити аукціон"
3. Не вибирайте нічого у списку "Процедура закупівлі" і натисніть "Створити аукціон"

Фактично:
Форма "Новий аукціон - Допорогові торги" відкрита
![default](https://cloud.githubusercontent.com/assets/13050207/19067598/a8c1b8de-8a27-11e6-9e2b-90aa48bf5a72.JPG)

Очікувано:
Поле Процедура закупівлі є обов"язковим, тому кнопка Створити аукціон має бути неактивна поки не вибрана жодна опція в цьому дропдауні.

**Comment by SlaOne** [comment]
исправлено

**Comment by SoftserveQC1** [comment]
Дефект вже не відтворюється
