### ISSUE TITLE
Newtend: При реєстрації нового користувача немає можливості завантажувати документи

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#742]
http://ea.newtend.com/signin/#/profile/login

Відтворення:
1. Натисніть кнопку Реєстрація
2. Натисніть "Далі"
3. Виберіть роль Ліквідатор
4. Всі інші поля заповніть коректними даними та натисніть Зберегти

Фактично:
Користувач збережений
У формі створення користувача не було поля, в яке можна було б завантажити скановану копію рішення дирекції ФГВ щодо призначення   

Очікувано:
У формі створення користувача має бути поле для завантаження документів

**Comment by SlaOne** [comment]
в адаптации к сценарию указано, что данный функционал находится в стадии разработки и будет реализован в кратчайшие сроки.

**Comment by SoftserveQC1** [comment]
Неможливо пройти регістрацію. Додаю відеофайл. 
[2016-10-28_1650_newtend_registration.zip](https://github.com/openprocurement/frontend/files/558668/2016-10-28_1650_newtend_registration.zip)

**Comment by SlaOne** [comment]
добавили видео. на видео нет возможности зарегистрироваться.
если видео не врет, то
1. номер телефона там введен в интересном формате "+38 (097) 097 09 09 099" (много цифр)
2. есть такой косяк - поле принимает от 7 до 10 цифр без скобок и пробелов.

**Comment by SlaOne** [comment]
на данный момент документы при регистрации пользователя, на втором шаге - грузятся.
