### ISSUE TITLE
PROM: Назва компанії англійською мовою автоматично не перекладається

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#745]
Передумови:
Браузер: Chrome
Юзер: ange.la.dvorkova@gmail.com (пароль 123456789)
Переконатись що роль учасника - юридична особа або ФОП

Кроки відтворення:
1. Відкрити http://e-auction.dz-test.net/authorization
2. Натиснути "Профіль"
3. Натиснути на поле "Назва"
4, Натиснути на поле "Назва англійською" (після натиску)
5. Ввести дані в поле "Назва" (наприклад: Комп’ютерний всесвіт)
6. Натиснути на поле "Назва англійською"

Поточний результат:
4. Після натиску, в полі "Назва англійською" буде відображено "Nazva moiei kompanii"
6. Після натиску, в полі "Назва англійською" буде відображено "Nazva moiei kompanii"
![1](https://cloud.githubusercontent.com/assets/13050207/19072836/246537dc-8a40-11e6-9810-932530fda13f.png)

Очікуваний результат:
6. Після натиску, в полі "Назва англійською" буде відображено та дані, які вводились в кроці 5

**Comment by znakharenko** [comment]
Минор, исправим.
