### ISSUE TITLE
PROM: Неправильно відображається назва області "Ровненская" замість "Рівненська"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#746]
Передумови:
Браузер: Chrome
Юзер: an.gela.dvorkova@gmail.com або ang.ela.dvorkova@gmail.com (пароль 123456789) 
Роль учасника неважлива (юридична чи фізична особа)

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/merchant/profile
2. Натиснути "Дані про компанію"
3. В блоці "Юридична адреса" або "Фізична адреса" натиснути на поле "Область"
4. Проскролити список до Полтавської області
5, Перевірити написання наступної області

Поточний результат:
3. Після натиску з’являється випадний список областей України 

Очікуваний результат 
5, Область "Рівненська" буде відображена у списку
![2](https://cloud.githubusercontent.com/assets/13050207/19074032/d414a496-8a46-11e6-9e72-cfeaf184537e.png)

**Comment by znakharenko** [comment]
Готово
