### ISSUE TITLE
PROM: Неможливо видалити скан копію ліцензії для фінансової компанії

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#747]
Передумови:
Браузер: Chrome
Юзер: an.gela.dvorkova@gmail.com (пароль 123456789) 

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/merchant/merchant_edit_page
2. В блоці "Юридична адреса" натиснути на чекбокс "Фінансова компанія" (тим самим активувати його)
3. Завантажити файл до "Скан-копія ліцензії"
4. Зберегти зміни
5. Спробувати видалити завантажений файл

Поточний результат:
5, Файл видалити неможливо, є змога тільки завантажити щось натомість

Очікуваний результат 
5. Присутня іконка для видалення файлу, після натиску якої, файл видаляється

**Comment by znakharenko** [comment]
Можно заменить, но исправим.
