### ISSUE TITLE
Newtend: Аукціон відображаєтьсядвічі у списку для учасника якщо він скасовував пропозицію і подавав знову

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#748]
http://ea.newtend.com/auction/#/create-tender/singlelot/dgfFinancialAssets

Відтворення:
1. Залогуйтесь в аплікацію під користувачем: auc001@mailinator.com
2. Створіть аукціон та опублікуйте його
3. Залогуйтесь в аплікацію під учасником: auc101@mailinator.com
4. Подайте пропозицію до створеної закупівлі
5. Скасуйте подану пропозицію
6. Подайте пропозицію ще раз
7. Зверху сторінки у випадаючому списку виберіть опцію Мої аукціони

Фактично:
Аукціон для якого скасовували пропозицію і подавали ще раз є у списку двічі
![2](https://cloud.githubusercontent.com/assets/13050207/19076765/c4c00222-8a52-11e6-9815-71c2eb106bf3.JPG)

Очікувано:
Аукціон не повинен відображатись двічі

**Comment by SlaOne** [comment]
исправлено.

**Comment by SoftserveQC1** [comment]
Дефект виправлений
