### ISSUE TITLE
"Авторизація". Для того щоб залогуватись новим користувачем потрібно вручну витерти дані (логін і пароль) попереднього користувача

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#75]
Крок 1. Логуємся як юзер1
Крок 2. виходимо з аплікації
Крок3. В тому ж вікні бровзера пробуємо залогуватись новим користувачем
як результат в вікні "Авторизація" відображаються логін і пароль користувача з Крок1.
Для того щоб залогуватись новим користувачем потрібно вручну витерти дані (логін і пароль) попереднього користувача

**Comment by lerich** [comment]
Каким браузером? Спасибо

**Comment by yuliyaSoftserve** [comment]
FireFox v 35.0.1

**Comment by S-Shevchenko** [comment]
не бага. Можно закрывать

**Comment by OksanaPakholok** [comment]
03/03/2015, http://services.e-tender.biz:100/#/login, перетестовано і відтворюється тільки у Firefox.

![firefox](https://cloud.githubusercontent.com/assets/11062040/6463503/59b469ca-c1bb-11e4-8aa0-b66c47938089.png)

Прошу підтвердження, що це не дефект

**Comment by OksanaPakholok** [comment]
@lerich
