### ISSUE TITLE
DTO: "Сайт недоступний" повідомлення на логін пейджі і при закінченні сесії браузера

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#751]
Деталі: 
Сайт http://www.dz3.byustudio.in.ua/tenders/current
Тестовий вхід:
login: admin
Pwd: uStudio

Фактичний результат:
1. Некоректний UI поп-апу (текст селектабельний і виходить за рамки, UI зсунуті контроли)
2. Повідомлення, що сайт недоступний, але він функціонуючий.

Очікуваний результат:
1. Повідомлення повинно вигляди коректно при таймауті сесії
2. Нелогічно використовувати "Сайт недоступний" і давати можливість залогуватись.
![session_timeout](https://cloud.githubusercontent.com/assets/19725434/19108225/9fe78dac-8af8-11e6-9d21-808a8215f5d8.JPG)

**Comment by ghost** [comment]
Хоча я підозрюю, що логування взагалі буде забрано з реліз версії

**Comment by w-be** [comment]
Застарілий дефект.
