### ISSUE TITLE
Реєстрація ліквідатора. Немає можливості завантажувати скановану копію рішення дирекції ФГВ щодо призначення.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#753]
посилання:  http://test.ubiz.com.ua/kabinet/settings/
користувач: b.iviktorqc@gmail.com

Відтворення:
1. Зареєструйте Юридичну особу.
2. Спробуйте завантажувати скановану копію рішення дирекції ФГВ щодо призначення.
3. Підтвердіть реєстрацію, перейшовши за посиланням листі-підтвердженні реєстрації.
4. Перейдіть до Налаштуання-Профіль.
5. Спробуйте завантажувати скановану копію рішення дирекції ФГВ щодо призначення.

Очікувано:
На етапі реєстрації, або пізніше в налаштуваннях профілю можливо завантажувати скановану копію рішення дирекції ФГВ щодо призначення.

Фактично:  Не можливо додати будь-які документи до свого профілю.

![image](https://cloud.githubusercontent.com/assets/11888281/19108575/03c8d280-8afa-11e6-8f5a-e0876ab21d7d.png)
![image](https://cloud.githubusercontent.com/assets/11888281/19108506/ce478340-8af9-11e6-8639-a9930092b09d.png)

**Comment by SergeAntonets** [comment]
Через 
![image](https://cloud.githubusercontent.com/assets/7313452/19439187/e59d299c-9485-11e6-8c8a-95d4505c571d.png)
![image](https://cloud.githubusercontent.com/assets/7313452/19439221/fda4f2a4-9485-11e6-9162-bfd8a8cbf9a9.png)

![image](https://cloud.githubusercontent.com/assets/7313452/19439234/0fdf2462-9486-11e6-8f65-2a68ac5418b5.png)
![image](https://cloud.githubusercontent.com/assets/7313452/19439304/5819d2cc-9486-11e6-9d34-60ffaba4d4d4.png)
![image](https://cloud.githubusercontent.com/assets/7313452/19439340/7021b5ce-9486-11e6-93bc-20b23d2555bb.png)

**Comment by oleksandrakulenko** [comment]
При подачи заявки на доступ ликвидатора прикрепить документ возможность есть.
Sergej Antonec [12:22 PM]  
В момент регистрации на площадке  у нас нету разделения  на обычных пользователей и ликвидаторов. У нас можно получить соответствующий доступ . Для этого необходимо в профиле заполнить соответствующую форму, и после администрирования ее  со стороны площадки ему предоставится доступ.
[12:25]  
Повторно отправлять заявку ликвидатором на доступ ликвидатора нельзя
[12:26]  
Изм какой -либо информации возможно только через администратора площадки

**Comment by SoftserveQC1** [comment]
Перевірено на майданчику http://test.ubiz.com.ua/
