### ISSUE TITLE
Реєстрація ліквідатора. В профілі користувача відсутнє поле телефон.

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#754]
посилання: http://test.ubiz.com.ua/kabinet/settings/
користувач: b.iviktorqc@gmail.com

Відтворення:
1. Зареєструйте Юридичну особу.
2. Спробуйте додати телефон.
3. Підтвердіть реєстрацію, перейшовши за посиланням листі-підтвердженні реєстрації.
4. Перейдіть до Налаштуання-Профіль.
5. Спробуйте додати телефон.

Очікувано:
На етапі реєстрації, або пізніше в налаштуваннях профілю можливо додати телефон

Фактично: Поля телефон немає в профілі користувача.
![image](https://cloud.githubusercontent.com/assets/11888281/19108918/79147246-8afb-11e6-97f5-5cb03a73f126.png)

**Comment by sokolov09** [comment]
Телефоны есть на соответствующей вкладке. 
![image](https://cloud.githubusercontent.com/assets/5014700/19353827/53b96416-916d-11e6-9d51-8e6894850130.png)

**Comment by SoftserveQC1** [comment]
Проверено на http://test.ubiz.com.ua
