### ISSUE TITLE
PROM: Не виконується переклад тексту коли вибрана мова англійська

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#757]
Передумови:
Браузер: Chrome
Юзер: angeladv@ukr.net (пароль 123456789)

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/state_auction/list
2. В налаштуваннях змінити мову інтерфейсу на англійську, зберегти зміни
3. Натиснути на "Аукционы"

Поточний результат:
Не весь текст перекладений на англійську, частина залишається російською

Очікуваний результат 
Текст інтерфейсу перекладений на англійську

![3](https://cloud.githubusercontent.com/assets/13050207/19109793/99ca42dc-8aff-11e6-82e1-d799e7fb1928.png)

**Comment by znakharenko** [comment]
Полная локализация планируется на 1-й квартал 2017
