### ISSUE TITLE
Реєстрація ліквідатора. Введені поля Прізвище, Ім’я, По батькові не виводяться в профілі користувача. 

### ISSUE THREAD

**Issue by w-be** [openprocurement/frontend#758]
посилання: http://test.ubiz.com.ua/kabinet/settings/
користувач: b.iviktorqc@gmail.com

Відтворення:
1. Зареєструйте Юридичну особу, заповнивши поля Прізвище, Ім’я, По батькові .
2. Підтвердіть реєстрацію, перейшовши за посиланням листі-підтвердженні реєстрації.
3. Перейдіть до Налаштування-Профіль.
4. Перевірте поле ПІБ керівника, посада

Очікувано:
1. Поле ПІБ керівника, посада містить введену раніше інформацію.
2. Пропоную використовувати однотипні назви полів при реєстрації і редагуванні профілю: 
всюди, або з словом "керівника", або без цього слова.
3. Пропоную поле "ПІБ керівника, посада" замінити на "ПІБ керівника" чи "ПІБ", так як наступне поле на формі "Посада".

Фактично: Поле ПІБ керівника, посада порожнє.

![image](https://cloud.githubusercontent.com/assets/11888281/19109044/45bb121e-8afc-11e6-9f3c-8d04753c3ab3.png)

**Comment by sokolov09** [comment]
1. ФИО которые вводятся при регистрации это параметры из 3 вкладки: Уповноважена Особа

![image](https://cloud.githubusercontent.com/assets/5014700/19353549/652e081a-916c-11e6-86b6-69b55f4d8cac.png)

![image](https://cloud.githubusercontent.com/assets/5014700/19353487/392261f8-916c-11e6-9ba7-70e4447d6ea4.png)

Считаю что issue можно закрывать

**Comment by SoftserveQC1** [comment]
Лінк: http://test.ubiz.com.ua/kabinet/settings/
Відсутня можливість перейти за вкладинкою "Уповноважена Особа"
Користувач: anny.efimenko@gmail.com

**Comment by SoftserveQC1** [comment]
Відтворюється на http://test.torgi.vidol.com.ua/
Користувач: a.kim80008@gmail.com

**Comment by SergeAntonets** [comment]
Нельзя по табам переходить на прямую. Так как проходит  ajax валидация табов при переходах

**Comment by SoftserveQC1** [comment]
Проверено на http://test.ubiz.com.ua
