### ISSUE TITLE
PROM: Сторінка створення аукціону не коректно перекладається коли вибрана англійська мова

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#759]
Передумови:
Браузер: Chrome
Юзер: angeladv@ukr.net (пароль 123456789)

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/state_auction/list
2. В налаштуваннях змінити мову інтерфейсу на англійську, зберегти зміни
3. Натиснути на "Аукционы"
4. Натиснути "New auction"

Очікуваний результат 
Текст інтерфейсу перекладений на англійську

Поточний результат:
Не весь текст перекладений на англійську, частина залишається російською
![6](https://cloud.githubusercontent.com/assets/13050207/19110380/406a8c30-8b02-11e6-9251-c304b541527d.png)

![7](https://cloud.githubusercontent.com/assets/13050207/19110377/40640806-8b02-11e6-9a76-3c83abfb26cd.png)

![8](https://cloud.githubusercontent.com/assets/13050207/19110379/406526d2-8b02-11e6-8dde-c63a2d71d3b2.png)

![5](https://cloud.githubusercontent.com/assets/13050207/19110378/4064bec2-8b02-11e6-9ed3-196a4dea52b4.png)

**Comment by znakharenko** [comment]
Полная локализация планируется на 1-й квартал 2017

**Comment by znakharenko** [comment]
Всё уже гораздо лучше, не идеально, но думаю приемлимо.

**Comment by SoftserveQC1** [comment]
Локалізація виправлена.
