### ISSUE TITLE
PROM: Можливо відредагувати назву предмету продажу під час подання пропозицій на аукціон

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#761]
Передумови:
Браузер: Chrome
Юзер: angeladv@ukr.net (пароль 123456789)

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/state_auction/list
2. Натиснути на "Аукціони"
3. Натиснути "Новий аукціон"
4. Заповнити необхідні поля (наприклад товар Ноутбук Dell Inspiron 7559 (I755810NDW-46) 
5. Зберегти аукціон
6. Натиснути "Редагувати аукціон"
7, Змінити назву предмету продажу (наприклад Комп’ютерна мишка  I7558531410NDW-46

Очікуваний результат 
Не можна змінювати поля під час подання пропозицій

Поточний результат:
Поле "Назва предмета продажу" можна відредагувати і успішно зберегти, деякі поля підсвічуються як активні, хоча для редагування недоступні

![12](https://cloud.githubusercontent.com/assets/13050207/19111827/44ccbe58-8b0a-11e6-818b-6b949724e110.png)

![11](https://cloud.githubusercontent.com/assets/13050207/19111828/44cfab2c-8b0a-11e6-97c7-3a46817920e8.png)

**Comment by znakharenko** [comment]
Пофікшено
