### ISSUE TITLE
DTO: Зміна мови спотворює відображувану інформацію в кабінеті користувача

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#762]
Передумова:
Зайти в будь-який модуль апплікації і спробувати змінити мову

Фактично:
1. Опції мови: укр і укр іконка-прапор
2. Зміна мови спотворює відображувану інформацію в кабінеті користувача

Очікувано:
Якщо це недороблена частина сайту - сховайте цю зміну мови як функціонал
![lang_change](https://cloud.githubusercontent.com/assets/19725434/19111594/0aa02fb8-8b09-11e6-90dd-8f9bc97ccfba.JPG)

**Comment by SoftserveQC1** [comment]
![2016-10-05_14h41_12](https://cloud.githubusercontent.com/assets/13050207/19111887/90d16b00-8b0a-11e6-87a1-32c6f397b3df.png)
Labels are not named, link without icon is present;

**Comment by ghost** [comment]
Дублювання старої баги https://github.com/openprocurement/frontend/issues/351
