### ISSUE TITLE
DTO: UI Помилка в меседжі для завантаження договору приєднання до регламенту

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#764]
![agreement_spelling](https://cloud.githubusercontent.com/assets/19725434/19111952/ddb536d6-8b0a-11e6-9b4a-cdc649c046a9.JPG)

**Comment by PaulBoroday** [comment]
Готово

**Comment by OSerhii** [comment]
Виправлено. Прошу закрити issue.

**Comment by SoftserveQC1** [comment]
Виправлено
![image](https://cloud.githubusercontent.com/assets/13050207/22651532/07df1d68-ec8c-11e6-9e0a-2e6a08c68fd8.png)
