### ISSUE TITLE
Newtend: Етап очікування оплати пропущений - після визначення переможця одразу можна підписати договір

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#765]
http://ea.newtend.com/signin/#/profile/login

Відтворення:
1. Залогуйтесь в аплікацію під користувачем: auc001@mailinator.com
2. Створіть аукціон та опублікуйте його
3. Залогуйтесь під кількома учасниками та подайте пропозиції
4. Дочекайтесь проведення аукціону та переходу в статус Кваліфікація
5. Призначте переможця

Фактично:
Після призначення переможця одразу є можливість завантажити договір 
![default](https://cloud.githubusercontent.com/assets/13050207/19111871/7c58283a-8b0a-11e6-85d1-06a3c5df6ce5.JPG)

Очікувано:
Після призначення переможця система переходить до етапу очікування оплати. Тоді Ліквідатор перевіряє, що оплата здійснена і тоді кваліфікує учасника. Лише після цього можна Опублікувати договір (Тестові сценарії рівень 1 (Організатор), пункт 9 - Перевірка ліквідатором оплати - дії користувача)

**Comment by w-be** [comment]
coolic [4:28 PM]  
как это работает сейчас:
протокол прикладывает Кандидат к своим документам после окончания торгов - статус остается на месте
совершение оплаты валидируется Ликвидатором и переводит статус из pending в active
договор прикладывает Ликвидатор и таким образом финализирует процесс
в будущем (1.5 месяца) каждый из этих этапов будет иметь свой статус
