### ISSUE TITLE
DTO: Іконки що підтверджують валідність уведених даних жовтого кольору (Зелений є більш прийнятним для користувача)

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#767]
На формі реєстрації введіть валідні дані у будь-яку форму (наприклад ім'я);
![2016-10-05_14h58_19](https://cloud.githubusercontent.com/assets/17592908/19112189/2e6553da-8b0c-11e6-9d86-594e78612be0.png)

**Comment by OSerhii** [comment]
Вирішили залишити жовтий колір, прошу закрити дефект.
