### ISSUE TITLE
Newtend: кнопка “Забираю гарантійний внесок зараз” відсутня у учасника, який зайняв 2-ге місце в аукціоні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#768]
http://ea.newtend.com/signin/#/profile/login

Відтворення:
1. Залогуйтесь в аплікацію під користувачем: auc001@mailinator.com
2. Створіть аукціон та опублікуйте його
3. Залогуйтесь під кількома учасниками та подайте пропозиції
4. Дочекайтесь проведення аукціону та переходу в статус Кваліфікація
5. Призначте переможця
6. Залогуйтесь в систему під користувачем чия заявка зайняла 2-ге місце в аукціоні
7. Відкрийте цей аукціон
8. Відкрийте вкладку торги
9. Натисніть на свою пропозицію

Фактично:
Дані про пропозицію відкриті. Внизу є кнопка "Готовий зачекати 15 днів" при натисканні на яку нічого не відбувається.
![default](https://cloud.githubusercontent.com/assets/13050207/19112255/7691b4f0-8b0c-11e6-9cf2-b06e79cecccb.JPG)

Очікувано:
Учаснику, який зайняв 2-ге місце в аукціоні має прийти повідомлення при наступному вході в кабінет про можливість не забирати гарантійний внесок на протязі 15 робочих днів під час яких Переможець аукціону може бути дискваліфікований. В інтерфейсі повідомлення має бути кнопка “Забираю гарантійний внесок зараз”, при натисканні на неї в ЦБД передається інформація про те, що другий кандидат відсутній. (Тестові сценарії рівень 2 (Учасник), пункт 10 -  Отримати повідомлення про визнання Учасника Кандидатом наступним за переможцем - дії користувача)

**Comment by SlaOne** [comment]
согласно ТЗ - https://docs.google.com/document/d/14Yav0iwWOHd-6NeZ_P4fHlNT8e22Hlo24RVz6rSed4M/edit
У випадку відмови переможця від підписання протоколу електронних торгів або не укладення ним договору за результатами електронних торгів із банком протягом 15-ти робочих днів з дати завершення електронних торгів, ЕТС визначає переможцем торгів Учасника з наступною по величині ціновою пропозицією, а при однакових цінових пропозиціях - поданою раніше, за умови, якщо ним був зроблений щонайменше один крок електронних торгів (Аукціону) та за умови згоди такого учасника не повертати гарантійний внесок на протязі десяти робочих днів: в інтерфейсі майданчика це має бути реалізовано кнопкою “готовий зачекати 15 робочих днів”; в ЦБД передається інформація про те, що даний Учасник очікує визначення переможця.

**Comment by w-be** [comment]
[12:40:40] Viktor Bilostennyi: тобто: 2-й учасник просто вилітає, але може своїми діями (натискання кнопки) бути в черзі і не забирати гроші?
[12:41:14] Sergii Kulyk: тут скорее наоборот.
если такой участник ничего не делает, считается, что он еще есть.
если же он нажимает кнопку “отказываюсь ждать 14 дней” - площадка должна уведомить ликвидатора об этом и ликвидатор на основании этого у себя дисквалифицирует его

**Comment by SlaOne** [comment]
на одной из конференций был разговор о том, что ЦБД на данный момент не готова принимать никаких действий со стороны других участников отличных от того, который "ожидает решения".
так же было сказано, что данное решение будет передаваться в ЦБД только после того как будет решение по первому участнику. 
переименовать кнопку? но тогда нужно и в ТЗ внести правки.

**Comment by w-be** [comment]
Попросив Кулика змінити ТЗ.

**Comment by SlaOne** [comment]
переименовали

**Comment by SoftserveQC1** [comment]
Дефект виправлено, чекаємо на додавння бекенду до кнопки “Забираю гарантійний внесок зараз” у наступних ітераціях
