### ISSUE TITLE
При яких умовах тендер має статус "Немає даних"?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#77]
![-](https://cloud.githubusercontent.com/assets/10761162/6082743/42e38e58-ae2c-11e4-8446-3fccfa9922d3.png)

**Comment by S-Shevchenko** [comment]
Статус "Немає даних" виникає під час синхронізації з ЦБД(відразу після створення тендера)

**Comment by lerich** [comment]
Закриваю.
