### ISSUE TITLE
DTO: Поп-апи на етапі реєстрації - аксептування Договору приєднання до Регламенту не закриваються після завантаження документу

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#771]
Фактично:
1. Меседж для завантаження Договору приєднання до Регламенту не закривається після завантаження
2. Меседж для завантаження фін ідентифікації не закривається після завантаження

Очікувано:
Поп-апи автоматично закриваються

**Comment by OSerhii** [comment]
Ми вважаємо поточну реалізацію коректною. Прошу закрити issue.
