### ISSUE TITLE
DTO: Пропущені обов'язкові значення повинні маркуватись червоним кольором

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#772]
![2016-10-05_15h20_41](https://cloud.githubusercontent.com/assets/17592908/19112747/486ae2a6-8b0f-11e6-8d0e-cf84b6e3e471.png)

**Comment by OSerhii** [comment]
На ДТО усі повідомлення про помилки виводяться жовтим кольором. Прошу закрити issue.
