### ISSUE TITLE
PROM: Не зберігаються введені раніше значення полів при зміні області 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#773]
Передумови:
Браузер: Chrome
Юзер: angeladv@ukr.net (пароль 123456789)

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/state_auction/list
2. Натиснути на "Аукціони"
3. Натиснути "Новий аукціон"
4. Заповнити необхідні поля 
5. У блоці "Список предметів продажу"  у пункті "Область" залишити значення "Оберіть область" 
6, Заповнити поля "Поштовий індекс", "Населений пункт", "Адреса"
7, Змінити значення поля "Область" (наприклад: "Вінницька")

Очікуваний результат 
Значення полів  "Поштовий індекс", "Населений пункт", "Адреса" залишаються такими, як були в кроці 6

Поточний результат:
Поля  "Поштовий індекс", "Населений пункт", "Адреса" стають пустими

**Comment by znakharenko** [comment]
Минор, исправим
