### ISSUE TITLE
PROM: неможливість завантажити документацію при створенні аукціону 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#774]
Кроки:
1) Залогуватись як організатор
2) Вибрати _Створити новий аукціон_
3) В полі _Завантаження документації_ завантажити документ
4) Розділ _Список предметів продажу_ в полі _Завантаження документації_ завантажити документ
- виконувалось у Firefox 47

Очікуваний результат: файли розміром до 49 МБ повинні завантажуватись
Актуальний результат: файли не не завантажуються
![default](https://cloud.githubusercontent.com/assets/13050207/19112884/eb25c0e2-8b0f-11e6-8f88-3a9dd5cbe538.JPG)
![1](https://cloud.githubusercontent.com/assets/13050207/19116010/b0a53fda-8b1c-11e6-9544-d5c4298b0a81.JPG)

**Comment by znakharenko** [comment]
Для сендбокса установлено ограничение в 1 мб
