### ISSUE TITLE
DTO: Незрозуміла валідація назви "Офіційного Сайту"

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#775]
Незрозуміла маска по якій назва сайту валідується

![2016-10-05_15h24_37](https://cloud.githubusercontent.com/assets/17592908/19112898/fd8b6b60-8b0f-11e6-8318-35b0cb03dcc7.png)

**Comment by kvskkvsk** [comment]
Вводимый УРЛ проверяется системой на наличии кода ответа 200 и ожидание такого ответа не более 5сек.  В противном случае сайт считается недоступным
