### ISSUE TITLE
Newtend: Заміна завантаженого договору відображається лише після того як перегрузити сторінку

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#776]
http://ea.newtend.com/signin/#/profile/login

Відтворення:
1. Залогуйтесь в аплікацію під користувачем: auc001@mailinator.com
2. Створіть аукціон та опублікуйте його
3. Залогуйтесь під кількома учасниками та подайте пропозиції
4. Дочекайтесь проведення аукціону та переходу в статус Кваліфікація
5. Призначте переможця
6. Завантажте сканкопію договору
7. Натисніть на "Замінити" навпроти завантаженого договору та завантажте інший документ
8. Перегрузіть сторінку

Фактично:
Перший договір стає перекресленим і другий відображається у списку лише після перегрузки сторінки.
Тобто якщо не перегрузити сторінку то складається враження ніби документ не замінений
![default](https://cloud.githubusercontent.com/assets/13050207/19113024/7d560026-8b10-11e6-96f3-25e8250adc0d.JPG)
![default](https://cloud.githubusercontent.com/assets/13050207/19113030/81ee16fa-8b10-11e6-9a63-11806b5cd433.JPG)

Очікувано:
Одразу після заміни договору має з"явитись у списку новий документ, а перший документ має бути перекресленим.

**Comment by SlaOne** [comment]
взяли в работу

**Comment by SoftserveQC1** [comment]
Дефект виправлений
