### ISSUE TITLE
Ubiz: Заголовок "Добавить майно" замість "Додати майно" при створенні мультилота

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#777]
1. Авторизуватись (наприклад : omelen@softserveinc.com ) актуально для фізичної та юридичної особи
2. Зайти до Кабінету та обрати опцію "Продаю"
3. Натиснути кнопку "Продати"
4. Обрати категорію "Мультилот"
5. Обрати будь-яку опцію майна (Автотранспорт, Нерухомість, Інше)

Фактично:
Заголовок "Добавить майно" , а також кнопка внизу вікна "Добавить"
Очікується:
Повинно бути "Додати майно" та кнопка "Додати"

![2016-10-05_1504](https://cloud.githubusercontent.com/assets/13050207/19113042/91dafa60-8b10-11e6-867f-d4e19921eb97.png)
![2016-10-05_1512](https://cloud.githubusercontent.com/assets/13050207/19113041/91d92104-8b10-11e6-9ef8-53bfc16a72e3.png)

**Comment by SergeAntonets** [comment]
изменили
