### ISSUE TITLE
DTO: Відсутня важлива функція "Повторна відправка СМС" 

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#778]
У випадку системного збою або проблем іщ мережою телерадіо оператора, користовачу повинна бути надана функція повторної відпраки смс інакше йому потрібно повторно вводити усі дані, що є абсолютно не прийнятним.

![2016-10-05_15h29_04](https://cloud.githubusercontent.com/assets/17592908/19113209/46a8f91a-8b11-11e6-9051-fd4b2661f583.png)

**Comment by kvskkvsk** [comment]
Эта возможность и так есть. Но она появляется не раньше чем, через 5 минут. СМС-ки ведь не бесплатные.
