### ISSUE TITLE
DTO: Тип "Учасник" - "Фізична особа не може бути Фінансовою Компанією"

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#779]
![2016-10-05_15h44_59](https://cloud.githubusercontent.com/assets/17592908/19113583/1243e070-8b13-11e6-90b0-34a9547408a4.png)

**Comment by PaulBoroday** [comment]
Це відповідальність учасника. Якщо він так зареєструються, з ним навіть договору не буде укладено. Не кажучи вже про участь в аукціонах
