### ISSUE TITLE
Newtend: Кандидат не має можливості завантажити до документів підписаний протокол результатів електронного аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#780]
http://ea.newtend.com/signin/#/profile/login

Відтворення:
1. Залогуйтесь в аплікацію під користувачем: auc001@mailinator.com
2. Створіть аукціон та опублікуйте його
3. Залогуйтесь під кількома учасниками та подайте пропозиції
4. Дочекайтесь проведення аукціону та переходу в статус Кваліфікація
5. Залогуйтесь під учасником, який став переможцем торгів
6. Відкрийте даний аукціон та завантажте до документів підписаний протокол результатів електронного аукціону

Фактично:
Учасник аукціону не має можливості завантажити до документів підписаний протокол результатів електронного аукціону

Очікувано:
Учасник аукціону має мати можливість завантажити до документів підписаний протокол результатів електронного аукціону (Тестові сценарії рівень 2 (Учасник), пункт 11 Публікація кандидатом підписаного протоколу - дії користувача)

**Comment by SlaOne** [comment]
взяли в работу

**Comment by SoftserveQC1** [comment]
Дефект виправлений
