### ISSUE TITLE
PROM: Можливість вибрати годину старту аукціону в минулому 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#781]
Кроки:
1) Залогуватись як організатор
2) Вибрати Створити новий аукціон
3) В полі _День старту електронного акуціону_ вибрати сьогоднішнє число і годину
- виконувалось у Firefox 47

Очікуваний результат: не можна вибрати годину, яка вже пройшла (напр., в 15.00 реального часу вибрати 02.00)
Актуальний результат: можна вибрати будь-яку годину

![default](https://cloud.githubusercontent.com/assets/13050207/19113887/498ecc42-8b14-11e6-82ce-8709a04a21c1.JPG)

**Comment by znakharenko** [comment]
Не э багом, час підтримується тільки на сендбоксі, не бачу сенсу для пісочниці вносити правки.
