### ISSUE TITLE
PROM: Відсутні поля "Право вимоги" та "Майно банку" при створенні лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#782]
Передумови:
Браузер: Chrome
Юзер: angeladv@ukr.net (пароль 123456789)

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/state_auction/list
2. Натиснути на "Аукціони"
3. Натиснути "Новий аукціон"

Очікуваний результат 
Присутні поля "Право вимоги" та "Майно банку" (дропдаун або радіобаттон)

Поточний результат:
Полів "Право вимоги" та "Майно банку" немає

**Comment by znakharenko** [comment]
http://take.ms/Trtyu

Будь ласка вкажіть посилання на термінологію, на скріншоту вище використовується термінологія з регламенту.
