### ISSUE TITLE
Ubiz: В розділі Адреса проживання місто Севастополь відсутнє в дропдауні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#783]
1. Авторизуватись (наприклад : omelen@softserveinc.com ) актуально для фізичної та юридичної особи
2. Увійти в Особистий кабінет
3. В дропдауні Налаштування обрати опцію "Профіль" 

Фактично:  В дропдауні "Область" відсутнє місто Севастополь 
![2016-10-05_1559](https://cloud.githubusercontent.com/assets/13050207/19114133/5d05c6da-8b15-11e6-98bb-79be60b76dc1.png)

Очікуваний результат:  Місто Севастополь відображається , а також відображаються його райони в дропдауні "Райони"

**Comment by SergeAntonets** [comment]
добавлено
