### ISSUE TITLE
PROM: Відсутнє текстове поле "Опис активу" при створенні лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#785]
Передумови:
Браузер: Chrome
Юзер: angeladv@ukr.net (пароль 123456789)

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/state_auction/list
2. Натиснути на "Аукціони"
3. Натиснути "Новий аукціон"

Очікуваний результат 
Присутнє текстове поле "Опис активу"

Поточний результат:
Відсутнє  текстове поле "Опис активу"

![15](https://cloud.githubusercontent.com/assets/13050207/19114909/a41c7a16-8b18-11e6-991e-d021f5ddcf64.png)

**Comment by znakharenko** [comment]
Исправим.
