### ISSUE TITLE
Newtend: в тілі аукціону немає посилання на регламент

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#787]
http://ea.newtend.com/signin/#/profile/login

Відтворення:
1. Залогуйтесь в аплікацію під користувачем: auc001@mailinator.com
2. Створіть аукціон та опублікуйте його
3. У створеному аукціоні знайдіть посилання на регламент

Фактично:
Посилання на регламент відсутнє
![default](https://cloud.githubusercontent.com/assets/13050207/19115295/187953f6-8b1a-11e6-8cbc-a969b339e3f4.JPG)

Очікувано:
В тілі аукціону має бути присутнє посилання на регламент: 
https://drive.google.com/file/d/0B7KIe21cMRzrbm9oZ3dsS0RsVG8/view?usp=sharing
(Тестові сценарії рівень 1 (Ліквідатор), очікуваний результат до пункту 2)

**Comment by SlaOne** [comment]
![screenshot from 2016-10-05 17 00 58](https://cloud.githubusercontent.com/assets/15046328/19116227/5dd643b6-8b1d-11e6-9390-609a998edd56.png)
ссылка на регламент присутствует при просмотре аукциона. находится внизу страницы под датами аукциона.
