### ISSUE TITLE
PROM: у поле кількість можна вводити будь-які символи

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#788]
Передумови:
Браузер: Firefox 47

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/state_auction/list; залогуватись як організатор
2. Натиснути на "Аукціони"
3. Натиснути "Новий аукціон"
4. Заповнити поле _Kількість_

Очікуваний результат: в дане поле можна вводити тільки цифрові значення
Актуальний результат: в дане поле можна вводити будь-які значення
![default](https://cloud.githubusercontent.com/assets/13050207/19115549/1534f078-8b1b-11e6-9c79-313108c78b54.JPG)

**Comment by znakharenko** [comment]
Не баг, валідація відбувається при сабміті форми.
