### ISSUE TITLE
PROM: Організатор не отримує посилання для перевірки публікації на публічному порталі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#791]
Передумови:
Браузер: Chrome 53.0.2785.143 m
Юзер: angeladv@ukr.net (пароль 123456789)

Кроки відтворення:
1. Відкрити https://my.e-auction.dz-test.net/cabinet/purchases/state_auction/list
2. Натиснути на "Аукціони"
3. Натиснути "Новий аукціон"
4. Заповнити всі необхідні поля
5. Зберегти аукціон

Очікуваний результат 
Організатор отримує повідомлення про публікацію в ЦБД і посилання для перевірки публікації на публічному порталі

Поточний результат:
Організатор отримує повідомлення лише про публікацію в ЦБД
![20](https://cloud.githubusercontent.com/assets/13050207/19117131/a54c4314-8b20-11e6-95b1-5e47ed1049ef.png)

**Comment by znakharenko** [comment]
На данный момент площадка выполняет размещение лотов. Соответственно ссылка на публичный портал не имеет особого смысла.

**Comment by SoftserveQC1** [comment]
Зачинено
