### ISSUE TITLE
DTO: [Створення лоту/Документація до лоту] Некоректний пункт в дропдауні "Визначте рівень"

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#792]
![default](https://cloud.githubusercontent.com/assets/19725434/19117539/01759978-8b22-11e6-9f5a-d12374200b59.JPG)

**Comment by PaulBoroday** [comment]
Це коректний пункт. Щонайменьше одна сутність item створюється в момент генерації форми створення всього аукціону і, відповідно, до неї вже можна долучити документ. А те, що в поточному сатусі в неї немає публічної назви - хто винен організатору, шо він форму знизу вверх заповнює?
