### ISSUE TITLE
PROM:Chrome. Неможливо завантажити документ лоту повторно після видалення

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#793]
Передумови:
Браузер: Chrome 53.0.2785.143 m

Кроки відтворення:
1. Перейти за посиланням http://e-auction.dz-test.net/authorization
2. Увійти під користувачем Організатор
3. Перейти до вкладки Аукціони
4. Створити новий Аукціон 
5. Перейти до секції "Завантаження документації" та завантажити будь який документ
6. Видалити документ 
7. Завантажити заново документ той самий документ.

Очікуваний результат: Документ завантажився заново
Актуальний результат: Документ не завантажився.
http://screencast.com/t/lcY4klHnjYM

**Comment by znakharenko** [comment]
Нельзя загрузить тот же документ, другой можно (особенность реализации). Посмотрим что можно сделать.

**Comment by znakharenko** [comment]
В процессе рефакторинга компонента работы с файлами, который решит данную проблему. 1-й квартал 2017
