### ISSUE TITLE
DTO: [МОЇ АУКЦІОНИ/Поточні аукціони] Дубляж кнопок + недоцільне розташування елементів

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#797]
**Наявний результат:**
1. Елемент 1 та 2 і 3 розміщенні на дуже великій відстані один від одного. (див скріншот)
2. Елемент 2-3 дублюють один одного.
3. На місці елементу 2 з'являється кнопка серч, це конфузить користувача.
4. Кнопка "Пошук" стрибає з місця на місце.

**Кроки:**
1.  Відкрий Мої аукціони/ Поточні аукціони,
2. Клікни РОЗШИРЕНИЙ ПОШУК
3. Закрий РОЗШИРЕНИЙ ПОШУК

**Очікувано**
Користувач не шукає кнопку закрити РОЗШИРЕНИЙ ПОШУК по всій сторінці, кнопка вкл/викл знаходиться на одному місці, якщо є підпис (Додатково) то він не дублюється іконкою "Х"

![2016-10-05_17h59_15](https://cloud.githubusercontent.com/assets/17592908/19118748/1624b68e-8b26-11e6-801b-6b119429bd80.png)
![2016-10-05_17h59_24](https://cloud.githubusercontent.com/assets/17592908/19118750/18af3154-8b26-11e6-9502-0f5800596f85.png)

**Comment by OSerhii** [comment]
Прошу закрити дефект, вирішили залишити у такому вигляді.
