### ISSUE TITLE
Privat: Період уточнення співпадає з періодом пропозицій

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#798]
Посилання: http://sell.pb.ua
користувач: +380102030405
Передумови: Створенний аукціон на http://ea.newtend.com/ (на приклад: UA-EA-2016-10-05-000094)

Відтворення: 
1. Авторизуватись у Приват-аукціоні
2. Знайти та відкрити створений аукціон

Очікувано: 
1. Аукціон має статус Уточнення
2. Статуси Уточнення та Пропозиції мають різні періоди
3. Текстове поле для поставлення питань(уточнень) присутнє

Фактично:
1. Аукціон має статус Пропозиції
2. Статуси Уточнення та Пропозиції мають однаковий період
3. Текстове поле для поставлення питань(уточнень) відсутнє

![image](https://cloud.githubusercontent.com/assets/13050207/19119037/1ae045a2-8b27-11e6-8683-a30afffe95ec.png)

**Comment by pbil** [comment]
Ось аукціон про який йде мова
http://public.api-sandbox.ea.openprocurement.org/api/2.3/auctions/8093e6702e214ab0a42cb4f06621a185

відповідно
"enquiryPeriod": {"startDate": "2016-10-05T18:02:20.993644+03:00", "endDate": "2016-10-31T14:59:00+02:00"}
"tenderPeriod": {"startDate": "2016-10-05T18:02:20.993644+03:00", "endDate": "2016-10-31T14:59:00+02:00"}

**Comment by myroslav** [comment]
В процедурах фонду періоди співпадають, тому пункти 1 та 2 не актуальні. Пункт 3 потребує уваги.

**Comment by pbil** [comment]
П. 3 поправили, вдячні за вказівку!

**Comment by SoftserveQC1** [comment]
Текстове поле для поставлення питань (уточнень) присутнє. Пункт 3 виправлений.
