### ISSUE TITLE
DTO: Запрошення учасників до аукціону через email не прийшли

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#800]
Деталі:
При створенні аукціону можна скористатись фічею запросити учасників, ввівши їх email.

Фактично:
Запрошення не прийшло на мейл

Очікувано:
Запрошення мало б прийти

**Comment by kvskkvsk** [comment]
Отправка работала и работает. Проверьте настройки своей почты. Также известны случая, когда на некоторые почтовые ящики письма не доходят, т.к. не проходят какие-то фильтры. Особенно это наблюдается на meta.ua

**Comment by OSerhii** [comment]
Дефект не відтворюється, листи приходять як і очікується. Прошу закрити issue.
