### ISSUE TITLE
DTO: При реєстрації Учасника (фізичної, юридичної особи, фін компанії) відсутня "Можливість завантажувати документи"

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#802]
При реєстрації учасника (фізичної, юридичної особи, фін компанії) відсутня "Можливість завантажувати документи":
Можливість завантажувати документи
Можливість завантаження фінансової ліцензії
Можливість завантаження інших документів

**Comment by kvskkvsk** [comment]
Верно. нет такой возможности. Эти документы необходимо каждый раз догружать в предложение к аукциону
