### ISSUE TITLE
DTO: Пробіли не трімаються в в інпутах для введення ціни

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#803]
**Фактично:**
http://www.dto.com.ua/tenders/1741/edit
При створенні Аукціону в полях де вказується ціна можливо ввести пробіли, і це спричиняє відхилення введених даних валідацією "введіть правильні значення"
**Кроки:**
1. Створи новий Аукціон,
2. В інпут з ціною (Початкова ціна реалізації Лоту) введи ціну із пробілами,
3. Чекни фідбек валідації,
**Очікувано:**
Пробіли трімаються і залишається тільки цифри
![2016-10-06_11h46_44](https://cloud.githubusercontent.com/assets/17592908/19146275/75573df8-8bbb-11e6-92ba-38a463d8d670.png)

**Comment by kvskkvsk** [comment]
И не должны
