### ISSUE TITLE
DTO: Період уточнень і Період пропозицій мають ідентичний час

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#804]
![offers](https://cloud.githubusercontent.com/assets/19725434/19146701/53c362b4-8bbd-11e6-9860-40d0144df7e7.JPG)

**Comment by w-be** [comment]
https://docs.google.com/document/d/14Yav0iwWOHd-6NeZ_P4fHlNT8e22Hlo24RVz6rSed4M/edit
Сторінка 15: "Період уточнень збігається з періодом подання пропозицій"
