### ISSUE TITLE
DTO: Оголошення про аукціон не публікується на публічному порталі prozorro (error 404)

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#805]
Перехід на публічний портал було здійснено за згенерованою на майданчику лінкою після 25 хв (заявлених для очікування)
![public_portal](https://cloud.githubusercontent.com/assets/19725434/19148403/3ecd0786-8bc5-11e6-9fd3-60c0db3de69c.JPG)

**Comment by ghost** [comment]
![public_portal2](https://cloud.githubusercontent.com/assets/19725434/19148751/d5f2288e-8bc6-11e6-9a8d-5f82dba81478.JPG)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/19725434/19148876/89c4cb32-8bc7-11e6-8c07-ccb48e6db26b.png)

**Comment by ghost** [comment]
Скасування аукціону теж недоступні на порталі

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/19725434/19150253/666e88ba-8bce-11e6-9ed8-52d98eeddccf.png)

**Comment by PaulBoroday** [comment]
В цих посиланнях "зашито" продуктивну адресу порталу, а аукціони стоворюються вами в пісочниці. Ясна справа, що в продуктивному порталі пісочних аукцинів немає. Ось і маємо 404.

**Comment by OSerhii** [comment]
Прошу закрити issue. Пояснення було надано вище.

**Comment by SoftserveQC1** [comment]
Даний баг можна закрити
