### ISSUE TITLE
DTO: Реєстрація "Учасника" - не можливо ввести жодний номер у "Номер Свідотцтва платника пдв "

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#806]
1. При створені "Учасника вкажіть "" є платником ПДВ"
2. У полі Дані платника ПДВ введіть дані 8-14 цифр

Фактично:
Жодні дані не приймаються
Очікую:
Є маска валідції або тултіп із підказкою, або форма працює як належно і приймає введені значення

**Comment by PaulBoroday** [comment]
Якщо вводити коректні (реальні) дані - все прийметься. Справа в тому, що номер свідотства ПДВ має співпадати із кодом ЄДРПОУ в частині перших 7-ми символів
