### ISSUE TITLE
DTO: Відсутнє повідомлення про успішну реєстрацію Учасника - Юридичної Особи- Фінансової Організації

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#807]
**Фактично**
Після успішної реєстрації учасника відсутнє повідомлення про успішну реєстраці а також не розпочинається проце проходження ідентифікації організації.
Емейл скринька та особистий кабінет пусті, повідомлення відсутні.

![2016-10-06_13h30_19](https://cloud.githubusercontent.com/assets/17592908/19149165/2936f694-8bc9-11e6-93a0-ec7a247b1c7c.png)

**Comment by kvskkvsk** [comment]
> Після успішної реєстрації учасника відсутнє повідомлення про успішну реєстраці

Там и не должно его быть

> а також не розпочинається проце проходження ідентифікації організації.

что имеется в виду?

> Емейл скринька та особистий кабінет пусті, повідомлення відсутні.

На почту, если она действующая и фильтры не удаляют письма, приходит сообщение с логином и сгенерированным паролем
