### ISSUE TITLE
DTO: Відповідь на питання в Обговореннях аукціону не має переносу, зєявляється скролл

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#808]
![image](https://cloud.githubusercontent.com/assets/19725434/19150327/d3acae0c-8bce-11e6-8f9a-f77e8c223962.png)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/19725434/19150531/fe30583a-8bcf-11e6-9516-70de84a50472.png)

**Comment by kvskkvsk** [comment]
И кто так будет отвечать?

**Comment by ghost** [comment]
А ви вважаєте, що відповідь може бути тільки двома словами? Ми зараз не про контент тестового інпуту говоримо
Дуже дивна у вас реакція на дефекти знайдені в вашому софті.

**Comment by kvskkvsk** [comment]
А вы пробовали много нормального текста вписать?

**Comment by ghost** [comment]
Не моя задача вас переконувати, якщо ви не бачите в своєму софті проблем.

**Comment by PaulBoroday** [comment]
Особисто я не можу пригадати слова довшого за 16 символів. Тому, якщо і правда заповнювати форми реалльними даними, ця проблема в реальному житі ніколи не постане
