### ISSUE TITLE
PROM: Текст запитання розкривається через емейл

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#809]
Передумови:
1,Браузер: Chrome  53.0.2785.143 m
2,Створити аукціон в ролі організатора
3,Залогуватись як учасник
4,Знайти аукціон створений в кроці 2
5, Задати запитання і відправити його

Кроки відтворення:
1. Залогуватись як організатор
2, Зайти на електронну пошту, вказану при реєстрації організатора

Очікуваний результат 
Інформація про автора запитання/вимоги не розкривається

Поточний результат:
Текст запитання розкривається через емейл
![21](https://cloud.githubusercontent.com/assets/13050207/19149374/362f4de6-8bca-11e6-89e4-ed5caf189a3c.png)

**Comment by znakharenko** [comment]
Будь ласка поясніть яким чином пов'язані?

Очікуваний результат 
Інформація про автора запитання/вимоги не розкривається

Поточний результат:
Текст запитання розкривається через емейл

У листі відсутня інформація про автора.
