### ISSUE TITLE
Після проведення аукціону, замовник має можливість "Визначити переможця" - двічі.

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#81]
1. Після закінчення аукціону, замовник (який оголосив тендер) повинен перейти у свій кабінет.
2. На закладці "Мої тендери" вибрати назву тендера, зі статусом "Кваліфікація переможця" по якому проходив аукціон.
3. У вікні "Тендер", у нижній частині вікна нажати кнопку "Визначити переможця".
4. У вікні "Переможець", завантажити файл, та нажати кнопку "Підтвердити".
5. Замовник повертається на попереднє вікно "Тендер", де вказана інформація про переможця.
6. В нижній частині цього ж вікна, нажати знову кнопку "Визначити переможця"
7. У вікні "Переможець" інформація про переможця - не відображається, та зявляється повідомлення "Інформація по наступному учаснику ще не імпортована".

![double_winner](https://cloud.githubusercontent.com/assets/10761162/6104828/aa4e49e6-b059-11e4-8765-3ea29be9f73b.png)

**Comment by yuliyaSoftserve** [comment]
У ході подальшого тестування виявилося, що якщо вручну зробити рефреш сторінки, то зявляється кнопка - "Контракт"

![contractrefresh](https://cloud.githubusercontent.com/assets/10761162/6214875/9053e612-b604-11e4-85b0-01b1c860db11.png)

**Comment by S-Shevchenko** [comment]
Да, так реализовано(контракт)

**Comment by OksanaPakholok** [comment]
Прошу переглянути відео, і підтвердити, що дефекту немає, і що поведінка аплікації є очікувана
http://screencast.com/t/YgiRrzqV00iy

@lerich

**Comment by lerich** [comment]
Взяли в работу, спасибо

**Comment by S-Shevchenko** [comment]
Исправлено. Можно закрывать(изменен функционал)
