### ISSUE TITLE
DTO: Некоректна сума відсотків від стартової ціни при поданні пропозицій

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#811]
![image](https://cloud.githubusercontent.com/assets/19725434/19151061/405ae614-8bd3-11e6-8736-47115055033d.png)

**Comment by kvskkvsk** [comment]
10% высчитываются только если в аукционе отсутствует значение гарантированного взноса

**Comment by PaulBoroday** [comment]
Випревлено (прибрали згадку про 10%)
