### ISSUE TITLE
Privat: система оповіщення знаходиться в розробці

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#813]
Посилання: http://sell.pb.ua
Користувач: +380102030405

Відтворення:
1. Авторизуватись в Приват-аукціоні
2. Увійти до аукціону в статусі "Пропозиції"
3. Додати пропозицію

Очікувано: повідомлення про успішну чи невдалу валідацію повинно прийти в особистий кабінет
Фактично: система оповіщення знаходиться в розробці

P.S. Не діють оповіщення про скасування аукціону, та про перемогу в аукціоні

**Comment by SoftserveQC1** [comment]
повідомлення про перемогу в аукціоні, початок/скасування аукціону не надходять учаснику.

**Comment by SoftserveQC1** [comment]
Не надходить повідомлення лише для скасування аукціону

**Comment by pbil** [comment]
У нас не відтворюється вказаний сценарій для скасування аукціону. Будь ласка перевірте ще раз. Або можливо є приклади id для auction, bid або question по яким зможемо перевірити конкретику?

**Comment by SoftserveQC1** [comment]
система оповіщення повністю реалізована та працює по відношенню до всіх можливих повідомлень.
