### ISSUE TITLE
DTO: Торги неможливо провести

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#814]
Деталі:
1. Тайм рейнджі торгів
![image](https://cloud.githubusercontent.com/assets/19725434/19152028/a4070de6-8bd8-11e6-81ef-1f079f4c31c1.png)
2. В період подачі пропозицій було подано 1 валідну пропозицію Учасником
3. В 15:11 подача пропозицій завершилась
![image](https://cloud.githubusercontent.com/assets/19725434/19152090/f7f5115a-8bd8-11e6-9d1b-d5f59eb0cead.png)
4. В 15:16 торги автоматично закрились, не повідомивши Банк про хоч якісь пропозиції
![image](https://cloud.githubusercontent.com/assets/19725434/19152124/2e090d64-8bd9-11e6-8d93-cbd9772ac039.png)
5. Пропозиція Учасника відправилась в чернетказ закритого аукціону
![image](https://cloud.githubusercontent.com/assets/19725434/19152213/ab981edc-8bd9-11e6-9044-623dcd282dd0.png)

**Comment by ghost** [comment]
Конфігураційна помилка (не підтверджена пропозиція)

**Comment by ghost** [comment]
Торги автоматично закрились і з підтвердженими пропозиціями

**Comment by kvskkvsk** [comment]
Торги закрывает ЦБД, а не площадка. В системных сообщениях есть записи об изменении состояния аукциона
