### ISSUE TITLE
DTO: Юзер не має можливості редагувати підтверджену коштами пропозицію

### ISSUE THREAD

**Issue by ghost** [openprocurement/frontend#816]
Фактично: Кнопка "Редагувати" підтверджену коштами пропозицію присутня, а кнопки зберегти відредаговане немає.

Очікувано: Захайдати кнопку і не дозволяти редагувати підтверджену пропозицію
або
Дозволити зберегти редагування додавши кнопку "Зберегти"

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/19725434/19153387/06b6beae-8bdf-11e6-8204-bbba4a610993.png)

**Comment by kvskkvsk** [comment]
Так и должно быть. Любая ставка и любые изменения должны быть подтверждены администрацией, в связи с этим возможно только отменить ставку и создать новую, которая направляется на подтверждение

**Comment by PaulBoroday** [comment]
Так. Це логіка нашого рішення та бізнес логіка нашої компанії. Ми хочемо валідувати все, що йде від нас в систему. Це, власне, ніким і ніяк не заборонено
