### ISSUE TITLE
DTO: Не працює пейджинг на сторінці із аукціонами

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#817]
Кроки:
1) Відкрий http://www.dto.com.ua/tenders/all
2) Перейди на будь-яку сторінку

Фактично:
Контент на сторінці не міняється

Очікувано:
Контент відповідає відкритій сторінці
![2016-10-06_15h47_44](https://cloud.githubusercontent.com/assets/17592908/19152845/a0906960-8bdc-11e6-84cf-da9087f3cfbe.png)
![2016-10-06_15h47_27](https://cloud.githubusercontent.com/assets/17592908/19152846/a0af5258-8bdc-11e6-91fe-fb395ef7e86d.png)

**Comment by PaulBoroday** [comment]
Виправили
