### ISSUE TITLE
DTO: При створенні  Цінова пропозиція - невірний меседж про не валідне значення якщо ціна містила пробіли

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#819]
http://www.dto.com.ua/tenders/1773
1) додай пробіл в значення ставки "Ваша Пропозиція"
2) Надішли запит 

Очікую:
Коректне повідомлення про не валідні значення

![2016-10-06_16h12_30](https://cloud.githubusercontent.com/assets/17592908/19153561/baf01a5a-8bdf-11e6-9688-9f9035bae537.png)

**Comment by PaulBoroday** [comment]
Виправили
