### ISSUE TITLE
Замовник у своєму кабінеті, не може бачити тендери, на які він подавав свої пропозиції, та брав участь в аукціоні.

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#82]
Замовник і учасник подали свої пропозиції, та приймали участь у аукціоні. Але учасник може бачити список тендерів, на які він подавав свою пропозицію у своєму кабінеті, а  замовник - може бачити тільки ті тендери, які він створив, а ці, в яких приймав участь - не може побачити.
![participant_client_tenders](https://cloud.githubusercontent.com/assets/10761162/6105256/d60cd4ea-b05d-11e4-921b-1c323d08025a.png)

**Comment by S-Shevchenko** [comment]
Исправлено. Можно закрывать.

**Comment by lerich** [comment]
Закриваю.
