### ISSUE TITLE
DTO: !Critical! : Цінова пропозиція ставки міняється на незрозуміле значення при введені числа із 6ма знаками і більше

### ISSUE THREAD

**Issue by 2cid-c2t** [openprocurement/frontend#820]
1) Відкрий Ваша пропозиція
2) зроби початкову ставку 2437496505086890759468357656
3) клікни на пусте місце

Фактично
Значення змінене на те що зображено на скріні
Очікую: Введене значення не міняється 
![2016-10-06_16h21_29](https://cloud.githubusercontent.com/assets/17592908/19153895/f41b6090-8be0-11e6-9174-7a8267faf5e5.png)

**Comment by kvskkvsk** [comment]
> зроби початкову ставку 2437496505086890759468357656

Текстом это сколько будет?

> 2.3e27

Согласно математическим правилам:
https://ru.wikipedia.org/wiki/%D0%AD%D0%BA%D1%81%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8C

**Comment by PaulBoroday** [comment]
Ну и давайте оперировать корректными данными? Ведь объективно ставок типа "2437496505086890759468357656" не будет в реальной системе. А то, что показано на скриншоте - это работа яваскрипта, а не площадки
