### ISSUE TITLE
Ubiz: Повідомлення про запитання не відповідає вимогам

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#821]
Попередні умови: Учасником було задано запитання з приводу лоту.
Кроки для відтворення:
1. Увійти до особистого кабінету в ролі організатора.

Фактично: Повідомлення про запитання знаходиться в верхньому кутку екрану, маленького розміру і його лекго пропустити.

![2016-10-06_1235](https://cloud.githubusercontent.com/assets/13050207/19155742/39b2f7ec-8be8-11e6-8e99-32422b626397.png)

Очікувано:  Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до Лоту.

**Comment by SergeAntonets** [comment]
изменили
