### ISSUE TITLE
PROM: організатор не бачить пропозицій, створених учасником

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#822]
Кроки:
1,Створити аукціон в ролі організатора
2,Залогуватись як учасник
3,Знайти аукціон створений в кроці 2
4, Створити пропозицію
5. Залогуватись як організатор
- Firefox 47

Очікуваний результат 
Інформація про пропозицію доступна для організатора

Поточний результат:
Інформація про пропозицію відсутня

**Comment by znakharenko** [comment]
Перепрошую, але інформація про пропозицію не розкривається до аукціону. Поясніть очікуванний результат.
