### ISSUE TITLE
Ubiz: організатор не бачить пропозицій, створених учасником

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#823]
**Кроки:**
1,Створити аукціон в ролі організатора
2,Залогуватись як учасник
3,Знайти аукціон створений в кроці 2
4, Створити пропозицію
5. Залогуватись як організатор

**Очікуваний результат** 
Інформація про пропозицію доступна для організатора

**Поточний результат:**
Інформація про пропозицію відсутня

**Comment by sokolov09** [comment]
такого кейса не должно быть.  Предложения до момента начала аукциона не должны отображаться вообще.
