### ISSUE TITLE
Ubiz: В учасника аукціону відсутнє повідомлення про успішну валідацію в особистому кабінеті

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#824]
**Кроки для відтворення:** 
1. Авторизуватись в ролі учасника 
2. Подати пропозицію на участь в аукціоні

**Фактично:** Повідомлення про спішну валідацію відсутнє в особистому кабінеті.
**Очікувано:** Учасник повинен отримати повідомлення в особистому кабінеті при наступному вході в нього. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до аукціону.

**Comment by SergeAntonets** [comment]
добавлено

**Comment by SoftserveQC1** [comment]
Зараз повідомлення з'являється в розділі "Повідомлення" в особистому кабінеті, але воно не відповідає вимозі , таке яке важко пропустити. "Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до аукціону."

**Comment by SergeAntonets** [comment]
![image](https://cloud.githubusercontent.com/assets/7313452/21764510/305da2ea-d66c-11e6-9136-6a6b49ee033c.png)
