### ISSUE TITLE
PROM: неможливість створити новий аукціон на основі існуючого

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#826]
Кроки:
1,Створити аукціон в ролі організатора
2,Знайти аукціон створений в кроці 1
3. Відредагувати дані
- Firefox 47

Очікуваний результат 
Інформацію можна редагувати

Поточний результат:
Інформацію не можна редагувати

**Comment by znakharenko** [comment]
Не баг, редагувати можливо лише документи. Створення аукціона на основі уснуючого - фіча, яку плануємо додати.
