### ISSUE TITLE
PROM: Немає повідомлень в особистому кабінеті для Учасника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#829]
Кроки відтворення:
Випадок 1
1. Залогінитись як Учасник на https://my.e-auction.dz-test.net/cabinet
2. Подати пропозицію на бідь який лот
3. Подати питання до лоту
Випадок 2
1. Залогінитись як Організатор на https://my.e-auction.dz-test.net/cabinet
2. Скасувати лот до якого Учасник подавав пропозицію/запитання

Очікуваний результат: Учасник повинен отримувати повідомлення з відповідним текстом в Особистому Кабінеті.
Фактичний результат: Учасник отримує повідомлення лише на пошту.

**Comment by znakharenko** [comment]
Особенность площадки.
