### ISSUE TITLE
Коли замовник, той що створив тендер, в "Період уточнень", завантажив файл, то нажавши на нього - файл не відкривається, а замовника навігується на початок сторінки.

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#83]
Якщо замовник завантажить, ще один файл, то другий файл - можна відкрити при натисканні на нього, перший файл - відкрити неможливо.
![waiting_stage](https://cloud.githubusercontent.com/assets/10761162/6106632/bdb1f494-b06b-11e4-98ce-dd6768cfd8b1.png)

**Comment by S-Shevchenko** [comment]
Не воспроизводится.
