### ISSUE TITLE
PROM: Після натиску "Завантажити протокол" з’являється вікно з помилкою

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#833]
Передумови: 
Chrome 53.0.2785.143 m
1. Є створений аукціон
2. Учасник 1 подав пропозицію на аукціон
3. Як Учасник 2 зробити меншу пропозицію ніж учасник з кроку 2
4. Дочекатись завершення аукціону
5. Отримати повідомлення про визнання Учасника 2 кандидатом наступним за переможцем

Кроки:
1. Відкрити сторінку аукціону
2. Проскролити донизу до блоку "Ваша пропозиція"
3. Натиснути "Забираю гарантійний внесок"
4. Натиснути "завантажити протокол" 
![26](https://cloud.githubusercontent.com/assets/13050207/19235482/a023232a-8efa-11e6-9391-970355d7ba95.png)

Очікуваний результат: Відкривається вікно для завантаження протоколу учасником
Актуальний результат: 
![27](https://cloud.githubusercontent.com/assets/13050207/19235484/a928f7ba-8efa-11e6-92e6-2d10da9fb79d.png)

**Comment by znakharenko** [comment]
На данный момент пример протокола отсутствует. Как появится - добавим.

**Comment by znakharenko** [comment]
Добавлен
