### ISSUE TITLE
PROM: Посилання на модуль електронного аукціону не приходить  електронною поштою та у кабінеті Учасника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#834]
Передумови
Chrome 53.0.2785.143 m
1. Створити аукціон
2. Подати пропозицію як Учасник 1
3. Подати пропозицію як Учасник 2
4. Дочекатись завершення періоду прийому пропозицій щодо аукціону

Очікуваний результат: Після завершення періоду прийому пропозицій, отримати посилання на модуль аукціону електронною поштою та у кабінеті Учасника

Актуальний результат: Посилання на модуль аукціону доступне тільки на сторінці самого аукціону
![31](https://cloud.githubusercontent.com/assets/13050207/19236407/d96fa572-8eff-11e6-83af-7b6c1d500a40.png)

**Comment by znakharenko** [comment]
Особенность площадки, секьюрити ишью. При компроментации почты к аукциону можно получить доступ, а так дополнительно надо знать ещё и пароль к кабинету.
