### ISSUE TITLE
PROM:  Немає можливості видалити документацію, що була додана до аукціону 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#835]
Передумови:
Chrome 53.0.2785.143 m
Є створений аукціон

Кроки:
1. Залогуватись як учасник
2. Подати пропозицію до аукціону з передумов
3. Прикріпити файл до блоку "Документація"
4. Натиснути "Створити пропозицію"
5. Проскролити сторінку аукціону донизу
6. Натиснути "Змінити пропозицію"

Очікуваний результат: Можна змінити ціну пропозиції, видалити документи та завантажити нові документи
Актуальний результат: Можна завантажити новий документ замість старого, видалити не можна
![32](https://cloud.githubusercontent.com/assets/13050207/19237005/1f819356-8f03-11e6-8c73-2169c94594e6.png)

**Comment by znakharenko** [comment]
В ЦБД отсутствует функционал удаления документов, можно только заменить. Для "удаления" возможно заменить пустым файлом или файлом с содержанием: "Загружен по ошибке"
