### ISSUE TITLE
PROM: Повідомлення про визнання Учасника переможцем не приходить при наступному вході в кабінет

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#836]
Передумови:
Chrome 53.0.2785.143 m
Створений аукціон
Подано мінімум 2 пропозиції від 2 різних учасників

Кроки
1. Дочекатись завершення аукціону
2. Залогуватись як учасник, який подав пропозицію з більшою ціною (з передумов)

Очікуваний результат: Отримати повідомлення про визнання Учасника переможцем при наступному вході в кабінет і необхідність підписати Протокол на протязі трьох діб. Отримати повідомлення про визнання Учасника переможцем електронною поштою і необхідність підписати Протокол на протязі трьох діб.

Актуальний результат: Немає повідомлення про визнання Учасника переможцем аукціону при вході в особистий кабінет. На електронну пошту повідомлення приходить
![33](https://cloud.githubusercontent.com/assets/13050207/19237303/e7e9eeb4-8f04-11e6-9c7f-b486d013bc2e.png)

**Comment by znakharenko** [comment]
Особенность площадки. Торги в которых победил находятся во вкладке "Мои победы" в интерфейсе.
