### ISSUE TITLE
PROM: Не повний переклад одиниць виміру при створенні аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#837]
Кроки відтворення:
1. Увійти в кабінет як Ліквідатор/Організатор до https://my.e-auction.dz-test.net/cabinet
2. Стврити новий Аукціон
3. У секції "Список предметів продажу"/ Конкретна назва предмету продажу відкрити список одиниць виміру

Поточний результат: Не всі одиниці виміру перекладені українською (тыс.штук, грамм, киловатт час, единица, кВАр/час, гигакалория)
Очікуваний результат: Усі одиниці виміру повинні відображатись тією ж мовою, що обрана для інтерфейсу. 
![image](https://cloud.githubusercontent.com/assets/13050207/19237487/bf2e1a4e-8f05-11e6-95fb-e691baff8b23.png)

**Comment by znakharenko** [comment]
В процессе фикса.

**Comment by znakharenko** [comment]
Должно было стать гораздо лучше

**Comment by SoftserveQC1** [comment]
дефект все ще актуальний
