### ISSUE TITLE
Чи повинне випадаюче меню - заховуватися, у віконному режимі при натисненні кнопки меню і виборі пункту з цього меню?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#84]
Чи користувач повинен повторно нажимати кнонку меню, щоб випадаюче меню заховалося?

![popup_menu_window_mode](https://cloud.githubusercontent.com/assets/10761162/6106910/38a7f304-b06e-11e4-9fba-2fd314d1cf63.png)

**Comment by S-Shevchenko** [comment]
Да, так реализовано.

**Comment by lerich** [comment]
Закриваю
