### ISSUE TITLE
Ubiz: Учасник не отримує повідомлення на пошту про те , що він став переможцем аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#842]
**Попередні умови :** учасник виграв аукціон.
**Кроки:**
1. Учасник перевіряє електронну пошту, яка була вказана під час реєстрації, на наявність листа.

**Очікуваний результат:** Користувая повинен отримати повідомлення про визнання Учасника переможцем електронною поштою і необхідність підписати Протокол на протязі трьох діб.
**Фактично:** Повідомлення на пошту не приходить.

**Comment by SergeAntonets** [comment]
проверил, пришло
