### ISSUE TITLE
Ubiz: Невалідне посилання в повідомленні про скасування аукціону.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#843]
**Попередні умови :** скасувати аукціон.
**Кроки:** 
1. Авторизуватись в ролі організатора котрий скасував аукціон.
2. Зайти до особистого кабінету
3. Зайти в розділ "Повідомлення" 
4. Відкрити повідомлення про скасування аукціону.

**Очікуваний результат:** Організатор отримує повідомлення про публікацію в ЦБД і посилання для перевірки публікації на публічному порталі.
**Фактично:** Організатор отримує повідомлення про публікацію в ЦБД і невалідне посилання, натискаючи на яке потрапляє на сторінку з 404 помилкою.

![2016-10-12_1727_404](https://cloud.githubusercontent.com/assets/13050207/19314016/39ebf26e-90a1-11e6-8084-f0e36e7aae4b.png)

отримане посилання  http://test.ubiz.com.ua/lot/920403 
повинно бути http://test.ubiz.com.ua/lot/920403-1231012/

Посилання , яке отримує користувач таке ж.

**Comment by sokolov09** [comment]
исправлена ссылка
