### ISSUE TITLE
Polonex: неможливо завантажити документацію для організатора аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#849]
Передумови:
Організатор: логін: testadmin@test.t
                      пароль: testpass
адреса майданчика: http://polonex.in.ua/
- виконувалось у Firefox47

Кроки:
1) Залогуватись як Організатор
2) У верхньому меню вибрати "Prozzoro.продажі"
3) Відкривється нове вікно і справа з*явиться кнопка "Додати аукціон". Натиснути цю кпопку
4) У розділі "Завантаження документації" завантажити файли з відповідним розширенням і розміром менше 10 мб

Очікувааний результат: файли з дозволеними розширеннями розіміром до 10 мб можна завантажити

Актуальний результат: файли неможливо завантажити

![1](https://cloud.githubusercontent.com/assets/13050207/19432620/166f6564-9466-11e6-930b-65fa293ce991.JPG)
![2](https://cloud.githubusercontent.com/assets/13050207/19432625/1b9c9318-9466-11e6-9014-faac76bfab34.JPG)
![3](https://cloud.githubusercontent.com/assets/13050207/19432630/1ecc6edc-9466-11e6-923c-659a8410579e.JPG)

**Comment by SoftserveQC1** [comment]
Документи неможливо завантажити на всіх етапах роботи з майданчиком як для Учасника, так і для Організатора.

**Comment by greeschenko** [comment]
не вдалося відтворити помилку файли завантажуються у всіх браузерах та у всіх сценаріях 

пришліть будьласка тестові файли які Ви намагалися завантажити 

![20161020-151903_1366x768](https://cloud.githubusercontent.com/assets/2754533/19559487/ca77ff16-96d8-11e6-87cc-f71a8a8bbe82.png)

**Comment by SoftserveQC1** [comment]
помилку не вдалося відтворити на http://test.polonex.in.ua
Тестувана на IE, Chrome, Firefox
