### ISSUE TITLE
Чим відрізняється тендер з "Включаючи ПДВ" і без ПДВ?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#85]
![create_tender](https://cloud.githubusercontent.com/assets/10761162/6107805/a6df5558-b076-11e4-9678-cdfdffaf75dc.png)

**Comment by myroslav** [comment]
відповідним "прапорцем" помічаються тендери в ЦБД і відповідно ця інформація повинна візуалізуватися постачальникам. При подачі цінової пропозиції постачальнику важливо знати, чи сума, яку він сподівається отримати від замовника за свої товари та послуги включає ПДВ, чи ні.

**Comment by OksanaPakholok** [comment]
Дякую. Питання можна закривати

**Comment by lerich** [comment]
Закриваю.

**Comment by lerich** [comment]
Закриваю
