### ISSUE TITLE
Polonex: проблеми з публікацією аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#850]
Передумови:
Організатор: логін: testadmin@test.t
пароль: testpass
адреса майданчика: http://polonex.in.ua/
- виконувалось у Firefox47

Кроки:
1) Залогуватись як Організатор
2) У верхньому меню вибрати "Prozzoro.продажі"
3) Відкривється нове вікно і справа з*явиться кнопка "Додати аукціон". Натиснути цю кпопку
4) Заповнити всі необхідні поля поля і зберегти аукціон як чернетку
5) Зайти у створену чернетку
6) Натиснути кнопку "Редагувати аукціон"
7) Заповнити необхідні поля і натиснути кнопку "Затвердити та опублікувати в ЦБД

Очікуваний результат: 
Виконуються автоматичні перевірки:
Всі обов’язкові поля заповнені значеннями потрібного типу
Організатор отримує повідомлення про те, що запис знаходиться в стані очікування публікації в ЦБД  
Організатор отримує повідомлення про публікацію в ЦБД з номером оголошеної процедури на кшталт UA-EA-2016-....

Отриманий результат: Повідомлення "Очікування публікації" не зникає протягом 60 хв

![default](https://cloud.githubusercontent.com/assets/13050207/19436254/b326f820-9477-11e6-87ff-d55a88072371.JPG)

**Comment by greeschenko** [comment]
виправлено 

але якщо в старому аукціоні більше одного актива то всі крім першого треба видалити і створити заново вони і давали помилки

**Comment by SoftserveQC1** [comment]
Додаю два відео. записані у Google Chrome 53. Передивіться, будь ласка. Можливо, я роблю помилку при створенні аукціону. 
[Polonex.zip](https://github.com/openprocurement/frontend/files/556053/Polonex.zip)

**Comment by SoftserveQC1** [comment]
Тестувала на майданчику: http://test.polonex.in.ua/ в Google Chrome, Firefox, IE
Не вдалося відтворити проблему
