### ISSUE TITLE
UACE: Користувач- Банк не має можливості фінансово авторизуватись в системі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#852]
**Кроки відтворення**
1. Перейти за посиланням https://eauction.uace.com.ua/register
2. Заповнити форму реєстрації для "Реєстрацiя як Банк"
3. Підтвердити Реєстрацію через пошту
4. Повернутись до кабінета користувача та відкрити вкладку Аукціони
5. Натиснути кнопку "Створити аукціон"

**Актуальний результат:** Немає інструкції або функціоналу для активації Користувача Банк.  
**Очікуваний результат:** Користувач Банк повинен мати можливість здійснити фінансову авторизацію.

![image](https://cloud.githubusercontent.com/assets/13050207/19479393/254710ca-954f-11e6-8633-be80e1aff182.png)

**Comment by PaulBoroday** [comment]
Інструкція зявилась. З приводу фінідентифікації банку (та і взагалі учасників) - то на розсуд майданчику. Майданчик працює через паперовий договір, що і викладено в інструкції наразі
