### ISSUE TITLE
UACE: Немає списку переліку всіх регіонів України при реєстрації/редагуванні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#853]
**Кроки відтворення:**
1. Перейти на форму реєстрації за посиланням https://eauction.uace.com.ua/register або зайти в кабінет вже зареєстрованого користувача та перейти на форму Редагування Компанії ( Моя Компанія/ Інформація про компанію/ Редагувати компанію)
2. Обрати у Випадаючому списку "Країна реєстрацiї - Україна"
3. Відкрити випадаючий список "Регiон / область"

**Актуальний результат:** В списку регаонів/областей немає всіх областей України
**Очікуваний результат:** Список повинен містити всі регіони України
![image](https://cloud.githubusercontent.com/assets/13050207/19480614/ba28eeda-9553-11e6-94bb-f16423244a14.png)

**Примітка:** Випадаючий список Країна реєстрацiї, також містить опцію "Амеріка" 
![image](https://cloud.githubusercontent.com/assets/13050207/19480684/fb0597fa-9553-11e6-9600-7b98baee52ee.png)

**Comment by PaulBoroday** [comment]
Заповнили довідник областей
