### ISSUE TITLE
UACE: Поля введення не мають валідації символів на формі реєстрації\редагуванні

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#854]
1. Перейти на форму реєстрації https://eauction.uace.com.ua/register  або зайти як вже зареєстрований користувач на форму Редагування компанії https://eauction.uace.com.ua/buyer/companies/update
2. Перевірити поля на введення спецсимволів, цифр:
3. Населений пункт
4. Адреса
5. Фінансова ліцензія
6. Поля з секції ДАНІ ПРО УПОВНОВАЖЕНУ ОСОБУ (ДЛЯ ДОГОВОРУ)

**Актуальний результат:** Полі можуть містити спецсимволи та цифри
**Очікуваний результат:** Поля для введенні повинні мати валідацію символів.

![image](https://cloud.githubusercontent.com/assets/13050207/19480996/279c02a8-9555-11e6-9eac-3d3267084735.png)

**Примітка** Те саме спостерігається на формі створення/редагування аукціону 
![image](https://cloud.githubusercontent.com/assets/13050207/19511822/b2c42828-95f1-11e6-9c2e-e2a334f15bdf.png)

**Comment by PaulBoroday** [comment]
Ну, колеги, так, ми не валідуємо текстові поля, розраховуючи на адекватність користувачів. Крім того, ніхто з них не зможе вчитяни активних дій доти, доки адміністрація вручну не активує їх обліковий запис

**Comment by SoftserveQC1** [comment]
Дефект перевірено і закрито.
