### ISSUE TITLE
UACE: Неможливо завантажити документи розміром більше 400 кб при створенні аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#856]
**Кроки відтворення:**
1. Зайти в систему як активований користувач- Банк https://eauction.uace.com.ua/buyer/cabinet
2. Перейти до вкладки Мої Аукціони і настиснути кнопку Створити аукціон
3. Перейти до секції ДОКУМЕНТИ
4. Спробувати завантажити файл розміром більше 400 кб

**Актуальний результат:** Файл не завантажується, і немає повідомлення, в разі якщо даний розмір файлу є завеликим для завантажень.
**Очікуваний результат:** Файл повинен успішно завантажитись. Якщо даний розмір файлу перевищу дозволений ліміт, то повинне бути повідомлення про це.

![image](https://cloud.githubusercontent.com/assets/13050207/19511162/c7fa308c-95ee-11e6-9d4a-63c140df7f24.png)

**Comment by PaulBoroday** [comment]
Це обмеження пісочниці ЦБД. Не наше
