### ISSUE TITLE
Polonex: питання від Учасника відображається не дуже зрозуміло в особистому кабінеті Організатора

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#857]
Передумови:
Організатор: логін: testadmin@test.t
пароль: testpass
Учасник: логін: testmemb1@test.t
пароль: testpass

адреса майданчика: http://polonex.in.ua/
- виконувалось у Firefox47

1) Залогуватись як Організатор і створити аукціон
2) Залогуватись як Учасник
3) Знайти відповідний аукціон. створений Організатором у кроці 1
4) Відкрити аукціон і натиснути кнопку "Додати запитання"
5) Написати запитання і натиснути кнопку "Додати"
6) Залогуватись як Організатор і відкрити аукціон, до якого було додане Учаником запитання

Очікуваний результат: Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до Лоту. 

Актуальний результат: повідомлення відображається так, що його легко пропустити 
![_](https://cloud.githubusercontent.com/assets/13050207/19514709/3c314784-95fd-11e6-9b07-8fedc3ac4e69.JPG)

**Comment by greeschenko** [comment]
ми вважаемо що варіант з блокуванням доступу до кабінету неприпустимий 
цеж не мережевий маркетинг де потрібно людям продати непотрібні речі 

і організатор і учасник максимально вмотивовані не пропустити евент зв'язаний з їх аукціоном чи пропозицією плюс повідомлення дублюються на email
