### ISSUE TITLE
OpenTender: помилка при публікації питання

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#858]
Майданчик: http://eauction.open-tender.com.ua
Користувач: seller@ustudio.com.ua
Передумова: Існуючий тендер

Сценарій:
1. Авторизуватись на майданчику
2. Відкрити "Аукціони"->"Актуальні"
3. Знайти існуючий тендер
4. Поставити питання

Фактично: Повідомлення публікується, але перед цим з'являється Swift_TransportException
Очікувано: Exception мають бути відсутніми

**Comment by PaulBoroday** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Дефект виправлено і успішно перевірено.
