### ISSUE TITLE
UACE: Немає нагадування про запитання без відповіді по лоту в особистому кабінеті

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#859]
**Передумови:** Користувачі Банк та Постачальник ,зареєстровані та фінансово авторизовані в системі. Аукціон/лот створено та опубліковано.
**Кроки відтворення:**
1. Зайти в систему як Постачальник
2. Знайти лот/аукціон і натиснути кнопку Детальніше
3. Перейти на форму Питання/відповіді
4. Заповнити всі необхідні поля та натиснути кнопку Задати Питання
5. Зайти в систему як користувач- Банк
6. Перейти до лоту/аукціону по якому було задано питаня

**Актуальний результат:** Немає ніде в особистому кабінеті повідомлення /гадування про те що є запитання по аукціону без відповіді. Користувач Банк може бачити що існують запитання по лотам лише якщо він відкриє конкретний лот детально.
**Очікуваний результат:** Коли користувач Банк заходить в систему він повинен бачити що існують запитання по лотам без відповіді

**Comment by PaulBoroday** [comment]
Раз на день(по крону) оновлюються події користувача типу "Банк". Нагадування про запитання без відповіді існує у вигляді повідомлення "Запитання до закупiвлi [ТЕСТУВАННЯ] werwe" в модальному окні події(для переходу натиснути кнопку "Події"). Воно буде там доки, поки на запитання не буде отримана відповідь і крон не запустить оновлення.

**Comment by OSerhii** [comment]
Виправлено. Прошу закрити issue.

**Comment by SoftserveQC1** [comment]
Дефект виправлено
