### ISSUE TITLE
Тендер в статусі "Закупівля не відбулась" та "Відмінена закупівля", в полі "Початок аукціону" вказано "Буде визначено після завершення періоду уточнень"

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#86]
Коли не було подано жодної пропозиції, тендер ніколи не перейде в статус "Період Аукціону". Тому коректно було б, в полі "Початок аукціону" відображати назву "Аукціон не проводився".

Такий же статус поля "Початок аукціону": "Аукціон не проводився" ми маємо, коли на тендер була подана 1 пропозиція, яка автоматично стала переможцем, і відповідно аукціон не проводився.

![purchase_not_sold](https://cloud.githubusercontent.com/assets/10761162/6128406/2ee56e20-b13e-11e4-97f8-c9a19b473f16.png)

Також у статусі тендера "Відмінена закупівля", поле "Початок аукціону" теж відображається, як "Буде визначено після завершення періоду уточнень"

![discardproposition](https://cloud.githubusercontent.com/assets/10761162/6165070/80e9f9d2-b2ad-11e4-9bb2-1d36a6478cbb.png)

**Comment by S-Shevchenko** [comment]
Спасибо. Не актуально. Есть общая задача по переименованиям. Можно закрывать.

**Comment by lerich** [comment]
Закрываю

**Comment by lerich** [comment]
закриваю
