### ISSUE TITLE
UACE: Лот/аукціон пропадає з списку аукціонів після його редагування

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#860]
**Кроки відтворення:**
1. Зайти в систему як Банк https://eauction.uace.com.ua/buyer/cabinet
2. Створити або знайти власний активний аукціон
3. Натиснути кнопку Детальніше
4. Натиснути кнопку Редагувати оголошення
5. Перейти до списку усіх власний акціонів натиснувши в верхньому меню Мої аукціони

**Актуальний результат:** Аукціон який редагувався пропав зі списку. Аукціон самостійно повертається в список з затримкою в кілька хвилин. 
**Очікуваний результат:** Список "моїх аукціонів" повинен відображати всі створені аукціони Банку

**Відео:**
http://screencast.com/t/w4Woef4zeND

**Comment by PaulBoroday** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Після редагування пропадає назва лота. В списку Мої Аукціони лишається тільки id аукціона.
Відео http://screencast.com/t/4CbxFFW09yl

**Comment by PaulBoroday** [comment]
Виправлено
