### ISSUE TITLE
UACE: Помилка бази даних при створенні аукціону в минулому часі

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#861]
**Кроки відтворення:**
Зайти в систему як Банк https://eauction.uace.com.ua
Перейти до пункту меню "Мої аукціони"
Натиснути кнопку Створити аукціон
Заповнити всі необхідні поля
В секції ДАТИ ТА ТЕРМIНИ встановити дату або час що вже минув
Натиснути "Зберегти та перейти до публікації"

**Актуальний результат:** Зміни не були збережені, виникла помилка бази даних
*_Очікуваний результат:_ Система не поивинна приймати здачення дат/часу в минулому.

![image](https://cloud.githubusercontent.com/assets/13050207/19517978/0c17e9ee-960d-11e6-95b6-98dafebe4b06.png)
[Error.txt](https://github.com/openprocurement/frontend/files/538857/Error.txt)

**Comment by PaulBoroday** [comment]
Залочили в календарі можливість обирати дату в минулому

**Comment by SoftserveQC1** [comment]
Якщо в календарі обрати поточну дату та будь який час (на 1 год і більше від поточного, менший інтервал вибратм неможливо) всеодно виникає помилка бази і неможливо зберегти лот. 
![image](https://cloud.githubusercontent.com/assets/13050207/19648922/80fc0f26-9a0c-11e6-8740-d7e20e9b1881.png)

**Comment by PaulBoroday** [comment]
Зараз майданчик вже в продуктивну ЦБД дивиться, а там немає акселерації. Відповідно початок и кінець періоду призначається ЦБД на один і той самий день. Тому ви і бачите цю помилку
