### ISSUE TITLE
UACE: Помилка в назві типу документа при створенні ставки

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#862]
**Передумови** Користувачі Банк та Постачальник створені та фінансово авторизовані в системі. Створено та опубліковано аукціон Банком.

**Кроки відтворення:**
1. Подати пропозицію по аукціону/лоту від  користувача- Постачальник
2. Обати тип документа "Ліцензія"

**Актуальний результат:**  Назва документу некоректно відображається

![image](https://cloud.githubusercontent.com/assets/13050207/19522263/33e223b0-961f-11e6-8f53-baa3ec0da178.png)

**Comment by PaulBoroday** [comment]
Виправлено
