### ISSUE TITLE
UACE: Веб елемент для встановлення часу проведення аукціону відображається не корекно

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#863]
**Кроки відтворення**
1. Зайти в систему як вже зареєстрований користувач- Банк https://eauction.uace.com.ua
2. Створити новий аукціон
3. Перейти до секції "ДАТИ ТА ТЕРМІНИ"
4. обрати дату та час для проведення аукціону

**Актуальний результат:** Віджет виглядає поламаним, час виберати не зручно.
**Очікуваний результат:** Час вибрати зручно
![image](https://cloud.githubusercontent.com/assets/13050207/19522535/47f15654-9620-11e6-9c1a-2227ec60e58b.png)

**Comment by PaulBoroday** [comment]
Виправлено
