### ISSUE TITLE
E-tender: Повідомлення про запитання до лоту не відповідає вимогам.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#866]
Лінк на майданчик: http://bid.uat.e-tender.biz
**Попередні умови:** Є створений лот з приводу якого користувач задав запитання.
**Кроки:**
1. Авторизуватись в ролі організатора (замовника).(логін:Gzamovnik2016 , ПІБ:Петров Андрій Васильович. пароль:  Ww123456)

**Очікувано:**  Організатор отримує повідомлення про запитання до лоту при наступному вході в кабінет. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до Лоту. 
**Фактично:** Повідомлення є в особистому кабінеті та к-сть питань відображається в розділі "Питання" (скріншот) , але окремого вікна або якогось сповіщення яке важко пропустити нема. 

![2016-10-20_1539](https://cloud.githubusercontent.com/assets/13050207/19560083/ac63d57e-96db-11e6-8257-8c0caf48c85b.png)

**Comment by SergeDmitriev** [comment]
Прошу убрать метки Prozorro.Sales, это проект тендеров
