### ISSUE TITLE
Polonex: редагування вже створеного аукціону недоступне

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#867]
Передумови:
Організатор: логін: testadmin@test.t
пароль: testpass
адреса майданчика: http://polonex.in.ua/
- виконувалось у Firefox47

Кроки:
1) Залогуватись як Організатор
2) У верхньому меню вибрати "Prozzoro.продажі"
3) Відкривється нове вікно і справа з*явиться кнопка "Додати аукціон". Натиснути цю кпопку
4) Заповнити всі необхідні поля поля і натиснути кнопку "Затвердити та опублікувати  в ЦБД"
5) Зайти у створений аукціон
6) Натиснути кнопку "Редагувати аукціон"
7) Змінити ціну лоту натиснути кнопку "Затвердити та опублікувати в ЦБД

Очікуваний результат: 
Виконуються автоматичні перевірки:
Всі обов’язкові поля заповнені значеннями потрібного типу
Організатор отримує повідомлення про те, що запис знаходиться в стані очікування публікації в ЦБД

Отриманий результат: Неочік
![default](https://cloud.githubusercontent.com/assets/13050207/19560921/2758cd0e-96df-11e6-9243-824616d15add.JPG)
увана помилка (див. скріншот)

**Comment by greeschenko** [comment]
можливо ваш тест співпав з оновленням або відладкою 
помилку не вдалося відтворити 

якщо всеж помилка повторюється пришліть будьласка посилання на цей аукціон

**Comment by SoftserveQC1** [comment]
Додаю два відео. записані у Google Chrome 53. Передивіться, будь ласка. Можливо, я роблю помилку при створенні аукціону. 
[Polonex.zip](https://github.com/openprocurement/frontend/files/556060/Polonex.zip)

**Comment by greeschenko** [comment]
вітаю
помилка з файлу 2016-10-27_1443_create_uaction.swf пов'язана із специфікою розрахунку періодів аукціону на цбд 
тому коли Ви виствляєте дату початку аукціону занадто близько до сьогодні тендер період або період уточнень який не використовується формується у минулому як результат помилка
і чомусь помилка не зв'язана  саме з періодом аукціону
якщо взяти початок періоду аукціону через днів 5 помилки не буде

**Comment by greeschenko** [comment]
у другому відео та сама помилка по тій же причині 
наразі ми шукаємо рішення для оповіщення юзера що обрана дата початку аукціону не підходить

**Comment by SoftserveQC1** [comment]
При редагуванні аукціону дозволено лише додавання документів. Інші зміни недоступні
Майданчик для тестування: http://test.polonex.in.ua
