### ISSUE TITLE
Polonex: аукціон переходить в статус "Аукціон не відбувся" після подання 2-х пропозицій Учасниками

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#868]
Передумови:
Організатор: логін: testadmin@test.t
пароль: testpass
Учасник1: логін: testmemb1@test.t
пароль: testpass
Учасник2: логін: testmemb2@test.t
пароль: testpass
адреса майданчика: http://polonex.in.ua/

виконувалось у Firefox47
1) Залогуватись як Організатор і створити аукціон
2) Залогуватись як Учасник
3) Знайти відповідний аукціон. створений Організатором у кроці 1
4) Відкрити аукціон і натиснути кнопку "Подати пропозицію"
5) Написати пропозицію і натиснути кнопку "Додати"
6) Повторити кроки 2-5 для Учасника2
7) Дочекатись закічення періоду пропозицій

Очікуваний результат: Після закічення періоду пропозицій аукціон переходить в статус "Період аукціону"

Актуальний результат: Після закічення періоду пропозицій аукціон переходить в статус "Аукціон не відбувся"

**Comment by greeschenko** [comment]
для того щоб аукціон відбувся 
треба не просто подати 2 пропозиції а щей кваліфікувати їх через майданчик

**Comment by SoftserveQC1** [comment]
Проблема не відтворюється на майданчику http://test.polonex.in.ua
Тестувала на наступних браузерах: Firefox, Chrome
