### ISSUE TITLE
OpenTender: Неможливо зареєструвати нового користувача

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#870]
Майданчик: http://eauction.open-tender.com.ua

Сценарій:
1. Відкрити сторінку
2. Натиснути "Зареєструватись"
3. Заповнити всі поля
4. Натиснути кнопку "Зареєструватись"

Фактично: Помилка SwiftException
Очікувано: Exception не показується. лист приходить на email

**Comment by PaulBoroday** [comment]
Виправлено

**Comment by SoftserveQC1** [comment]
Перевірено. Функціонал відпрацьовує за очікуванним сценарієм.
Дефект зачинено

**Comment by SoftserveQC1** [comment]
Після реєстрації користувача на пошту не приходило повідомлення з лінкою для активації.
Після чого зареєстрований користувач не міг залогінитися на сайт використовуючи емейл адресу і пароль. Помилка: "Incorrect username or password."
Відновити пароль використовуючи форму не вдалося. Помилка: "Користувача з таким iм\'ям(електронною поштою) не iснує"
Зареєструватися з тієюж поштою не вдалося. Помилка: "Такий логін вже існує."

**Comment by SoftserveQC1** [comment]
перевірено на тестовому майданчику test-eauction.open-tender.com.ua.
помилка відсутня.
