### ISSUE TITLE
OpenTender: велика довжина тексту в кнопці

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#871]
Майданчик: http://eauction.open-tender.com.ua
Користувач: buyer@ustudio.com.ua
Передумова: Існуючий тендер з визначеним переможцем

Сценарій:
1. Авторизуватись на майданчику
2. Відкрити аукціон з передумови
3. Натиснути "Контракт"

Фактично: Назва кнопки занадто довга. Частину тексту не видно.
Очікувано: Назва кнопки повинна бути короткою та/чи вміщатись в розмір кнопки
![image](https://cloud.githubusercontent.com/assets/13050207/19564199/5bb1a20e-96eb-11e6-8aec-485950fb7d81.png)

**Comment by OSerhii** [comment]
Виправлено, прошу закрити.

**Comment by SoftserveQC1** [comment]
Дефект виправлено http://eauction.byustudio.in.ua/
![kontr](https://user-images.githubusercontent.com/13050207/27687136-513213cc-5cde-11e7-9a9f-f4f2681b055a.png)
