### ISSUE TITLE
OpenTender: Помилка при погодженні пропозиції учасника

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#872]
Майданчик: http://eauction.open-tender.com.ua
Користувач: buyer@ustudio.com.ua
Передумова: Існуючий тендер в стадії кваліфікації

Сценарій: 
1. Авторизуватись
2. Відкрити тендер з передумови
3. Натиснути "Протокол ОК"

Фактично: Apiexception
Очікувано: Сторінка оновлюється з новим функціоналом

NOTE: exception не є блокером. При переході назад показується оновлена сторінка

**Comment by PaulBoroday** [comment]
Виправлено
