### ISSUE TITLE
OpenTender: SwiftException під час визнання переможця

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#873]
Майданчик: http://eauction.open-tender.com.ua
Користувач: buyer@ustudio.com.ua
Передумова: Існуючий тендер в стадії кваліфікації

Сценарій: 
1. Авторизуватись
2. Відкрити тендер з передумови
3. Натиснути "Визнати переможцем"

Фактично: Swiftexception
Очікувано: Сторінка оновлюється з відображенням нових можливостей

P.S. Exception не є блокером. При поверненні на попередню сторінку відображаються нові можливості

**Comment by PaulBoroday** [comment]
Виправлено
