### ISSUE TITLE
E-tender: Неможливо зберегти внесені зміни до договору.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#879]
**Лінк:** http://bid.uat.e-tender.biz/#/contracts/e025cd6de9d44c5cac8284cc6d377292 
**Передумови:** Пропозиції по тендеру розглянуто.
**Кроки:**
1. Авторизуватись в ролі організатора (замовника).(логін:Gzamovnik2016 , ПІБ:Петров Андрій Васильович. пароль: Ww123456)
2. Перейти до тендеру по якому було розглянуто пропозиції.
3. Перейти до протоколів розгляду.
4. Перейти до договору заповнити його.
5. Внести зміни до договору та натиснути "зберегти внесені зміни"

**Очікувано:** Зміни збережено.
**Фактично:** Зміни зберегти неможливо з'являється еррор.

![2016-10-21_1746](https://cloud.githubusercontent.com/assets/13050207/19602850/7f633506-97b7-11e6-84fb-e1f6df8eac12.png)

**Comment by SergeDmitriev** [comment]
Вже виправили помилку
