### ISSUE TITLE
Після проведення аукціону, і відхиленні всіх пропозицій, тендер не переходить в статус "Відмінена закупівля", а в - "Пропозиції розглянуто".

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#88]
![incorectstatus](https://cloud.githubusercontent.com/assets/10761162/6164455/14621efc-b2a8-11e4-863e-dc26a6bc124b.png)

**Comment by myroslav** [comment]
Наразі в ЦБД для обох варіантів є один і той самий стан. Розглядається його розділення на два окремих підстани, щоб зняти двозначність. Зараз майданчикам рекомендовано цей "двозначний" стан називати "Пропозиції розглянуто".

Через 1 добу тендер перейде в статус "Неуспішний".

**Comment by yuliyaSoftserve** [comment]
На даний час, після очікування більше ніж 1 доби, статус тендера не перейшов у "Неуспішний".

![no_changes](https://cloud.githubusercontent.com/assets/10761162/6208968/d2cc4a34-b5c8-11e4-813d-a4e6270ce928.png)

Ми маємо таку ж ситуацію, з визначенням переможця, статус тендера, теж залишається в статусі "Пропозиції розглянуто

![winner_not_changed](https://cloud.githubusercontent.com/assets/10761162/6209104/5c3af580-b5ca-11e4-9d85-3b9cad159b35.png)
"

**Comment by S-Shevchenko** [comment]
не воспроизводиться
