### ISSUE TITLE
OpenTender: Реєстраційна форма не дає можливості завантажувати скановані копії

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#886]
Реєстраційна форма не дає можливості завантажувати скановані копії
Очікуваний результат: "Можливість завантажувати скановану копію рішення дирекції ФГВ щодо призначення", "Можливість завантажувати документи: Згода з офертою про персональні дані.", "Можливість завантажувати документи Номер фінансової ліцензії", "Можливість завантаження фінансової ліцензії", "Можливість завантаження інших документів"
Кроки відтворення:
1. Зайти на сайт і відкрити реєстраційну форму
2. Знайти форму для завантаження сканованих копій

Майданчик: http://eauction.open-tender.com.ua

**Comment by OSerhii** [comment]
На майданчику фінансова ліцензія має завантажуватися при кожному розміщенні пропозиції учасником. Тобто вона завантажується не один раз при реєстрації, а тоді коли користувач робить ставку. Так зроблено для того щоби не було ситуації коли користувач робить пропозицію із простроченою ліцензією.

**Comment by SoftserveQC1** [comment]
Дефект виправлено

![123](https://user-images.githubusercontent.com/13050207/27679236-bddb4674-5cc0-11e7-8baa-1e4783fb708a.png)
