### ISSUE TITLE
E-Auction: складно скасувати аукціон.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#888]
**Лінк:** http://e-auction.pro/#/
**Передумови:** Організатор створив аукціон
**Кроки:** (виконується організатором) 
1. Відкрити сторінку аукціону та натиснути "почати процедуру скасування торгів"
2. Надрувувати причину і перейти до вікна з додаванням файлу
3. Через кнопку "Обзор" спробувати додати "документ для скасування"

**Очікувано:** Документ додано, кнопка "Скасувати аукціон" активна 
**Фактично:** Документ не додано, кнопка "Скасувати аукціон" неактивна, скасування аукціону неможливе

**Comment by SoftserveQC1** [comment]
Коментар: скасувати аукціон можна, якщо: (продовження дій ліквідатора)
**Кроки**
4. Зачекати деякий час
5. Поновити сторінку
**Фактично:** тільки тепер видно, що документ з п.3 було додано, кнопка "Скасувати аукціон" стала активною
6. Скасувати аукціон натиснувши на кнопку "Скасувати аукціон"

**Comment by OlegNekovalev** [comment]
Добавили уведомление о том, что необходимо дождаться загрузки документов

**Comment by SoftserveQC1** [comment]
Зникла можливість перевірити зміни. Зникла можливість завантажити документ
![image](https://cloud.githubusercontent.com/assets/13050207/21388726/3ca4028c-c786-11e6-8a96-87d3f4ec0bb1.png)

**Comment by SergeDmitriev** [comment]
Поправили возможность отмены лота
Успешно можно отменять лот, после загрузки, нужно подождать 1 минуту и обновить страницу

**Comment by SoftserveQC1** [comment]
успішно перетестовано
