### ISSUE TITLE
E-Auction: При видаленні  "Позиція аукціону № 1" неможливо додавати позиції аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#889]
**Лінк:** http://e-auction.pro/#/
**Передумови:** зареєстрований банк-ліквідатор.
**Кроки:** (виконуються організатором)

1. Натиснути "Створити оголошення з продажу активу"
2. Видалити "Позиція аукціону № 1"

**Очікувано:** Є можливість додати позиції аукціону
**Фактично:** Немає можливості додати позиції, потрібне перезавантаження сторінки і повторне введення усіх даних

**Comment by OlegNekovalev** [comment]
Виправили

**Comment by SoftserveQC1** [comment]
Можливість видалити "Позиція аукціону №1" закрито.
дефект зачинено
