### ISSUE TITLE
Чи повинна бути можливість додавати файли, на етапі створення тендера?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#89]
У тестовому сценарії: http://ppr.org.ua/files/TestScripts_v1.00_Phase2.pdf,
ДЕНЬ 1, 010-Розміщення оголошення про закупівлю, ст.2,
зазначено, що замовник повинен додати вкладені файли на етапі створення оголошення.

**Comment by S-Shevchenko** [comment]
Да, На данный момент работает так: 
После создания тендера, заходим  и добавляем файлы к тендеру.
![image](https://cloud.githubusercontent.com/assets/10655287/6284060/0c69361a-b8f5-11e4-8a7d-1f230cd8e06e.png)

**Comment by lerich** [comment]
Закриваю.
