### ISSUE TITLE
Ubiz: Після скасування аукціону вискакує повідомлення про скасування при переході на любу сторінку

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#892]
Лінк: http://test.ubiz.com.ua/
Передумови: Зареєструвати юридичну особу
Кроки:
Як організатор, створити аукціон
Скасувати аукціон, заповнити всі необхідні поля. Перейти на інші сторінки, або оновити сторінку.
Фактично: При кожному переході або оновлені сторінки вискакує повідомлення "Аукціон UA-EA-2016-11-17-000718 скасовано! "

**Comment by SergeAntonets** [comment]
![image](https://cloud.githubusercontent.com/assets/7313452/21762985/370bbeb8-d664-11e6-8d67-ada74267349c.png)
Нужно кликнуть по кнопке "Сховати повідомлення", тогда при следующей перезагрузке  с-ма уведомление показывать не будет!
