### ISSUE TITLE
DTO: Фотогалерея до лоту не грузиться.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#894]
Лінк на майданчик: https://www.dto.com.ua
Кроки: 
1. Створити аукціон або зайти на вже створений в якому додані ілюстрації. (наприклад UA-EA-2016-11-16-000012 ) користувач - організатор: omelen@softserveinc.com
2.  В розділі "Документація до лоту" натиснути на лінк "Фотогалерея до лоту".

Очікувано: Відкриваються зображення , котрі були додані до лоту.
Фактично: Ілюстрація не грузиться , виходить за межі вікна. 

![2016-11-17-](https://cloud.githubusercontent.com/assets/13050207/20390287/df60c070-acd6-11e6-9abe-ea69ade0d815.png)

**Comment by PaulBoroday** [comment]
Виправили

**Comment by SoftserveQC1** [comment]
При нажиманні на додані ілюстрації до лоту вони загружаються на комп'ютер і відображаються
