### ISSUE TITLE
OpenTender: Аукціон стартує не з 9-ї години " Старт аукцiону: 21/11/2016 11:57:29"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#895]
OpenTender: Аукціон стартує не з 9-ї години " Старт аукцiону: 21/11/2016 11:57:29"

Кроки для відтворення:
1. Зайти на майданчик як ліквідатор
2. Створити лот та вибрати дату старту аукціону

Очікуваний результат:
Дата старту аукціон з 9:00 вибраного дня

**Comment by oleg4646** [comment]
А почему аукцион должен начинаться в 9.00? Укажите id аукциона.
