### ISSUE TITLE
OpenTender: При наявності запитання до лоту організатор не отримує повідомлення при залогіненню

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#896]
OpenTender: При наявності запитання до лоту організатор не отримує повідомлення при залогіненню

Кроки відтворення:
1. Залогінитися як учасник
2. Написати запитання до лоту
3. Залогінитися як організатор

Очікуваний результат:
Після залогінення як організатор появляється повідомлення про нові запитання

**Comment by PaulBoroday** [comment]
Оновлення подій в кабінеті користувача типу "Банк" відбувається раз на день(по крону). Тому при отриманні запитання, повідомлення про нове запитання з'явиться лише після наступного оновлення, а не після входу в кабінет чи будь-якої іншої події.

**Comment by OSerhii** [comment]
Виправлено, прошу закрити.

**Comment by SoftserveQC1** [comment]
Дефект виправлено http://eauction.byustudio.in.ua/
![1](https://user-images.githubusercontent.com/13050207/27685288-3038079c-5cd6-11e7-8c84-90351f4f0960.png)
