### ISSUE TITLE
Newtend: Неможливо зробити вибір дати при створені копії лоту зі статусом "Не відбувся"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#897]
http://ea-trunk.newtend.com/

Відтворення:
1. Зайти як організатор (ліквідатор) 
2. Створити аукціон
3. Почекати до початку аукціону (оскільки немає пропозицій, аукціон отримає статус "Не відбувся")
4. Перейти до "Мої аукціони"
5. Натиснути на "Створити копію"
6. Натиснути на іконку календаря у полі "День старту електронного аукціону"

Фактично:
Кнопка не працює

Очікувано:
Відкривається календар

![cant enter auction start date](https://cloud.githubusercontent.com/assets/13050207/20396282/5a97ad8c-acee-11e6-9546-18aaee447671.jpg)

**Comment by SlaOne** [comment]
взяли в работу

**Comment by SoftserveQC1** [comment]
Дефект виправлено
