### ISSUE TITLE
Newtend: Учасники аукціону бачать кнопку "Замінити" поруч з документами аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#898]
http://ea-trunk.newtend.com/

Відтворення:
Зайти як організатор (ліквідатор)
Створити аукціон (обов'язково додати документи до аукціону)
Зайти як учасник аукціону (фізичне лице)
Знайти аукціон створений у кроку 2
Зробити пропозицію на аукціон

Фактично:
Поруч з документами аукціону з'явилась кнопка "Замінити"

Очікувано:
Кнопки "Замінити" поруч з документами аукціону немає

Коментар:
На вкладці "Опис" присутні тільки документи аукціону. Документи, які завантажують учасники аукціону є у вкладці "Документи". Учасники аукціону не мають можливості щось змінювати на вкладці "Опис".

![document changing](https://cloud.githubusercontent.com/assets/13050207/20396663/91503c80-acef-11e6-9da0-ab7afa017392.jpg)

**Comment by SlaOne** [comment]
взяли в работу

**Comment by SoftserveQC1** [comment]
Дефект виправлено
