### ISSUE TITLE
E-Auction. Зміна коду CAV в одній позиції аукціону призвидить до зміни коду CAV у всіх позиціях

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#899]
**Лінк:** http://e-auction.pro/#/
**Передумови:** зареєстрований банк-ліквідатор.
**Кроки:** (виконується організатором)

1. Натиснути "Створити оголошення з продажу активу"
2. Обрати код CAV в активі №1 лоту 
3. Додати кілька інших активів лоту
4. Обрати код CAV в активі №2 лоту

**Очікувано:** код CAV в активі №1 лишається тим, який був обраний на кроці 2.
**Фактично:** Зміна коду CAV в одній позиції аукціону призвидить до зміни коду CAV у всіх позиціях

**Comment by SergeDmitriev** [comment]
Убрали проверки, теперь можно выбрать разные классификаторы, перепроверьте пожалуйста

**Comment by SoftserveQC1** [comment]
Перевірено на http://e-auction.pro/#/. Виправлено.
