### ISSUE TITLE
E-Auction. Нестабільна робота системи.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#900]
**Лінк:** http://e-auction.pro/#/

**Замічені ознаки нестабільної роботи системи"
1. Час від часу при створенні аукціону він лишається в статусі "Зачекайте, аукціон обробляється".  Відповідно в загальному переліку аукціонів він не відображається. 
2. Відповідь ліквідатора на питання може не відобразитись в системі
3. Аукціон може лишитись в стані "прийняття пропозицій". Приклад: UA-EA-2016-11-21-000670 все ще в стані "прийняття пропозицій", пройшло >15 хв з очікуваного часу початку.
4. Не відкривається сторінка проведення аукціону: https://github.com/openprocurement/frontend/issues/901 

![1](https://cloud.githubusercontent.com/assets/13050207/20404695/af27736c-ad0e-11e6-9f64-81e873d5a24c.png)
![2](https://cloud.githubusercontent.com/assets/13050207/20404696/af2ec068-ad0e-11e6-823c-e886284fe99a.png)

**Comment by oleksandrakulenko** [comment]
Dmytro Mazenko [11:03 AM]  
уже не актуальны,

**Comment by SoftserveQC1** [comment]
дефект зачинено, як не актуальний
