### ISSUE TITLE
OpenTender: Аукціон з декількох активів з різними CAV не створюється

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#903]
OpenTender: Аукціон з декількох активів з різними CAV не створюється

Кроки відтворення:
1. Залогувати як ліквідатор
2. Створити Аукціон
3. Додати до аукціону декілька активів з різними CAV

Очікуваний результат:
Аукціон з декількома активами з різними CAV створено

**Comment by PaulBoroday** [comment]
Перевірте будь ласка повторно. Оновили цей функціонал

**Comment by SoftserveQC1** [comment]
Функціонал імплементовано на тестовому майданчику
веб адреса http://test-eauction.open-tender.com.ua/
