### ISSUE TITLE
Polonex: Редагування аукціону недоступне

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#904]
Лінк тестового майданчика: http://test.polonex.in.ua
Кроки відтворення:
1.  Зайти як організатор (логін testadmin@test.t)
2. Створити аукціон
3. Редагувати аукціон і натиснути "Затвердити та опублікувати в ЦБД"
Очікуваний результат: успішно завантажені документи, успішно закривається сторінка редагування аукціону
Отриманий результат: неочікувана помилка - стектрейс з PHP Notice
![php notice](https://cloud.githubusercontent.com/assets/13050207/20430698/7e8bb20a-ad9e-11e6-8b32-0b2a4f74ae55.png)

Див. скріншот

**Comment by greeschenko** [comment]
доброго дня вкажіть посилання на аукціон  з помилкою або посилання на чорновик

**Comment by SoftserveQC1** [comment]
[Uploading 2016-11-25_1438.zip…]()

Додаю відео
