### ISSUE TITLE
E-Auction: Під час реєстрації фізичної особи відсутня "Згода з офертою про персональні дані." 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#905]
**Лінк:** http://e-auction.pro/#/register

**Кроки:** перейти по лінці і зареєструвати користувача-фізичну особу.

**Очікувано:** Під час реєстрації користувачу має бути показана оферта про персональні дані. Реєстрація повинна бути бути здійснена лише при згоді користувача з офертою.
**Фактично:** Функціонал згоди з офертою про персональні дані не реалізований

**Comment by OlegNekovalev** [comment]
Функціонал згоди з офертою про персональні дані реалізований

**Comment by SoftserveQC1** [comment]
успішно перетестовано
