### ISSUE TITLE
DTO: Організатор не отримує нагадування про запитання до лоту.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#907]
**Лінк на майданчик:** https://www.dto.com.ua
**Попередні умови:** Є створений лот з приводу якого користувач задав запитання, відповідь на яке не була надана.
**Кроки:**
1. Авторизуватись в ролі організатора. (логін: omelen@softserveinc.com)
**Очікувано:** Отримати нагадування про запитання до Лоту в особистому кабінеті Організатора при наступному вході в нього. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до Лоту.
**Фактично:** Нагадування відсутнє.

**Примітка:** також нагадування нема на пошті.

**Comment by PaulBoroday** [comment]
повідомлення є в кабінеті : http://prntscr.com/duqrl6
Ця штука висить тоти, доки є нерозглянуті запитання

**Comment by OSerhii** [comment]
Зроблено, закрийте issue будь ласка.
