### ISSUE TITLE
DTO: Сайт не відкривається на новій версії ІЕ.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#909]
**Кроки:** 
1. Відкрити https://www.dto.com.ua в ІЕ Version: 11.0.9600.18499.

**Очікувано:** Сайт відкривається і працює.
**Фактично:** З'являється повідомлення "You must have MSIE greater 7!!!"

**Comment by kvskkvsk** [comment]
Предоставьте, пожалуйста, отправляемый заголовок User-Agent

**Comment by SoftserveQC1** [comment]
проблема була через ввімкнений Compatibility Mode
