### ISSUE TITLE
DTO: Нема повідомлення про необхідність підписати Протокол на протязі трьох діб.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#910]
**Лінк:** https://www.dto.com.ua/
**Попередні умови:** Відбувся аукціон в якому було визначено переможця.
**Кроки:**
1. Залогінитись , як переможець аукціону і перейти до особистого кабінету. (наприклад учасник: oleksandra.melenko@gmail.com)

**Очікувано:** В листі про визнання учасника переможцем аукціону повинна бути інформація про необхідність підписати Протокол на протязі трьох діб.
**Фактично:** Інформації про необхідність підписати Протокол на протязі трьох діб нема.

**Comment by PaulBoroday** [comment]
повідомлення є в кабінеті : http://prntscr.com/duqrl6
Ця штука висить тоти, доки є нерозглянуті запитання

**Comment by OSerhii** [comment]
Зроблено, закрийте issue будь ласка.
