### ISSUE TITLE
PROM: Відсутня валідація поля ЄДРПОУ

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#915]
**Лінк:** http://zakupki.dz-test.net
**Кроки:**

1. Зареєструвати організатора. (логін  	omelen@softserveinc.com)
2. Перейти до заповнення профілю.

**Очікувано:** максимальна кількість знаків в полі ЄДРПОУ 8.
**Фактично:** можна ввести більше знаків, а також текст.

![2016-11-23_1100](https://cloud.githubusercontent.com/assets/13050207/20555720/1cbd1560-b16c-11e6-8b03-d85a3394fc88.png)

**Comment by znakharenko** [comment]
Сознательное решение, всё модерируется в ручную. Ограничивать пользователя не имеет смысла.

**Comment by SoftserveQC1** [comment]
згідно з відповіддю майданчика, відбувається обов'язкова модерація з боку співробітника майданчика. без цього реєстрація не буде завершена.
зачинено.
