### ISSUE TITLE
Newtend: Після закінчення аукціону додаються два однакові аудити 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#916]
http://ea-trunk.newtend.com/

Відтворення:
1. Зайти як організатор (ліквідатор)
2. Створити аукціон (майно)
3. Зайти іншими учасниками
4. Зробити пропозиції
5. Дочекатися закінчення аукціону
6. Відкрити лот
7. Перейти на вкладку "Документи"

Фактично:
Додано два аудити, другий замінив перший (отже перший перекреслений)

Очікувано:
Доданий один аудит після закінчення аукціону

![documents 1](https://cloud.githubusercontent.com/assets/13050207/20557126/c9e6cad2-b172-11e6-9abe-fe09bb548c50.jpg)
![documents 2](https://cloud.githubusercontent.com/assets/13050207/20557125/c9e67d52-b172-11e6-9409-c2e494ed5cd9.jpg)

**Comment by SlaOne** [comment]
мы к этим файлам не имеем никакого отношения. после аукциона ЦБД генерит служебный файл в котором хранится история самого аукциона.
ЦБД файл передает - мы отображаем.
ЦБД возвращает два разных файла. один заменяется другим файлом.
