### ISSUE TITLE
Newtend: Лист про відновлення паролю виглядає некорректно

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#917]
http://ea-trunk.newtend.com/

Відтворення:
Відкрити головну сторінку майданчику
Натиснути "ВІДНОВИТИ ПАРОЛЬ" під полем логіну
Ввести правильну пошту
Натиснути надіслати
Зайти на пошту
Відкрити лист від newtend

Фактично:
Лист містить в собі шматки коду

Очікувано:
Лист виглядає нормально

![restore password](https://cloud.githubusercontent.com/assets/13050207/20557174/1e893624-b173-11e6-826b-fd12428ecd19.jpg)

**Comment by SlaOne** [comment]
взяли в работу

**Comment by SoftserveQC1** [comment]
Дефект виправлено
