### ISSUE TITLE
PROM: Відсутня валідація поля ІПН.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#918]
**Лінк:**  http://zakupki.dz-test.net
**Кроки:**

1.Зареєструвати учасника .
2.Перейти до заповнення профілю.

**Очікувано:** максимальна кількість знаків в полі  ІПН 10.
**Фактично:** можна ввести більше або менше знаків, а також текст.

**Comment by znakharenko** [comment]
Сознательное решение, всё модерируется в ручную. Ограничивать пользователя не имеет смысла.

**Comment by SoftserveQC1** [comment]
згідно з відповіддю майданчика, відбувається обов'язкова модерація з боку співробітника майданчика. без цього реєстрація не буде завершена.
зачинено.
