### ISSUE TITLE
Privat: Власник лоту може робити пропозиції на свій власний лот

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#920]
https://sell.pb.ua/

Відтворення:

1. Створити лот
2. Перейти на сторінку лоту

Фактично:
Власник лоту бачить форму для відправлення пропозицій

Очікувано:
Власник лоту не бачить форму для відправлення пропозицій

![propositions](https://cloud.githubusercontent.com/assets/13050207/20557583/b518f420-b174-11e6-94c2-fd89237c3d5b.jpg)

**Comment by kurbpa** [comment]
Исправлено на  sell.pb.ua

**Comment by SoftserveQC1** [comment]
дефект перевірено. Виправлено
