### ISSUE TITLE
E-Auction: Не відображається початкова ціна реалізації лоту у випадку користування пошуком

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#921]
**Передумови:** створений аукціон 
**Кроки:** Перейти у вкладку "Торги" і скористатись пошуком аукціону за номером 

**Очікувано:** усі поля у знайденому аукціоні заповнені відповідними значеннями
**Фактично:** поле "Початкова ціна реалізації лоту" незаповнене 

Відео: https://Max_QC.tinytake.com/sf/MTEyODY0Nl80NDUxNDI1

**Comment by OlegNekovalev** [comment]
Усі поля у знайденому аукціоні заповнені відповідними значеннями

**Comment by SoftserveQC1** [comment]
успішно перетестовано
