### ISSUE TITLE
OpenTender: Переможець аукцону не отримує нотифікація про перемогу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#925]
OpenTender: Переможець аукцону не отримує нотифікація про перемогу

1. Провести тендер і визначити перможця
2. Зайти переможцем аукціону в особистий кабінет

Очікуваний результат:
Отримати повідомлення про визнання Учасника переможцем при наступному вході в кабінет і необхідність підписати Протокол на протязі трьох діб.
Отримати повідомлення про визнання Учасника переможцем електронною поштою і необхідність підписати Протокол на протязі трьох діб.

Отриманий результат:
Переможець аукціону не отримує нотифікації про переможу в аукціону при заході в кабінет

**Comment by OSerhii** [comment]
Зроблено. Закривайте issue.

**Comment by SoftserveQC1** [comment]
Дефект виправлено http://eauction.byustudio.in.ua/
![pop](https://user-images.githubusercontent.com/13050207/27688625-e729294c-5ce3-11e7-9c4d-131f8d6dc197.png)
