### ISSUE TITLE
E-Auction: після закінчення періоду прийняття пропозицій учасники не отримують повідомлення з посиланням на аукціон

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#927]
**Лінк:** http://e-auction.pro/#/
**Передумови:** Організатор створив аукціон, мінімум два учасники зареєстрували пропозиції
**Кроки:** (виконується одним з учасників) 
1. Зачекати закінчення терміну прийняття пропозицій
2. Перевірити електронну пошту, повідомлення в особистому кабінеті

**Очікувано:** Після завершення періоду прийому пропозицій  отримати повідомлення про аукціон, що має відбутись. 
**Фактично:** Повідомлення про початок аукціону не надходить ані електронною поштою, ані повідомленням в особистому кабінеті. Нижче - скріншоти електронної пошти та вкладки "Повідомлення" в особистому кабінеті учасника.
![1](https://cloud.githubusercontent.com/assets/13050207/20793456/c5b9d11c-b7cf-11e6-8951-090a4d087a68.png)
![2](https://cloud.githubusercontent.com/assets/13050207/20793224/a85a7280-b7ce-11e6-9101-b8cfc688d7b7.png)
![3](https://cloud.githubusercontent.com/assets/13050207/20793403/86fb2386-b7cf-11e6-917d-c897e485698d.png)

**Comment by SergeDmitriev** [comment]
Ссылку на участие в аукционе - не отправляем на почту в целях безопасности

**Comment by SoftserveQC1** [comment]
повідомлення не надходять в особисті повідомлення на майданчику також

**Comment by OlegNekovalev** [comment]
![screenshot_47](https://cloud.githubusercontent.com/assets/23699721/21484322/56e49bcc-cb99-11e6-8a09-f111257181fc.png)
![screenshot_48](https://cloud.githubusercontent.com/assets/23699721/21484323/59bd19dc-cb99-11e6-8161-72009016ec47.png)

**Comment by SoftserveQC1** [comment]
Повідомлення з посиланням на аукціон відсутнє

**Comment by SoftserveQC1** [comment]
Повідомлення з посиланням на аукціон все ще не надходить

**Comment by OlegNekovalev** [comment]
В целях безопасности не отправляем ссылку на аукцион

**Comment by SoftserveQC1** [comment]
перевірено та зачинено
