### ISSUE TITLE
E-Auction: переможцю не повідомляється про необхідність підписати протокол протягом трьох діб

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#928]
**Лінк:** http://e-auction.pro/#/
**Передумови:** Організатор створив аукціон, учасники зареєстрували пропозиції, пройшли торги
**Кроки:** (виконується учасником) 
1. Як організатор, визначити переможця аукціону (підтвердити пропозицію учасника) 
2. Як учасник-переможець, перевірити пошту, особистий кабінет

**Очікувано:** учасник отримує повідомлення про визнання його переможцем, та необхідність підписати протокол протягом трьох діб
**Фактично:**  учасник отримує повідомлення ВАША ПРОПОЗИЦІЯ ПІДТВЕРДЖЕНА. Перейдіть в особистий кабінет для ознайомлення з опублікованим рішенням про підтвердження Вашої пропозиції.
Посилання переводить просто в особистий кабінет, не в конкретний аукціон.

**Comment by OlegNekovalev** [comment]
Учасник отримує повідомлення про визнання його переможцем, та необхідність підписати протокол протягом трьох діб
![screenshot_7](https://cloud.githubusercontent.com/assets/23699721/22013714/2cde1f2c-dca3-11e6-9854-e8f2089c494d.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/23699721/22013719/304dcdba-dca3-11e6-8050-0f4aa0ac2970.png)

**Comment by SoftserveQC1** [comment]
дефект виправлено
