### ISSUE TITLE
E-Auction: Не передбачено вказання причини неуспішної валідації модератором.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#929]
**Лінк:** http://e-auction.pro/#/
**Передумови:** Організатор створив аукціон, учасники зареєстрували пропозиції

**Кроки:** 
1. Як модератор, не підтвердити пропозицію одного з учасників

**Очікувано:** модератор може відхилити пропозицію із вказанням причини (натиснувши на відповідну кнопку)
**Фактично:** модератор може лише підтвердити або *не підтвердити* пропозицію (тобто не здійснювати жодних дій), яка буде автоматично відхилена в момент закінчення прийняття пропозицій.  
* Немає окремої кнопки "Відхилити". 
* Неможливо вказати причину непідтвердження пропозиції.

**Comment by OlegNekovalev** [comment]
Модератор може відхилити пропозицію із вказанням причини (натиснувши на відповідну кнопку)

**Comment by SoftserveQC1** [comment]
кнопка для відміни чи підтвердження відсутня
![image](https://cloud.githubusercontent.com/assets/13050207/21431657/d3511586-c870-11e6-9ffa-a9488943221f.png)

**Comment by SoftserveQC1** [comment]
кнопка для відхилення пропозиції все ще відсутня

**Comment by SoftserveQC1** [comment]
дефект перевірено і зачинено
