### ISSUE TITLE
Privat: Власник лоту може задавати питання до свого лоту

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#930]
https://sell.pb.ua/

Відтворення:
Створити лот
Перейти на сторінку лоту

Фактично:
Власник лоту бачить форму для відправлення запитань

Очікувано:
Власник лоту не бачить форму для відправлення запитань

![questions](https://cloud.githubusercontent.com/assets/13050207/20605686/58e4ec8e-b275-11e6-83c7-8e753e90ae21.jpg)

**Comment by kurbpa** [comment]
Исправлено на  sell.pb.ua

**Comment by SoftserveQC1** [comment]
Дефект перевірено
