### ISSUE TITLE
OpenTender: Помилка при створенні аукціону з різними CAV

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#934]
OpenTender: Помилка при створенні аукціону з різними CAV

При створенні аукціону з лотами які мають різні CAV виникає помилка:
"Помилка (#422)
Виникла внутрішня помилка сервера."

1. Залогіниться як ліквідатор
2. Створити аукціон з декількома лотами які мають різні CAV
3. Зберегти та опублікувати аукціон

Очікуваний результат:
Аукціон з декіьлкома лотами з різними CAV створено та опубліковано
Отриманий результат:
Після натискання "Зберегти та перейти до публікування" появляєтьсяпомилка а аукціон зберігається як чернетка, яку також не можна опублікувати

**Comment by w-be** [comment]
користувач: buyer@ustudio.com.ua
веб адреса: https://eauction.open-tender.com.ua/

**Comment by SoftserveQC1** [comment]
Функціонал імплементовано на тестовому майданчику
веб адреса http://test-eauction.open-tender.com.ua/
