### ISSUE TITLE
PROM: Учасник не може перейти до скасованого аукціону на який він подавав пропозицію.

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#937]
**Лінк:** http://zakupki.dz-test.net/gosudarstvennye-zakupki
**Кроки:**
**Передумови:** Створено аукціон.
1. Як учасник (oleksandra.melenko@gmail.com) подати пропозицію на аукціон.
2. Як організатор (omelen@softserveinc.com) скасувати аукціон.
**Випадок № 1:**
3. Як учасник отримати повідомлення на пошту про скасування аукціона. 
4. Перейти за лінком з листа на аукціон. 
**Випадок № 2:** 
3. Як учасник увійти в особистий кабінет.
4. Перейти до скасованого аукціону з таби "Беру участь".

**Очікувано:** Можна переглянути скасований аукціон та причини скасування.
**Фактично:** З'являється помилка виконання запита. 

![2016-11-25_1645](https://cloud.githubusercontent.com/assets/13050207/20628450/b06e30c8-b32e-11e6-8259-f2a6faa53844.png)

**Comment by znakharenko** [comment]
Не повторяется. Возможно были временные проблемы. Проверьте повторно плз.

**Comment by SoftserveQC1** [comment]
дефект зачинено
