### ISSUE TITLE
E-Auction: неповна валідація поля мінімального кроку аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#939]
**Лінк:** http://e-auction.pro/#/
**Передумови:** Залогований організатор 
**Кроки:** 
1. Як організатор, почати створювати аукціон, заповнити поля
- Початкова ціна реалізації Лоту: 100
- Мінімальний крок аукціону, %: 99

**Очікувано:** помилка, оскільки Мінімальний крок аукціону, % згідно UI має бути не більше 5%
**Фактично:** помилка відсутня

2. Як організатор, почати створювати аукціон, заповнити поля
- Початкова ціна реалізації Лоту: 100
- Мінімальний крок аукціону, %: 0.5

**Очікувано:** помилка, оскільки мінімільний крок % згідно UI має бути не менше 3%
**Фактично:** помилка відсутня,

![14](https://cloud.githubusercontent.com/assets/13050207/20630514/edc3e0de-b339-11e6-94d6-f1d97f8ddf16.png)
![15](https://cloud.githubusercontent.com/assets/13050207/20630515/edeb4214-b339-11e6-9abd-4940969010ac.png)

**Comment by OlegNekovalev** [comment]
Добрый день, проблему исправили

**Comment by SoftserveQC1** [comment]
Проблема виправлена: не можна виставити крок аукціону менше 1%. 
Верхня межа кроку аукціону лишилась 100% це ок зі слів Oleksandr Akulenko (скайп повідомлення в групі ProzorroSales Stand up о 13:55)
