### ISSUE TITLE
E-Auction: Важливі повідомлення можуть пройти повз увагу користувачів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#940]
**Лінк:** http://e-auction.pro/#/

В системі передбачені повідомлення, для перегляду яких користувачу потрібно перейти до "Кабінет">"Повідомлення".  

**Приклади важливих повідомлень:**

* Отримати повідомлення про запитання
* Отримати нагадування про запитання/вимоги без відповіді
* Отримати повідомлення про успішну валідацію пропозиції
* Отримати повідомлення про неуспішну валідацію пропозиції
* Отримати повідомлення про скасування Аукціону, на який Учасник задавав запитання чи подавав пропозиції
* Отримати повідомлення про визнання Учасника переможцем аукціону
* Отримати повідомлення про визнання Учасника Кандидатом наступним за переможцем

**Фактично:**  Повідомлення не є такими, яке важко пропустити. 

**Очікувано:** Отримати повідомлення в особистому кабінеті Організатора при наступному вході в нього. Повідомлення має бути таким, яке важко пропустити. Оптимально – окреме вікно, яке блокує доступ до кабінету, доки користувач не перейде до Лоту.

**Comment by OlegNekovalev** [comment]
Добавили окреме вікно, яке блокує доступ до кабінету
![screenshot_1](https://cloud.githubusercontent.com/assets/23699721/21850619/2541b8e8-d814-11e6-84ed-93d1fcb40a5c.png)

**Comment by SoftserveQC1** [comment]
перевірено та зачинено
