### ISSUE TITLE
E-Auction: неможливо створити аукціон з кількома позиціями

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#941]
**Лінк:** http://e-auction.pro/#/
**Передумови:** залогований організатор 
**Дані для трьох позицій аукціону:** CAV 30123200-9, 06020000-8, 39714110-4

**Кроки:** 
1. Як організатор перейти до сторінки створення аукціону (продаж майна банків, що ліквідуються), 
2. Заповнити усі поля валідними даними, обрати завтрашню дату і час та натиснути кнопку "створити оголошення з продажу активу".

**Очікувано:** оголошення про аукціон створено

**Фактично:** помилка створення оголошення про аукціон

![1](https://cloud.githubusercontent.com/assets/13050207/20704974/def0f19e-b629-11e6-9e63-fc1e196d78ff.png)

**Comment by SergeDmitriev** [comment]
Добрый день, проблему исправили
Пример - http://e-auction.pro/#/tenderDetailes/50b4812dd925431a94652ec3baed1825

**Comment by SoftserveQC1** [comment]
Коментар: Дефект більше не відтворюється
