### ISSUE TITLE
Polonex: Помилка при завантаженні документа організатором на стадії кваліфікації

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#946]
Передумови:
Організатор: логін: testadmin@test.t
адреса майданчика: http://test.polonex.in.ua/
Попередьо потрбно створити аукціон, створити пропозиції та перейти на етап кваліфікації переможця

1. Залогуватися як Організатор
2. Знайти попередньо створений аукціон з статусом "Пропозиції розглянуто"
3. Організатор визначає переможця як "Кваліфікований"
4. Натискаємо кнопку "Додати/Оновити документи"
Очікуваний результат: документ успішно доданий
Фактичний результат: неочкувана помилка. Див скріншот 
![error](https://cloud.githubusercontent.com/assets/13050207/20731413/02798180-b693-11e6-8ebc-3df6c1a26fe3.png)

**Comment by greeschenko** [comment]
вкажіть будьласка номер лоту або посилання на нього

**Comment by SoftserveQC1** [comment]
UA-EA-2016-12-02-000639

**Comment by greeschenko** [comment]
виправили цей момент, перевірте будьласка

**Comment by SoftserveQC1** [comment]
Виправлено. Документи завантажуються успішно
адреса майданчика: http://test.polonex.in.ua/
