### ISSUE TITLE
Polonex: Помилка при завантаженні договора в систему Організатором

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#947]
Передумови:
Організатор: логін: testadmin@test.t
адреса майданчика: http://test.polonex.in.ua/
Попередьо потрбно створити аукціон, створити пропозиції та перейти на етап кваліфікації переможця

 1.Залогуватися як Організатор
 2. Знайти попередньо створений аукціон з статусом "Пропозиції розглянуто"
 3.  Організатор визначає переможця як "Кваліфікований"
 4.  Натискаємо кнопку "Підписати договір"
    Очікуваний результат: документ успішно доданий
    Фактичний результат: неочкувана помилка. Див скріншот
Пробувала різні дати для підписання договору

![error1](https://cloud.githubusercontent.com/assets/13050207/20743564/cc7c4764-b6df-11e6-8d62-112d1234cfb2.png)
![error2](https://cloud.githubusercontent.com/assets/13050207/20743661/476bd368-b6e0-11e6-9a6f-f1a1242aea02.png)

**Comment by greeschenko** [comment]
як вказано в помилках дата підписання не може бути в майбутньому та має бути більшою за 2016-11-30 9:22 (дату закінчення періоду розгляду переможців)

**Comment by SoftserveQC1** [comment]
я пробувала різні дати. Вказувала дату більшу за дату закінчення періоду розгляду переможців.
ID Аукціону 	UA-EA-2016-12-02-000634 
Помилка збереження {"status":"error","errors":[{"location":"body","name":"dateSigned","description":["Contract signature date can't be in the future"]}],"status_code":422}

**Comment by greeschenko** [comment]
вітаю, Ви можете або не обирати дату підписання або обрати поточну дату

**Comment by SoftserveQC1** [comment]
При умові якщо не обирати час підписання договору, або вибрати поточний час бага не відтворюється. Ми отримуємо повідомлення "Договір успішно підписаний"
Бага відтворюється якщо вибрати майбутній чи минулий час. Програма не забороняє користувачу вибрати час підписання договору наприклад через 10 хв від поточного часу.

**Comment by greeschenko** [comment]
Вітаю, ми додали додаткові валідації дати тепер юзер одержує повідомлення якщо дата вказана невірно

**Comment by SoftserveQC1** [comment]
Не відтворюється. Перевірено на: http://test.polonex.in.ua та
http://test.e-trading.kiev.ua
