### ISSUE TITLE
Polonex: неможливо зарєструвати ліквідатора, юридичну особу

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#948]
адреса майданчика: http://test.polonex.in.ua/
1. перейти на майданчик
2. перейти на "Реєстрацію" юридичної особи або ліквідатора
3. заповнити всі необхідні поля та додати документи

Фактичний результат: документи додані, проте отримуємо помилку: Файл не завантажено
Очікуваний результат: обліковий запис створений
Фізичну особу вдалося зарєструвати успішно
Тестувана на Firefox, Chrome. 
![error_001](https://cloud.githubusercontent.com/assets/13050207/20744958/6f6bd708-b6e7-11e6-919e-60b48b21b5ec.png)

**Comment by greeschenko** [comment]
додайте будьласка файл який не вдалося завантажити

**Comment by SoftserveQC1** [comment]
додала. Я намагалася додавати різні формати файлів (.png, .jpec, архіви) Помилка виникала при будь-яких завантаженнях
![unnamed](https://cloud.githubusercontent.com/assets/13050207/20828528/a63d4e70-b880-11e6-9972-8a7f534fde87.jpg)

**Comment by greeschenko** [comment]
![6f6bd708-b6e7-11e6-919e-60b48b21b5ec](https://cloud.githubusercontent.com/assets/2754533/20938201/d0465980-bbf2-11e6-876f-e6d77fa422ea.png)

**Comment by SoftserveQC1** [comment]
Згідна. Я вибирала не ту опцію "+Оберіть файли" Успішно додала документи і зареєструвала нового користувача. Проте інтуїтивно дуже легко вибрати не вірну опцію "+Оберіть файли" при додаванні документа.
