### ISSUE TITLE
UACE: Повідомлення валідація полів при реєстрації не змінюються для Фізичної особи

### ISSUE THREAD

**Issue by TedBronson** [openprocurement/frontend#950]
**Кроки відтворення:**
1. Зайти на сайт http://test-eauction.uace.com.ua/register
2. Натиснути кнопку "Зареєструватись"
3. У секції ІНФОРМАЦІЯ ПРО УЧАСНИКА > "ФОРМА ВЛАСНОСТI" обрати "Фізична особа"
4. Натиснути кнопку "Зареєструватись" під формою реєстрації

**Очікуваний результат:**
Повідомлення валідації для полів "ПІБ Особи", "Personal name" та "ІПН" мають бути показані. Вони мають бути відмінні від повідомлень, що показані для Юридичної особи.

**Актуальний результат:**
Повідомлення для полів:
"ПІБ Особи" - Необхідно заповнити "Назва юридичної особи".
"Personal name" - Необхідно заповнити "Company Name in English".
"ІПН" - Необхідно заповнити "Код ИПН".
![validation rules](https://cloud.githubusercontent.com/assets/6704434/21050605/50bc82f0-be24-11e6-9502-f89786eada18.PNG)

**Comment by oleg4646** [comment]
Готово.

**Comment by TedBronson** [comment]
Перевірено, проблему виправлено.
