### ISSUE TITLE
UACE: При відновленні пароля картинка капчі перекрита полем ввода коду

### ISSUE THREAD

**Issue by TedBronson** [openprocurement/frontend#951]
**Серидовище:**
Google Chrome 55.0.2883.87
Firefox 50

**Кроки відтворення:**
1. Зайти на сайт http://test-eauction.uace.com.ua/
2. Натиснути на кнопку "Нагадати пароль"
3. Подивитися на картинку з кодом

**Очікуваний результат:**
Картинка з кодом має бути повністю видима.

**Актуальний результат:**
Картинка з кодом перекривається полем для вводу коду з правого боку. 
![captcha covered](https://cloud.githubusercontent.com/assets/6704434/21094247/bca5fdd4-c05e-11e6-868e-ecd255d2b92b.png)

**Примітка:**
Проблема на відтворюється якщо ширина вікна менше 1200 пікселів.

**Comment by oleg4646** [comment]
Поправили.

**Comment by TedBronson** [comment]
Перевірено, проблема виправлена.
