### ISSUE TITLE
UACE: Значення в полі "Дата рішення виконавчої дирекції" сприймається як не вірне

### ISSUE THREAD

**Issue by TedBronson** [openprocurement/frontend#953]
**Кроки відтворення:**

1. Зайти на сайт http://test-eauction.uace.com.ua/
2. Створити новий аукціон
3. Заповнити поле "Номер лоту за ФГВ"
4. Заповнити поле "Номер рішення виконавчої дирекції ФГВФО про затвердження умов продажу"
5. Обрати дату у полі "Дата рішення виконавчої дирекції ФГВФО про затвердження умов продажу"
Дата має бути більшою за 12 (наприклад 20е число).
6. Зберегти аукціон до Чернетки

**Очікуваний результат:**
Аукціон має бути збережений.

**Актуальний результат:**
Показано повідомлення про помилку. 
'29/02/2016' is not a valid date time value: DateTime::__construct(): Failed to parse time string (29/02/2016) at position 0 (2): Unexpected character
![datetime error](https://cloud.githubusercontent.com/assets/6704434/21141513/4dac7c08-c146-11e6-8025-385418ac2810.PNG)

Примітка:
Повідомлення про помилку не з'являється, якщо дата менше або дорівнює 12.

**Comment by oleg4646** [comment]
Готово.

**Comment by TedBronson** [comment]
Перевірено, проблема виправлена.
