### ISSUE TITLE
UACE: Є можливість додати Договір NDA для процедури "Продаж майна банків"

### ISSUE THREAD

**Issue by TedBronson** [openprocurement/frontend#954]
**Кроки відтворення:**
1. Зайти на сайт http://test-eauction.uace.com.ua/
2. Створити новий аукціон
3. У пункті "Процедура торгу" обрати "Продаж майна банків"
4. У розділі "Документи" завантажити документ
5. Відкрити випадаюче меню "Оберіть тип документа"

**Очікуваний результат:**
Пункт "Договір NDA" має бути відсутнім у списку.

**Актуальний результат:**
Пункт "Договір NDA" присутній у списку.
Є можливість зберегти документ цього типу

**Comment by oleg4646** [comment]
Заблокировали этот пункт.

**Comment by TedBronson** [comment]
Перевірено, проблему виправлено.
