### ISSUE TITLE
E-Auction: Організатор може добавляти і редагувати дані по Virtual Data Room після оголошення аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#956]
**Лінк:** http://e-auction.pro/#/
**Кроки:** (виконуються організатором)

1. Створити оголошення з продажу активів, тип аукціону "Продаж права вимоги за кредитними договорами" на наступний день.

2. Відкрити створений аукціон, додати інформацію в поля Virtual Data Room: "Назва", "посилання".
**Фактично:** є можливість добавляти поля Virtual Data Room: "Назва", "посилання",
**Очікувано:** у вже створеному аукціоні не можна нічого змінювати чи добавляти крім документів та ілюстрацій.

3. Після збереження, відредагувати поля Virtual Data Room: "Назва", "посилання".
**Фактично:** є можливість редагувати поля Virtual Data Room: "Назва", "посилання",
**Очікувано:** у вже створеному аукціоні не можна нічого змінювати чи добавляти крім документів та ілюстрацій.

**Comment by SoftserveQC1** [comment]
Також частково відтворюється на майданчику UACE. У опублікованному посиланні на VDR є можливість змінити Назву документа, але не пряме посилання.

**Comment by oleg4646** [comment]
Убрали возможность редактирования.

**Comment by SoftserveQC1** [comment]
Перевірено, можливість редагування опублікованого посилання на VDR на майданчику UACE вимкнена.

**Comment by SoftserveQC1** [comment]
дефект все ще присутній у eauction

**Comment by SoftserveQC1** [comment]
перевірено та зачинено
