### ISSUE TITLE
UBIZ: Присутня можливість додати договір NDA для процедури "Майна банків"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#958]
**Лінк:** http://test.ubiz.com.ua/
**Кроки:**
1. Залогінитись , як організатор (логін: omelen@softserveinc.com).
2. Створити аукціон, обравши тип "Майно Банку"
3. Перейти до завантаження документів.

**Очікувано:** Можливість завантажувати договір NDA , присутня тільки для "Права вимоги".
**Фактично:** Можливість додати договір NDA присутня також для процедури "Майна банків"

![nda](https://cloud.githubusercontent.com/assets/13050207/21183653/91506610-c211-11e6-85d5-ede3d3e24d2c.png)

**Comment by SergeAntonets** [comment]
исправлено
