### ISSUE TITLE
UACE: Є можливість добавляти дані VDR для аукціону з продажу майна банків

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#961]
**Кроки відтворення:**
1. Зайти на сайт http://test-eauction.uace.com.ua/
2. Створити новий аукціон
3. Обрати "Тип процедури" > "Продаж майна банків"
4. Знайти поля для додавання VDR 

**Очікуваний результат:**
Додавання VDR має бути недоступним при виборі процедури "Продаж майна банків"

**Актуальний результат:**
Є можливість додати та зберегти посилання на VDR.
![vdr](https://cloud.githubusercontent.com/assets/13050207/21184646/10d3e822-c216-11e6-8233-923d30c3d8ee.PNG)

**Comment by oleg4646** [comment]
Готово.

**Comment by SoftserveQC1** [comment]
Перевірено, проблему виправлено.
