### ISSUE TITLE
Newtend: Лист на пошту про перебіг аукціону приходить із не адаптованим змістом

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#962]
http://ea-trunk.newtend.com/

**Опис:** Лист на пошту про перебіг аукціону приходить із не локалізованим під українську мову змістом, зокрема статус аукціону - англійською(як змінна в коді), а підпис майданчика - російською.

**Передумова:**
- Зайти як організатор (ліквідатор)
- Створити аукціон (наприклад майно)
- Зайти як покупец
- Зробити ставку

**Відтворення:**
1) Відмінити аукціон (або можна дочекатися зміни стадії аукціону)
2) Перевірити пошту (як організатором так і учасником)

**Очікуваний результат:** Лист на пошту організатора(учасника) приходить стилізований українською мовою.

**Фактичний результат:** 1) Заголовок листа та повідомлення про статус аукціону є англійською(приклад: cancelled або active.qualification див. додатки)
2) підпис "EA.NEWTEND – это электронная площадка для проведения государственных аукционов." російською мовою.

![1](https://cloud.githubusercontent.com/assets/13050207/21184230/2a3c2b6e-c214-11e6-9e08-9de9763eed4a.png)
![2](https://cloud.githubusercontent.com/assets/13050207/21184229/2a3c2e52-c214-11e6-832b-ad7d63346c4f.png)

**Comment by SoftserveQC1** [comment]
Аналогічно із листами про нові уточнення - в листі замість тексту уточнення йде незрозумілий id http://www.screencast.com/t/LfPwMArX

**Comment by SlaOne** [comment]
взяли в работу

**Comment by SoftserveQC1** [comment]
Дефект виправлено
