### ISSUE TITLE
Smart: NDA додається до майна

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#964]
майданчик: http://test.smarttender.biz/
користувач: ppr_test

сценарій: 
1. Створити аукціон
2. Обрати процедуру Продаж майна банків
3. Вказати всі обов'язкові дані
4. Перейти на вкладку Завантаження документації
5. Завантажити Документ
6. Виділити та переглянути випадаючий список типу документів.

Очікувано: NDA Документ відсутній
Актуально: NDA документ можна обрати і створити з ним даний аукціон

**Comment by AlexRudenko** [comment]
Дороблено.
NDA тепер можна заводити тільки для FinancialAssets.

**Comment by SoftserveQC1** [comment]
дефект виправлено
