### ISSUE TITLE
UACE: Показ некоректного посилання для Публічного паспорту активу та VDR у Чернетці

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#965]
**Кроки відтворення:**
1. Зайти на сайт http://test-eauction.uace.com.ua/
2. Створити новий аукціон
3. Додати посилання на VDR
4. Додати посилання на Публічний Паспорт Активу
5. Зберегти аукціон як Черенетку
6. У Чернетці подивитися на посилання VDR та Публічного Паспорту Активу

**Очікуваний результат:**
Посилання має бути коректно збережене та відображене
![link entered](https://cloud.githubusercontent.com/assets/13050207/21187990/874543be-c222-11e6-937a-1062c9690d68.PNG)

**Актуальний результат:**
Замість посиланнь, доданних на кроках 3 та 4, відображається посилання "http://test-eauction.uace.com.ua/web/uploads/"
![link actual](https://cloud.githubusercontent.com/assets/13050207/21187979/7f19032e-c222-11e6-8e41-25504abd02cc.PNG)

**Примітка:**
Після публікації аукціону посилання відображається корректно, тобто значення посилання зберігається вірно, але не відображається у Чернетці.

**Comment by oleg4646** [comment]
Готово.

**Comment by SoftserveQC1** [comment]
Перевірено, проблему виправлено.
