### ISSUE TITLE
Prom: Договір NDA додається до майна

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#967]
майданчик: https://my.zakupki.dz-test.net/
користувач: omelen@softserveinc.com 

Сценарій: 
1. Авторизуватись, як організатор
2. Створити аукціон
3. Обрати тип процедури Майно
4. Завантажити документ
5. Відкрити випадаючий список

Очікувано: варіант "Договір NDA" відсутній
Актуально: варіант "Договір NDA" присутній

**Comment by znakharenko** [comment]
Принято, исправляем

**Comment by znakharenko** [comment]
Исправлено

**Comment by SoftserveQC1** [comment]
дефект виправлено та зачинено
