### ISSUE TITLE
E-Auction: Не відбувається оновлення статуса аукціону на сторінці 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#969]
**Лінк:** http://e-auction.pro/#/

**Кроки:** 
1. Як ліквідатор, створити аукціон. 
2. Як ліквідатор, перевірити поле "статус аукціону" на сторінці, яка буде йому відкрита.

**Фактично:** статус аукціону відразу після його створення - " Зачекайте, аукціон обробляється". Користувач може довго чекати - статус на сторінці не буде змінюватись. Для оновлення статусу потрібне перезавантаження сторінки.

**Очікувано:** після фактичної зміни статусу ця зміна має бути автоматично відображена на сторінці.

![1](https://cloud.githubusercontent.com/assets/13050207/21228830/f899b354-c2e7-11e6-9266-fa4657bf0c1d.png)

**Comment by SergeDmitriev** [comment]
Добрый день, возможно вы пытались создать тендер, когда пересобирался проект
сейчас процедуры экспортируются быстро, вот например:
продаж майна - http://e-auction.pro/#/tenderDetailes/8084a09f3e634a8e8888626b97325f17
продаж права вимоги - http://e-auction.pro/#/tenderDetailes/a84c1ecdc0244465ae0c9c5dd0b35132

**Comment by SoftserveQC1** [comment]
успішно перетестовано
