### ISSUE TITLE
Уточніть будь-ласка, де саме в кабінеті Замовника, потрібно зареєструвати контракт, пропозицію-переможця тендера?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#97]
У тестовому сценарії: http://ppr.org.ua/files/TestScripts_v1.00_Phase2.pdf,
ДЕНЬ 4, 140 – Реєстрація контракту, ст.9,
зазначено, що в кабінеті Замовника, потрібно вибрати пропозицію-переможця, і виконати реєстрацію контракту. Проте, на даний момент такої можливості немає.

**Comment by S-Shevchenko** [comment]
Після визначення Замовником Переможця, на сторінці відповідного тендеру з’являється кнопка "Контракт" . Натиснувши на дану кнопку відкриється вікно, в якому Замовник додає договір та натискає "підписати".  
![image](https://cloud.githubusercontent.com/assets/10655287/6284165/ef9a6986-b8f5-11e4-8b42-17ea9d657cd9.png)

**Comment by lerich** [comment]
Закриваю.
