### ISSUE TITLE
Newtend: Проблеми з документами. Існує можливість завантажити зайві документи до аукціону

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#974]
http://ea-trunk.newtend.com/

**Передумова:**
- Зайти як організатор (ліквідатор)
- Створити аукціон (приклад майно)

**Відтворення:**
1) Перейти у розділ аукціону "Документи"
2) Натиснути кнопку "Завантажити документ"
3) У вікні "Завантажте документ", яке з'явилось, кликнути на випадаючий список "Тип документу"
4) Переглянути список можливих документів для завантаження

О**чікуваний результат:** перелік доступних до завантаження документів  має відповідати затвердженним змінам -https://docs.google.com/document/d/1RDuqCp3hMmKCE6K0SSV4V8mXHBndChQUo6DchHQaR7w/edit

**Фактичний результат:** можливо завантажити документи яких не має бути:
- Повідомлення про аукціон
- Критерії оцінки
- Пояснення до питань заданих учасниками
- Кваліфікаційні критеріії 

![default](https://cloud.githubusercontent.com/assets/13050207/21261941/2caf0978-c397-11e6-92dd-8f97a6738d10.png)
![default](https://cloud.githubusercontent.com/assets/13050207/21262623/0fbd3ade-c39b-11e6-804c-55269097b090.png)

**Comment by SlaOne** [comment]
получается, что необходимо внести изменения в Техническую документацию, по которой был написан функционал - http://dgf.api-docs.openprocurement.org/uk/latest/standard/document.html
исправление - взяли в работу

**Comment by SlaOne** [comment]
исправили

**Comment by SoftserveQC1** [comment]
Дефект виправлений
