### ISSUE TITLE
DTO: Відсутність назви у полів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#975]
DTO: Відсутність назви у полів

1. Залогуватися як організатор аукціонів
2. Перейти до створення аукціону
3. Перевірити правильність назв полів

Очікуваний результат:
Поля мають правильні назви на українській мові

Отриманий результат:
Частина нових полів на мають назви: "?:tender form tenderAttempts"

**Comment by SoftserveQC1** [comment]
Скріншот багу при створенні аукціону:
![capture5](https://cloud.githubusercontent.com/assets/13050207/21519587/135b23e4-ccf7-11e6-89f6-53287618ed7b.JPG)

Скріншот багу при перегляду створеного аукціону:
![capture6](https://cloud.githubusercontent.com/assets/13050207/21519593/2a39f50e-ccf7-11e6-80cd-e13a516e53e0.JPG)

**Comment by PaulBoroday** [comment]
Готово
