### ISSUE TITLE
OpenTender: некорректна назва полів

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#976]
майданчик: test-eauction.open-tender.com.ua/
користувач: buyer@ustudio.com.ua

Сценарій:
1. Авторизуватись на майданчику
2. Перейти до "Мої аукціони"
3. Створити "Новий аукціон"

Очікувано: поле "Порядок ознайомлення з майном/активом у кімнаті даних" присутнє і має коректну назву
Актуально: Поле винесено в окремий розділ "Ознайомчий актив" та має назву "Access details"

**Comment by oleg4646** [comment]
Заменил.

**Comment by SoftserveQC1** [comment]
прохання виправити назву полів при створенні аукціону та в існуючому аукціоні:

Для майна - Порядок ознайомлення з майном 
Для активу - Порядок ознайомлення з активом у кімнаті даних

![image](https://cloud.githubusercontent.com/assets/13050207/21312868/4198f0f8-c5f7-11e6-956c-ce2c0530c3b5.png)
