### ISSUE TITLE
DTO: Кнопка із знаком запитання не вибликає підказки

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#977]
DTO: Кнопка із знаком запитання не вибликає підказки

1. Зайти на майданчик як організатор
2. Перейти до створення аукціону
3. Ввести в текстове/числове поле не валідні дані
4. Після появи знаку питання написати на нього

Очікуваний результат:
Після нажаття на кнопку відповідний блок з допомогою не появляється

Отриманий результат:
Після натискання на кнопку із занком запитання відповідне меню із поясненням має появитися

**Comment by w-be** [comment]
Дублікат: https://github.com/openprocurement/frontend/issues/752
