### ISSUE TITLE
DTO: До "?:upload link title" неможливо додати лінку: "?:upload link url"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#978]
DTO: До "?:upload link title" неможливо додати лінку: "?:upload link url"

1. Зайти на майданчик як організатор
2. Створити аукціон
3. В документах додати: ?:tender form add link
4. В поле "?:upload link url" внести значення www.google.com

Очікуваний результат:
Після нажаття клавіші лінка успішно збережена до аукціону

Отриманий результат:
Після нажаття кнопки "?:upload link send" знизу появляється помилка: "Будь ласка, введіть правильне значення."

**Comment by kvskkvsk** [comment]
www.google.com существует на протоколе https, если в браузере вставить www.google.com, то адрес изменяется
Все это система проверяет, а именно на наличие ответа 200 при попытке открыть указанную ссылку

**Comment by SoftserveQC1** [comment]
При спробі додоати адресу https://www.google.com помилка також появляється:

**Comment by SoftserveQC1** [comment]
![capture3](https://cloud.githubusercontent.com/assets/13050207/21312540/5137b97e-c5f5-11e6-95e2-7b6db8c7b50f.JPG)

**Comment by kvskkvsk** [comment]
Введите в адресную строку  https://www.google.com и затем сравните то, что у вас появиться в адресной строке
Второе ограничение это: ожидание ответа 200 составляет не более 5 сек.

**Comment by SoftserveQC1** [comment]
Багу можна надати низький рівень важливості при додаванні лінки  https://www.google.com.ua валідація відбувається і лінку можна додати.
Також для користувачів необхідно надати підказки для зручності користування даним функціонал та вказати причини неможливості завантаження тієї чи іншої лінки.

**Comment by PaulBoroday** [comment]
Додано http://prntscr.com/dre2gg
