### ISSUE TITLE
UACE: Є можливість поставити "Розмір мінімального кроку аукціону" менше 1%

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#979]
**Кроки відтворення:**
1. Зайти на сайт http://test-eauction.uace.com.ua/
2. Створити новий аукціон
3. Ввести дані у поле "Початкова ціна продажу лоту" (наприклад "1000")
4. Ввесте дані у поле "Розмір мінімального кроку аукціону". Мінімальний крок має бути менше ніж 1% від Початкової ціни продажу лоту (наприклад "1")
5. Побачити автоматично заповнені дані у полі "Розмір мінімального кроку аукціону, %"
6. Видалити дані з поля "Розмір мінімального кроку аукціону, %"
7. Заповнити інші обов'язкові поля, опублікувати аукціон

**Очікуваний результат:**
Дані у поле "Розмір мінімального кроку аукціону" мають бути помічені як невалідні. Аукціон не має бути опублікованим.

**Актуальний результат:**
Дані у поле "Розмір мінімального кроку аукціону" проходять як валідні. Аукціон успішно публікується.

**Comment by oleg4646** [comment]
Вы можете показать место в документации, где описаны Ваши требования?

**Comment by w-be** [comment]
https://docs.google.com/document/d/14Yav0iwWOHd-6NeZ_P4fHlNT8e22Hlo24RVz6rSed4M/edit
9-та сторінка, 9-те поле
"minimalStep:amount
Мінімальний крок пiдвищення ціни: не менше 1% від стартової вартості Лоту"

**Comment by oleg4646** [comment]
Как я понял, замечание в том, что поле "Розмір мінімального кроку аукціону, %" не обязательное. Я поэтому и попросил привести место в документации, где написано, что оно обязательно должно быть заполнено. Я такого не нашел.

**Comment by SoftserveQC1** [comment]
Я поправил описание дефекта. Изначально он был написан на конкретную реализацию, а не на суть ошибки.

**Comment by oleg4646** [comment]
Добавил валидатор.

**Comment by SoftserveQC1** [comment]
Перевірено, проблему виправлено.
