### ISSUE TITLE
E-Auction: Відсутня валідація поля "Номер лоту ФГВ:"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#984]
**Лінк:** http://e-auction.pro/#/

**Кроки:** (Виконуються ліквідатором)
1. Відкрити сторінку створення нового Аукціону
2. Заповнити усі поля валідними даними крім поля "Номер лоту ФГВ:" (лишити порожнім) 
3. Натиснути на кнопку "Створити оголошення з продажу активу"

**Фактично:** Валідація поля "Номер лоту ФГВ відсутня, аукціон успішно створений. 

**Очікувано:** Помилка під час створення аукціону

**Comment by SergeDmitriev** [comment]
Поле сделано обязательным к заполнению

**Comment by SoftserveQC1** [comment]
Перетестовано успішно
