### ISSUE TITLE
E-Auction: Відсутня валідація поля "Номер рішення в ФГВ:"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#985]
**Лінк:** http://e-auction.pro/#/

**Кроки:** (Виконуються ліквідатором)
1. Відкрити сторінку створення нового Аукціону
2. Заповнити усі поля валідними даними крім поля "Номер рішення в ФГВ:" (лишити порожнім) 
3. Натиснути на кнопку "Створити оголошення з продажу активу"

**Фактично:** Валідація поля "Номер рішення в ФГВ відсутня, аукціон успішно створений.
 
**Очікувано:** Помилка під час створення аукціону

**Comment by SergeDmitriev** [comment]
Поле сделано обязательным к заполнению

**Comment by SoftserveQC1** [comment]
Перетестовано успішно
