### ISSUE TITLE
E-Auction: Створення аукціону: зависання сторінки якщо незаповнене поле "Дата прийняття рішення в ФГВ:"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#986]
**Лінк:** http://e-auction.pro/#/

**Кроки:** (Виконуються ліквідатором)
1. Відкрити сторінку створення нового Аукціону
2. Заповнити усі поля валідними даними крім поля "Дата прийняття рішення в ФГВ:" (лишити порожнім) 
3. Натиснути на кнопку "Створити оголошення з продажу активу"

**Фактично:** Внизу сторінки виводиться загальне повідомлення про помилку. Поле "Дата прийняття рішення в ФГВ:" не підсвічується червоним. Сторінка зависає. Для продовження потрібне перезавантаження сторінки, при цьому втрачаються усі ведені дані.

**Очікувано:** Поле "Дата прийняття рішення в ФГВ:" підсвічується червоним. Сторінка не зависає.

**Comment by OlegNekovalev** [comment]
Поле "Дата прийняття рішення в ФГВ:" підсвічується червоним. Сторінка не зависає.
![screenshot_56](https://cloud.githubusercontent.com/assets/23699721/21608255/17062526-d1c4-11e6-9d9a-32fcd97e6353.png)

**Comment by SoftserveQC1** [comment]
перевірено та зачинено
