### ISSUE TITLE
E-Auction: Організатор може опублікувати аукціон без заведення усіх полів. Після публікації є можливість редагувати поля, відмінні від типу "документ" 

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#987]
**Лінк:** http://e-auction.pro/#/
**Подібно до дефекту**: https://github.com/openprocurement/frontend/issues/956 

## **A. Аукціон з продажу активів**

**Кроки:** (Виконуються ліквідатором)

1. Відкрити сторінку створення нового Аукціону (з продажу активів)
2. Заповнити усі поля валідними даними 
3. Натиснути на кнопку "Створити оголошення з продажу активу"

**Фактично:** Під час заповнення полів у п.2. наступні поля відсутні:
* "Посилання на Публічний Паспорт Активу" 
* "Порядок ознайомлення з активом у кімнаті даних"

**Фактично:** Після п.3 Аукціон відразу публікується. Ліквідатор тепер має можливість додати, редагувати або взагалі не добавляти інформацію до полів:
* "Посилання на Публічний Паспорт Активу" 
* "Порядок ознайомлення з активом у кімнаті даних"

4. Як учасник, відкрити аукціон, перевірити поля  "Посилання на Публічний Паспорт Активу" та
"Порядок ознайомлення з активом у кімнаті даних":

**Фактично:** див скріншот нижче 
* Поле "Посилання на Публічний Паспорт Активу" - немає даних
* Поле "Порядок ознайомлення з активом у кімнаті даних" - немає даних
Учасник може робити заявку на участь у такому аукціоні 

**Очікувано**:
* Аукціон не повинен публікуватись без заведення усіх даних 
* У вже створеному аукціоні не можна нічого змінювати чи добавляти крім документів та ілюстрацій.

![3](https://cloud.githubusercontent.com/assets/13050207/21314638/c9648ffc-c600-11e6-806c-695f6e92018c.png)

## В. Аукціон з продажу прав вимоги**

**Кроки:** (Виконуються ліквідатором)

1. Відкрити сторінку створення нового Аукціону (з продажу  прав вимоги)
2. Заповнити усі поля валідними даними 
3. Натиснути на кнопку "Створити оголошення з продажу активу"

**Фактично:** Під час заповнення полів у п.2. наступні поля відсутні:
* "Посилання на Публічний Паспорт Активу" 
* "Порядок ознайомлення з активом у кімнаті даних"
* "Virtual Data Room"

**Фактично:** Після п.3 Аукціон відразу публікується. Ліквідатор тепер має можливість добавляти, редагувати або взагалі не добавляти інформацію до полів:
* "Посилання на Публічний Паспорт Активу" 
* "Порядок ознайомлення з активом у кімнаті даних"
* "Virtual Data Room"

4. Як учасник, відкрити аукціон, перевірити поля  "Посилання на Публічний Паспорт Активу", "Virtual Data Room" та "Порядок ознайомлення з активом у кімнаті даних":

**Фактично:** див скріншот нижче 
* Поле "Посилання на Публічний Паспорт Активу" - немає даних
* Поле "Порядок ознайомлення з активом у кімнаті даних" - немає даних
* "Virtual Data Room" - немає даних
Учасник може робити заявку на участь у такому аукціоні 

**Очікувано**:
* Аукціон не повинен публікуватись без заведення усіх даних 
* У вже створеному аукціоні не можна нічого змінювати чи добавляти крім документів та ілюстрацій.

![2](https://cloud.githubusercontent.com/assets/13050207/21314475/fc368076-c5ff-11e6-8c10-650642f1e7b8.png)

**Comment by oleksandrakulenko** [comment]
Формально це також документи, така поведінка поки є нормальною.
Прохання закрити.
