### ISSUE TITLE
E-Auction: Відсутнє поле "Адреса місцезнаходження майна" або "Адреса місцезнаходження активу" (в залежності від обраної процедури)

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#988]
**Лінк:** http://e-auction.pro/#/

**Кроки:** (Виконуються ліквідатором)
1. Відкрити сторінку створення нового Аукціону
2. Заповнити усі поля валідними даними 
3. Натиснути на кнопку "Створити оголошення з продажу активу"

**Фактично:**
Поле "Адреса місцезнаходження майна" або "Адреса місцезнаходження активу" (в залежності від обраної процедури) відсутнє 

**Очікувано:** Присутність поля "Адреса місцезнаходження майна" або "Адреса місцезнаходження активу" (в залежності від обраної процедури)

**Comment by SergeDmitriev** [comment]
Исправили

**Comment by SoftserveQC1** [comment]
успішно перетестовано
