### ISSUE TITLE
E-auction: поле посилання присутнє як тип документа

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#989]
майданчик: http://e-auction.pro/#
користувач: bankpz_test

Сценарій:
1. Авторизуватись
2. Створити аукціон
3. Відкрити випадаючий список "Тип документів"

Фактично: Посилання на паспорт активу та Віртуальна кімната знаходяться в списку
Очікувано: Посилання на паспорт активу та Віртуальна кімната (Кімната VDR) повинні бути текстовими полями для посилань, доступними при створенні аукціону

**Comment by SergeDmitriev** [comment]
Убрали некорректные докуметны из списка

**Comment by SoftserveQC1** [comment]
успішно перевірено
