### ISSUE TITLE
Чи очікувана поведінка відображення одиниць виміру замовлення на аукціоні - на іншій мові, а ніж при створенні тендера?

### ISSUE THREAD

**Issue by yuliyaSoftserve** [openprocurement/frontend#99]
При створенні тендера ми маємо мождивість обирати одиниці виміру замовлення тільки українською мовою. При розміщенні пропозицій на цей тендер, одиниці виміру замовлення теж відображаються на українській мові. Але при переході на аукціон - одиниці виміру замовлення - відображаються на англійській мові. (Причому що мова, на якій має відбуватися аукціон, вказана як українська)
![amount](https://cloud.githubusercontent.com/assets/10761162/6186644/c32def06-b384-11e4-8368-1f492f9bc96b.png)

**Comment by OksanaPakholok** [comment]
Протестовано, зараз поведінка очікувана. Це питання можна закривати

![ukr_ok](https://cloud.githubusercontent.com/assets/11062040/6410089/4cfa758e-be74-11e4-8b41-52e87b8aa486.png)

Але відрите нове ішю https://github.com/openprocurement/frontend/issues/128
про те що на російські і англійській мові, некоректне відображення.

**Comment by lerich** [comment]
Закриваю.
