### ISSUE TITLE
E-auction: договір NDA додається до майна

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#990]
майданчик: http://e-auction.pro/#/
користувач: bankpz_test

Сценарій:
1. Авторизуватись
2. Створити аукціон для продажу майна
3. Відкрити випадаючий список "Тип документу"

Фактично: договір NDA присутній в списку
Очікувано: договір NDA повинен бути відсутнім або недоступним для вибору

**Comment by OlegNekovalev** [comment]
Тип документу "договір NDA" відсутній для аукціону з продажу майна

**Comment by SoftserveQC1** [comment]
перевірено та зачинено
