### ISSUE TITLE
E-auction: Посилання місця та форми заяв можливо видалити

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#992]
майданчик: http://e-auction.pro/#
користувач: bankpz_test

Сценарій:
1. Відкрити аукціон для редагування
2. знайти посилання Місця та форми заяв...

Фактично: Посилання має кнопки редагування видалення
Очікувано: Посилання не повинно мати кнопки редагування/видалення

**Comment by SergeDmitriev** [comment]
http://e-auction.pro/#/tenderDetailes/4a1c3f6b902744ef9d3ab1a743537d5a
убрали "редактирование/удаление" документа для "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків"

**Comment by SoftserveQC1** [comment]
успішно перетестовано
