### ISSUE TITLE
E-auction: Відсутність переносів у полі "Порядок ознайомлення"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#994]
майданчик: http://e-auction.pro/#
користувач: bankpz_test

Сценарій: 
1. Авторизуватись
2. Створити аукціон
3. Вказати "Порядок ознайомлення..." з декількома переносами тексту
4. Зберегти

Фактично: Після збереження текст у полі відображається однією строкою
Очікувано: Після збереження переноси будуть присутні
![image](https://cloud.githubusercontent.com/assets/13050207/21385412/1cad613a-c777-11e6-8dc9-b4b9926069ef.png)

**Comment by w-be** [comment]
Додай, будь-ласка знымок екрану.

**Comment by SoftserveQC1** [comment]
додано скріншот
