### ISSUE TITLE
E-Auction: Невірне відображення даних з поля "Лоти виставляються"

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#995]
**Лінк:** http://e-auction.pro/#/

## А.
**Кроки:** (Виконуються ліквідатором)
1. Авторизуватись
2. Створити аукціон, при цьому обрати **"1", "2", "3" або "4"** з випадаючого списку "Лоти виставляються" 
3. Як учасник або як ліквідатор, перевірити створений аукціон

**Фактично:** 
* Значення поля "Лоти виставляються:"  відповідно 1, 2, 3 або 4
* Поле "Загальний опис аукціону: містить фразу "Лот виставляється повторно"

**Очікувано:** 
* Значення поля "Лоти виставляються:"  
о "Лот виставляється вперше" для 1 
о "Лот виставляється повторно" для 2, 3, 4
* Поле "Загальний опис аукціону: не має містити фразу "Лот виставляється повторно"

## B.
**Кроки:** (Виконуються ліквідатором)
1. Авторизуватись
2. Створити аукціон, при цьому обрати **"не відомо"** з випадаючого списку "Лоти виставляються" 
3. Як учасник або як ліквідатор, перевірити створений аукціон

**Фактично:**  Поле "Загальний опис аукціону: не містить фразу "Торги проводяться повторно"

**Очікувано:**  Поле "Загальний опис аукціону: має містити фразу "Торги проводяться повторно”

**Comment by SergeDmitriev** [comment]
Исправили кейсы A,Б

**Comment by SoftserveQC1** [comment]
Успішно перетестовано
