### ISSUE TITLE
E-Auction: Під час редагування пропозиції анулюються зміни поля "Сума", якщо до пропозиції додати файл

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#996]
**Лінк:** http://e-auction.pro/#/
**Опис:** Якщо учасник перед початком аукціону захоче одночасно змінити суму своєї пропозиції і додати до пропозиції якийсь файл, є імовірність, що на модерацію буде відправлено тільки додавання файлу, а сума лишиться тою, що була раніше

**Передумови:** Ліквідатор створив аукціон, Учасник зареєстрував пропозицію на суму ХХ, Модератор акцептував пропозицію учасника 

**Кроки:** (Виконуються учасником)
1. Відкрити сторінку Аукціону 
2. Змінити суму своєї пропозиції на суму YY
3. Додати будь-який файл до пропозиції
4. Перевірити поле "Сума"

**Фактично:** Після додавання файлу значення поля "Сума" вернулось до попереднього стану XX
**Очікувано:** Додавання файлу не повинно анульовувати зміни поля "Сума"

**Comment by oleksandrakulenko** [comment]
Баг треба правити 

Кроме отмены должна быть возможность редактировать лот + это должно быть прозрачно для участника. Когда при добавлении файла сумма пропадает, это явно ошибочное поведение.

1. ТЗ https://docs.google.com/document/d/1dKg81cEvc_BZtXg-esvhrLvtKcobpgn1MRLYeNAh0ZA/edit#heading=h.3t3vrzlhhuan
2. Ручные тесты https://docs.google.com/document/d/1Ieh4NC-XhwLbdtA8vxdhLFBdNn-JOY1nzTWsvI9J3h0/edit#heading=h.i3u7jfz1rezh

>До дати закінчення прийому пропозицій, Учасники мають право зняти >пропозицію (видалити), внести зміни в ціновій пропозиції.

>Внести зміни до пропозиції - дії користувача
> Внести наступні зміни в полях Лоту: Початкова цінова пропозиції 
>Натиснути кнопку “Опублікувати”

**Comment by OlegNekovalev** [comment]
Согласно сценариев ручных тестов:
**Внести зміни до пропозиції - дії користувача**
Внести наступні зміни в полях Лоту: Початкова цінова пропозиції
Натиснути кнопку “Опублікувати”
На нашей площадке это реализовано. После нажатия на кнопку “Опублікувати” редактированная ставка отправляется на модерацию (см. screenshot)
![screenshot_55](https://cloud.githubusercontent.com/assets/23699721/21607428/ac18ad6a-d1be-11e6-8f4f-9c35aed21b9a.png)

**Comment by SoftserveQC1** [comment]
перевірено та зачинено
