### ISSUE TITLE
e-auction: неповна локалізація майданчика

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#997]
майданчик: http://e-auction.pro/#
користувач: bankpz_test
передумова: аукціон на редагуванні

Фактично: присутні назва поля Access Details та кнопки Choose File
Очікувано: локалізація повинна бути повною

**Comment by SergeDmitriev** [comment]
Access Details - поле переименуем
Choose File - почему данная ошибка critical? она выполняет свою основную функциональность, интуитивно и так понятно для чего она используется

**Comment by SergeDmitriev** [comment]
http://e-auction.pro/#/tenderDetailes/4a1c3f6b902744ef9d3ab1a743537d5a
поле - Access Details переименовано

**Comment by w-be** [comment]
Баг критичний якраз через "Access Details".

**Comment by SergeDmitriev** [comment]
Теперь поле корректно назвается

**Comment by oleksandrakulenko** [comment]
Про файл не критична, але теж має бути виправлена. Майданчик має бути повністю локалізований. 

> Choose File - почему данная ошибка critical? она выполняет свою основную функциональность, интуитивно и так понятно для чего она используется

**Comment by SergeDmitriev** [comment]
Кнопка загрузки документа - стандартная, и ее название отображается в зависимости от локализации браузера, например если у браузера будет английская локализация - то будет chooseFile, если украинская - то "Оберіть файл". Ранее данная кнопка была в виде (Screenshot_7.jpg), но для прохождения автотестов была заменена на текущюю версию, чтобы не возникало конфликтов при запуске (связано с неправильной работой angular+robotFramework)

**Comment by SergeDmitriev** [comment]
![screenshot_7](https://cloud.githubusercontent.com/assets/16797471/21391605/18241e6a-c795-11e6-95ce-0fc465e9d67e.jpg)

**Comment by oleksandrakulenko** [comment]
Дякую. 

@w-be  Можна закривати.

**Comment by SoftserveQC1** [comment]
Поле Access Details все ще має невірну назву. Прохання вказати встановити назву

Для майна: Порядок ознайомлення з майном
Для прав вимоги: Порядок ознайомлення з активом у кімнаті даних

Ще можливий варіант
Порядок ознайомлення з майном або Порядок ознайомлення з активом у кімнаті даних

**Comment by SergeDmitriev** [comment]
Подскажите пожалуйста что на что нужно изменить?
![screenshot_7](https://cloud.githubusercontent.com/assets/16797471/21394216/718d8d14-c7a0-11e6-902d-819131e7b20e.jpg)

**Comment by SoftserveQC1** [comment]
https://gyazo.com/019da0bd55d32249a10980e1464ca67a
поле назва прибрати. друге поле або лишити без назви, або прибрати виділення назви розділу і призначити його як назву поля.

**Comment by SergeDmitriev** [comment]
Реализовали как на скриншоте
![screenshot_11](https://cloud.githubusercontent.com/assets/16797471/21400161/6fd55224-c7b7-11e6-9b56-8e1b1ffdd78a.jpg)

**Comment by SoftserveQC1** [comment]
Згідно з інформацією, що вказано в попередньому коментарі - поле "Назва" повинно бути відсутнім також

**Comment by SoftserveQC1** [comment]
перевірено та зачинено
