### ISSUE TITLE
E-Auction: неправильне розташування роздільчої лінії

### ISSUE THREAD

**Issue by SoftserveQC1** [openprocurement/frontend#999]
майданчик: http://e-auction.pro/#
користувач: bankpz_test
передумова: існуючий аукціон

Фактично: роздільча лінія відділяє гарантійний внесок від мінімальної ціни
![image](https://cloud.githubusercontent.com/assets/13050207/21321824/22762f92-c61f-11e6-8cac-512af88ea702.png)
Очікувано: Гарантійний внесок відноситься до розділу з ціною

**Comment by w-be** [comment]
Відповідно до Олександра Акуленко: "1. розташування роздільчої лінії ніяк не регламентується
2. розмір гарантійного внеску відноситься не до ціни, а до рішення дирекції Фонду. Відповідно знаходиться у правильному місці"
